//! Action API for nros C API.
//!
//! Actions provide long-running task execution with feedback and cancellation.
//! This module implements both action servers and clients.
//!
//! The action server follows the same metadata-only init → executor registration
//! pattern as subscriptions and services:
//! 1. `nros_action_server_init()` stores metadata (name, type, callbacks)
//! 2. `nros_executor_add_action_server()` creates RMW entities and registers
//!    with the nros-node executor
//! 3. Operation functions delegate through `ActionServerRawHandle`

use core::ffi::{c_char, c_void};
use core::ptr;

use crate::constants::{MAX_ACTION_NAME_LEN, MAX_TYPE_HASH_LEN, MAX_TYPE_NAME_LEN};
use crate::error::*;
use crate::node::{nros_node_state_t, nros_node_t};

// ============================================================================
// Constants
// ============================================================================

// NROS_MAX_CONCURRENT_GOALS is generated by build.rs from env var.
use crate::executor::NROS_MAX_CONCURRENT_GOALS;

// ============================================================================
// Goal Status
// ============================================================================

/// Goal status enumeration.
///
/// Compatible with action_msgs/msg/GoalStatus values.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum nros_goal_status_t {
    /// Goal state is unknown
    NROS_GOAL_STATUS_UNKNOWN = 0,
    /// Goal was accepted and is pending execution
    NROS_GOAL_STATUS_ACCEPTED = 1,
    /// Goal is currently being executed
    NROS_GOAL_STATUS_EXECUTING = 2,
    /// Goal is being canceled
    NROS_GOAL_STATUS_CANCELING = 3,
    /// Goal completed successfully
    NROS_GOAL_STATUS_SUCCEEDED = 4,
    /// Goal was canceled
    NROS_GOAL_STATUS_CANCELED = 5,
    /// Goal was aborted (failed)
    NROS_GOAL_STATUS_ABORTED = 6,
}

/// Goal response codes for goal request handling.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum nros_goal_response_t {
    /// Reject the goal
    NROS_GOAL_REJECT = 0,
    /// Accept the goal and start executing immediately
    NROS_GOAL_ACCEPT_AND_EXECUTE = 1,
    /// Accept the goal but defer execution
    NROS_GOAL_ACCEPT_AND_DEFER = 2,
}

/// Cancel response codes.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum nros_cancel_response_t {
    /// Reject the cancel request
    NROS_CANCEL_REJECT = 0,
    /// Accept the cancel request
    NROS_CANCEL_ACCEPT = 1,
}

// ============================================================================
// Action Type Info
// ============================================================================

/// Action type information.
#[repr(C)]
pub struct nros_action_type_t {
    /// Action type name (e.g., "example_interfaces::action::Fibonacci")
    pub type_name: *const c_char,
    /// Action type hash
    pub type_hash: *const c_char,
    /// Maximum serialized size of goal message
    pub goal_serialized_size_max: usize,
    /// Maximum serialized size of result message
    pub result_serialized_size_max: usize,
    /// Maximum serialized size of feedback message
    pub feedback_serialized_size_max: usize,
}

// ============================================================================
// Goal UUID
// ============================================================================

/// Goal UUID structure (16 bytes).
#[repr(C)]
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct nros_goal_uuid_t {
    /// UUID bytes
    pub uuid: [u8; 16],
}

// ============================================================================
// Goal Handle
// ============================================================================

/// Goal handle structure.
#[repr(C)]
pub struct nros_goal_handle_t {
    /// Goal UUID
    pub uuid: nros_goal_uuid_t,
    /// Current status
    pub status: nros_goal_status_t,
    /// Whether this goal slot is in use
    pub active: bool,
    /// User context pointer for this goal
    pub context: *mut c_void,
    /// Pointer back to the action server (internal)
    server: *mut nros_action_server_t,
}

impl Default for nros_goal_handle_t {
    fn default() -> Self {
        Self {
            uuid: nros_goal_uuid_t::default(),
            status: nros_goal_status_t::NROS_GOAL_STATUS_UNKNOWN,
            active: false,
            context: ptr::null_mut(),
            server: ptr::null_mut(),
        }
    }
}

// ============================================================================
// Callback Types
// ============================================================================

/// Goal request callback type.
pub type nros_goal_callback_t = Option<
    unsafe extern "C" fn(
        goal_uuid: *const nros_goal_uuid_t,
        goal_request: *const u8,
        goal_len: usize,
        context: *mut c_void,
    ) -> nros_goal_response_t,
>;

/// Cancel request callback type.
pub type nros_cancel_callback_t = Option<
    unsafe extern "C" fn(
        goal: *mut nros_goal_handle_t,
        context: *mut c_void,
    ) -> nros_cancel_response_t,
>;

/// Goal accepted callback type.
pub type nros_accepted_callback_t =
    Option<unsafe extern "C" fn(goal: *mut nros_goal_handle_t, context: *mut c_void)>;

/// Feedback callback type (for client).
pub type nros_feedback_callback_t = Option<
    unsafe extern "C" fn(
        goal_uuid: *const nros_goal_uuid_t,
        feedback: *const u8,
        feedback_len: usize,
        context: *mut c_void,
    ),
>;

/// Result callback type (for client).
pub type nros_result_callback_t = Option<
    unsafe extern "C" fn(
        goal_uuid: *const nros_goal_uuid_t,
        status: nros_goal_status_t,
        result: *const u8,
        result_len: usize,
        context: *mut c_void,
    ),
>;

// ============================================================================
// Action Server
// ============================================================================

/// Action server state.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum nros_action_server_state_t {
    /// Not initialized
    NROS_ACTION_SERVER_STATE_UNINITIALIZED = 0,
    /// Initialized and ready
    NROS_ACTION_SERVER_STATE_INITIALIZED = 1,
    /// Shutdown
    NROS_ACTION_SERVER_STATE_SHUTDOWN = 2,
}

/// Action server structure.
#[repr(C)]
pub struct nros_action_server_t {
    /// Current state
    pub state: nros_action_server_state_t,
    /// Action name storage
    pub(crate) action_name: [u8; MAX_ACTION_NAME_LEN],
    /// Action name length
    pub(crate) action_name_len: usize,
    /// Type name storage
    pub(crate) type_name: [u8; MAX_TYPE_NAME_LEN],
    /// Type name length
    pub(crate) type_name_len: usize,
    /// Type hash storage
    pub(crate) type_hash: [u8; MAX_TYPE_HASH_LEN],
    /// Type hash length
    pub(crate) type_hash_len: usize,
    /// Goal callback
    pub(crate) goal_callback: nros_goal_callback_t,
    /// Cancel callback
    pub(crate) cancel_callback: nros_cancel_callback_t,
    /// Accepted callback
    pub(crate) accepted_callback: nros_accepted_callback_t,
    /// User context pointer
    pub(crate) context: *mut c_void,
    /// Goal handles
    goals: [nros_goal_handle_t; NROS_MAX_CONCURRENT_GOALS],
    /// Number of active goals
    active_goal_count: usize,
    /// Pointer to parent node
    node: *const nros_node_t,
    /// Opaque pointer to internal implementation (`Box<ActionServerInternal>`)
    pub(crate) _internal: *mut c_void,
}

impl Default for nros_action_server_t {
    fn default() -> Self {
        Self {
            state: nros_action_server_state_t::NROS_ACTION_SERVER_STATE_UNINITIALIZED,
            action_name: [0u8; MAX_ACTION_NAME_LEN],
            action_name_len: 0,
            type_name: [0u8; MAX_TYPE_NAME_LEN],
            type_name_len: 0,
            type_hash: [0u8; MAX_TYPE_HASH_LEN],
            type_hash_len: 0,
            goal_callback: None,
            cancel_callback: None,
            accepted_callback: None,
            context: ptr::null_mut(),
            goals: [
                nros_goal_handle_t::default(),
                nros_goal_handle_t::default(),
                nros_goal_handle_t::default(),
                nros_goal_handle_t::default(),
            ],
            active_goal_count: 0,
            node: ptr::null(),
            _internal: ptr::null_mut(),
        }
    }
}

// ============================================================================
// Internal implementation (delegates to nros-node executor)
// ============================================================================

/// Internal state created during executor registration.
///
/// Holds the `ActionServerRawHandle` and C callback pointers needed by
/// the goal/cancel trampolines.
#[cfg(feature = "alloc")]
pub(crate) struct ActionServerInternal {
    /// Handle returned by `Executor::add_action_server_raw()`.
    /// `None` until registration completes (set immediately after).
    pub(crate) handle: Option<nros_node::ActionServerRawHandle>,
    /// Pointer to the internal Rust executor (`CExecutor`).
    pub(crate) executor_ptr: *mut c_void,
    /// C goal callback from init.
    pub(crate) c_goal_callback: unsafe extern "C" fn(
        *const nros_goal_uuid_t,
        *const u8,
        usize,
        *mut c_void,
    ) -> nros_goal_response_t,
    /// C cancel callback from init (may be None).
    pub(crate) c_cancel_callback: nros_cancel_callback_t,
    /// C accepted callback from init (may be None).
    pub(crate) c_accepted_callback: nros_accepted_callback_t,
    /// C user context from init.
    pub(crate) c_context: *mut c_void,
    /// Pointer back to the C action server struct.
    pub(crate) server_ptr: *mut nros_action_server_t,
}

/// Goal callback trampoline for nros-node.
///
/// Wraps the C `nros_goal_callback_t` as a `RawGoalCallback`. On acceptance,
/// fills a C-side goal slot and calls the C accepted callback.
#[cfg(feature = "alloc")]
pub(crate) unsafe extern "C" fn goal_callback_trampoline(
    goal_id: *const nros_core::GoalId,
    goal_data: *const u8,
    goal_len: usize,
    context: *mut c_void,
) -> nros_core::GoalResponse {
    let internal = &*(context as *const ActionServerInternal);
    let server = &mut *internal.server_ptr;

    // GoalId and nros_goal_uuid_t are layout-compatible (both [u8; 16])
    let uuid_ptr = goal_id as *const nros_goal_uuid_t;

    // Call the C goal callback
    let c_response =
        (internal.c_goal_callback)(uuid_ptr, goal_data, goal_len, internal.c_context);

    // Map C response to Rust GoalResponse
    let response = match c_response {
        nros_goal_response_t::NROS_GOAL_REJECT => return nros_core::GoalResponse::Reject,
        nros_goal_response_t::NROS_GOAL_ACCEPT_AND_EXECUTE => {
            nros_core::GoalResponse::AcceptAndExecute
        }
        nros_goal_response_t::NROS_GOAL_ACCEPT_AND_DEFER => {
            nros_core::GoalResponse::AcceptAndDefer
        }
    };

    // Goal was accepted — fill a C-side goal slot
    if let Some(slot) = server.goals.iter_mut().find(|g| !g.active) {
        slot.uuid = *uuid_ptr;
        slot.status = match response {
            nros_core::GoalResponse::AcceptAndExecute => {
                nros_goal_status_t::NROS_GOAL_STATUS_EXECUTING
            }
            nros_core::GoalResponse::AcceptAndDefer => {
                nros_goal_status_t::NROS_GOAL_STATUS_ACCEPTED
            }
            _ => nros_goal_status_t::NROS_GOAL_STATUS_UNKNOWN,
        };
        slot.active = true;
        slot.server = internal.server_ptr;
        server.active_goal_count += 1;

        // Call the accepted callback
        if let Some(cb) = internal.c_accepted_callback {
            cb(slot as *mut _, internal.c_context);
        }
    }

    response
}

/// Cancel callback trampoline for nros-node.
///
/// The Rust `RawCancelCallback` receives `(goal_id, status, context)`,
/// while the C `nros_cancel_callback_t` receives `(goal_handle, context)`.
/// This trampoline finds the matching C-side goal slot, updates its status
/// to CANCELING, and calls the C cancel callback.
#[cfg(feature = "alloc")]
pub(crate) unsafe extern "C" fn cancel_callback_trampoline(
    goal_id: *const nros_core::GoalId,
    _status: nros_core::GoalStatus,
    context: *mut c_void,
) -> nros_core::CancelResponse {
    let internal = &*(context as *const ActionServerInternal);
    let server = &mut *internal.server_ptr;

    // Find the C-side goal matching this goal_id
    let goal_id_ref = &*goal_id;
    let goal_slot = server
        .goals
        .iter_mut()
        .find(|g| g.active && g.uuid.uuid == goal_id_ref.uuid);

    match (internal.c_cancel_callback, goal_slot) {
        (Some(cb), Some(goal)) => {
            // Update goal status to canceling before calling the callback
            goal.status = nros_goal_status_t::NROS_GOAL_STATUS_CANCELING;

            let c_response = cb(goal as *mut _, internal.c_context);

            // Map C cancel response to Rust CancelResponse
            // C: REJECT=0, ACCEPT=1
            // Rust: Ok=0 (accepted), Rejected=1
            match c_response {
                nros_cancel_response_t::NROS_CANCEL_ACCEPT => nros_core::CancelResponse::Ok,
                nros_cancel_response_t::NROS_CANCEL_REJECT => {
                    // Revert status since cancel was rejected
                    goal.status = nros_goal_status_t::NROS_GOAL_STATUS_EXECUTING;
                    nros_core::CancelResponse::Rejected
                }
            }
        }
        (None, _) => {
            // No cancel callback — accept by default
            nros_core::CancelResponse::Ok
        }
        (_, None) => {
            // Goal not found in C-side tracking
            nros_core::CancelResponse::UnknownGoal
        }
    }
}

/// Get the `ActionServerInternal` from a server's `_internal` pointer.
#[cfg(feature = "alloc")]
unsafe fn get_internal(
    server: *const nros_action_server_t,
) -> Option<&'static ActionServerInternal> {
    let ptr = (*server)._internal;
    if ptr.is_null() {
        None
    } else {
        Some(&*(ptr as *const ActionServerInternal))
    }
}

// ============================================================================
// Action Server Functions
// ============================================================================

/// Get a zero-initialized action server.
#[unsafe(no_mangle)]
pub extern "C" fn nros_action_server_get_zero_initialized() -> nros_action_server_t {
    nros_action_server_t::default()
}

/// Initialize an action server.
///
/// Stores metadata (name, type, callbacks). RMW entity creation is deferred
/// to `nros_executor_add_action_server()`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn nros_action_server_init(
    server: *mut nros_action_server_t,
    node: *const nros_node_t,
    action_name: *const c_char,
    type_info: *const nros_action_type_t,
    goal_callback: nros_goal_callback_t,
    cancel_callback: nros_cancel_callback_t,
    accepted_callback: nros_accepted_callback_t,
    context: *mut c_void,
) -> nros_ret_t {
    // Validate required arguments
    if server.is_null() || node.is_null() || action_name.is_null() || type_info.is_null() {
        return NROS_RET_INVALID_ARGUMENT;
    }

    if goal_callback.is_none() {
        return NROS_RET_INVALID_ARGUMENT;
    }

    let server = &mut *server;
    let node_ref = &*node;
    let type_info = &*type_info;

    // Check if server is already initialized
    if server.state != nros_action_server_state_t::NROS_ACTION_SERVER_STATE_UNINITIALIZED {
        return NROS_RET_BAD_SEQUENCE;
    }

    // Check if node is initialized
    if node_ref.state != nros_node_state_t::NROS_NODE_STATE_INITIALIZED {
        return NROS_RET_NOT_INIT;
    }

    // Copy action name
    let name_ptr = action_name as *const u8;
    let mut len = 0usize;
    while len < MAX_ACTION_NAME_LEN - 1 {
        let c = *name_ptr.add(len);
        if c == 0 {
            break;
        }
        server.action_name[len] = c;
        len += 1;
    }
    if len == 0 {
        return NROS_RET_INVALID_ARGUMENT;
    }
    server.action_name[len] = 0;
    server.action_name_len = len;

    // Copy type name
    if !type_info.type_name.is_null() {
        let type_ptr = type_info.type_name as *const u8;
        len = 0;
        while len < MAX_TYPE_NAME_LEN - 1 {
            let c = *type_ptr.add(len);
            if c == 0 {
                break;
            }
            server.type_name[len] = c;
            len += 1;
        }
        server.type_name[len] = 0;
        server.type_name_len = len;
    }

    // Copy type hash
    if !type_info.type_hash.is_null() {
        let hash_ptr = type_info.type_hash as *const u8;
        len = 0;
        while len < MAX_TYPE_HASH_LEN - 1 {
            let c = *hash_ptr.add(len);
            if c == 0 {
                break;
            }
            server.type_hash[len] = c;
            len += 1;
        }
        server.type_hash[len] = 0;
        server.type_hash_len = len;
    }

    // Store callbacks and context
    server.goal_callback = goal_callback;
    server.cancel_callback = cancel_callback;
    server.accepted_callback = accepted_callback;
    server.context = context;
    server.node = node;
    server.active_goal_count = 0;

    // Initialize goal handles with pointer back to server
    let server_ptr = server as *mut nros_action_server_t;
    for goal in server.goals.iter_mut() {
        *goal = nros_goal_handle_t::default();
        goal.server = server_ptr;
    }

    // RMW entity creation is deferred to nros_executor_add_action_server()
    server._internal = ptr::null_mut();
    server.state = nros_action_server_state_t::NROS_ACTION_SERVER_STATE_INITIALIZED;

    NROS_RET_OK
}

/// Publish feedback for an executing goal.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn nros_action_publish_feedback(
    goal: *mut nros_goal_handle_t,
    feedback: *const u8,
    feedback_len: usize,
) -> nros_ret_t {
    if goal.is_null() || feedback.is_null() {
        return NROS_RET_INVALID_ARGUMENT;
    }

    let goal = &*goal;

    // Check goal is in executing state
    if goal.status != nros_goal_status_t::NROS_GOAL_STATUS_EXECUTING {
        return NROS_RET_NOT_ALLOWED;
    }

    if !goal.active {
        return NROS_RET_NOT_ALLOWED;
    }

    #[cfg(feature = "alloc")]
    {
        if goal.server.is_null() {
            return NROS_RET_NOT_INIT;
        }
        let internal = match get_internal(goal.server) {
            Some(i) => i,
            None => return NROS_RET_NOT_INIT,
        };
        let handle = match internal.handle {
            Some(h) => h,
            None => return NROS_RET_NOT_INIT,
        };

        let executor = crate::executor::get_executor(internal.executor_ptr);
        let goal_id = nros_core::GoalId {
            uuid: goal.uuid.uuid,
        };
        let data = core::slice::from_raw_parts(feedback, feedback_len);

        match handle.publish_feedback_raw(executor, &goal_id, data) {
            Ok(()) => NROS_RET_OK,
            Err(_) => NROS_RET_ERROR,
        }
    }

    #[cfg(not(feature = "alloc"))]
    NROS_RET_ERROR
}

/// Mark a goal as succeeded with a result.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn nros_action_succeed(
    goal: *mut nros_goal_handle_t,
    result: *const u8,
    result_len: usize,
) -> nros_ret_t {
    if goal.is_null() {
        return NROS_RET_INVALID_ARGUMENT;
    }

    let goal = &mut *goal;

    // Check goal is in executing state
    if goal.status != nros_goal_status_t::NROS_GOAL_STATUS_EXECUTING {
        return NROS_RET_NOT_ALLOWED;
    }

    if !goal.active {
        return NROS_RET_NOT_ALLOWED;
    }

    #[cfg(feature = "alloc")]
    {
        if goal.server.is_null() {
            return NROS_RET_NOT_INIT;
        }
        let internal = match get_internal(goal.server) {
            Some(i) => i,
            None => return NROS_RET_NOT_INIT,
        };
        let handle = match internal.handle {
            Some(h) => h,
            None => return NROS_RET_NOT_INIT,
        };

        let executor = crate::executor::get_executor(internal.executor_ptr);
        let goal_id = nros_core::GoalId {
            uuid: goal.uuid.uuid,
        };
        let result_data = if !result.is_null() {
            core::slice::from_raw_parts(result, result_len)
        } else {
            &[]
        };

        // Delegate to nros-node executor
        handle.complete_goal_raw(
            executor,
            &goal_id,
            nros_core::GoalStatus::Succeeded,
            result_data,
        );

        // Update C-side goal state
        goal.status = nros_goal_status_t::NROS_GOAL_STATUS_SUCCEEDED;
        goal.active = false;
        let server = &mut *goal.server;
        if server.active_goal_count > 0 {
            server.active_goal_count -= 1;
        }

        NROS_RET_OK
    }

    #[cfg(not(feature = "alloc"))]
    NROS_RET_ERROR
}

/// Mark a goal as aborted with an optional result.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn nros_action_abort(
    goal: *mut nros_goal_handle_t,
    result: *const u8,
    result_len: usize,
) -> nros_ret_t {
    if goal.is_null() {
        return NROS_RET_INVALID_ARGUMENT;
    }

    let goal = &mut *goal;

    // Check goal is in executing or canceling state
    if goal.status != nros_goal_status_t::NROS_GOAL_STATUS_EXECUTING
        && goal.status != nros_goal_status_t::NROS_GOAL_STATUS_CANCELING
    {
        return NROS_RET_NOT_ALLOWED;
    }

    if !goal.active {
        return NROS_RET_NOT_ALLOWED;
    }

    #[cfg(feature = "alloc")]
    {
        if goal.server.is_null() {
            return NROS_RET_NOT_INIT;
        }
        let internal = match get_internal(goal.server) {
            Some(i) => i,
            None => return NROS_RET_NOT_INIT,
        };
        let handle = match internal.handle {
            Some(h) => h,
            None => return NROS_RET_NOT_INIT,
        };

        let executor = crate::executor::get_executor(internal.executor_ptr);
        let goal_id = nros_core::GoalId {
            uuid: goal.uuid.uuid,
        };
        let result_data = if !result.is_null() {
            core::slice::from_raw_parts(result, result_len)
        } else {
            &[]
        };

        handle.complete_goal_raw(
            executor,
            &goal_id,
            nros_core::GoalStatus::Aborted,
            result_data,
        );

        goal.status = nros_goal_status_t::NROS_GOAL_STATUS_ABORTED;
        goal.active = false;
        let server = &mut *goal.server;
        if server.active_goal_count > 0 {
            server.active_goal_count -= 1;
        }

        NROS_RET_OK
    }

    #[cfg(not(feature = "alloc"))]
    NROS_RET_ERROR
}

/// Mark a goal as canceled with an optional result.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn nros_action_canceled(
    goal: *mut nros_goal_handle_t,
    result: *const u8,
    result_len: usize,
) -> nros_ret_t {
    if goal.is_null() {
        return NROS_RET_INVALID_ARGUMENT;
    }

    let goal = &mut *goal;

    // Check goal is in canceling state
    if goal.status != nros_goal_status_t::NROS_GOAL_STATUS_CANCELING {
        return NROS_RET_NOT_ALLOWED;
    }

    if !goal.active {
        return NROS_RET_NOT_ALLOWED;
    }

    #[cfg(feature = "alloc")]
    {
        if goal.server.is_null() {
            return NROS_RET_NOT_INIT;
        }
        let internal = match get_internal(goal.server) {
            Some(i) => i,
            None => return NROS_RET_NOT_INIT,
        };
        let handle = match internal.handle {
            Some(h) => h,
            None => return NROS_RET_NOT_INIT,
        };

        let executor = crate::executor::get_executor(internal.executor_ptr);
        let goal_id = nros_core::GoalId {
            uuid: goal.uuid.uuid,
        };
        let result_data = if !result.is_null() {
            core::slice::from_raw_parts(result, result_len)
        } else {
            &[]
        };

        handle.complete_goal_raw(
            executor,
            &goal_id,
            nros_core::GoalStatus::Canceled,
            result_data,
        );

        goal.status = nros_goal_status_t::NROS_GOAL_STATUS_CANCELED;
        goal.active = false;
        let server = &mut *goal.server;
        if server.active_goal_count > 0 {
            server.active_goal_count -= 1;
        }

        NROS_RET_OK
    }

    #[cfg(not(feature = "alloc"))]
    NROS_RET_ERROR
}

/// Execute a goal (transition from accepted to executing).
#[unsafe(no_mangle)]
pub unsafe extern "C" fn nros_action_execute(
    goal: *mut nros_goal_handle_t,
) -> nros_ret_t {
    if goal.is_null() {
        return NROS_RET_INVALID_ARGUMENT;
    }

    let goal = &mut *goal;

    // Check goal is in accepted state
    if goal.status != nros_goal_status_t::NROS_GOAL_STATUS_ACCEPTED {
        return NROS_RET_NOT_ALLOWED;
    }

    if !goal.active {
        return NROS_RET_NOT_ALLOWED;
    }

    // Update nros-node side if registered with executor
    #[cfg(feature = "alloc")]
    if !goal.server.is_null()
        && let Some(internal) = get_internal(goal.server)
        && let Some(handle) = internal.handle
    {
        let executor = crate::executor::get_executor(internal.executor_ptr);
        let goal_id = nros_core::GoalId {
            uuid: goal.uuid.uuid,
        };
        handle.set_goal_status(executor, &goal_id, nros_core::GoalStatus::Executing);
    }

    goal.status = nros_goal_status_t::NROS_GOAL_STATUS_EXECUTING;
    NROS_RET_OK
}

/// Get the number of active goals.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn nros_action_server_get_active_goal_count(
    server: *const nros_action_server_t,
) -> usize {
    if server.is_null() {
        return 0;
    }

    let server = &*server;
    server.active_goal_count
}

/// Finalize an action server.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn nros_action_server_fini(
    server: *mut nros_action_server_t,
) -> nros_ret_t {
    if server.is_null() {
        return NROS_RET_INVALID_ARGUMENT;
    }

    let server = &mut *server;

    if server.state != nros_action_server_state_t::NROS_ACTION_SERVER_STATE_INITIALIZED {
        return NROS_RET_NOT_INIT;
    }

    // Drop the internal implementation
    #[cfg(feature = "alloc")]
    {
        if !server._internal.is_null() {
            let _internal = alloc::boxed::Box::from_raw(
                server._internal as *mut ActionServerInternal,
            );
            // ActionServerInternal is dropped here
        }
    }

    server._internal = ptr::null_mut();

    // Reset all goal handles
    for goal in server.goals.iter_mut() {
        *goal = nros_goal_handle_t::default();
    }

    server.goal_callback = None;
    server.cancel_callback = None;
    server.accepted_callback = None;
    server.context = ptr::null_mut();
    server.node = ptr::null();
    server.active_goal_count = 0;
    server.state = nros_action_server_state_t::NROS_ACTION_SERVER_STATE_SHUTDOWN;

    NROS_RET_OK
}

// ============================================================================
// Action Client
// ============================================================================

/// Action client state.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum nros_action_client_state_t {
    /// Not initialized
    NROS_ACTION_CLIENT_STATE_UNINITIALIZED = 0,
    /// Initialized and ready
    NROS_ACTION_CLIENT_STATE_INITIALIZED = 1,
    /// Shutdown
    NROS_ACTION_CLIENT_STATE_SHUTDOWN = 2,
}

/// Action client structure.
#[repr(C)]
pub struct nros_action_client_t {
    /// Current state
    pub state: nros_action_client_state_t,
    /// Action name storage
    action_name: [u8; MAX_ACTION_NAME_LEN],
    /// Action name length
    action_name_len: usize,
    /// Type name storage
    type_name: [u8; MAX_TYPE_NAME_LEN],
    /// Type name length
    type_name_len: usize,
    /// Type hash storage
    type_hash: [u8; MAX_TYPE_HASH_LEN],
    /// Type hash length
    type_hash_len: usize,
    /// Feedback callback
    feedback_callback: nros_feedback_callback_t,
    /// Result callback
    result_callback: nros_result_callback_t,
    /// User context pointer
    context: *mut c_void,
    /// Pointer to parent node
    node: *const nros_node_t,
    /// Opaque pointer to internal implementation
    _internal: *mut c_void,
}

impl Default for nros_action_client_t {
    fn default() -> Self {
        Self {
            state: nros_action_client_state_t::NROS_ACTION_CLIENT_STATE_UNINITIALIZED,
            action_name: [0u8; MAX_ACTION_NAME_LEN],
            action_name_len: 0,
            type_name: [0u8; MAX_TYPE_NAME_LEN],
            type_name_len: 0,
            type_hash: [0u8; MAX_TYPE_HASH_LEN],
            type_hash_len: 0,
            feedback_callback: None,
            result_callback: None,
            context: ptr::null_mut(),
            node: ptr::null(),
            _internal: ptr::null_mut(),
        }
    }
}

/// Get a zero-initialized action client.
#[unsafe(no_mangle)]
pub extern "C" fn nros_action_client_get_zero_initialized() -> nros_action_client_t {
    nros_action_client_t::default()
}

/// Initialize an action client.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn nros_action_client_init(
    client: *mut nros_action_client_t,
    node: *const nros_node_t,
    action_name: *const c_char,
    type_info: *const nros_action_type_t,
) -> nros_ret_t {
    // Validate required arguments
    if client.is_null() || node.is_null() || action_name.is_null() || type_info.is_null() {
        return NROS_RET_INVALID_ARGUMENT;
    }

    let client = &mut *client;
    let node_ref = &*node;
    let type_info = &*type_info;

    // Check if client is already initialized
    if client.state != nros_action_client_state_t::NROS_ACTION_CLIENT_STATE_UNINITIALIZED {
        return NROS_RET_BAD_SEQUENCE;
    }

    // Check if node is initialized
    if node_ref.state != nros_node_state_t::NROS_NODE_STATE_INITIALIZED {
        return NROS_RET_NOT_INIT;
    }

    // Copy action name
    let name_ptr = action_name as *const u8;
    let mut len = 0usize;
    while len < MAX_ACTION_NAME_LEN - 1 {
        let c = *name_ptr.add(len);
        if c == 0 {
            break;
        }
        client.action_name[len] = c;
        len += 1;
    }
    if len == 0 {
        return NROS_RET_INVALID_ARGUMENT;
    }
    client.action_name[len] = 0;
    client.action_name_len = len;

    // Copy type name
    if !type_info.type_name.is_null() {
        let type_ptr = type_info.type_name as *const u8;
        len = 0;
        while len < MAX_TYPE_NAME_LEN - 1 {
            let c = *type_ptr.add(len);
            if c == 0 {
                break;
            }
            client.type_name[len] = c;
            len += 1;
        }
        client.type_name[len] = 0;
        client.type_name_len = len;
    }

    // Copy type hash
    if !type_info.type_hash.is_null() {
        let hash_ptr = type_info.type_hash as *const u8;
        len = 0;
        while len < MAX_TYPE_HASH_LEN - 1 {
            let c = *hash_ptr.add(len);
            if c == 0 {
                break;
            }
            client.type_hash[len] = c;
            len += 1;
        }
        client.type_hash[len] = 0;
        client.type_hash_len = len;
    }

    // Store node pointer
    client.node = node;

    // Client init is metadata-only (same as server)
    client._internal = ptr::null_mut();
    client.state = nros_action_client_state_t::NROS_ACTION_CLIENT_STATE_INITIALIZED;

    NROS_RET_OK
}

/// Set feedback callback.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn nros_action_client_set_feedback_callback(
    client: *mut nros_action_client_t,
    callback: nros_feedback_callback_t,
    context: *mut c_void,
) -> nros_ret_t {
    if client.is_null() {
        return NROS_RET_INVALID_ARGUMENT;
    }

    let client = &mut *client;
    client.feedback_callback = callback;
    client.context = context;

    NROS_RET_OK
}

/// Set result callback.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn nros_action_client_set_result_callback(
    client: *mut nros_action_client_t,
    callback: nros_result_callback_t,
    context: *mut c_void,
) -> nros_ret_t {
    if client.is_null() {
        return NROS_RET_INVALID_ARGUMENT;
    }

    let client = &mut *client;
    client.result_callback = callback;
    client.context = context;

    NROS_RET_OK
}

/// Send a goal request.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn nros_action_send_goal(
    client: *mut nros_action_client_t,
    goal: *const u8,
    goal_len: usize,
    goal_uuid: *mut nros_goal_uuid_t,
) -> nros_ret_t {
    if client.is_null() || goal.is_null() || goal_uuid.is_null() {
        return NROS_RET_INVALID_ARGUMENT;
    }

    let client = &mut *client;

    if client.state != nros_action_client_state_t::NROS_ACTION_CLIENT_STATE_INITIALIZED {
        return NROS_RET_NOT_INIT;
    }

    #[cfg(feature = "alloc")]
    {
        // Generate a UUID for this goal
        let uuid = &mut *goal_uuid;
        if nros_goal_uuid_generate(uuid) != NROS_RET_OK {
            return NROS_RET_ERROR;
        }

        // Client send_goal not yet wired to executor
        let _data = core::slice::from_raw_parts(goal, goal_len);
        NROS_RET_OK
    }

    #[cfg(not(feature = "alloc"))]
    NROS_RET_ERROR
}

/// Request cancellation of a goal.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn nros_action_cancel_goal(
    client: *mut nros_action_client_t,
    goal_uuid: *const nros_goal_uuid_t,
) -> nros_ret_t {
    if client.is_null() || goal_uuid.is_null() {
        return NROS_RET_INVALID_ARGUMENT;
    }

    let client = &mut *client;

    if client.state != nros_action_client_state_t::NROS_ACTION_CLIENT_STATE_INITIALIZED {
        return NROS_RET_NOT_INIT;
    }

    #[cfg(feature = "alloc")]
    {
        let _uuid = &*goal_uuid;
        NROS_RET_OK
    }

    #[cfg(not(feature = "alloc"))]
    NROS_RET_ERROR
}

/// Request result of a goal (blocking).
#[unsafe(no_mangle)]
pub unsafe extern "C" fn nros_action_get_result(
    client: *mut nros_action_client_t,
    goal_uuid: *const nros_goal_uuid_t,
    status: *mut nros_goal_status_t,
    result: *mut u8,
    result_capacity: usize,
    result_len: *mut usize,
) -> nros_ret_t {
    if client.is_null()
        || goal_uuid.is_null()
        || status.is_null()
        || result.is_null()
        || result_len.is_null()
    {
        return NROS_RET_INVALID_ARGUMENT;
    }

    let client = &mut *client;

    if client.state != nros_action_client_state_t::NROS_ACTION_CLIENT_STATE_INITIALIZED {
        return NROS_RET_NOT_INIT;
    }

    #[cfg(feature = "alloc")]
    {
        let _uuid = &*goal_uuid;
        let _buf = core::slice::from_raw_parts_mut(result, result_capacity);
        NROS_RET_TIMEOUT
    }

    #[cfg(not(feature = "alloc"))]
    NROS_RET_ERROR
}

/// Finalize an action client.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn nros_action_client_fini(
    client: *mut nros_action_client_t,
) -> nros_ret_t {
    if client.is_null() {
        return NROS_RET_INVALID_ARGUMENT;
    }

    let client = &mut *client;

    if client.state != nros_action_client_state_t::NROS_ACTION_CLIENT_STATE_INITIALIZED {
        return NROS_RET_NOT_INIT;
    }

    // Clean up internal resources
    #[cfg(feature = "alloc")]
    {
        if !client._internal.is_null() {
            client._internal = ptr::null_mut();
        }
    }

    client.feedback_callback = None;
    client.result_callback = None;
    client.context = ptr::null_mut();
    client.node = ptr::null();
    client.state = nros_action_client_state_t::NROS_ACTION_CLIENT_STATE_SHUTDOWN;

    NROS_RET_OK
}

// ============================================================================
// Utility Functions
// ============================================================================

/// Generate a new random goal UUID.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn nros_goal_uuid_generate(
    uuid: *mut nros_goal_uuid_t,
) -> nros_ret_t {
    if uuid.is_null() {
        return NROS_RET_INVALID_ARGUMENT;
    }

    let uuid = &mut *uuid;

    #[cfg(feature = "std")]
    {
        use std::time::{SystemTime, UNIX_EPOCH};

        // Simple UUID generation using system time and a counter
        // Not cryptographically secure, but sufficient for goal IDs
        static COUNTER: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(0);

        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default();
        let nanos = now.as_nanos() as u64;
        let count = COUNTER.fetch_add(1, std::sync::atomic::Ordering::Relaxed);

        // Fill UUID with time-based values
        uuid.uuid[0..8].copy_from_slice(&nanos.to_le_bytes());
        uuid.uuid[8..16].copy_from_slice(&count.to_le_bytes());

        // Set version (4) and variant bits for UUID v4-like format
        uuid.uuid[6] = (uuid.uuid[6] & 0x0f) | 0x40;
        uuid.uuid[8] = (uuid.uuid[8] & 0x3f) | 0x80;

        NROS_RET_OK
    }

    #[cfg(not(feature = "std"))]
    {
        // For no_std, use a simple counter-based approach
        static mut COUNTER: u64 = 0;
        COUNTER = COUNTER.wrapping_add(1);

        uuid.uuid = [0u8; 16];
        let counter_bytes = COUNTER.to_le_bytes();
        uuid.uuid[0..8].copy_from_slice(&counter_bytes);

        NROS_RET_OK
    }
}

/// Compare two goal UUIDs.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn nros_goal_uuid_equal(
    a: *const nros_goal_uuid_t,
    b: *const nros_goal_uuid_t,
) -> bool {
    if a.is_null() || b.is_null() {
        return false;
    }

    let a = &*a;
    let b = &*b;

    a.uuid == b.uuid
}

/// Get status name as string.
#[unsafe(no_mangle)]
pub extern "C" fn nros_goal_status_to_string(status: nros_goal_status_t) -> *const c_char {
    match status {
        nros_goal_status_t::NROS_GOAL_STATUS_UNKNOWN => c"UNKNOWN".as_ptr(),
        nros_goal_status_t::NROS_GOAL_STATUS_ACCEPTED => c"ACCEPTED".as_ptr(),
        nros_goal_status_t::NROS_GOAL_STATUS_EXECUTING => c"EXECUTING".as_ptr(),
        nros_goal_status_t::NROS_GOAL_STATUS_CANCELING => c"CANCELING".as_ptr(),
        nros_goal_status_t::NROS_GOAL_STATUS_SUCCEEDED => c"SUCCEEDED".as_ptr(),
        nros_goal_status_t::NROS_GOAL_STATUS_CANCELED => c"CANCELED".as_ptr(),
        nros_goal_status_t::NROS_GOAL_STATUS_ABORTED => c"ABORTED".as_ptr(),
    }
}
