//! Compiler-derived opaque storage sizes for RMW handles.
//!
//! These constants are computed from `core::mem::size_of` at compile time,
//! so they always match the actual Rust type layout. No manual maintenance
//! needed — if the underlying type changes, these adjust automatically.
//!
//! When no RMW backend is enabled (workspace-level `cargo check`), placeholder
//! values are used. The placeholders are never used at runtime — all RMW code
//! is `#[cfg]`-gated.

use core::mem::size_of;

/// Compute the number of u64 units needed to store T with 8-byte alignment.
const fn u64s_for<T>() -> usize {
    size_of::<T>().div_ceil(8)
}

// When an RMW backend is active, compute exact sizes from the actual types.
#[cfg(any(
    feature = "rmw-zenoh",
    feature = "rmw-xrce",
    feature = "rmw-dds",
    feature = "rmw-cffi"
))]
pub const SESSION_OPAQUE_U64S: usize = u64s_for::<nros::internals::RmwSession>();
#[cfg(any(
    feature = "rmw-zenoh",
    feature = "rmw-xrce",
    feature = "rmw-dds",
    feature = "rmw-cffi"
))]
pub const PUBLISHER_OPAQUE_U64S: usize = u64s_for::<nros::internals::RmwPublisher>();
// Phase 82: service client opaque storage no longer holds the RMW
// transport handle (it lives in the executor's arena). Use
// SERVICE_CLIENT_INTERNAL_OPAQUE_U64S (from build.rs) for the C struct
// instead.

// Placeholders for no-RMW workspace builds.
#[cfg(not(any(
    feature = "rmw-zenoh",
    feature = "rmw-xrce",
    feature = "rmw-dds",
    feature = "rmw-cffi"
)))]
pub const SESSION_OPAQUE_U64S: usize = 1;
#[cfg(not(any(
    feature = "rmw-zenoh",
    feature = "rmw-xrce",
    feature = "rmw-dds",
    feature = "rmw-cffi"
)))]
pub const PUBLISHER_OPAQUE_U64S: usize = 1;

// ── Guard Condition ──────────────────────────────────────────────────────

pub const GUARD_HANDLE_OPAQUE_U64S: usize = u64s_for::<nros_node::GuardConditionHandle>();

// ── Action Server / Client ────────────────────────────────────────────
//
// ACTION_SERVER_INTERNAL_OPAQUE_U64S and ACTION_CLIENT_INTERNAL_OPAQUE_U64S
// are defined in `crate::config` (generated by build.rs) as conservative
// upper bounds that hold across all supported target architectures.
//
// Compile-time assertions below verify that the upper bounds are sufficient
// for the actual Rust types. If either assertion fails, increase the
// corresponding formula in build.rs.

#[cfg(any(feature = "rmw-zenoh", feature = "rmw-xrce"))]
const _: () = assert!(
    u64s_for::<crate::action::ActionServerInternal>()
        <= crate::config::ACTION_SERVER_INTERNAL_OPAQUE_U64S,
    "ACTION_SERVER_INTERNAL_OPAQUE_U64S too small — \
     increase action_server_storage_bytes in build.rs"
);

#[cfg(any(feature = "rmw-zenoh", feature = "rmw-xrce"))]
const _: () = assert!(
    u64s_for::<crate::action::ActionClientInternal>()
        <= crate::config::ACTION_CLIENT_INTERNAL_OPAQUE_U64S,
    "ACTION_CLIENT_INTERNAL_OPAQUE_U64S too small — \
     increase action_client formula in build.rs"
);

#[cfg(any(feature = "rmw-zenoh", feature = "rmw-xrce"))]
const _: () = assert!(
    u64s_for::<crate::service::ServiceClientInternal>()
        <= crate::config::SERVICE_CLIENT_INTERNAL_OPAQUE_U64S,
    "SERVICE_CLIENT_INTERNAL_OPAQUE_U64S too small — \
     increase service_client_internal formula in build.rs"
);
