//! Compiler-derived opaque storage sizes for RMW handles.
//!
//! These constants are computed from `core::mem::size_of` at compile time,
//! so they always match the actual Rust type layout. No manual maintenance
//! needed — if the underlying type changes, these adjust automatically.
//!
//! When no RMW backend is enabled (workspace-level `cargo check`), placeholder
//! values are used. The placeholders are never used at runtime — all RMW code
//! is `#[cfg]`-gated.

use core::mem::size_of;

/// Compute the number of u64 units needed to store T with 8-byte alignment.
const fn u64s_for<T>() -> usize {
    size_of::<T>().div_ceil(8)
}

// When an RMW backend is active, compute exact sizes from the actual types.
#[cfg(any(
    feature = "rmw-zenoh",
    feature = "rmw-xrce",
    feature = "rmw-dds",
    feature = "rmw-cffi"
))]
pub const SESSION_OPAQUE_U64S: usize = u64s_for::<nros::internals::RmwSession>();
#[cfg(any(
    feature = "rmw-zenoh",
    feature = "rmw-xrce",
    feature = "rmw-dds",
    feature = "rmw-cffi"
))]
pub const PUBLISHER_OPAQUE_U64S: usize = u64s_for::<nros::internals::RmwPublisher>();
// Phase 82: service client opaque storage no longer holds the RMW
// transport handle (it lives in the executor's arena). Use
// SERVICE_CLIENT_INTERNAL_OPAQUE_U64S (from build.rs) for the C struct
// instead.

// Placeholders for no-RMW workspace builds.
#[cfg(not(any(
    feature = "rmw-zenoh",
    feature = "rmw-xrce",
    feature = "rmw-dds",
    feature = "rmw-cffi"
)))]
pub const SESSION_OPAQUE_U64S: usize = 1;
#[cfg(not(any(
    feature = "rmw-zenoh",
    feature = "rmw-xrce",
    feature = "rmw-dds",
    feature = "rmw-cffi"
)))]
pub const PUBLISHER_OPAQUE_U64S: usize = 1;

// ── Guard Condition ──────────────────────────────────────────────────────

pub const GUARD_HANDLE_OPAQUE_U64S: usize = u64s_for::<nros_node::GuardConditionHandle>();

// ── Lifecycle (no RMW dependency) ────────────────────────────────────────
//
// Phase 87: `NROS_LIFECYCLE_CTX_OPAQUE_U64S` is now derived from
// `size_of::<LifecyclePollingNodeCtx>()` directly (see `constants.rs`),
// so the previous "upper bound" assertion is trivially true and has
// been removed. The C-side `NROS_LIFECYCLE_CTX_SIZE` macro lives in
// `nros_config_generated.h`.

// ── Action Server ────────────────────────────────────────────────────
//
// ACTION_SERVER_INTERNAL_OPAQUE_U64S is defined in `crate::config`
// (generated by build.rs) as a conservative upper bound that holds
// across all supported target architectures. The compile-time assertion
// below verifies that the upper bound is sufficient for the actual Rust
// type. If it fails, increase `action_server_storage_bytes` in build.rs.
//
// Phase 87.5: `ActionClientInternal`, `ServiceClientInternal`, and
// `ServiceServerInternal` are now `#[repr(C)]` and embedded directly in
// their outer `nros_*_t` types — no opaque storage, no upper-bound
// assertion needed. `ActionServerInternal` still uses the opaque pattern
// because its `Option<ActionServerRawHandle>` field can't be made
// `#[repr(C)]` without a separate niche-free rewrite.

#[cfg(any(feature = "rmw-zenoh", feature = "rmw-xrce"))]
const _: () = assert!(
    u64s_for::<crate::action::ActionServerInternal>()
        <= crate::config::ACTION_SERVER_INTERNAL_OPAQUE_U64S,
    "ACTION_SERVER_INTERNAL_OPAQUE_U64S too small — \
     increase action_server_storage_bytes in build.rs"
);
