# Licensed under the Apache License, Version 2.0

"""RFC-0087 D2/D3 — the manifest facts a colcon task needs, read in one place.

## What changed in phase-420 W4

This extension used to register 30 entry points keyed
``ros.nros.<lang>.<platform>`` — six Rust platforms, four C, four C++, twice
over for build and test — and recovered the language and the platform by
splitting that string back apart. **No ``package.xml`` in the tree has ever
declared ``nros.<lang>.<platform>``**, so colcon never derived that type and
the whole path was dead (RFC-0087 Motivation defect 2). The only producer of
the spelling was `cargo-nano-ros`'s scaffolder, and W4 moves that too.

RFC-0087 D2 replaces it with two keys, ``ros.nros_cargo`` and
``ros.nros_cmake``, and no new key per platform. That deletes the string the
two facts used to be smuggled in, so each has to come from where it actually
lives:

* **Which build system builds this?** — ``<build_type>`` itself, which is the
  field's whole job. ``nros_cargo`` means cargo, ``nros_cmake`` means CMake.
  This is strictly better than the old ``lang`` token: W3 measured 19 *Rust*
  packages that are CMake-rooted (the Zephyr and ThreadX leaves, where west
  drives the build and the crate is a staticlib CMake imports), and
  ``lang == "rust"`` would have routed every one of them to ``cargo build``.

* **Which platform?** — the board the package's own ``system.toml`` names
  (``[image.<id>] board``, RFC-0098 D3), whose deploy token ``nros ws
  leaf-system`` derives through the board catalog. That verb is the ONE reader
  `find_package(nano_ros)` also asks, so this module is the same rule for the
  colcon path, not a second one. (Until phase-445 W3b the platform was the
  ``<export><nano_ros deploy=…/></export>`` tuple; it is retired, and a
  manifest still carrying it is refused, as both package.xml readers refuse
  it.)

**The language is not recoverable, and is not faked.** ``nros_cmake`` says
CMake; it does not say C, C++ or Rust-imported-by-CMake, and no manifest tag
declares that. It turns out nothing needed it: `_build_cmake` never read the
old ``lang`` argument, and the augmentation's ``_needs_c`` / ``_needs_cpp``
flags were written and never read — C/C++ interface bindings are generated by
CMake's ``nano_ros_generate_interfaces()``, as `task/nros/build.py` says. The
one load-bearing question, "does this workspace need Rust bindings generated?",
is answered from evidence instead: a ``nros_cargo`` package always does, and a
``nros_cmake`` package does when it carries a ``Cargo.toml``.

## Why catkin_pkg and not a fresh XML parse

`colcon_ros` has already parsed and cached every ``package.xml`` in the
workspace by the time a task runs, comments stripped, conditions evaluated.
Re-parsing here would be a second reader of one rule, which is the shape that
produced both reader bugs RFC-0087's Motivation lists.
"""

from pathlib import Path

# `<build_type>` → which build system runs. The two canonical RFC-0087 D2
# spellings, prefixed the way colcon derives a package type (`ros.` + the
# build type). Legacy spellings are deliberately absent: `ament_cargo` and
# `ament_cmake` belong to colcon's own ament tasks and to interface packages,
# and claiming them here is the false claim D2 exists to end.
BUILD_PATH_BY_TYPE = {
    "ros.nros_cargo": "cargo",
    "ros.nros_cmake": "cmake",
}

# `deploy` absent means the host build, the identical rule
# `_nros_deploy_to_platform` applies in cmake/NanoRosPackageXml.cmake
# (`deploy STREQUAL ""` → the host axis). It is not a guess standing in for a
# missing fact: a package that requests no cross-compilation is asking for the
# host, and colcon builds into a host prefix by construction.
DEFAULT_DEPLOY = "native"


def is_nros_type(pkg_type):
    """Is this a package this extension owns?

    >>> is_nros_type('ros.nros_cargo')
    True
    >>> is_nros_type('ros.ament_cmake')
    False
    """
    return pkg_type in BUILD_PATH_BY_TYPE


def build_path(pkg_type):
    """Resolve a colcon package type to ``'cargo'`` or ``'cmake'``.

    >>> build_path('ros.nros_cargo')
    'cargo'
    >>> build_path('ros.nros_cmake')
    'cmake'
    """
    try:
        return BUILD_PATH_BY_TYPE[pkg_type]
    except KeyError:
        raise ValueError(
            f"Not a nano-ros build type: '{pkg_type}'. Expected one of "
            f"{', '.join(sorted(BUILD_PATH_BY_TYPE))} — RFC-0087 D2."
        ) from None


def nano_ros_export(pkg_path):
    """Attributes of the ``<export><nano_ros …/></export>`` tag, or ``{}``.

    Reads the manifest colcon_ros already parsed and cached for this path.
    """
    from colcon_ros.package_identification.ros import get_package_with_build_type

    pkg, _ = get_package_with_build_type(str(pkg_path))
    if pkg is None:
        return {}
    attributes = {}
    for export in pkg.exports:
        if export.tagname == "nano_ros":
            attributes.update(export.attributes)
    return attributes


def leaf_system(pkg_path):
    """``nros ws leaf-system <pkg_path>`` as a ``{KEY: VALUE}`` dict.

    The CLI is the one reader of a leaf's ``system.toml`` (RFC-0098 D3); a
    second parser here would be the drift RFC-0087 D2 built its shared table to
    prevent. Resolved by ``$NROS_CLI``, else ``nros`` on PATH.
    """
    import os
    import shutil
    import subprocess

    nros = os.environ.get("NROS_CLI") or shutil.which("nros")
    if not nros:
        raise RuntimeError(
            f"{pkg_path}/system.toml names this package's board, and reading it "
            "needs the `nros` CLI — put it on PATH (source the nano-ros "
            "activate.sh) or set NROS_CLI."
        )
    proc = subprocess.run(
        [nros, "ws", "leaf-system", str(pkg_path)],
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        raise RuntimeError(f"nros ws leaf-system {pkg_path}: {proc.stderr.strip()}")
    rows = {}
    for line in proc.stdout.splitlines():
        key, sep, value = line.partition("=")
        if sep:
            rows[key] = value
    return rows


def deploy(pkg_path):
    """The platform this package deploys to.

    From the board its ``system.toml`` names (``NROS_LEAF_DEPLOY`` of ``nros
    ws leaf-system``); a package with no ``system.toml`` requests no
    cross-compilation and is the host build, ``DEFAULT_DEPLOY``. A leftover
    ``<nano_ros deploy=…/>`` tuple is REFUSED (phase-445 W3b) — reading it as
    the host would build a freertos package for Linux with no diagnostic.
    """
    retired = nano_ros_export(pkg_path)
    if retired:
        raise ValueError(
            f"{pkg_path}/package.xml: the <nano_ros "
            + " ".join(f'{k}="{v}"' for k, v in sorted(retired.items()))
            + "/> element is retired (RFC-0098 D3/D5, phase-445) — state the "
            "deployment in a system.toml beside the package (`[image.<id>] "
            "board`, `[system] rmw`) and delete the element."
        )
    if not (Path(pkg_path) / "system.toml").is_file():
        return DEFAULT_DEPLOY
    return leaf_system(pkg_path).get("NROS_LEAF_DEPLOY") or DEFAULT_DEPLOY


def needs_rust_bindings(pkg_type, pkg_path):
    """Does this package consume generated Rust message bindings?

    ``nros_cargo`` is cargo-rooted, so always. ``nros_cmake`` is CMake-rooted
    and usually C or C++, whose bindings CMake generates itself — but the 19
    Zephyr/ThreadX Rust leaves W3 measured are `nros_cmake` packages that
    import a crate, and a `Cargo.toml` beside the manifest is what says so.
    """
    if build_path(pkg_type) == "cargo":
        return True
    return (Path(pkg_path) / "Cargo.toml").is_file()
