#!/usr/bin/env bash
# Phase 157.A — generate Kconfig + Make.defs + Makefile wrappers
# for every NuttX C/C++ example. Idempotent.

set -e

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

declare -A DESCRIPTIONS=(
  [talker]='Publishes std_msgs/msg/Int32 on /chatter via zenoh-pico.'
  [listener]='Subscribes to std_msgs/msg/Int32 on /chatter and prints each message.'
  [service-server]='Hosts an example_interfaces/srv/AddTwoInts service on /add_two_ints.'
  [service-client]='Calls example_interfaces/srv/AddTwoInts on /add_two_ints and prints the result.'
  [action-server]='Hosts an example_interfaces/action/Fibonacci action on /fibonacci.'
  [action-client]='Sends an example_interfaces/action/Fibonacci goal on /fibonacci and streams feedback.'
)

upper_underscore() {
  echo "$1" | tr '[:lower:]-' '[:upper:]_'
}

gen_kconfig() {
  local example="$1" lang="$2" config_sym="$3"
  local depends desc
  if [ "$lang" = "c" ]; then
    depends='NROS && NROS_C_API'
  else
    depends='NROS && NROS_CPP_API'
  fi
  desc="${DESCRIPTIONS[$example]}"
  cat <<EOF
# Phase 157 — NuttX external-app Kconfig for the ${lang^^} ${example} example.
# Sourced from \`integrations/nuttx/Kconfig\` via osource glob.

config ${config_sym}
    tristate "nano-ros: ${lang^^} ${example} (zenoh)"
    default n
    depends on ${depends}
    ---help---
        ${desc}
        Built-in command name: \`nuttx_${lang}_$(echo "$example" | tr - _)\`.
EOF
}

gen_make_defs() {
  local example="$1" lang="$2" config_sym="$3"
  cat <<EOF
# Phase 157 — NuttX external-app Make.defs for the ${lang^^} ${example} example.
# Discovered by NuttX's apps/Makefile via the \`apps/external/*/Make.defs\`
# glob. Sibling \`integrations/nuttx/Make.defs\` exposes nano-ros headers +
# \`libnros_${lang}.a\` via the parent CONFIG_NROS gate.

ifneq (\$(CONFIG_${config_sym}),)
CONFIGURED_APPS += \$(APPDIR)/external/nano-ros-${example}-${lang}
endif
EOF
}

gen_makefile() {
  local example="$1" lang="$2" config_sym="$3"
  local progname mainsrc srcsline
  progname="nuttx_${lang}_$(echo "$example" | tr - _)"
  if [ "$lang" = "c" ]; then
    mainsrc='src/main.c'
    srcsline='CSRCS   = $(wildcard generated/*.c)'
  else
    mainsrc='src/main.cpp'
    srcsline='CXXSRCS = $(wildcard generated/*.cpp)'
  fi
  cat <<EOF
# Phase 157 — NuttX external-app Makefile for the ${lang^^} ${example} example.
#
# Delegates to apps/Application.mk for compile + link; the parent
# integrations/nuttx/Make.defs already put libnros_${lang}.a on
# EXTRA_LIBS and the nano-ros ${lang^^} headers on INCDIR_PREFIX, so this
# file only declares the example's own SRCS + the built-in command
# registration (PROGNAME / PRIORITY / STACKSIZE / MODULE).
#
# Phase 157 — NROS_NUTTX_EXTERNAL_APP=1 flips main.${mainsrc##*.}'s
# NROS_APP_MAIN_REGISTER() auto-detect from REGISTER_VOID (used by
# the Phase 144.6 QEMU cmake bring-up via the nros-board-nuttx-
# qemu-arm Rust shim) to REGISTER_NUTTX which emits the
# \`int main(int, char**)\` symbol Application.mk renames to
# \`<PROGNAME>_main\` via \`-Dmain=<PROGNAME>_main\`.

include \$(APPDIR)/Make.defs

# Phase 157.C.16 — NuttX defaults CXXEXT to \`.cxx\`; nano-ros
# examples use the more common \`.cpp\`. Override so
# Application.mk's MAINCXXSRCS filter matches MAINSRC = src/main.cpp.
CXXEXT := .cpp

PROGNAME  = ${progname}
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 16384
MODULE    = \$(CONFIG_${config_sym})

CFLAGS   += -DNROS_NUTTX_EXTERNAL_APP=1
CXXFLAGS += -DNROS_NUTTX_EXTERNAL_APP=1

# Phase 157.C.15 — each example defines \`int nros_app_main(int,
# char**)\` with external linkage. When the kernel links all 12
# example app objects into a single \`nuttx\` ELF, those
# definitions collide ("multiple definition of nros_app_main").
# Rename per-example so each app gets its own symbol; the
# wrapper \`int main()\` (which Application.mk renames to
# \`${progname}_main\` via -Dmain=...) calls the renamed
# nros_app_main from inside its own translation unit.
CFLAGS   += -Dnros_app_main=${progname}_nros_app_main
CXXFLAGS += -Dnros_app_main=${progname}_nros_app_main

# Phase 157.C.9 — per-example app_config.h is generated by
# scripts/nuttx/gen-app-config.py during staging from config.toml
# (cmake's nano_ros_generate_config_header() equivalent). The
# header lands at generated/include/nros/app_config.h relative
# to this Makefile's dir (\$(CURDIR)).
CFLAGS   += \${INCDIR_PREFIX}\$(CURDIR)/generated/include
CXXFLAGS += \${INCDIR_PREFIX}\$(CURDIR)/generated/include

# Phase 157.C.9 + .C.14 — nros-codegen output. scripts/nuttx/
# gen-interfaces.py parses each example's CMakeLists.txt for
# nros_generate_interfaces() / nros_find_interfaces() calls + runs
# the codegen at staging time. C output: generated/c/<pkg>/{msg,srv,
# action}/*.c + top-level *.h umbrella. CPP output:
# generated/cpp/<pkg>/{msg,srv,action}/*.cpp + <pkg>.hpp umbrella.
NROS_GEN_C_DIRS   := \$(wildcard \$(CURDIR)/generated/c/*)
NROS_GEN_CPP_DIRS := \$(wildcard \$(CURDIR)/generated/cpp/*)
CFLAGS   += \$(addprefix \${INCDIR_PREFIX},\$(NROS_GEN_C_DIRS))
CXXFLAGS += \$(addprefix \${INCDIR_PREFIX},\$(NROS_GEN_C_DIRS))
CXXFLAGS += \$(addprefix \${INCDIR_PREFIX},\$(NROS_GEN_CPP_DIRS))
# Phase 157.C.16 — cross-package C codegen includes reference
# sibling packages via \`#include "<pkg>/msg/<file>.h"\`. Add
# generated/c/ + generated/cpp/ parent dirs so the compiler
# finds the nested pkg subdirs.
CFLAGS   += \${INCDIR_PREFIX}\$(CURDIR)/generated/c
CXXFLAGS += \${INCDIR_PREFIX}\$(CURDIR)/generated/c
CXXFLAGS += \${INCDIR_PREFIX}\$(CURDIR)/generated/cpp
NROS_GEN_CSRCS := \$(wildcard \$(CURDIR)/generated/c/*/msg/*.c \\
                              \$(CURDIR)/generated/c/*/srv/*.c \\
                              \$(CURDIR)/generated/c/*/action/*.c)
NROS_GEN_CXXSRCS := \$(wildcard \$(CURDIR)/generated/cpp/*/msg/*.cpp \\
                                \$(CURDIR)/generated/cpp/*/srv/*.cpp \\
                                \$(CURDIR)/generated/cpp/*/action/*.cpp)

EOF
  # Append the right SRCS line based on language. C examples consume the
  # codegen C output only; CPP examples consume both (cpp wrappers
  # reference the c-side typesupport structs).
  if [ "$lang" = "c" ]; then
    cat <<EOF
CSRCS   = \$(wildcard generated/*.c) \$(NROS_GEN_CSRCS)
MAINSRC = ${mainsrc}

include \$(APPDIR)/Application.mk
EOF
  else
    cat <<EOF
CSRCS    = \$(NROS_GEN_CSRCS)
CXXSRCS  = \$(wildcard generated/*.cpp) \$(NROS_GEN_CXXSRCS)
MAINSRC  = ${mainsrc}

# Phase 157.C.16 — per-package cpp FFI staticlibs (one per
# resolved msg/srv/action package). scripts/nuttx/gen-cpp-ffi-
# crates.py cargo-builds them at staging time + emits the lib
# paths into generated/ffi/extra_libs.mk as \`EXTRA_LIBS += <path>\`
# lines. \`-include\` (lowercase) silently no-ops if the fragment
# is missing — handles the case where staging skipped codegen
# (no AMENT_PREFIX_PATH).
-include \$(CURDIR)/generated/ffi/extra_libs.mk

include \$(APPDIR)/Application.mk
EOF
  fi
}

for lang in c cpp; do
  for example in talker listener service-server service-client action-server action-client; do
    config_sym="NROS_EXAMPLE_$(upper_underscore "$example")_${lang^^}"
    dir="$ROOT/examples/qemu-arm-nuttx/$lang/$example"
    [ -d "$dir" ] || { echo "missing dir $dir" >&2; continue; }
    gen_kconfig "$example" "$lang" "$config_sym"  > "$dir/Kconfig"
    gen_make_defs "$example" "$lang" "$config_sym" > "$dir/Make.defs"
    gen_makefile "$example" "$lang" "$config_sym"  > "$dir/Makefile"
    echo "  wrote $dir/{Kconfig,Make.defs,Makefile}"
  done
done

# Flip every main.{c,cpp}'s NROS_APP_MAIN_REGISTER_VOID() to the
# auto-detect macro so NROS_NUTTX_EXTERNAL_APP=1 from the wrapper
# Makefile picks the int-main variant. Idempotent: only rewrites
# files that still have the old explicit VOID call + leaves the
# explanatory comment in place.
for lang in c cpp; do
  for example in talker listener service-server service-client action-server action-client; do
    mainfile="$ROOT/examples/qemu-arm-nuttx/$lang/$example/src/main.${lang/cpp/cpp}"
    [ "$lang" = "c" ] && mainfile="$ROOT/examples/qemu-arm-nuttx/$lang/$example/src/main.c"
    [ "$lang" = "cpp" ] && mainfile="$ROOT/examples/qemu-arm-nuttx/$lang/$example/src/main.cpp"
    [ -f "$mainfile" ] || continue
    if grep -q 'NROS_APP_MAIN_REGISTER_VOID()' "$mainfile"; then
      # Replace bare VOID call with explanatory comment + auto-detect.
      python3 - "$mainfile" <<'PYEOF'
import sys, pathlib
p = pathlib.Path(sys.argv[1])
src = p.read_text()
old = 'NROS_APP_MAIN_REGISTER_VOID()'
new = '''/* Phase 157 — NuttX external-app build (canonical
 * apps/external/<name>/) defines NROS_NUTTX_EXTERNAL_APP=1 via the
 * sibling Makefile so the auto-detect macro picks the
 * `int main(int, char**)` entry that NuttX's Application.mk
 * renames to `<PROGNAME>_main`. QEMU cmake bring-up (Phase 144.6)
 * leaves the define unset and stays on `app_main(void)` for the
 * nros-board-nuttx-qemu-arm Rust shim. */
NROS_APP_MAIN_REGISTER()'''
p.write_text(src.replace(old, new))
PYEOF
      echo "  flipped REGISTER macro in $mainfile"
    fi
  done
done

echo "Done."
