#!/usr/bin/env bash
# Phase 157.C — stage nano-ros integration shell + example external
# apps into a NuttX apps tree so `make` from the configured NuttX
# kernel picks them up via the canonical apps/external/*/Make.defs
# + apps/external/*/Kconfig discovery.
#
# Idempotent. Re-running replaces existing symlinks; never modifies
# files outside $NUTTX_APPS_DIR/external/.
#
# Usage:
#   stage-external-apps.sh <nuttx-apps-dir>
#
# Required: <nuttx-apps-dir> must exist and look like a NuttX apps
# tree (has a `Make.defs` at the top level).

set -euo pipefail

if [ $# -lt 1 ]; then
    echo "usage: $0 <nuttx-apps-dir>" >&2
    exit 2
fi

NUTTX_APPS_DIR="$1"
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
INTEGRATION="$ROOT/integrations/nuttx"

if [ ! -f "$NUTTX_APPS_DIR/Make.defs" ]; then
    echo "error: $NUTTX_APPS_DIR doesn't look like a NuttX apps tree (no Make.defs)" >&2
    exit 1
fi

EXT="$NUTTX_APPS_DIR/external"
mkdir -p "$EXT"

# Top-level apps/external/Make.defs — pulls in every sub-app via
# wildcard glob (Make supports it natively).
install -m 0644 "$INTEGRATION/external-Make.defs.in" "$EXT/Make.defs"

# Integration shell.
ln -sfn "$INTEGRATION" "$EXT/nano-ros"

# Each example as a sibling under apps/external/.
# Phase 157.C.9 — each example's `main.{c,cpp}` includes
# `<nros/app_config.h>`. The cmake path generates it via
# `nano_ros_generate_config_header()`; the NuttX make path
# doesn't run cmake, so we generate the header here at staging
# time from the example's config.toml. The make build's CFLAGS
# additions for `<NANO_ROS_ROOT>/<example>/generated/include`
# (added by the per-example Makefile in 157.A) pick it up.
staged_dirs=()
for lang in c cpp; do
    for example in talker listener service-server service-client action-server action-client; do
        src="$ROOT/examples/qemu-arm-nuttx/$lang/zenoh/$example"
        dst="$EXT/nano-ros-$example-$lang"
        if [ -d "$src" ]; then
            ln -sfn "$src" "$dst"
            staged_dirs+=("nano-ros-$example-$lang")
            # Generate per-example app_config.h.
            if [ -f "$src/config.toml" ]; then
                python3 "$ROOT/scripts/nuttx/gen-app-config.py" \
                    "$src/config.toml" \
                    "$src/generated/include/nros/app_config.h"
            fi
            # Run nros-codegen for message dependencies (parses
            # nros_generate_interfaces() calls from the example's
            # CMakeLists.txt). Skips gracefully if AMENT_PREFIX_PATH
            # is unset / interfaces can't be resolved.
            python3 "$ROOT/scripts/nuttx/gen-interfaces.py" "$src" || true
        else
            echo "  [skip] $src missing"
        fi
    done
done

# Top-level apps/external/Kconfig — enumerate sub-app Kconfigs
# explicitly. NuttX's bundled kconfig-conf doesn't support the
# `osource` glob directive (post-v4.18 kconfig), so generate a
# Kconfig file with explicit source statements for the integration
# shell + every staged example.
{
    echo "# Phase 157.C — apps/external/Kconfig (generated by"
    echo "# scripts/nuttx/stage-external-apps.sh). DO NOT EDIT."
    echo ""
    echo "menu \"External Modules\""
    echo ""
    echo "source \"\$APPSDIR/external/nano-ros/Kconfig\""
    for dir in "${staged_dirs[@]}"; do
        echo "source \"\$APPSDIR/external/$dir/Kconfig\""
    done
    echo ""
    echo "endmenu"
} > "$EXT/Kconfig"

echo "Staged nano-ros external apps under $EXT/"
ls -la "$EXT" | sed 's/^/  /'
