#!/usr/bin/env bash
# Phase 157.C — stage nano-ros integration shell + example external
# apps into a NuttX apps tree so `make` from the configured NuttX
# kernel picks them up via the canonical apps/external/*/Make.defs
# + apps/external/*/Kconfig discovery.
#
# Idempotent. Re-running replaces existing symlinks; never modifies
# files outside $NUTTX_APPS_DIR/external/.
#
# Usage:
#   stage-external-apps.sh <nuttx-apps-dir> [nros-codegen-binary]
#                          [--bringup <bringup-pkg-dir>] [--copy]
#
# Required: <nuttx-apps-dir> must exist and look like a NuttX apps
# tree (has a `Make.defs` at the top level).
#
# Phase 212.H.2 — `--bringup <dir>` additionally stages a Phase 212
# `<system>_bringup` package at `apps/external/<basename(dir)>/` from
# the per-bringup template at `integrations/nuttx/apps-external-template/`.
# The bringup source tree itself is symlinked at
# `apps/external/<bringup>-source` (or copied with `--copy`); the
# template files (Make.defs, Makefile, Kconfig) are written into the
# `apps/external/<bringup>/` shell along with `nros_bringup.mk`
# pinning the workspace + bringup name. Idempotent.

set -euo pipefail

if [ $# -lt 1 ]; then
    echo "usage: $0 <nuttx-apps-dir> [nros-codegen-binary] [--bringup <dir>] [--copy]" >&2
    exit 2
fi

NUTTX_APPS_DIR="$1"; shift
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
INTEGRATION="$ROOT/integrations/nuttx"
TEMPLATE="$INTEGRATION/apps-external-template"
BRINGUP_DIR=""
COPY_MODE="symlink"
CODEGEN_ARG=""

while [ $# -gt 0 ]; do
    case "$1" in
        --bringup)
            BRINGUP_DIR="$2"; shift 2 ;;
        --copy)
            COPY_MODE="copy"; shift ;;
        *)
            if [ -z "$CODEGEN_ARG" ] && [ "${1:0:2}" != "--" ]; then
                CODEGEN_ARG="$1"; shift
            else
                echo "error: unknown arg $1" >&2; exit 2
            fi ;;
    esac
done

# Phase 212.M-F.12 — the legacy Phase 157.C per-example staging loop
# is gone, so the `[nros-codegen-binary]` positional / NROS_CODEGEN /
# NROS_CLI env-vars are no longer consumed here. The argument is
# still parsed (compat with `just nuttx build-fixtures-make` callers
# that pass it) but otherwise ignored.
: "${CODEGEN_ARG:=}"

if [ ! -f "$NUTTX_APPS_DIR/Make.defs" ]; then
    echo "error: $NUTTX_APPS_DIR doesn't look like a NuttX apps tree (no Make.defs)" >&2
    exit 1
fi

EXT="$NUTTX_APPS_DIR/external"
mkdir -p "$EXT"

# Top-level apps/external/Make.defs — pulls in every sub-app via
# wildcard glob (Make supports it natively).
install -m 0644 "$INTEGRATION/external-Make.defs.in" "$EXT/Make.defs"

# Integration shell.
ln -sfn "$INTEGRATION" "$EXT/nano-ros"

# Top-level apps/external/Kconfig — enumerate sub-app Kconfigs
# explicitly. NuttX's bundled kconfig-conf doesn't support the
# `osource` glob directive (post-v4.18 kconfig), so generate a
# Kconfig file with explicit source statements for the integration
# shell. Phase 212.H.2 `--bringup <dir>` (below) appends a bringup
# row when supplied.
#
# Phase 212.M-F.12 — the legacy Phase 157.C nuttx-examples staging
# loop (per-example symlinks under `examples/qemu-arm-nuttx/{c,cpp}/`
# + per-example `gen-app-config.py` / `gen-interfaces.py` /
# `gen-cpp-ffi-crates.py` runs + cpp-FFI staticlib accumulation)
# was retired here. M-F.10.5 deleted the
# `cmake/templates/nros_app_config.h.in` template the per-example
# baker required, and the Phase 212 multi-pkg workspace path
# (`--bringup`) supersedes the per-example shape. Carving the loop
# out also unblocks `phase212_h2_nuttx::nuttx_qemu_arm_2_component_
# bringup_builds` on hosts with NuttX provisioned. The legacy
# `nuttx_make_e2e` smoke + `just nuttx build-fixtures-make` recipe
# remain in-tree pending a follow-up sweep that retires them in
# concert.
{
    echo "# Phase 157.C — apps/external/Kconfig (generated by"
    echo "# scripts/nuttx/stage-external-apps.sh). DO NOT EDIT."
    echo ""
    echo "menu \"External Modules\""
    echo ""
    echo "source \"\$APPSDIR/external/nano-ros/Kconfig\""
    echo ""
    echo "endmenu"
} > "$EXT/Kconfig"

# Phase 212.H.2 — optional `--bringup <dir>` staging. Symlinks (or
# copies) the bringup workspace next to the apps/external/ tree and
# writes the per-bringup template (Make.defs + Makefile + Kconfig +
# nros_bringup.mk pinning) at apps/external/<bringup>/.
if [ -n "$BRINGUP_DIR" ]; then
    if [ ! -d "$BRINGUP_DIR" ]; then
        echo "error: --bringup target $BRINGUP_DIR not found" >&2
        exit 1
    fi
    if [ ! -d "$TEMPLATE" ]; then
        echo "error: integration template missing: $TEMPLATE" >&2
        exit 1
    fi
    bringup_name="$(basename "$BRINGUP_DIR")"
    bringup_workspace="$(cd "$BRINGUP_DIR/.." && pwd)"
    if [ "$(basename "$bringup_workspace")" = "src" ]; then
        bringup_workspace="$(dirname "$bringup_workspace")"
    fi
    shell_dst="$EXT/$bringup_name"
    mkdir -p "$shell_dst"
    for f in Make.defs Makefile Kconfig; do
        install -m 0644 "$TEMPLATE/$f" "$shell_dst/$f"
    done
    {
        echo "# Generated by stage-external-apps.sh (Phase 212.H.2). DO NOT EDIT."
        printf 'NROS_BRINGUP_NAME      := %s\n' "$bringup_name"
        printf 'NROS_BRINGUP_WORKSPACE := %s\n' "$bringup_workspace"
    } > "$shell_dst/nros_bringup.mk"
    src_link="$EXT/${bringup_name}-source"
    if [ "$COPY_MODE" = "copy" ]; then
        rm -rf "$src_link"
        cp -a "$BRINGUP_DIR" "$src_link"
    else
        ln -sfn "$BRINGUP_DIR" "$src_link"
    fi
    # Re-emit apps/external/Kconfig with the bringup row appended.
    {
        cat "$EXT/Kconfig"
        echo ""
        echo "# Phase 212.H.2 bringup (auto-appended)"
        echo "source \"\$APPSDIR/external/$bringup_name/Kconfig\""
    } > "$EXT/Kconfig.tmp"
    mv "$EXT/Kconfig.tmp" "$EXT/Kconfig"
    echo "Staged Phase 212 bringup pkg: $bringup_name → $shell_dst"
fi

echo "Staged nano-ros external apps under $EXT/"
ls -la "$EXT" | sed 's/^/  /'
