// nros-c message type - C header for embedded systems
// Package: geometry_msgs
// Message: PoseArray
// Auto-generated by rosidl-codegen - do not edit

#ifndef GEOMETRY_MSGS_MSG_POSE_ARRAY_H
#define GEOMETRY_MSGS_MSG_POSE_ARRAY_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#include <nros/types.h>

#ifdef __cplusplus
extern "C" {
#endif
#include "geometry_msgs_msg_pose.h"
#include "std_msgs/msg/std_msgs_msg_header.h"

// Constants

/// PoseArray message structure
typedef struct geometry_msgs_msg_pose_array {
    struct std_msgs_msg_header header;
    struct { uint32_t size; struct geometry_msgs_msg_pose data[64]; } poses;
} geometry_msgs_msg_pose_array;

/// Get the ROS type name for PoseArray
static inline const char* geometry_msgs_msg_pose_array_get_type_name(void) {
    return "geometry_msgs::msg::dds_::PoseArray_";
}

/// Get the type hash for PoseArray
static inline const char* geometry_msgs_msg_pose_array_get_type_hash(void) {
    return "TypeHashNotSupported";
}

/// Initialize a PoseArray message to default values
void geometry_msgs_msg_pose_array_init(geometry_msgs_msg_pose_array* msg);

/// Serialize a PoseArray message to CDR format (writes a fresh
/// 4-byte CDR encapsulation header followed by the fields).
/// Returns 0 on success, -1 on error. On success, *serialized_size contains
/// bytes written.
int32_t geometry_msgs_msg_pose_array_serialize(const geometry_msgs_msg_pose_array* msg, uint8_t* buffer, size_t buffer_size, size_t* serialized_size);

/// Deserialize a PoseArray message from CDR format (expects a
/// 4-byte CDR encapsulation header followed by the fields).
/// Returns 0 on success, -1 on error
int32_t geometry_msgs_msg_pose_array_deserialize(geometry_msgs_msg_pose_array* msg, const uint8_t* buffer, size_t buffer_size);

/// Serialize a PoseArray inline into an already-open CDR stream,
/// without emitting its own encapsulation header. Used by parent messages,
/// services, and actions that embed this type as a nested field.
/// - ptr_ref: in/out current write pointer (advanced on success)
/// - end: one-past-last byte of the destination buffer
/// - origin: CDR alignment origin (start of the surrounding encapsulation)
/// Returns 0 on success, -1 on error.
int32_t geometry_msgs_msg_pose_array_serialize_inline(const geometry_msgs_msg_pose_array* msg, uint8_t** ptr_ref, const uint8_t* end, const uint8_t* origin);

/// Deserialize a PoseArray inline from an already-open CDR stream,
/// without consuming an encapsulation header. Parameters mirror the inline
/// serialize variant.
int32_t geometry_msgs_msg_pose_array_deserialize_inline(geometry_msgs_msg_pose_array* msg, const uint8_t** ptr_ref, const uint8_t* end, const uint8_t* origin);

/// Get the nros_message_type_t for this message type
const nros_message_type_t* geometry_msgs_msg_pose_array_get_type_support(void);

/// Typed publish helper. Serializes `msg` into a stack buffer of size
/// `NROS_PUB_BUFFER_SIZE` (override at compile time; default 256) then
/// hands it to nros_publish_raw. nros_ret_t / nros_publisher_t /
/// nros_publish_raw all come in via <nros/types.h> (already included
/// at the top of this header).
#ifndef NROS_PUB_BUFFER_SIZE
#define NROS_PUB_BUFFER_SIZE 256
#endif
static inline nros_ret_t geometry_msgs_msg_pose_array_publish(struct nros_publisher_t* publisher,
                                                   const geometry_msgs_msg_pose_array* msg) {
    uint8_t buf[NROS_PUB_BUFFER_SIZE];
    size_t n = 0;
    int32_t r = geometry_msgs_msg_pose_array_serialize(msg, buf, sizeof(buf), &n);
    if (r != 0) return r;
    return nros_publish_raw(publisher, buf, n);
}

#ifdef __cplusplus
}
#endif

#endif // GEOMETRY_MSGS_MSG_POSE_ARRAY_H