meta:
  version: 1
  inputs:
  - path: launch/freertos_system.launch.xml
    sha256: 1d631ec2fad8328a1f9a18329054e90beb7b1c2f8695d37be310c9e3d1232507
  - path: system.toml
    sha256: 40fde3beb3d12ba296bcfe72891802c2106e7385ae3da17839e2245ba30b7e00
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
structure:
  scopes:
    freertos_system.launch.xml:
      file: freertos_system.launch.xml
  nodes:
    /aux_node:
      scope: freertos_system.launch.xml
      pkg: aux_pkg
      exec: aux
      node_name: aux_node
    /ctrl_node:
      scope: freertos_system.launch.xml
      pkg: ctrl_pkg
      exec: ctrl
      node_name: ctrl_node
    /telem_node:
      scope: freertos_system.launch.xml
      pkg: telem_pkg
      exec: telem
      node_name: telem_node
execution:
  deploy:
    /aux_node:
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
    /ctrl_node:
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
    /telem_node:
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
  tiers:
    high:
      class: real_time
      spin_period_us: 10000
      posix:
        priority: 80
      freertos:
        priority: 5
      zephyr:
        priority: 5
        deadline_us: 10000
      nuttx:
        priority: 110
        budget_us: 5000
        period_us: 10000
    low:
      spin_period_us: 100000
      posix:
        priority: 10
      freertos:
        priority: 2
        core: 0
      zephyr:
        priority: 10
      nuttx:
        priority: 100
    mid:
      spin_period_us: 50000
      posix:
        priority: 40
      freertos:
        priority: 3
  bindings:
    /aux_node/aux: mid
    /ctrl_node/ctrl: high
    /telem_node/telem: low
