meta:
  version: 1
  inputs:
  - path: launch/system.launch.xml
    sha256: 263292326cd1f0847e622d705fefdc259c519b5f4d32240960e7223dd4156c25
  - path: system.toml
    sha256: b8cd55ad5265cfdab7ab1e01cdb2bc8d92ff56085fba4d56620a0310b4bdbc5c
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
structure:
  scopes:
    system.launch.xml:
      file: system.launch.xml
  nodes:
    /ctrl_node:
      scope: system.launch.xml
      pkg: ctrl_pkg
      exec: ctrl
      node_name: ctrl_node
    /telem_node:
      scope: system.launch.xml
      pkg: telem_pkg
      exec: telem
      node_name: telem_node
execution:
  deploy:
    /ctrl_node:
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
    /telem_node:
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
  tiers:
    high:
      class: real_time
      spin_period_us: 10000
      posix:
        priority: 80
      freertos:
        priority: 5
      zephyr:
        priority: 5
        deadline_us: 10000
      nuttx:
        priority: 110
        budget_us: 5000
        period_us: 10000
    low:
      spin_period_us: 100000
      posix:
        priority: 10
      freertos:
        priority: 2
        core: 0
      zephyr:
        priority: 10
      nuttx:
        priority: 100
  bindings:
    /ctrl_node/ctrl: high
    /telem_node/telem: low
