// nros-c message type - C header for embedded systems
// Package: action_msgs
// Message: GoalStatusArray
// Auto-generated by rosidl-codegen - do not edit

#ifndef ACTION_MSGS_MSG_GOAL_STATUS_ARRAY_H
#define ACTION_MSGS_MSG_GOAL_STATUS_ARRAY_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#include <nros/types.h>

#ifdef __cplusplus
extern "C" {
#endif
#include "action_msgs_msg_goal_status.h"

// Constants

/// GoalStatusArray message structure
typedef struct action_msgs_msg_goal_status_array {
    struct { uint32_t size; struct action_msgs_msg_goal_status data[64]; } status_list;
} action_msgs_msg_goal_status_array;

/// Get the ROS type name for GoalStatusArray
static inline const char* action_msgs_msg_goal_status_array_get_type_name(void) {
    return "action_msgs::msg::dds_::GoalStatusArray_";
}

/// Get the type hash for GoalStatusArray
static inline const char* action_msgs_msg_goal_status_array_get_type_hash(void) {
    return "TypeHashNotSupported";
}

/// Initialize a GoalStatusArray message to default values
void action_msgs_msg_goal_status_array_init(action_msgs_msg_goal_status_array* msg);

/// Serialize a GoalStatusArray message to CDR format (writes a fresh
/// 4-byte CDR encapsulation header followed by the fields).
/// Returns 0 on success, -1 on error. On success, *serialized_size contains
/// bytes written.
int32_t action_msgs_msg_goal_status_array_serialize(const action_msgs_msg_goal_status_array* msg, uint8_t* buffer, size_t buffer_size, size_t* serialized_size);

/// Deserialize a GoalStatusArray message from CDR format (expects a
/// 4-byte CDR encapsulation header followed by the fields).
/// Returns 0 on success, -1 on error
int32_t action_msgs_msg_goal_status_array_deserialize(action_msgs_msg_goal_status_array* msg, const uint8_t* buffer, size_t buffer_size);

/// Serialize a GoalStatusArray inline into an already-open CDR stream,
/// without emitting its own encapsulation header. Used by parent messages,
/// services, and actions that embed this type as a nested field.
/// - ptr_ref: in/out current write pointer (advanced on success)
/// - end: one-past-last byte of the destination buffer
/// - origin: CDR alignment origin (start of the surrounding encapsulation)
/// Returns 0 on success, -1 on error.
int32_t action_msgs_msg_goal_status_array_serialize_inline(const action_msgs_msg_goal_status_array* msg, uint8_t** ptr_ref, const uint8_t* end, const uint8_t* origin);

/// Deserialize a GoalStatusArray inline from an already-open CDR stream,
/// without consuming an encapsulation header. Parameters mirror the inline
/// serialize variant.
int32_t action_msgs_msg_goal_status_array_deserialize_inline(action_msgs_msg_goal_status_array* msg, const uint8_t** ptr_ref, const uint8_t* end, const uint8_t* origin);

/// Get the nros_message_type_t for this message type
const nros_message_type_t* action_msgs_msg_goal_status_array_get_type_support(void);

/// Typed publish helper. Serializes `msg` into a stack buffer of size
/// `NROS_PUB_BUFFER_SIZE` (override at compile time; default 256) then
/// hands it to nros_publish_raw. nros_ret_t / nros_publisher_t /
/// nros_publish_raw all come in via <nros/types.h> (already included
/// at the top of this header).
#ifndef NROS_PUB_BUFFER_SIZE
#define NROS_PUB_BUFFER_SIZE 256
#endif
static inline nros_ret_t action_msgs_msg_goal_status_array_publish(struct nros_publisher_t* publisher,
                                                   const action_msgs_msg_goal_status_array* msg) {
    uint8_t buf[NROS_PUB_BUFFER_SIZE];
    size_t n = 0;
    int32_t r = action_msgs_msg_goal_status_array_serialize(msg, buf, sizeof(buf), &n);
    if (r != 0) return r;
    return nros_publish_raw(publisher, buf, n);
}

#ifdef __cplusplus
}
#endif

#endif // ACTION_MSGS_MSG_GOAL_STATUS_ARRAY_H