// nros-c message type - C implementation
// Package: action_msgs
// Message: GoalStatusArray
// Auto-generated by rosidl-codegen - do not edit

#include "action_msgs_msg_goal_status_array.h"
#include <nros/types.h>
#include <nros/cdr.h>
#include <string.h>

// Type support structure
static const nros_message_type_t action_msgs_msg_goal_status_array_type_support = {
    .type_name = "action_msgs::msg::dds_::GoalStatusArray_",
    .type_hash = "TypeHashNotSupported",
    .serialized_size_max = 0,  // Dynamic/unknown
};

const nros_message_type_t* action_msgs_msg_goal_status_array_get_type_support(void) {
    return &action_msgs_msg_goal_status_array_type_support;
}

void action_msgs_msg_goal_status_array_init(action_msgs_msg_goal_status_array* msg) {
    if (msg == NULL) return;
    memset(msg, 0, sizeof(action_msgs_msg_goal_status_array));
}

// =============================================================================
// Inline serialize — writes fields only into an already-open CDR stream.
// Used by parent messages, services, and actions that embed this type as a
// nested field. Does NOT write an encapsulation header. `origin` is the
// CDR alignment origin of the surrounding encapsulation.
// =============================================================================
int32_t action_msgs_msg_goal_status_array_serialize_inline(const action_msgs_msg_goal_status_array* msg, uint8_t** ptr_ref, const uint8_t* end, const uint8_t* origin) {
    if (msg == NULL || ptr_ref == NULL || *ptr_ref == NULL) return -1;
    uint8_t* ptr = *ptr_ref;
    (void)origin; // may be unused for empty structs
    if (nros_cdr_write_u32(&ptr, end, origin, msg->status_list.size) < 0) return -1;
    for (size_t i = 0; i < msg->status_list.size; ++i) {
        if (action_msgs_msg_goal_status_serialize_inline(&msg->status_list.data[i], &ptr, end, origin) < 0) return -1;
    }
    *ptr_ref = ptr;
    return 0;
}

// =============================================================================
// Public serialize — writes a fresh 4-byte CDR encapsulation header then
// delegates to the inline serializer.
// =============================================================================
int32_t action_msgs_msg_goal_status_array_serialize(const action_msgs_msg_goal_status_array* msg, uint8_t* buffer, size_t buffer_size, size_t* serialized_size) {
    if (msg == NULL || buffer == NULL) return -1;

    uint8_t* ptr = buffer;
    const uint8_t* end = buffer + buffer_size;

    // Write CDR header (little-endian, version 1)
    if (ptr + 4 > end) return -1;
    *ptr++ = 0x00; // CDR encapsulation
    *ptr++ = 0x01; // Little-endian
    *ptr++ = 0x00; // Options (unused)
    *ptr++ = 0x00; // Options (unused)
    const uint8_t* origin = ptr; // CDR alignment origin (after header)

    if (action_msgs_msg_goal_status_array_serialize_inline(msg, &ptr, end, origin) < 0) return -1;

    if (serialized_size != NULL) {
        *serialized_size = (size_t)(ptr - buffer);
    }
    return 0;
}

// =============================================================================
// Inline deserialize — reads fields only from an already-open CDR stream.
// =============================================================================
int32_t action_msgs_msg_goal_status_array_deserialize_inline(action_msgs_msg_goal_status_array* msg, const uint8_t** ptr_ref, const uint8_t* end, const uint8_t* origin) {
    if (msg == NULL || ptr_ref == NULL || *ptr_ref == NULL) return -1;
    const uint8_t* ptr = *ptr_ref;
    (void)origin;
    {
        uint32_t len;
        if (nros_cdr_read_u32(&ptr, end, origin, &len) < 0) return -1;
        msg->status_list.size = len;
        if (len > 64) return -1;
        for (size_t i = 0; i < len; ++i) {
            if (action_msgs_msg_goal_status_deserialize_inline(&msg->status_list.data[i], &ptr, end, origin) < 0) return -1;
        }
    }
    *ptr_ref = ptr;
    return 0;
}

// =============================================================================
// Public deserialize — skips the 4-byte CDR encapsulation header then
// delegates to the inline deserializer.
// =============================================================================
int32_t action_msgs_msg_goal_status_array_deserialize(action_msgs_msg_goal_status_array* msg, const uint8_t* buffer, size_t buffer_size) {
    if (msg == NULL || buffer == NULL) return -1;

    const uint8_t* ptr = buffer;
    const uint8_t* end = buffer + buffer_size;

    // Skip CDR header
    if (ptr + 4 > end) return -1;
    ptr += 4;
    const uint8_t* origin = ptr; // CDR alignment origin (after header)

    action_msgs_msg_goal_status_array_init(msg);

    if (action_msgs_msg_goal_status_array_deserialize_inline(msg, &ptr, end, origin) < 0) return -1;
    return 0;
}