meta:
  version: 1
  inputs:
  - path: /home/aeon/repos/nano-ros/examples/workspaces/mixed/src/demo_bringup/launch/multihost.launch.xml
    sha256: d8295df870a2c68e7d2d0608503a8252494f5e2c37b05aedc3b9e2f6ce7222e7
  resolver:
    tool: play_launch
    version: 0.8.2
structure:
  scopes:
    multihost.launch.xml:
      file: multihost.launch.xml
  nodes:
    /heartbeat:
      scope: multihost.launch.xml
      pkg: rust_heartbeat_pkg
      exec: heartbeat
      node_name: heartbeat
    /listener:
      scope: multihost.launch.xml
      pkg: cpp_listener_pkg
      exec: listener
      node_name: listener
    /talker:
      scope: multihost.launch.xml
      pkg: c_talker_pkg
      exec: talker
      node_name: talker
execution:
  deploy:
    /heartbeat:
      host: robot1
    /listener:
      host: robot2
    /talker:
      host: robot1
