meta:
  version: 1
  args:
    host: robot2
  inputs:
  - path: launch/multihost.launch.xml
    sha256: 07806eef107da22d4b3c1b680cafb91a57466befaeb4f534e88fa73559154388
  - path: system.toml
    sha256: fe0419ce31737ffd472b5203f1d05bb93ccb7bc819d838fb346d195c7c5f35be
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
  diagnostics:
  - 'system config: [deploy.robot1] places unknown node ''/talker'' (absent in this variant?)'
  - 'system config: [deploy.robot1] places unknown node ''/heartbeat'' (absent in this variant?)'
structure:
  scopes:
    multihost.launch.xml:
      file: multihost.launch.xml
      args:
        host: robot2
  nodes:
    /listener:
      scope: multihost.launch.xml
      pkg: cpp_listener_pkg
      exec: listener
      node_name: listener
execution:
  deploy:
    /listener:
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: robot2
        kind: self
        target: x86_64-unknown-linux-gnu
