meta:
  version: 1
  inputs:
  - path: launch/service_server.launch.xml
    sha256: d923cb61925eac87edbbc659cb64f0f6fa6e4960c51fcfc4e27ec38591d38416
  - path: system.toml
    sha256: 6c394b12f7d818651edd9468f794882065947af40ea1f06c179116854d2e7791
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
structure:
  scopes:
    service_server.launch.xml:
      file: service_server.launch.xml
  nodes:
    /add_server:
      scope: service_server.launch.xml
      pkg: c_add_server_pkg
      exec: add_server
      node_name: add_server
execution:
  deploy:
    /add_server:
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
