meta:
  version: 1
  inputs:
  - path: launch/service_client.launch.xml
    sha256: fb6add712e0fc8c24d416ca73f0258c9b0d9b6e33cd367be386b9fdecc0365b6
  - path: system.toml
    sha256: 95179f9360ecded0f00b9e253d4478d37fef7267f3d4c329cc233d5ed01c58bb
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
structure:
  scopes:
    service_client.launch.xml:
      file: service_client.launch.xml
  nodes:
    /add_client:
      scope: service_client.launch.xml
      pkg: cpp_add_client_pkg
      exec: add_client
      node_name: add_client
execution:
  deploy:
    /add_client:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
