// nros-cpp: Inline storage size constants
// Freestanding C++ — no exceptions, no STL required
//
// All NROS_CPP_*_STORAGE_SIZE macros are auto-generated by nros-cpp's
// build.rs into `nros_cpp_config_generated.h`. The Rust side has
// compile-time assertions (`size_of::<T>() <= CPP_*_OPAQUE_U64S * 8`)
// that catch any undercount — the generated values are safe upper
// bounds derived from `nros-node::limits` and the target pointer width.

/**
 * @file config.hpp
 * @ingroup grp_support
 * @brief Inline storage-size macros for opaque entity buffers.
 */

#ifndef NROS_CPP_CONFIG_HPP
#define NROS_CPP_CONFIG_HPP

#include "nros/nros_cpp_config_generated.h"

#endif // NROS_CPP_CONFIG_HPP
