/* Phase 159 (Path C) — NuttX fallback. */
#ifndef NROS_CPP_CONFIG_GENERATED_NUTTX_H
#define NROS_CPP_CONFIG_GENERATED_NUTTX_H
#define NROS_CPP_EXECUTOR_STORAGE_SIZE 79304
#define NROS_CPP_ACTION_SERVER_STORAGE_SIZE 80
#define NROS_CPP_ACTION_CLIENT_STORAGE_SIZE 48
#define NROS_EXECUTOR_SIZE 79296
#define NROS_GUARD_CONDITION_SIZE 24
#define NROS_PUBLISHER_SIZE 560
#define NROS_SUBSCRIBER_SIZE 560
#define NROS_SERVICE_CLIENT_SIZE 4632
#define NROS_SERVICE_SERVER_SIZE 528
#define NROS_CPP_RAW_SUBSCRIPTION_OPAQUE_U64S 205
#define NROS_CPP_RAW_SERVICE_SERVER_OPAQUE_U64S 194
#define NROS_CPP_RAW_SERVICE_CLIENT_OPAQUE_U64S 707
#define NROS_CPP_RAW_ACTION_SERVER_OPAQUE_U64S 786
#define NROS_CPP_RAW_ACTION_CLIENT_OPAQUE_U64S 2193
#endif
