// nros-cpp: Publisher class
// Freestanding C++ — no exceptions, no STL required

#ifndef NROS_CPP_PUBLISHER_HPP
#define NROS_CPP_PUBLISHER_HPP

#include <cstdint>
#include <cstddef>

#include "nros/result.hpp"

// FFI declarations
extern "C" {
typedef int nros_cpp_ret_t;
nros_cpp_ret_t nros_cpp_publish_raw(void* handle, const uint8_t* data, size_t len);
nros_cpp_ret_t nros_cpp_publisher_destroy(void* handle);
const char* nros_cpp_publisher_get_topic_name(const void* handle);
} // extern "C"

namespace nros {

/// Typed publisher for a ROS 2 topic.
///
/// Mirrors `rclcpp::Publisher<M>`. The message type `M` must provide
/// `TYPE_NAME`, `TYPE_HASH`, and `ffi_publish()` (generated by codegen).
///
/// Raw CDR publishing is always available via `publish_raw()`.
///
/// Usage:
/// ```cpp
/// nros::Publisher<std_msgs::msg::String> pub;
/// NROS_TRY(node.create_publisher(pub, "/chatter"));
/// pub.publish_raw(cdr_data, cdr_len);
/// ```
template <typename M> class Publisher {
  public:
    /// Publish a typed message.
    ///
    /// Calls the codegen-generated `M::ffi_publish()` which serializes to CDR
    /// on the Rust side and publishes. Available after 66.4 codegen.
    Result publish(const M& msg) { return Result(M::ffi_publish(handle_, &msg)); }

    /// Publish raw CDR bytes.
    Result publish_raw(const uint8_t* data, size_t len) {
        if (!initialized_) return Result(ErrorCode::NotInitialized);
        return Result(nros_cpp_publish_raw(handle_, data, len));
    }

    /// Get the topic name.
    const char* get_topic_name() const {
        if (!initialized_) return "";
        return nros_cpp_publisher_get_topic_name(handle_);
    }

    /// Check if the publisher is initialized and valid.
    bool is_valid() const { return initialized_; }

    /// Destructor — releases publisher resources.
    ~Publisher() {
        if (initialized_) {
            nros_cpp_publisher_destroy(handle_);
            initialized_ = false;
        }
    }

    // Move semantics (non-copyable)
    Publisher(Publisher&& other) : handle_(other.handle_), initialized_(other.initialized_) {
        other.handle_ = nullptr;
        other.initialized_ = false;
    }

    Publisher& operator=(Publisher&& other) {
        if (this != &other) {
            if (initialized_) {
                nros_cpp_publisher_destroy(handle_);
            }
            handle_ = other.handle_;
            initialized_ = other.initialized_;
            other.handle_ = nullptr;
            other.initialized_ = false;
        }
        return *this;
    }

  private:
    Publisher(const Publisher&) = delete;
    Publisher& operator=(const Publisher&) = delete;

    friend class Node;
    Publisher() : handle_(nullptr), initialized_(false) {}

    void* handle_;
    bool initialized_;
};

} // namespace nros

#endif // NROS_CPP_PUBLISHER_HPP
