// nros-cpp: Publisher class
// Freestanding C++ — no exceptions, no STL required

#ifndef NROS_CPP_PUBLISHER_HPP
#define NROS_CPP_PUBLISHER_HPP

#include <cstdint>
#include <cstddef>
#include <cstring>

#include "nros/config.hpp"
#include "nros/result.hpp"

// FFI declarations
extern "C" {
typedef int nros_cpp_ret_t;
nros_cpp_ret_t nros_cpp_publish_raw(void* storage, const uint8_t* data, size_t len);
nros_cpp_ret_t nros_cpp_publisher_destroy(void* storage);
nros_cpp_ret_t nros_cpp_publisher_relocate(void* old_storage, void* new_storage);
} // extern "C"

namespace nros {

/// Maximum topic name length stored inside `nros::Publisher<M>`.
///
/// Mirrors `nros_node::limits::MAX_TOPIC_LEN` (256). The topic name is
/// now owned C++-side (Phase 87.6 thin-wrapper refactor) rather than
/// inside the Rust-side FFI struct, so there's no Rust-side size constant
/// to derive this from.
static constexpr size_t PUBLISHER_TOPIC_NAME_MAX = 256;

/// Typed publisher for a ROS 2 topic.
///
/// Mirrors `rclcpp::Publisher<M>`. The message type `M` must provide
/// `TYPE_NAME`, `TYPE_HASH`, and `ffi_publish()` (generated by codegen).
///
/// Raw CDR publishing is always available via `publish_raw()`.
///
/// Phase 87.6: the inline storage now holds an `RmwPublisher` handle
/// directly (`NROS_PUBLISHER_SIZE` bytes, derived from Rust's
/// `size_of::<RmwPublisher>()` via the `nros-sizes-build` probe). Topic
/// name metadata lives C++-side in `topic_name_`, avoiding a Rust-side
/// buffer copy and an FFI hop for `get_topic_name()`.
///
/// Usage:
/// ```cpp
/// nros::Publisher<std_msgs::msg::String> pub;
/// NROS_TRY(node.create_publisher(pub, "/chatter"));
/// pub.publish_raw(cdr_data, cdr_len);
/// ```
template <typename M> class Publisher {
  public:
    /// Publish a typed message.
    ///
    /// Calls the codegen-generated `M::ffi_publish()` which serializes to CDR
    /// on the Rust side and publishes.
    Result publish(const M& msg) { return Result(M::ffi_publish(storage_, &msg)); }

    /// Publish raw CDR bytes.
    Result publish_raw(const uint8_t* data, size_t len) {
        if (!initialized_) return Result(ErrorCode::NotInitialized);
        return Result(nros_cpp_publish_raw(storage_, data, len));
    }

    /// Get the topic name.
    const char* get_topic_name() const { return initialized_ ? topic_name_ : ""; }

    /// Check if the publisher is initialized and valid.
    bool is_valid() const { return initialized_; }

    /// Destructor — releases publisher resources.
    ~Publisher() {
        if (initialized_) {
            nros_cpp_publisher_destroy(storage_);
            initialized_ = false;
        }
    }

    // Move semantics (non-copyable). Relocation goes through the
    // Rust-side `nros_cpp_publisher_relocate` FFI.
    Publisher(Publisher&& other) : initialized_(other.initialized_) {
        if (other.initialized_) {
            nros_cpp_publisher_relocate(other.storage_, storage_);
            std::memcpy(topic_name_, other.topic_name_, sizeof(topic_name_));
            other.initialized_ = false;
        }
    }

    Publisher& operator=(Publisher&& other) {
        if (this != &other) {
            if (initialized_) {
                nros_cpp_publisher_destroy(storage_);
                initialized_ = false;
            }
            if (other.initialized_) {
                nros_cpp_publisher_relocate(other.storage_, storage_);
                std::memcpy(topic_name_, other.topic_name_, sizeof(topic_name_));
                initialized_ = true;
                other.initialized_ = false;
            }
        }
        return *this;
    }

    /// Default constructor — creates an uninitialized publisher.
    /// Use `Node::create_publisher()` to initialize.
    Publisher() : storage_(), topic_name_{}, initialized_(false) {}

  private:
    Publisher(const Publisher&) = delete;
    Publisher& operator=(const Publisher&) = delete;

    friend class Node;

    alignas(8) uint8_t storage_[NROS_PUBLISHER_SIZE];
    char topic_name_[PUBLISHER_TOPIC_NAME_MAX];
    bool initialized_;
};

} // namespace nros

#endif // NROS_CPP_PUBLISHER_HPP
