// nros-cpp: Subscription class
// Freestanding C++ — no exceptions, no STL required

#ifndef NROS_CPP_SUBSCRIPTION_HPP
#define NROS_CPP_SUBSCRIPTION_HPP

#include <cstdint>
#include <cstddef>

#include "nros/result.hpp"

// FFI declarations
extern "C" {
typedef int nros_cpp_ret_t;
nros_cpp_ret_t nros_cpp_subscription_try_recv_raw(void* handle, uint8_t* out_data,
                                                  size_t out_capacity, size_t* out_len);
nros_cpp_ret_t nros_cpp_subscription_destroy(void* handle);
const char* nros_cpp_subscription_get_topic_name(const void* handle);
} // extern "C"

namespace nros {

/// Typed subscription for a ROS 2 topic.
///
/// Mirrors `rclcpp::Subscription<M>`. The message type `M` must provide
/// `TYPE_NAME`, `TYPE_HASH`, and deserialization support (generated by codegen).
///
/// Manual-poll style: call `try_recv_raw()` after `nros::spin_once()`.
///
/// Usage:
/// ```cpp
/// nros::Subscription<std_msgs::msg::String> sub;
/// NROS_TRY(node.create_subscription(sub, "/chatter"));
/// nros::spin_once(10);
/// uint8_t buf[256];
/// size_t len;
/// if (sub.try_recv_raw(buf, sizeof(buf), len)) {
///     // process buf[0..len]
/// }
/// ```
template <typename M> class Subscription {
  public:
    /// Try to receive raw CDR data (non-blocking).
    ///
    /// Returns true if data was received and copied into `buf`.
    /// Sets `out_len` to the number of bytes received (0 if no data).
    ///
    /// @param buf       Buffer to receive CDR data.
    /// @param capacity  Size of the buffer.
    /// @param out_len   Receives the number of bytes (0 if no data available).
    /// @return true if data was received, false otherwise.
    bool try_recv_raw(uint8_t* buf, size_t capacity, size_t& out_len) {
        if (!initialized_) {
            out_len = 0;
            return false;
        }
        nros_cpp_ret_t ret = nros_cpp_subscription_try_recv_raw(handle_, buf, capacity, &out_len);
        return ret == 0 && out_len > 0;
    }

    /// Get the topic name.
    const char* get_topic_name() const {
        if (!initialized_) return "";
        return nros_cpp_subscription_get_topic_name(handle_);
    }

    /// Check if the subscription is initialized and valid.
    bool is_valid() const { return initialized_; }

    /// Destructor — releases subscription resources.
    ~Subscription() {
        if (initialized_) {
            nros_cpp_subscription_destroy(handle_);
            initialized_ = false;
        }
    }

    // Move semantics (non-copyable)
    Subscription(Subscription&& other) : handle_(other.handle_), initialized_(other.initialized_) {
        other.handle_ = nullptr;
        other.initialized_ = false;
    }

    Subscription& operator=(Subscription&& other) {
        if (this != &other) {
            if (initialized_) {
                nros_cpp_subscription_destroy(handle_);
            }
            handle_ = other.handle_;
            initialized_ = other.initialized_;
            other.handle_ = nullptr;
            other.initialized_ = false;
        }
        return *this;
    }

  private:
    Subscription(const Subscription&) = delete;
    Subscription& operator=(const Subscription&) = delete;

    friend class Node;
    Subscription() : handle_(nullptr), initialized_(false) {}

    void* handle_;
    bool initialized_;
};

} // namespace nros

#endif // NROS_CPP_SUBSCRIPTION_HPP
