// nros-cpp: Subscription class
// Freestanding C++ — no exceptions, no STL required

#ifndef NROS_CPP_SUBSCRIPTION_HPP
#define NROS_CPP_SUBSCRIPTION_HPP

#include <cstdint>
#include <cstddef>

#include "nros/config.hpp"
#include "nros/result.hpp"
#include "nros/stream.hpp"

// FFI declarations
extern "C" {
typedef int nros_cpp_ret_t;
nros_cpp_ret_t nros_cpp_subscription_try_recv_raw(void* storage, uint8_t* out_data,
                                                  size_t out_capacity, size_t* out_len);
nros_cpp_ret_t nros_cpp_subscription_destroy(void* storage);
nros_cpp_ret_t nros_cpp_subscription_relocate(void* old_storage, void* new_storage);
const char* nros_cpp_subscription_get_topic_name(const void* storage);
} // extern "C"

namespace nros {

/// Typed subscription for a ROS 2 topic.
///
/// Mirrors `rclcpp::Subscription<M>`. The message type `M` must provide
/// `TYPE_NAME`, `TYPE_HASH`, and deserialization support (generated by codegen).
///
/// Manual-poll style: call `try_recv_raw()` after `nros::spin_once()`.
///
/// Usage:
/// ```cpp
/// nros::Subscription<std_msgs::msg::String> sub;
/// NROS_TRY(node.create_subscription(sub, "/chatter"));
/// nros::spin_once(10);
/// uint8_t buf[256];
/// size_t len;
/// if (sub.try_recv_raw(buf, sizeof(buf), len)) {
///     // process buf[0..len]
/// }
/// ```
template <typename M> class Subscription {
  public:
    /// Try to receive a typed message (non-blocking).
    ///
    /// Receives raw CDR data into a stack buffer, then deserializes into `msg`
    /// using the codegen-generated `M::ffi_deserialize()`.
    ///
    /// @param msg  Output message struct (filled on success).
    /// @return Result::success() if a message was received and deserialized;
    ///         ErrorCode::TryAgain if no data is available right now;
    ///         ErrorCode::NotInitialized if the subscription is not initialized;
    ///         ErrorCode::Error if deserialization failed.
    Result try_recv(M& msg) {
        if (!initialized_) return Result(ErrorCode::NotInitialized);
        uint8_t buf[M::SERIALIZED_SIZE_MAX];
        size_t len = 0;
        nros_cpp_ret_t ret = nros_cpp_subscription_try_recv_raw(storage_, buf, sizeof(buf), &len);
        if (ret != 0) return Result(ret);
        if (len == 0) return Result(ErrorCode::TryAgain);
        if (M::ffi_deserialize(buf, len, &msg) != 0) return Result(ErrorCode::Error);
        return Result::success();
    }

    /// Try to receive raw CDR data (non-blocking).
    ///
    /// Sets `out_len` to the number of bytes received (0 if no data).
    ///
    /// @param buf       Buffer to receive CDR data.
    /// @param capacity  Size of the buffer.
    /// @param out_len   Receives the number of bytes (0 if no data available).
    /// @return Result::success() if data was received; ErrorCode::TryAgain
    ///         if no data is available; ErrorCode::NotInitialized or the
    ///         FFI error code otherwise.
    Result try_recv_raw(uint8_t* buf, size_t capacity, size_t& out_len) {
        if (!initialized_) {
            out_len = 0;
            return Result(ErrorCode::NotInitialized);
        }
        nros_cpp_ret_t ret = nros_cpp_subscription_try_recv_raw(storage_, buf, capacity, &out_len);
        if (ret != 0) return Result(ret);
        if (out_len == 0) return Result(ErrorCode::TryAgain);
        return Result::success();
    }

    /// Get the topic name.
    const char* get_topic_name() const {
        if (!initialized_) return "";
        return nros_cpp_subscription_get_topic_name(storage_);
    }

    /// Get a reference to the subscription's message stream.
    ///
    /// Use for blocking reception with executor spin:
    /// ```cpp
    /// M msg;
    /// NROS_TRY(sub.stream().wait_next(executor.handle(), 1000, msg));
    /// ```
    Stream<M>& stream() {
        if (initialized_ && !stream_.is_valid()) {
            stream_.bind(storage_, &nros_cpp_subscription_try_recv_raw);
        }
        return stream_;
    }

    const Stream<M>& stream() const { return stream_; }

    /// Check if the subscription is initialized and valid.
    bool is_valid() const { return initialized_; }

    /// Destructor — releases subscription resources.
    ~Subscription() {
        if (initialized_) {
            nros_cpp_subscription_destroy(storage_);
            initialized_ = false;
        }
    }

    // Move semantics (non-copyable). Relocation goes through the
    // Rust-side `nros_cpp_subscription_relocate` FFI (Phase 84.C1);
    // the `stream_` is rebound to the new storage afterwards.
    Subscription(Subscription&& other) : initialized_(other.initialized_) {
        if (other.initialized_) {
            nros_cpp_subscription_relocate(other.storage_, storage_);
            stream_.bind(storage_, &nros_cpp_subscription_try_recv_raw);
            other.initialized_ = false;
        }
        other.stream_ = Stream<M>();
    }

    Subscription& operator=(Subscription&& other) {
        if (this != &other) {
            if (initialized_) {
                nros_cpp_subscription_destroy(storage_);
                initialized_ = false;
                stream_ = Stream<M>();
            }
            if (other.initialized_) {
                nros_cpp_subscription_relocate(other.storage_, storage_);
                stream_.bind(storage_, &nros_cpp_subscription_try_recv_raw);
                initialized_ = true;
                other.initialized_ = false;
            }
            other.stream_ = Stream<M>();
        }
        return *this;
    }

    /// Default constructor — creates an uninitialized subscription.
    /// Use `Node::create_subscription()` to initialize.
    Subscription() : storage_(), initialized_(false), stream_() {}

  private:
    Subscription(const Subscription&) = delete;
    Subscription& operator=(const Subscription&) = delete;

    friend class Node;

    alignas(8) uint8_t storage_[NROS_CPP_SUBSCRIPTION_STORAGE_SIZE];
    bool initialized_;
    Stream<M> stream_;
};

} // namespace nros

#endif // NROS_CPP_SUBSCRIPTION_HPP
