meta:
  version: 1
  inputs:
  - path: launch/system.launch.xml
    sha256: a151aa9a0d21098e7ac3809348f99c825a69e87f4136eb9061d45515f75e70e9
  - path: system.toml
    sha256: 6fef3cdc4897f6afeeff0c0d653423fd4afa529eb004ae88bcb8662af1618c48
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
structure:
  scopes:
    system.launch.xml:
      file: system.launch.xml
  nodes:
    /managed_talker:
      scope: system.launch.xml
      pkg: cpp_lifecycle_talker_pkg
      exec: managed_talker
      node_name: managed_talker
execution:
  deploy:
    /managed_talker:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
