include = ["../../../../nros-patch.toml"]

[patch.crates-io]
custom_msgs = { path = "generated/custom_msgs" }  # nros-managed
nros-zephyr-build = { path = "../../../packages/tooling/nros-zephyr-build" }  # nros-managed
