/* Auto-generated by nros-c build.rs — do not edit */
#ifndef NROS_CONFIG_GENERATED_H
#define NROS_CONFIG_GENERATED_H

#include <stdint.h>

/** Inline opaque storage size (bytes) for nros_executor_t. */
#define NROS_EXECUTOR_STORAGE_SIZE 18752

/* ── Probe-derived inline storage sizes ──────────────────────
 * Each constant below is the byte size of the corresponding
 * runtime type, extracted from the compiled runtime by the
 * build script. They size the `_opaque` storage of the public
 * C handle types so callers can declare them on the stack or
 * inside their own structs without dynamic allocation.
 */
#define NROS_EXECUTOR_SIZE 17968
#define NROS_GUARD_CONDITION_SIZE 8
#define NROS_PUBLISHER_SIZE 560
#define NROS_SUBSCRIBER_SIZE 560
#define NROS_SERVICE_CLIENT_SIZE 4632
#define NROS_SERVICE_SERVER_SIZE 528
#define NROS_SESSION_SIZE 528
#define NROS_LIFECYCLE_CTX_SIZE 64
#define NROS_ACTION_SERVER_INTERNAL_SIZE 96

/* ── *_OPAQUE_U64S macros — sized opaque storage for the
 *    handle structs declared in <nros/nros_generated.h>.
 *    Each value is `ceil(size_of_type / 8)` u64 slots so the
 *    handle's storage is u64-aligned.
 */
#define SESSION_OPAQUE_U64S 66
#define PUBLISHER_OPAQUE_U64S 70
#define EXECUTOR_OPAQUE_U64S 2344
#define GUARD_HANDLE_OPAQUE_U64S 1
#define NROS_LIFECYCLE_CTX_OPAQUE_U64S 8

/* ── Type-compatible opaque definition of ActionServerRawHandle ──
 * Public C handle struct. The runtime owns the body; the C API
 * never lets callers reach into `_internal.handle` directly,
 * so an opaque, size-equivalent declaration is sufficient.
 */
#ifdef __cplusplus
extern "C" {
#endif
typedef struct ActionServerRawHandle {
    uint64_t _opaque[6];
} ActionServerRawHandle;
#ifdef __cplusplus
}
#endif

#endif /* NROS_CONFIG_GENERATED_H */
