/* nros common types — see nros_generated.h for most declarations */
#ifndef NROS_TYPES_H
#define NROS_TYPES_H
#include "nros/nros_generated.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef NROS_SERVICE_TYPE_DEFINED
#define NROS_SERVICE_TYPE_DEFINED
/**
 * Service type information (generated by codegen).
 *
 * Provides type name and hash for a ROS 2 service type.
 * This type is used by generated C code from nano_ros_generate_interfaces()
 * but is not referenced by any nros-c function, so cbindgen does not
 * include it in nros_generated.h.
 */
typedef struct nros_service_type_t {
    /** Type name (e.g., "example_interfaces::srv::dds_::AddTwoInts_") */
    const char *type_name;
    /** Type hash (RIHS format) */
    const char *type_hash;
} nros_service_type_t;
#endif

#ifdef __cplusplus
}
#endif

#endif /* NROS_TYPES_H */
