//! PX4 uORB RMW backend for nano-ros.
//!
//! Implements [`nros_rmw::Rmw`] over [`px4_uorb::Publication`] /
//! [`px4_uorb::Subscription`]. uORB is publish/subscribe-only; service and
//! action traits return [`nros_rmw::TransportError::Backend`] until a
//! request/reply paired-topic protocol lands (see Phase 90.4).
//!
//! Topic name resolution: ROS 2 topic strings (e.g. `/fmu/out/sensor_gyro`)
//! map to uORB metadata via a compile-time `phf::Map` generated by `build.rs`
//! from `topics.toml`.

#![cfg_attr(not(feature = "std"), no_std)]

#[cfg(feature = "alloc")]
extern crate alloc;

mod publisher;
mod session;
mod subscriber;
mod service;
mod topics;

pub use publisher::UorbPublisher;
pub use session::{UorbRmw, UorbSession};
pub use subscriber::UorbSubscriber;
pub use service::{UorbServiceClient, UorbServiceServer};
pub use topics::{lookup_topic, TopicEntry};
