//! PX4 uORB RMW backend for nano-ros.
//!
//! Implements [`nros_rmw::Rmw`] over [`px4_uorb::Publication`] /
//! [`px4_uorb::Subscription`]. uORB is publish/subscribe-only; service and
//! action traits return [`nros_rmw::TransportError::Backend`] until a
//! request/reply paired-topic protocol lands (see Phase 90.4).
//!
//! Topic name resolution: ROS 2 topic strings (e.g. `/fmu/out/sensor_gyro`)
//! map to uORB metadata via a compile-time `phf::Map` generated by `build.rs`
//! from `topics.toml`.

#![cfg_attr(not(feature = "std"), no_std)]

#[cfg(feature = "alloc")]
extern crate alloc;

mod raw;
mod topics;

// Direct typed API — primary entry point for PX4-shaped messages.
// Available in both std and no_std builds.
pub use raw::{publication, subscription};

// nros-rmw trait impls (UorbSession etc.) bridge nros-node's typed
// Publisher<M>/Subscription<M> onto px4-uorb via the trampoline registry.
// Both the impls and the registry are std-only — no_std consumers (real
// PX4 module builds) must use the raw API above instead.
#[cfg(feature = "std")]
mod publisher;
#[cfg(feature = "std")]
mod registry;
#[cfg(feature = "std")]
mod service;
#[cfg(feature = "std")]
mod session;
#[cfg(feature = "std")]
mod subscriber;

#[cfg(feature = "std")]
pub use publisher::UorbPublisher;
#[cfg(feature = "std")]
pub use registry::register;
#[cfg(feature = "std")]
pub use service::{UorbServiceClient, UorbServiceServer};
#[cfg(feature = "std")]
pub use session::{UorbRmw, UorbSession};
#[cfg(feature = "std")]
pub use subscriber::UorbSubscriber;

// Topic-mapping internals.
pub use topics::{lookup_topic, TopicEntry};

#[cfg(all(feature = "std", any(test, feature = "test-helpers")))]
pub use registry::_reset;
