//! PX4 uORB RMW backend for nano-ros.
//!
//! Implements [`nros_rmw::Rmw`] over [`px4_uorb::Publication`] /
//! [`px4_uorb::Subscription`]. uORB is publish/subscribe-only; service and
//! action traits return [`nros_rmw::TransportError::Backend`] until a
//! request/reply paired-topic protocol lands (see Phase 90.4).
//!
//! Topic name resolution: ROS 2 topic strings (e.g. `/fmu/out/sensor_gyro`)
//! map to uORB metadata via a compile-time `phf::Map` generated by `build.rs`
//! from `topics.toml`.

#![cfg_attr(not(feature = "std"), no_std)]

#[cfg(feature = "alloc")]
extern crate alloc;

mod publisher;
mod raw;
mod registry;
mod session;
mod subscriber;
mod service;
mod topics;

// Direct typed API — primary entry point for PX4-shaped messages.
pub use raw::{publication, subscription};

// Trampoline registry — only needed for nros-node typed-Publisher integration.
pub use registry::register;

// nros-rmw trait impls (consumed by nros-node when feature `rmw-uorb` is on).
pub use publisher::UorbPublisher;
pub use session::{UorbRmw, UorbSession};
pub use subscriber::UorbSubscriber;
pub use service::{UorbServiceClient, UorbServiceServer};

// Topic-mapping internals.
pub use topics::{lookup_topic, TopicEntry};

#[cfg(any(test, feature = "test-helpers"))]
pub use registry::_reset;
