//! Typed-trampoline registry bridging nros-rmw's type-erased `&[u8]` API
//! onto px4-uorb's typed `Publication<T>` / `Subscription<T>`.
//!
//! ## Why a registry?
//!
//! `nros_rmw::Publisher::publish_raw(&[u8])` is type-erased — it carries
//! no information about which uORB struct the bytes represent. uORB, by
//! contrast, requires a `Publication<T: UorbTopic>` parameterised by a
//! marker type. We close the gap with a fixed-size lookup table keyed by
//! the ROS 2 topic string: each entry holds a `Box<dyn TopicHandle>`
//! that owns a typed `Publication`/`Subscription` and exposes
//! byte-shaped publish/recv methods.
//!
//! Users call [`register`] once per topic at module init (typically from
//! `nros_px4::run`'s closure), naming both the ROS 2 topic and the
//! generated uORB topic marker.
//!
//! ## no_std + alloc compatibility (Phase 90.2b)
//!
//! Earlier revisions used `std::sync::Mutex<HashMap<...>>`. Replaced
//! with `critical_section::Mutex<RefCell<heapless::Vec<...>>>` so real
//! PX4 NuttX modules (which build no_std but do have an allocator)
//! can use the registry. Capacity is bounded at compile time
//! ([`MAX_TOPICS`]); registering past that returns an error rather
//! than silently overflowing.
//!
//! `lookup` was also reshaped: instead of returning a guard that
//! holds the lock across the caller's stack frame (incompatible with
//! the closure-based `critical_section::with` API), it now takes a
//! closure invoked while the critical section is held. Critical
//! sections must stay short — uORB publish/recv themselves take
//! their own broker locks but execute in bounded time.
//!
//! ## Memory layout assumption
//!
//! PX4 uORB uses raw memcpy — `T::Msg` is `#[repr(C)] Copy`. Bytes
//! arriving at `publish_raw` are interpreted as `T::Msg` directly via
//! `core::ptr::copy_nonoverlapping`. Length must match
//! `size_of::<T::Msg>()`. **Callers are responsible for using the
//! same `.msg` definition both sides of the wire** — there is no CDR.

use core::cell::RefCell;

use alloc::boxed::Box;
use critical_section::Mutex;
use heapless::Vec as HVec;
use nros_rmw::TransportError;
use px4_uorb::UorbTopic;

/// Maximum number of distinct ROS topic names that can be registered
/// in a single PX4 module. Bumping this is a recompile; capacity is
/// const-generic to keep the static layout zero-cost and avoid heap
/// fragmentation on long-running modules.
pub const MAX_TOPICS: usize = 32;

/// Per-topic byte-shaped publish/recv shim. One implementor per
/// `T: UorbTopic` is generated by [`register`].
pub(crate) trait TopicHandle: Send + Sync {
    fn publish(&self, data: &[u8]) -> Result<(), TransportError>;
    fn try_recv(&self, buf: &mut [u8]) -> Result<Option<usize>, TransportError>;
    /// Byte size of the underlying uORB message struct. Used by
    /// downstream consumers (test harnesses, future buffer-presize
    /// hooks) to size receive buffers without re-deriving from
    /// `T::Msg`.
    #[allow(dead_code)]
    fn msg_size(&self) -> usize;
    /// Force `orb_register_callback` to wire now. Idempotent. Called
    /// once at registration time after the handle is boxed (heap
    /// address stable). See [`register`].
    fn eager_register(&self);
    /// Register a single-slot waker on the subscription's
    /// `AtomicWaker`. The next uORB publish on this topic fires the
    /// waker. Used by [`crate::park_until_event`] to park a single
    /// executor task on every active topic at once.
    fn register_wake(&self, waker: &core::task::Waker);
}

type Slot = (&'static str, Box<dyn TopicHandle>);

/// Registry storage. Linear-scan over `MAX_TOPICS` entries — a hash
/// map would need lazy initialisation since `FnvIndexMap::new()` is
/// not `const`. For sub-100 topics linear scan is faster than a hash
/// anyway (no hashing cost, branchy memcmp short-circuits).
static REGISTRY: Mutex<RefCell<HVec<Slot, MAX_TOPICS>>> = Mutex::new(RefCell::new(HVec::new()));

/// Register a typed publisher/subscriber pair for `ros_name`.
///
/// Idempotent: re-registering a name overwrites the prior entry.
/// Returns `Err(TransportError::Backend(...))` if the registry is
/// full (more than [`MAX_TOPICS`] distinct names).
///
/// Eagerly wires `orb_register_callback` so `register_wake` can fire
/// even before the first `try_recv` happens. The Box's heap address is
/// stable, so it's safe to call `eager_register` after boxing.
pub fn register<T: UorbTopic>(ros_name: &'static str, instance: u8) -> Result<(), TransportError> {
    let handle: Box<dyn TopicHandle> = Box::new(Handle::<T>::new(instance));
    handle.eager_register();
    critical_section::with(|cs| {
        let mut reg = REGISTRY.borrow_ref_mut(cs);
        // Replace if already present.
        if let Some(slot) = reg.iter_mut().find(|(k, _)| *k == ros_name) {
            slot.1 = handle;
            return Ok(());
        }
        reg.push((ros_name, handle))
            .map_err(|_| TransportError::Backend("uORB registry full"))?;
        Ok(())
    })
}

/// Iterate every registered handle and call `register_wake(waker)` on
/// each. Used by [`crate::park_until_event`] so one executor task can
/// be woken by any uORB publish across all topics it subscribes to.
///
/// Each per-topic `AtomicWaker` is single-slot; calling this from
/// multiple parking awaiters concurrently would clobber. The current
/// `nros_px4::run_async` design has exactly one executor task → one
/// waker → safe.
pub(crate) fn register_wake_on_all(waker: &core::task::Waker) {
    critical_section::with(|cs| {
        let reg = REGISTRY.borrow_ref(cs);
        for (_, handle) in reg.iter() {
            handle.register_wake(waker);
        }
    });
}

/// Look up the handle for `ros_name` and invoke `f` while the
/// critical section is held. Returns `f`'s result, or `None` if the
/// topic isn't registered.
///
/// Critical sections must stay short. Heavy work (memcpy, mutex
/// hand-off in the broker) inside `f` is fine — both run in bounded
/// time — but blocking calls or `await` points are not.
pub(crate) fn lookup_with<R>(ros_name: &str, f: impl FnOnce(&dyn TopicHandle) -> R) -> Option<R> {
    critical_section::with(|cs| {
        let reg = REGISTRY.borrow_ref(cs);
        reg.iter()
            .find(|(k, _)| *k == ros_name)
            .map(|(_, h)| f(h.as_ref()))
    })
}

/// One-topic-per-instance handle. Owns both a `Publication<T>` and a
/// `Subscription<T>` because the same `ros_name` may be used for either
/// direction.
struct Handle<T: UorbTopic> {
    pub_: px4_uorb::Publication<T>,
    sub: px4_uorb::Subscription<T>,
}

impl<T: UorbTopic> Handle<T> {
    fn new(instance: u8) -> Self {
        Self {
            pub_: px4_uorb::Publication::<T>::new(),
            sub: px4_uorb::Subscription::<T>::with_instance(instance),
        }
    }
}

// SAFETY: `Publication<T>` is documented as Send+Sync (handle is
// `AtomicPtr`). `Subscription<T>` is `!Send` upstream because it
// registers a waker keyed on its own address. We sidestep that by
// (a) not exposing the subscription publicly, (b) only calling
// `try_recv()` (no future / waker registration) from inside the
// registry, and (c) holding the critical section during access.
unsafe impl<T: UorbTopic> Send for Handle<T> {}
unsafe impl<T: UorbTopic> Sync for Handle<T> {}

impl<T: UorbTopic> TopicHandle for Handle<T> {
    fn publish(&self, data: &[u8]) -> Result<(), TransportError> {
        let expected = core::mem::size_of::<T::Msg>();
        if data.len() != expected {
            return Err(TransportError::BufferTooSmall);
        }
        // SAFETY: T::Msg is `#[repr(C)] Copy` (uORB invariant). The byte
        // slice is exactly its size. We materialise a temporary T::Msg by
        // bitwise copy so `publish` can take a typed reference.
        let msg: T::Msg = unsafe { core::ptr::read_unaligned(data.as_ptr() as *const T::Msg) };
        self.pub_
            .publish(&msg)
            .map_err(|_| TransportError::PublishFailed)
    }

    fn try_recv(&self, buf: &mut [u8]) -> Result<Option<usize>, TransportError> {
        let expected = core::mem::size_of::<T::Msg>();
        if buf.len() < expected {
            return Err(TransportError::BufferTooSmall);
        }
        match self.sub.try_recv() {
            Some(msg) => {
                // SAFETY: T::Msg is `#[repr(C)] Copy`; `expected` bytes match
                // its size; `buf` is at least that long.
                unsafe {
                    core::ptr::copy_nonoverlapping(
                        &msg as *const T::Msg as *const u8,
                        buf.as_mut_ptr(),
                        expected,
                    );
                }
                Ok(Some(expected))
            }
            None => Ok(None),
        }
    }

    fn msg_size(&self) -> usize {
        core::mem::size_of::<T::Msg>()
    }

    fn eager_register(&self) {
        // Forces ensure_registered() inside Subscription::try_recv. The
        // returned message (if any) is intentionally discarded — at
        // registration time the topic is fresh, no message expected.
        let _ = self.sub.try_recv();
    }

    fn register_wake(&self, waker: &core::task::Waker) {
        self.sub.register_waker(waker);
    }
}

/// Test-only: clear the registry between unit tests.
#[cfg(any(test, feature = "test-helpers"))]
pub fn _reset() {
    critical_section::with(|cs| {
        REGISTRY.borrow_ref_mut(cs).clear();
    });
}
