//! Typed-trampoline registry bridging nros-rmw's type-erased `&[u8]` API
//! onto px4-uorb's typed `Publication<T>` / `Subscription<T>`.
//!
//! ## Why a registry?
//!
//! `nros_rmw::Publisher::publish_raw(&[u8])` is type-erased — it carries
//! no information about which uORB struct the bytes represent. uORB, by
//! contrast, requires a `Publication<T: UorbTopic>` parameterised by a
//! marker type. We close the gap with a runtime lookup table keyed by
//! the ROS 2 topic string: each entry holds a `Box<dyn TopicHandle>`
//! that owns a typed `Publication`/`Subscription` and exposes
//! byte-shaped publish/recv methods.
//!
//! Users call [`register`] once per topic at module init (typically from
//! `nros_px4::run`'s closure), naming both the ROS 2 topic and the
//! generated uORB topic marker.
//!
//! ## Memory layout assumption
//!
//! PX4 uORB uses raw memcpy — `T::Msg` is `#[repr(C)] Copy`. Bytes
//! arriving at `publish_raw` are interpreted as `T::Msg` directly via
//! `core::ptr::copy_nonoverlapping`. Length must match
//! `size_of::<T::Msg>()`. **Callers are responsible for using the
//! same `.msg` definition both sides of the wire** — there is no CDR.

// The trampoline registry uses std::sync::Mutex + std::collections::HashMap.
// no_std consumers (PX4 module builds, RTOS targets) must use the direct
// typed API in `raw.rs` (`publication::<T>` / `subscription::<T>`) instead.
// Phase 90.2b tracks adding a no_std-friendly registry backed by
// heapless::FnvIndexMap + critical_section if real demand arises.

use std::boxed::Box;
use std::collections::HashMap;
use std::sync::{Mutex, OnceLock};

use nros_rmw::TransportError;
use px4_uorb::UorbTopic;

/// Per-topic byte-shaped publish/recv shim. One implementor per
/// `T: UorbTopic` is generated by [`register`].
pub(crate) trait TopicHandle: Send + Sync {
    fn publish(&self, data: &[u8]) -> Result<(), TransportError>;
    fn try_recv(&self, buf: &mut [u8]) -> Result<Option<usize>, TransportError>;
    /// Byte size of the underlying uORB message struct.
    fn msg_size(&self) -> usize;
}

static REGISTRY: OnceLock<Mutex<HashMap<&'static str, Box<dyn TopicHandle>>>> = OnceLock::new();

fn registry() -> &'static Mutex<HashMap<&'static str, Box<dyn TopicHandle>>> {
    REGISTRY.get_or_init(|| Mutex::new(HashMap::new()))
}

/// Register a typed publisher/subscriber pair for `ros_name`.
///
/// Idempotent: re-registering a name overwrites the prior entry.
pub fn register<T: UorbTopic>(ros_name: &'static str, instance: u8) {
    let handle = Box::new(Handle::<T>::new(instance));
    registry()
        .lock()
        .expect("registry poisoned")
        .insert(ros_name, handle);
}

/// Look up a previously-registered topic. Used by [`crate::UorbPublisher`]
/// and [`crate::UorbSubscriber`] inside their `publish_raw` / `try_recv_raw`
/// methods.
pub(crate) fn lookup(ros_name: &str) -> Option<HandleGuard> {
    let guard = registry().lock().expect("registry poisoned");
    if !guard.contains_key(ros_name) {
        return None;
    }
    Some(HandleGuard { _guard: guard, key: ros_name.to_string() })
}

/// RAII guard returning a `&dyn TopicHandle` for the duration of one
/// publish/recv call. Holds the registry mutex; do not retain across
/// `await` points or long callbacks.
pub(crate) struct HandleGuard {
    _guard: std::sync::MutexGuard<'static, HashMap<&'static str, Box<dyn TopicHandle>>>,
    key: String,
}

impl HandleGuard {
    pub(crate) fn handle(&self) -> &dyn TopicHandle {
        // The registry contains the key (verified in `lookup`) and we hold
        // the mutex; the borrow is sound for the lifetime of `self`.
        self._guard
            .get(self.key.as_str())
            .map(|b| b.as_ref())
            .expect("topic vanished from registry while guard held")
    }
}

/// One-topic-per-instance handle. Owns both a `Publication<T>` and a
/// `Subscription<T>` because the same `ros_name` may be used for either
/// direction.
struct Handle<T: UorbTopic> {
    pub_: px4_uorb::Publication<T>,
    sub: px4_uorb::Subscription<T>,
}

impl<T: UorbTopic> Handle<T> {
    fn new(instance: u8) -> Self {
        Self {
            pub_: px4_uorb::Publication::<T>::new(),
            sub: px4_uorb::Subscription::<T>::with_instance(instance),
        }
    }
}

// SAFETY: `Publication<T>` is documented as Send+Sync (handle is
// `AtomicPtr`). `Subscription<T>` is `!Send` upstream because it
// registers a waker keyed on its own address. We sidestep that by
// (a) not exposing the subscription publicly, (b) only calling
// `try_recv()` (no future / waker registration) from inside the
// registry, and (c) holding the registry mutex during access.
unsafe impl<T: UorbTopic> Send for Handle<T> {}
unsafe impl<T: UorbTopic> Sync for Handle<T> {}

impl<T: UorbTopic> TopicHandle for Handle<T> {
    fn publish(&self, data: &[u8]) -> Result<(), TransportError> {
        let expected = core::mem::size_of::<T::Msg>();
        if data.len() != expected {
            return Err(TransportError::BufferTooSmall);
        }
        // SAFETY: T::Msg is `#[repr(C)] Copy` (uORB invariant). The byte
        // slice is exactly its size. We materialise a temporary T::Msg by
        // bitwise copy so `publish` can take a typed reference.
        let msg: T::Msg = unsafe { core::ptr::read_unaligned(data.as_ptr() as *const T::Msg) };
        self.pub_
            .publish(&msg)
            .map_err(|_| TransportError::PublishFailed)
    }

    fn try_recv(&self, buf: &mut [u8]) -> Result<Option<usize>, TransportError> {
        let expected = core::mem::size_of::<T::Msg>();
        if buf.len() < expected {
            return Err(TransportError::BufferTooSmall);
        }
        match self.sub.try_recv() {
            Some(msg) => {
                // SAFETY: T::Msg is `#[repr(C)] Copy`; `expected` bytes match
                // its size; `buf` is at least that long.
                unsafe {
                    core::ptr::copy_nonoverlapping(
                        &msg as *const T::Msg as *const u8,
                        buf.as_mut_ptr(),
                        expected,
                    );
                }
                Ok(Some(expected))
            }
            None => Ok(None),
        }
    }

    fn msg_size(&self) -> usize {
        core::mem::size_of::<T::Msg>()
    }
}

/// Test-only: clear the registry between unit tests.
#[cfg(any(test, feature = "test-helpers"))]
pub fn _reset() {
    if let Some(reg) = REGISTRY.get() {
        reg.lock().expect("registry poisoned").clear();
    }
}
