//! Service request/reply over paired uORB topics (Phase 90.4b).
//!
//! uORB has no native request/response. We layer one over two
//! ordinary uORB topics named `<service>/_request` and
//! `<service>/_reply`. Both topics carry a small wire envelope:
//!
//! ```text
//! ┌──────────────┬──────────────────┬───────────────────────┬──────────┐
//! │ seq: u64 LE  │ payload_len: u16 │ payload: payload_len  │ zero-pad │
//! │ (8 bytes)    │ LE (2 bytes)     │ bytes                 │ to o_size│
//! └──────────────┴──────────────────┴───────────────────────┴──────────┘
//! ```
//!
//! The trailing zero-pad exists because uORB's `publish_raw` requires
//! `data.len() == size_of::<T::Msg>()`. We always write a full
//! topic-sized buffer; the explicit `payload_len` lets the receiver
//! recover the meaningful prefix.
//!
//! `seq` is generated by the client from a per-handle atomic counter
//! and echoed verbatim by the server in its reply. The client's
//! `try_recv_reply_raw` ignores reply messages whose `seq` doesn't
//! match the most recently sent request — this lets multiple client
//! processes share one reply topic without seeing each other's
//! traffic, at the cost of multi-in-flight requests within a single
//! client process (which the existing `nros-node` `Promise` shape
//! doesn't support anyway).
//!
//! Topic registration: callers must `register::<ReqTopic>` /
//! `register::<ReplyTopic>` for both topics before opening the
//! service. The user-facing service name (`/foo`) is mapped to
//! `/foo/_request` + `/foo/_reply` internally — pick uORB topic
//! struct types whose `o_size` is at least `8 + max_payload_size`.
//!
//! Limitations:
//! - Single in-flight request per client handle. Server happily
//!   accepts concurrent requests; client only matches the latest.
//! - No timeout / cancellation primitives — Promise layer handles
//!   that on top.
//! - No multi-instance routing — server broadcasts replies to
//!   anyone subscribed to the reply topic.

use core::sync::atomic::Ordering;
use portable_atomic::AtomicU64;

use heapless::String as HString;
use nros_rmw::{ServiceClientTrait, ServiceRequest, ServiceServerTrait, TransportError};

use crate::registry::lookup_with;

const MAX_NAME: usize = 144;
const SEQ_LEN: usize = 8;
const LEN_LEN: usize = 2;
const HEADER_LEN: usize = SEQ_LEN + LEN_LEN;

/// Encode `seq | payload_len | payload | zero-pad` into `dst`.
/// Caller guarantees `dst.len() >= HEADER_LEN + payload.len()`. The
/// trailing bytes of `dst` are zero-filled to honour uORB's
/// fixed-size publish contract.
fn encode_envelope(dst: &mut [u8], seq: u64, payload: &[u8]) {
    debug_assert!(payload.len() <= u16::MAX as usize);
    debug_assert!(dst.len() >= HEADER_LEN + payload.len());
    dst[..SEQ_LEN].copy_from_slice(&seq.to_le_bytes());
    dst[SEQ_LEN..HEADER_LEN].copy_from_slice(&(payload.len() as u16).to_le_bytes());
    dst[HEADER_LEN..HEADER_LEN + payload.len()].copy_from_slice(payload);
    for byte in &mut dst[HEADER_LEN + payload.len()..] {
        *byte = 0;
    }
}

/// Decode `seq | payload_len | payload` from `src`. Returns
/// `(seq, payload_slice)` or `None` if `src` is too short or the
/// declared `payload_len` exceeds what's left in `src`.
fn decode_envelope(src: &[u8]) -> Option<(u64, &[u8])> {
    if src.len() < HEADER_LEN {
        return None;
    }
    let seq = u64::from_le_bytes(src[..SEQ_LEN].try_into().unwrap());
    let payload_len = u16::from_le_bytes(src[SEQ_LEN..HEADER_LEN].try_into().unwrap()) as usize;
    if HEADER_LEN + payload_len > src.len() {
        return None;
    }
    Some((seq, &src[HEADER_LEN..HEADER_LEN + payload_len]))
}

/// Build the request / reply topic names from the user-facing
/// service name.
fn paired_names(service: &str) -> Result<(HString<MAX_NAME>, HString<MAX_NAME>), TransportError> {
    let mut req: HString<MAX_NAME> = HString::new();
    let mut rep: HString<MAX_NAME> = HString::new();
    req.push_str(service)
        .and_then(|_| req.push_str("/_request"))
        .map_err(|_| TransportError::InvalidConfig)?;
    rep.push_str(service)
        .and_then(|_| rep.push_str("/_reply"))
        .map_err(|_| TransportError::InvalidConfig)?;
    Ok((req, rep))
}

/// Total size of the uORB topic struct used as a service envelope
/// carrier. Both `<svc>/_request` and `<svc>/_reply` topics MUST be
/// registered against an `UorbTopic` whose `T::Msg` is exactly this
/// many bytes — uORB's fixed-size publish contract requires the
/// full message buffer on every send.
///
/// Recommended pattern:
///
/// ```ignore
/// #[repr(C)]
/// #[derive(Copy, Clone)]
/// struct ServiceEnvelope { bytes: [u8; UORB_SERVICE_TOPIC_BYTES] }
/// // ... impl UorbTopic with metadata.o_size == size_of::<ServiceEnvelope>()
/// register::<MyServiceRequestTopic>("/foo/_request", 0)?;
/// register::<MyServiceReplyTopic>("/foo/_reply", 0)?;
/// ```
pub const UORB_SERVICE_TOPIC_BYTES: usize = 256;

/// Maximum payload size after the envelope header. Equal to
/// `UORB_SERVICE_TOPIC_BYTES - HEADER_LEN`.
pub const UORB_SERVICE_PAYLOAD_MAX: usize = UORB_SERVICE_TOPIC_BYTES - HEADER_LEN;

/// Server end of a paired-topic uORB service.
#[derive(Debug)]
pub struct UorbServiceServer {
    request_topic: HString<MAX_NAME>,
    reply_topic: HString<MAX_NAME>,
    /// Full-topic-sized buffer for outgoing reply (seq + len +
    /// payload + zero-pad to UORB_SERVICE_TOPIC_BYTES).
    reply_envelope: [u8; UORB_SERVICE_TOPIC_BYTES],
    /// Full-topic-sized buffer for incoming request. Sized to fit
    /// the topic struct because uORB writes `o_size` bytes — even
    /// if the caller's `buf` is smaller, the underlying try_recv
    /// rejects.
    recv_envelope: [u8; UORB_SERVICE_TOPIC_BYTES],
}

/// Client end of a paired-topic uORB service.
#[derive(Debug)]
pub struct UorbServiceClient {
    request_topic: HString<MAX_NAME>,
    reply_topic: HString<MAX_NAME>,
    /// Per-client seq counter. Wraps after 2^64 calls — fine.
    next_seq: AtomicU64,
    /// Last seq we sent on the request topic. `try_recv_reply_raw`
    /// only accepts replies tagged with this value.
    last_sent_seq: AtomicU64,
    /// Full-topic-sized buffer for outgoing request envelope.
    request_envelope: [u8; UORB_SERVICE_TOPIC_BYTES],
    /// Full-topic-sized buffer for incoming reply.
    recv_envelope: [u8; UORB_SERVICE_TOPIC_BYTES],
}

impl UorbServiceServer {
    pub(crate) fn new(service_name: &str) -> Result<Self, TransportError> {
        let (request_topic, reply_topic) = paired_names(service_name)?;
        Ok(Self {
            request_topic,
            reply_topic,
            reply_envelope: [0u8; UORB_SERVICE_TOPIC_BYTES],
            recv_envelope: [0u8; UORB_SERVICE_TOPIC_BYTES],
        })
    }
}

impl UorbServiceClient {
    pub(crate) fn new(service_name: &str) -> Result<Self, TransportError> {
        let (request_topic, reply_topic) = paired_names(service_name)?;
        Ok(Self {
            request_topic,
            reply_topic,
            next_seq: AtomicU64::new(1),
            last_sent_seq: AtomicU64::new(0),
            request_envelope: [0u8; UORB_SERVICE_TOPIC_BYTES],
            recv_envelope: [0u8; UORB_SERVICE_TOPIC_BYTES],
        })
    }
}

impl ServiceServerTrait for UorbServiceServer {
    type Error = TransportError;

    fn try_recv_request<'a>(
        &mut self,
        buf: &'a mut [u8],
    ) -> Result<Option<ServiceRequest<'a>>, Self::Error> {
        // Receive into our internal full-topic-sized buffer
        // (try_recv requires buf.len() >= o_size). Then decode +
        // copy the payload into the caller-supplied `buf` so the
        // returned ServiceRequest borrows from `buf`.
        let recv_envelope = &mut self.recv_envelope;
        let len_opt = lookup_with(self.request_topic.as_str(), |handle| {
            handle.try_recv(recv_envelope.as_mut_slice())
        })
        .ok_or(TransportError::Backend(
            "uORB service: request topic not registered — call \
             nros_rmw_uorb::register::<T>(\"<svc>/_request\", 0) first",
        ))??;
        let Some(_len) = len_opt else {
            return Ok(None);
        };
        let (seq, payload) =
            decode_envelope(&self.recv_envelope).ok_or(TransportError::DeserializationError)?;
        if buf.len() < payload.len() {
            return Err(TransportError::BufferTooSmall);
        }
        buf[..payload.len()].copy_from_slice(payload);
        let payload_len = payload.len();
        Ok(Some(ServiceRequest {
            data: &buf[..payload_len],
            sequence_number: seq as i64,
        }))
    }

    fn send_reply(&mut self, sequence_number: i64, data: &[u8]) -> Result<(), Self::Error> {
        if data.len() > UORB_SERVICE_PAYLOAD_MAX {
            return Err(TransportError::BufferTooSmall);
        }
        encode_envelope(&mut self.reply_envelope, sequence_number as u64, data);
        let envelope: &[u8] = &self.reply_envelope;
        lookup_with(self.reply_topic.as_str(), |handle| handle.publish(envelope)).ok_or(
            TransportError::Backend(
                "uORB service: reply topic not registered — call \
             nros_rmw_uorb::register::<T>(\"<svc>/_reply\", 0) first",
            ),
        )?
    }
}

impl ServiceClientTrait for UorbServiceClient {
    type Error = TransportError;

    fn send_request_raw(&mut self, request: &[u8]) -> Result<(), Self::Error> {
        if request.len() > UORB_SERVICE_PAYLOAD_MAX {
            return Err(TransportError::BufferTooSmall);
        }
        let seq = self.next_seq.fetch_add(1, Ordering::AcqRel);
        encode_envelope(&mut self.request_envelope, seq, request);
        let envelope: &[u8] = &self.request_envelope;
        lookup_with(self.request_topic.as_str(), |handle| {
            handle.publish(envelope)
        })
        .ok_or(TransportError::Backend(
            "uORB service: request topic not registered — call \
             nros_rmw_uorb::register::<T>(\"<svc>/_request\", 0) first",
        ))??;
        self.last_sent_seq.store(seq, Ordering::Release);
        Ok(())
    }

    fn try_recv_reply_raw(&mut self, reply_buf: &mut [u8]) -> Result<Option<usize>, Self::Error> {
        // uORB only keeps the latest sample per topic, so we get at
        // most one delivery per poll — no need to loop draining
        // mismatched replies.
        let recv_envelope = &mut self.recv_envelope;
        let len_opt = lookup_with(self.reply_topic.as_str(), |handle| {
            handle.try_recv(recv_envelope.as_mut_slice())
        })
        .ok_or(TransportError::Backend(
            "uORB service: reply topic not registered — call \
             nros_rmw_uorb::register::<T>(\"<svc>/_reply\", 0) first",
        ))??;
        let Some(_len) = len_opt else {
            return Ok(None);
        };
        let (seq, payload) =
            decode_envelope(&self.recv_envelope).ok_or(TransportError::DeserializationError)?;
        let expected = self.last_sent_seq.load(Ordering::Acquire);
        if seq != expected {
            // Reply for a different in-flight request (another client
            // process, or stale). Treat as no-data.
            return Ok(None);
        }
        if reply_buf.len() < payload.len() {
            return Err(TransportError::BufferTooSmall);
        }
        let payload_len = payload.len();
        reply_buf[..payload_len].copy_from_slice(payload);
        Ok(Some(payload_len))
    }
}
