//! ROS 2 topic name → uORB topic mapping.
//!
//! `TOPIC_MAP` is a compile-time `phf::Map` generated by `build.rs` from
//! `topics.toml`. Lookup at runtime is O(1) hash + string compare.

/// Descriptor produced by [`lookup_topic`].
///
/// `uorb_name` is the uORB topic identifier (matches `orb_metadata::o_name`);
/// `instance` is the multi-instance index passed to `with_instance` /
/// `advertise_multi`.
#[derive(Debug, Clone, Copy)]
pub struct TopicEntry {
    pub uorb_name: &'static str,
    pub instance: u8,
}

include!(concat!(env!("OUT_DIR"), "/topics_generated.rs"));

/// Resolve a ROS 2 topic string to its uORB descriptor.
///
/// Returns `None` if the topic is not in `topics.toml`.
pub fn lookup_topic(ros_name: &str) -> Option<TopicEntry> {
    TOPIC_MAP.get(ros_name).copied()
}
