meta:
  version: 1
  inputs:
  - path: /home/aeon/repos/nano-ros/examples/workspaces/ws-qos-mixed/src/demo_bringup/config/listener_model.record.json
    sha256: 05a50986d5c832c507115be51591661e69104b8e5231d0ebaa5a7a80b1500aee
  - path: /home/aeon/repos/nano-ros/examples/workspaces/ws-qos-mixed/src/demo_bringup/launch/listener.launch.xml
    sha256: 93a8e890e03bc4956152c77b8b594023cdd069cd83f76b9ad3c96179a484501f
  - path: /home/aeon/repos/nano-ros/examples/workspaces/ws-qos-mixed/src/demo_bringup/system.toml
    sha256: f8ff65af78f701c48f4fa5dce93fecb996c4cbf4bddbc730db35e7f32dbf2574
  resolver:
    tool: play_launch
    version: 0.8.2
  record:
    path: /home/aeon/repos/nano-ros/examples/workspaces/ws-qos-mixed/src/demo_bringup/config/listener_model.record.json
    sha256: 05a50986d5c832c507115be51591661e69104b8e5231d0ebaa5a7a80b1500aee
structure:
  scopes:
    /: {}
  nodes:
    /qos_listener:
      scope: /
      pkg: qos_listener_pkg
      exec: qos_listener
execution:
  deploy:
    /qos_listener:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
