//! The writer — one descriptor, byte-stable, path-free.
//!
//! Hand-rendered rather than `toml::to_string`, for two reasons that are both
//! acceptance criteria rather than taste.
//!
//! **Byte-stability.** The artifact is compared, cached and written
//! write-if-changed; a serializer's key order, integer spelling or table
//! placement is not part of any contract it offers. Rendering the field order
//! here makes it one. The order is the D4 sketch's, so the file and the RFC read
//! the same.
//!
//! **No absolute paths, ever — issue 0320's rule.** The descriptor must be
//! byte-identical across two checkouts of one tree at different paths, so no
//! field in the schema can hold a path and nothing here writes one.
//!
//! That is enforced rather than intended, by [`portability_violation`] — and it
//! is enforced against the CHECKOUT ROOTS the producer names, not against a list
//! of filesystem prefixes. A prefix list cannot work: a ROS topic is an
//! absolute-looking string too, and no predicate over the text alone separates
//! one from a leaked directory. The producer knows exactly which directories it
//! read from, so the producer is what can answer exactly.
//!
//! The check is on the rendered OUTPUT rather than on the typed inputs, because
//! a path reaches a string field through a REFUSAL REASON — prose a producer
//! writes freely, and the one place an interpolated `Path::display()` would slip
//! in. A refusal that names a file names it relative, or names the entry instead.

use crate::schema::{Endpoint, Image, Meta, Policy, SizingDescriptor, Target, Types};

/// The header every descriptor carries.
const HEADER: &str = "\
# Generated by `nros sync` -- do not edit, do not commit (build artifact).
#
# RFC-0100 D4: the ONE sizing descriptor for this entry. `nros sync` writes it;
# every consumer reads it BY PATH and derives its own buffers from it
# (`nros-sizing-descriptor` is the shared reader -- do not re-parse this by hand).
#
# Env transport is what this replaces: issue 0460 (a knob that reached the Zephyr
# C lane and not the cargo one) and issue 0491 (a PATH variable compared as text).
# Neither can carry per-endpoint structure without encoding it in a string.
#
# Per-FIELD status, never one global status (D6). A `refused` sub-table beside a
# section's values carries the prose for the fields that have no number, so a
# `history = keep_all` endpoint loses its depth-derived fields and degrades
# nothing else.
#
# Demand is published UNFLOORED (D7, issues 1015 + 1033). Zero is a legitimate
# demand; whether zero is a legal SIZE is a property of the storage, so the floor
# belongs at the consumer's pool and is deliberately not applied here.
";

/// Render a descriptor to its canonical bytes.
///
/// Endpoints are emitted in `(kind, type, topic)` order; call
/// [`SizingDescriptor::sort_endpoints`] first, or accept the order you built.
/// The writer does not sort silently — a caller that assembled rows in a
/// meaningful order should not have it changed without asking.
///
/// Portability is the producer's to assert — see [`portability_violation`] —
/// because only the producer knows which directories it read from.
pub fn render(desc: &SizingDescriptor) -> String {
    let mut out = String::from(HEADER);
    out.push('\n');
    out.push_str(&format!("schema_version = {}\n", desc.schema_version));

    out.push_str("\n[meta]\n");
    out.push_str(&format!("entry = \"{}\"\n", escape(&desc.meta.entry)));
    out.push_str(&format!("status = \"{}\"\n", desc.meta.status.tag()));
    out.push_str(&format!("basis = \"{}\"\n", desc.meta.basis.tag()));
    emit_values(&mut out, Meta::FIELDS, |f| desc.meta.raw_value(f));
    emit_refusals(&mut out, "meta.refused", desc.meta.refusals());

    out.push_str("\n[target]\n");
    emit_values(&mut out, Target::FIELDS, |f| desc.target.raw_value(f));
    emit_refusals(&mut out, "target.refused", desc.target.refusals());

    for ep in &desc.endpoints {
        out.push_str("\n[[endpoint]]\n");
        out.push_str(&format!("kind = \"{}\"\n", ep.kind.tag()));
        out.push_str(&format!("type = \"{}\"\n", escape(&ep.type_name)));
        out.push_str(&format!("topic = \"{}\"\n", escape(&ep.topic)));
        emit_values(&mut out, Endpoint::FIELDS, |f| ep.raw_value(f));
        emit_refusals(&mut out, "endpoint.refused", ep.refusals());
    }

    out.push_str("\n[image]\n");
    emit_values(&mut out, Image::FIELDS, |f| desc.image.raw_value(f));
    emit_refusals(&mut out, "image.refused", desc.image.refusals());

    out.push_str("\n[types]\n");
    emit_values(&mut out, Types::FIELDS, |f| desc.types.raw_value(f));
    emit_refusals(&mut out, "types.refused", desc.types.refusals());

    out.push_str("\n[policy]\n");
    emit_values(&mut out, Policy::FIELDS, |f| desc.policy.raw_value(f));
    emit_refusals(&mut out, "policy.refused", desc.policy.refusals());

    out
}

fn emit_values(out: &mut String, fields: &[&str], value: impl Fn(&str) -> Option<String>) {
    for f in fields {
        if let Some(v) = value(f) {
            out.push_str(&format!("{f} = {v}\n"));
        }
    }
}

/// A section's refusals, as a sub-table beside its values.
///
/// Omitted entirely when there are none, so a fully derived image's descriptor
/// reads exactly like the D4 sketch and carries no ceremony.
fn emit_refusals(
    out: &mut String,
    table: &str,
    refusals: &std::collections::BTreeMap<String, String>,
) {
    if refusals.is_empty() {
        return;
    }
    out.push_str(&format!("\n[{table}]\n"));
    // `BTreeMap` is already sorted by key; the iteration order is the stability.
    for (field, reason) in refusals {
        out.push_str(&format!("{field} = \"{}\"\n", escape(reason)));
    }
}

/// TOML basic-string escaping, and a refusal for the control characters a
/// reason string must not contain.
///
/// A newline inside a refusal would split the key/value line and produce a file
/// that parses as something else — the failure mode is a WRONG descriptor, not a
/// broken one, so it is normalised here rather than trusted to every producer.
fn escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' | '\r' => out.push(' '),
            '\t' => out.push(' '),
            c if (c as u32) < 0x20 => out.push(' '),
            c => out.push(c),
        }
    }
    out
}

/// Issue 0320 — does `text` name any of `roots`?
///
/// `Some(prose)` naming the offending line and root when a rendered descriptor
/// mentions a checkout directory, `None` when it is portable.
///
/// **The roots are supplied, never guessed.** The failure this guards is a
/// producer interpolating a `Path::display()` into a refusal reason, and the only
/// thing separating such a string from a legitimate ROS topic is that it begins
/// at a directory the producer read from — which the producer knows and a string
/// predicate cannot. An earlier version of this check carried a list of
/// filesystem prefixes instead, and that was wrong twice over: it could not see a
/// checkout somewhere unusual, and its own literals were build-host absolute
/// paths in a tracked file, which `scripts/ci/absolute-path-check.sh` exists to
/// refuse.
///
/// A root that is not absolute, or is one character long, is IGNORED rather than
/// matched: the filesystem root appears in every descriptor that carries a topic,
/// and a guard that fires on every call is the same as no guard.
pub fn portability_violation(text: &str, roots: &[&std::path::Path]) -> Option<String> {
    for root in roots {
        let Some(needle) = root.to_str() else {
            continue;
        };
        if needle.len() < 2 || !root.is_absolute() {
            continue;
        }
        for (i, line) in text.lines().enumerate() {
            // The header is a constant; nothing a producer writes reaches it.
            if line.starts_with('#') {
                continue;
            }
            if line.contains(needle) {
                return Some(format!(
                    "sizing descriptor line {} names the checkout directory `{needle}`. The \
                     descriptor must be byte-identical across two checkouts of one tree at \
                     different paths (issue 0320) -- name the entry, or a repo-relative path, \
                     instead:\n  {line}",
                    i + 1
                ));
            }
        }
    }
    None
}
