//! Pure and testable build-script helpers for `zpico-sys`.

use std::{
    collections::HashSet,
    fmt::Write as _,
    path::{Path, PathBuf},
    process::Command,
};

use nros_board_common::{manifest, policy::LinkFeatures};

pub mod runner;

/// Shim slot count configuration.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ShimConfig {
    pub max_publishers: usize,
    pub max_subscribers: usize,
    pub max_queryables: usize,
    pub max_liveliness: usize,
    pub max_pending_gets: usize,
    pub get_reply_buf_size: usize,
    pub get_poll_interval_ms: usize,
    /// phase-279 (#145) — opt-in tx batching (`ZPICO_TX_BATCH=1`): puts queue in
    /// the transport write buffer and ship as ONE socket send per
    /// `zpico_spin_once` flush. Default OFF (adds up to one spin period of tx
    /// latency; gets/replies/express publishers bypass). Biggest win on Zephyr,
    /// where zsock's per-fd lock caps tx at ~1 send per socket-recv window.
    pub tx_batch: bool,
    /// phase-282 (#145) — flush cadence, ms (`ZPICO_TX_BATCH_FLUSH_MS`,
    /// default 50): period of the dedicated tx-flush thread and rate limit of
    /// the spin-driven fallback flush. Bounds the extra publish latency the
    /// batch adds. Only meaningful with `tx_batch`.
    pub tx_batch_flush_ms: usize,
}

impl ShimConfig {
    /// Generate `$OUT_DIR/shim_constants.rs` contents with Rust const declarations.
    pub fn rust_consts(&self) -> String {
        format!(
            "/// Maximum number of concurrent publishers (set via ZPICO_MAX_PUBLISHERS, default 8).\n\
             pub const ZPICO_MAX_PUBLISHERS: usize = {};\n\
             /// Maximum number of concurrent subscribers (set via ZPICO_MAX_SUBSCRIBERS, default 8).\n\
             pub const ZPICO_MAX_SUBSCRIBERS: usize = {};\n\
             /// Maximum number of concurrent queryables (set via ZPICO_MAX_QUERYABLES, default 8).\n\
             pub const ZPICO_MAX_QUERYABLES: usize = {};\n\
             /// Maximum number of concurrent liveliness tokens (set via ZPICO_MAX_LIVELINESS, default 16).\n\
             pub const ZPICO_MAX_LIVELINESS: usize = {};\n\
             /// Maximum number of concurrent pending get operations (set via ZPICO_MAX_PENDING_GETS, default 4).\n\
             pub const ZPICO_MAX_PENDING_GETS: usize = {};\n",
            self.max_publishers,
            self.max_subscribers,
            self.max_queryables,
            self.max_liveliness,
            self.max_pending_gets,
        )
    }

    /// Add `-D` flags to a `cc::Build` so the C shim picks up the same values.
    pub fn apply_to_cc(&self, build: &mut cc::Build) {
        build.define(
            "ZPICO_MAX_PUBLISHERS",
            self.max_publishers.to_string().as_str(),
        );
        build.define(
            "ZPICO_MAX_SUBSCRIBERS",
            self.max_subscribers.to_string().as_str(),
        );
        build.define(
            "ZPICO_MAX_QUERYABLES",
            self.max_queryables.to_string().as_str(),
        );
        build.define(
            "ZPICO_MAX_LIVELINESS",
            self.max_liveliness.to_string().as_str(),
        );
        build.define(
            "ZPICO_MAX_PENDING_GETS",
            self.max_pending_gets.to_string().as_str(),
        );
        build.define(
            "ZPICO_GET_REPLY_BUF_SIZE",
            self.get_reply_buf_size.to_string().as_str(),
        );
        build.define(
            "ZPICO_GET_POLL_INTERVAL_MS",
            self.get_poll_interval_ms.to_string().as_str(),
        );
        if self.tx_batch {
            build.define("ZPICO_TX_BATCH", "1");
            build.define(
                "ZPICO_TX_BATCH_FLUSH_MS",
                self.tx_batch_flush_ms.to_string().as_str(),
            );
        }
    }
}

/// Buffer size configuration for zenoh-pico.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ZenohBufferConfig {
    pub frag_max_size: usize,
    pub batch_unicast_size: usize,
    pub batch_multicast_size: usize,
}

/// Generate a zenoh-pico config header body from already-resolved build inputs.
pub fn config_header(
    link: &LinkFeatures,
    buf: &ZenohBufferConfig,
    target: &str,
    unstable_api: bool,
    orin_spe: bool,
    tx_batch: bool,
    tx_split_lock: bool,
) -> String {
    let mut header = String::new();
    writeln!(header, "/**").unwrap();
    writeln!(header, " * zenoh_generic_config.h - Generated by build.rs").unwrap();
    writeln!(header, " *").unwrap();
    writeln!(
        header,
        " * Z_FEATURE_LINK_* values are derived from Cargo link-* features."
    )
    .unwrap();
    writeln!(
        header,
        " * Buffer sizes are configurable via ZPICO_* environment variables."
    )
    .unwrap();
    writeln!(header, " * DO NOT EDIT — regenerated on every build.").unwrap();
    writeln!(header, " */").unwrap();
    writeln!(header).unwrap();
    writeln!(header, "#ifndef ZENOH_GENERIC_CONFIG_H").unwrap();
    writeln!(header, "#define ZENOH_GENERIC_CONFIG_H").unwrap();
    writeln!(header).unwrap();
    writeln!(header, "// Buffer Sizes").unwrap();
    writeln!(header, "#define Z_FRAG_MAX_SIZE {}", buf.frag_max_size).unwrap();
    writeln!(
        header,
        "#define Z_BATCH_UNICAST_SIZE {}",
        buf.batch_unicast_size
    )
    .unwrap();
    writeln!(
        header,
        "#define Z_BATCH_MULTICAST_SIZE {}",
        buf.batch_multicast_size
    )
    .unwrap();

    const GENERIC_SOCKET_TIMEOUT_MS: u32 = 100;
    const NUTTX_SOCKET_TIMEOUT_MS: u32 = 5000;
    const Z_TRANSPORT_LEASE_MS: u32 = 10_000;
    let socket_timeout = if target.contains("nuttx") {
        NUTTX_SOCKET_TIMEOUT_MS
    } else {
        GENERIC_SOCKET_TIMEOUT_MS
    };
    writeln!(header, "#define Z_CONFIG_SOCKET_TIMEOUT {}", socket_timeout).unwrap();
    writeln!(header, "#define Z_TRANSPORT_LEASE {}", Z_TRANSPORT_LEASE_MS).unwrap();
    writeln!(header, "#define Z_TRANSPORT_LEASE_EXPIRE_FACTOR 3").unwrap();
    writeln!(header, "#define ZP_PERIODIC_SCHEDULER_MAX_TASKS 8").unwrap();
    writeln!(header).unwrap();
    writeln!(header, "// Core Features").unwrap();
    writeln!(header, "#ifndef Z_FEATURE_MULTI_THREAD").unwrap();
    writeln!(header, "#define Z_FEATURE_MULTI_THREAD 0").unwrap();
    writeln!(header, "#endif").unwrap();
    writeln!(header, "#define Z_FEATURE_PUBLICATION 1").unwrap();
    writeln!(header, "#define Z_FEATURE_ADVANCED_PUBLICATION 0").unwrap();
    writeln!(header, "#define Z_FEATURE_SUBSCRIPTION 1").unwrap();
    writeln!(header, "#define Z_FEATURE_ADVANCED_SUBSCRIPTION 0").unwrap();
    writeln!(header, "#define Z_FEATURE_QUERY 1").unwrap();
    writeln!(header, "#define Z_FEATURE_QUERYABLE 1").unwrap();
    writeln!(header, "#define Z_FEATURE_LIVELINESS 1").unwrap();
    writeln!(header, "#define Z_FEATURE_INTEREST 1").unwrap();
    writeln!(header).unwrap();
    writeln!(
        header,
        "// Transport Link Features (from Cargo link-* features)"
    )
    .unwrap();
    writeln!(header, "#define Z_FEATURE_LINK_TCP {}", link.tcp_flag()).unwrap();
    writeln!(
        header,
        "#define Z_FEATURE_LINK_UDP_UNICAST {}",
        link.udp_unicast_flag()
    )
    .unwrap();
    writeln!(
        header,
        "#define Z_FEATURE_LINK_UDP_MULTICAST {}",
        link.udp_multicast_flag()
    )
    .unwrap();
    writeln!(
        header,
        "#define Z_FEATURE_LINK_SERIAL {}",
        link.serial_flag()
    )
    .unwrap();
    writeln!(header, "#define Z_FEATURE_LINK_BLUETOOTH 0").unwrap();
    writeln!(header, "#define Z_FEATURE_LINK_WS 0").unwrap();
    writeln!(header, "#define Z_FEATURE_LINK_SERIAL_USB 0").unwrap();
    writeln!(header, "#define Z_FEATURE_LINK_IVC {}", link.ivc_flag()).unwrap();
    writeln!(
        header,
        "#define Z_FEATURE_LINK_CUSTOM {}",
        link.custom_flag()
    )
    .unwrap();
    writeln!(header, "#define Z_FEATURE_LINK_TLS {}", link.tls_flag()).unwrap();
    writeln!(
        header,
        "#define Z_FEATURE_RAWETH_TRANSPORT {}",
        link.raweth_flag()
    )
    .unwrap();
    writeln!(header).unwrap();
    writeln!(header, "// Transport Modes").unwrap();
    writeln!(header, "#define Z_FEATURE_UNICAST_TRANSPORT 1").unwrap();
    writeln!(header, "#define Z_FEATURE_MULTICAST_TRANSPORT 0").unwrap();
    writeln!(header, "#define Z_FEATURE_SCOUTING 0").unwrap();
    writeln!(header, "#ifndef Z_FEATURE_SCOUTING_UDP").unwrap();
    writeln!(header, "#define Z_FEATURE_SCOUTING_UDP 0").unwrap();
    writeln!(header, "#endif").unwrap();
    writeln!(header).unwrap();
    if unstable_api {
        writeln!(header, "#define Z_FEATURE_UNSTABLE_API").unwrap();
    }
    writeln!(header).unwrap();
    writeln!(header, "// Protocol Features").unwrap();
    writeln!(header, "#define Z_FEATURE_FRAGMENTATION 1").unwrap();
    let encoding_values = if orin_spe { 0 } else { 1 };
    writeln!(
        header,
        "#define Z_FEATURE_ENCODING_VALUES {}",
        encoding_values
    )
    .unwrap();
    writeln!(header, "#define Z_FEATURE_TCP_NODELAY 1").unwrap();
    // Same-session loopback (issue 0096): a single `nros::main!` entry registers every
    // node of a launch on ONE zenoh-pico session, so in-process node-to-node delivery —
    // pub→sub AND client query→queryable — depends on these flags. With them 0 the
    // loopback path (src/session/loopback.c) is compiled out and same-session callbacks
    // never fire. Enable on the HOST/native build (multi-process is optional there, so
    // single-process multi-node demos are common); keep OFF on embedded, where RAM is
    // tight and the loopback + write-filter code is unbudgeted (revisit per-target with a
    // size probe). The flags are purely additive: a local match sets the write filter to
    // OFF (filtering.c), so the network publication to external subscribers is preserved.
    let local_loopback = if is_embedded_target(target) { 0 } else { 1 };
    writeln!(
        header,
        "#define Z_FEATURE_LOCAL_SUBSCRIBER {}",
        local_loopback
    )
    .unwrap();
    writeln!(
        header,
        "#define Z_FEATURE_LOCAL_QUERYABLE {}",
        local_loopback
    )
    .unwrap();
    writeln!(header, "#define Z_FEATURE_SESSION_CHECK 1").unwrap();
    // phase-279 (#145) — Z_FEATURE_BATCHING gates transport-struct FIELDS
    // (_batch_state/_batch_count), so it must be uniform across every TU that
    // includes this header (zenoh-pico + zpico.c — the issue-0135 ABI rule).
    // Flipped here (the shared generated config) by the ZPICO_TX_BATCH knob;
    // stays 0 when the knob is off = byte-identical to today's config.
    writeln!(
        header,
        "#define Z_FEATURE_BATCHING {}",
        if tx_batch { 1 } else { 0 }
    )
    .unwrap();
    // phase-282 (#145) — Z_FEATURE_TX_SPLIT_LOCK also gates struct fields
    // (_wbuf_spare/_mutex_link_tx): same #135 every-TU rule as BATCHING.
    writeln!(
        header,
        "#define Z_FEATURE_TX_SPLIT_LOCK {}",
        if tx_split_lock && tx_batch { 1 } else { 0 }
    )
    .unwrap();
    writeln!(header, "#define Z_FEATURE_BATCH_TX_MUTEX 0").unwrap();
    writeln!(header, "#define Z_FEATURE_BATCH_PEER_MUTEX 0").unwrap();
    writeln!(header, "#define Z_FEATURE_MATCHING 1").unwrap();
    writeln!(header, "#define Z_FEATURE_RX_CACHE 0").unwrap();
    writeln!(header, "#define Z_FEATURE_UNICAST_PEER 0").unwrap();
    let auto_reconnect = if orin_spe { 0 } else { 1 };
    writeln!(
        header,
        "#define Z_FEATURE_AUTO_RECONNECT {}",
        auto_reconnect
    )
    .unwrap();
    writeln!(header, "#define Z_FEATURE_MULTICAST_DECLARATIONS 0").unwrap();
    writeln!(header, "#define Z_FEATURE_PERIODIC_TASKS 0").unwrap();
    writeln!(header).unwrap();
    writeln!(header, "#endif /* ZENOH_GENERIC_CONFIG_H */").unwrap();

    header
}

/// Check if we're building for an embedded target.
pub fn is_embedded_target(target: &str) -> bool {
    target.contains("zephyr")
        || target.contains("none")
        || target.contains("nuttx")
        || target.contains("thumbv")
        || target.contains("riscv")
}

pub fn is_plausible_generated_header(header: &str) -> bool {
    header.contains("#ifndef ZPICO_H")
        && header.contains("#define ZPICO_OK")
        && header.contains("typedef void (*ZpicoCallback)")
        && header.contains("int32_t zpico_init(")
}

/// Post-process the generated header to remove duplicate declarations.
pub fn post_process_header(header: &str) -> String {
    let mut result = String::new();
    let mut prev_blank = false;
    let mut skip_until_semicolon = false;
    let mut seen_declarations: HashSet<String> = HashSet::new();
    let mut pending_lines: Vec<String> = Vec::new();

    for line in header.lines() {
        let trimmed = line.trim();

        if line.starts_with("extern ") {
            if !trimmed.ends_with(';') {
                skip_until_semicolon = true;
            }
            continue;
        }

        if skip_until_semicolon {
            if trimmed.ends_with(';') {
                skip_until_semicolon = false;
            }
            continue;
        }

        if trimmed.starts_with("/**") || trimmed.starts_with('*') || trimmed.starts_with("*/") {
            pending_lines.push(line.to_string());
            continue;
        }

        if trimmed.starts_with("typedef ")
            && let Some(name) = extract_typedef_name(trimmed)
        {
            if seen_declarations.contains(&name) {
                pending_lines.clear();
                if !trimmed.ends_with(';') {
                    skip_until_semicolon = true;
                }
                continue;
            }
            seen_declarations.insert(name);
        }

        if (trimmed.starts_with("int32_t ")
            || trimmed.starts_with("void ")
            || trimmed.starts_with("void *")
            || trimmed.starts_with("uint32_t ")
            || trimmed.starts_with("uint64_t ")
            || trimmed.starts_with("bool "))
            && trimmed.contains('(')
            && let Some(name) = extract_function_name(trimmed)
        {
            if seen_declarations.contains(&name) {
                pending_lines.clear();
                if !trimmed.ends_with(';') {
                    skip_until_semicolon = true;
                }
                continue;
            }
            seen_declarations.insert(name);
        }

        for pending in pending_lines.drain(..) {
            result.push_str(&pending);
            result.push('\n');
        }

        let is_blank = trimmed.is_empty();
        if is_blank && prev_blank {
            continue;
        }
        prev_blank = is_blank;

        result.push_str(line);
        result.push('\n');
    }

    result
}

/// Extract function name from a declaration line.
pub fn extract_function_name(line: &str) -> Option<String> {
    let trimmed = line.trim();
    let paren_pos = trimmed.find('(')?;
    let before_paren = &trimmed[..paren_pos];
    let name = before_paren.split_whitespace().last()?;
    Some(name.trim_start_matches('*').to_string())
}

/// Extract typedef name from a declaration line.
pub fn extract_typedef_name(line: &str) -> Option<String> {
    let trimmed = line.trim();

    if let Some(start) = trimmed.find("(*") {
        let after_star = &trimmed[start + 2..];
        if let Some(end) = after_star.find(')') {
            return Some(after_star[..end].to_string());
        }
    }

    if trimmed.ends_with(';') {
        let without_semi = trimmed.trim_end_matches(';').trim();
        return without_semi
            .split_whitespace()
            .last()
            .map(|s| s.to_string());
    }

    None
}

/// Apply an `[arch.*]` profile to a `cc::Build`.
pub fn apply_arch(arch: &manifest::ArchEntry, build: &mut cc::Build, out_dir: &Path) {
    for flag in &arch.cflags {
        build.flag(flag);
    }
    if arch.needs_riscv_compiler {
        detect_riscv_compiler(build);
    }
    if arch.needs_errno_override {
        let errno_dir = out_dir.join("errno-override");
        std::fs::create_dir_all(&errno_dir).unwrap();
        std::fs::write(
            errno_dir.join("errno.h"),
            include_bytes!("../../zpico-sys/c/platform/errno_override.h"),
        )
        .unwrap();
        build.include(&errno_dir);
    }
    if arch.needs_picolibc
        && let Some(sysroot) = get_picolibc_sysroot()
    {
        build.include(sysroot.join("include"));
    }
}

/// Returns `true` when the `[arch.*]` predicates allow the current target triple.
pub fn arch_matches(arch: &manifest::ArchEntry, target: &str) -> bool {
    if let Some(needle) = arch.target_match.as_deref()
        && !target.contains(needle)
    {
        return false;
    }
    if let Some(needle) = arch.target_exclude.as_deref()
        && target.contains(needle)
    {
        return false;
    }
    true
}

/// Add the zenoh-pico core source set to a `cc::Build`.
pub fn add_zenoh_pico_core_sources(build: &mut cc::Build, zenoh_pico_src: &Path) {
    let src_dir = zenoh_pico_src.join("src");
    for subdir in &[
        "api",
        "collections",
        "link",
        "net",
        "protocol",
        "session",
        "transport",
        "utils",
    ] {
        add_c_sources_recursive(build, &src_dir.join(subdir));
    }
    add_c_sources_recursive(build, &src_dir.join("system").join("common"));
}

/// Recursively collect all .c files from a directory and add them to a cc::Build.
pub fn add_c_sources_recursive(build: &mut cc::Build, dir: &Path) {
    if !dir.exists() {
        return;
    }
    let mut entries: Vec<_> = std::fs::read_dir(dir)
        .unwrap()
        .filter_map(Result::ok)
        .collect();
    entries.sort_by_key(|e| e.file_name());
    for entry in entries {
        let path = entry.path();
        if path.is_dir() {
            add_c_sources_recursive(build, &path);
        } else if path.extension().is_some_and(|ext| ext == "c") {
            build.file(&path);
        }
    }
}

/// Detect and set the RISC-V cross-compiler for cc::Build.
pub fn detect_riscv_compiler(build: &mut cc::Build) {
    for cc_name in &["riscv64-unknown-elf-gcc", "riscv32-esp-elf-gcc"] {
        if Command::new(cc_name).arg("--version").output().is_ok() {
            build.compiler(cc_name);
            return;
        }
    }
}

/// Get the picolibc sysroot path for RISC-V.
pub fn get_picolibc_sysroot() -> Option<PathBuf> {
    for cc_name in &["riscv64-unknown-elf-gcc", "riscv32-esp-elf-gcc"] {
        if let Ok(output) = Command::new(cc_name)
            .args([
                "-march=rv32imc",
                "-mabi=ilp32",
                "--specs=picolibc.specs",
                "-print-sysroot",
            ])
            .output()
            && output.status.success()
        {
            let sysroot = String::from_utf8_lossy(&output.stdout).trim().to_string();
            if !sysroot.is_empty() {
                let path = PathBuf::from(&sysroot);
                if path.join("include").exists() {
                    return Some(path);
                }
            }
        }
    }
    let fallback = PathBuf::from("/usr/lib/picolibc/riscv64-unknown-elf");
    if fallback.join("include").exists() {
        return Some(fallback);
    }
    None
}

/// Check if the RISC-V GCC supports picolibc specs.
pub fn has_picolibc_specs() -> bool {
    for cc in &["riscv64-unknown-elf-gcc", "riscv32-esp-elf-gcc"] {
        if let Ok(status) = Command::new(cc)
            .args([
                "-march=rv32imc",
                "-mabi=ilp32",
                "--specs=picolibc.specs",
                "-E",
                "-x",
                "c",
                "/dev/null",
                "-o",
                "/dev/null",
            ])
            .status()
            && status.success()
        {
            return true;
        }
    }
    false
}

/// Read the size of a symbol from a static library using llvm-nm or nm.
pub fn read_symbol_size(
    archive: &Path,
    symbol: &str,
    rustc_sysroot: Option<&str>,
    host: &str,
) -> usize {
    let sysroot = rustc_sysroot.map(ToOwned::to_owned).or_else(|| {
        Command::new("rustc")
            .args(["--print", "sysroot"])
            .output()
            .ok()
            .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
    });

    let llvm_nm_candidates = [
        sysroot
            .as_ref()
            .map(|s| {
                PathBuf::from(s)
                    .join("lib/rustlib")
                    .join(host)
                    .join("bin/llvm-nm")
            })
            .unwrap_or_default(),
        PathBuf::from("llvm-nm"),
        PathBuf::from("nm"),
    ];

    for nm in &llvm_nm_candidates {
        if let Ok(output) = Command::new(nm)
            .args(["--print-size", "--defined-only"])
            .arg(archive)
            .output()
            && output.status.success()
        {
            let stdout = String::from_utf8_lossy(&output.stdout);
            for line in stdout.lines() {
                if line.contains(symbol) {
                    let parts: Vec<&str> = line.split_whitespace().collect();
                    if parts.len() >= 2
                        && let Ok(size) = usize::from_str_radix(parts[1], 16)
                        && size > 0
                    {
                        return size;
                    }
                }
            }
        }
    }

    eprintln!(
        "cargo:warning=Could not determine size of {} from {}, using fallback 16",
        symbol,
        archive.display()
    );
    16
}

/// Generate pkg-config `.pc` file contents for mbedTLS.
pub fn mbedtls_pc_files(lib_dir: &str) -> [(&'static str, String); 3] {
    fn pc(name: &str, libs: &str, requires: &str, lib_dir: &str) -> String {
        format!(
            "prefix=/usr\n\
             libdir={lib_dir}\n\
             includedir=/usr/include\n\n\
             Name: {name}\n\
             Description: mbed TLS - {name}\n\
             Version: 2.28.0\n\
             Libs: -L${{libdir}} {libs}\n\
             Cflags: -I${{includedir}}\n\
             Requires: {requires}\n"
        )
    }

    [
        ("mbedcrypto", pc("mbedcrypto", "-lmbedcrypto", "", lib_dir)),
        (
            "mbedx509",
            pc("mbedx509", "-lmbedx509", "mbedcrypto", lib_dir),
        ),
        ("mbedtls", pc("mbedtls", "-lmbedtls", "mbedx509", lib_dir)),
    ]
}

/// Generate zenoh-pico version header contents.
pub fn embedded_version_header(version: &str, template: &str) -> String {
    let version = version.trim();
    let parts: Vec<&str> = version.split('.').collect();
    let major = parts.first().unwrap_or(&"0");
    let minor = parts.get(1).unwrap_or(&"0");
    let patch = parts.get(2).unwrap_or(&"0");

    template
        .replace("@ZENOH_PICO@", version)
        .replace("@ZENOH_PICO_MAJOR@", major)
        .replace("@ZENOH_PICO_MINOR@", minor)
        .replace("@ZENOH_PICO_PATCH@", patch)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extracts_function_names_from_c_declarations() {
        assert_eq!(
            extract_function_name("int32_t zpico_init(const char *locator);").as_deref(),
            Some("zpico_init")
        );
        assert_eq!(
            extract_function_name("void *zpico_loan(size_t len);").as_deref(),
            Some("zpico_loan")
        );
    }

    #[test]
    fn extracts_typedef_names() {
        assert_eq!(
            extract_typedef_name("typedef void (*ZpicoCallback)(void *ctx);").as_deref(),
            Some("ZpicoCallback")
        );
        assert_eq!(
            extract_typedef_name("typedef struct zpico_session ZpicoSession;").as_deref(),
            Some("ZpicoSession")
        );
    }

    #[test]
    fn post_process_header_removes_externs_and_duplicate_declarations() {
        let header = "\
extern int hidden;\n\
/** first */\n\
typedef int ZpicoFoo;\n\
/** duplicate */\n\
typedef int ZpicoFoo;\n\
\n\
\n\
int32_t zpico_init(void);\n\
int32_t zpico_init(void);\n";
        let processed = post_process_header(header);

        assert!(!processed.contains("extern int hidden"));
        assert!(processed.contains("/** first */\ntypedef int ZpicoFoo;"));
        assert!(!processed.contains("duplicate"));
        assert_eq!(processed.matches("zpico_init").count(), 1);
        assert!(!processed.contains("\n\n\n"));
    }

    #[test]
    fn shim_consts_are_generated_from_config() {
        let cfg = ShimConfig {
            max_publishers: 1,
            max_subscribers: 2,
            max_queryables: 3,
            max_liveliness: 4,
            max_pending_gets: 5,
            get_reply_buf_size: 6,
            get_poll_interval_ms: 7,
            tx_batch: false,
            tx_batch_flush_ms: 50,
        };

        let body = cfg.rust_consts();
        assert!(body.contains("ZPICO_MAX_PUBLISHERS: usize = 1;"));
        assert!(body.contains("ZPICO_MAX_PENDING_GETS: usize = 5;"));
        assert!(!body.contains("get_reply_buf_size"));
    }

    #[test]
    fn config_header_uses_resolved_link_and_platform_values() {
        let link = LinkFeatures {
            tcp: true,
            udp_unicast: false,
            udp_multicast: false,
            serial: true,
            raweth: false,
            tls: true,
            ivc: false,
            custom: true,
        };
        let buf = ZenohBufferConfig {
            frag_max_size: 4096,
            batch_unicast_size: 2048,
            batch_multicast_size: 1024,
        };

        let header = config_header(&link, &buf, "armv7a-nuttx-eabihf", true, true, false, false);

        assert!(header.contains("#define Z_FRAG_MAX_SIZE 4096"));
        assert!(header.contains("#define Z_CONFIG_SOCKET_TIMEOUT 5000"));
        assert!(header.contains("#define Z_FEATURE_LINK_TCP 1"));
        assert!(header.contains("#define Z_FEATURE_LINK_UDP_UNICAST 0"));
        assert!(header.contains("#define Z_FEATURE_LINK_TLS 1"));
        assert!(header.contains("#define Z_FEATURE_LINK_CUSTOM 1"));
        assert!(header.contains("#define Z_FEATURE_UNSTABLE_API"));
        assert!(header.contains("#define Z_FEATURE_ENCODING_VALUES 0"));
        assert!(header.contains("#define Z_FEATURE_AUTO_RECONNECT 0"));
        // issue 0096 — same-session loopback stays OFF on embedded (RAM-budgeted).
        assert!(header.contains("#define Z_FEATURE_LOCAL_SUBSCRIBER 0"));
        assert!(header.contains("#define Z_FEATURE_LOCAL_QUERYABLE 0"));
    }

    #[test]
    fn host_build_enables_same_session_loopback() {
        // issue 0096 — the HOST/native build compiles in zenoh-pico's same-session
        // loopback so two nodes of one `nros::main!` entry can talk in-process.
        let link = LinkFeatures {
            tcp: true,
            udp_unicast: false,
            udp_multicast: false,
            serial: false,
            raweth: false,
            tls: false,
            ivc: false,
            custom: false,
        };
        let buf = ZenohBufferConfig {
            frag_max_size: 4096,
            batch_unicast_size: 2048,
            batch_multicast_size: 1024,
        };

        let header = config_header(
            &link,
            &buf,
            "x86_64-unknown-linux-gnu",
            false,
            false,
            false,
            false,
        );

        assert!(header.contains("#define Z_FEATURE_LOCAL_SUBSCRIBER 1"));
        assert!(header.contains("#define Z_FEATURE_LOCAL_QUERYABLE 1"));
    }

    #[test]
    fn mbedtls_pc_files_point_at_requested_lib_dir() {
        let files = mbedtls_pc_files("/opt/lib");

        assert_eq!(files[0].0, "mbedcrypto");
        assert!(files[0].1.contains("libdir=/opt/lib"));
        assert!(files[1].1.contains("Requires: mbedcrypto"));
        assert!(files[2].1.contains("Requires: mbedx509"));
    }

    #[test]
    fn version_header_replaces_template_tokens() {
        let template = "@ZENOH_PICO@ @ZENOH_PICO_MAJOR@ @ZENOH_PICO_MINOR@ @ZENOH_PICO_PATCH@";
        assert_eq!(embedded_version_header("1.2.3\n", template), "1.2.3 1 2 3");
    }

    #[test]
    fn embedded_target_detection_matches_supported_families() {
        assert!(is_embedded_target("thumbv7em-none-eabihf"));
        assert!(is_embedded_target("riscv32imc-unknown-none-elf"));
        assert!(is_embedded_target("armv7a-nuttx-eabihf"));
        assert!(!is_embedded_target("x86_64-unknown-linux-gnu"));
    }
}
