meta:
  version: 1
  inputs:
  - path: launch/system.launch.xml
    sha256: 1a67dea174e80f21abf69e3b949f3c83a26c1781166e85a02904bb093f51c141
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
structure:
  scopes:
    system.launch.xml:
      file: system.launch.xml
