//! Gather the generated `px4_msgs` FFI pair into one `include!`-able file.
//!
//! `nros generate-px4-msgs --lang cpp` writes `<name>_types.rs` + `<name>_exports.rs`
//! per message into `$NROS_PX4_BRIDGE_GEN/px4_msgs/msg/`. Rather than restate the
//! topic list here (a second source for it — the thing issue 0362 warns about for
//! the type hash), glob whatever the generator wrote: the recipe's `--topics` is
//! the single source of truth.
use std::{env, fs, path::PathBuf};

fn main() {
    let gen_dir = PathBuf::from(env::var("NROS_PX4_BRIDGE_GEN").expect(
        "NROS_PX4_BRIDGE_GEN must point at the `nros generate-px4-msgs --lang cpp` output",
    ))
    .join("px4_msgs")
    .join("msg");
    println!("cargo:rerun-if-env-changed=NROS_PX4_BRIDGE_GEN");
    println!("cargo:rerun-if-changed={}", gen_dir.display());

    // `_types.rs` defines the repr(C) mirrors; `_exports.rs` defines the
    // `extern "C"` bodies that reference them, so types must come first.
    let mut types = Vec::new();
    let mut exports = Vec::new();
    for entry in fs::read_dir(&gen_dir)
        .unwrap_or_else(|e| panic!("read generated dir {}: {e}", gen_dir.display()))
    {
        let path = entry.expect("dir entry").path();
        let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
            continue;
        };
        if name.ends_with("_types.rs") {
            types.push(path);
        } else if name.ends_with("_exports.rs") {
            exports.push(path);
        }
    }
    assert!(
        !types.is_empty(),
        "no *_types.rs under {} — run `nros generate-px4-msgs --lang cpp` first",
        gen_dir.display()
    );
    types.sort();
    exports.sort();

    let mut out = String::from("// Generated by build.rs — do not edit.\n");
    for p in types.into_iter().chain(exports) {
        out.push_str(&format!("include!({:?});\n", p.display().to_string()));
    }
    let dest = PathBuf::from(env::var("OUT_DIR").unwrap()).join("px4_msgs_ffi.rs");
    fs::write(&dest, out).expect("write px4_msgs_ffi.rs");
}
