#!/usr/bin/env python3
"""Extract named `run:` steps from a GitHub workflow into one bash script
(phase-447 A3 — the installed-path probe builds its asset THIS way).

WHY THE PROBE READS THE RELEASE WORKFLOW INSTEAD OF STAGING ITS OWN ASSET

The clean-host probe has to install a release that does not exist yet
(`installation.md`: "No release has been cut yet"). So it builds one. The
question is what "one" means, and there is exactly one honest answer: what
`release-nros.yml` would publish. A probe that carried its own list of what an
asset contains would be a SECOND implementation of that list, and it would
stay green on the day the workflow dropped a line — the precise failure
`check-release-manifest` R5 was first written with (it read the install probe's
MENTION of `bin/nros-launch-resolve` and passed with the staging `cp` deleted).

This is the same move `extract-book-steps.py` makes for the user side: the
book is the SSoT for what a user types, the release workflow is the SSoT for
what a user downloads, and the probe executes both rather than restating
either. It is also what makes the probe's mutation direction mean something —
revert phase-447 A1 and the workflow stops staging `share/nano-ros`, so the
probe builds exactly the asset that dead-ends, and fails where a user would.

Steps are selected BY NAME and emitted in the order given. A missing name, a
step with no `run:`, or a GitHub expression the caller did not substitute is a
hard error — a probe that silently ran a shorter pipeline is the false green
this file exists to prevent.

Usage:
  extract-workflow-steps.py --workflow W.yml --job build --out steps.sh \
      --step 'Build the CLI from source' --step 'Stage the prefix' \
      [--expr 'inputs.version=0.0.0-probe' ...]
"""

import argparse
import re
import shlex
import sys
from pathlib import Path

import yaml

EXPR_RE = re.compile(r"\$\{\{\s*([^}]*?)\s*\}\}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--workflow", required=True)
    ap.add_argument("--job", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--step", action="append", required=True,
                    help="step name, exactly as in the workflow; repeatable, in run order")
    ap.add_argument("--expr", action="append", default=[],
                    help="NAME=VALUE for a `${{ NAME }}` expression; every expression "
                         "in a selected step must have one")
    ap.add_argument("--runner-image-out",
                    help="write the docker image equivalent to the job's `runs-on` "
                         "here (`ubuntu-22.04` -> `ubuntu:22.04`), so the probe builds "
                         "on the base the release pins rather than on a second copy "
                         "of that decision")
    args = ap.parse_args()

    wf_path = Path(args.workflow)
    wf = yaml.safe_load(wf_path.read_text())
    job = (wf.get("jobs") or {}).get(args.job)
    if job is None:
        sys.exit(f"probe workflow extract: {wf_path} has no job '{args.job}'")

    if args.runner_image_out:
        runs_on = job.get("runs-on")
        m = re.fullmatch(r"ubuntu-(\d+\.\d+)", str(runs_on))
        if not m:
            # `ubuntu-latest` or a self-hosted label names no fixed base, and
            # the whole point of reading this is that the release PINS one —
            # its glibc and libpython are the asset's ABI floor.
            sys.exit(
                f"probe workflow extract: job '{args.job}' runs on {runs_on!r}, "
                "which names no pinned Ubuntu base the probe can reproduce"
            )
        Path(args.runner_image_out).write_text(f"ubuntu:{m.group(1)}\n")
    steps = {s.get("name"): s for s in job.get("steps", []) if isinstance(s, dict)}

    exprs = {}
    for e in args.expr:
        if "=" not in e:
            sys.exit(f"probe workflow extract: bad --expr (no '='): {e}")
        k, v = e.split("=", 1)
        exprs[k.strip()] = v

    out = [
        "#!/usr/bin/env bash",
        "# GENERATED by scripts/probe/extract-workflow-steps.py — DO NOT EDIT.",
        f"# Source of truth: the named steps of job '{args.job}' in {wf_path.name}.",
        "# Each step runs in its OWN `bash -e` from $GITHUB_WORKSPACE, as a runner",
        "# executes a `run:` with no `shell:` — so no state leaks between steps",
        "# that would not leak on GitHub.",
        "set -euo pipefail",
    ]
    for name in args.step:
        step = steps.get(name)
        if step is None:
            known = "\n  ".join(n for n in steps if n)
            sys.exit(
                f"probe workflow extract: {wf_path} job '{args.job}' has no step "
                f"named {name!r}. The workflow drifted from the probe — rename the "
                f"--step in run-bootstrap-probe.sh. Steps it does have:\n  {known}"
            )
        body = step.get("run")
        if not body:
            sys.exit(f"probe workflow extract: step {name!r} has no `run:` block")
        if step.get("if"):
            sys.exit(
                f"probe workflow extract: step {name!r} is conditional "
                f"(if: {step['if']}); the probe cannot decide that for it"
            )

        def subst(m, name=name):
            key = m.group(1)
            if key not in exprs:
                sys.exit(
                    f"probe workflow extract: step {name!r} uses ${{{{ {key} }}}}, "
                    "which the probe does not supply — add an --expr for it, or "
                    "the step reads runner state the probe cannot reproduce"
                )
            return exprs[key]

        body = EXPR_RE.sub(subst, body)
        out.append("")
        out.append(f"echo {shlex.quote(f'=== release step: {name} ===')}")
        out.append(f'( cd "$GITHUB_WORKSPACE" && bash -e <<\'NROS_PROBE_STEP_EOF\'')
        out.append(body.rstrip("\n"))
        out.append("NROS_PROBE_STEP_EOF")
        out.append(")")

    Path(args.out).write_text("\n".join(out) + "\n")
    print(f"probe workflow extract: {len(args.step)} steps -> {args.out}")


if __name__ == "__main__":
    main()
