//! `nros explain` — human-readable rendering of a generated `nros-plan.json`.
//!
//! Phase 172.F. Reads the plan (the same artifact `nros check` validates) and
//! prints a structured walkthrough so a user can answer, without parsing JSON:
//! which launch instance maps to which component, the nodes + their endpoints
//! (topic + interface + QoS), how each parameter resolved (and from which
//! artifact), why a callback got its SchedContext, and what the scheduling
//! table contains. Read-only: it touches no runtime code or plan schema.

use std::{io::Write, path::PathBuf};

use clap::Args as ClapArgs;
use eyre::{Result, WrapErr};

use crate::orchestration::{
    plan::{NrosPlan, PlanEntity, TransportKind},
    schema::{DeadlinePolicy, InterfaceRef, ParameterValue, QosProfile, SchedClass},
};

#[derive(Debug, ClapArgs)]
pub struct Args {
    /// Path to nros-plan.json
    #[arg(default_value = "build/nros/nros-plan.json")]
    pub plan: PathBuf,
}

pub fn run(args: Args) -> Result<()> {
    let raw = std::fs::read_to_string(&args.plan)
        .wrap_err_with(|| format!("read {}", args.plan.display()))?;
    let plan: NrosPlan = serde_json::from_str(&raw)
        .wrap_err_with(|| format!("parse nros-plan.json schema at {}", args.plan.display()))?;
    let stdout = std::io::stdout();
    render(&plan, &mut stdout.lock()).wrap_err("write explanation")?;
    Ok(())
}

/// Render the plan to `w`. Returns the first write error; on a terminal this is
/// infallible, but a piped/closed sink can fail mid-stream.
pub fn render<W: Write>(plan: &NrosPlan, w: &mut W) -> std::io::Result<()> {
    writeln!(
        w,
        "nros explain — system `{}`  (plan schema v{})",
        plan.system, plan.version
    )?;
    writeln!(w, "  generated by : {}", plan.trace.generated_by)?;
    writeln!(w, "  system config: {}", plan.trace.system_config)?;
    writeln!(w, "  launch record: {}", plan.trace.launch_record)?;
    writeln!(w)?;

    // Build target the plan compiles to.
    let b = &plan.build;
    write!(
        w,
        "Build: target={} board={} rmw={} profile={}",
        b.target, b.board, b.rmw, b.profile
    )?;
    if !b.features.is_empty() {
        write!(w, "  features=[{}]", b.features.join(", "))?;
    }
    writeln!(w)?;
    writeln!(w)?;

    // Components.
    writeln!(w, "Components ({}):", plan.components.len())?;
    for c in &plan.components {
        let cfg = c
            .component_config
            .as_deref()
            .map(|s| format!("  config={s}"))
            .unwrap_or_default();
        writeln!(
            w,
            "  {:<18} {}::{}  [{}]{}",
            c.id, c.package, c.component, c.language, cfg
        )?;
    }
    writeln!(w)?;

    // Instances: the launch-instance → component map, then each instance's
    // nodes/endpoints, resolved parameters, and scheduling bindings.
    writeln!(
        w,
        "Instances ({})   (launch instance → component):",
        plan.instances.len()
    )?;
    for inst in &plan.instances {
        writeln!(
            w,
            "  {} → {}   ns={}  exec={}::{}",
            inst.launch_name,
            inst.component,
            ns_or_root(&inst.namespace),
            inst.package,
            inst.executable
        )?;
        for rm in &inst.remaps {
            writeln!(w, "      remap: {} → {}", rm.from, rm.to)?;
        }
        for node in &inst.nodes {
            writeln!(
                w,
                "      node {}   (source: {})",
                node.resolved_name, node.source_node
            )?;
            for e in &node.entities {
                writeln!(w, "        {}", entity_line(e))?;
            }
        }
        if !inst.parameters.is_empty() {
            writeln!(w, "      parameters  (name = value  [resolved from]):")?;
            for p in &inst.parameters {
                writeln!(
                    w,
                    "        {} = {}   [{} @ {}]",
                    p.name,
                    value_str(&p.value),
                    source_kind_str(&p.source.kind),
                    p.source.artifact
                )?;
            }
        }
        if !inst.sched_bindings.is_empty() {
            writeln!(w, "      sched bindings  (callback → context):")?;
            for sb in &inst.sched_bindings {
                let prio = sb
                    .priority
                    .map(|v| format!(" prio={v}"))
                    .unwrap_or_default();
                writeln!(
                    w,
                    "        {} → {}{}   (from {})",
                    sb.callback, sb.context, prio, sb.source
                )?;
            }
        }
        writeln!(w)?;
    }

    // Issue 0259 — what the realizer concluded, shown before the table it
    // produced. Ordered that way deliberately: a reader who sees "this node's
    // declaration is infeasible" should see it BEFORE the priorities derived
    // for it, not as a footnote after them.
    if !plan.sched_warnings.is_empty() {
        writeln!(
            w,
            "Derived-schedule verdicts ({}):",
            plan.sched_warnings.len()
        )?;
        for sw in &plan.sched_warnings {
            writeln!(w, "  {} [{}]", sw.node, sw.dim)?;
            writeln!(w, "      {}", sw.reason)?;
        }
        writeln!(w)?;
    }

    // The scheduling table the runtime is generated against.
    if !plan.sched_contexts.is_empty() {
        writeln!(
            w,
            "SchedContexts ({})   (the generated scheduling table):",
            plan.sched_contexts.len()
        )?;
        for s in &plan.sched_contexts {
            let mut bits = vec![format!("class={}", sched_class_str(&s.class))];
            if let Some(p) = s.priority {
                bits.push(format!("prio={p}"));
            }
            if let Some(v) = s.period_ms {
                bits.push(format!("period={v}ms"));
            }
            if let Some(v) = s.budget_ms {
                bits.push(format!("budget={v}ms"));
            }
            if let Some(v) = s.deadline_ms {
                bits.push(format!(
                    "deadline={v}ms({})",
                    deadline_policy_str(&s.deadline_policy)
                ));
            }
            if let Some(v) = s.core {
                bits.push(format!("core={v}"));
            }
            if let Some(ref t) = s.task {
                bits.push(format!("task={t}"));
            }
            writeln!(
                w,
                "  {:<16} executor={}  {}",
                s.id,
                s.executor,
                bits.join(" ")
            )?;
        }
        writeln!(w)?;
    }

    // Transports (bridge mode = more than one).
    if !plan.build.transports.is_empty() {
        writeln!(w, "Transports ({}):", plan.build.transports.len())?;
        for t in &plan.build.transports {
            let id =
                t.id.as_deref()
                    .map(|s| format!(" id={s}"))
                    .unwrap_or_default();
            let detail = transport_detail(t);
            let rmw = t
                .rmw
                .as_deref()
                .map(|s| format!(" rmw={s}"))
                .unwrap_or_default();
            writeln!(w, "  {}{}{}{}", transport_kind_str(t.kind), id, detail, rmw)?;
        }
        writeln!(w)?;
    }

    // Additive sections (only present on newer plans).
    if let Some(ref lc) = plan.lifecycle {
        writeln!(w, "Lifecycle: managed node, autostart={:?}", lc.autostart)?;
    }
    if !plan.callback_chains.is_empty() {
        writeln!(
            w,
            "Callback chains: {} (dataflow-inferred)",
            plan.callback_chains.len()
        )?;
    }
    if !plan.callback_groups.is_empty() {
        writeln!(w, "Callback groups: {}", plan.callback_groups.len())?;
    }
    Ok(())
}

fn ns_or_root(ns: &str) -> &str {
    if ns.is_empty() { "/" } else { ns }
}

fn entity_line(e: &PlanEntity) -> String {
    match e {
        PlanEntity::Publisher {
            resolved_name,
            interface,
            qos,
            ..
        } => format!(
            "pub  {}  {}  [{}]",
            resolved_name,
            iface_str(interface),
            qos_str(qos)
        ),
        PlanEntity::Subscriber {
            resolved_name,
            interface,
            qos,
            callback,
            ..
        } => format!(
            "sub  {}  {}  [{}]{}",
            resolved_name,
            iface_str(interface),
            qos_str(qos),
            cb_suffix(callback)
        ),
        // Issue #505 — render the period at the resolution it was DECLARED at.
        // A whole-millisecond timer still prints `10ms` (the overwhelming case,
        // and what every existing expectation reads); a 33.333 ms or
        // sub-millisecond one prints microseconds instead of the truncated
        // value that `period_ms` alone would show.
        PlanEntity::Timer {
            period_ms,
            period_us,
            callback,
            ..
        } => {
            let us = period_us.unwrap_or_else(|| period_ms.saturating_mul(1_000));
            if us % 1_000 == 0 {
                format!("timer  {}ms{}", us / 1_000, cb_suffix(callback))
            } else {
                format!("timer  {us}us{}", cb_suffix(callback))
            }
        }
        PlanEntity::ServiceServer {
            resolved_name,
            interface,
            callback,
            ..
        } => format!(
            "srv-server  {}  {}{}",
            resolved_name,
            iface_str(interface),
            cb_suffix(callback)
        ),
        PlanEntity::ServiceClient {
            resolved_name,
            interface,
            ..
        } => format!("srv-client  {}  {}", resolved_name, iface_str(interface)),
        PlanEntity::ActionServer {
            resolved_name,
            interface,
            callback,
            ..
        } => format!(
            "action-server  {}  {}{}",
            resolved_name,
            iface_str(interface),
            cb_suffix(callback)
        ),
        PlanEntity::ActionClient {
            resolved_name,
            interface,
            ..
        } => format!("action-client  {}  {}", resolved_name, iface_str(interface)),
    }
}

fn cb_suffix(callback: &Option<String>) -> String {
    callback
        .as_deref()
        .map(|c| format!("  → {c}"))
        .unwrap_or_default()
}

fn iface_str(i: &InterfaceRef) -> String {
    format!("{}/{}", i.package, i.name)
}

fn qos_str(q: &QosProfile) -> String {
    format!(
        "{:?}/{:?}/{:?}({})",
        q.reliability, q.durability, q.history, q.depth
    )
}

fn value_str(v: &ParameterValue) -> String {
    match v {
        ParameterValue::Bool(b) => b.to_string(),
        ParameterValue::Integer(i) => i.to_string(),
        ParameterValue::Float(f) => f.to_string(),
        ParameterValue::String(s) => format!("\"{s}\""),
        ParameterValue::BoolArray(a) => format!("{a:?}"),
        ParameterValue::IntegerArray(a) => format!("{a:?}"),
        ParameterValue::FloatArray(a) => format!("{a:?}"),
        ParameterValue::StringArray(a) => format!("{a:?}"),
    }
}

fn source_kind_str(k: &crate::orchestration::plan::ParameterSourceKind) -> &'static str {
    use crate::orchestration::plan::ParameterSourceKind::*;
    match k {
        SourceDefault => "source default",
        ComponentConfig => "component config",
        SystemOverlay => "system overlay",
        Launch => "launch",
    }
}

fn sched_class_str(c: &SchedClass) -> &'static str {
    match c {
        SchedClass::BestEffort => "best-effort",
        SchedClass::RealTime => "real-time",
        SchedClass::TimeTriggered => "time-triggered",
        SchedClass::Interrupt => "interrupt",
    }
}

fn deadline_policy_str(p: &DeadlinePolicy) -> &'static str {
    match p {
        DeadlinePolicy::Ignore => "ignore",
        DeadlinePolicy::Warn => "warn",
        DeadlinePolicy::Skip => "skip",
        DeadlinePolicy::Fault => "fault",
    }
}

fn transport_kind_str(k: TransportKind) -> &'static str {
    match k {
        TransportKind::Ethernet => "ethernet",
        TransportKind::Wifi => "wifi",
        TransportKind::Serial => "serial",
        TransportKind::Can => "can",
    }
}

fn transport_detail(t: &crate::orchestration::plan::PlanTransport) -> String {
    let mut parts = Vec::new();
    if let Some(ref ip) = t.ip {
        parts.push(format!(" ip={ip}"));
    }
    if let Some(ref dev) = t.device {
        parts.push(format!(" device={dev}"));
    }
    if let Some(baud) = t.baudrate {
        parts.push(format!(" baud={baud}"));
    }
    parts.join("")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::orchestration::{plan::EntityTrace, schema::SourceLocation};

    fn timer(period_ms: u64, period_us: Option<u64>) -> PlanEntity {
        PlanEntity::Timer {
            id: "t".into(),
            source_entity: "n".into(),
            callback: None,
            period_ms,
            period_us,
            trace: EntityTrace {
                source_artifact: SourceLocation {
                    artifact: "system.toml".into(),
                    line: None,
                    column: None,
                },
                manifest_endpoint: None,
                declaration_slot: None,
            },
        }
    }

    /// Issue 0519 — the plan said `0ms` for a timer firing at 500 µs.
    ///
    /// `#505` gave the runtime microsecond resolution and added `period_us`
    /// beside the truncating `period_ms`; the plan path kept reading only the
    /// truncating one, so a sub-millisecond timer was REPORTED at a rate it does
    /// not run at. The render was fixed to prefer `period_us`; nothing pinned
    /// it, so the exact defect could return silently.
    #[test]
    fn a_sub_millisecond_timer_is_not_reported_as_zero() {
        let line = entity_line(&timer(0, Some(500)));
        assert!(
            line.contains("500us"),
            "a 500 µs timer must report its real period, got {line:?}"
        );
        assert!(
            !line.contains("0ms"),
            "issue 0519 is back — the plan reports a rate the timer does not run at: {line:?}"
        );
    }

    /// The overwhelming case, and what every existing expectation reads: a
    /// whole-millisecond timer still prints milliseconds. A fix that rendered
    /// `10000us` everywhere would satisfy the test above and be a regression.
    #[test]
    fn a_whole_millisecond_timer_still_prints_milliseconds() {
        assert!(entity_line(&timer(10, Some(10_000))).contains("10ms"));
    }

    /// A plan written before #505 carries only `period_ms`. Absent `period_us`
    /// means "`period_ms` widened", not "zero" — those fixtures are legitimate
    /// inputs, which is why the fix prefers-and-falls-back rather than
    /// replacing the field.
    #[test]
    fn a_pre_505_plan_without_period_us_widens_the_millisecond_field() {
        assert!(entity_line(&timer(25, None)).contains("25ms"));
    }

    /// Issue 0259 — a realizer verdict reaches the artifact AND the reader.
    ///
    /// Built by DESERIALISING a plan rather than constructing the struct: that
    /// exercises the schema too, so this fails if `sched_warnings` ever stops
    /// round-tripping through `nros-plan.json` — which is the whole point of
    /// routing verdicts there instead of onto stderr.
    fn plan_json(extra: &str) -> NrosPlan {
        let src = format!(
            r#"{{
              "version": 2,
              "system": "demo",
              "trace": {{
                "system_config": "system.toml",
                "launch_record": "rec.json",
                "generated_by": "test"
              }},
              "components": [],
              "instances": [],
              "interfaces": [],
              "sched_contexts": [],
              "build": {{
                "target": "native",
                "board": "linux",
                "rmw": "zenoh",
                "profile": "dev",
                "features": [],
                "cfg": {{}}
              }}{extra}
            }}"#
        );
        serde_json::from_str(&src).expect("plan json must parse")
    }

    #[test]
    fn explain_shows_derived_schedule_verdicts_with_their_inputs() {
        let plan = plan_json(
            r#",
              "sched_warnings": [
                {
                  "node": "/perception",
                  "dim": "feasibility",
                  "reason": "C=6000us + B=5000us > D=10000us"
                }
              ]"#,
        );
        assert_eq!(plan.sched_warnings.len(), 1, "the field must round-trip");

        let mut out = Vec::new();
        render(&plan, &mut out).expect("render");
        let text = String::from_utf8(out).expect("utf8");

        assert!(text.contains("/perception"), "{text}");
        assert!(text.contains("feasibility"), "{text}");
        assert!(
            text.contains("C=6000us + B=5000us > D=10000us"),
            "the verdict must carry its inputs, not just a label: {text}"
        );
    }

    /// A plan with no verdicts renders no section — silence rather than an
    /// empty heading, so `explain` output stays byte-identical for systems that
    /// derive nothing.
    #[test]
    fn explain_is_silent_when_there_are_no_verdicts() {
        let plan = plan_json("");
        assert!(plan.sched_warnings.is_empty());
        let mut out = Vec::new();
        render(&plan, &mut out).expect("render");
        let text = String::from_utf8(out).expect("utf8");
        assert!(!text.contains("Derived-schedule verdicts"), "{text}");
    }
}
