meta:
  version: 1
  inputs:
  - path: launch/system.launch.xml
    sha256: 78e80db76c80cbf4fada1ba2a73062c7c1ce2d9d4e0a5bcb134d643cbbfd1bcf
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
structure:
  scopes:
    system.launch.xml:
      file: system.launch.xml
