meta:
  version: 1
  inputs:
  - path: launch/action_client.launch.xml
    sha256: 101307ea5bd41555bf03330675d82fca01325b7aefc0aa0de1034f307413e335
  - path: system.toml
    sha256: cca0a561c85937d8b1cce9b18cf321e7c7c1e8e299aec8e7cfc5b848cd9e1fe7
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
  diagnostics:
  - 'system config: [deploy.robot1] places unknown node ''/talker'' (absent in this variant?)'
  - 'system config: [deploy.robot2] places unknown node ''/listener'' (absent in this variant?)'
structure:
  scopes:
    action_client.launch.xml:
      file: action_client.launch.xml
  nodes:
    /fib_client:
      scope: action_client.launch.xml
      pkg: action_client_pkg
      exec: fib_client
      node_name: fib_client
execution:
  deploy:
    /fib_client:
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
