meta:
  version: 1
  inputs:
  - path: /home/aeon/repos/nano-ros/examples/workspaces/c/src/demo_bringup/launch/multihost.launch.xml
    sha256: 2d5adbc9d9593fafe81e1133a4c8614d41cbca33788c35f8b944156d91c02e37
  resolver:
    tool: play_launch
    version: 0.8.2
structure:
  scopes:
    multihost.launch.xml:
      file: multihost.launch.xml
  nodes:
    /listener:
      scope: multihost.launch.xml
      pkg: c_listener_pkg
      exec: listener
      node_name: listener
    /talker:
      scope: multihost.launch.xml
      pkg: c_talker_pkg
      exec: talker
      node_name: talker
execution:
  deploy:
    /listener:
      host: robot2
    /talker:
      host: robot1
