meta:
  version: 1
  inputs:
  - path: launch/multihost.launch.xml
    sha256: 2d5adbc9d9593fafe81e1133a4c8614d41cbca33788c35f8b944156d91c02e37
  - path: system.toml
    sha256: 1bbe619b8faaa76594e5dd1c5aece9f22453b42bb6468cb7acdeda9f0034572c
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
structure:
  scopes:
    multihost.launch.xml:
      file: multihost.launch.xml
  nodes:
    /listener:
      scope: multihost.launch.xml
      pkg: c_listener_pkg
      exec: listener
      node_name: listener
    /talker:
      scope: multihost.launch.xml
      pkg: c_talker_pkg
      exec: talker
      node_name: talker
execution:
  deploy:
    /listener:
      target: linux
      host: robot2
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: robot2
        kind: self
        target: x86_64-unknown-linux-gnu
    /talker:
      target: linux
      host: robot1
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: robot1
        kind: self
        target: x86_64-unknown-linux-gnu
