meta:
  version: 1
  args:
    host: robot1
  inputs:
  - path: launch/multihost.launch.xml
    sha256: de6cdfb8a4ef9894ec699e3ecdc4e9a47c7689c84fa20d60ed6b9316b02e0e2c
  - path: system.toml
    sha256: cca0a561c85937d8b1cce9b18cf321e7c7c1e8e299aec8e7cfc5b848cd9e1fe7
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
  diagnostics:
  - 'system config: [deploy.robot2] places unknown node ''/listener'' (absent in this variant?)'
structure:
  scopes:
    multihost.launch.xml:
      file: multihost.launch.xml
      args:
        host: robot1
  nodes:
    /talker:
      scope: multihost.launch.xml
      pkg: talker_pkg
      exec: talker
      node_name: talker
execution:
  deploy:
    /talker:
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: robot1
        kind: self
        target: x86_64-unknown-linux-gnu
