meta:
  version: 1
  inputs:
  - path: launch/service_client.launch.xml
    sha256: 8cce8136abc52bbc15fe2d28cf9d5f77ec42d2a814fdbd3eb26b118659ab936f
  - path: system.toml
    sha256: f5b5f670aa707f96eefeb50e4e126ea91966fdf02c98a3d661d618b6954e0279
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
  diagnostics:
  - 'system config: [deploy.robot1] places unknown node ''/talker'' (absent in this variant?)'
  - 'system config: [deploy.robot2] places unknown node ''/listener'' (absent in this variant?)'
structure:
  scopes:
    service_client.launch.xml:
      file: service_client.launch.xml
  nodes:
    /add_client:
      scope: service_client.launch.xml
      pkg: c_add_client_pkg
      exec: add_client
      node_name: add_client
execution:
  deploy:
    /add_client:
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
