meta:
  version: 1
  inputs:
  - path: launch/service_client.launch.xml
    sha256: daaa4b3d983e1d21fc3e59f85eb733d094754fe1fd640a0d44dfcd742458a017
  - path: system.toml
    sha256: cca0a561c85937d8b1cce9b18cf321e7c7c1e8e299aec8e7cfc5b848cd9e1fe7
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
  diagnostics:
  - 'system config: [deploy.robot1] places unknown node ''/talker'' (absent in this variant?)'
  - 'system config: [deploy.robot2] places unknown node ''/listener'' (absent in this variant?)'
structure:
  scopes:
    service_client.launch.xml:
      file: service_client.launch.xml
  nodes:
    /add_client:
      scope: service_client.launch.xml
      pkg: service_client_pkg
      exec: add_client
      node_name: add_client
execution:
  deploy:
    /add_client:
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
