meta:
  version: 1
  inputs:
  - path: launch/system.launch.xml
    sha256: 67dec34584a216841c924346fbc829ca5305a1b9cfdaea29576192a8189f31ad
  - path: system.toml
    sha256: cca0a561c85937d8b1cce9b18cf321e7c7c1e8e299aec8e7cfc5b848cd9e1fe7
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
structure:
  scopes:
    system.launch.xml:
      file: system.launch.xml
  nodes:
    /listener:
      scope: system.launch.xml
      pkg: listener_pkg
      exec: listener
      node_name: listener
    /talker:
      scope: system.launch.xml
      pkg: talker_pkg
      exec: talker
      node_name: talker
execution:
  deploy:
    /listener:
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
    /talker:
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
