meta:
  version: 1
  inputs:
  - path: /home/aeon/repos/nano-ros/examples/workspaces/ws-qos-cpp/src/demo_bringup/config/system_model.record.json
    sha256: 5b9ec62d230549cfae5085ed4ea89f10fbe3a677c52b6711fefaf417ceff911b
  - path: /home/aeon/repos/nano-ros/examples/workspaces/ws-qos-cpp/src/demo_bringup/launch/system.launch.xml
    sha256: 7476979045b4602fce2c8882feda9bd2cd663ac72913a1056c8fb8c6cb144f1d
  - path: /home/aeon/repos/nano-ros/examples/workspaces/ws-qos-cpp/src/demo_bringup/system.toml
    sha256: e961bf802e6865173591affad22408cd975ab27c295c82e9eb95b20e244631b4
  resolver:
    tool: play_launch
    version: 0.8.2
  record:
    path: /home/aeon/repos/nano-ros/examples/workspaces/ws-qos-cpp/src/demo_bringup/config/system_model.record.json
    sha256: 5b9ec62d230549cfae5085ed4ea89f10fbe3a677c52b6711fefaf417ceff911b
structure:
  scopes:
    /: {}
  nodes:
    /qos_listener:
      scope: /
      pkg: qos_listener_pkg
      exec: qos_listener
    /qos_talker:
      scope: /
      pkg: qos_talker_pkg
      exec: qos_talker
execution:
  deploy:
    /qos_listener:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
    /qos_talker:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
