include = [ "../../../../../nros-patch.toml", "nros-board.toml"]

[patch.crates-io]
nros-board-threadx-qemu-riscv64 = { path = "../../../../packages/boards/nros-board-threadx-qemu-riscv64" }  # nros-managed
nros-platform = { path = "../../../../packages/platform/nros-platform" }  # nros-managed
nros-rmw-cyclonedds-sys = { path = "../../../../packages/rmw/cyclonedds/nros-rmw-cyclonedds-sys" }  # nros-managed
nros-rmw-zenoh = { path = "../../../../packages/rmw/zenoh/nros-rmw-zenoh" }  # nros-managed

