// emit:ok
// nros-cpp message type — C++ header for embedded systems
// Package: fingerprint-corpus
// Message: Bounded
// Auto-generated by rosidl-codegen — do not edit

#ifndef FINGERPRINT_CORPUS_MSG_BOUNDED_HPP
#define FINGERPRINT_CORPUS_MSG_BOUNDED_HPP

#include <cstdint>
#include <cstddef>

#include "nros/fixed_string.hpp"
#include "nros/fixed_sequence.hpp"
#include "nros/heap_sequence.hpp"
#include "nros/heap_string.hpp"

// FFI declarations
extern "C" {
int nros_cpp_publish_fingerprint_corpus_msg_bounded(void* handle, const void* msg);
int nros_cpp_serialize_fingerprint_corpus_msg_bounded(const void* msg, uint8_t* buf, size_t buf_len, size_t* out_len);
int nros_cpp_deserialize_fingerprint_corpus_msg_bounded(const uint8_t* data, size_t len, void* out);
} // extern "C"

namespace fingerprint_corpus { namespace msg {

/// Bounded message structure (repr(C) compatible)
struct Bounded {
    bool flag = {};
    int64_t wide = {};
    uint8_t narrow = {};
    double d = {};
    nros::FixedString<8> label = {};
    int32_t fixed[4] = {};
    nros::FixedSequence<nros::FixedString<8>, 4> labels = {};

    // Type metadata
    static constexpr const char* TYPE_NAME = "fingerprint-corpus::msg::dds_::Bounded_";
    static constexpr const char* TYPE_HASH = "h";

    /// Largest CDR payload this type can produce or consume, encapsulation
    /// header included. Derived by `nros_serdes::size::max_serialized_size`
    /// over this type's own schema -- THE size rule, not a copy of it -- so
    /// it cannot disagree with the Rust `MAX_SERIALIZED_SIZE_XCDR*` const
    /// or the exported bound inventory for the same type (issue 0964).
    ///
    /// `max(XCDR1, XCDR2)`: this stack WRITES XCDR1, but data_representation
    /// is negotiable and a non-default peer may send XCDR2, so one constant
    /// serving both a publish buffer and a receive buffer must hold either.
    static constexpr size_t SERIALIZED_SIZE_MAX = 133;

    /// Publish via FFI (called by Publisher<M>::publish)
    static int ffi_publish(void* handle, const void* msg) {
        return nros_cpp_publish_fingerprint_corpus_msg_bounded(handle, msg);
    }

    /// Serialize to CDR buffer (called by Service/Client/Action)
    static int ffi_serialize(const void* msg, uint8_t* buf, size_t buf_len, size_t* out_len) {
        return nros_cpp_serialize_fingerprint_corpus_msg_bounded(msg, buf, buf_len, out_len);
    }

    /// Deserialize from CDR (called by Subscription<M>::try_recv)
    static int ffi_deserialize(const uint8_t* data, size_t len, void* out) {
        return nros_cpp_deserialize_fingerprint_corpus_msg_bounded(data, len, out);
    }
};

// Constants — namespace-level `<Msg>_<NAME>` aliases (legacy shape; prefer
// the struct-member `<Msg>::<NAME>` above, which matches rosidl C++).

}} // namespace fingerprint_corpus::msg

#endif // FINGERPRINT_CORPUS_MSG_BOUNDED_HPP