meta:
  version: 1
  inputs:
  - path: launch/system.launch.xml
    sha256: f90d90c4e3be5ae2ea3c316dc6ec41a364877285f6acf5dfb3d809ff6962b75b
  - path: system.toml
    sha256: a3728d324ed75b32a7087e36a32534c9490e323bf74f310f307776b209d6c53f
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
structure:
  scopes:
    system.launch.xml:
      file: system.launch.xml
  nodes:
    /island/remap_talker:
      scope: system.launch.xml
      pkg: remap_talker_pkg
      exec: remap_talker
      remaps:
      - from: ~/out
        to: /remapped_out
      node_name: remap_talker
execution:
  deploy:
    /island/remap_talker:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
