[patch.crates-io]
nros = { path = "../../../packages/core/nros" }
nros-core = { path = "../../../packages/core/nros-core" }
nros-serdes = { path = "../../../packages/core/nros-serdes" }
nros-node = { path = "../../../packages/core/nros-node" }
nano-ros-transport = { path = "../../../packages/core/nano-ros-transport" }
nros-params = { path = "../../../packages/core/nros-params" }
nros-macros = { path = "../../../packages/core/nros-macros" }
nano-ros-transport-zenoh = { path = "../../../packages/transport/nano-ros-transport-zenoh" }
nano-ros-transport-zenoh-sys = { path = "../../../packages/transport/nano-ros-transport-zenoh-sys" }
builtin_interfaces = { path = "generated/builtin_interfaces" }
std_msgs = { path = "generated/std_msgs" }
