[build]
target = "riscv32imc-unknown-none-elf"

[target.riscv32imc-unknown-none-elf]
rustflags = [
    "-C", "link-arg=--gc-sections",
  "-C", "link-arg=-Tlinkall.x",
  "-C", "force-frame-pointers",
]

[env]
ESP_LOG = "info"
NROS_EXECUTOR_ARENA_SIZE = "16384"
NROS_SMOLTCP_MAX_UDP_SOCKETS = "2"

[unstable]
build-std = ["core", "alloc"]

