[package]
name = "nros-serdes"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[features]
default = []
std = []
alloc = []

[dependencies]
heapless = "0.8"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(kani)'] }
