[target.xtensa-esp32s3-none-elf]
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "force-frame-pointers",
]

[build]
target = "xtensa-esp32s3-none-elf"

[env]
ESP_LOG = "info"

[unstable]
build-std = ["core", "alloc"]
