[build]
target = "armv7a-nuttx-eabi"

[unstable]
build-std = ["std", "panic_abort"]

[patch.crates-io]
nros-core = { path = "../../../../../packages/core/nros-core" }
nros-serdes = { path = "../../../../../packages/core/nros-serdes" }
builtin_interfaces = { path = "generated/builtin_interfaces" }
std_msgs = { path = "generated/std_msgs" }
