//! Build script for nros-c
//!
//! 1. Reads nros-c-specific env vars and `DEP_NROS_NODE_*` metadata (from
//!    nros-node's `links = "nros_node"`) to generate `nros_c_config.rs`.
//! 2. Generates a C config header with the opaque executor storage size.
//! 3. Runs cbindgen to generate `include/nros/nros_generated.h`.
//!
//! The opaque storage size is an upper bound computed from the executor's
//! arena, entries, and overhead. A compile-time assertion in executor.rs
//! validates that `size_of::<Executor>()` fits within this bound — if the
//! estimate drifts, the build fails instead of silently corrupting memory.

use std::env;
use std::path::{Path, PathBuf};

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());

    generate_config(&out_dir, &manifest_dir);
    generate_header(&manifest_dir);

    // Re-run if source files change (for library rebuild + header regen)
    println!("cargo:rerun-if-changed=src/");
    println!("cargo:rerun-if-changed=cbindgen.toml");
}

/// Generate `nros_c_config.rs` with build-time configurable constants.
fn generate_config(out_dir: &str, manifest_dir: &Path) {
    // --- C API knobs (nros-c only, not shared with nros-node) ---
    let executor_max_handles = env_usize("NROS_EXECUTOR_MAX_HANDLES", 16);
    let max_subscriptions = env_usize("NROS_MAX_SUBSCRIPTIONS", 8);
    let max_timers = env_usize("NROS_MAX_TIMERS", 8);
    let max_services = env_usize("NROS_MAX_SERVICES", 4);
    let let_buffer_size = env_usize("NROS_LET_BUFFER_SIZE", 512);
    let message_buffer_size = env_usize("NROS_MESSAGE_BUFFER_SIZE", 1024);

    // --- Executor layout from nros-node (via Cargo `links` metadata) ---
    // These are NOT user-settable from nros-c. nros-node is the single source
    // of truth for MAX_CBS and ARENA_SIZE.
    let max_cbs = dep_usize("DEP_NROS_NODE_MAX_CBS");
    let arena_size = dep_usize("DEP_NROS_NODE_ARENA_SIZE");

    // --- Opaque storage upper bound ---
    // This MUST be >= size_of::<Executor>(). We use a generous estimate;
    // the compile-time assertion in executor.rs catches any undercount.
    //
    // Layout: SessionStore + arena + entries + trigger + misc fields
    let session_upper = 512; // SessionStore enum (Owned or Borrowed)
    let entries_upper = max_cbs * 80; // Option<CallbackMeta> ~72 bytes, rounded up
    let overhead = 512; // Trigger + semantics + node_name + namespace + halt_flag + padding
    let executor_bytes = session_upper + arena_size + entries_upper + overhead;
    let executor_opaque_u64s = executor_bytes.div_ceil(8);
    let executor_storage_bytes = executor_opaque_u64s * 8;

    let contents = format!(
        "/// Maximum number of handles in an executor \
         (set via NROS_EXECUTOR_MAX_HANDLES, default 16).\n\
         pub const NROS_EXECUTOR_MAX_HANDLES: usize = {executor_max_handles};\n\
         \n\
         /// Maximum number of subscriptions in an executor \
         (set via NROS_MAX_SUBSCRIPTIONS, default 8).\n\
         pub const NROS_MAX_SUBSCRIPTIONS: usize = {max_subscriptions};\n\
         \n\
         /// Maximum number of timers in an executor \
         (set via NROS_MAX_TIMERS, default 8).\n\
         pub const NROS_MAX_TIMERS: usize = {max_timers};\n\
         \n\
         /// Maximum number of services in an executor \
         (set via NROS_MAX_SERVICES, default 4).\n\
         pub const NROS_MAX_SERVICES: usize = {max_services};\n\
         \n\
         /// Buffer size for LET semantics per handle \
         (set via NROS_LET_BUFFER_SIZE, default 512).\n\
         pub const LET_BUFFER_SIZE: usize = {let_buffer_size};\n\
         \n\
         /// Maximum buffer size for subscription/service data \
         (set via NROS_MESSAGE_BUFFER_SIZE, default 1024).\n\
         pub const MESSAGE_BUFFER_SIZE: usize = {message_buffer_size};\n\
         \n\
         /// Inline opaque storage for `Executor` inside `nros_executor_t` (in u64 units).\n\
         /// Upper bound derived from nros-node's MAX_CBS and ARENA_SIZE.\n\
         /// Validated at compile time by `size_of::<Executor>()` assertion.\n\
         pub const EXECUTOR_OPAQUE_U64S: usize = {executor_opaque_u64s};\n"
    );

    std::fs::write(Path::new(out_dir).join("nros_c_config.rs"), contents).unwrap();

    // Generate C config header with executor storage size
    let c_header = format!(
        "/* Auto-generated by nros-c build.rs — do not edit */\n\
         #ifndef NROS_CONFIG_GENERATED_H\n\
         #define NROS_CONFIG_GENERATED_H\n\
         \n\
         /** Inline opaque storage size (bytes) for nros_executor_t. */\n\
         #define NROS_EXECUTOR_STORAGE_SIZE {executor_storage_bytes}\n\
         \n\
         #endif /* NROS_CONFIG_GENERATED_H */\n"
    );
    let config_header_path = manifest_dir.join("include/nros/nros_config_generated.h");
    std::fs::write(config_header_path, c_header).unwrap();
}

/// Generate `include/nros/nros_generated.h` using cbindgen.
///
/// cbindgen reads Rust source files and generates C header declarations
/// for all `#[repr(C)]` structs, enums, type aliases, constants, and
/// `extern "C"` functions. The generated header is the single source of
/// truth for C/Rust type layout compatibility.
fn generate_header(manifest_dir: &Path) {
    let config_path = manifest_dir.join("cbindgen.toml");
    let output_path = manifest_dir.join("include/nros/nros_generated.h");

    let config = match cbindgen::Config::from_file(&config_path) {
        Ok(c) => c,
        Err(e) => {
            println!("cargo:warning=Failed to load cbindgen config: {e}");
            return;
        }
    };

    let result = cbindgen::Builder::new()
        .with_crate(manifest_dir)
        .with_config(config)
        .generate();

    match result {
        Ok(bindings) => {
            bindings.write_to_file(&output_path);
        }
        Err(e) => {
            // cbindgen may fail if dependencies aren't available (e.g.,
            // during no-default-features builds). This is expected —
            // the generated header is only needed for builds with an
            // RMW backend enabled.
            println!("cargo:warning=cbindgen header generation skipped: {e}");
        }
    }
}

/// Read a usize from an environment variable, falling back to a default.
fn env_usize(name: &str, default: usize) -> usize {
    println!("cargo:rerun-if-env-changed={name}");
    env::var(name)
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(default)
}

/// Read a usize from a `DEP_*` environment variable (Cargo `links` metadata).
///
/// Panics if the variable is missing — this means nros-node's `links` export
/// is broken, which is a build system bug that should fail loudly.
fn dep_usize(name: &str) -> usize {
    env::var(name)
        .unwrap_or_else(|_| {
            panic!("{name} not set — is nros-node's `links = \"nros_node\"` configured?")
        })
        .parse()
        .unwrap_or_else(|_| panic!("{name} is not a valid usize"))
}
