meta:
  version: 1
  inputs:
  - path: /home/aeon/repos/nano-ros/examples/workspaces/ws-qos-c/src/demo_bringup/config/listener_model.record.json
    sha256: 14f992b2eee96fa7816f136338c471e05fc3db42fcea63580d09cd8826bcbb0f
  - path: /home/aeon/repos/nano-ros/examples/workspaces/ws-qos-c/src/demo_bringup/launch/listener.launch.xml
    sha256: 93a8e890e03bc4956152c77b8b594023cdd069cd83f76b9ad3c96179a484501f
  - path: /home/aeon/repos/nano-ros/examples/workspaces/ws-qos-c/src/demo_bringup/system.toml
    sha256: 1b0d5ef127d538433a93331cb3c03c65506200d9c44a3cdda927f439c832fc32
  resolver:
    tool: play_launch
    version: 0.8.2
  record:
    path: /home/aeon/repos/nano-ros/examples/workspaces/ws-qos-c/src/demo_bringup/config/listener_model.record.json
    sha256: 14f992b2eee96fa7816f136338c471e05fc3db42fcea63580d09cd8826bcbb0f
structure:
  scopes:
    /: {}
  nodes:
    /qos_listener:
      scope: /
      pkg: qos_listener_pkg
      exec: qos_listener
execution:
  deploy:
    /qos_listener:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
