include = ["../../../../../../nros-patch.toml", "nros-board.toml"]
[build]
target = "thumbv7m-none-eabi"


[patch.crates-io]
nros-board-mps2-an385 = { path = "../../../../boards/nros-board-mps2-an385" }  # nros-managed
nros-rmw-zenoh = { path = "../../../../rmw/zenoh/nros-rmw-zenoh" }  # nros-managed
