meta:
  version: 1
  inputs:
  - path: launch/system.launch.xml
    sha256: fec2a92c1ab536e834089027d087d5ce0f21345bc0b468d2e2d00e7ded4bb108
  - path: system.toml
    sha256: 0c61adda6e7bc58d1123d45857d7b24ed33165b04d236b53ee330bd90150e099
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
structure:
  scopes:
    system.launch.xml:
      file: system.launch.xml
  nodes:
    /control_node:
      scope: system.launch.xml
      pkg: ctrl_pkg
      exec: control_node
      node_name: control_node
    /telem_node:
      scope: system.launch.xml
      pkg: telem_pkg
      exec: telem_node
      node_name: telem_node
execution:
  tiers:
    high:
      class: real_time
      spin_period_us: 1000
      posix:
        priority: 80
        core: 0
      zephyr:
        priority: 5
        deadline_us: 10000
      threadx:
        priority: 5
      nuttx:
        priority: 110
        budget_us: 5000
        period_us: 10000
    low:
      spin_period_us: 10000
      posix:
        priority: 10
      zephyr:
        priority: 10
        core: 0
      threadx:
        priority: 15
        core: 0
        preempt_threshold: 10
        time_slice_us: 5000
      nuttx:
        priority: 100
        core: 0
  bindings:
    /control_node/ctrl: high
    /telem_node/telem: low
