fn main() {
    nros_build_helpers::cpp::run();
    generate_cpp_surface_anchor();
}

/// Phase 241 W11 (Option D) — emit a `#[used]` anchor that force-references every
/// `#[unsafe(no_mangle)] extern "C"` entry point this crate defines.
///
/// Mirrors `nros-c`'s `generate_c_surface_anchor`, one level up. Today `nros-cpp` is the
/// C++ umbrella's staticlib root, so its own `nros_cpp_*` no_mangle symbols survive DCE
/// for free. Under W11 a per-entry `<entry>_runtime` crate bundles `nros-cpp` as an
/// **rlib** dependency and emits the final staticlib; rustc then dead-code-eliminates
/// any `nros_cpp_*` symbol the runtime root doesn't reference — yet the C++ entry / node
/// TUs (linked separately into the exe) call them, so they must be in the archive. The
/// anchor (re-pulled by the runtime root via `FORCE_LINK_ANCHOR`) keeps the whole C++
/// FFI surface. (We never call through it; the extern decls only name the symbols.)
fn generate_cpp_surface_anchor() {
    use std::fmt::Write as _;

    let mut names: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
    let mut stack = vec![std::path::PathBuf::from("src")];
    while let Some(dir) = stack.pop() {
        let Ok(entries) = std::fs::read_dir(&dir) else {
            continue;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                stack.push(path);
                continue;
            }
            if path.extension().and_then(|e| e.to_str()) != Some("rs") {
                continue;
            }
            println!("cargo:rerun-if-changed={}", path.display());
            let Ok(content) = std::fs::read_to_string(&path) else {
                continue;
            };
            // Walk the contiguous attribute / doc block above each `extern "C" fn` and
            // anchor it only when that block carries `#[unsafe(no_mangle)]` AND no
            // `#[cfg(...)]`, AND the fn is declared at column 0 (an indented fn may be
            // gated by an enclosing `#[cfg] mod { … }` even when its own block isn't).
            // Same heuristic as nros-c — see that crate's build.rs for the rationale.
            let mut has_no_mangle = false;
            let mut has_cfg = false;
            for line in content.lines() {
                let t = line.trim_start();
                let is_attr_or_doc =
                    t.starts_with("#[") || t.starts_with("#!") || t.starts_with("//");
                if t.contains("no_mangle") {
                    has_no_mangle = true;
                }
                if t.starts_with("#[cfg(") || t.starts_with("#[cfg_attr(") {
                    has_cfg = true;
                }
                if let Some(idx) = t.find("extern \"C\" fn ") {
                    let indented = line.starts_with(' ') || line.starts_with('\t');
                    if has_no_mangle && !has_cfg && !indented {
                        let rest = &t[idx + "extern \"C\" fn ".len()..];
                        let name: String = rest
                            .chars()
                            .take_while(|c| c.is_alphanumeric() || *c == '_')
                            .collect();
                        if name.starts_with("nros_") {
                            names.insert(name);
                        }
                    }
                    has_no_mangle = false;
                    has_cfg = false;
                } else if !is_attr_or_doc && !t.is_empty() {
                    has_no_mangle = false;
                    has_cfg = false;
                }
            }
        }
    }

    let mut out = String::new();
    out.push_str("// Generated by build.rs — do not edit. See generate_cpp_surface_anchor().\n");
    out.push_str("#[allow(unused, improper_ctypes)]\n");
    // `pub` so a downstream staticlib root (the per-entry `<entry>_runtime` crate) can
    // REFERENCE the anchor — a bare `#[used]` here is DCE'd when nros-cpp is a dep rlib.
    out.push_str("pub mod cpp_surface_anchor {\n    unsafe extern \"C\" {\n");
    for n in &names {
        let _ = writeln!(out, "        pub fn {n}();");
    }
    out.push_str("    }\n");
    let _ = writeln!(
        out,
        "    #[used]\n    pub static CPP_SURFACE_ANCHOR: [unsafe extern \"C\" fn(); {}] = [",
        names.len()
    );
    for n in &names {
        let _ = writeln!(out, "        {n},");
    }
    out.push_str("    ];\n}\n");

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest = std::path::Path::new(&out_dir).join("cpp_surface_anchor.rs");
    std::fs::write(&dest, out).expect("write cpp_surface_anchor.rs");
}
