//! Build script for nros-cpp
//!
//! 1. Reads `DEP_NROS_NODE_*` metadata (from nros-node's `links = "nros_node"`)
//!    to compute opaque storage for CppContext.
//! 2. Runs cbindgen to generate `include/nros_cpp_ffi.h`.
//!
//! The opaque storage size is an upper bound. A compile-time assertion in
//! lib.rs validates that `size_of::<CppContext>()` fits within this bound.

use std::env;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = env::var("OUT_DIR").unwrap();

    generate_config(&out_dir, &manifest_dir);
    generate_header(&manifest_dir);

    println!("cargo:rerun-if-changed=src/");
    println!("cargo:rerun-if-changed=cbindgen.toml");
}

/// Generate `nros_cpp_ffi_config.rs` with build-time constants for executor storage.
fn generate_config(out_dir: &str, manifest_dir: &std::path::Path) {
    // Read executor layout from nros-node via Cargo `links` metadata.
    // nros-node is the single source of truth.
    let max_cbs = dep_usize("DEP_NROS_NODE_MAX_CBS");
    let arena_size = dep_usize("DEP_NROS_NODE_ARENA_SIZE");

    // Upper bound for CppContext size (in bytes):
    //   CppContext = Executor + domain_id (u32) + padding
    //   Executor ≈ SessionStore + arena + entries + trigger + misc
    let session_upper = 512;
    let entries_upper = max_cbs * 80;
    let overhead = 512; // trigger + semantics + strings + halt_flag + domain_id + padding
    let total_bytes = session_upper + arena_size + entries_upper + overhead;
    let opaque_u64s = total_bytes.div_ceil(8);
    let storage_bytes = opaque_u64s * 8;

    // Action server: CppActionServer = handle + pending goals + action_name
    //   pending = [PendingGoal; 4], PendingGoal = GoalId(16) + [u8; ACTION_BUF] + usize + bool
    let action_buf_size = 1024usize; // ACTION_BUF_SIZE in action.rs
    let max_pending_goals = 4usize; // MAX_PENDING_GOALS in action.rs
    let pending_goal_size = 16 + action_buf_size + 8 + 8; // GoalId + data + data_len + occupied (aligned)
    let action_server_bytes = 16 + (pending_goal_size * max_pending_goals) + 256 + 8 + 16; // handle + pending + name + name_len + padding
    let action_server_opaque_u64s = action_server_bytes.div_ceil(8);
    let action_server_storage = action_server_opaque_u64s * 8;

    // Action client: CppActionClient = ActionClientCore<1024,1024,1024> + action_name
    //   ActionClientCore has 3 service clients + 1 subscriber + 3 buffers + counters
    let service_client_upper = 384usize; // matches nros-c constant
    let subscriber_upper = 128usize;
    let action_client_bytes =
        3 * service_client_upper + subscriber_upper + 3 * action_buf_size + 256 + 64;
    let action_client_opaque_u64s = action_client_bytes.div_ceil(8);
    let action_client_storage = action_client_opaque_u64s * 8;

    let contents = format!(
        "/// Inline opaque storage for `CppContext` (in u64 units).\n\
         /// Upper bound derived from nros-node's MAX_CBS and ARENA_SIZE.\n\
         /// Validated at compile time by `size_of::<CppContext>()` assertion.\n\
         pub const CPP_EXECUTOR_OPAQUE_U64S: usize = {opaque_u64s};\n\
         \n\
         /// Inline opaque storage for `CppActionServer` (in u64 units).\n\
         pub const CPP_ACTION_SERVER_OPAQUE_U64S: usize = {action_server_opaque_u64s};\n\
         \n\
         /// Inline opaque storage for `CppActionClient` (in u64 units).\n\
         pub const CPP_ACTION_CLIENT_OPAQUE_U64S: usize = {action_client_opaque_u64s};\n"
    );

    std::fs::write(
        std::path::Path::new(out_dir).join("nros_cpp_ffi_config.rs"),
        contents,
    )
    .unwrap();

    // Generate C++ config header with executor storage size (local include/nros/)
    let cpp_header = format!(
        "/* Auto-generated by nros-cpp build.rs — do not edit */\n\
         #ifndef NROS_CPP_CONFIG_GENERATED_H\n\
         #define NROS_CPP_CONFIG_GENERATED_H\n\
         \n\
         /** Inline opaque storage size (bytes) for nros::Executor. */\n\
         #define NROS_CPP_EXECUTOR_STORAGE_SIZE {storage_bytes}\n\
         \n\
         /** Inline opaque storage size (bytes) for nros::ActionServer<A>. */\n\
         #define NROS_CPP_ACTION_SERVER_STORAGE_SIZE {action_server_storage}\n\
         \n\
         /** Inline opaque storage size (bytes) for nros::ActionClient<A>. */\n\
         #define NROS_CPP_ACTION_CLIENT_STORAGE_SIZE {action_client_storage}\n\
         \n\
         #endif /* NROS_CPP_CONFIG_GENERATED_H */\n"
    );
    let include_dir = manifest_dir.join("include/nros");
    std::fs::create_dir_all(&include_dir).ok();
    std::fs::write(include_dir.join("nros_cpp_config_generated.h"), cpp_header).unwrap();
}

/// Read a usize from a `DEP_*` environment variable (Cargo `links` metadata).
///
/// Panics if the variable is missing — this means nros-node's `links` export
/// is broken, which is a build system bug that should fail loudly.
fn dep_usize(name: &str) -> usize {
    env::var(name)
        .unwrap_or_else(|_| {
            panic!("{name} not set — is nros-node's `links = \"nros_node\"` configured?")
        })
        .parse()
        .unwrap_or_else(|_| panic!("{name} is not a valid usize"))
}

/// Generate `include/nros_cpp_ffi.h` using cbindgen.
fn generate_header(manifest_dir: &std::path::Path) {
    let config_path = manifest_dir.join("cbindgen.toml");
    let output_path = manifest_dir.join("include/nros_cpp_ffi.h");

    let config = match cbindgen::Config::from_file(&config_path) {
        Ok(c) => c,
        Err(e) => {
            println!("cargo:warning=Failed to load cbindgen config: {e}");
            return;
        }
    };

    let result = cbindgen::Builder::new()
        .with_crate(manifest_dir)
        .with_config(config)
        .generate();

    match result {
        Ok(bindings) => {
            // Ensure include directory exists
            if let Some(parent) = output_path.parent() {
                std::fs::create_dir_all(parent).ok();
            }
            bindings.write_to_file(&output_path);
        }
        Err(e) => {
            println!("cargo:warning=cbindgen header generation skipped: {e}");
        }
    }
}
