#!/usr/bin/env bash
#
# Run the nano-ros self-hosted runner INSIDE AN UNPRIVILEGED CONTAINER.
# Design: docs/development/multi-agent-ci-workflow.md ("Security").
#
# WHY A CONTAINER IS ENOUGH *HERE*, WHEN THE GENERAL ADVICE SAYS IT IS NOT
#
# The standard warning is real: a container does not isolate an untrusted job,
# because the escapes people add to make CI work ARE the vulnerability. Mounting
# the host Docker socket, or `--privileged` / docker-in-docker, both hand a job
# root on the host. Guidance that says "containers are insufficient" is talking
# about jobs that build images or start containers.
#
# nano-ros' self-hosted jobs do neither. MEASURED across all four
# (`build-wide`, `run-matrix`, `queue` L3, `nightly` matrix-nightly): zero
# references to docker, zero to KVM, zero device mounts. The work is cargo,
# cmake and QEMU in PURE EMULATION — `-icount shift=auto`, which is
# deterministic and incompatible with KVM, so not even `/dev/kvm` is wanted.
#
# So the escapes are not needed, and this script REFUSES to add them. That is
# the whole security argument, and it stops being true the moment a job needs to
# build an image — at which point the honest answer is a microVM, not a flag.
#
# WHAT IS AND IS NOT PROTECTED
#
# Fork pull requests already cannot reach these runners: every self-hosted job
# triggers only on `push`, `merge_group`, `schedule` or `workflow_dispatch`, and
# `check-workflow-runner-isolation` keeps it that way. The container bounds what
# someone WITH WRITE ACCESS can reach — it does not eliminate it. If the host
# carries unrelated work, that boundary is the point.
#
# Usage:
#   scripts/ci/runner-container.sh <labels> [--build] [--run] [--check]
#
#   <labels>   comma- or space-separated, e.g. nros-qemu,nros-sdk-zephyr,nros-big
#   --build    build the image only
#   --run      run the container only (image must exist)
#   --check    print what would happen, touch nothing
#
# With neither --build nor --run, does both.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
IMAGE="${NROS_RUNNER_IMAGE:-nano-ros-runner:local}"
NAME="${NROS_RUNNER_NAME:-nano-ros-runner}"
ENGINE="${NROS_CONTAINER_ENGINE:-docker}"
DO_BUILD=0 DO_RUN=0 CHECK=0
LABELS=""

while [ $# -gt 0 ]; do
    case "$1" in
        --build) DO_BUILD=1 ;;
        --run)   DO_RUN=1 ;;
        --check|--dry-run) CHECK=1 ;;
        # Refused ON PURPOSE. These are the two flags that turn a contained
        # runner back into an uncontained one, and a script that accepts them
        # "just this once" is how the property is lost without anyone deciding
        # to lose it.
        --privileged|-v*/var/run/docker.sock*|--docker-socket)
            echo "runner-container: refusing '$1'." >&2
            echo "  Mounting the docker socket or running privileged gives any" >&2
            echo "  job root on the HOST, which removes the only reason to use a" >&2
            echo "  container here. nano-ros' self-hosted jobs need neither —" >&2
            echo "  measured: no docker, no KVM, no device access in any of the" >&2
            echo "  four. If a job now genuinely needs to build an image, the" >&2
            echo "  answer is a microVM, not this flag." >&2
            exit 2 ;;
        -h|--help) sed -n '2,45p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        -*) echo "runner-container: unknown option '$1'" >&2; exit 2 ;;
        *)  LABELS="$1" ;;
    esac
    shift
done

[ -n "$LABELS" ] || { echo "runner-container: need <labels>, e.g. nros-qemu,nros-sdk-zephyr,nros-big" >&2; exit 2; }
LABELS="${LABELS// /,}"
if [ "$DO_BUILD" -eq 0 ] && [ "$DO_RUN" -eq 0 ]; then DO_BUILD=1; DO_RUN=1; fi

command -v "$ENGINE" >/dev/null 2>&1 || {
    echo "runner-container: '$ENGINE' not found (set NROS_CONTAINER_ENGINE)" >&2; exit 2; }

CONTEXT="$REPO_ROOT/ci/docker/runner"
mkdir -p "$CONTEXT"

# The image provisions THROUGH `runner-provision.sh`, not through a second list
# of apt packages. A runner and a contributor must provision the same way or the
# runner's toolchain becomes a thing nobody can account for — the reason that
# script exists at all.
cat > "$CONTEXT/Dockerfile" <<'DOCKEREOF'
# Generated by scripts/ci/runner-container.sh — edit that, not this.
FROM ubuntu:22.04

# The runner refuses to run as root, and running as root would also defeat the
# isolation this image exists for.
ARG RUNNER_UID=1001
ARG RUNNER_VERSION=2.329.0

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
        ca-certificates curl git sudo jq python3 python3-venv build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m -u ${RUNNER_UID} -s /bin/bash runner
WORKDIR /home/runner

# v2.329.0 or later is REQUIRED to configure or re-register since GitHub's
# 2026-06-12 change, and job execution needs staying inside a moving 30-day
# window. Pinned so the image is reproducible; bump it deliberately.
RUN curl -fsSL -o actions-runner.tar.gz \
      "https://github.com/actions/runner/releases/download/v${RUNNER_VERSION}/actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz" \
    && tar xzf actions-runner.tar.gz && rm actions-runner.tar.gz \
    && ./bin/installdependencies.sh \
    && chown -R runner:runner /home/runner

COPY --chown=runner:runner entrypoint.sh /home/runner/entrypoint.sh
RUN chmod +x /home/runner/entrypoint.sh
USER runner
ENTRYPOINT ["/home/runner/entrypoint.sh"]
DOCKEREOF

cat > "$CONTEXT/entrypoint.sh" <<'ENTRYEOF'
#!/usr/bin/env bash
# Generated by scripts/ci/runner-container.sh.
set -euo pipefail
: "${NROS_RUNNER_LABELS:?labels required}"
: "${GH_REPO:?GH_REPO required, e.g. NEWSLabNTU/nano-ros}"
: "${RUNNER_TOKEN:?RUNNER_TOKEN required — a SHORT-LIVED registration token}"

# --ephemeral: one job, then the registration is spent. A job cannot leave state
# for the next one, which is also what stops the orphan/disk rot a long-lived
# runner accumulates (the design doc records 71 orphaned processes, oldest 10
# days, on a persistent runner).
./config.sh \
    --url "https://github.com/${GH_REPO}" \
    --token "${RUNNER_TOKEN}" \
    --labels "${NROS_RUNNER_LABELS}" \
    --name "${RUNNER_NAME:-$(hostname)}" \
    --work /home/runner/_work \
    --ephemeral --unattended --replace
exec ./run.sh
ENTRYEOF
chmod +x "$CONTEXT/entrypoint.sh"

run_or_echo() {
    if [ "$CHECK" -eq 1 ]; then printf '  would run: %s\n' "$*"; else "$@"; fi
}

if [ "$DO_BUILD" -eq 1 ]; then
    echo "runner-container: building $IMAGE (labels: $LABELS)"
    run_or_echo "$ENGINE" build -t "$IMAGE" "$CONTEXT"
    echo "  NOTE: the image carries the RUNNER, not the toolchain. Provision the"
    echo "  labels inside a running container, or bake them by extending the"
    echo "  Dockerfile with 'runner-provision.sh $LABELS' — same script a"
    echo "  contributor uses, so the two cannot drift."
fi

if [ "$DO_RUN" -eq 1 ]; then
    [ -n "${RUNNER_TOKEN:-}" ] || {
        echo "runner-container: RUNNER_TOKEN is unset." >&2
        echo "  Get a SHORT-LIVED registration token (valid ~1h):" >&2
        echo "    gh api -X POST repos/${GH_REPO:-NEWSLabNTU/nano-ros}/actions/runners/registration-token --jq .token" >&2
        echo "  Never bake a token into the image or a file." >&2
        exit 2; }
    echo "runner-container: starting $NAME"
    # Every flag here is a security decision, and each was TESTED, not assumed:
    #   --cap-drop ALL       no capabilities; nothing here needs one
    #   --security-opt       no privilege escalation via setuid
    #   --user runner        never root, in or out of the container
    #   --pids-limit         a fork bomb in a job cannot take the host down
    #   --tmpfs /tmp         exec-capable scratch that dies with the container
    #   named volumes        caches persist; nothing else does
    # and NOTHING mounts the host filesystem or the docker socket.
    #
    # NOT `--read-only`, deliberately, having measured what it costs here: the
    # runner resolves its `_diag` log directory from its binary's REAL path, so
    # an immutable install under /opt is still written to through the symlink
    # and the process dies (SIGSEGV, rc=139 — an unhandled IOException in
    # HostTraceListener, not a clean error). Making it work means copying the
    # whole ~200 MB install into a tmpfs on every start. It would buy little:
    # `--ephemeral` already destroys the writable layer after ONE job, which is
    # the property `--read-only` was there to approximate.
    run_or_echo "$ENGINE" run -d --name "$NAME" \
        --cap-drop ALL \
        --security-opt no-new-privileges \
        --user runner \
        --pids-limit 4096 \
        --tmpfs /tmp:rw,exec,nosuid,size=8g \
        -v "nros-runner-work:/home/runner/_work" \
        -v "nros-runner-cargo:/home/runner/.cargo" \
        -v "nros-runner-sccache:/home/runner/.cache/sccache" \
        -e NROS_RUNNER_LABELS="$LABELS" \
        -e GH_REPO="${GH_REPO:-NEWSLabNTU/nano-ros}" \
        -e RUNNER_TOKEN="$RUNNER_TOKEN" \
        -e RUNNER_NAME="${RUNNER_NAME:-$NAME}" \
        "$IMAGE"
    echo "  logs: $ENGINE logs -f $NAME"
    echo "  NEXT: verify the labels are TRUE from inside, then enable the lanes:"
    echo "    $ENGINE exec $NAME just runner-doctor $LABELS"
    echo "    scripts/ci/enable-merge-queue.sh --apply --self-hosted-ready"
fi
