//! FFI declarations for zenoh-pico-shim
//!
//! This module defines the C API that the shim implements and the
//! platform FFI functions that Rust provides.
//!
//! # Header Generation
//!
//! The header `c/include/zenoh_shim.h` is automatically generated by cbindgen
//! during the build process (see `build.rs`).

use core::ffi::c_void;

// c_char is used in cbindgen stubs
#[cfg(cbindgen)]
use core::ffi::c_char;

// ============================================================================
// Configuration Constants
// ============================================================================

/// Maximum number of concurrent publishers
pub const ZENOH_SHIM_MAX_PUBLISHERS: usize = 8;

/// Maximum number of concurrent subscribers
pub const ZENOH_SHIM_MAX_SUBSCRIBERS: usize = 8;

/// Maximum number of concurrent liveliness tokens
pub const ZENOH_SHIM_MAX_LIVELINESS: usize = 16;

/// Maximum number of concurrent queryables
pub const ZENOH_SHIM_MAX_QUERYABLES: usize = 8;

/// Size of Zenoh ID in bytes
pub const ZENOH_SHIM_ZID_SIZE: usize = 16;

/// Size of RMW GID in bytes (for ROS 2 humble compatibility)
pub const ZENOH_SHIM_RMW_GID_SIZE: usize = 16;

// ============================================================================
// Error Codes
// ============================================================================

/// Success
pub const ZENOH_SHIM_OK: i32 = 0;
/// Generic error
pub const ZENOH_SHIM_ERR_GENERIC: i32 = -1;
/// Configuration error
pub const ZENOH_SHIM_ERR_CONFIG: i32 = -2;
/// Session error
pub const ZENOH_SHIM_ERR_SESSION: i32 = -3;
/// Task creation error
pub const ZENOH_SHIM_ERR_TASK: i32 = -4;
/// Invalid key expression
pub const ZENOH_SHIM_ERR_KEYEXPR: i32 = -5;
/// Resource limit reached
pub const ZENOH_SHIM_ERR_FULL: i32 = -6;
/// Invalid handle
pub const ZENOH_SHIM_ERR_INVALID: i32 = -7;
/// Publish error
pub const ZENOH_SHIM_ERR_PUBLISH: i32 = -8;
/// Query timeout
pub const ZENOH_SHIM_ERR_TIMEOUT: i32 = -9;

// ============================================================================
// Callback Types
// ============================================================================

/// Callback function type for receiving samples (legacy, payload only).
///
/// # Parameters
/// * `data` - Pointer to received data buffer
/// * `len` - Length of data in bytes
/// * `ctx` - User-provided context pointer
pub type ShimCallback = extern "C" fn(data: *const u8, len: usize, ctx: *mut c_void);

/// Callback function type for receiving samples with attachment (RMW compatible).
///
/// # Parameters
/// * `data` - Pointer to received data buffer
/// * `len` - Length of data in bytes
/// * `attachment` - Pointer to attachment buffer (may be NULL)
/// * `attachment_len` - Length of attachment in bytes
/// * `ctx` - User-provided context pointer
pub type ShimCallbackWithAttachment = extern "C" fn(
    data: *const u8,
    len: usize,
    attachment: *const u8,
    attachment_len: usize,
    ctx: *mut c_void,
);

/// Callback function type for receiving queries (service requests).
///
/// # Parameters
/// * `keyexpr` - Key expression string (not null-terminated)
/// * `keyexpr_len` - Length of key expression
/// * `payload` - Pointer to request payload (may be NULL)
/// * `payload_len` - Length of payload in bytes
/// * `ctx` - User-provided context pointer
pub type ShimQueryCallback = extern "C" fn(
    keyexpr: *const core::ffi::c_char,
    keyexpr_len: usize,
    payload: *const u8,
    payload_len: usize,
    ctx: *mut c_void,
);

// ============================================================================
// cbindgen Stub Functions for Shim API
//
// These stubs exist only for cbindgen to generate the C header.
// They are never actually called - the C implementation is linked instead.
// ============================================================================

#[cfg(cbindgen)]
mod cbindgen_stubs {
    use super::*;

    /// A key-value property for transport configuration.
    #[repr(C)]
    pub struct zenoh_shim_property_t {
        /// Property key (null-terminated C string)
        pub key: *const c_char,
        /// Property value (null-terminated C string)
        pub value: *const c_char,
    }

    /// Initialize zenoh configuration with client mode and connect locator.
    ///
    /// # Parameters
    /// * `locator` - Connection string (e.g., "tcp/192.168.1.1:7447"), null-terminated.
    ///   Can be NULL to use default.
    ///
    /// # Returns
    /// 0 on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zenoh_shim_init(_locator: *const c_char) -> i32 {
        0
    }

    /// Initialize zenoh configuration with mode, locator, and properties.
    ///
    /// # Parameters
    /// * `locator` - Connection string (e.g., "tcp/192.168.1.1:7447"), null-terminated.
    ///   Can be NULL for peer mode.
    /// * `mode` - Session mode string ("client" or "peer"), null-terminated.
    /// * `properties` - Array of key-value properties, or NULL.
    /// * `num_properties` - Number of properties in the array.
    ///
    /// # Returns
    /// 0 on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zenoh_shim_init_with_config(
        _locator: *const c_char,
        _mode: *const c_char,
        _properties: *const zenoh_shim_property_t,
        _num_properties: usize,
    ) -> i32 {
        0
    }

    /// Open zenoh session and start background tasks (if threaded backend).
    ///
    /// # Returns
    /// 0 on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zenoh_shim_open() -> i32 {
        0
    }

    /// Check if session is currently open.
    ///
    /// # Returns
    /// Non-zero if open, 0 if closed.
    #[unsafe(no_mangle)]
    pub extern "C" fn zenoh_shim_is_open() -> i32 {
        0
    }

    /// Close the session and clean up all resources.
    #[unsafe(no_mangle)]
    pub extern "C" fn zenoh_shim_close() {}

    /// Declare a publisher for the given key expression.
    ///
    /// # Parameters
    /// * `keyexpr` - Key expression string (e.g., "demo/topic"), null-terminated.
    ///
    /// # Returns
    /// Publisher handle (>= 0) on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zenoh_shim_declare_publisher(_keyexpr: *const c_char) -> i32 {
        0
    }

    /// Publish data using publisher handle.
    ///
    /// # Parameters
    /// * `handle` - Publisher handle from zenoh_shim_declare_publisher()
    /// * `data` - Pointer to data buffer
    /// * `len` - Length of data in bytes
    ///
    /// # Returns
    /// 0 on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zenoh_shim_publish(_handle: i32, _data: *const u8, _len: usize) -> i32 {
        0
    }

    /// Undeclare a publisher.
    ///
    /// # Parameters
    /// * `handle` - Publisher handle
    ///
    /// # Returns
    /// 0 on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zenoh_shim_undeclare_publisher(_handle: i32) -> i32 {
        0
    }

    /// Declare a subscriber for the given key expression.
    ///
    /// # Parameters
    /// * `keyexpr` - Key expression string (e.g., "demo/topic"), null-terminated.
    /// * `callback` - Callback function to invoke when samples arrive
    /// * `ctx` - User context pointer passed to callback
    ///
    /// # Returns
    /// Subscriber handle (>= 0) on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zenoh_shim_declare_subscriber(
        _keyexpr: *const c_char,
        _callback: ShimCallback,
        _ctx: *mut c_void,
    ) -> i32 {
        0
    }

    /// Declare a subscriber with attachment support for RMW compatibility.
    ///
    /// # Parameters
    /// * `keyexpr` - Key expression string (e.g., "demo/topic"), null-terminated.
    /// * `callback` - Callback function to invoke when samples arrive (includes attachment)
    /// * `ctx` - User context pointer passed to callback
    ///
    /// # Returns
    /// Subscriber handle (>= 0) on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zenoh_shim_declare_subscriber_with_attachment(
        _keyexpr: *const c_char,
        _callback: ShimCallbackWithAttachment,
        _ctx: *mut c_void,
    ) -> i32 {
        0
    }

    /// Undeclare a subscriber.
    ///
    /// # Parameters
    /// * `handle` - Subscriber handle
    ///
    /// # Returns
    /// 0 on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zenoh_shim_undeclare_subscriber(_handle: i32) -> i32 {
        0
    }

    /// Poll for incoming data and process callbacks.
    ///
    /// For threaded backends (Zephyr, POSIX), this is a no-op as background
    /// tasks handle polling automatically.
    ///
    /// For polling backends (smoltcp), this must be called regularly to
    /// process network data and dispatch callbacks.
    ///
    /// # Parameters
    /// * `timeout_ms` - Maximum time to wait for data (0 = non-blocking)
    ///
    /// # Returns
    /// Number of events processed, or negative on error.
    #[unsafe(no_mangle)]
    pub extern "C" fn zenoh_shim_poll(_timeout_ms: u32) -> i32 {
        0
    }

    /// Combined poll and keepalive operation.
    ///
    /// This is equivalent to calling zenoh_shim_poll() and performing any
    /// necessary keepalive operations. For threaded backends, this is just
    /// a brief poll. For polling backends, this handles both network I/O
    /// and zenoh protocol maintenance.
    ///
    /// # Parameters
    /// * `timeout_ms` - Maximum time to wait (0 = non-blocking)
    ///
    /// # Returns
    /// Number of events processed, or negative on error.
    #[unsafe(no_mangle)]
    pub extern "C" fn zenoh_shim_spin_once(_timeout_ms: u32) -> i32 {
        0
    }

    /// Check if the current backend uses polling.
    ///
    /// # Returns
    /// true if polling required (smoltcp), false if threaded (Zephyr, POSIX).
    #[unsafe(no_mangle)]
    pub extern "C" fn zenoh_shim_uses_polling() -> bool {
        false
    }

    // ========================================================================
    // ZenohId API
    // ========================================================================

    /// Get the session's Zenoh ID.
    ///
    /// # Parameters
    /// * `zid_out` - Pointer to 16-byte buffer to receive the ZID
    ///
    /// # Returns
    /// 0 on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zenoh_shim_get_zid(_zid_out: *mut u8) -> i32 {
        0
    }

    // ========================================================================
    // Liveliness API
    // ========================================================================

    /// Declare a liveliness token for ROS 2 discovery.
    ///
    /// # Parameters
    /// * `keyexpr` - Key expression string, null-terminated.
    ///
    /// # Returns
    /// Liveliness handle (>= 0) on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zenoh_shim_declare_liveliness(_keyexpr: *const c_char) -> i32 {
        0
    }

    /// Undeclare a liveliness token.
    ///
    /// # Parameters
    /// * `handle` - Liveliness handle
    ///
    /// # Returns
    /// 0 on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zenoh_shim_undeclare_liveliness(_handle: i32) -> i32 {
        0
    }

    // ========================================================================
    // Publish with Attachment API
    // ========================================================================

    /// Publish data with an attachment (for RMW compatibility).
    ///
    /// # Parameters
    /// * `handle` - Publisher handle
    /// * `data` - Pointer to data buffer
    /// * `len` - Length of data in bytes
    /// * `attachment` - Pointer to attachment buffer (may be NULL)
    /// * `attachment_len` - Length of attachment in bytes
    ///
    /// # Returns
    /// 0 on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zenoh_shim_publish_with_attachment(
        _handle: i32,
        _data: *const u8,
        _len: usize,
        _attachment: *const u8,
        _attachment_len: usize,
    ) -> i32 {
        0
    }

    // ========================================================================
    // Queryable API (for ROS 2 Services)
    // ========================================================================

    /// Declare a queryable for receiving service requests.
    ///
    /// # Parameters
    /// * `keyexpr` - Key expression string, null-terminated.
    /// * `callback` - Callback function to invoke when queries arrive
    /// * `ctx` - User context pointer passed to callback
    ///
    /// # Returns
    /// Queryable handle (>= 0) on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zenoh_shim_declare_queryable(
        _keyexpr: *const c_char,
        _callback: ShimQueryCallback,
        _ctx: *mut c_void,
    ) -> i32 {
        0
    }

    /// Undeclare a queryable.
    ///
    /// # Parameters
    /// * `handle` - Queryable handle
    ///
    /// # Returns
    /// 0 on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zenoh_shim_undeclare_queryable(_handle: i32) -> i32 {
        0
    }

    /// Reply to a query (must be called within query callback).
    ///
    /// # Parameters
    /// * `keyexpr` - Reply key expression string, null-terminated.
    /// * `data` - Pointer to reply data buffer
    /// * `len` - Length of data in bytes
    /// * `attachment` - Pointer to attachment buffer (may be NULL)
    /// * `attachment_len` - Length of attachment in bytes
    ///
    /// # Returns
    /// 0 on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zenoh_shim_query_reply(
        _queryable_handle: i32,
        _keyexpr: *const c_char,
        _data: *const u8,
        _len: usize,
        _attachment: *const u8,
        _attachment_len: usize,
    ) -> i32 {
        0
    }

    /// Send a query and wait for reply (blocking, for service client).
    ///
    /// # Parameters
    /// * `keyexpr` - Key expression string, null-terminated.
    /// * `payload` - Request payload (may be NULL)
    /// * `payload_len` - Length of payload in bytes
    /// * `reply_buf` - Buffer to receive reply data
    /// * `reply_buf_size` - Size of reply buffer
    /// * `timeout_ms` - Timeout in milliseconds
    ///
    /// # Returns
    /// Number of bytes in reply on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zenoh_shim_get(
        _keyexpr: *const c_char,
        _payload: *const u8,
        _payload_len: usize,
        _reply_buf: *mut u8,
        _reply_buf_size: usize,
        _timeout_ms: u32,
    ) -> i32 {
        0
    }
}
