meta:
  version: 1
  inputs:
  - path: /home/aeon/repos/nano-ros/examples/templates/multi-node-workspace-cpp/src/demo_bringup/launch/system.launch.xml
    sha256: e6b64017dae99ad4782f70a1ba5375ff300c2b065d0164e663a1449d5b5a1dc3
  - path: /home/aeon/repos/nano-ros/examples/templates/multi-node-workspace-cpp/src/demo_bringup/system.toml
    sha256: f34eecb58d1f0427540b99929def7a86c82193bb1e843311c042e99d91ba74d5
  resolver:
    tool: play_launch
    version: 0.8.2
structure:
  scopes:
    /: {}
  nodes:
    /listener:
      scope: /
      pkg: listener_pkg
      exec: listener
      node_name: listener
    /talker:
      scope: /
      pkg: talker_pkg
      exec: talker
      params:
        qos_overrides./chatter.publisher.reliability: best_effort
      node_name: talker
execution:
  deploy:
    /listener:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
    /talker:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
