meta:
  version: 1
  inputs:
  - path: launch/system.launch.xml
    sha256: e6b64017dae99ad4782f70a1ba5375ff300c2b065d0164e663a1449d5b5a1dc3
  - path: system.toml
    sha256: f34eecb58d1f0427540b99929def7a86c82193bb1e843311c042e99d91ba74d5
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
structure:
  scopes:
    system.launch.xml:
      file: system.launch.xml
  nodes:
    /talker:
      scope: system.launch.xml
      pkg: talker_pkg
      exec: talker
      params:
        qos_overrides./chatter.publisher.reliability: best_effort
      param_sources:
      - kind: inline
        name: qos_overrides./chatter.publisher.reliability
        value: best_effort
      node_name: talker
    /listener:
      scope: system.launch.xml
      pkg: listener_pkg
      exec: listener
      node_name: listener
execution:
  deploy:
    /listener:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
    /talker:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
