meta:
  version: 1
  inputs:
  - path: launch/system.launch.xml
    sha256: 048d971aae2ee56baa8b3004ae8e2d24e1aad233b7d2d98fc29d697d22afbb38
  - path: system.toml
    sha256: a15e034aa5e060144b904ab13617178b79140ddfb1c1ef4a5f4b66c2b9c5f3a8
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
structure:
  scopes:
    system.launch.xml:
      file: system.launch.xml
  nodes:
    /aux_node:
      scope: system.launch.xml
      pkg: aux_pkg
      exec: aux
      node_name: aux_node
    /ctrl_node:
      scope: system.launch.xml
      pkg: ctrl_pkg
      exec: ctrl
      node_name: ctrl_node
    /telem_node:
      scope: system.launch.xml
      pkg: telem_pkg
      exec: telem
      node_name: telem_node
execution:
  tiers:
    high:
      spin_period_us: 10000
      posix:
        priority: 80
      freertos:
        priority: 5
    low:
      spin_period_us: 100000
      posix:
        priority: 10
      freertos:
        priority: 2
    mid:
      spin_period_us: 50000
      posix:
        priority: 40
      freertos:
        priority: 3
  bindings:
    /aux_node/aux: mid
    /ctrl_node/ctrl: high
    /telem_node/telem: low
