//! phase-457 W3 - nano-ros ranks the shared contract exactly as
//! ros-launch-manifest's committed snapshot says it does.
//!
//! rlm design issue #52 split one derivation between two consumers. The
//! agreement is only worth what a gate proves, so rlm ships the fixture and
//! the byte-for-byte `RankedPlan` snapshot both consumers compare against:
//! rlm's own `derive/tests/parity.rs`, play_launch's
//! `every_contract_fixture_ranks_to_its_committed_plan`, and this file.
//!
//! Provenance. Both files under
//! `fixtures/contract_derived_chain_parity/` are copies of
//! ros-launch-manifest TAG v0.1.37 - the tag this repository pins
//! (phase-457 W1) - byte for byte:
//!
//! - `contract_derived_chain.resolved.yaml` <-
//!   `derive/tests/fixtures/contract_derived_chain.system_model.yaml`
//! - `contract_derived_chain.ranked_plan.txt` <-
//!   `derive/tests/snapshots/contract_derived_chain.ranked_plan.txt`
//!
//! Copies rather than a path into a sibling checkout on purpose: the test
//! must run from this repository alone, and a later pin bump that changes
//! the ranking has to fail HERE, loudly, with the two texts to diff, rather
//! than follow whatever the other checkout happens to hold. Re-taking the
//! snapshot is rlm's act (`UPDATE_RANKED_PLAN_SNAPSHOT=1` over there);
//! here it is copied in with the pin, in the same commit, or the gate is a
//! tautology.
//!
//! The file names differ from rlm's by one character each:
//! `scripts/check-no-tracked-models.sh` (phase-330 W7) bans every tracked
//! path ending in `_model.yaml`, because a committed RESOLVED model is a
//! build artifact somebody will hand-edit. This one is a test INPUT, never
//! regenerated by `nros sync` and never read by a build, so it keeps the
//! gate's letter as well as its spirit and is spelled `.resolved.yaml`.
//!
//! What this file does NOT do: re-derive, re-implement or paraphrase the
//! ranking. It calls the same entry point `codegen-system` calls
//! (`nros_orchestration_ir::mapper_input`), which is one call into
//! `ros_launch_manifest_derive` since phase-457 W2.

use nros_orchestration_ir::mapper_input::{mapper_input_and_report, rank_from_model};
use ros_launch_manifest_model::SystemModel;

/// rlm `derive/tests/fixtures/contract_derived_chain.system_model.yaml`.
const CONTRACT_FIXTURE: &str =
    include_str!("../fixtures/contract_derived_chain_parity/contract_derived_chain.resolved.yaml");
/// rlm `derive/tests/snapshots/contract_derived_chain.ranked_plan.txt`.
const SNAPSHOT: &str = include_str!(
    "../fixtures/contract_derived_chain_parity/contract_derived_chain.ranked_plan.txt"
);
/// The island's four timer loops with every rate promise deleted.
const ISLAND_FIXTURE: &str =
    include_str!("../fixtures/contract_derived_chain_parity/island_timers.resolved.yaml");

/// The rlm tag both copies came from. Named here so a pin bump that forgets
/// to re-copy them is visible in the diff of this file.
const RLM_TAG: &str = "v0.1.37";

fn model(yaml: &str) -> SystemModel {
    SystemModel::from_yaml_str(yaml).expect("the fixture parses as a SystemModel")
}

/// The one rendering every consumer compares against: `{:#?}` plus a
/// trailing newline, so the snapshot is a text file. rlm's `render`.
fn render(plan: &impl std::fmt::Debug) -> String {
    format!("{plan:#?}\n")
}

/// Name the first differing line rather than print two screens of text, so a
/// consumer that fails this gate sees the fact that moved.
fn assert_matches_snapshot(actual: &str, expected: &str) {
    if actual == expected {
        return;
    }
    let first_diff = actual
        .lines()
        .zip(expected.lines())
        .position(|(a, e)| a != e)
        .unwrap_or(actual.lines().count().min(expected.lines().count()))
        + 1;
    panic!(
        "the ranking of rlm's contract_derived_chain fixture differs from the \
         snapshot rlm {RLM_TAG} ships, at line {first_diff}.\n\
         Either the pin moved the derivation or something here stopped calling \
         it; re-copy BOTH files from the new tag only after reading rlm's own \
         reason for the change.\n\
         --- expected (rlm {RLM_TAG})\n{expected}\n--- actual (nano-ros)\n{actual}"
    );
}

// ---------------------------------------------------------------------------
// 1. parity with rlm's snapshot
// ---------------------------------------------------------------------------

/// `rank_from_model` over rlm's fixture is rlm's snapshot, byte for byte:
/// one chain drained toward its sink (`control` above `filter`, one event
/// segment), the 100 Hz timer boundary below both, no other item, and a
/// feasibility verdict that names the boundary it took on trust.
#[test]
fn the_shared_contract_ranks_to_the_snapshot_rlm_ships() {
    let plan = rank_from_model(&model(CONTRACT_FIXTURE));
    assert_matches_snapshot(&render(&plan), SNAPSHOT);

    // What the snapshot pins, in words, so a diff reads as a fact.
    let order: Vec<(&str, &str)> = plan
        .items
        .iter()
        .map(|it| (it.node.as_str(), it.path.as_str()))
        .collect();
    assert_eq!(
        order,
        vec![
            ("/control/control_node", "control"),
            ("/perception/filter_component", "filter"),
            ("/perception/sensor_node", "tick"),
        ],
        "drain toward the sink, then the boundary; the container has no path"
    );
    assert_eq!(
        plan.items[0].fine_group, plan.items[1].fine_group,
        "control and filter are one event segment"
    );
    assert_ne!(plan.items[1].fine_group, plan.items[2].fine_group);
    assert!(
        plan.items
            .iter()
            .all(|it| it.coarse_group.as_deref() == Some("points_to_cmd")),
        "every item is the chain's: {:?}",
        plan.items
    );
}

/// The facts the ranking above was derived from, through THIS repository's
/// entry point: the chain rlm resolves is resolved here too, no path is left
/// unclassified, and the timer's rate comes off the trigger.
///
/// Without this a snapshot match could hide a derivation that ranked the
/// right three items for the wrong reasons - and phase-457 exists because
/// that is exactly what happened for the whole of phase-296's lifetime.
#[test]
fn the_same_input_facts_reach_the_ranker_here() {
    let model = model(CONTRACT_FIXTURE);
    let (input, report) = mapper_input_and_report(&model, None);

    assert!(
        report.paths_without_trigger.is_empty(),
        "every path in the fixture carries a trigger: {:?}",
        report.paths_without_trigger
    );
    assert_eq!(
        input.chains.len(),
        1,
        "the scope path resolves to one chain: {:?}",
        input.chains
    );

    let node = |name: &str| input.nodes.iter().find(|n| n.name == name).unwrap();
    let sensor = node("/perception/sensor_node");
    assert_eq!(
        sensor.rate_hz,
        Some(100.0),
        "the timer's rate, from the trigger, not from a promise"
    );
    assert_eq!(sensor.criticality, None);
    let control = node("/control/control_node");
    assert_eq!(
        control.rate_hz, None,
        "an input path has no rate of its own"
    );
    assert_eq!(control.deadline_us, Some(10_000));
    assert!(input.nodes.iter().all(|n| !n.claims_concurrency));

    // phase-457 W2's one consumer-side correction (rlm design issue #52's
    // open seam): `MapperNode::scope` is the ROS namespace a `[[assign]]
    // scope =` selector matches, not the model's launch-FILE scope key. It
    // does not reach the ranking - the snapshot above is unaffected - but
    // both toolchains must spell it the same or one rule selects different
    // nodes in each.
    assert_eq!(sensor.scope, "/perception");
    assert_eq!(control.scope, "/control");
}

/// The snapshot file is what it claims to be without running anything: a
/// reader should be able to trust its first lines.
#[test]
fn the_snapshot_is_a_ranked_plan_of_three_items() {
    assert!(SNAPSHOT.starts_with("RankedPlan {\n"), "{SNAPSHOT}");
    assert!(SNAPSHOT.ends_with("}\n"), "the file ends in one newline");
    assert_eq!(SNAPSHOT.matches("RankItem {").count(), 3);
    assert_eq!(SNAPSHOT.matches("ChainFeasibleWithoutWcet").count(), 1);
    assert!(SNAPSHOT.is_ascii(), "the snapshot is keyboard ASCII");
    assert!(
        CONTRACT_FIXTURE.contains("trigger:"),
        "the fixture is a post-{RLM_TAG} model; a copy without triggers would \
         rank nothing and the snapshot would not be this"
    );
}

// ---------------------------------------------------------------------------
// 2. the island, ranked from its timers alone
// ---------------------------------------------------------------------------

/// The island's four timer loops rank by period - both 30 Hz loops above
/// both 10 Hz ones - from a model carrying NO rate promise at all.
///
/// The island declares its promises (`min_rate_hz` on every endpoint, equal
/// to the timers; the resolver flags 14 as `derivable-min-rate`), so before
/// phase-457 W2 the derived order here was right by a redundant declaration:
/// the period was reconstructed from the first output's promise. Delete the
/// promises, as this fixture does, and the old derivation ranked nothing.
/// What ranks now is `contracts.node_paths.*.trigger`.
#[test]
fn the_island_ranks_from_its_timers_with_no_rate_promises() {
    let model = model(ISLAND_FIXTURE);

    // Checked on the WIRE FORM of the parsed model, not on the fixture text:
    // the file's own header says what was deleted and why, and a test that
    // grepped the text would be asserting against that prose.
    let wire = model.to_yaml_string().expect("the model re-serializes");
    assert!(
        !wire.contains("min_rate_hz"),
        "the point of the fixture is that no rate PROMISE is in it:\n{wire}"
    );
    assert_eq!(
        wire.matches("rate_hz").count(),
        4,
        "the only rates in the model are the four timers' own:\n{wire}"
    );

    let (input, report) = mapper_input_and_report(&model, None);
    assert!(
        report.paths_without_trigger.is_empty(),
        "{:?}",
        report.paths_without_trigger
    );
    let rate = |name: &str| {
        input
            .nodes
            .iter()
            .find(|n| n.name == name)
            .unwrap_or_else(|| panic!("{name} is in the model"))
            .rate_hz
    };
    assert_eq!(rate("/mrm_emergency_stop_operator"), Some(30.0));
    assert_eq!(rate("/stop_mode_operator"), Some(30.0));
    assert_eq!(rate("/mrm_comfortable_stop_operator"), Some(10.0));
    assert_eq!(rate("/mrm_handler"), Some(10.0));

    // No end-to-end budget is declared on the island, so these four are the
    // non-chain remainder: one criticality bucket (none declares one), then
    // time budget ascending, which on four timers is rate-monotonic.
    assert!(input.chains.is_empty(), "the island declares no scope path");
    let plan = rank_from_model(&model);
    let order: Vec<&str> = plan.items.iter().map(|it| it.node.as_str()).collect();
    assert_eq!(order.len(), 4, "one item per timer path: {:?}", plan.items);
    let pos = |name: &str| order.iter().position(|n| *n == name).unwrap();
    for fast in ["/mrm_emergency_stop_operator", "/stop_mode_operator"] {
        for slow in ["/mrm_comfortable_stop_operator", "/mrm_handler"] {
            assert!(
                pos(fast) < pos(slow),
                "the 30 Hz {fast} must outrank the 10 Hz {slow}: {order:?}"
            );
        }
    }
    // Declaration order in `structure.nodes` is the launch file's, which
    // interleaves the rates; a pass-through would return it unchanged.
    assert_ne!(
        order,
        vec![
            "/mrm_emergency_stop_operator",
            "/mrm_comfortable_stop_operator",
            "/stop_mode_operator",
            "/mrm_handler",
        ],
        "the ranking is not the declaration order"
    );
    assert!(
        plan.items
            .iter()
            .all(|it| it.provenance.contains("non-chain")),
        "every item is the non-chain remainder: {:?}",
        plan.items
    );
}
