// nros-c message type - C implementation
// Package: sensor_msgs
// Message: RelativeHumidity
// Auto-generated by rosidl-codegen - do not edit

#include "sensor_msgs_msg_relative_humidity.h"
#include <nros/types.h>
#include <nros/cdr.h>
#include <string.h>

// Type support structure
static const nros_message_type_t sensor_msgs_msg_relative_humidity_type_support = {
    .type_name = "sensor_msgs::msg::dds_::RelativeHumidity_",
    .type_hash = "TypeHashNotSupported",
    .serialized_size_max = 0,  // Dynamic/unknown
};

const nros_message_type_t* sensor_msgs_msg_relative_humidity_get_type_support(void) {
    return &sensor_msgs_msg_relative_humidity_type_support;
}

void sensor_msgs_msg_relative_humidity_init(sensor_msgs_msg_relative_humidity* msg) {
    if (msg == NULL) return;
    memset(msg, 0, sizeof(sensor_msgs_msg_relative_humidity));
}

// =============================================================================
// Inline serialize — writes fields only into an already-open CDR stream.
// Used by parent messages, services, and actions that embed this type as a
// nested field. Does NOT write an encapsulation header. `origin` is the
// CDR alignment origin of the surrounding encapsulation.
// =============================================================================
int32_t sensor_msgs_msg_relative_humidity_serialize_inline(const sensor_msgs_msg_relative_humidity* msg, uint8_t** ptr_ref, const uint8_t* end, const uint8_t* origin) {
    if (msg == NULL || ptr_ref == NULL || *ptr_ref == NULL) return -1;
    uint8_t* ptr = *ptr_ref;
    (void)origin; // may be unused for empty structs
    if (std_msgs_msg_header_serialize_inline(&msg->header, &ptr, end, origin) < 0) return -1;
    if (nros_cdr_write_f64(&ptr, end, origin, msg->relative_humidity) < 0) return -1;
    if (nros_cdr_write_f64(&ptr, end, origin, msg->variance) < 0) return -1;
    *ptr_ref = ptr;
    return 0;
}

// =============================================================================
// Public serialize — writes a fresh 4-byte CDR encapsulation header then
// delegates to the inline serializer.
// =============================================================================
int32_t sensor_msgs_msg_relative_humidity_serialize(const sensor_msgs_msg_relative_humidity* msg, uint8_t* buffer, size_t buffer_size, size_t* serialized_size) {
    if (msg == NULL || buffer == NULL) return -1;

    uint8_t* ptr = buffer;
    const uint8_t* end = buffer + buffer_size;

    // Write CDR header (little-endian, version 1)
    if (ptr + 4 > end) return -1;
    *ptr++ = 0x00; // CDR encapsulation
    *ptr++ = 0x01; // Little-endian
    *ptr++ = 0x00; // Options (unused)
    *ptr++ = 0x00; // Options (unused)
    const uint8_t* origin = ptr; // CDR alignment origin (after header)

    if (sensor_msgs_msg_relative_humidity_serialize_inline(msg, &ptr, end, origin) < 0) return -1;

    if (serialized_size != NULL) {
        *serialized_size = (size_t)(ptr - buffer);
    }
    return 0;
}

// =============================================================================
// Inline deserialize — reads fields only from an already-open CDR stream.
// =============================================================================
int32_t sensor_msgs_msg_relative_humidity_deserialize_inline(sensor_msgs_msg_relative_humidity* msg, const uint8_t** ptr_ref, const uint8_t* end, const uint8_t* origin) {
    if (msg == NULL || ptr_ref == NULL || *ptr_ref == NULL) return -1;
    const uint8_t* ptr = *ptr_ref;
    (void)origin;
    if (std_msgs_msg_header_deserialize_inline(&msg->header, &ptr, end, origin) < 0) return -1;
    if (nros_cdr_read_f64(&ptr, end, origin, &msg->relative_humidity) < 0) return -1;
    if (nros_cdr_read_f64(&ptr, end, origin, &msg->variance) < 0) return -1;
    *ptr_ref = ptr;
    return 0;
}

// =============================================================================
// Public deserialize — skips the 4-byte CDR encapsulation header then
// delegates to the inline deserializer.
// =============================================================================
int32_t sensor_msgs_msg_relative_humidity_deserialize(sensor_msgs_msg_relative_humidity* msg, const uint8_t* buffer, size_t buffer_size) {
    if (msg == NULL || buffer == NULL) return -1;

    const uint8_t* ptr = buffer;
    const uint8_t* end = buffer + buffer_size;

    // Skip CDR header
    if (ptr + 4 > end) return -1;
    ptr += 4;
    const uint8_t* origin = ptr; // CDR alignment origin (after header)

    sensor_msgs_msg_relative_humidity_init(msg);

    if (sensor_msgs_msg_relative_humidity_deserialize_inline(msg, &ptr, end, origin) < 0) return -1;
    return 0;
}