// nros-c message type - C header for embedded systems
// Package: sensor_msgs
// Message: Temperature
// Auto-generated by rosidl-codegen - do not edit

#ifndef SENSOR_MSGS_MSG_TEMPERATURE_H
#define SENSOR_MSGS_MSG_TEMPERATURE_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#include <nros/types.h>

#ifdef __cplusplus
extern "C" {
#endif
#include "std_msgs/msg/std_msgs_msg_header.h"

// Constants

/// Temperature message structure
typedef struct sensor_msgs_msg_temperature {
    struct std_msgs_msg_header header;
    double temperature;
    double variance;
} sensor_msgs_msg_temperature;

/// Get the ROS type name for Temperature
static inline const char* sensor_msgs_msg_temperature_get_type_name(void) {
    return "sensor_msgs::msg::dds_::Temperature_";
}

/// Get the type hash for Temperature
static inline const char* sensor_msgs_msg_temperature_get_type_hash(void) {
    return "TypeHashNotSupported";
}

/// Initialize a Temperature message to default values
void sensor_msgs_msg_temperature_init(sensor_msgs_msg_temperature* msg);

/// Serialize a Temperature message to CDR format (writes a fresh
/// 4-byte CDR encapsulation header followed by the fields).
/// Returns 0 on success, -1 on error. On success, *serialized_size contains
/// bytes written.
int32_t sensor_msgs_msg_temperature_serialize(const sensor_msgs_msg_temperature* msg, uint8_t* buffer, size_t buffer_size, size_t* serialized_size);

/// Deserialize a Temperature message from CDR format (expects a
/// 4-byte CDR encapsulation header followed by the fields).
/// Returns 0 on success, -1 on error
int32_t sensor_msgs_msg_temperature_deserialize(sensor_msgs_msg_temperature* msg, const uint8_t* buffer, size_t buffer_size);

/// Serialize a Temperature inline into an already-open CDR stream,
/// without emitting its own encapsulation header. Used by parent messages,
/// services, and actions that embed this type as a nested field.
/// - ptr_ref: in/out current write pointer (advanced on success)
/// - end: one-past-last byte of the destination buffer
/// - origin: CDR alignment origin (start of the surrounding encapsulation)
/// Returns 0 on success, -1 on error.
int32_t sensor_msgs_msg_temperature_serialize_inline(const sensor_msgs_msg_temperature* msg, uint8_t** ptr_ref, const uint8_t* end, const uint8_t* origin);

/// Deserialize a Temperature inline from an already-open CDR stream,
/// without consuming an encapsulation header. Parameters mirror the inline
/// serialize variant.
int32_t sensor_msgs_msg_temperature_deserialize_inline(sensor_msgs_msg_temperature* msg, const uint8_t** ptr_ref, const uint8_t* end, const uint8_t* origin);

/// Get the nros_message_type_t for this message type
const nros_message_type_t* sensor_msgs_msg_temperature_get_type_support(void);

/// Typed publish helper. Serializes `msg` into a stack buffer of size
/// `NROS_PUB_BUFFER_SIZE` (override at compile time; default 256) then
/// hands it to nros_publish_raw. nros_ret_t / nros_publisher_t /
/// nros_publish_raw all come in via <nros/types.h> (already included
/// at the top of this header).
#ifndef NROS_PUB_BUFFER_SIZE
#define NROS_PUB_BUFFER_SIZE 256
#endif
static inline nros_ret_t sensor_msgs_msg_temperature_publish(struct nros_publisher_t* publisher,
                                                   const sensor_msgs_msg_temperature* msg) {
    uint8_t buf[NROS_PUB_BUFFER_SIZE];
    size_t n = 0;
    int32_t r = sensor_msgs_msg_temperature_serialize(msg, buf, sizeof(buf), &n);
    if (r != 0) return r;
    return nros_publish_raw(publisher, buf, n);
}

#ifdef __cplusplus
}
#endif

#endif // SENSOR_MSGS_MSG_TEMPERATURE_H