// nros-c message type - C header for embedded systems
// Package: sensor_msgs
// Message: NavSatFix
// Auto-generated by rosidl-codegen - do not edit

#ifndef SENSOR_MSGS_MSG_NAV_SAT_FIX_H
#define SENSOR_MSGS_MSG_NAV_SAT_FIX_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#include <nros/types.h>

#ifdef __cplusplus
extern "C" {
#endif
#include "sensor_msgs_msg_nav_sat_status.h"
#include "std_msgs/msg/std_msgs_msg_header.h"

// Constants
#define SENSOR_MSGS_MSG_NAV_SAT_FIX_COVARIANCE_TYPE_UNKNOWN 0
#define SENSOR_MSGS_MSG_NAV_SAT_FIX_COVARIANCE_TYPE_APPROXIMATED 1
#define SENSOR_MSGS_MSG_NAV_SAT_FIX_COVARIANCE_TYPE_DIAGONAL_KNOWN 2
#define SENSOR_MSGS_MSG_NAV_SAT_FIX_COVARIANCE_TYPE_KNOWN 3

/// NavSatFix message structure
typedef struct sensor_msgs_msg_nav_sat_fix {
    struct std_msgs_msg_header header;
    struct sensor_msgs_msg_nav_sat_status status;
    double latitude;
    double longitude;
    double altitude;
    double position_covariance[9];
    uint8_t position_covariance_type;
} sensor_msgs_msg_nav_sat_fix;

/// Get the ROS type name for NavSatFix
static inline const char* sensor_msgs_msg_nav_sat_fix_get_type_name(void) {
    return "sensor_msgs::msg::dds_::NavSatFix_";
}

/// Get the type hash for NavSatFix
static inline const char* sensor_msgs_msg_nav_sat_fix_get_type_hash(void) {
    return "TypeHashNotSupported";
}

/// Initialize a NavSatFix message to default values
void sensor_msgs_msg_nav_sat_fix_init(sensor_msgs_msg_nav_sat_fix* msg);

/// Serialize a NavSatFix message to CDR format (writes a fresh
/// 4-byte CDR encapsulation header followed by the fields).
/// Returns 0 on success, -1 on error. On success, *serialized_size contains
/// bytes written.
int32_t sensor_msgs_msg_nav_sat_fix_serialize(const sensor_msgs_msg_nav_sat_fix* msg, uint8_t* buffer, size_t buffer_size, size_t* serialized_size);

/// Deserialize a NavSatFix message from CDR format (expects a
/// 4-byte CDR encapsulation header followed by the fields).
/// Returns 0 on success, -1 on error
int32_t sensor_msgs_msg_nav_sat_fix_deserialize(sensor_msgs_msg_nav_sat_fix* msg, const uint8_t* buffer, size_t buffer_size);

/// Serialize a NavSatFix inline into an already-open CDR stream,
/// without emitting its own encapsulation header. Used by parent messages,
/// services, and actions that embed this type as a nested field.
/// - ptr_ref: in/out current write pointer (advanced on success)
/// - end: one-past-last byte of the destination buffer
/// - origin: CDR alignment origin (start of the surrounding encapsulation)
/// Returns 0 on success, -1 on error.
int32_t sensor_msgs_msg_nav_sat_fix_serialize_inline(const sensor_msgs_msg_nav_sat_fix* msg, uint8_t** ptr_ref, const uint8_t* end, const uint8_t* origin);

/// Deserialize a NavSatFix inline from an already-open CDR stream,
/// without consuming an encapsulation header. Parameters mirror the inline
/// serialize variant.
int32_t sensor_msgs_msg_nav_sat_fix_deserialize_inline(sensor_msgs_msg_nav_sat_fix* msg, const uint8_t** ptr_ref, const uint8_t* end, const uint8_t* origin);

/// Get the nros_message_type_t for this message type
const nros_message_type_t* sensor_msgs_msg_nav_sat_fix_get_type_support(void);

/// Typed publish helper. Serializes `msg` into a stack buffer of size
/// `NROS_PUB_BUFFER_SIZE` (override at compile time; default 256) then
/// hands it to nros_publish_raw. nros_ret_t / nros_publisher_t /
/// nros_publish_raw all come in via <nros/types.h> (already included
/// at the top of this header).
#ifndef NROS_PUB_BUFFER_SIZE
#define NROS_PUB_BUFFER_SIZE 256
#endif
static inline nros_ret_t sensor_msgs_msg_nav_sat_fix_publish(struct nros_publisher_t* publisher,
                                                   const sensor_msgs_msg_nav_sat_fix* msg) {
    uint8_t buf[NROS_PUB_BUFFER_SIZE];
    size_t n = 0;
    int32_t r = sensor_msgs_msg_nav_sat_fix_serialize(msg, buf, sizeof(buf), &n);
    if (r != 0) return r;
    return nros_publish_raw(publisher, buf, n);
}

#ifdef __cplusplus
}
#endif

#endif // SENSOR_MSGS_MSG_NAV_SAT_FIX_H