meta:
  version: 1
  inputs:
  - path: launch/system.launch.xml
    sha256: 3e37be9d1dfe695cdc6e3e0d63c402b3489b6a7367b7d23ddd418e00bdfad415
  - path: system.toml
    sha256: 9f840360b0cb5093e33e648ad0bd9f31701e288a05c89a324bb068b464150af0
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
structure:
  scopes:
    system.launch.xml:
      file: system.launch.xml
  nodes:
    /param_talker:
      scope: system.launch.xml
      pkg: c_param_talker_pkg
      exec: param_talker
      params:
        publish_period_ms: 250
      node_name: param_talker
execution:
  deploy:
    /param_talker:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
