meta:
  version: 1
  inputs:
  - path: /home/aeon/repos/nano-ros/examples/workspaces/ws-custom-msg-c/src/demo_bringup/config/system_model.record.json
    sha256: 3ec9255695adff4e4338fa76e2bafddf7019e069b2047827fb12cd1c6bdc424f
  - path: /home/aeon/repos/nano-ros/examples/workspaces/ws-custom-msg-c/src/demo_bringup/launch/system.launch.xml
    sha256: 126b69850f9526e76e13d3c9cf911e856002fd31cedc4d070bf2d4e5b5d44751
  - path: /home/aeon/repos/nano-ros/examples/workspaces/ws-custom-msg-c/src/demo_bringup/system.toml
    sha256: faefb36b029eee69ddc378f462868cb2acae84b3412cc4f7133324e38c37ec0f
  resolver:
    tool: play_launch
    version: 0.8.2
  record:
    path: /home/aeon/repos/nano-ros/examples/workspaces/ws-custom-msg-c/src/demo_bringup/config/system_model.record.json
    sha256: 3ec9255695adff4e4338fa76e2bafddf7019e069b2047827fb12cd1c6bdc424f
structure:
  scopes:
    /: {}
  nodes:
    /reading_listener:
      scope: /
      pkg: reading_listener_pkg
      exec: reading_listener
    /reading_talker:
      scope: /
      pkg: reading_talker_pkg
      exec: reading_talker
execution:
  deploy:
    /reading_listener:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
    /reading_talker:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
