meta:
  version: 1
  inputs:
  - path: /home/aeon/repos/nano-ros/examples/workspaces/ws-realtime-cpp-subnode/src/demo_bringup/launch/system.launch.xml
    sha256: cf0adad5e1ba8b071ba62df40b084d2df2d6b91ba15a123a9b182085b33913f0
  - path: /home/aeon/repos/nano-ros/examples/workspaces/ws-realtime-cpp-subnode/src/demo_bringup/system.toml
    sha256: 8c8512a25923f6edf04c2dc49772e4800ba2e8ca3b98e37fbe1fd86b4152e0b8
  resolver:
    tool: play_launch
    version: 0.8.2
structure:
  scopes:
    /: {}
  nodes:
    /sub_node:
      scope: /
      pkg: subnode_pkg
      exec: subnode
      node_name: sub_node
execution:
  deploy:
    /sub_node:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
  tiers:
    high:
      spin_period_us: 10000
      posix:
        priority: 80
    low:
      spin_period_us: 100000
      posix:
        priority: 10
  bindings:
    /sub_node/ctrl: high
    /sub_node/telem: low
