meta:
  version: 1
  inputs:
  - path: /home/aeon/repos/nano-ros/examples/qemu-arm-freertos/rust/listener-entry/launch/system.launch.xml
    sha256: 530080f8452c1f702e5ddaa8ecfd86ac1b74601cc78c2ad35360960d42966ca0
  resolver:
    tool: play_launch
    version: 0.8.2
structure:
  scopes:
    system.launch.xml:
      file: system.launch.xml
