meta:
  version: 1
  inputs:
  - path: launch/system.launch.xml
    sha256: 530080f8452c1f702e5ddaa8ecfd86ac1b74601cc78c2ad35360960d42966ca0
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
structure:
  scopes:
    system.launch.xml:
      file: system.launch.xml
