//! phase-308 W1 — the C/C++ metadata probe driver.
//!
//! The Rust producer generates a harness *crate* and `cargo run`s it
//! ([`super::metadata_build`]). A C/C++ component cannot be driven that way:
//! its sources are built by its own `CMakeLists.txt`, through
//! `find_package(nano_ros)` and the `nano_ros_*` verbs. So the probe is a
//! generated **CMake project** that adds the component package as a
//! subdirectory, links it into a one-node probe executable, and runs it.
//!
//! The probe TU itself is NOT written here — it comes from
//! `codegen::entry::emit_cpp::emit_typed_probe`, the same emitter that
//! produces real entries. This module owns only the project scaffolding and
//! the configure/build/run invocation.
//!
//! # Why `NROS_RMW=metadata`
//!
//! The probe links a real `libnros_cpp.a`, which force-links whatever backend
//! the component's build selected. Selecting the recording backend by NAME —
//! rather than making it the default — is what keeps that unambiguous: with two
//! registered backends and no selector the executor refuses to open at all.
//!
//! # What this cannot do
//!
//! A component package whose `CMakeLists.txt` pulls board configuration cannot
//! be configured for the host, exactly as a board-coupled Rust crate cannot
//! (issue 0286). Such packages must be reported as un-probeable rather than
//! attempted; the caller degrades them to the sidecar-less path.

use std::{
    path::{Path, PathBuf},
    process::Command,
};

use core::fmt::Write as _;

use eyre::{Result, WrapErr, bail};

use crate::codegen::entry::{
    Plan, PlanNode,
    emit_cpp::{ProbeExport, emit_typed_probe},
};

/// Everything the driver needs to probe one C/C++ component.
#[derive(Debug, Clone)]
pub struct CmakeProbeOptions {
    /// ROS package name (the sidecar's `package`).
    pub package: String,
    /// Component instance name (the sidecar's `component`).
    pub component: String,
    /// Executable name — the `(package, executable)` key consumers match on.
    pub executable: String,
    /// Fully-qualified class, e.g. `talker_pkg::Talker`.
    pub class: String,
    /// Header to `#include`, e.g. `talker_pkg/Talker.hpp`.
    pub header: String,
    /// `"c"` or `"cpp"`.
    pub language: String,
    /// `"configure"` or `"rclcpp"`.
    pub shape: String,
    /// The CMake library target the component builds into. The probe LINKS it —
    /// that is what carries the target's PUBLIC include dirs (its own header,
    /// and any generated message headers it depends on).
    pub library_target: String,
    /// The component package directory (holds its `CMakeLists.txt`).
    pub package_dir: PathBuf,
    /// nano-ros checkout, for `find_package(nano_ros)`.
    pub nano_ros_workspace: PathBuf,
    /// Where the probe writes the sidecar.
    pub output_path: PathBuf,
    /// Scratch directory for the generated probe project.
    pub probe_dir: PathBuf,
}

/// The workspace's single probe project (phase-313).
///
/// One project, one `add_subdirectory` per component package, one probe
/// executable per component. The runtime — and the ~1.2 GB of nested
/// `sizes-probe` cargo builds inside `nros-c` and `nros-cpp`'s build scripts —
/// is then built ONCE for the whole workspace instead of once per component.
///
/// Each package is still built by its OWN `CMakeLists.txt`: same verbs, same
/// interface libraries, same generated message headers. That is what makes "it
/// compiled in the probe" mean "it compiles in an entry", and it is why the
/// recorded entity count can be trusted.
pub fn render_probe_cmakelists(comps: &[CmakeProbeOptions]) -> String {
    let mut out = String::from(concat!(
        "# Generated by `nros` (phase-313) — metadata probes for this workspace.\n",
        "# DO NOT EDIT. Each component is built by its own CMakeLists via\n",
        "# add_subdirectory; only the probe executables are synthesized here.\n",
        "cmake_minimum_required(VERSION 3.22)\n",
        "project(nros_metadata_probes LANGUAGES C CXX)\n\n",
        "set(CMAKE_CXX_STANDARD 14)\n",
        "set(CMAKE_CXX_STANDARD_REQUIRED ON)\n\n",
        "# The recording RMW backend rides in on nros-cpp's `metadata-mode` cargo\n",
        "# feature, appended to the umbrella's feature list. Host build only —\n",
        "# never reachable from a firmware one. NOTE: this must be the variable\n",
        "# NanoRosRuntimeCrate reads; a plain cache var is inert.\n",
        "set(NROS_EXTRA_CPP_FEATURES \"metadata-mode\")\n\n",
        "find_package(nano_ros REQUIRED)\n\n",
    ));
    // Each package added once even when it declares several components.
    let mut added: Vec<&str> = Vec::new();
    for c in comps {
        let dir = c.package_dir.to_string_lossy();
        if added.contains(&dir.as_ref()) {
            continue;
        }
        added.push(Box::leak(dir.clone().into_owned().into_boxed_str()));
        let _ = writeln!(out, "add_subdirectory({dir} {})", c.package);
    }
    out.push('\n');
    for c in comps {
        let _ = writeln!(
            out,
            concat!(
                "add_executable({t} {t}.cpp)\n",
                "# Link the component library, not just build it: linking is what\n",
                "# propagates its PUBLIC include dirs.\n",
                "target_link_libraries({t} PRIVATE {lib})\n",
                "target_link_libraries({t} PRIVATE NanoRos::NanoRosCpp)\n",
                "nano_ros_link_rmw({t})\n",
            ),
            t = c.probe_target(),
            lib = c.library_target,
        );
    }
    out
}

impl CmakeProbeOptions {
    /// CMake target name for this component's probe. Package + component, so a
    /// workspace with several components per package stays unambiguous.
    pub fn probe_target(&self) -> String {
        format!("probe_{}__{}", self.package, self.component).replace(['-', '.', '/'], "_")
    }
}

/// The probe TU, from the SAME emitter that produces real entries.
pub fn render_probe_main(o: &CmakeProbeOptions) -> Result<String> {
    let plan = probe_plan(o);
    let export = ProbeExport {
        package: o.package.clone(),
        component: o.component.clone(),
        executable: o.executable.clone(),
        language: o.language.clone(),
        out_path: o.output_path.display().to_string(),
    };
    emit_typed_probe(&plan, &export)
        .map_err(|e| eyre::eyre!("emit metadata probe for `{}`: {e}", o.package))
}

/// A one-node plan describing just this component.
///
/// `board = "native"` because the probe is a HOST binary — the same reason one
/// probe covers every deploy target.
fn probe_plan(o: &CmakeProbeOptions) -> Plan {
    Plan {
        board: "native".into(),
        bringup: format!("{}_metadata_probe", o.package),
        launch_file: o.package_dir.join("metadata-probe.launch.xml"),
        nodes: vec![PlanNode {
            pkg: o.package.clone(),
            exec: o.executable.clone(),
            name: Some(o.component.clone()),
            namespace: None,
            class_name: Some(o.class.clone()),
            class_header: Some(o.header.clone()),
            lang: Some(o.language.clone()),
            shape: Some(o.shape.clone()),
            qos_overrides: Vec::new(),
            params: Vec::new(),
            remaps: Vec::new(),
            callback_groups: Vec::new(),
            sched_context: None,
            group_tiers: std::collections::BTreeMap::new(),
        }],
        depfile_paths: Vec::new(),
        lifecycle: None,
        param_services: false,
        safety: None,
        tiers: Default::default(),
        node_overrides: Vec::new(),
        resolved_tiers: None,
    }
}

/// Outcome of one component's probe within a batched run.
pub struct ProbeOutcome {
    pub package: String,
    pub component: String,
    /// `Ok(())` = the sidecar was written; `Err` = this component only.
    pub result: Result<()>,
}

/// Generate + configure ONE project for the whole workspace, then build and run
/// each component's probe individually (phase-313).
///
/// Configure is shared — that is where the saving is — but the BUILD is
/// per-target, so a component whose sources do not compile costs only its own
/// sidecar. Batching the build would make one bad component lose every
/// component's metadata, which is a robustness regression against the
/// per-component projects this replaces.
pub fn run_probes(probe_dir: &Path, comps: &[CmakeProbeOptions]) -> Result<Vec<ProbeOutcome>> {
    if comps.is_empty() {
        return Ok(Vec::new());
    }
    std::fs::create_dir_all(probe_dir)
        .wrap_err_with(|| format!("create {}", probe_dir.display()))?;
    std::fs::write(
        probe_dir.join("CMakeLists.txt"),
        render_probe_cmakelists(comps),
    )?;
    for c in comps {
        std::fs::write(
            probe_dir.join(format!("{}.cpp", c.probe_target())),
            render_probe_main(c)?,
        )?;
        if let Some(parent) = c.output_path.parent() {
            std::fs::create_dir_all(parent)?;
        }
    }

    let build_dir = probe_dir.join("build");
    let nano_ros = &comps[0].nano_ros_workspace;
    // A configure failure IS fatal: it means the project itself is malformed,
    // not that one component is unprobeable.
    run_step(
        Command::new("cmake")
            .arg("-S")
            .arg(probe_dir)
            .arg("-B")
            .arg(&build_dir)
            .arg(format!("-DCMAKE_PREFIX_PATH={}", nano_ros.display()))
            .env("NROS_WORKSPACE", nano_ros),
        "configure",
        "workspace",
    )?;

    // Build EVERY probe in one parallel invocation. One `cmake --build` per
    // component was serial by construction, and each one links a real
    // `libnros_cpp.a` — on a workspace with seven C/C++ components that is
    // seven sequential link steps inside a single `nros sync`, which is what
    // made sync look like it was hanging for minutes.
    //
    // On failure we fall back to the per-target loop: a batched build reports
    // one anonymous non-zero exit, and this driver's contract is that ONE
    // unprobeable component degrades to the sidecar-less path by NAME rather
    // than taking the whole workspace with it.
    let targets: Vec<String> = comps.iter().map(|c| c.probe_target()).collect();
    let batched = build_all(&build_dir, &targets);

    let mut out = Vec::new();
    for c in comps {
        let target = c.probe_target();
        let result = if batched.is_ok() {
            run_one(&build_dir, c, &target)
        } else {
            build_and_run_one(&build_dir, c, &target)
        };
        out.push(ProbeOutcome {
            package: c.package.clone(),
            component: c.component.clone(),
            result,
        });
    }
    Ok(out)
}

/// Build every probe target in ONE parallel `cmake --build`.
fn build_all(build_dir: &Path, targets: &[String]) -> Result<()> {
    let mut cmd = Command::new("cmake");
    cmd.arg("--build").arg(build_dir).arg("--parallel");
    // Multiple `--target` arguments in one invocation: CMake >= 3.15, and this
    // project pins 3.22.
    cmd.arg("--target");
    for t in targets {
        cmd.arg(t);
    }
    run_step(&mut cmd, "build", "all probes")
}

fn build_and_run_one(build_dir: &Path, c: &CmakeProbeOptions, target: &str) -> Result<()> {
    run_step(
        Command::new("cmake")
            .arg("--build")
            .arg(build_dir)
            .arg("--target")
            .arg(target),
        "build",
        &format!("{}::{}", c.package, c.component),
    )?;
    run_one(build_dir, c, target)
}

/// Run a probe that is already built, and check it wrote its sidecar.
fn run_one(build_dir: &Path, c: &CmakeProbeOptions, target: &str) -> Result<()> {
    run_step(
        // Selecting by NAME is why the backend registers that way: the probe
        // also links the component's real backend, and with two registered and
        // no selector the executor refuses to open.
        Command::new(build_dir.join(target)).env("NROS_RMW", "metadata"),
        "run",
        &format!("{}::{}", c.package, c.component),
    )?;
    if !c.output_path.is_file() {
        bail!(
            "metadata probe for `{}::{}` exited 0 but wrote no sidecar at {}",
            c.package,
            c.component,
            c.output_path.display()
        );
    }
    Ok(())
}

fn run_step(cmd: &mut Command, step: &str, who: &str) -> Result<()> {
    let out = cmd
        .output()
        .wrap_err_with(|| format!("spawn metadata probe {step} for `{who}`"))?;
    if !out.status.success() {
        // The component's own build errors are the useful part; surface them
        // rather than just the exit code.
        bail!(
            "metadata probe {step} failed for `{who}` (exit {}):\n{}\n{}",
            out.status.code().unwrap_or(-1),
            String::from_utf8_lossy(&out.stdout),
            String::from_utf8_lossy(&out.stderr),
        );
    }
    Ok(())
}

/// Path helper: the ONE probe project dir for a workspace (phase-313).
///
/// Was per component, which is what made every probe rebuild the runtime.
pub fn probe_dir_for_workspace(root: &Path) -> PathBuf {
    root.join("metadata-probe-cmake")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn opts() -> CmakeProbeOptions {
        CmakeProbeOptions {
            package: "talker_pkg".into(),
            component: "talker".into(),
            executable: "talker".into(),
            class: "talker_pkg::Talker".into(),
            header: "talker_pkg/Talker.hpp".into(),
            language: "cpp".into(),
            shape: "configure".into(),
            library_target: "talker_lib".into(),
            package_dir: PathBuf::from("/ws/src/talker_pkg"),
            nano_ros_workspace: PathBuf::from("/nano-ros"),
            output_path: PathBuf::from("/ws/src/talker_pkg/metadata/talker.json"),
            probe_dir: PathBuf::from("/scratch/probe"),
        }
    }

    /// The component is built by its OWN CMakeLists, not a reimplementation of
    /// it — that is what makes "it compiled here" mean "it compiles in an
    /// entry".
    #[test]
    fn cmakelists_adds_the_component_package_and_enables_metadata_mode() {
        let txt = render_probe_cmakelists(std::slice::from_ref(&opts()));
        assert!(
            txt.contains("add_subdirectory(/ws/src/talker_pkg talker_pkg)"),
            "{txt}"
        );
        assert!(txt.contains("find_package(nano_ros REQUIRED)"), "{txt}");
        assert!(
            txt.contains("set(NROS_EXTRA_CPP_FEATURES \"metadata-mode\")"),
            "the recording backend rides in on this feature:\n{txt}"
        );
        assert!(
            txt.contains("nano_ros_link_rmw(probe_talker_pkg__talker)"),
            "{txt}"
        );
        // NanoRosCpp, not NanoRos: only the Cpp target carries the `nros/*.hpp`
        // include dirs, and the probe TU is C++ even for a C component.
        assert!(
            txt.contains("NanoRos::NanoRosCpp"),
            "probe needs the C++ include dirs:\n{txt}"
        );
        // Linking the component lib is what brings its own header's include dir.
        assert!(txt.contains("PRIVATE talker_lib"), "{txt}");
    }

    /// The probe TU comes from the entry emitter, so the construction and
    /// `configure` call are the ones a real entry would make.
    #[test]
    fn probe_main_is_the_entry_setup_body_with_a_dump_tail() {
        let src = render_probe_main(&opts()).expect("emit");
        assert!(src.contains("#include \"talker_pkg/Talker.hpp\""), "{src}");
        assert!(src.contains(".configure("), "{src}");
        assert!(
            src.contains("nros_cpp_metadata_dump(\"talker_pkg\", \"talker\", \"talker\", \"cpp\""),
            "{src}"
        );
        assert!(
            src.contains("/ws/src/talker_pkg/metadata/talker.json"),
            "{src}"
        );
        assert!(
            !src.contains("::run_components("),
            "a probe never spins:\n{src}"
        );
    }

    /// A C component takes the C-ABI factory seam, not a C++ class construct —
    /// routed by `lang`, by the same emitter branch a real entry uses.
    #[test]
    fn c_components_route_through_the_c_abi_seam() {
        let mut o = opts();
        o.language = "c".into();
        o.package = "c_talker_pkg".into();
        o.class = "c_talker_pkg::Talker".into();
        let src = render_probe_main(&o).expect("emit");
        assert!(
            src.contains("__nros_c_component_c_talker_pkg_configure"),
            "{src}"
        );
    }

    /// phase-313 — ONE project for the workspace. Per-component dirs are what
    /// made every probe rebuild the runtime and the nested sizes probes.
    #[test]
    fn the_probe_project_is_per_workspace() {
        assert_eq!(
            probe_dir_for_workspace(Path::new("/b")),
            Path::new("/b/metadata-probe-cmake")
        );
    }

    /// Several components share one project: one `add_subdirectory` per
    /// PACKAGE (deduped), one executable per COMPONENT.
    #[test]
    fn a_batch_adds_each_package_once_and_one_target_per_component() {
        let mut a = opts();
        let mut b = opts();
        b.component = "second".into();
        b.class = "talker_pkg::Second".into();
        b.header = "talker_pkg/Second.hpp".into();
        let mut c = opts();
        c.package = "listener_pkg".into();
        c.component = "listener".into();
        c.package_dir = PathBuf::from("/ws/src/listener_pkg");
        c.library_target = "listener_lib".into();
        a.component = "talker".into();

        let txt = render_probe_cmakelists(&[a, b, c]);
        assert_eq!(
            txt.matches("add_subdirectory(/ws/src/talker_pkg").count(),
            1,
            "one package, added once even with two components:\n{txt}"
        );
        assert!(
            txt.contains("add_subdirectory(/ws/src/listener_pkg"),
            "{txt}"
        );
        for t in [
            "probe_talker_pkg__talker",
            "probe_talker_pkg__second",
            "probe_listener_pkg__listener",
        ] {
            assert!(
                txt.contains(&format!("add_executable({t} {t}.cpp)")),
                "{t}\n{txt}"
            );
        }
    }
}
