//! phase-308 W1 — the C/C++ metadata probe driver.
//!
//! The Rust producer generates a harness *crate* and `cargo run`s it
//! ([`super::metadata_build`]). A C/C++ component cannot be driven that way:
//! its sources are built by its own `CMakeLists.txt`, through
//! `find_package(nano_ros)` and the `nano_ros_*` verbs. So the probe is a
//! generated **CMake project** that adds the component package as a
//! subdirectory, links it into a one-node probe executable, and runs it.
//!
//! The probe TU itself is NOT written here — it comes from
//! `codegen::entry::emit_cpp::emit_typed_probe`, the same emitter that
//! produces real entries. This module owns only the project scaffolding and
//! the configure/build/run invocation.
//!
//! # Why `NROS_RMW=metadata`
//!
//! The probe links a real `libnros_cpp.a`, which force-links whatever backend
//! the component's build selected. Selecting the recording backend by NAME —
//! rather than making it the default — is what keeps that unambiguous: with two
//! registered backends and no selector the executor refuses to open at all.
//!
//! # What this cannot do
//!
//! A component package whose `CMakeLists.txt` pulls board configuration cannot
//! be configured for the host, exactly as a board-coupled Rust crate cannot
//! (issue 0286). Such packages must be reported as un-probeable rather than
//! attempted; the caller degrades them to the sidecar-less path.

use std::{
    path::{Path, PathBuf},
    process::Command,
};

use eyre::{Result, WrapErr, bail};

use crate::codegen::entry::{
    Plan, PlanNode,
    emit_cpp::{ProbeExport, emit_typed_probe},
};

/// Everything the driver needs to probe one C/C++ component.
#[derive(Debug, Clone)]
pub struct CmakeProbeOptions {
    /// ROS package name (the sidecar's `package`).
    pub package: String,
    /// Component instance name (the sidecar's `component`).
    pub component: String,
    /// Executable name — the `(package, executable)` key consumers match on.
    pub executable: String,
    /// Fully-qualified class, e.g. `talker_pkg::Talker`.
    pub class: String,
    /// Header to `#include`, e.g. `talker_pkg/Talker.hpp`.
    pub header: String,
    /// `"c"` or `"cpp"`.
    pub language: String,
    /// `"configure"` or `"rclcpp"`.
    pub shape: String,
    /// The component package directory (holds its `CMakeLists.txt`).
    pub package_dir: PathBuf,
    /// nano-ros checkout, for `find_package(nano_ros)`.
    pub nano_ros_workspace: PathBuf,
    /// Where the probe writes the sidecar.
    pub output_path: PathBuf,
    /// Scratch directory for the generated probe project.
    pub probe_dir: PathBuf,
}

/// The probe project's `CMakeLists.txt`.
///
/// `add_subdirectory` on the component package builds it exactly as a real
/// consumer would — same verbs, same interface libraries, same generated
/// message headers. Anything that would not compile here would not compile in
/// an entry either, which is the property that makes the recorded count
/// trustworthy.
pub fn render_probe_cmakelists(o: &CmakeProbeOptions) -> String {
    format!(
        "# Generated by `nros` (phase-308) — metadata probe for {pkg}::{comp}.\n\
         # DO NOT EDIT. Builds the component exactly as a consumer would, links\n\
         # it into a probe that records its declarations instead of running them.\n\
         cmake_minimum_required(VERSION 3.22)\n\
         project(nros_metadata_probe LANGUAGES C CXX)\n\
         \n\
         set(CMAKE_CXX_STANDARD 14)\n\
         set(CMAKE_CXX_STANDARD_REQUIRED ON)\n\
         \n\
         # The recording RMW backend rides in on nros-cpp's `metadata-mode`\n\
         # cargo feature. Host build only — never reachable from a firmware one.\n\
         set(NANO_ROS_CARGO_FEATURES \"metadata-mode\" CACHE STRING \"\" FORCE)\n\
         \n\
         find_package(nano_ros REQUIRED)\n\
         \n\
         # The component package, built by its OWN CMakeLists — same verbs and\n\
         # interface libs a real consumer gets.\n\
         add_subdirectory({pkg_dir} component_pkg)\n\
         \n\
         add_executable(nros_metadata_probe probe_main.cpp)\n\
         # NanoRosCpp, not NanoRos: the probe TU is C++ even when the component\n\
         # is C (it drives the C ABI seam), and only the Cpp target carries the\n\
         # `nros/*.hpp` include dirs. Linking the C target compiles the probe\n\
         # with no `<nros/component.hpp>` on the include path.\n\
         target_link_libraries(nros_metadata_probe PRIVATE NanoRos::NanoRosCpp)\n\
         nano_ros_link_rmw(nros_metadata_probe)\n",
        pkg = o.package,
        comp = o.component,
        pkg_dir = o.package_dir.display(),
    )
}

/// The probe TU, from the SAME emitter that produces real entries.
pub fn render_probe_main(o: &CmakeProbeOptions) -> Result<String> {
    let plan = probe_plan(o);
    let export = ProbeExport {
        package: o.package.clone(),
        component: o.component.clone(),
        executable: o.executable.clone(),
        language: o.language.clone(),
        out_path: o.output_path.display().to_string(),
    };
    emit_typed_probe(&plan, &export)
        .map_err(|e| eyre::eyre!("emit metadata probe for `{}`: {e}", o.package))
}

/// A one-node plan describing just this component.
///
/// `board = "native"` because the probe is a HOST binary — the same reason one
/// probe covers every deploy target.
fn probe_plan(o: &CmakeProbeOptions) -> Plan {
    Plan {
        board: "native".into(),
        bringup: format!("{}_metadata_probe", o.package),
        launch_file: o.package_dir.join("metadata-probe.launch.xml"),
        nodes: vec![PlanNode {
            pkg: o.package.clone(),
            exec: o.executable.clone(),
            name: Some(o.component.clone()),
            namespace: None,
            class_name: Some(o.class.clone()),
            class_header: Some(o.header.clone()),
            lang: Some(o.language.clone()),
            shape: Some(o.shape.clone()),
            host: None,
            qos_overrides: Vec::new(),
            params: Vec::new(),
            remaps: Vec::new(),
            callback_groups: Vec::new(),
            sched_context: None,
            group_tiers: std::collections::BTreeMap::new(),
        }],
        depfile_paths: Vec::new(),
        lifecycle: None,
        param_services: false,
        safety: None,
        tiers: Default::default(),
        node_overrides: Vec::new(),
        resolved_tiers: None,
    }
}

/// Generate, configure, build and run the probe. It writes the sidecar itself.
pub fn run_probe(o: &CmakeProbeOptions) -> Result<()> {
    std::fs::create_dir_all(&o.probe_dir)
        .wrap_err_with(|| format!("create {}", o.probe_dir.display()))?;
    std::fs::write(
        o.probe_dir.join("CMakeLists.txt"),
        render_probe_cmakelists(o),
    )?;
    std::fs::write(o.probe_dir.join("probe_main.cpp"), render_probe_main(o)?)?;
    if let Some(parent) = o.output_path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    let build_dir = o.probe_dir.join("build");
    run_step(
        Command::new("cmake")
            .arg("-S")
            .arg(&o.probe_dir)
            .arg("-B")
            .arg(&build_dir)
            .arg(format!(
                "-DCMAKE_PREFIX_PATH={}",
                o.nano_ros_workspace.display()
            ))
            .env("NROS_WORKSPACE", &o.nano_ros_workspace),
        "configure",
        o,
    )?;
    run_step(
        Command::new("cmake").arg("--build").arg(&build_dir),
        "build",
        o,
    )?;

    let bin = build_dir.join("nros_metadata_probe");
    run_step(
        // The selector is the whole reason the backend registers by name: the
        // probe binary also links the component's real backend, and with two
        // registered and no selector the executor refuses to open.
        Command::new(&bin).env("NROS_RMW", "metadata"),
        "run",
        o,
    )?;

    if !o.output_path.is_file() {
        bail!(
            "metadata probe for `{}::{}` exited 0 but wrote no sidecar at {}",
            o.package,
            o.component,
            o.output_path.display()
        );
    }
    Ok(())
}

fn run_step(cmd: &mut Command, step: &str, o: &CmakeProbeOptions) -> Result<()> {
    let out = cmd
        .output()
        .wrap_err_with(|| format!("spawn metadata probe {step} for `{}`", o.package))?;
    if !out.status.success() {
        // The component's own build errors are the useful part; surface them
        // rather than just the exit code.
        bail!(
            "metadata probe {step} failed for `{}::{}` (exit {}):\n{}\n{}",
            o.package,
            o.component,
            out.status.code().unwrap_or(-1),
            String::from_utf8_lossy(&out.stdout),
            String::from_utf8_lossy(&out.stderr),
        );
    }
    Ok(())
}

/// Path helper: the scratch dir for one component's probe.
pub fn probe_dir_for(root: &Path, package: &str, component: &str) -> PathBuf {
    root.join("metadata-probe-cmake")
        .join(format!("{package}__{component}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn opts() -> CmakeProbeOptions {
        CmakeProbeOptions {
            package: "talker_pkg".into(),
            component: "talker".into(),
            executable: "talker".into(),
            class: "talker_pkg::Talker".into(),
            header: "talker_pkg/Talker.hpp".into(),
            language: "cpp".into(),
            shape: "configure".into(),
            package_dir: PathBuf::from("/ws/src/talker_pkg"),
            nano_ros_workspace: PathBuf::from("/nano-ros"),
            output_path: PathBuf::from("/ws/src/talker_pkg/metadata/talker.json"),
            probe_dir: PathBuf::from("/scratch/probe"),
        }
    }

    /// The component is built by its OWN CMakeLists, not a reimplementation of
    /// it — that is what makes "it compiled here" mean "it compiles in an
    /// entry".
    #[test]
    fn cmakelists_adds_the_component_package_and_enables_metadata_mode() {
        let txt = render_probe_cmakelists(&opts());
        assert!(
            txt.contains("add_subdirectory(/ws/src/talker_pkg component_pkg)"),
            "{txt}"
        );
        assert!(txt.contains("find_package(nano_ros REQUIRED)"), "{txt}");
        assert!(
            txt.contains("set(NANO_ROS_CARGO_FEATURES \"metadata-mode\""),
            "the recording backend rides in on this feature:\n{txt}"
        );
        assert!(
            txt.contains("nano_ros_link_rmw(nros_metadata_probe)"),
            "{txt}"
        );
        // NanoRosCpp, not NanoRos: only the Cpp target carries the `nros/*.hpp`
        // include dirs, and the probe TU is C++ even for a C component.
        assert!(
            txt.contains("NanoRos::NanoRosCpp"),
            "probe needs the C++ include dirs:\n{txt}"
        );
    }

    /// The probe TU comes from the entry emitter, so the construction and
    /// `configure` call are the ones a real entry would make.
    #[test]
    fn probe_main_is_the_entry_setup_body_with_a_dump_tail() {
        let src = render_probe_main(&opts()).expect("emit");
        assert!(src.contains("#include \"talker_pkg/Talker.hpp\""), "{src}");
        assert!(src.contains(".configure("), "{src}");
        assert!(
            src.contains("nros_cpp_metadata_dump(\"talker_pkg\", \"talker\", \"talker\", \"cpp\""),
            "{src}"
        );
        assert!(
            src.contains("/ws/src/talker_pkg/metadata/talker.json"),
            "{src}"
        );
        assert!(
            !src.contains("::run_components("),
            "a probe never spins:\n{src}"
        );
    }

    /// A C component takes the C-ABI factory seam, not a C++ class construct —
    /// routed by `lang`, by the same emitter branch a real entry uses.
    #[test]
    fn c_components_route_through_the_c_abi_seam() {
        let mut o = opts();
        o.language = "c".into();
        o.package = "c_talker_pkg".into();
        o.class = "c_talker_pkg::Talker".into();
        let src = render_probe_main(&o).expect("emit");
        assert!(
            src.contains("__nros_c_component_c_talker_pkg_configure"),
            "{src}"
        );
    }

    #[test]
    fn probe_dirs_are_per_component() {
        let a = probe_dir_for(Path::new("/b"), "p", "one");
        let b = probe_dir_for(Path::new("/b"), "p", "two");
        assert_ne!(a, b);
    }
}
