//! phase-398 W3 — resolve a workspace's `<depend>` names.
//!
//! RFC-0062 (amended 2026-08-29) settled the ladder. A `<depend>` is resolved
//! by asking, in order:
//!
//! 1. **a workspace package** — build ORDER, not a prerequisite. Today's
//!    behaviour, unchanged.
//! 2. **a generated message package** — `nros sync` owns it. Not decoration:
//!    `std_msgs` is a legitimate prerequisite key in other ecosystems and a
//!    GENERATED crate here, so without this rung sync and the resolver both
//!    claim it and the winner is whichever ran last.
//! 3. **a `[prereq.*]` key** — its provider installs it, its `check` decides.
//! 4. **a package the ambient ROS install provides** — the ament index.
//!    `ament_cmake`, `rclcpp` and friends are neither ours nor prerequisites we
//!    could install; they come with ROS. Measured on this tree: 42 of the 92
//!    names that resolved nowhere are exactly these.
//! 5. **the pinned rosdep snapshot** — RFC-0099 D8 / phase-447 D3. A user
//!    writing `<depend>libopencv-dev</depend>` in their OWN package used to hit
//!    the bottom of this ladder, where a ROS user gets it from rosdep's
//!    community keys. That is a DATA gap, and the fix is data: a projection of
//!    ros/rosdistro's rosdep database onto the four managers `[prereq.*]`
//!    installs through, generated by `scripts/gen-rosdep-snapshot.py`, pinned to
//!    a rosdistro commit and committed. `provider = "system"` only, and every
//!    key from it is UNPROBED — see [`crate::orchestration::rosdep_snapshot`]
//!    for why this is not the rosdep RFC-0062's amendment rejected.
//! 6. **otherwise UNKNOWN** — and that is an error, because the alternative is
//!    the silence this whole RFC exists to delete.
//!
//! ## Why the silence had to go
//!
//! A name that matched nothing was dropped without a word: `provider_scan`
//! says so in its own doc ("Includes names that are not workspace packages
//! (`std_msgs`); ordering ignores those rather than failing"). The first run of
//! this resolver over the tree found three `<exec_depend>` entries naming
//! packages that DO NOT EXIST — `reliable_talker_pkg`, `qos_listener_pkg`,
//! `param_talker_pkg`, stale since a rename — in workspaces that build green.
//! Nothing had ever looked.
//!
//! ## Scope
//!
//! A WORKSPACE, not the repository. `external/` and `third-party/` are
//! gitignored vendored checkouts of other people's code; 41 of the 50
//! genuinely-unresolved names in a repo-wide sweep were theirs, and none of
//! them is ours to declare.

use std::{
    collections::{BTreeMap, BTreeSet},
    path::Path,
};

/// How one `<depend>` name resolved.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Resolution {
    /// A package in this workspace — a build-order edge.
    WorkspacePackage,
    /// A message package `nros sync` generates.
    GeneratedMessage,
    /// A `[prereq.*]` key.
    Prereq,
    /// Provided by the ambient ROS install (the ament index).
    RosPackage,
    /// The declaring package's OWN buildtool, named by its `<build_type>`.
    ///
    /// `<buildtool_depend>ament_cmake</buildtool_depend>` on a package whose
    /// build type IS `ament_cmake` is a tautology: if that builder is building
    /// it, the buildtool is present. rosdep wants the declaration anyway, so
    /// the tree should carry it — but resolving it must not require an ambient
    /// ROS, or an embedded-only contributor with no `AMENT_PREFIX_PATH` gets a
    /// hard error for a dependency that is satisfied by definition.
    SelfBuildtool,
    /// A key in the pinned, vendored rosdep snapshot — RFC-0099 D8.
    ///
    /// The LAST rung before UNKNOWN, deliberately. Everything above it is a
    /// provider this tree chose and can probe; this one is a community database
    /// we vendored, with no `check` and therefore no way to say whether the
    /// package is present. It resolves the name — which is the whole gap it
    /// exists to close — and every consumer must say where the answer came from
    /// and that it is unprobed.
    RosdepSnapshot,
    /// Nothing claims it.
    Unknown,
}

impl Resolution {
    /// True for a resolution whose presence on the host was never tested.
    ///
    /// One predicate rather than each consumer matching the variant, so
    /// "which rungs are unprobed" has a single answer to change when a rung is
    /// added.
    #[must_use]
    pub fn is_unprobed(self) -> bool {
        matches!(self, Self::RosdepSnapshot)
    }
}

/// One unresolved name and the files that declare it.
#[derive(Clone, Debug)]
pub struct Unresolved {
    pub name: String,
    pub declared_by: Vec<String>,
}

/// The packages the ambient ROS install provides, from the ament index.
///
/// `AMENT_PREFIX_PATH` when set, else nothing — deliberately NOT a guess at
/// `/opt/ros/<distro>`, because a resolver that silently reaches a ROS the
/// caller did not select is how one tree resolves two ways (the reasoning that
/// removed the rosdep backend).
#[must_use]
pub fn ros_packages() -> BTreeSet<String> {
    let mut out = BTreeSet::new();
    let Some(paths) = std::env::var_os("AMENT_PREFIX_PATH") else {
        return out;
    };
    for prefix in std::env::split_paths(&paths) {
        let dir = prefix.join("share/ament_index/resource_index/packages");
        if let Ok(rd) = std::fs::read_dir(dir) {
            out.extend(
                rd.flatten()
                    .map(|e| e.file_name().to_string_lossy().into_owned()),
            );
        }
    }
    out
}

/// Classify every `<depend>` name a workspace declares.
///
/// `workspace_packages` and `generated` are the first two rungs;
/// `prereq_keys` the third; `ros` the fourth; `self_buildtools` the fifth; and
/// `rosdep` the pinned snapshot, last before UNKNOWN.
#[must_use]
pub fn classify(
    name: &str,
    workspace_packages: &BTreeSet<String>,
    generated: &BTreeSet<String>,
    prereq_keys: &BTreeSet<String>,
    ros: &BTreeSet<String>,
    self_buildtools: &BTreeSet<String>,
    rosdep: &BTreeSet<String>,
) -> Resolution {
    if workspace_packages.contains(name) {
        Resolution::WorkspacePackage
    } else if generated.contains(name) {
        Resolution::GeneratedMessage
    } else if prereq_keys.contains(name) {
        Resolution::Prereq
    } else if ros.contains(name) {
        Resolution::RosPackage
    } else if self_buildtools.contains(name) {
        // LAST, deliberately. An ambient ROS or a `[prereq.*]` key is a real
        // provider and should win; this rung exists so the absence of both is
        // not an error for a dependency the builder satisfies by definition.
        Resolution::SelfBuildtool
    } else if rosdep.contains(name) {
        // BELOW every rung above, including `SelfBuildtool`. The snapshot has
        // an apt name for `cmake` and `ament_cmake`, and answering with it
        // would replace a truthful "the builder supplies this" — and a probed
        // `[prereq.*]` row — with an unprobed guess from a vendored database.
        Resolution::RosdepSnapshot
    } else {
        Resolution::Unknown
    }
}

/// Load the pinned rosdep snapshot, but only if the ladder above it left work.
///
/// The snapshot is 150 KB of TOML and the ladder above resolves essentially
/// everything in this tree, so a load on every `nros build` would be pure cost.
/// Consulting it ONLY for names that are otherwise UNKNOWN is also the
/// structural statement of what a fallback rung is: it cannot change an answer
/// any higher rung gave, because it is never asked.
///
/// Returns `None` when nothing is unresolved, when there is no nano-ros root,
/// or when the file is absent — an out-of-tree consumer with no checkout keeps
/// today's behaviour rather than gaining a hard error about a missing snapshot.
/// A file that IS present and malformed is an error: a broken pin must not
/// degrade to silence.
pub fn rosdep_fallback(
    declared: &BTreeMap<String, Vec<String>>,
    workspace_packages: &BTreeSet<String>,
    generated: &BTreeSet<String>,
    prereq_keys: &BTreeSet<String>,
    ros: &BTreeSet<String>,
    self_buildtools: &BTreeSet<String>,
    nano_ros_root: Option<&Path>,
) -> eyre::Result<Option<crate::orchestration::rosdep_snapshot::RosdepSnapshot>> {
    let none = BTreeSet::new();
    let any_unknown = declared.keys().any(|n| {
        classify(
            n,
            workspace_packages,
            generated,
            prereq_keys,
            ros,
            self_buildtools,
            &none,
        ) == Resolution::Unknown
    });
    if !any_unknown {
        return Ok(None);
    }
    let Some(path) = nano_ros_root.map(crate::orchestration::rosdep_snapshot::default_path) else {
        return Ok(None);
    };
    if !path.is_file() {
        return Ok(None);
    }
    Ok(Some(
        crate::orchestration::rosdep_snapshot::RosdepSnapshot::load(&path)?,
    ))
}

/// Every name a workspace's `package.xml` files declare, with where.
///
/// Reads the files directly rather than taking `provider_scan`'s `depends`,
/// because this needs the DECLARING FILE for the diagnostic — "which
/// package.xml names this?" is the first question anyone asks — and that scan
/// keeps only the set.
#[must_use]
pub fn declared_depends(ws_root: &Path) -> BTreeMap<String, Vec<String>> {
    let mut out: BTreeMap<String, Vec<String>> = BTreeMap::new();
    let mut stack = vec![ws_root.to_path_buf()];
    while let Some(dir) = stack.pop() {
        let Ok(rd) = std::fs::read_dir(&dir) else {
            continue;
        };
        for e in rd.flatten() {
            let p = e.path();
            let name = e.file_name().to_string_lossy().into_owned();
            if p.is_dir() {
                if !is_pruned_dir(&name, &p) {
                    stack.push(p);
                }
            } else if name == "package.xml"
                && let Ok(text) = std::fs::read_to_string(&p)
            {
                for dep in depend_names(&text) {
                    out.entry(dep).or_default().push(p.display().to_string());
                }
            }
        }
    }
    out
}

/// Directories a `package.xml` scan must not descend into.
///
/// Issue 1318 — this predicate used to be written out twice, once in each
/// walk below, and both copies pruned `build` and `target-*` but not
/// `build-*`. The two OTHER `package.xml` walkers in this CLI
/// ([`crate::pkg_index::build_pkg_index`] and
/// [`crate::builder::discover::cargo_packages_by_walk`]) both prune the
/// `build-` prefix, so a workspace that keeps its out-of-source build trees
/// beside `src/` was walked in full by this scan and by no other.
///
/// Measured on Autoware Safety Island, whose tree had accumulated 85
/// `build-*` directories: one `nros image-facts` opened 362,782 directories,
/// 98.7% of every open it made, to read a single file. On btrfs over a
/// 7200 RPM disk that was 242 MB of physical reads for 27 KB of answers and
/// minutes in uninterruptible sleep.
///
/// The ignore markers are the ament convention the sibling walkers already
/// honour; a scan that skipped them here would disagree with the index about
/// what is in the workspace.
fn is_pruned_dir(name: &str, path: &Path) -> bool {
    if matches!(
        name,
        "build"
            | "target"
            | ".git"
            | ".cargo"
            | "external"
            | "third-party"
            | "node_modules"
            | "__pycache__"
    ) {
        return true;
    }
    if name.starts_with("build-") || name.starts_with("target-") {
        return true;
    }
    ["COLCON_IGNORE", "AMENT_IGNORE", "NROS_IGNORE", ".nros-ignore"]
        .iter()
        .any(|marker| path.join(marker).exists())
}

/// `<depend>`, `<build_depend>`, `<exec_depend>`, `<test_depend>` … all of them.
///
/// A tiny scanner rather than an XML parser: the tree has no namespaces or
/// entities in these files, and adding a dependency to read four tag names
/// would be the larger change.
#[must_use]
pub fn depend_names(xml: &str) -> Vec<String> {
    let mut out = Vec::new();
    for (i, _) in xml.match_indices("depend>") {
        // Only an OPENING tag: `</exec_depend>` also contains "depend>".
        let open = xml[..i].rfind('<');
        let Some(open) = open else { continue };
        if xml[open..].starts_with("</") {
            continue;
        }
        let Some(rest) = xml.get(i + "depend>".len()..) else {
            continue;
        };
        let Some(end) = rest.find('<') else { continue };
        let value = rest[..end].trim();
        if !value.is_empty() {
            out.push(value.to_string());
        }
    }
    out.sort();
    out.dedup();
    out
}

/// `<build_type>` -> the buildtool package that build type implies.
///
/// Measured on this tree: 345 of 367 packages declare a `<build_type>` and NOT
/// the matching `<buildtool_depend>`, and the only buildtool declarations that
/// are NOT inferable this way are `rosidl_default_generators` (10 message
/// packages) and `cargo-ros2` (1). So the mapping is nearly total, and what it
/// cannot infer is exactly what a human should still write by hand.
///
/// The nano-ros build types map to `nros`: they are served by this repo's own
/// builders, so there is no upstream buildtool package to name. `ament_cargo`
/// and `cargo-ros2` are served by the in-tree `packages/cli/colcon-cargo-ros2`
/// colcon extension — also not apt-installable, which is why inventing
/// `[prereq.*]` rows with `apt = ["ros-humble-..."]` for them would be fiction.
#[must_use]
pub fn buildtool_for_build_type(build_type: &str) -> Option<&'static str> {
    Some(match build_type {
        "ament_cmake" => "ament_cmake",
        "ament_cargo" => "ament_cargo",
        "cmake" => "cmake",
        "cargo" => "cargo",
        "ament_nros" | "nros_entry" | "nros_cargo" | "nros_bringup" => "nros",
        _ => return None,
    })
}

/// The `<build_type>` a `package.xml` exports, if it declares one.
#[must_use]
pub fn build_type(xml: &str) -> Option<String> {
    let i = xml.find("<build_type>")? + "<build_type>".len();
    let rest = xml.get(i..)?;
    let end = rest.find("</build_type>")?;
    Some(rest[..end].trim().to_string())
}

/// Buildtool names that every declaring package satisfies by its own build type.
///
/// Deliberately conservative: a name qualifies only if EVERY `package.xml` that
/// declares it has a build type implying it. One package declaring
/// `ament_cmake` while being built some other way keeps the name on the normal
/// ladder, where an ambient ROS or a `[prereq.*]` key still has to claim it.
#[must_use]
pub fn self_satisfied_buildtools(ws_root: &Path) -> BTreeSet<String> {
    let mut implied: BTreeMap<String, (usize, usize)> = BTreeMap::new();
    for (_path, text) in package_xml_files(ws_root) {
        let own = build_type(&text).and_then(|bt| buildtool_for_build_type(&bt));
        for dep in depend_names(&text) {
            if buildtool_for_build_type(&dep).is_some() || dep == "nros" {
                let e = implied.entry(dep.clone()).or_insert((0, 0));
                e.1 += 1;
                if own == Some(dep.as_str()) {
                    e.0 += 1;
                }
            }
        }
    }
    implied
        .into_iter()
        .filter(|(_n, (ok, total))| *total > 0 && ok == total)
        .map(|(n, _)| n)
        .collect()
}

/// Every `package.xml` under a workspace, as (path, text).
fn package_xml_files(ws_root: &Path) -> Vec<(std::path::PathBuf, String)> {
    let mut out = Vec::new();
    let mut stack = vec![ws_root.to_path_buf()];
    while let Some(dir) = stack.pop() {
        let Ok(rd) = std::fs::read_dir(&dir) else {
            continue;
        };
        for e in rd.flatten() {
            let p = e.path();
            let name = e.file_name().to_string_lossy().into_owned();
            if p.is_dir() {
                if !is_pruned_dir(&name, &p) {
                    stack.push(p);
                }
            } else if name == "package.xml"
                && let Ok(text) = std::fs::read_to_string(&p)
            {
                out.push((p, text));
            }
        }
    }
    out
}

/// The name of a `package.xml`'s own package.
#[must_use]
pub fn package_name(xml: &str) -> Option<String> {
    let i = xml.find("<name>")? + "<name>".len();
    let rest = xml.get(i..)?;
    let end = rest.find("</name>")?;
    Some(rest[..end].trim().to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Issue 1318 — an out-of-source build tree beside `src/` is not part of
    /// the workspace, and a `package.xml` scan that walks into one reads a
    /// copy of every package it already found.
    ///
    /// `build-*` is the shape `west build -d build-<name>` and
    /// `cmake -B build-<name>` leave behind, and a tree accumulates one per
    /// experiment. The scan pruned `build` and `target-*` but not `build-*`,
    /// so every one of them was walked in full.
    #[test]
    fn a_build_tree_beside_src_is_not_walked() {
        let tmp = tempfile::tempdir().unwrap();
        let ws = tmp.path();

        std::fs::create_dir_all(ws.join("src/real_pkg")).unwrap();
        std::fs::write(
            ws.join("src/real_pkg/package.xml"),
            "<package><name>real_pkg</name><depend>rclcpp</depend></package>",
        )
        .unwrap();

        // What an out-of-source build leaves behind: a STALE copy of the same
        // package.xml, deep enough that walking it is the expensive part.
        let stale = ws.join("build-zephyr/real_pkg/ament_cmake_core/stamps");
        std::fs::create_dir_all(&stale).unwrap();
        std::fs::write(
            stale.join("package.xml"),
            "<package><name>real_pkg</name><depend>ghost_dep</depend></package>",
        )
        .unwrap();

        // And the two spellings that were already pruned, to keep them pruned.
        for pruned in ["build", "target-thumbv7em"] {
            let d = ws.join(pruned).join("nested");
            std::fs::create_dir_all(&d).unwrap();
            std::fs::write(
                d.join("package.xml"),
                "<package><name>real_pkg</name><depend>ghost_dep</depend></package>",
            )
            .unwrap();
        }

        let found = package_xml_files(ws);
        assert_eq!(
            found.len(),
            1,
            "only the package under src/ is in the workspace, found: {:?}",
            found.iter().map(|(p, _)| p).collect::<Vec<_>>()
        );

        let deps = declared_depends(ws);
        assert!(deps.contains_key("rclcpp"));
        assert!(
            !deps.contains_key("ghost_dep"),
            "a dependency that exists only inside a build tree is not declared \
             by this workspace"
        );
    }

    /// An ament ignore marker is honoured here the same way the pkg-index and
    /// the cargo walk honour it, so the three agree about the workspace.
    #[test]
    fn an_ignore_marker_prunes_a_directory() {
        let tmp = tempfile::tempdir().unwrap();
        let ws = tmp.path();

        let ignored = ws.join("vendor_drop/some_pkg");
        std::fs::create_dir_all(&ignored).unwrap();
        std::fs::write(ws.join("vendor_drop/COLCON_IGNORE"), "").unwrap();
        std::fs::write(
            ignored.join("package.xml"),
            "<package><name>vendored</name></package>",
        )
        .unwrap();

        assert!(package_xml_files(ws).is_empty());
    }

    fn set(v: &[&str]) -> BTreeSet<String> {
        v.iter().map(|s| (*s).to_string()).collect()
    }

    /// Every rung, in order, and the one that matters: an unmatched name is
    /// UNKNOWN rather than silently dropped.
    #[test]
    fn the_ladder_resolves_in_order() {
        let ws = set(&["talker_pkg"]);
        let msgs = set(&["std_msgs"]);
        let keys = set(&["libslirp"]);
        let ros = set(&["ament_cmake"]);
        let bt = BTreeSet::new();
        let rd = set(&["libopencv-dev"]);
        let c = |n: &str| classify(n, &ws, &msgs, &keys, &ros, &bt, &rd);

        assert_eq!(c("talker_pkg"), Resolution::WorkspacePackage);
        assert_eq!(c("std_msgs"), Resolution::GeneratedMessage);
        assert_eq!(c("libslirp"), Resolution::Prereq);
        assert_eq!(c("ament_cmake"), Resolution::RosPackage);
        assert_eq!(c("libopencv-dev"), Resolution::RosdepSnapshot);
        assert_eq!(c("nros-no-such-thing"), Resolution::Unknown);
    }

    /// The generated-message rung sits ABOVE the prereq rung on purpose.
    /// `std_msgs` is a legitimate prerequisite key elsewhere and a generated
    /// crate here; if the prereq rung won, `nros sync` and the resolver would
    /// both claim it and the winner would be whichever ran last.
    #[test]
    fn a_generated_message_outranks_a_prereq_key_of_the_same_name() {
        let both = set(&["std_msgs"]);
        assert_eq!(
            classify(
                "std_msgs",
                &BTreeSet::new(),
                &both,
                &both,
                &BTreeSet::new(),
                &BTreeSet::new(),
                &BTreeSet::new()
            ),
            Resolution::GeneratedMessage,
        );
    }

    /// A workspace package outranks everything — it is a build-order edge, not
    /// something to install.
    #[test]
    fn a_workspace_package_outranks_every_other_rung() {
        let all = set(&["talker_pkg"]);
        assert_eq!(
            classify("talker_pkg", &all, &all, &all, &all, &all, &all),
            Resolution::WorkspacePackage,
        );
    }

    /// phase-422 W8 — a key's ROLE decides whether a package.xml may name it.
    /// `infra` (emulators, cross toolchains, probes) RESOLVES on the prereq
    /// rung, so the ladder alone cannot tell the category error from a
    /// legitimate dependency; the caller has to consult the role. This pins the
    /// rung's part of that contract: an infra key still classifies as `Prereq`,
    /// which is what makes the refusal a SEPARATE decision with its own remedy
    /// ("declare the deploy target") rather than an "unresolved" error whose
    /// advice would be to add an index entry — the wrong fix.
    #[test]
    fn an_infra_key_still_resolves_on_the_prereq_rung() {
        let empty = BTreeSet::new();
        let keys = set(&["qemu-system-arm"]);
        assert_eq!(
            classify(
                "qemu-system-arm",
                &empty,
                &empty,
                &keys,
                &empty,
                &empty,
                &empty
            ),
            Resolution::Prereq,
        );
    }

    /// The rung this exists for: no ambient ROS, and a package declaring the
    /// buildtool its own `<build_type>` implies still resolves.
    ///
    /// Without it, adding the `<buildtool_depend>` rosdep expects would hard-fail
    /// `nros build` on every host with no `AMENT_PREFIX_PATH` — which is every
    /// embedded-only contributor.
    #[test]
    fn a_packages_own_buildtool_resolves_without_ros() {
        let empty = BTreeSet::new();
        let bt = set(&["ament_cmake"]);
        assert_eq!(
            classify("ament_cmake", &empty, &empty, &empty, &empty, &bt, &empty),
            Resolution::SelfBuildtool,
        );
        // and it is still UNKNOWN when nothing implies it
        assert_eq!(
            classify(
                "ament_cmake",
                &empty,
                &empty,
                &empty,
                &empty,
                &empty,
                &empty
            ),
            Resolution::Unknown,
        );
    }

    /// A real provider outranks the tautology: if ROS supplies `ament_cmake`,
    /// say so, because that is the truthful answer and the one a user can act on.
    #[test]
    fn an_ambient_ros_outranks_the_self_buildtool_rung() {
        let s = set(&["ament_cmake"]);
        assert_eq!(
            classify(
                "ament_cmake",
                &BTreeSet::new(),
                &BTreeSet::new(),
                &BTreeSet::new(),
                &s,
                &s,
                &BTreeSet::new()
            ),
            Resolution::RosPackage,
        );
    }

    /// The mapping is per build type, and nano-ros's own builders resolve to
    /// `nros` — they have no upstream buildtool package to name.
    #[test]
    fn build_type_implies_its_buildtool() {
        assert_eq!(buildtool_for_build_type("ament_cmake"), Some("ament_cmake"));
        assert_eq!(buildtool_for_build_type("cmake"), Some("cmake"));
        assert_eq!(buildtool_for_build_type("nros_entry"), Some("nros"));
        assert_eq!(buildtool_for_build_type("ament_cargo"), Some("ament_cargo"));
        // Not every build type implies one; an unknown type must not be guessed.
        assert_eq!(buildtool_for_build_type("colcon_lunar_module"), None);
    }

    #[test]
    fn build_type_is_read_from_the_export_block() {
        let xml = "<package><export><build_type>ament_cmake</build_type></export></package>";
        assert_eq!(build_type(xml).as_deref(), Some("ament_cmake"));
        assert_eq!(build_type("<package/>"), None);
    }

    /// All four depend spellings, and the closing tag must not be mistaken for
    /// an opening one — `</exec_depend>` also ends in `depend>`.
    #[test]
    fn every_depend_spelling_is_read_and_closing_tags_are_not() {
        let xml = "<package>\
                   <name>p</name>\
                   <depend>a</depend>\
                   <build_depend>b</build_depend>\
                   <exec_depend>c</exec_depend>\
                   <test_depend>d</test_depend>\
                   </package>";
        assert_eq!(depend_names(xml), vec!["a", "b", "c", "d"]);
        assert_eq!(package_name(xml).as_deref(), Some("p"));
    }

    /// Whitespace and duplicates: a name written twice is one dependency.
    #[test]
    fn names_are_trimmed_and_deduped() {
        let xml = "<depend> a </depend><exec_depend>a</exec_depend>";
        assert_eq!(depend_names(xml), vec!["a"]);
    }

    /// The rung this item exists for: a name no rung above claims, which the
    /// pinned snapshot knows, resolves instead of erroring.
    ///
    /// `libopencv-dev` is the acceptance case from RFC-0099 D8 — a user's own
    /// package naming a system library that is not a `[prereq.*]` key.
    #[test]
    fn a_snapshot_key_resolves_where_nothing_above_claims_it() {
        let empty = BTreeSet::new();
        let rd = set(&["libopencv-dev"]);
        assert_eq!(
            classify("libopencv-dev", &empty, &empty, &empty, &empty, &empty, &rd),
            Resolution::RosdepSnapshot,
        );
        assert!(Resolution::RosdepSnapshot.is_unprobed());
    }

    /// Every rung ABOVE the snapshot wins, and this is the half that matters:
    /// 15 of the 46 `[prereq.*]` keys (`cmake`, `curl`, `clang`, `openocd`, …)
    /// are ALSO snapshot keys, measured on rosdistro ba7d998b. Those rows carry
    /// a `check`; the snapshot's do not. If the snapshot won, adding a
    /// fallback DATABASE would have silently removed the probes from a sixth of
    /// the authored index — the exact objection RFC-0062's amendment raised.
    #[test]
    fn a_probed_prereq_key_outranks_the_same_name_in_the_snapshot() {
        let empty = BTreeSet::new();
        let both = set(&["cmake"]);
        assert_eq!(
            classify("cmake", &empty, &empty, &both, &empty, &empty, &both),
            Resolution::Prereq,
        );
        assert!(!Resolution::Prereq.is_unprobed());
    }

    /// … and the same for the two rungs between: an ambient ROS package and a
    /// package's own buildtool are both truthful answers about a provider this
    /// tree chose, so neither may be replaced by a vendored guess.
    #[test]
    fn the_snapshot_is_the_last_rung_before_unknown() {
        let empty = BTreeSet::new();
        let s = set(&["ament_cmake"]);
        assert_eq!(
            classify("ament_cmake", &empty, &empty, &empty, &s, &empty, &s),
            Resolution::RosPackage,
        );
        assert_eq!(
            classify("ament_cmake", &empty, &empty, &empty, &empty, &s, &s),
            Resolution::SelfBuildtool,
        );
    }

    /// The fallback is LAZY, and this proves it by consequence rather than by
    /// inspection: the snapshot on disk is MALFORMED, so a load cannot be
    /// silent. With every name resolved above, `rosdep_fallback` returns
    /// `None` — it never opened the file. With one name unresolved, the same
    /// call fails, naming the file.
    ///
    /// A broken pin must not degrade to silence, which is why the second half
    /// asserts an error rather than `None`.
    #[test]
    fn the_snapshot_is_read_only_when_a_name_is_otherwise_unresolved() {
        let dir = std::env::temp_dir().join(format!(
            "nros-rosdep-lazy-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_nanos())
                .unwrap_or_default()
        ));
        std::fs::create_dir_all(&dir).expect("temp dir");
        std::fs::write(
            crate::orchestration::rosdep_snapshot::default_path(&dir),
            "this is not { toml",
        )
        .expect("write");

        let ws = set(&["talker_pkg"]);
        let empty = BTreeSet::new();
        let mut declared: BTreeMap<String, Vec<String>> = BTreeMap::new();
        declared.insert("talker_pkg".into(), vec!["a/package.xml".into()]);

        let resolved = rosdep_fallback(&declared, &ws, &empty, &empty, &empty, &empty, Some(&dir));
        assert!(
            matches!(resolved, Ok(None)),
            "a fully-resolved workspace must never open the snapshot",
        );

        declared.insert("libopencv-dev".into(), vec!["a/package.xml".into()]);
        let err = rosdep_fallback(&declared, &ws, &empty, &empty, &empty, &empty, Some(&dir))
            .expect_err("a malformed snapshot is an error, never a silent skip");
        assert!(
            format!("{err:#}").contains("nros-rosdep-snapshot.toml"),
            "{err:#}"
        );

        // An out-of-tree consumer with no nano-ros checkout keeps today's
        // behaviour rather than gaining an error about a file it cannot have.
        assert!(matches!(
            rosdep_fallback(&declared, &ws, &empty, &empty, &empty, &empty, None),
            Ok(None)
        ));

        let _ = std::fs::remove_dir_all(&dir);
    }

    /// End to end on the SHIPPED data — the committed snapshot against the
    /// committed index, which is the pair a user actually gets.
    ///
    /// This is the acceptance criterion, and it is only meaningful over both
    /// real files: the overlap it asserts about (15 keys, measured) exists
    /// because rosdep and this tree happen to name the same tools, and a
    /// hand-written fixture would be me choosing the collision rather than
    /// finding it.
    #[test]
    fn the_shipped_snapshot_closes_the_gap_without_shadowing_the_index() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            // packages/cli/nros-cli-core -> cli -> packages -> repo root
            .ancestors()
            .nth(3)
            .expect("repo root")
            .to_path_buf();
        let index =
            crate::orchestration::sdk_index::SdkIndex::load(&root.join("nros-sdk-index.toml"))
                .expect("the shipped index must load");
        let prereq_map = index.prereqs();
        let prereq_keys: BTreeSet<String> = prereq_map.keys().cloned().collect();
        let snap = crate::orchestration::rosdep_snapshot::RosdepSnapshot::load(
            &crate::orchestration::rosdep_snapshot::default_path(&root),
        )
        .expect("the shipped snapshot must load");
        let rosdep = snap.keys();
        let empty = BTreeSet::new();

        // The gap closes.
        assert_eq!(
            classify(
                "libopencv-dev",
                &empty,
                &empty,
                &prereq_keys,
                &empty,
                &empty,
                &rosdep
            ),
            Resolution::RosdepSnapshot,
        );

        // And it closes without taking anything from the index. Every key the
        // two share must still answer `Prereq` — those are the rows carrying a
        // `check`, and losing them to an unprobed database is precisely the
        // failure RFC-0062's amendment predicted.
        let shared: Vec<&String> = prereq_keys.intersection(&rosdep).collect();
        assert!(
            !shared.is_empty(),
            "no shared keys — this assertion would be vacuous"
        );
        for name in &shared {
            assert_eq!(
                classify(name, &empty, &empty, &prereq_keys, &empty, &empty, &rosdep),
                Resolution::Prereq,
                "{name} lost its probed index row to the snapshot",
            );
        }
    }

    /// Without `AMENT_PREFIX_PATH` the ROS rung answers NOTHING rather than
    /// guessing `/opt/ros/<distro>`. A resolver that silently reaches a ROS the
    /// caller did not select is how one tree resolves two ways — the reasoning
    /// that removed the rosdep backend.
    #[test]
    fn the_ros_rung_does_not_guess_a_prefix() {
        let saved = std::env::var_os("AMENT_PREFIX_PATH");
        // SAFETY: single-threaded test; restored below.
        unsafe { std::env::remove_var("AMENT_PREFIX_PATH") };
        let empty = ros_packages().is_empty();
        if let Some(v) = saved {
            unsafe { std::env::set_var("AMENT_PREFIX_PATH", v) };
        }
        assert!(empty, "no AMENT_PREFIX_PATH ⇒ no ROS packages claimed");
    }
}
