meta:
  version: 1
  inputs:
  - path: launch/system.launch.xml
    sha256: 263292326cd1f0847e622d705fefdc259c519b5f4d32240960e7223dd4156c25
  - path: system.toml
    sha256: 82259daf24c961f5c13ed4394a88ce39a3d6f44ecb25329a91a1c19a6712fd53
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
structure:
  scopes:
    system.launch.xml:
      file: system.launch.xml
  nodes:
    /ctrl_node:
      scope: system.launch.xml
      pkg: ctrl_pkg
      exec: ctrl
      node_name: ctrl_node
    /telem_node:
      scope: system.launch.xml
      pkg: telem_pkg
      exec: telem
      node_name: telem_node
execution:
  deploy:
    /ctrl_node:
      domain: 0
      rmw: cyclonedds
      extra:
        deploy_name: fvp
        kind: zephyr
        target: fvp_baser_aemv8r_smp
    /telem_node:
      domain: 0
      rmw: cyclonedds
      extra:
        deploy_name: fvp
        kind: zephyr
        target: fvp_baser_aemv8r_smp
  tiers:
    high:
      spin_period_us: 10000
      posix:
        priority: 80
      zephyr:
        priority: 5
      nuttx:
        priority: 110
    low:
      spin_period_us: 100000
      posix:
        priority: 10
      zephyr:
        priority: 10
      nuttx:
        priority: 100
  bindings:
    /ctrl_node/ctrl: high
    /telem_node/telem: low
