//! Build script for zpico-platform-shim.
//!
//! Probes the sizes of zenoh-pico's `_z_sys_net_socket_t` and
//! `_z_sys_net_endpoint_t` from the C headers using the cross-compiler,
//! then generates Rust constants for the opaque wrapper types.

use std::{
    env,
    path::{Path, PathBuf},
    process::Command,
};

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let zpico_sys_dir = manifest_dir.parent().unwrap().join("zpico-sys");
    let zenoh_pico_include = zpico_sys_dir.join("zenoh-pico/include");

    // Phase 87.10: never silently fall back to default sizes when the
    // zenoh-pico headers are present. The previous behaviour ("defaults
    // first, override if probe succeeds") meant a failed probe shipped
    // a guess for `_z_sys_net_socket_t` size — which is passed by value
    // through the shim's FFI. Wrong size = silent ABI corruption.
    //
    // Two valid paths:
    //   * Headers absent (workspace `cargo check` without RMW features,
    //     pre-`just setup` builds, etc.): use placeholder defaults.
    //     The shim's FFI is feature-gated and never called in this mode,
    //     so the placeholders are dead weight, not an ABI hazard.
    //   * Headers present: the probe MUST succeed. If it doesn't, hard-
    //     fail with a clear error message instead of writing a stale
    //     fallback into `platform_net_sizes.rs`.
    let (socket_size, endpoint_size) = if zenoh_pico_include.exists() {
        match probe_sizes(&zpico_sys_dir, &zenoh_pico_include, &out_dir) {
            Some(sizes) => sizes,
            None => panic!(
                "zpico-platform-shim: size_probe failed for zenoh-pico headers at {} \
                 — check that the cross-compiler can find the platform SDK headers \
                 (FREERTOS_DIR / NUTTX_DIR / THREADX_DIR / NETX_DIR + lwIP + libc). \
                 Falling back to default sizes would silently corrupt the \
                 `_z_sys_net_socket_t` pass-by-value ABI on platforms where the \
                 real size differs from the (16, 8) guess; build aborted.",
                zenoh_pico_include.display(),
            ),
        }
    } else {
        // No headers → no FFI consumer. Placeholder values for `cargo
        // check`-only flows; never reach runtime.
        (16usize, 8usize)
    };

    let contents = format!(
        "// Auto-generated by zpico-platform-shim/build.rs\n\
         // Sizes derived from zenoh-pico C headers via size probe.\n\
         pub const NET_SOCKET_SIZE: usize = {socket_size};\n\
         pub const NET_ENDPOINT_SIZE: usize = {endpoint_size};\n",
    );
    std::fs::write(out_dir.join("platform_net_sizes.rs"), contents).unwrap();

    println!("cargo:rerun-if-changed=build.rs");
    println!(
        "cargo:rerun-if-changed={}",
        zpico_sys_dir.join("c/size_probe.c").display()
    );
}

#[derive(Copy, Clone, PartialEq, Eq)]
enum ProbePlatform {
    Freertos,
    Nuttx,
    Threadx,
    BareMetal,
    Linux,
    Macos,
    Unknown,
}

fn probe_sizes(
    zpico_sys_dir: &Path,
    zenoh_include: &Path,
    out_dir: &Path,
) -> Option<(usize, usize)> {
    let probe_c = zpico_sys_dir.join("c/size_probe.c");
    if !probe_c.exists() {
        return None;
    }

    let target = env::var("TARGET").unwrap_or_default();

    // Zephyr builds set ZEPHYR_BASE. The probe can't easily include Zephyr
    // headers (they depend on the generated zephyr/kconfig.h and the full
    // west build context), so we short-circuit with hardcoded sizes that
    // match `zenoh-pico/include/zenoh-pico/system/platform/zephyr.h`:
    //
    //   _z_sys_net_socket_t   = union { int _fd; const struct device *_serial; }
    //   _z_sys_net_endpoint_t = union { struct addrinfo *_iptcp; }
    //
    // Both collapse to pointer size on the target (8 bytes on 64-bit,
    // 4 bytes on 32-bit). Skipping the probe is safe IF AND ONLY IF the
    // zenoh-pico Zephyr port keeps these layouts. If a future zenoh-pico
    // version adds a non-pointer field to either union, the
    // pass-by-value ABI for `_z_sys_net_socket_t` would silently corrupt.
    //
    // Audit hook (Phase 87.12 follow-up): if `zenoh-pico/include/zenoh-pico/
    // system/platform/zephyr.h` is touched, re-verify these layouts. A
    // proper Zephyr-aware probe would require running the build inside
    // the west workspace; not currently in scope.
    if env::var("ZEPHYR_BASE").is_ok() {
        let ptr_size = if env::var("CARGO_CFG_TARGET_POINTER_WIDTH").ok().as_deref() == Some("32") {
            4
        } else {
            8
        };
        return Some((ptr_size, ptr_size));
    }

    // Phase 89.5: the `network-smoltcp-bridge` feature is activated by
    // zpico-sys only for the `bare-metal` platform feature, so when it's
    // present we know this build targets smoltcp — short-circuit the
    // target-triple heuristic. Without this check, a thumbv7m bare-metal
    // build with `.envrc` exporting FREERTOS_DIR would silently fall into
    // the FreeRTOS branch (4-byte socket / 4-byte endpoint sizes from the
    // lwIP headers) instead of the bare-metal branch (2-byte socket /
    // 6-byte endpoint). The resulting pass-by-value ABI mismatch truncates
    // the TCP port and sends SYNs to an arbitrary port on the slirp
    // gateway, giving RST responses and `Transport(ConnectionFailed)`.
    let uses_smoltcp_bridge = env::var("CARGO_FEATURE_NETWORK_SMOLTCP_BRIDGE").is_ok();

    // Target triple determines the platform branch FIRST; env vars
    // are consulted only as sources of SDK paths. Using env vars as
    // the branching key was unreliable because `.envrc` exports
    // `FREERTOS_DIR` / `NUTTX_DIR` / `THREADX_DIR` globally whenever
    // any of those SDKs is set up — so a build for `riscv64gc-…-elf`
    // (ThreadX) would silently take the FREERTOS branch and the
    // probe would fall through to defaults (16/8), corrupting the
    // `_z_sys_net_socket_t` pass-by-value ABI.
    let primary = if uses_smoltcp_bridge {
        ProbePlatform::BareMetal
    } else if target.contains("thumbv7m") && env::var("FREERTOS_DIR").is_ok() {
        ProbePlatform::Freertos
    } else if target.contains("nuttx") || target.contains("armv7a-nuttx") {
        ProbePlatform::Nuttx
    } else if (target.contains("riscv64") && env::var("THREADX_DIR").is_ok())
        || (!target.contains("none")
            && !target.contains("linux-gnu")
            && env::var("THREADX_DIR").is_ok()
            && env::var("NETX_DIR").is_ok())
    {
        ProbePlatform::Threadx
    } else if target.contains("none") {
        ProbePlatform::BareMetal
    } else if target.contains("linux") {
        ProbePlatform::Linux
    } else if target.contains("darwin") || target.contains("macos") {
        ProbePlatform::Macos
    } else {
        ProbePlatform::Unknown
    };

    // Try the heuristically-selected platform first. If that probe
    // fails on a `-none-` target (bare-metal-capable), retry with the
    // bare-metal config — the heuristic can misfire when `.envrc`
    // exports `FREERTOS_DIR` / `THREADX_DIR` globally for a workspace
    // where this particular crate is actually being built bare-metal.
    //
    // The primary attempt runs with `cargo_warnings(false)` so its
    // compiler stderr doesn't surface as `cargo:warning=…`; a retry
    // success means the primary was the wrong pick, not a real bug.
    let will_retry = target.contains("none") && primary != ProbePlatform::BareMetal;
    if let Some(sizes) = try_probe(
        &probe_c,
        zenoh_include,
        zpico_sys_dir,
        out_dir,
        &target,
        primary,
        /* suppress_warnings = */ will_retry,
    ) {
        return Some(sizes);
    }
    if will_retry
        && let Some(sizes) = try_probe(
            &probe_c,
            zenoh_include,
            zpico_sys_dir,
            out_dir,
            &target,
            ProbePlatform::BareMetal,
            false,
        )
    {
        return Some(sizes);
    }
    println!(
        "cargo:warning=zpico-platform-shim size_probe failed for all platform \
         configurations — falling back to default sizes — pass-by-value ABI \
         for _z_sys_net_socket_t will corrupt if the real struct size differs"
    );
    None
}

fn try_probe(
    probe_c: &Path,
    zenoh_include: &Path,
    zpico_sys_dir: &Path,
    out_dir: &Path,
    target: &str,
    platform: ProbePlatform,
    suppress_warnings: bool,
) -> Option<(usize, usize)> {
    let mut build = cc::Build::new();
    build.file(probe_c);
    build.include(zenoh_include);
    if suppress_warnings {
        build.cargo_warnings(false);
    }

    if platform == ProbePlatform::Freertos {
        build.define("ZENOH_FREERTOS_LWIP", None);
        if let Ok(dir) = env::var("FREERTOS_DIR") {
            let f = PathBuf::from(&dir);
            build.include(f.join("include"));
            if let Ok(port) = env::var("FREERTOS_PORT") {
                build.include(f.join("portable").join(&port));
            }
        }
        if let Ok(dir) = env::var("FREERTOS_CONFIG_DIR") {
            build.include(dir);
        }
        if let Ok(dir) = env::var("LWIP_DIR") {
            build.include(PathBuf::from(dir).join("src/include"));
        }
    } else if platform == ProbePlatform::Nuttx {
        build.define("ZENOH_NUTTX", None);
        build.define("ZENOH_LINUX", None);
        if let Ok(dir) = env::var("NUTTX_DIR") {
            build.include(PathBuf::from(dir).join("include"));
        }
    } else if platform == ProbePlatform::Threadx {
        build.define("ZENOH_GENERIC", None);
        build.define("ZENOH_THREADX", None);
        build.include(zpico_sys_dir.join("c/platform"));

        // ThreadX platform.h pulls in tx_api.h which pulls in
        // architecture-specific `tx_port.h` + C standard library
        // (stdint.h). Without the ThreadX / NetX / picolibc includes
        // the probe falls back to hardcoded 16/8 and silently skews
        // the `_z_sys_net_socket_t` pass-by-value ABI. Mirror the
        // include set from the main zpico-sys threadx build.
        if let Ok(dir) = env::var("THREADX_DIR") {
            let threadx_dir = PathBuf::from(&dir);
            build.include(threadx_dir.join("common/inc"));
            if target.contains("riscv64") {
                build.include(threadx_dir.join("ports/risc-v64/gnu/inc"));
            } else if !target.contains("none") {
                build.include(threadx_dir.join("ports/linux/gnu/inc"));
            }
        }
        if let Ok(dir) = env::var("THREADX_CONFIG_DIR") {
            build.include(dir);
        }
        if let Ok(dir) = env::var("NETX_DIR") {
            let netx_dir = PathBuf::from(&dir);
            build.include(netx_dir.join("common/inc"));
            build.include(netx_dir.join("addons/BSD"));
            if !target.contains("none") {
                build.include(netx_dir.join("ports/linux/gnu/inc"));
            }
        }
        if let Ok(dir) = env::var("NETX_CONFIG_DIR") {
            build.include(dir);
        }
        if target.contains("riscv64") {
            build
                .flag("-march=rv64gc")
                .flag("-mabi=lp64d")
                .flag("-mcmodel=medany");
            let errno_dir = out_dir.join("errno-override");
            std::fs::create_dir_all(&errno_dir).ok();
            std::fs::write(
                errno_dir.join("errno.h"),
                include_bytes!("../zpico-sys/c/platform/errno_override.h"),
            )
            .ok();
            build.include(&errno_dir);
            if let Some(sysroot) = get_picolibc_sysroot() {
                build.include(sysroot.join("include"));
            } else {
                println!(
                    "cargo:warning=zpico-platform-shim: picolibc sysroot not found; \
                     size probe will likely fail and fall back to default sizes"
                );
            }
        }
    } else if platform == ProbePlatform::BareMetal {
        // Bare-metal: ZENOH_GENERIC → zenoh_generic_platform.h → bare-metal/platform.h
        build.define("ZENOH_GENERIC", None);
        build.include(zpico_sys_dir.join("c/platform"));

        // RV32 bare-metal (ESP32-C3): picolibc isn't on the system's
        // `riscv64-unknown-elf-gcc -march=rv32imc` default include path,
        // so the probe fails with `fatal error: stdint.h: No such file
        // or directory` and the silent fallback to 16/8 corrupts the
        // `_z_sys_net_socket_t` pass-by-value ABI. Mirror the RV32
        // cross-compile setup from `zpico-sys/build.rs::build_zenoh_pico_embedded`.
        if target.contains("riscv32") {
            build.flag("-march=rv32imc").flag("-mabi=ilp32");
            let errno_dir = out_dir.join("errno-override");
            std::fs::create_dir_all(&errno_dir).ok();
            std::fs::write(
                errno_dir.join("errno.h"),
                include_bytes!("../zpico-sys/c/platform/errno_override.h"),
            )
            .ok();
            build.include(&errno_dir);
            if let Some(sysroot) = get_picolibc_sysroot() {
                build.include(sysroot.join("include"));
            }
        } else if target.contains("thumbv7m") || target.contains("thumbv7em") {
            if target.contains("thumbv7em") {
                build
                    .flag("-mcpu=cortex-m4")
                    .flag("-mthumb")
                    .flag("-mfpu=fpv4-sp-d16")
                    .flag("-mfloat-abi=hard");
            } else {
                build.flag("-mcpu=cortex-m3").flag("-mthumb");
            }
        } else if target.contains("armv7r") {
            // Phase 100.3 — AGX Orin SPE (Cortex-R5F) runs ARM mode, no
            // `-mthumb`. `cc::Build` already emits `-march=armv7-r` from
            // the target triple, so we don't repeat `-mcpu=cortex-r5`
            // (gcc warns "switch -mcpu=… conflicts with -march=…"). The
            // FSP ships a `vfpv3-d16` hard-float build of the FreeRTOS
            // ARM_CR5 port; matching the FPU + float ABI here keeps the
            // probe's compile environment lined up with the real board
            // build. (Pointer/int sizes are ABI-determined, so the probe
            // would pick `(2, 6)` even without these flags — they exist
            // for parity, not correctness.)
            build.flag("-mfpu=vfpv3-d16").flag("-mfloat-abi=hard");
        }
    } else if platform == ProbePlatform::Linux {
        build.define("ZENOH_LINUX", None);
    } else if platform == ProbePlatform::Macos {
        build.define("ZENOH_MACOS", None);
    }

    build.cargo_metadata(false);
    // Use a unique archive name per platform so retry attempts don't
    // clash with each other in the same OUT_DIR.
    let archive_name = match platform {
        ProbePlatform::Freertos => "nros_size_probe_freertos",
        ProbePlatform::Nuttx => "nros_size_probe_nuttx",
        ProbePlatform::Threadx => "nros_size_probe_threadx",
        ProbePlatform::BareMetal => "nros_size_probe_bare_metal",
        ProbePlatform::Linux => "nros_size_probe_linux",
        ProbePlatform::Macos => "nros_size_probe_macos",
        ProbePlatform::Unknown => "nros_size_probe",
    };
    if build.try_compile(archive_name).is_err() {
        return None;
    }

    let archive = out_dir.join(format!("lib{archive_name}.a"));
    let socket = read_symbol_size(&archive, "__nros_sizeof_net_socket");
    let endpoint = read_symbol_size(&archive, "__nros_sizeof_net_endpoint");

    if socket > 0 && endpoint > 0 {
        Some((socket, endpoint))
    } else {
        None
    }
}

/// Get the picolibc sysroot path for bare-metal RISC-V (provides
/// C standard library headers: stdint.h, etc.). Mirrors the helper
/// in `zpico-sys/build.rs` — kept in sync manually.
fn get_picolibc_sysroot() -> Option<PathBuf> {
    for cc_name in &["riscv64-unknown-elf-gcc", "riscv32-esp-elf-gcc"] {
        if let Ok(output) = Command::new(cc_name)
            .args([
                "-march=rv32imc",
                "-mabi=ilp32",
                "--specs=picolibc.specs",
                "-print-sysroot",
            ])
            .output()
            && output.status.success()
        {
            let sysroot = String::from_utf8_lossy(&output.stdout).trim().to_string();
            if !sysroot.is_empty() {
                let path = PathBuf::from(&sysroot);
                if path.join("include").exists() {
                    return Some(path);
                }
            }
        }
    }
    let fallback = PathBuf::from("/usr/lib/picolibc/riscv64-unknown-elf");
    if fallback.join("include").exists() {
        return Some(fallback);
    }
    None
}

fn read_symbol_size(archive: &Path, symbol: &str) -> usize {
    let sysroot = Command::new("rustc")
        .args(["--print", "sysroot"])
        .output()
        .ok()
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_default();

    let host = env::var("HOST").unwrap_or_default();
    let rust_nm = PathBuf::from(&sysroot)
        .join("lib/rustlib")
        .join(&host)
        .join("bin/llvm-nm");

    for nm in &[rust_nm, PathBuf::from("llvm-nm"), PathBuf::from("nm")] {
        if let Ok(output) = Command::new(nm)
            .args(["--print-size", "--defined-only"])
            .arg(archive)
            .output()
            && output.status.success()
        {
            let stdout = String::from_utf8_lossy(&output.stdout);
            for line in stdout.lines() {
                if line.contains(symbol) {
                    let parts: Vec<&str> = line.split_whitespace().collect();
                    if parts.len() >= 2
                        && let Ok(size) = usize::from_str_radix(parts[1], 16)
                    {
                        return size;
                    }
                }
            }
        }
    }
    0
}
