meta:
  version: 1
  inputs:
  - path: launch/system.launch.xml
    sha256: 9b982bd862bb3dfc4cf4ab2d2dae1f88aa0b71a60e15b5a8e955c396f862b6c4
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
structure:
  scopes:
    system.launch.xml:
      file: system.launch.xml
