//! Zenoh transport backend
//!
//! Provides a transport backend using the nros-rmw-zenoh wrapper.
//! This is designed for embedded platforms that need a simpler API than
//! the full zenoh-pico bindings.
//!
//! Requires the `shim` feature flag.
//!
//! # Features
//!
//! - Session management with ZenohId support
//! - Publishers with RMW attachment support for rmw_zenoh compatibility
//! - Subscribers with wildcard matching
//! - Liveliness tokens for ROS 2 discovery
//! - Service servers via queryables
//! - Service clients via z_get queries
//! - Manual polling (no background threads) for embedded systems
//!
//! # Example
//!
//! ```ignore
//! use nros_rmw::{Transport, TransportConfig, SessionMode};
//! use nros_rmw_zenoh::ZenohTransport;
//!
//! // Create config
//! let config = TransportConfig {
//!     locator: Some("tcp/192.168.1.1:7447"),
//!     mode: SessionMode::Client,
//!     properties: &[],
//! };
//!
//! // Open session
//! let mut session = ZenohTransport::open(&config).expect("Failed to open session");
//!
//! // Must poll periodically
//! session.spin_once(core::time::Duration::from_millis(10))?;
//! ```

pub mod publisher;
pub mod service;
pub mod session;
pub mod subscriber;
pub mod transport;

use portable_atomic::Ordering;

// Use AtomicI64 on 64-bit targets, AtomicI32 on 32-bit (e.g. Cortex-M, riscv32)
// portable-atomic provides fetch_add/fetch_sub even on targets without native
// atomic RMW instructions (e.g. riscv32imc) via software fallback.
#[cfg(target_has_atomic = "64")]
pub(crate) type AtomicSeqCounter = portable_atomic::AtomicI64;
#[cfg(not(target_has_atomic = "64"))]
pub(crate) type AtomicSeqCounter = portable_atomic::AtomicI32;

use nros_rmw::{QosSettings, ServiceInfo, TopicInfo, TransportError};

use crate::{
    keyexpr::QosKeyExpr,
    zpico::{Context, LivelinessToken, ZPICO_RMW_GID_SIZE, ZpicoError},
};

// Re-export for convenience
pub use crate::zpico::ZenohId;

// Re-export submodule types
pub use publisher::ZenohPublisher;
pub use service::{ZenohServiceClient, ZenohServiceServer};
pub use session::ZenohSession;
pub use subscriber::ZenohSubscriber;
pub use transport::{ZenohRmw, ZenohTransport};

// ============================================================================
// Constants
// ============================================================================

/// RMW GID size for attachment serialization (16 bytes for Humble)
pub const RMW_GID_SIZE: usize = ZPICO_RMW_GID_SIZE;

/// Size of serialized RMW attachment (without safety CRC)
/// Format: sequence_number (8) + timestamp (8) + VLE length (1) + gid (16) = 33 bytes
pub(crate) const RMW_ATTACHMENT_SIZE: usize = 8 + 8 + 1 + RMW_GID_SIZE;

/// Size of the CRC-32 field appended when safety-e2e is enabled
#[cfg(feature = "safety-e2e")]
pub(crate) const SAFETY_CRC_SIZE: usize = 4;

/// Total attachment size with safety CRC (37 bytes)
#[cfg(feature = "safety-e2e")]
pub(crate) const RMW_ATTACHMENT_SIZE_WITH_CRC: usize = RMW_ATTACHMENT_SIZE + SAFETY_CRC_SIZE;

/// LCG multiplier for GID PRNG generation.
const GID_PRNG_MULTIPLIER: u64 = 0x517cc1b727220a95;

/// Null-terminated locator string buffer size.
pub(crate) const LOCATOR_BUFFER_SIZE: usize = 128;

/// Property key/value buffer size for session configuration.
/// Must be large enough for file paths (TLS certificates, etc.).
pub(crate) const CONFIG_PROPERTY_SIZE: usize = 256;

/// Maximum number of session configuration properties.
pub(crate) const MAX_SESSION_PROPERTIES: usize = 8;

// KEYEXPR_STRING_SIZE and KEYEXPR_BUFFER_SIZE are generated by build.rs
// from the NROS_KEYEXPR_STRING_SIZE env var (default 256).
pub(crate) use crate::config::{KEYEXPR_BUFFER_SIZE, KEYEXPR_STRING_SIZE};

/// Buffer size for topic/namespace name mangling.
const MANGLED_NAME_SIZE: usize = 64;

/// 16-byte ZID formatted as hexadecimal (32 ASCII characters).
const ZID_HEX_SIZE: usize = 32;

/// QoS encoding string buffer size.
const QOS_STRING_SIZE: usize = 32;

/// Placeholder timestamp increment per publish (1ms in nanoseconds).
/// Retained as a documented landing place for legacy callers; the
/// publisher path now uses `<P as PlatformClock>::clock_ms()` directly
/// (Phase 108.C.zenoh.2).
#[allow(dead_code)]
pub(crate) const TIMESTAMP_INCREMENT_NS: i64 = 1_000_000;

/// Attachment buffer size: 33 bytes normally, 37 with safety CRC
#[cfg(not(feature = "safety-e2e"))]
pub(crate) const SUBSCRIBER_ATTACHMENT_BUF_SIZE: usize = RMW_ATTACHMENT_SIZE;
#[cfg(feature = "safety-e2e")]
pub(crate) const SUBSCRIBER_ATTACHMENT_BUF_SIZE: usize = RMW_ATTACHMENT_SIZE_WITH_CRC;

pub use crate::config::{SERVICE_BUFFER_SIZE, SUBSCRIBER_BUFFER_SIZE};

// ============================================================================
// Executor Wake Signal (std only)
// ============================================================================

/// Signal the executor that new data is available.
///
/// Called from subscription and service callbacks (which run on the zenoh-pico
/// background read thread) to wake the executor's `spin()` loop immediately
/// instead of waiting for the poll interval timeout.
#[cfg(feature = "std")]
pub fn signal_executor_wake() {
    let (lock, cvar) = &*EXECUTOR_WAKE;
    if let Ok(mut pending) = lock.lock() {
        *pending = true;
        cvar.notify_one();
    }
}

/// Wait for a wake signal or timeout.
///
/// Returns `true` if woken by a signal, `false` on timeout.
/// Used by `BasicExecutor::spin()` to sleep efficiently between iterations.
#[cfg(feature = "std")]
pub fn wait_for_executor_wake(timeout: core::time::Duration) -> bool {
    let (lock, cvar) = &*EXECUTOR_WAKE;
    if let Ok(mut pending) = lock.lock() {
        if *pending {
            *pending = false;
            return true;
        }
        let result = cvar.wait_timeout(pending, timeout);
        if let Ok((mut guard, _)) = result {
            let was_signaled = *guard;
            *guard = false;
            was_signaled
        } else {
            false
        }
    } else {
        // Mutex poisoned — fall back to sleep behavior
        std::thread::sleep(timeout);
        false
    }
}

#[cfg(feature = "std")]
static EXECUTOR_WAKE: std::sync::LazyLock<(std::sync::Mutex<bool>, std::sync::Condvar)> =
    std::sync::LazyLock::new(|| (std::sync::Mutex::new(false), std::sync::Condvar::new()));

// ============================================================================
// Error Conversion
// ============================================================================

impl From<ZpicoError> for TransportError {
    fn from(err: ZpicoError) -> Self {
        match err {
            ZpicoError::Generic => TransportError::ConnectionFailed,
            ZpicoError::Config => TransportError::InvalidArgument,
            ZpicoError::Session => TransportError::ConnectionFailed,
            ZpicoError::Task => TransportError::TaskStartFailed,
            ZpicoError::KeyExpr => TransportError::TopicNameInvalid,
            ZpicoError::Full => TransportError::PublisherCreationFailed,
            ZpicoError::Invalid => TransportError::InvalidArgument,
            ZpicoError::Publish => TransportError::PublishFailed,
            ZpicoError::NotOpen => TransportError::Disconnected,
            ZpicoError::Timeout => TransportError::Timeout,
        }
    }
}

// ============================================================================
// RMW Attachment Support
// ============================================================================

/// RMW attachment data for rmw_zenoh compatibility
///
/// This metadata is attached to each published message and is required
/// for ROS 2 nodes using rmw_zenoh_cpp to receive messages.
#[derive(Debug, Clone, Copy)]
pub struct RmwAttachment {
    /// Message sequence number (incremented per publish)
    pub sequence_number: i64,
    /// Timestamp in nanoseconds
    pub timestamp: i64,
    /// RMW Global Identifier (random, generated once per publisher)
    pub rmw_gid: [u8; RMW_GID_SIZE],
}

impl RmwAttachment {
    /// Create a new attachment with a random GID
    pub fn new() -> Self {
        Self {
            sequence_number: 0,
            timestamp: 0,
            rmw_gid: Self::generate_gid(),
        }
    }

    /// Generate a random GID using a simple PRNG
    pub fn generate_gid() -> [u8; RMW_GID_SIZE] {
        let mut gid = [0u8; RMW_GID_SIZE];
        static COUNTER: AtomicSeqCounter = AtomicSeqCounter::new(0);
        let seed = COUNTER.fetch_add(1, Ordering::Relaxed) as u64;
        // Use address of gid as additional entropy
        let addr = &gid as *const _ as u64;
        let mixed = seed.wrapping_mul(GID_PRNG_MULTIPLIER) ^ addr;

        for (i, byte) in gid.iter_mut().enumerate() {
            let shift = (i % 8) * 8;
            *byte = ((mixed.wrapping_mul((i as u64).wrapping_add(1))) >> shift) as u8;
        }
        gid
    }

    /// Serialize the attachment in the format expected by rmw_zenoh_cpp
    ///
    /// Format:
    /// - int64: sequence_number (little-endian, 8 bytes)
    /// - int64: timestamp (little-endian, 8 bytes)
    /// - VLE length (1 byte for length 16)
    /// - 16 x uint8: GID
    pub fn serialize(&self, buf: &mut [u8; RMW_ATTACHMENT_SIZE]) {
        // Sequence number (little-endian)
        buf[0..8].copy_from_slice(&self.sequence_number.to_le_bytes());
        // Timestamp (little-endian)
        buf[8..16].copy_from_slice(&self.timestamp.to_le_bytes());
        // VLE length (16 fits in single byte)
        buf[16] = RMW_GID_SIZE as u8;
        // GID bytes
        buf[17..33].copy_from_slice(&self.rmw_gid);
    }
}

impl Default for RmwAttachment {
    fn default() -> Self {
        Self::new()
    }
}

impl RmwAttachment {
    /// Deserialize attachment from raw bytes received from RMW
    ///
    /// Format:
    /// - int64: sequence_number (little-endian, 8 bytes)
    /// - int64: timestamp (little-endian, 8 bytes)
    /// - VLE length (1 byte for length 16)
    /// - 16 x uint8: GID
    ///
    /// Returns None if the buffer is too small or malformed.
    pub fn deserialize(buf: &[u8]) -> Option<Self> {
        if buf.len() < RMW_ATTACHMENT_SIZE {
            return None;
        }

        // Parse sequence number (little-endian)
        let sequence_number = i64::from_le_bytes([
            buf[0], buf[1], buf[2], buf[3], buf[4], buf[5], buf[6], buf[7],
        ]);

        // Parse timestamp (little-endian)
        let timestamp = i64::from_le_bytes([
            buf[8], buf[9], buf[10], buf[11], buf[12], buf[13], buf[14], buf[15],
        ]);

        // Parse VLE length (should be 16)
        let gid_len = buf[16] as usize;
        if gid_len != RMW_GID_SIZE {
            return None;
        }

        // Parse GID
        let mut rmw_gid = [0u8; RMW_GID_SIZE];
        rmw_gid.copy_from_slice(&buf[17..33]);

        Some(Self {
            sequence_number,
            timestamp,
            rmw_gid,
        })
    }
}

/// Message information parsed from RMW attachment
///
/// This struct contains metadata about a received message, extracted
/// from the rmw_zenoh attachment.
#[derive(Debug, Clone, Copy)]
pub struct MessageInfo {
    /// Message sequence number from the publisher
    pub sequence_number: i64,
    /// Timestamp in nanoseconds (source time)
    pub timestamp_ns: i64,
    /// Publisher's Global Identifier
    pub publisher_gid: [u8; RMW_GID_SIZE],
}

impl MessageInfo {
    /// Parse MessageInfo from raw attachment data
    ///
    /// Returns None if no attachment or if parsing fails.
    pub fn from_attachment(attachment: &[u8]) -> Option<Self> {
        RmwAttachment::deserialize(attachment).map(|att| Self {
            sequence_number: att.sequence_number,
            timestamp_ns: att.timestamp,
            publisher_gid: att.rmw_gid,
        })
    }
}

// ============================================================================
// Ros2Liveliness Helper
// ============================================================================

/// ROS 2 liveliness key expression builder for the shim transport
///
/// Generates the key expressions required for ROS 2 discovery via rmw_zenoh.
///
/// Protocol format:
/// `{PREFIX}/{domain_id}/{zid}/{version}/{entity}/%/{ns}/{node}[/{topic}/{type}/{hash}/{qos}]`
pub struct Ros2Liveliness;

// rmw_zenoh liveliness protocol constants
const LIVELINESS_PREFIX: &str = "@ros2_lv";
const PROTO_VERSION_NODE: &str = "0/0";
const PROTO_VERSION_TOPIC: &str = "0/11";
const ENTITY_NODE: &str = "NN";
const ENTITY_PUBLISHER: &str = "MP";
const ENTITY_SUBSCRIBER: &str = "MS";
const ENTITY_SERVICE_SERVER: &str = "SS";
const ENTITY_SERVICE_CLIENT: &str = "SC";

impl Ros2Liveliness {
    /// Build a node liveliness key expression
    ///
    /// Format: `@ros2_lv/<domain_id>/<zid>/0/0/NN/%/<mangled_ns>/<node_name>`
    ///
    /// The namespace is mangled using the same rules as topic names:
    /// - `/` → `%`
    /// - `/demo` → `%demo`
    /// - `/ns/sub` → `%ns%sub`
    pub fn node_keyexpr<const N: usize>(
        domain_id: u32,
        zid: &ZenohId,
        namespace: &str,
        node_name: &str,
    ) -> heapless::String<N> {
        let mut key = heapless::String::new();
        let mut zid_hex = [0u8; ZID_HEX_SIZE];
        zid.to_hex_bytes(&mut zid_hex);
        let zid_str = core::str::from_utf8(&zid_hex).unwrap_or("");
        let ns_mangled = Self::mangle_topic_name::<MANGLED_NAME_SIZE>(namespace);
        let _ = core::fmt::write(
            &mut key,
            format_args!(
                "{}/{}/{}/{}/{}/%/{}/{}",
                LIVELINESS_PREFIX,
                domain_id,
                zid_str,
                PROTO_VERSION_NODE,
                ENTITY_NODE,
                ns_mangled.as_str(),
                node_name
            ),
        );
        key
    }

    /// Build a publisher liveliness key expression
    ///
    /// Format: `@ros2_lv/<domain_id>/<zid>/0/11/MP/%/<mangled_ns>/<node_name>/<topic>/<type>/<hash>/<qos>`
    /// Note: type_hash already includes the `RIHS01_` prefix from generated code
    pub fn publisher_keyexpr<const N: usize>(
        domain_id: u32,
        zid: &ZenohId,
        namespace: &str,
        node_name: &str,
        topic: &TopicInfo,
        qos: &QosSettings,
    ) -> heapless::String<N> {
        let mut key = heapless::String::new();
        let mut zid_hex = [0u8; ZID_HEX_SIZE];
        zid.to_hex_bytes(&mut zid_hex);
        let zid_str = core::str::from_utf8(&zid_hex).unwrap_or("");
        // Mangle topic name: replace slashes with percent signs
        let topic_mangled = Self::mangle_topic_name::<MANGLED_NAME_SIZE>(topic.name);
        let ns_mangled = Self::mangle_topic_name::<MANGLED_NAME_SIZE>(namespace);
        let qos_string: heapless::String<QOS_STRING_SIZE> = qos.to_qos_string();
        let _ = core::fmt::write(
            &mut key,
            format_args!(
                "{}/{}/{}/{}/{}/%/{}/{}/{}/{}/{}/{}",
                LIVELINESS_PREFIX,
                domain_id,
                zid_str,
                PROTO_VERSION_TOPIC,
                ENTITY_PUBLISHER,
                ns_mangled.as_str(),
                node_name,
                topic_mangled.as_str(),
                topic.type_name,
                topic.type_hash,
                qos_string.as_str()
            ),
        );
        key
    }

    /// Build a subscriber liveliness key expression
    ///
    /// Format: `@ros2_lv/<domain_id>/<zid>/0/11/MS/%/<mangled_ns>/<node_name>/<topic>/<type>/<hash>/<qos>`
    /// Note: type_hash already includes the `RIHS01_` prefix from generated code
    pub fn subscriber_keyexpr<const N: usize>(
        domain_id: u32,
        zid: &ZenohId,
        namespace: &str,
        node_name: &str,
        topic: &TopicInfo,
        qos: &QosSettings,
    ) -> heapless::String<N> {
        let mut key = heapless::String::new();
        let mut zid_hex = [0u8; ZID_HEX_SIZE];
        zid.to_hex_bytes(&mut zid_hex);
        let zid_str = core::str::from_utf8(&zid_hex).unwrap_or("");
        let topic_mangled = Self::mangle_topic_name::<MANGLED_NAME_SIZE>(topic.name);
        let ns_mangled = Self::mangle_topic_name::<MANGLED_NAME_SIZE>(namespace);
        let qos_string: heapless::String<QOS_STRING_SIZE> = qos.to_qos_string();
        let _ = core::fmt::write(
            &mut key,
            format_args!(
                "{}/{}/{}/{}/{}/%/{}/{}/{}/{}/{}/{}",
                LIVELINESS_PREFIX,
                domain_id,
                zid_str,
                PROTO_VERSION_TOPIC,
                ENTITY_SUBSCRIBER,
                ns_mangled.as_str(),
                node_name,
                topic_mangled.as_str(),
                topic.type_name,
                topic.type_hash,
                qos_string.as_str()
            ),
        );
        key
    }

    /// Build a service server liveliness key expression
    ///
    /// Format: `@ros2_lv/<domain_id>/<zid>/0/11/SS/%/<mangled_ns>/<node_name>/<service>/<type>/<hash>/<qos>`
    /// Note: type_hash already includes the `RIHS01_` prefix from generated code
    pub fn service_server_keyexpr<const N: usize>(
        domain_id: u32,
        zid: &ZenohId,
        namespace: &str,
        node_name: &str,
        service: &ServiceInfo,
        qos: &QosSettings,
    ) -> heapless::String<N> {
        let mut key = heapless::String::new();
        let mut zid_hex = [0u8; ZID_HEX_SIZE];
        zid.to_hex_bytes(&mut zid_hex);
        let zid_str = core::str::from_utf8(&zid_hex).unwrap_or("");
        let service_mangled = Self::mangle_topic_name::<MANGLED_NAME_SIZE>(service.name);
        let ns_mangled = Self::mangle_topic_name::<MANGLED_NAME_SIZE>(namespace);
        let qos_string: heapless::String<QOS_STRING_SIZE> = qos.to_qos_string();
        let _ = core::fmt::write(
            &mut key,
            format_args!(
                "{}/{}/{}/{}/{}/%/{}/{}/{}/{}/{}/{}",
                LIVELINESS_PREFIX,
                domain_id,
                zid_str,
                PROTO_VERSION_TOPIC,
                ENTITY_SERVICE_SERVER,
                ns_mangled.as_str(),
                node_name,
                service_mangled.as_str(),
                service.type_name,
                service.type_hash,
                qos_string.as_str()
            ),
        );
        key
    }

    /// Build a service client liveliness key expression
    ///
    /// Format: `@ros2_lv/<domain_id>/<zid>/0/11/SC/%/<mangled_ns>/<node_name>/<service>/<type>/<hash>/<qos>`
    /// Note: type_hash already includes the `RIHS01_` prefix from generated code
    pub fn service_client_keyexpr<const N: usize>(
        domain_id: u32,
        zid: &ZenohId,
        namespace: &str,
        node_name: &str,
        service: &ServiceInfo,
        qos: &QosSettings,
    ) -> heapless::String<N> {
        let mut key = heapless::String::new();
        let mut zid_hex = [0u8; ZID_HEX_SIZE];
        zid.to_hex_bytes(&mut zid_hex);
        let zid_str = core::str::from_utf8(&zid_hex).unwrap_or("");
        let service_mangled = Self::mangle_topic_name::<MANGLED_NAME_SIZE>(service.name);
        let ns_mangled = Self::mangle_topic_name::<MANGLED_NAME_SIZE>(namespace);
        let qos_string: heapless::String<QOS_STRING_SIZE> = qos.to_qos_string();
        let _ = core::fmt::write(
            &mut key,
            format_args!(
                "{}/{}/{}/{}/{}/%/{}/{}/{}/{}/{}/{}",
                LIVELINESS_PREFIX,
                domain_id,
                zid_str,
                PROTO_VERSION_TOPIC,
                ENTITY_SERVICE_CLIENT,
                ns_mangled.as_str(),
                node_name,
                service_mangled.as_str(),
                service.type_name,
                service.type_hash,
                qos_string.as_str()
            ),
        );
        key
    }

    /// Build a wildcard liveliness keyexpr matching any service-server token
    /// for the given service.
    ///
    /// Phase 108.C.zenoh.4 — wildcard publisher liveliness keyexpr.
    ///
    /// Format: `@ros2_lv/<domain_id>/*/0/11/MP/%/*/*/<topic>/<type>/*/*`
    /// — wildcards on zid, namespace, node, type_hash, qos. Used by
    /// `ZenohSubscriber`'s LivelinessChanged emulation: the subscriber
    /// periodically polls this keyexpr via `liveliness_get_start` to
    /// discover any publisher matching its own (topic, type) pair, and
    /// fires `LivelinessChanged` on alive-state transitions.
    pub fn publisher_keyexpr_wildcard<const N: usize>(
        domain_id: u32,
        topic: &TopicInfo,
    ) -> heapless::String<N> {
        let mut key = heapless::String::new();
        let topic_mangled = Self::mangle_topic_name::<MANGLED_NAME_SIZE>(topic.name);
        let _ = core::fmt::write(
            &mut key,
            format_args!(
                "{}/{}/*/{}/{}/%/*/*/{}/{}/*/*",
                LIVELINESS_PREFIX,
                domain_id,
                PROTO_VERSION_TOPIC,
                ENTITY_PUBLISHER,
                topic_mangled.as_str(),
                topic.type_name,
            ),
        );
        key
    }

    /// Format: `@ros2_lv/<domain_id>/*/0/11/SS/%/*/*/<service>/<type>/*/*`
    /// — wildcards on zid, namespace, node, type_hash, and qos. Used by
    /// `Client::wait_for_service` to discover any matching server before
    /// the first request, mirroring `rclcpp::ClientBase::wait_for_service`.
    pub fn service_server_keyexpr_wildcard<const N: usize>(
        domain_id: u32,
        service: &ServiceInfo,
    ) -> heapless::String<N> {
        let mut key = heapless::String::new();
        let service_mangled = Self::mangle_topic_name::<MANGLED_NAME_SIZE>(service.name);
        let _ = core::fmt::write(
            &mut key,
            format_args!(
                "{}/{}/*/{}/{}/%/*/*/{}/{}/*/*",
                LIVELINESS_PREFIX,
                domain_id,
                PROTO_VERSION_TOPIC,
                ENTITY_SERVICE_SERVER,
                service_mangled.as_str(),
                service.type_name,
            ),
        );
        key
    }

    /// Mangle a topic name by replacing '/' with '%'
    fn mangle_topic_name<const N: usize>(topic: &str) -> heapless::String<N> {
        let mut mangled = heapless::String::new();
        for c in topic.chars() {
            if c == '/' {
                let _ = mangled.push('%');
            } else {
                let _ = mangled.push(c);
            }
        }
        mangled
    }
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    // ========================================================================
    // Error Conversion Tests
    // ========================================================================

    #[test]
    fn test_error_conversion() {
        assert_eq!(
            TransportError::from(ZpicoError::Config),
            TransportError::InvalidArgument
        );
        assert_eq!(
            TransportError::from(ZpicoError::Publish),
            TransportError::PublishFailed
        );
    }

    // ========================================================================
    // C.6 RMW Zenoh Protocol Verification Tests
    // ========================================================================

    // ------------------------------------------------------------------------
    // RMW Attachment Format Tests
    // ------------------------------------------------------------------------

    #[test]
    fn test_rmw_attachment_serialization() {
        let mut att = RmwAttachment::new();
        att.sequence_number = 42;
        att.timestamp = 1000000;

        let mut buf = [0u8; RMW_ATTACHMENT_SIZE];
        att.serialize(&mut buf);

        // Check sequence number (little-endian)
        assert_eq!(&buf[0..8], &42i64.to_le_bytes());
        // Check timestamp (little-endian)
        assert_eq!(&buf[8..16], &1000000i64.to_le_bytes());
        // Check VLE length
        assert_eq!(buf[16], 16);
        // Check GID (should match)
        assert_eq!(&buf[17..33], &att.rmw_gid);
    }

    #[test]
    fn test_rmw_attachment_deserialization() {
        // Create known attachment bytes
        let mut buf = [0u8; RMW_ATTACHMENT_SIZE];
        // Sequence number: 123
        buf[0..8].copy_from_slice(&123i64.to_le_bytes());
        // Timestamp: 456789
        buf[8..16].copy_from_slice(&456789i64.to_le_bytes());
        // VLE length: 16
        buf[16] = 16;
        // GID: 0x01, 0x02, ..., 0x10
        for i in 0..16 {
            buf[17 + i] = (i + 1) as u8;
        }

        let parsed = RmwAttachment::deserialize(&buf);
        assert!(parsed.is_some());
        let att = parsed.unwrap();

        assert_eq!(att.sequence_number, 123);
        assert_eq!(att.timestamp, 456789);
        for i in 0..16 {
            assert_eq!(att.rmw_gid[i], (i + 1) as u8);
        }
    }

    #[test]
    fn test_rmw_attachment_roundtrip() {
        let original = RmwAttachment {
            sequence_number: 999,
            timestamp: 1234567890,
            rmw_gid: [
                0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xFF, 0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77,
                0x88, 0x99,
            ],
        };

        let mut buf = [0u8; RMW_ATTACHMENT_SIZE];
        original.serialize(&mut buf);

        let parsed = RmwAttachment::deserialize(&buf).expect("Failed to deserialize");
        assert_eq!(parsed.sequence_number, original.sequence_number);
        assert_eq!(parsed.timestamp, original.timestamp);
        assert_eq!(parsed.rmw_gid, original.rmw_gid);
    }

    #[test]
    fn test_rmw_attachment_deserialize_too_short() {
        let buf = [0u8; 10]; // Too short
        assert!(RmwAttachment::deserialize(&buf).is_none());
    }

    #[test]
    fn test_rmw_attachment_deserialize_wrong_gid_length() {
        let mut buf = [0u8; RMW_ATTACHMENT_SIZE];
        buf[16] = 8; // Wrong GID length (should be 16)
        assert!(RmwAttachment::deserialize(&buf).is_none());
    }

    #[test]
    fn test_message_info_from_attachment() {
        let mut buf = [0u8; RMW_ATTACHMENT_SIZE];
        buf[0..8].copy_from_slice(&42i64.to_le_bytes());
        buf[8..16].copy_from_slice(&1000000i64.to_le_bytes());
        buf[16] = 16;

        let info = MessageInfo::from_attachment(&buf);
        assert!(info.is_some());
        let info = info.unwrap();
        assert_eq!(info.sequence_number, 42);
        assert_eq!(info.timestamp_ns, 1000000);
    }

    // ------------------------------------------------------------------------
    // Liveliness Token Format Tests
    // ------------------------------------------------------------------------

    #[test]
    fn test_ros2_liveliness_mangle() {
        let mangled = Ros2Liveliness::mangle_topic_name::<MANGLED_NAME_SIZE>("/chatter");
        assert_eq!(mangled.as_str(), "%chatter");

        let mangled2 = Ros2Liveliness::mangle_topic_name::<MANGLED_NAME_SIZE>("/foo/bar/baz");
        assert_eq!(mangled2.as_str(), "%foo%bar%baz");
    }

    #[test]
    fn test_ros2_liveliness_node_keyexpr() {
        let zid = ZenohId::from_bytes([
            0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e,
            0x0f, 0x10,
        ]);
        // Root namespace: "/" mangles to "%"
        let keyexpr = Ros2Liveliness::node_keyexpr::<256>(0, &zid, "/", "my_node");

        // Format: @ros2_lv/<domain_id>/<zid>/0/0/NN/%/<mangled_ns>/<node_name>
        // ZID is in LSB-first order
        assert!(keyexpr.as_str().starts_with("@ros2_lv/0/"));
        assert!(keyexpr.as_str().contains("/0/0/NN/%/%/"));
        assert!(keyexpr.as_str().ends_with("/my_node"));
    }

    #[test]
    fn test_ros2_liveliness_node_keyexpr_with_namespace() {
        let zid = ZenohId::from_bytes([0u8; 16]);

        // Non-root namespace: "/demo" mangles to "%demo"
        let keyexpr = Ros2Liveliness::node_keyexpr::<256>(0, &zid, "/demo", "talker");
        assert!(keyexpr.as_str().contains("/0/0/NN/%/%demo/talker"));

        // Nested namespace: "/ns/sub" mangles to "%ns%sub"
        let keyexpr2 = Ros2Liveliness::node_keyexpr::<256>(0, &zid, "/ns/sub", "my_node");
        assert!(keyexpr2.as_str().contains("/0/0/NN/%/%ns%sub/my_node"));
    }

    #[test]
    fn test_ros2_liveliness_publisher_keyexpr() {
        let zid = ZenohId::from_bytes([0u8; 16]);
        let topic = TopicInfo::new("/chatter", "std_msgs::msg::dds_::String_", "RIHS01_abc123");
        let qos = QosSettings::QOS_PROFILE_SENSOR_DATA;
        let keyexpr =
            Ros2Liveliness::publisher_keyexpr::<256>(0, &zid, "/", "my_node", &topic, &qos);

        // Format: @ros2_lv/<domain_id>/<zid>/0/11/MP/%/<mangled_ns>/<node_name>/<mangled_topic>/<type>/<hash>/<qos>
        assert!(keyexpr.as_str().starts_with("@ros2_lv/0/"));
        assert!(keyexpr.as_str().contains("/0/11/MP/%/%/"));
        assert!(keyexpr.as_str().contains("/my_node/"));
        assert!(keyexpr.as_str().contains("%chatter/"));
        assert!(keyexpr.as_str().contains("std_msgs::msg::dds_::String_"));
        assert!(keyexpr.as_str().contains("RIHS01_abc123"));
    }

    #[test]
    fn test_ros2_liveliness_publisher_keyexpr_with_namespace() {
        let zid = ZenohId::from_bytes([0u8; 16]);
        let topic = TopicInfo::new("/chatter", "std_msgs::msg::dds_::String_", "RIHS01_abc123");
        let qos = QosSettings::QOS_PROFILE_SENSOR_DATA;
        let keyexpr =
            Ros2Liveliness::publisher_keyexpr::<256>(0, &zid, "/demo", "talker", &topic, &qos);
        assert!(keyexpr.as_str().contains("/0/11/MP/%/%demo/talker/"));
    }

    #[test]
    fn test_ros2_liveliness_subscriber_keyexpr() {
        let zid = ZenohId::from_bytes([0u8; 16]);
        let topic = TopicInfo::new("/chatter", "std_msgs::msg::dds_::Int32_", "RIHS01_def456");
        let qos = QosSettings::QOS_PROFILE_SENSOR_DATA;
        let keyexpr =
            Ros2Liveliness::subscriber_keyexpr::<256>(0, &zid, "/", "my_node", &topic, &qos);

        // Format: @ros2_lv/<domain_id>/<zid>/0/11/MS/%/<mangled_ns>/<node_name>/<mangled_topic>/<type>/<hash>/<qos>
        assert!(keyexpr.as_str().starts_with("@ros2_lv/0/"));
        assert!(keyexpr.as_str().contains("/0/11/MS/%/%/"));
        assert!(keyexpr.as_str().contains("/my_node/"));
        assert!(keyexpr.as_str().contains("%chatter/"));
    }

    #[test]
    fn test_ros2_liveliness_service_server_keyexpr() {
        let zid = ZenohId::from_bytes([0u8; 16]);
        let service = ServiceInfo::new(
            "/add_two_ints",
            "example_interfaces::srv::dds_::AddTwoInts",
            "RIHS01_abc123",
        );
        let qos = QosSettings::QOS_PROFILE_SERVICES_DEFAULT;
        let keyexpr =
            Ros2Liveliness::service_server_keyexpr::<256>(0, &zid, "/", "my_node", &service, &qos);

        // Format: @ros2_lv/<domain_id>/<zid>/0/11/SS/%/<mangled_ns>/<node_name>/<mangled_service>/<type>/<hash>/<qos>
        assert!(keyexpr.as_str().starts_with("@ros2_lv/0/"));
        assert!(keyexpr.as_str().contains("/0/11/SS/%/%/"));
        assert!(keyexpr.as_str().contains("/my_node/"));
        assert!(keyexpr.as_str().contains("%add_two_ints/"));
    }

    #[test]
    fn test_ros2_liveliness_service_server_keyexpr_with_namespace() {
        let zid = ZenohId::from_bytes([0u8; 16]);
        let service = ServiceInfo::new(
            "/add_two_ints",
            "example_interfaces::srv::dds_::AddTwoInts",
            "RIHS01_abc123",
        );
        let qos = QosSettings::QOS_PROFILE_SERVICES_DEFAULT;
        let keyexpr = Ros2Liveliness::service_server_keyexpr::<256>(
            0, &zid, "/demo", "my_node", &service, &qos,
        );
        assert!(keyexpr.as_str().contains("/0/11/SS/%/%demo/my_node/"));
    }

    #[test]
    fn test_ros2_liveliness_service_client_keyexpr() {
        let zid = ZenohId::from_bytes([0u8; 16]);
        let service = ServiceInfo::new(
            "/add_two_ints",
            "example_interfaces::srv::dds_::AddTwoInts",
            "RIHS01_abc123",
        );
        let qos = QosSettings::QOS_PROFILE_SERVICES_DEFAULT;
        let keyexpr =
            Ros2Liveliness::service_client_keyexpr::<256>(0, &zid, "/", "my_node", &service, &qos);

        // Format: @ros2_lv/<domain_id>/<zid>/0/11/SC/%/<mangled_ns>/<node_name>/<mangled_service>/<type>/<hash>/<qos>
        assert!(keyexpr.as_str().starts_with("@ros2_lv/0/"));
        assert!(keyexpr.as_str().contains("/0/11/SC/%/%/"));
        assert!(keyexpr.as_str().contains("/my_node/"));
        assert!(keyexpr.as_str().contains("%add_two_ints/"));
    }

    // ------------------------------------------------------------------------
    // Data KeyExpr Format Tests
    // ------------------------------------------------------------------------

    #[test]
    fn test_topic_info_to_key_humble() {
        let topic = TopicInfo::new(
            "/chatter",
            "std_msgs::msg::dds_::Int32_",
            "TypeHashNotSupported",
        );

        let key: heapless::String<128> = topic.to_key();
        // Format: <domain_id>/<topic_name>/<type_name>/<type_hash>
        assert_eq!(
            key.as_str(),
            "0/chatter/std_msgs::msg::dds_::Int32_/TypeHashNotSupported"
        );
    }

    #[test]
    fn test_topic_info_to_key_wildcard() {
        let topic = TopicInfo::new(
            "/chatter",
            "std_msgs::msg::dds_::Int32_",
            "TypeHashNotSupported",
        );

        let key: heapless::String<128> = topic.to_key_wildcard();
        // Format: <domain_id>/<topic_name>/<type_name>/*
        assert_eq!(key.as_str(), "0/chatter/std_msgs::msg::dds_::Int32_/*");
    }

    // ------------------------------------------------------------------------
    // Service KeyExpr Format Tests
    // ------------------------------------------------------------------------

    #[test]
    fn test_service_info_format() {
        let service = ServiceInfo::new(
            "/add_two_ints",
            "example_interfaces::srv::dds_::AddTwoInts",
            "TypeHashNotSupported",
        );

        // Verify service info fields are correct
        assert_eq!(service.name, "/add_two_ints");
        assert_eq!(
            service.type_name,
            "example_interfaces::srv::dds_::AddTwoInts"
        );
        assert_eq!(service.domain_id, 0);
    }

    // ------------------------------------------------------------------------
    // QoS String Encoding Tests
    // ------------------------------------------------------------------------

    #[test]
    fn test_qos_best_effort_volatile() {
        // BEST_EFFORT reliability (2), VOLATILE durability (2), KEEP_LAST history with depth 1
        let qos = "2:2:1,1:,:,:,,";
        assert!(qos.starts_with("2:")); // BEST_EFFORT
        assert!(qos.contains(":2:")); // VOLATILE
    }

    #[test]
    fn test_qos_reliable_transient_local() {
        // RELIABLE reliability (1), TRANSIENT_LOCAL durability (1)
        let qos = "1:1:1,1:,:,:,,";
        assert!(qos.starts_with("1:")); // RELIABLE
    }

    // ------------------------------------------------------------------------
    // ZenohId Format Tests
    // ------------------------------------------------------------------------

    #[test]
    fn test_zenoh_id_to_hex_lsb_first() {
        // Test that ZenohId is formatted in LSB-first order
        let zid = ZenohId::from_bytes([
            0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e,
            0x0f, 0x10,
        ]);
        let mut buf = [0u8; ZID_HEX_SIZE];
        zid.to_hex_bytes(&mut buf);
        let hex = core::str::from_utf8(&buf).unwrap();

        // LSB-first: byte 15 first, byte 0 last
        assert_eq!(hex, "100f0e0d0c0b0a090807060504030201");
    }
}

// =============================================================================
// Ghost model validation
// =============================================================================

#[cfg(test)]
mod ghost_checks {
    use super::*;
    use nros_ghost_types::{ServiceBufferGhost, SubscriberBufferGhost};
    use service::ServiceBuffer;
    use subscriber::SubscriberBuffer;

    /// Structural check: construct SubscriberBufferGhost from SubscriberBuffer private fields.
    /// If a field is renamed or retyped, this fails to compile.
    fn ghost_from_buffer(b: &SubscriberBuffer) -> SubscriberBufferGhost {
        SubscriberBufferGhost {
            has_data: b.has_data.load(Ordering::Relaxed),
            overflow: b.overflow.load(Ordering::Relaxed),
            locked: b.locked.load(Ordering::Relaxed),
            stored_len: b.len.load(Ordering::Relaxed),
            buf_capacity: b.data.len(),
        }
    }

    #[test]
    fn ghost_new_state() {
        let buffer = SubscriberBuffer::new();
        let ghost = ghost_from_buffer(&buffer);
        assert!(!ghost.has_data);
        assert!(!ghost.overflow);
        assert!(!ghost.locked);
        assert_eq!(ghost.stored_len, 0);
        assert_eq!(ghost.buf_capacity, SUBSCRIBER_BUFFER_SIZE);
    }

    #[test]
    fn ghost_capacity_constant() {
        let buffer = SubscriberBuffer::new();
        let ghost = ghost_from_buffer(&buffer);
        assert_eq!(ghost.buf_capacity, SUBSCRIBER_BUFFER_SIZE);
    }

    // ========================================================================
    // ServiceBufferGhost Correspondence
    // ========================================================================

    /// Structural check: construct ServiceBufferGhost from ServiceBuffer private fields.
    /// If a field is renamed or retyped, this fails to compile.
    fn ghost_from_service_buffer(b: &ServiceBuffer) -> ServiceBufferGhost {
        ServiceBufferGhost {
            has_request: b.has_request.load(Ordering::Relaxed),
            overflow: b.overflow.load(Ordering::Relaxed),
            stored_len: b.len.load(Ordering::Relaxed),
            buf_capacity: b.data.len(),
        }
    }

    #[test]
    fn ghost_service_new_state() {
        let buffer = ServiceBuffer::new();
        let ghost = ghost_from_service_buffer(&buffer);
        assert!(!ghost.has_request);
        assert!(!ghost.overflow);
        assert_eq!(ghost.stored_len, 0);
        assert_eq!(ghost.buf_capacity, SERVICE_BUFFER_SIZE);
    }

    #[test]
    fn ghost_service_capacity_constant() {
        let buffer = ServiceBuffer::new();
        let ghost = ghost_from_service_buffer(&buffer);
        assert_eq!(ghost.buf_capacity, SERVICE_BUFFER_SIZE);
    }

    #[test]
    fn svc_buf_overflow_signals_error() {
        let buffer = ServiceBuffer::new();
        // Simulate the callback detecting an oversized request
        buffer.overflow.store(true, Ordering::Release);
        buffer.has_request.store(true, Ordering::Release);

        let ghost = ghost_from_service_buffer(&buffer);
        assert!(ghost.has_request);
        assert!(ghost.overflow);
    }

    // ========================================================================
    // E2E Safety Protocol Unit Tests
    // ========================================================================

    /// Helper: build a valid 37-byte safety attachment from seq, timestamp, and payload CRC.
    #[cfg(feature = "safety-e2e")]
    fn build_safety_attachment(
        seq: i64,
        ts: i64,
        payload: &[u8],
    ) -> [u8; RMW_ATTACHMENT_SIZE_WITH_CRC] {
        let crc = nros_rmw::crc32(payload);
        let mut att = [0u8; RMW_ATTACHMENT_SIZE_WITH_CRC];
        att[0..8].copy_from_slice(&seq.to_le_bytes());
        att[8..16].copy_from_slice(&ts.to_le_bytes());
        att[16] = RMW_GID_SIZE as u8; // VLE GID length
        // GID bytes 17..33 left as zero
        att[RMW_ATTACHMENT_SIZE..RMW_ATTACHMENT_SIZE_WITH_CRC].copy_from_slice(&crc.to_le_bytes());
        att
    }

    /// Helper: parse attachment bytes and validate CRC against payload.
    ///
    /// This mirrors the logic in `try_recv_validated()` but is testable
    /// without creating a full `ZenohSubscriber` (which requires a zenoh session).
    #[cfg(feature = "safety-e2e")]
    fn validate_from_buffers(
        payload: &[u8],
        attachment: &[u8],
        validator: &mut nros_rmw::SafetyValidator,
    ) -> nros_rmw::IntegrityStatus {
        let (message_seq, crc_valid) = if attachment.len() >= RMW_ATTACHMENT_SIZE {
            let seq = i64::from_le_bytes([
                attachment[0],
                attachment[1],
                attachment[2],
                attachment[3],
                attachment[4],
                attachment[5],
                attachment[6],
                attachment[7],
            ]);

            let crc_result = if attachment.len() >= RMW_ATTACHMENT_SIZE + SAFETY_CRC_SIZE {
                let received_crc = u32::from_le_bytes([
                    attachment[RMW_ATTACHMENT_SIZE],
                    attachment[RMW_ATTACHMENT_SIZE + 1],
                    attachment[RMW_ATTACHMENT_SIZE + 2],
                    attachment[RMW_ATTACHMENT_SIZE + 3],
                ]);
                let computed_crc = nros_rmw::crc32(payload);
                Some(received_crc == computed_crc)
            } else {
                None
            };

            (seq, crc_result)
        } else {
            (0, None)
        };

        validator.validate(message_seq, crc_valid)
    }

    #[cfg(feature = "safety-e2e")]
    #[test]
    fn test_safety_validate_happy_path() {
        let payload = b"\x00\x01\x00\x00\x2a\x00\x00\x00"; // CDR-encoded Int32(42)
        let attachment = build_safety_attachment(0, 1000, payload);

        let mut validator = nros_rmw::SafetyValidator::new();
        let status = validate_from_buffers(payload, &attachment, &mut validator);

        assert!(status.is_valid());
        assert_eq!(status.crc_valid, Some(true));
        assert_eq!(status.gap, 0);
        assert!(!status.duplicate);
    }

    #[cfg(feature = "safety-e2e")]
    #[test]
    fn test_safety_validate_sequential_messages() {
        let mut validator = nros_rmw::SafetyValidator::new();

        for seq in 0..10i64 {
            let payload = seq.to_le_bytes();
            let attachment = build_safety_attachment(seq, seq * 1000, &payload);
            let status = validate_from_buffers(&payload, &attachment, &mut validator);

            assert!(status.is_valid(), "failed at seq {}: {:?}", seq, status);
            assert_eq!(status.gap, 0);
            assert!(!status.duplicate);
            assert_eq!(status.crc_valid, Some(true));
        }
    }

    #[cfg(feature = "safety-e2e")]
    #[test]
    fn test_safety_validate_tampered_crc() {
        let payload = b"hello world CDR data";
        let mut attachment = build_safety_attachment(0, 1000, payload);

        // Tamper with the CRC (flip a bit)
        attachment[RMW_ATTACHMENT_SIZE] ^= 0x01;

        let mut validator = nros_rmw::SafetyValidator::new();
        let status = validate_from_buffers(payload, &attachment, &mut validator);

        assert!(!status.is_valid());
        assert_eq!(status.crc_valid, Some(false));
    }

    #[cfg(feature = "safety-e2e")]
    #[test]
    fn test_safety_validate_tampered_payload() {
        let payload = b"original payload data";
        let attachment = build_safety_attachment(0, 1000, payload);

        // Tamper with the payload (simulating transport corruption)
        let mut tampered_payload = *payload;
        tampered_payload[0] ^= 0xFF;

        let mut validator = nros_rmw::SafetyValidator::new();
        let status = validate_from_buffers(&tampered_payload, &attachment, &mut validator);

        assert!(!status.is_valid());
        assert_eq!(status.crc_valid, Some(false));
    }

    #[cfg(feature = "safety-e2e")]
    #[test]
    fn test_safety_validate_sequence_gap() {
        let mut validator = nros_rmw::SafetyValidator::new();

        // First message: seq 0
        let payload0 = b"msg0";
        let att0 = build_safety_attachment(0, 0, payload0);
        let status = validate_from_buffers(payload0, &att0, &mut validator);
        assert!(status.is_valid());

        // seq 1
        let payload1 = b"msg1";
        let att1 = build_safety_attachment(1, 1000, payload1);
        let status = validate_from_buffers(payload1, &att1, &mut validator);
        assert!(status.is_valid());

        // Skip to seq 5 (gap of 3)
        let payload5 = b"msg5";
        let att5 = build_safety_attachment(5, 5000, payload5);
        let status = validate_from_buffers(payload5, &att5, &mut validator);

        assert!(!status.is_valid());
        assert_eq!(status.gap, 3);
        assert!(!status.duplicate);
        assert_eq!(status.crc_valid, Some(true));
    }

    #[cfg(feature = "safety-e2e")]
    #[test]
    fn test_safety_validate_duplicate() {
        let mut validator = nros_rmw::SafetyValidator::new();

        // seq 0, 1, 2
        for seq in 0..3i64 {
            let payload = seq.to_le_bytes();
            let att = build_safety_attachment(seq, seq * 1000, &payload);
            validate_from_buffers(&payload, &att, &mut validator);
        }

        // Receive seq 1 again (duplicate)
        let payload1 = 1i64.to_le_bytes();
        let att1 = build_safety_attachment(1, 1000, &payload1);
        let status = validate_from_buffers(&payload1, &att1, &mut validator);

        assert!(!status.is_valid());
        assert!(status.duplicate);
        assert_eq!(status.crc_valid, Some(true));
    }

    #[cfg(feature = "safety-e2e")]
    #[test]
    fn test_safety_validate_no_crc_interop() {
        // Simulate a 33-byte attachment (sender without safety-e2e)
        let payload = b"some data";
        let mut attachment = [0u8; RMW_ATTACHMENT_SIZE]; // Only 33 bytes, no CRC
        attachment[0..8].copy_from_slice(&0i64.to_le_bytes());
        attachment[8..16].copy_from_slice(&1000i64.to_le_bytes());
        attachment[16] = RMW_GID_SIZE as u8;

        let mut validator = nros_rmw::SafetyValidator::new();
        let status = validate_from_buffers(payload, &attachment, &mut validator);

        assert!(status.is_valid()); // No CRC is acceptable (interop)
        assert_eq!(status.crc_valid, None);
    }

    #[cfg(feature = "safety-e2e")]
    #[test]
    fn test_safety_attachment_format() {
        let payload = b"test payload for CRC";
        let expected_crc = nros_rmw::crc32(payload);

        let attachment = build_safety_attachment(42, 999999, payload);

        // Verify format: 37 bytes total
        assert_eq!(attachment.len(), 37);

        // Bytes 0..8: sequence number (LE)
        assert_eq!(i64::from_le_bytes(attachment[0..8].try_into().unwrap()), 42);

        // Bytes 8..16: timestamp (LE)
        assert_eq!(
            i64::from_le_bytes(attachment[8..16].try_into().unwrap()),
            999999
        );

        // Byte 16: GID VLE length
        assert_eq!(attachment[16], 16);

        // Bytes 33..37: CRC-32 of payload (LE)
        let crc = u32::from_le_bytes(attachment[33..37].try_into().unwrap());
        assert_eq!(crc, expected_crc);
    }

    // ========================================================================
    // 37.1a: Cross-buffer interaction tests
    // ========================================================================

    #[test]
    fn sub_svc_independent() {
        use service::tests::{reset_service_buffer, simulate_service_request, try_recv_service};
        use subscriber::tests::{
            reset_subscriber_buffer, simulate_subscription_callback, try_recv_subscription,
        };

        // Use slot 2 — subscription array and service array are separate
        let slot = 2;
        reset_subscriber_buffer(slot);
        reset_service_buffer(slot);

        simulate_subscription_callback(slot, b"sub_data");
        simulate_service_request(slot, b"svc_data", b"svc/x");

        let mut recv_buf = [0u8; 1024];
        let sub_result = try_recv_subscription(slot, &mut recv_buf);
        assert!(matches!(sub_result, Ok(Some(8))));
        assert_eq!(&recv_buf[..8], b"sub_data");

        let svc_result = try_recv_service(slot, &mut recv_buf);
        assert!(matches!(svc_result, Ok(Some(8))));
        assert_eq!(&recv_buf[..8], b"svc_data");
    }

    #[test]
    fn sub_overflow_does_not_affect_svc() {
        use service::tests::{reset_service_buffer, simulate_service_request, try_recv_service};
        use subscriber::tests::{
            reset_subscriber_buffer, simulate_subscription_callback, try_recv_subscription,
        };

        let slot = 3;
        reset_subscriber_buffer(slot);
        reset_service_buffer(slot);

        // Subscription overflow
        simulate_subscription_callback(slot, &[0u8; 2000]);
        // Service normal request
        simulate_service_request(slot, b"svc_ok", b"svc/x");

        // Subscription has overflow error
        let mut recv_buf = [0u8; 1024];
        let sub_result = try_recv_subscription(slot, &mut recv_buf);
        assert!(matches!(sub_result, Err(TransportError::MessageTooLarge)));

        // Service buffer unaffected
        let svc_result = try_recv_service(slot, &mut recv_buf);
        assert!(matches!(svc_result, Ok(Some(6))));
        assert_eq!(&recv_buf[..6], b"svc_ok");
    }
}
