meta:
  version: 1
  inputs:
  - path: launch/system.launch.xml
    sha256: d24b6872b91b79ac228a6d2afc1bad01f0c100783baef69e4e136cce6fa5551d
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
structure:
  scopes:
    system.launch.xml:
      file: system.launch.xml
