use core::ffi::{c_char, c_ulong, c_void};

use nros_platform::{
    ConcretePlatform, PlatformAlloc, PlatformClock, PlatformRandom, PlatformSleep,
    PlatformThreading, PlatformTime,
};
// The four network traits live at the parent scope so the inner
// `mod net_*` submodules can reach them via `use super::{…}`. They
// are only USED inside those submodules, all of which are
// `#[cfg(feature = "network")]`, so the imports themselves must be
// gated too — otherwise the compiler warns on unused imports when
// `network` is disabled.
#[cfg(feature = "network")]
use nros_platform::{PlatformSocketHelpers, PlatformTcp, PlatformUdp, PlatformUdpMulticast};

type P = ConcretePlatform;

// ============================================================================
// Network type sizes (auto-detected from C headers at build time)
// ============================================================================

/// Sizes of `_z_sys_net_socket_t` and `_z_sys_net_endpoint_t` for the target
/// platform. Generated by build.rs from DEP_ZPICO_SOCKET_SIZE / ENDPOINT_SIZE,
/// which zpico-sys's size probe derives from the C headers.
mod net_sizes {
    include!(concat!(env!("OUT_DIR"), "/platform_net_sizes.rs"));
}

/// Opaque wrapper matching `_z_sys_net_socket_t` size for the target platform.
/// Used in pass-by-value `extern "C"` functions (_z_read_tcp, _z_send_tcp, etc.)
///
/// Size is auto-probed from C headers. `repr(C)` with `[u8; N]` ensures the
/// Rust type has exactly the same size as the C struct for correct ABI when
/// passed by value across the `extern "C"` boundary.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct ZSysNetSocket {
    _opaque: [u8; net_sizes::NET_SOCKET_SIZE],
}

/// Opaque wrapper matching `_z_sys_net_endpoint_t` size for the target platform.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct ZSysNetEndpoint {
    _opaque: [u8; net_sizes::NET_ENDPOINT_SIZE],
}

// ============================================================================
// Clock
// ============================================================================

#[cfg(not(feature = "skip-clock-symbols"))]
#[unsafe(no_mangle)]
pub extern "C" fn z_clock_now() -> usize {
    <P as PlatformClock>::clock_ms() as usize
}

#[cfg(not(feature = "skip-clock-symbols"))]
#[unsafe(no_mangle)]
pub extern "C" fn z_clock_elapsed_us(time: *const usize) -> c_ulong {
    let prev = unsafe { *time } as u64;
    let now = <P as PlatformClock>::clock_ms();
    (now.wrapping_sub(prev) * 1000) as c_ulong
}

#[cfg(not(feature = "skip-clock-symbols"))]
#[unsafe(no_mangle)]
pub extern "C" fn z_clock_elapsed_ms(time: *const usize) -> c_ulong {
    let prev = unsafe { *time } as u64;
    let now = <P as PlatformClock>::clock_ms();
    now.wrapping_sub(prev) as c_ulong
}

#[cfg(not(feature = "skip-clock-symbols"))]
#[unsafe(no_mangle)]
pub extern "C" fn z_clock_elapsed_s(time: *const usize) -> c_ulong {
    let prev = unsafe { *time } as u64;
    let now = <P as PlatformClock>::clock_ms();
    (now.wrapping_sub(prev) / 1000) as c_ulong
}

#[cfg(not(feature = "skip-clock-symbols"))]
#[unsafe(no_mangle)]
pub extern "C" fn z_clock_advance_us(clock: *mut usize, duration: c_ulong) {
    unsafe {
        *clock = (*clock).wrapping_add((duration as usize) / 1000);
    }
}

#[cfg(not(feature = "skip-clock-symbols"))]
#[unsafe(no_mangle)]
pub extern "C" fn z_clock_advance_ms(clock: *mut usize, duration: c_ulong) {
    unsafe {
        *clock = (*clock).wrapping_add(duration as usize);
    }
}

#[cfg(not(feature = "skip-clock-symbols"))]
#[unsafe(no_mangle)]
pub extern "C" fn z_clock_advance_s(clock: *mut usize, duration: c_ulong) {
    unsafe {
        *clock = (*clock).wrapping_add((duration as usize) * 1000);
    }
}

// ============================================================================
// smoltcp bridge symbols (bare-metal only — called from zpico.c)
// smoltcp_clock_now_ms is always needed (nros-smoltcp links against it).
// smoltcp_init/cleanup/poll are only needed when ZPICO_SMOLTCP is defined.
#[unsafe(no_mangle)]
pub extern "C" fn smoltcp_clock_now_ms() -> u64 {
    <P as PlatformClock>::clock_ms()
}

// ============================================================================
// Memory

#[unsafe(no_mangle)]
pub extern "C" fn z_malloc(size: usize) -> *mut c_void {
    <P as PlatformAlloc>::alloc(size)
}

#[unsafe(no_mangle)]
pub extern "C" fn z_realloc(ptr: *mut c_void, size: usize) -> *mut c_void {
    <P as PlatformAlloc>::realloc(ptr, size)
}

#[unsafe(no_mangle)]
pub extern "C" fn z_free(ptr: *mut c_void) {
    <P as PlatformAlloc>::dealloc(ptr)
}

// ============================================================================
// Sleep
// ============================================================================

#[unsafe(no_mangle)]
pub extern "C" fn z_sleep_us(time: usize) -> i8 {
    <P as PlatformSleep>::sleep_us(time);
    0
}

#[unsafe(no_mangle)]
pub extern "C" fn z_sleep_ms(time: usize) -> i8 {
    <P as PlatformSleep>::sleep_ms(time);
    0
}

#[unsafe(no_mangle)]
pub extern "C" fn z_sleep_s(time: usize) -> i8 {
    <P as PlatformSleep>::sleep_s(time);
    0
}

// ============================================================================
// Random
// ============================================================================

#[unsafe(no_mangle)]
pub extern "C" fn z_random_u8() -> u8 {
    <P as PlatformRandom>::random_u8()
}

#[unsafe(no_mangle)]
pub extern "C" fn z_random_u16() -> u16 {
    <P as PlatformRandom>::random_u16()
}

#[unsafe(no_mangle)]
pub extern "C" fn z_random_u32() -> u32 {
    <P as PlatformRandom>::random_u32()
}

#[unsafe(no_mangle)]
pub extern "C" fn z_random_u64() -> u64 {
    <P as PlatformRandom>::random_u64()
}

#[unsafe(no_mangle)]
pub extern "C" fn z_random_fill(buf: *mut c_void, len: usize) {
    <P as PlatformRandom>::random_fill(buf, len)
}

// ============================================================================
// Time (wall clock)
// ============================================================================

#[repr(C)]
pub struct ZTimeSinceEpoch {
    pub secs: u32,
    pub nanos: u32,
}

#[unsafe(no_mangle)]
pub extern "C" fn z_time_now() -> u64 {
    <P as PlatformTime>::time_now_ms()
}

#[unsafe(no_mangle)]
pub extern "C" fn z_time_now_as_str(buf: *mut c_char, _buflen: c_ulong) -> *const c_char {
    // Minimal stub — write "0" into the buffer
    if !buf.is_null() {
        unsafe {
            *buf = b'0' as c_char;
            *buf.add(1) = 0;
        }
    }
    buf as *const c_char
}

#[unsafe(no_mangle)]
pub extern "C" fn z_time_elapsed_us(time: *const u64) -> c_ulong {
    let prev = unsafe { *time };
    let now = <P as PlatformTime>::time_now_ms();
    (now.wrapping_sub(prev) * 1000) as c_ulong
}

#[unsafe(no_mangle)]
pub extern "C" fn z_time_elapsed_ms(time: *const u64) -> c_ulong {
    let prev = unsafe { *time };
    let now = <P as PlatformTime>::time_now_ms();
    now.wrapping_sub(prev) as c_ulong
}

#[unsafe(no_mangle)]
pub extern "C" fn z_time_elapsed_s(time: *const u64) -> c_ulong {
    let prev = unsafe { *time };
    let now = <P as PlatformTime>::time_now_ms();
    (now.wrapping_sub(prev) / 1000) as c_ulong
}

#[unsafe(no_mangle)]
pub extern "C" fn _z_get_time_since_epoch(t: *mut ZTimeSinceEpoch) -> i8 {
    unsafe {
        (*t).secs = <P as PlatformTime>::time_since_epoch_secs();
        (*t).nanos = <P as PlatformTime>::time_since_epoch_nanos();
    }
    0
}

// ============================================================================
// Threading — tasks
// ============================================================================

// Opaque types matching zenoh-pico's expectations.
// The actual layout is defined by the platform backend.
//
// `ZTask`/`ZTaskAttr` are only referenced by the `_z_task_*` shim functions
// below, which are compiled out under `skip-task-symbols` (ThreadX provides
// its own task.c). Gate the structs with the same cfg so they don't trip
// dead_code when tasks are supplied by C.
#[cfg(not(feature = "skip-task-symbols"))]
#[repr(C)]
pub struct ZTask {
    _opaque: [u8; 64],
}

#[cfg(not(feature = "skip-task-symbols"))]
#[repr(C)]
pub struct ZTaskAttr {
    _opaque: [u8; 64],
}

#[repr(C)]
pub struct ZMutex {
    _opaque: [u8; 64],
}

#[repr(C)]
pub struct ZMutexRec {
    _opaque: [u8; 64],
}

#[repr(C)]
pub struct ZCondvar {
    _opaque: [u8; 64],
}

// Task symbols are skipped for ThreadX — provided by C task.c instead,
// because _z_task_t struct layout (TX_THREAD + embedded stack) is needed
// for tx_thread_create() and the trampoline.
#[cfg(not(feature = "skip-task-symbols"))]
#[unsafe(no_mangle)]
pub extern "C" fn _z_task_init(
    task: *mut ZTask,
    attr: *mut ZTaskAttr,
    fun: Option<unsafe extern "C" fn(*mut c_void) -> *mut c_void>,
    arg: *mut c_void,
) -> i8 {
    <P as PlatformThreading>::task_init(task as *mut c_void, attr as *mut c_void, fun, arg)
}

#[cfg(not(feature = "skip-task-symbols"))]
#[unsafe(no_mangle)]
pub extern "C" fn _z_task_join(task: *mut ZTask) -> i8 {
    <P as PlatformThreading>::task_join(task as *mut c_void)
}

#[cfg(not(feature = "skip-task-symbols"))]
#[unsafe(no_mangle)]
pub extern "C" fn _z_task_detach(task: *mut ZTask) -> i8 {
    <P as PlatformThreading>::task_detach(task as *mut c_void)
}

#[cfg(not(feature = "skip-task-symbols"))]
#[unsafe(no_mangle)]
pub extern "C" fn _z_task_cancel(task: *mut ZTask) -> i8 {
    <P as PlatformThreading>::task_cancel(task as *mut c_void)
}

#[cfg(not(feature = "skip-task-symbols"))]
#[unsafe(no_mangle)]
pub extern "C" fn _z_task_exit() {
    <P as PlatformThreading>::task_exit()
}

#[cfg(not(feature = "skip-task-symbols"))]
#[unsafe(no_mangle)]
pub extern "C" fn _z_task_free(task: *mut *mut ZTask) {
    <P as PlatformThreading>::task_free(task as *mut *mut c_void)
}

// ============================================================================
// Threading — mutex
// ============================================================================

#[unsafe(no_mangle)]
pub extern "C" fn _z_mutex_init(m: *mut ZMutex) -> i8 {
    <P as PlatformThreading>::mutex_init(m as *mut c_void)
}

#[unsafe(no_mangle)]
pub extern "C" fn _z_mutex_drop(m: *mut ZMutex) -> i8 {
    <P as PlatformThreading>::mutex_drop(m as *mut c_void)
}

#[unsafe(no_mangle)]
pub extern "C" fn _z_mutex_lock(m: *mut ZMutex) -> i8 {
    <P as PlatformThreading>::mutex_lock(m as *mut c_void)
}

#[unsafe(no_mangle)]
pub extern "C" fn _z_mutex_try_lock(m: *mut ZMutex) -> i8 {
    <P as PlatformThreading>::mutex_try_lock(m as *mut c_void)
}

#[unsafe(no_mangle)]
pub extern "C" fn _z_mutex_unlock(m: *mut ZMutex) -> i8 {
    <P as PlatformThreading>::mutex_unlock(m as *mut c_void)
}

// ============================================================================
// Threading — recursive mutex
// ============================================================================

#[unsafe(no_mangle)]
pub extern "C" fn _z_mutex_rec_init(m: *mut ZMutexRec) -> i8 {
    <P as PlatformThreading>::mutex_rec_init(m as *mut c_void)
}

#[unsafe(no_mangle)]
pub extern "C" fn _z_mutex_rec_drop(m: *mut ZMutexRec) -> i8 {
    <P as PlatformThreading>::mutex_rec_drop(m as *mut c_void)
}

#[unsafe(no_mangle)]
pub extern "C" fn _z_mutex_rec_lock(m: *mut ZMutexRec) -> i8 {
    <P as PlatformThreading>::mutex_rec_lock(m as *mut c_void)
}

#[unsafe(no_mangle)]
pub extern "C" fn _z_mutex_rec_try_lock(m: *mut ZMutexRec) -> i8 {
    <P as PlatformThreading>::mutex_rec_try_lock(m as *mut c_void)
}

#[unsafe(no_mangle)]
pub extern "C" fn _z_mutex_rec_unlock(m: *mut ZMutexRec) -> i8 {
    <P as PlatformThreading>::mutex_rec_unlock(m as *mut c_void)
}

// ============================================================================
// Threading — condition variables
// ============================================================================

#[unsafe(no_mangle)]
pub extern "C" fn _z_condvar_init(cv: *mut ZCondvar) -> i8 {
    <P as PlatformThreading>::condvar_init(cv as *mut c_void)
}

#[unsafe(no_mangle)]
pub extern "C" fn _z_condvar_drop(cv: *mut ZCondvar) -> i8 {
    <P as PlatformThreading>::condvar_drop(cv as *mut c_void)
}

#[unsafe(no_mangle)]
pub extern "C" fn _z_condvar_signal(cv: *mut ZCondvar) -> i8 {
    <P as PlatformThreading>::condvar_signal(cv as *mut c_void)
}

#[unsafe(no_mangle)]
pub extern "C" fn _z_condvar_signal_all(cv: *mut ZCondvar) -> i8 {
    <P as PlatformThreading>::condvar_signal_all(cv as *mut c_void)
}

#[unsafe(no_mangle)]
pub extern "C" fn _z_condvar_wait(cv: *mut ZCondvar, m: *mut ZMutex) -> i8 {
    <P as PlatformThreading>::condvar_wait(cv as *mut c_void, m as *mut c_void)
}

#[unsafe(no_mangle)]
pub extern "C" fn _z_condvar_wait_until(
    cv: *mut ZCondvar,
    m: *mut ZMutex,
    abstime: *const usize, // z_clock_t = TickType_t (u32) on FreeRTOS, void* on bare-metal
) -> i8 {
    let t = unsafe { *abstime } as u64;
    <P as PlatformThreading>::condvar_wait_until(cv as *mut c_void, m as *mut c_void, t)
}

// (socket_stubs module removed — replaced by `network` feature forwarders)

// ============================================================================
// Networking — TCP forwarders (Phase 80)
// ============================================================================
//
// These forward zenoh-pico's _z_*_tcp() C calls to PlatformTcp trait methods
// via ConcretePlatform. Gated on the `network` feature — only active when a
// platform provides PlatformTcp/PlatformUdp implementations.

#[cfg(feature = "network")]
mod net_tcp {
    use super::{P, PlatformTcp, ZSysNetEndpoint, ZSysNetSocket, c_void};

    #[unsafe(no_mangle)]
    pub extern "C" fn _z_create_endpoint_tcp(
        ep: *mut ZSysNetEndpoint,
        s_address: *const u8,
        s_port: *const u8,
    ) -> i8 {
        <P as PlatformTcp>::create_endpoint(ep as *mut c_void, s_address, s_port)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn _z_free_endpoint_tcp(ep: *mut ZSysNetEndpoint) {
        <P as PlatformTcp>::free_endpoint(ep as *mut c_void);
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn _z_open_tcp(sock: *mut ZSysNetSocket, rep: ZSysNetEndpoint, tout: u32) -> i8 {
        <P as PlatformTcp>::open(
            sock as *mut c_void,
            &rep as *const ZSysNetEndpoint as *const c_void,
            tout,
        )
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn _z_listen_tcp(sock: *mut ZSysNetSocket, rep: ZSysNetEndpoint) -> i8 {
        <P as PlatformTcp>::listen(
            sock as *mut c_void,
            &rep as *const ZSysNetEndpoint as *const c_void,
        )
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn _z_close_tcp(sock: *mut ZSysNetSocket) {
        <P as PlatformTcp>::close(sock as *mut c_void);
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn _z_read_tcp(sock: ZSysNetSocket, ptr: *mut u8, len: usize) -> usize {
        <P as PlatformTcp>::read(&sock as *const ZSysNetSocket as *const c_void, ptr, len)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn _z_read_exact_tcp(sock: ZSysNetSocket, ptr: *mut u8, len: usize) -> usize {
        <P as PlatformTcp>::read_exact(&sock as *const ZSysNetSocket as *const c_void, ptr, len)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn _z_send_tcp(sock: ZSysNetSocket, ptr: *const u8, len: usize) -> usize {
        <P as PlatformTcp>::send(&sock as *const ZSysNetSocket as *const c_void, ptr, len)
    }
}

#[cfg(feature = "network")]
mod net_udp {
    use super::{P, PlatformUdp, ZSysNetEndpoint, ZSysNetSocket, c_void};

    #[unsafe(no_mangle)]
    pub extern "C" fn _z_create_endpoint_udp(
        ep: *mut ZSysNetEndpoint,
        s_address: *const u8,
        s_port: *const u8,
    ) -> i8 {
        <P as PlatformUdp>::create_endpoint(ep as *mut c_void, s_address, s_port)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn _z_free_endpoint_udp(ep: *mut ZSysNetEndpoint) {
        <P as PlatformUdp>::free_endpoint(ep as *mut c_void);
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn _z_open_udp_unicast(
        sock: *mut ZSysNetSocket,
        rep: ZSysNetEndpoint,
        tout: u32,
    ) -> i8 {
        <P as PlatformUdp>::open(
            sock as *mut c_void,
            &rep as *const ZSysNetEndpoint as *const c_void,
            tout,
        )
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn _z_listen_udp_unicast(
        _sock: *mut ZSysNetSocket,
        _rep: ZSysNetEndpoint,
        _tout: u32,
    ) -> i8 {
        // Permanent fallback while platforms use inherent-method
        // dispatch. `PlatformUdp::listen` defaults to -1; when Phase
        // 84.F4 migrates platforms to trait dispatch, this shim can
        // forward to `P::listen(...)` and platforms that override
        // it will take effect automatically.
        -1
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn _z_close_udp_unicast(sock: *mut ZSysNetSocket) {
        <P as PlatformUdp>::close(sock as *mut c_void);
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn _z_read_udp_unicast(sock: ZSysNetSocket, ptr: *mut u8, len: usize) -> usize {
        <P as PlatformUdp>::read(&sock as *const ZSysNetSocket as *const c_void, ptr, len)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn _z_read_exact_udp_unicast(
        sock: ZSysNetSocket,
        ptr: *mut u8,
        len: usize,
    ) -> usize {
        <P as PlatformUdp>::read_exact(&sock as *const ZSysNetSocket as *const c_void, ptr, len)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn _z_send_udp_unicast(
        sock: ZSysNetSocket,
        ptr: *const u8,
        len: usize,
        rep: ZSysNetEndpoint,
    ) -> usize {
        <P as PlatformUdp>::send(
            &sock as *const ZSysNetSocket as *const c_void,
            ptr,
            len,
            &rep as *const ZSysNetEndpoint as *const c_void,
        )
    }
}

#[cfg(feature = "network")]
mod net_helpers {
    use super::{P, PlatformSocketHelpers, ZMutex, ZSysNetSocket, c_void};

    #[unsafe(no_mangle)]
    pub extern "C" fn _z_socket_set_non_blocking(sock: *const ZSysNetSocket) -> i8 {
        <P as PlatformSocketHelpers>::set_non_blocking(sock as *const c_void)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn _z_socket_accept(
        sock_in: *const ZSysNetSocket,
        sock_out: *mut ZSysNetSocket,
    ) -> i8 {
        <P as PlatformSocketHelpers>::accept(sock_in as *const c_void, sock_out as *mut c_void)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn _z_socket_close(sock: *mut ZSysNetSocket) {
        <P as PlatformSocketHelpers>::close(sock as *mut c_void);
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn _z_socket_wait_event(peers: *mut c_void, mutex: *mut ZMutex) -> i8 {
        <P as PlatformSocketHelpers>::wait_event(peers, mutex as *mut c_void)
    }
}

// ============================================================================
// Serial-build socket fallbacks
// ============================================================================
// Even on serial-only zpico-sys builds, peer.c unconditionally calls
// `_z_socket_close` from `_z_transport_peer_unicast_clear`. The peer's
// `_owns_socket` flag is false on serial transports so the call is a
// no-op at runtime, but the linker still needs the symbol. Provide a
// no-op stub when the `network` feature is off.
#[cfg(all(feature = "active", not(feature = "network")))]
mod net_helpers_stub {
    use super::{ZMutex, ZSysNetSocket, c_void};

    #[unsafe(no_mangle)]
    pub extern "C" fn _z_socket_close(_sock: *mut ZSysNetSocket) {}

    #[unsafe(no_mangle)]
    pub extern "C" fn _z_socket_set_non_blocking(_sock: *const ZSysNetSocket) -> i8 {
        0
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn _z_socket_accept(
        _sock_in: *const ZSysNetSocket,
        _sock_out: *mut ZSysNetSocket,
    ) -> i8 {
        -1
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn _z_socket_wait_event(_peers: *mut c_void, _mutex: *mut ZMutex) -> i8 {
        0
    }
}

// ============================================================================
// Networking — UDP multicast forwarders (Phase 80)
// ============================================================================

#[cfg(feature = "network")]
mod net_mcast {
    use super::{P, PlatformUdpMulticast, ZSysNetEndpoint, ZSysNetSocket, c_void};

    #[unsafe(no_mangle)]
    pub extern "C" fn _z_open_udp_multicast(
        sock: *mut ZSysNetSocket,
        rep: ZSysNetEndpoint,
        lep: *mut ZSysNetEndpoint,
        tout: u32,
        iface: *const u8,
    ) -> i8 {
        <P as PlatformUdpMulticast>::mcast_open(
            sock as *mut c_void,
            &rep as *const ZSysNetEndpoint as *const c_void,
            lep as *mut c_void,
            tout,
            iface,
        )
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn _z_listen_udp_multicast(
        sock: *mut ZSysNetSocket,
        rep: ZSysNetEndpoint,
        tout: u32,
        iface: *const u8,
        join: *const u8,
    ) -> i8 {
        <P as PlatformUdpMulticast>::mcast_listen(
            sock as *mut c_void,
            &rep as *const ZSysNetEndpoint as *const c_void,
            tout,
            iface,
            join,
        )
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn _z_close_udp_multicast(
        sockrecv: *mut ZSysNetSocket,
        socksend: *mut ZSysNetSocket,
        rep: ZSysNetEndpoint,
        lep: ZSysNetEndpoint,
    ) {
        <P as PlatformUdpMulticast>::mcast_close(
            sockrecv as *mut c_void,
            socksend as *mut c_void,
            &rep as *const ZSysNetEndpoint as *const c_void,
            &lep as *const ZSysNetEndpoint as *const c_void,
        );
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn _z_read_udp_multicast(
        sock: ZSysNetSocket,
        ptr: *mut u8,
        len: usize,
        lep: ZSysNetEndpoint,
        addr: *mut c_void, // *mut _z_slice_t
    ) -> usize {
        <P as PlatformUdpMulticast>::mcast_read(
            &sock as *const ZSysNetSocket as *const c_void,
            ptr,
            len,
            &lep as *const ZSysNetEndpoint as *const c_void,
            addr,
        )
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn _z_read_exact_udp_multicast(
        sock: ZSysNetSocket,
        ptr: *mut u8,
        len: usize,
        lep: ZSysNetEndpoint,
        addr: *mut c_void,
    ) -> usize {
        <P as PlatformUdpMulticast>::mcast_read_exact(
            &sock as *const ZSysNetSocket as *const c_void,
            ptr,
            len,
            &lep as *const ZSysNetEndpoint as *const c_void,
            addr,
        )
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn _z_send_udp_multicast(
        sock: ZSysNetSocket,
        ptr: *const u8,
        len: usize,
        rep: ZSysNetEndpoint,
    ) -> usize {
        <P as PlatformUdpMulticast>::mcast_send(
            &sock as *const ZSysNetSocket as *const c_void,
            ptr,
            len,
            &rep as *const ZSysNetEndpoint as *const c_void,
        )
    }
}

// ============================================================================
// smoltcp bridge FFI (bare-metal only — called from zpico.c when ZPICO_SMOLTCP)
// ============================================================================

#[cfg(feature = "network-smoltcp-bridge")]
mod net_smoltcp_bridge {
    unsafe extern "C" {
        fn nros_smoltcp_is_initialized() -> bool;
        fn nros_smoltcp_init();
        fn nros_smoltcp_do_poll() -> i32;
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn smoltcp_init() -> i32 {
        unsafe {
            if nros_smoltcp_is_initialized() {
                return 0;
            }
            nros_smoltcp_init();
        }
        0
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn smoltcp_cleanup() {
        // Static allocations — nothing to clean up
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn smoltcp_poll() -> i32 {
        unsafe { nros_smoltcp_do_poll() }
    }
}
