include = ["../../../../../../nros-patch.toml"]
[patch.crates-io]
nros-board-native = { path = "../../../../boards/nros-board-native" }  # nros-managed
nros-platform = { path = "../../../../core/nros-platform" }  # nros-managed
