# Phase 212.N.7 step-2 — Entry pkg cargo config.

[build]
target = "x86_64-unknown-linux-gnu"

[patch.crates-io]
action_msgs = { path = "generated/action_msgs" }  # nros-managed
builtin_interfaces = { path = "generated/builtin_interfaces" }  # nros-managed
example_interfaces = { path = "generated/example_interfaces" }  # nros-managed
nros = { path = "../../../../packages/core/nros" }  # nros-managed
nros-board-threadx-linux = { path = "../../../../packages/boards/nros-board-threadx-linux" }  # nros-managed
nros-core = { path = "../../../../packages/core/nros-core" }  # nros-managed
nros-platform = { path = "../../../../packages/core/nros-platform" }  # nros-managed
nros-rmw-cyclonedds = { path = "../../../../packages/dds/nros-rmw-cyclonedds" }  # nros-managed
nros-serdes = { path = "../../../../packages/core/nros-serdes" }  # nros-managed
unique_identifier_msgs = { path = "generated/unique_identifier_msgs" }  # nros-managed
