meta:
  version: 1
  inputs:
  - path: launch/c_params.launch.xml
    sha256: be2a10be1da58018f39ff5e8643aa327046d6617cda09e21dcc18ed1e1d6b022
  - path: system.toml
    sha256: 8cbc553de78028b3e8ab479899d416e1b52d8f81f20375abec8fe907793ffb44
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
structure:
  scopes:
    c_params.launch.xml:
      file: c_params.launch.xml
  nodes:
    /param_talker:
      scope: c_params.launch.xml
      pkg: c_param_talker_pkg
      exec: c_param_talker
      lifecycle_autostart: active
      params:
        publish_period_ms: 250
      node_name: param_talker
execution:
  deploy:
    /param_talker:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
  features:
  - param_services
  - lifecycle
