meta:
  version: 1
  inputs:
  - path: launch/cpp_lifecycle.launch.xml
    sha256: a02e15529fa5d83b5a4b8b0eca5c0cc35ab07bf9b18fbb6ae66ff6744ce3c73a
  - path: system.toml
    sha256: 712932b44d84f8bff41a4a0845fa1d263bc26ac631c70b06e5d13a540ebb99c5
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
structure:
  scopes:
    cpp_lifecycle.launch.xml:
      file: cpp_lifecycle.launch.xml
  nodes:
    /talker:
      scope: cpp_lifecycle.launch.xml
      pkg: cpp_lifecycle_talker_pkg
      exec: cpp_talker
      lifecycle_autostart: active
      node_name: talker
execution:
  deploy:
    /talker:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
  features:
  - param_services
  - lifecycle
