meta:
  version: 1
  inputs:
  - path: launch/cpp_custom_msg_talker.launch.xml
    sha256: 6f3cad6628a814c5e82bec1b35c2ebd8c007070d243914fd5838d91c85cb2755
  - path: system.toml
    sha256: a81cc58a561d3118a78cecdef057c2d29bb5261efa3a6cf3b96d8969fd1e13bf
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
structure:
  scopes:
    cpp_custom_msg_talker.launch.xml:
      file: cpp_custom_msg_talker.launch.xml
  nodes:
    /reading_talker:
      scope: cpp_custom_msg_talker.launch.xml
      pkg: cpp_reading_talker_pkg
      exec: cpp_reading_talker
      lifecycle_autostart: active
      node_name: reading_talker
execution:
  deploy:
    /reading_talker:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
  features:
  - param_services
  - lifecycle
