meta:
  version: 1
  inputs:
  - path: launch/cpp_qos_listener.launch.xml
    sha256: 7f10013f0dfdd88feb438bde87770ad486cbdf345cb226d6678b39088bcec3b3
  - path: system.toml
    sha256: a81cc58a561d3118a78cecdef057c2d29bb5261efa3a6cf3b96d8969fd1e13bf
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
structure:
  scopes:
    cpp_qos_listener.launch.xml:
      file: cpp_qos_listener.launch.xml
  nodes:
    /qos_listener:
      scope: cpp_qos_listener.launch.xml
      pkg: cpp_qos_listener_pkg
      exec: cpp_qos_listener
      lifecycle_autostart: active
      node_name: qos_listener
execution:
  deploy:
    /qos_listener:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
  features:
  - param_services
  - lifecycle
