meta:
  version: 1
  inputs:
  - path: launch/mixed_custom_msg_listener.launch.xml
    sha256: 772ec4a50d2996dbe972b31e8228d42d4079125334fa4c1ace28fe2ee21de7d9
  - path: system.toml
    sha256: 98b05fa759c6416f0d191da1891e863b2dca773d66b9114e11306c8ebc7552d1
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
structure:
  scopes:
    mixed_custom_msg_listener.launch.xml:
      file: mixed_custom_msg_listener.launch.xml
  nodes:
    /reading_listener:
      scope: mixed_custom_msg_listener.launch.xml
      pkg: mixed_reading_listener_pkg
      exec: mixed_reading_listener
      lifecycle_autostart: active
      node_name: reading_listener
execution:
  deploy:
    /reading_listener:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
  features:
  - param_services
  - lifecycle
