meta:
  version: 1
  inputs:
  - path: launch/mixed_custom_msg_talker.launch.xml
    sha256: b817da0c4df3600da5f8af00d78586ee49cc8f5f93d186f7ec0ad5c443ca1103
  - path: system.toml
    sha256: 98b05fa759c6416f0d191da1891e863b2dca773d66b9114e11306c8ebc7552d1
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
structure:
  scopes:
    mixed_custom_msg_talker.launch.xml:
      file: mixed_custom_msg_talker.launch.xml
  nodes:
    /reading_talker:
      scope: mixed_custom_msg_talker.launch.xml
      pkg: mixed_reading_talker_pkg
      exec: mixed_reading_talker
      lifecycle_autostart: active
      node_name: reading_talker
execution:
  deploy:
    /reading_talker:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
  features:
  - param_services
  - lifecycle
