meta:
  version: 1
  inputs:
  - path: launch/rust_remap.launch.xml
    sha256: 387c64767f4d9ce328336c8f2f701b92ea02f30f5dc5db3a69b271f69c585326
  - path: system.toml
    sha256: a81cc58a561d3118a78cecdef057c2d29bb5261efa3a6cf3b96d8969fd1e13bf
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
structure:
  scopes:
    rust_remap.launch.xml:
      file: rust_remap.launch.xml
  nodes:
    /island/remap_talker:
      scope: rust_remap.launch.xml
      pkg: rust_remap_talker_pkg
      exec: remap_talker
      lifecycle_autostart: active
      remaps:
      - from: ~/out
        to: /remapped_out
      node_name: remap_talker
execution:
  deploy:
    /island/remap_talker:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
  features:
  - param_services
  - lifecycle
