//! Issue 1009 — keep the DDS interop bus on loopback, for BOTH sides of a pair.
//!
//! # Why
//!
//! Our DDS interop tests discover on whatever multicast the host can reach, so
//! any DDS participant on the LAN is a peer: a colleague's laptop, a robot, a CI
//! runner. Issue 0741 spent fifteen sections and four wrong diagnoses on a
//! 28-byte reply that turned out to belong to a CycloneDDS `add_two_ints_server`
//! on a DIFFERENT HOST, squatting 35 ROS domains. The repro needed none of our
//! code:
//!
//! ```text
//! $ ROS_DOMAIN_ID=1 ros2 service call /add_two_ints \
//!     example_interfaces/srv/AddTwoInts "{a: 5, b: 3}"
//! [RTPS_READER_HISTORY Error] Change payload size of '28' bytes is larger than
//! the history payload size of '15' bytes and cannot be resized.
//! ```
//!
//! # `ROS_LOCALHOST_ONLY=1` IS NOT THE FIX, and that is measured
//!
//! | batch | condition | pass / fail |
//! | --- | --- | ---: |
//! | D | per-run daemon kill, UDP-only profile | 12 / 3 |
//! | F | `ROS_LOCALHOST_ONLY=1` alone | **0 / 15** |
//! | G | Fast-DDS `interfaceWhiteList 127.0.0.1`, BOTH processes | **15 / 15** |
//!
//! Batch F is zero passes with EMPTY client output — no history error at all —
//! because **the XRCE Agent is a bare Fast-DDS application, not a ROS process**,
//! so it ignores `ROS_LOCALHOST_ONLY` and the two sides stop discovering each
//! other. A variable that isolates one half of a pair is worse than none: it
//! turns a wrong answer into no answer.
//!
//! What works is a profile FILE, exported so both the peer and the Agent read
//! it. That is what this module writes and hands out.
//!
//! # Do not combine with `ROS_LOCALHOST_ONLY`
//!
//! A custom `userTransports` profile DEFEATS that variable (the issue's batch E
//! is confounded, 9/6, for exactly this reason). Nothing here sets it, and
//! nothing else should alongside it.

use std::{
    io::Write as _,
    path::{Path, PathBuf},
    sync::OnceLock,
};

/// Escape hatch: leave the bus on the LAN.
///
/// For the one case this isolation cannot serve — a peer that must genuinely
/// reach another host. Deliberately an env var and not a parameter: the callers
/// are ~14 helper functions that all want the same answer, and a parameter
/// threaded through every one of them is a parameter someone passes wrong.
pub fn lan_allowed() -> bool {
    std::env::var_os("NROS_DDS_ALLOW_LAN").is_some()
}

/// Per-process directory holding the generated profiles.
///
/// Per PROCESS, not per repo: two nextest binaries running at once must not
/// write the same file while the other is reading it. The pid makes that
/// impossible without any locking.
fn profile_dir() -> &'static Path {
    static DIR: OnceLock<PathBuf> = OnceLock::new();
    DIR.get_or_init(|| {
        let dir = std::env::temp_dir().join(format!("nros-dds-loopback-{}", std::process::id()));
        let _ = std::fs::create_dir_all(&dir);
        dir
    })
}

/// Write `content` to `<profile_dir>/<name>` once, atomically, and return it.
///
/// Atomic because the Agent may be spawned while a sibling helper is still
/// building its env string, and a half-written profile is a parse error that
/// presents as "no discovery" — the exact symptom this module exists to remove.
fn write_once(name: &str, content: &str) -> PathBuf {
    let path = profile_dir().join(name);
    if path.exists() {
        return path;
    }
    let tmp = path.with_extension("tmp");
    if let Ok(mut f) = std::fs::File::create(&tmp) {
        if f.write_all(content.as_bytes()).is_ok() {
            let _ = f.sync_all();
            let _ = std::fs::rename(&tmp, &path);
        }
    }
    path
}

/// Fast-DDS profile pinning every participant to the loopback interface.
///
/// `useBuiltinTransports=false` matters as much as the whitelist: leaving the
/// builtin transports on adds a second, un-whitelisted UDPv4 descriptor beside
/// this one, and discovery escapes through it.
const FASTDDS_LOOPBACK_XML: &str = r#"<?xml version="1.0" encoding="UTF-8" ?>
<!-- Generated by nros-tests (issue 1009). Do not edit; see dds_isolation.rs. -->
<dds xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
  <profiles>
    <transport_descriptors>
      <transport_descriptor>
        <transport_id>nros_loopback_udp</transport_id>
        <type>UDPv4</type>
        <interfaceWhiteList>
          <address>127.0.0.1</address>
        </interfaceWhiteList>
      </transport_descriptor>
    </transport_descriptors>
    <participant profile_name="nros_loopback" is_default_profile="true">
      <rtps>
        <userTransports>
          <transport_id>nros_loopback_udp</transport_id>
        </userTransports>
        <useBuiltinTransports>false</useBuiltinTransports>
      </rtps>
    </participant>
  </profiles>
</dds>
"#;

/// CycloneDDS equivalent.
///
/// **NOT measured the way the Fast-DDS profile was.** The issue records 15/15
/// for the Fast-DDS side against a live foreign peer and says plainly that the
/// `CYCLONEDDS_URI` equivalent "is not yet written". This is that file, written
/// from Cyclone's documented config, and it has been shown to keep a local pair
/// talking — but never against the poisoned domain, because the 35 orphans on
/// `arm-a100` were cleared before it existed. Treat the isolation as asserted
/// for Cyclone and demonstrated for Fast-DDS.
///
/// `AllowMulticast=false` plus an explicit localhost peer is the pair that does
/// the work: the interface alone still leaves SPDP announcing to a multicast
/// group, and a participant elsewhere on the LAN that announces to the same
/// group is still discovered.
const CYCLONE_LOOPBACK_XML: &str = r#"<?xml version="1.0" encoding="UTF-8" ?>
<!-- Generated by nros-tests (issue 1009). Do not edit; see dds_isolation.rs. -->
<CycloneDDS xmlns="https://cdds.io/config">
  <Domain id="any">
    <General>
      <Interfaces>
        <NetworkInterface address="127.0.0.1" priority="default" multicast="false" />
      </Interfaces>
      <AllowMulticast>false</AllowMulticast>
    </General>
    <Discovery>
      <ParticipantIndex>auto</ParticipantIndex>
      <Peers>
        <Peer address="localhost"/>
      </Peers>
    </Discovery>
  </Domain>
</CycloneDDS>
"#;

/// Path to the generated Fast-DDS loopback profile.
pub fn fastdds_profile_path() -> PathBuf {
    write_once("nros-loopback-fastdds.xml", FASTDDS_LOOPBACK_XML)
}

/// `file://` URI for the generated CycloneDDS loopback config.
pub fn cyclone_config_uri() -> String {
    format!(
        "file://{}",
        write_once("nros-loopback-cyclone.xml", CYCLONE_LOOPBACK_XML).display()
    )
}

/// Bash `export` clauses that put `rmw` on loopback, or an empty string.
///
/// Empty when the caller opted out, and empty for an RMW this does not know
/// how to isolate — silently doing nothing is right there, because the
/// alternative is exporting a variable the middleware ignores, which is
/// precisely the `ROS_LOCALHOST_ONLY` failure one layer up.
///
/// An operator's own `FASTRTPS_DEFAULT_PROFILES_FILE` / `CYCLONEDDS_URI` wins:
/// someone debugging a transport has a reason, and a test harness that
/// overwrites it makes the debugging session lie.
pub fn env_exports_for_rmw(rmw: &str) -> String {
    if lan_allowed() {
        return String::new();
    }
    match rmw {
        "rmw_fastrtps_cpp" | "rmw_fastrtps_dynamic_cpp" => {
            if std::env::var_os("FASTRTPS_DEFAULT_PROFILES_FILE").is_some() {
                return String::new();
            }
            format!(
                " && export FASTRTPS_DEFAULT_PROFILES_FILE={}",
                fastdds_profile_path().display()
            )
        }
        "rmw_cyclonedds_cpp" => {
            if std::env::var_os("CYCLONEDDS_URI").is_some() {
                return String::new();
            }
            format!(" && export CYCLONEDDS_URI={}", cyclone_config_uri())
        }
        _ => String::new(),
    }
}

/// Put the Fast-DDS loopback profile on a `Command`'s environment.
///
/// This is the half `ROS_LOCALHOST_ONLY` could never reach. The XRCE Agent is
/// spawned directly rather than through a `source setup.bash` shell, so it gets
/// the profile as an env var on the `Command` itself.
pub fn apply_fastdds_profile(cmd: &mut std::process::Command) {
    if lan_allowed() || std::env::var_os("FASTRTPS_DEFAULT_PROFILES_FILE").is_some() {
        return;
    }
    cmd.env("FASTRTPS_DEFAULT_PROFILES_FILE", fastdds_profile_path());
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_generated_profiles_are_well_formed_and_pin_loopback() {
        // Not a schema check -- a check that the two clauses which actually do
        // the work are present. A profile that parses but leaves the builtin
        // transports on isolates nothing, and would pass a well-formedness test.
        let fast = std::fs::read_to_string(fastdds_profile_path()).unwrap();
        assert!(fast.contains("<address>127.0.0.1</address>"));
        assert!(fast.contains("<useBuiltinTransports>false</useBuiltinTransports>"));
        assert!(fast.trim_start().starts_with("<?xml"));

        let uri = cyclone_config_uri();
        let path = uri.strip_prefix("file://").unwrap();
        let cyc = std::fs::read_to_string(path).unwrap();
        assert!(cyc.contains("<AllowMulticast>false</AllowMulticast>"));
        assert!(cyc.contains(r#"address="127.0.0.1""#));
    }

    #[test]
    fn an_unknown_rmw_gets_no_exports_rather_than_a_variable_it_ignores() {
        // The `ROS_LOCALHOST_ONLY` lesson as an assertion: exporting something
        // the middleware ignores is worse than exporting nothing, because it
        // reads as isolation while providing none.
        assert_eq!(env_exports_for_rmw("rmw_zenoh_cpp"), "");
        assert_eq!(env_exports_for_rmw(""), "");
    }

    #[test]
    fn each_known_dds_rmw_gets_its_own_variable() {
        // Only meaningful when the caller has not opted out or pre-set one.
        if lan_allowed() {
            return;
        }
        if std::env::var_os("FASTRTPS_DEFAULT_PROFILES_FILE").is_none() {
            assert!(
                env_exports_for_rmw("rmw_fastrtps_cpp").contains("FASTRTPS_DEFAULT_PROFILES_FILE")
            );
        }
        if std::env::var_os("CYCLONEDDS_URI").is_none() {
            assert!(env_exports_for_rmw("rmw_cyclonedds_cpp").contains("CYCLONEDDS_URI"));
        }
    }
}
