include = [ "../../../../../../nros-patch.toml", "nros-board.toml"]
[build]
target = "thumbv7m-none-eabi"


[patch.crates-io]
mps2-an385-pac = { path = "../../../../boards/mps2-an385-pac" }  # nros-managed
nros-board-mps2-an385 = { path = "../../../../boards/nros-board-mps2-an385" }  # nros-managed
