[build]
target = "thumbv7m-none-eabi"

[target.thumbv7m-none-eabi]
runner = "qemu-system-arm -cpu cortex-m3 -machine mps2-an385 -nographic -semihosting-config enable=on,target=native -kernel"
rustflags = [
    "-C", "link-arg=--gc-sections",
    "-C",
    "link-arg=-Tlink.x",
]

[patch.crates-io]
mps2-an385-pac = { path = "../../../../boards/mps2-an385-pac" }  # nros-managed
nros = { path = "../../../../core/nros" }  # nros-managed
nros-board-mps2-an385 = { path = "../../../../boards/nros-board-mps2-an385" }  # nros-managed
nros-board-rtic-mps2-an385 = { path = "../../../../boards/nros-board-rtic-mps2-an385" }  # nros-managed
nros-core = { path = "../../../../core/nros-core" }  # nros-managed
nros-serdes = { path = "../../../../core/nros-serdes" }  # nros-managed
