//! phase-459 W2 (issue 1426) + W4 (issue 1427) - the generated ENTRY runs the
//! schedule the contract implies, at priorities the board's plan allows.
//!
//! The fixture is `examples/workspaces/derived-tiers-cpp` (phase-459 W0): four
//! `SHAPE rclcpp` C++ components in the shape of the Autoware Safety Island,
//! one wall timer each, two at 30 Hz and two at 10 Hz, `CALLBACK_GROUPS main`
//! on every registration, and a `system.toml` that authors no `group_tiers`
//! and no `[tiers.*]`.
//!
//! What issue 1426 measured: even with the groups reaching `codegen-system`
//! (W1), the ENTRY still emitted `run_components`. `codegen entry` built its
//! plan from `model.execution.tiers` alone and called no derivation, so the
//! derived table lived in the bake's `nros-plan.json` and reached no image.
//! The entry is generated by `nano_ros_add_executable` before and
//! independently of the Zephyr module's bake, so it cannot read that file
//! either; it derives the same table from the same model instead.
//!
//! This exercises the pipeline `nros codegen entry --lang cpp --typed
//! --board zephyr --metadata <nros-metadata.json>` runs, in process:
//! `plan_from_model` -> `enrich_plan` -> `resolve_plan_sched` ->
//! `emit_cpp::emit_typed`, which is `cmd::codegen::run_entry`'s own sequence.
//!
//! # What is asserted
//!
//! MEMBERSHIP, ORDER and the PRIORITY NUMBERS, because with phase-459 W4 the
//! numbers are no longer an artefact of rank position: they are allocated out
//! of the Zephyr plan's application pool, which for this board's Kconfig
//! (15 preemptive priorities, the zenoh read band at its default) is [5, 14].
//! 30 Hz lands at 5 and 10 Hz at 6 - below the transport threads that feed
//! them, which is the whole of issue 1427.

mod common;

use std::{
    collections::BTreeMap,
    fs,
    path::{Path, PathBuf},
    time::{SystemTime, UNIX_EPOCH},
};

use nros_cli_core::codegen::entry::{
    Plan, emit_cpp, metadata, plan_from_model, resolve_plan_sched,
};

/// The two 30 Hz components, in the island's naming.
const FAST: [&str; 2] = ["mrm_emergency_stop_operator", "stop_mode_operator"];
/// The two 10 Hz components.
const SLOW: [&str; 2] = ["mrm_comfortable_stop_operator", "mrm_handler"];

/// The board key the entry bakes for. The fixture's `[image.zephyr]` names
/// `native_sim/native/64`; `codegen entry` is given the FAMILY key, which is
/// what selects the `[tiers.*.zephyr]` sub-table and `ZephyrBoard::run_tiers`.
const BOARD: &str = "zephyr";

/// The Zephyr application pool this board's Kconfig resolves to (RFC-0079
/// section 4.1): the transport occupies k_thread [0, 4], so the application
/// owns [5, 14]. phase-459 W4 records it; `priority_plan.rs` derives it.
const POOL: (i64, i64) = (5, 14);

fn repo_root() -> PathBuf {
    // <repo>/packages/cli/nros-cli-core/tests/ -> <repo>
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(3)
        .expect("repo root")
        .to_path_buf()
}

/// A private copy of the W0 fixture, so a test may write a build tree into it.
/// Repo rule: temp trees live under `$project/tmp/`, not the system temp dir.
struct Fixture {
    root: PathBuf,
}

impl Fixture {
    fn copy(tag: &str) -> Self {
        let repo = repo_root();
        let stamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("clock")
            .as_nanos();
        let root = repo.join("tmp").join(format!(
            "derived-tiers-entry-{tag}-{}-{stamp}",
            std::process::id()
        ));
        fs::create_dir_all(&root).expect("create the fixture copy");
        copy_tree(&repo.join("examples/workspaces/derived-tiers-cpp"), &root);
        Self { root }
    }

    fn bringup(&self) -> PathBuf {
        self.root.join("src/demo_bringup")
    }

    /// The `nros-metadata.json` a `cmake -B build-board` configure of this
    /// workspace writes - the file `nano_ros_add_executable` hands the entry
    /// bake as `--metadata`. `groups` is what `CALLBACK_GROUPS` put in it.
    fn configure(&self, groups: &[&str]) -> PathBuf {
        let ids = groups
            .iter()
            .map(|g| format!("\"{g}\""))
            .collect::<Vec<_>>()
            .join(", ");
        let rows: Vec<String> = [
            (
                "emergency_stop_pkg",
                "mrm_emergency_stop_operator",
                "MrmEmergencyStopOperator",
            ),
            ("stop_mode_pkg", "stop_mode_operator", "StopModeOperator"),
            (
                "comfortable_stop_pkg",
                "mrm_comfortable_stop_operator",
                "MrmComfortableStopOperator",
            ),
            ("mrm_handler_pkg", "mrm_handler", "MrmHandler"),
        ]
        .iter()
        .map(|(pkg, name, class)| {
            format!(
                "    {{\"name\": \"{name}\", \"pkg\": \"{pkg}\", \"class\": \"{pkg}::{class}\", \
                 \"class_header\": \"{pkg}/{class}.hpp\", \"shape\": \"rclcpp\", \
                 \"sources\": [\"src/{class}.cpp\"], \"deploy\": [], \
                 \"pkg_dir\": \"{}/src/{pkg}\", \"lang\": \"cpp\", \
                 \"callback_groups\": [{ids}]}}",
                self.root.display()
            )
        })
        .collect();
        let doc = format!(
            "{{\n  \"components\": [\n{}\n  ],\n  \"applications\": [\n  ]\n}}\n",
            rows.join(",\n")
        );
        let dir = self.root.join("build-board");
        fs::create_dir_all(&dir).expect("create the build tree");
        let path = dir.join("nros-metadata.json");
        fs::write(&path, doc).expect("write nros-metadata.json");
        path
    }
}

impl Drop for Fixture {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.root);
    }
}

fn copy_tree(from: &Path, to: &Path) {
    fs::create_dir_all(to).expect("mkdir");
    for entry in fs::read_dir(from).expect("read the fixture") {
        let entry = entry.expect("dir entry");
        let dst = to.join(entry.file_name());
        if entry.file_type().expect("file type").is_dir() {
            copy_tree(&entry.path(), &dst);
        } else {
            fs::copy(entry.path(), &dst).expect("copy");
        }
    }
}

/// The fixture's launch file + its contract sidecar, through the pinned
/// resolver, written where a bake would write it. The model is a build
/// artifact, so the test makes one.
fn resolve_model(bringup: &Path) -> PathBuf {
    resolve_model_with(bringup, false)
}

/// `with_system` folds the bringup's `system.toml` into the model, which is
/// what carries an AUTHORED `[tiers.*]` across. The derived road deliberately
/// does not need it: its `system.toml` states no tier at all.
fn resolve_model_with(bringup: &Path, with_system: bool) -> PathBuf {
    let resolver = common::pinned_launch_resolver();
    let out = bringup.join("model-out");
    fs::create_dir_all(&out).expect("create the model out dir");
    let model = out.join("system_model.yaml");
    let mut cmd = std::process::Command::new(&resolver);
    cmd.arg(bringup.join("launch/system.launch.xml"))
        .arg("--bringup-root")
        .arg(bringup);
    if with_system {
        cmd.arg("--system").arg(bringup.join("system.toml"));
    }
    let output = cmd
        .arg("-o")
        .arg(&model)
        .output()
        .expect("spawn nros-launch-resolve");
    assert!(
        output.status.success(),
        "nros-launch-resolve failed:\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    model
}

/// `cmd::codegen::run_entry`'s own sequence for a typed C++ Zephyr entry.
fn entry_plan(fixture: &Fixture, groups: &[&str]) -> Plan {
    let meta = fixture.configure(groups);
    let model = resolve_model(&fixture.bringup());
    let mut plan = plan_from_model(&model, Some(BOARD.to_string())).expect("plan from the model");
    let index = metadata::ComponentIndex::load(&meta).expect("the cmake metadata loads");
    metadata::enrich_plan(&mut plan, &index).expect("enrich from the cmake metadata");
    resolve_plan_sched(&mut plan, BOARD).expect("resolve (and, with no authored tier, derive)");
    plan
}

/// `node -> the Zephyr priority its resolved tier carries`.
fn priorities(plan: &Plan) -> BTreeMap<String, i64> {
    let table = plan
        .resolved_tiers
        .as_ref()
        .expect("a derived entry resolves a tier table");
    let mut out = BTreeMap::new();
    for tier in &table.tiers {
        for (node, _group) in &tier.members {
            out.insert(node.clone(), tier.priority);
        }
    }
    out
}

/// The wave: the entry derives, and the emitted C++ drives the nodes through
/// `run_tiers` over the derived table.
#[test]
fn the_entry_derives_its_tiers_and_emits_run_tiers() {
    let fixture = Fixture::copy("derives");
    let plan = entry_plan(&fixture, &["main"]);

    assert!(
        plan.is_multi_tier(),
        "the derived table is not the single synthesised default tier: {:?}",
        plan.resolved_tiers
    );
    let prio = priorities(&plan);
    let mut placed: Vec<&str> = prio.keys().map(String::as_str).collect();
    placed.sort_unstable();
    let mut want: Vec<&str> = FAST.iter().chain(SLOW.iter()).copied().collect();
    want.sort_unstable();
    assert_eq!(placed, want, "all four components are placed: {prio:?}");

    // phase-459 W4 - the numbers come from the board's plan, not from rank
    // position. Zephyr counts down, so the 30 Hz pair carries the smaller
    // number, and BOTH sit inside the application pool.
    let fast: Vec<i64> = FAST.iter().map(|n| prio[*n]).collect();
    let slow: Vec<i64> = SLOW.iter().map(|n| prio[*n]).collect();
    assert_eq!(fast, vec![5, 5], "the two 30 Hz nodes: {prio:?}");
    assert_eq!(slow, vec![6, 6], "the two 10 Hz nodes: {prio:?}");
    for (node, p) in &prio {
        assert!(
            POOL.0 <= *p && *p <= POOL.1,
            "{node} at {p} is outside the board's application pool {POOL:?}; a \
             derived tier must not outrank the transport that feeds it (issue 1427)"
        );
    }

    let src = emit_cpp::emit_typed(&plan).expect("the typed C++ entry emits");
    assert!(
        src.contains("::nros::board::ZephyrBoard::run_tiers("),
        "the entry must end in ZephyrBoard::run_tiers, not run_components; src:\n{src}"
    );
    assert!(
        !src.contains("run_components("),
        "a derived multi-tier entry must not fall back to run_components; src:\n{src}"
    );
    // One tier per node (W3 is the wave that names them by rank), each with
    // its allocated priority in the baked table.
    assert!(
        src.contains("__nros_tiers[4]"),
        "four derived tiers in the baked table; src:\n{src}"
    );
    for node in FAST.iter().chain(SLOW.iter()) {
        assert!(
            src.contains(&format!("\"{node}\"")),
            "tier table names {node}; src:\n{src}"
        );
    }

    // The tier table is emitted most-urgent-first in the RESOLVER's order, and
    // every priority in it is a pool address.
    let table = plan.resolved_tiers.as_ref().unwrap();
    for tier in &table.tiers {
        assert!(
            POOL.0 <= tier.priority && tier.priority <= POOL.1,
            "tier {} at {} is outside {POOL:?}",
            tier.name,
            tier.priority
        );
        assert_eq!(
            tier.members.len(),
            1,
            "a derived tier holds one node's group: {:?}",
            tier.members
        );
    }
}

/// The negative control, and the reason the derivation is a new SOURCE rather
/// than a new default: with no `CALLBACK_GROUPS` in the metadata, nothing is
/// derived and the entry stays exactly what it was - one executor, no tiers.
#[test]
fn without_the_keyword_the_entry_derives_nothing_and_keeps_run_components() {
    let fixture = Fixture::copy("no-keyword");
    let plan = entry_plan(&fixture, &[]);

    assert!(
        plan.tiers.is_empty() && plan.node_overrides.is_empty(),
        "nothing may be derived: {:?}",
        plan.tiers.keys().collect::<Vec<_>>()
    );
    assert!(
        plan.resolved_tiers.is_none(),
        "a groupless plan does not even resolve a table: {:?}",
        plan.resolved_tiers
    );

    let src = emit_cpp::emit_typed(&plan).expect("the typed C++ entry emits");
    assert!(
        !src.contains("run_tiers"),
        "without a declared group there is no tier to run; src:\n{src}"
    );
    assert!(
        src.contains("run_components"),
        "the groupless entry keeps the single-executor shape; src:\n{src}"
    );
}

/// An AUTHORED tier still wins. The derivation engages only on an empty tier
/// table - the same rule `codegen-system` applies - so a workspace that writes
/// its own `[tiers.*]` is untouched by this wave.
#[test]
fn an_authored_tier_table_is_not_replaced_by_the_derivation() {
    let fixture = Fixture::copy("authored");
    let meta = fixture.configure(&["main"]);
    let bringup = fixture.bringup();
    let system = bringup.join("system.toml");
    let raw = fs::read_to_string(&system).expect("read system.toml");
    // The authored form RFC-0079 retires, written the way it is written today:
    // the tier, its per-RTOS priority, and the binding on the component.
    let raw = raw.replace(
        "name = \"mrm_handler\"",
        "name = \"mrm_handler\"\ngroup_tiers = { main = \"ctrl\" }",
    );
    fs::write(
        &system,
        format!("{raw}\n[tiers.ctrl]\n[tiers.ctrl.zephyr]\npriority = 7\n"),
    )
    .expect("author a tier");

    let model = resolve_model_with(&bringup, true);
    let mut plan = plan_from_model(&model, Some(BOARD.to_string())).expect("plan from the model");
    assert!(
        !plan.tiers.is_empty(),
        "the authored tier reaches the plan: {:?}",
        plan.tiers.keys().collect::<Vec<_>>()
    );
    let index = metadata::ComponentIndex::load(&meta).expect("the cmake metadata loads");
    metadata::enrich_plan(&mut plan, &index).expect("enrich");
    resolve_plan_sched(&mut plan, BOARD).expect("resolve");

    assert_eq!(
        plan.tiers.keys().collect::<Vec<_>>(),
        vec!["ctrl"],
        "the authored table is the whole table; nothing was derived beside it"
    );
    let prio = priorities(&plan);
    assert_eq!(
        prio["mrm_handler"], 7,
        "the authored priority is honoured verbatim: {prio:?}"
    );
}
