//! phase-459 W2 (issue 1426) + W4 (issue 1427) - the generated ENTRY runs the
//! schedule the contract implies, at priorities the board's plan allows.
//!
//! The fixture is `examples/workspaces/derived-tiers-cpp` (phase-459 W0): four
//! `SHAPE rclcpp` C++ components in the shape of the Autoware Safety Island,
//! one wall timer each, two at 30 Hz and two at 10 Hz, `CALLBACK_GROUPS main`
//! on every registration, and a `system.toml` that authors no `group_tiers`
//! and no `[tiers.*]`.
//!
//! What issue 1426 measured: even with the groups reaching `codegen-system`
//! (W1), the ENTRY still emitted `run_components`. `codegen entry` built its
//! plan from `model.execution.tiers` alone and called no derivation, so the
//! derived table lived in the bake's `nros-plan.json` and reached no image.
//! The entry is generated by `nano_ros_add_executable` before and
//! independently of the Zephyr module's bake, so it cannot read that file
//! either; it derives the same table from the same model instead.
//!
//! This exercises the pipeline `nros codegen entry --lang cpp --typed
//! --board zephyr --metadata <nros-metadata.json>` runs, in process:
//! `plan_from_model` -> `enrich_plan` -> `resolve_plan_sched` ->
//! `emit_cpp::emit_typed`, which is `cmd::codegen::run_entry`'s own sequence.
//!
//! # What is asserted
//!
//! MEMBERSHIP, ORDER and the PRIORITY NUMBERS, because with phase-459 W4 the
//! numbers are no longer an artefact of rank position: they are allocated out
//! of the Zephyr plan's application pool, which for this board's Kconfig
//! (15 preemptive priorities, the zenoh read band at its default) is [5, 14].
//! 30 Hz lands at 5 and 10 Hz at 6 - below the transport threads that feed
//! them, which is the whole of issue 1427.

mod common;

use std::collections::BTreeMap;

use common::derived_tiers::{FAST, Fixture, SLOW, resolve_model_path};
use nros_cli_core::codegen::entry::{
    Plan, emit_cpp, metadata, plan_from_model, resolve_plan_sched,
};

/// The board key the entry bakes for. The fixture's `[image.zephyr]` names
/// `native_sim/native/64`; `codegen entry` is given the FAMILY key, which is
/// what selects the `[tiers.*.zephyr]` sub-table and `ZephyrBoard::run_tiers`.
const BOARD: &str = "zephyr";

/// The Zephyr application pool this board's Kconfig resolves to (RFC-0079
/// section 4.1): the transport occupies k_thread [0, 4], so the application
/// owns [5, 14]. phase-459 W4 records it; `priority_plan.rs` derives it.
const POOL: (i64, i64) = (5, 14);

/// `cmd::codegen::run_entry`'s own sequence for a typed C++ Zephyr entry.
fn entry_plan(fixture: &Fixture, groups: &[&str]) -> Plan {
    let meta = fixture.configure(groups);
    let model = resolve_model_path(&fixture.bringup(), false);
    let mut plan = plan_from_model(&model, Some(BOARD.to_string())).expect("plan from the model");
    let index = metadata::ComponentIndex::load(&meta).expect("the cmake metadata loads");
    metadata::enrich_plan(&mut plan, &index).expect("enrich from the cmake metadata");
    resolve_plan_sched(&mut plan, BOARD).expect("resolve (and, with no authored tier, derive)");
    plan
}

/// `node -> the Zephyr priority its resolved tier carries`.
fn priorities(plan: &Plan) -> BTreeMap<String, i64> {
    let table = plan
        .resolved_tiers
        .as_ref()
        .expect("a derived entry resolves a tier table");
    let mut out = BTreeMap::new();
    for tier in &table.tiers {
        for (node, _group) in &tier.members {
            out.insert(node.clone(), tier.priority);
        }
    }
    out
}

/// The wave: the entry derives, and the emitted C++ drives the nodes through
/// `run_tiers` over the derived table.
#[test]
fn the_entry_derives_its_tiers_and_emits_run_tiers() {
    let fixture = Fixture::copy("entry-derives");
    let plan = entry_plan(&fixture, &["main"]);

    assert!(
        plan.is_multi_tier(),
        "the derived table is not the single synthesised default tier: {:?}",
        plan.resolved_tiers
    );
    let prio = priorities(&plan);
    let mut placed: Vec<&str> = prio.keys().map(String::as_str).collect();
    placed.sort_unstable();
    let mut want: Vec<&str> = FAST.iter().chain(SLOW.iter()).copied().collect();
    want.sort_unstable();
    assert_eq!(placed, want, "all four components are placed: {prio:?}");

    // phase-459 W4 - the numbers come from the board's plan, not from rank
    // position. Zephyr counts down, so the 30 Hz pair carries the smaller
    // number, and BOTH sit inside the application pool.
    let fast: Vec<i64> = FAST.iter().map(|n| prio[*n]).collect();
    let slow: Vec<i64> = SLOW.iter().map(|n| prio[*n]).collect();
    assert_eq!(fast, vec![5, 5], "the two 30 Hz nodes: {prio:?}");
    assert_eq!(slow, vec![6, 6], "the two 10 Hz nodes: {prio:?}");
    for (node, p) in &prio {
        assert!(
            POOL.0 <= *p && *p <= POOL.1,
            "{node} at {p} is outside the board's application pool {POOL:?}; a \
             derived tier must not outrank the transport that feeds it (issue 1427)"
        );
    }

    let src = emit_cpp::emit_typed(&plan).expect("the typed C++ entry emits");
    assert!(
        src.contains("::nros::board::ZephyrBoard::run_tiers("),
        "the entry must end in ZephyrBoard::run_tiers, not run_components; src:\n{src}"
    );
    assert!(
        !src.contains("run_components("),
        "a derived multi-tier entry must not fall back to run_components; src:\n{src}"
    );
    // One tier per node (W3 is the wave that names them by rank), each with
    // its allocated priority in the baked table.
    assert!(
        src.contains("__nros_tiers[4]"),
        "four derived tiers in the baked table; src:\n{src}"
    );
    for node in FAST.iter().chain(SLOW.iter()) {
        assert!(
            src.contains(&format!("\"{node}\"")),
            "tier table names {node}; src:\n{src}"
        );
    }

    // The tier table is emitted most-urgent-first in the RESOLVER's order, and
    // every priority in it is a pool address.
    let table = plan.resolved_tiers.as_ref().unwrap();
    for tier in &table.tiers {
        assert!(
            POOL.0 <= tier.priority && tier.priority <= POOL.1,
            "tier {} at {} is outside {POOL:?}",
            tier.name,
            tier.priority
        );
        assert_eq!(
            tier.members.len(),
            1,
            "a derived tier holds one node's group: {:?}",
            tier.members
        );
    }
}

/// The negative control, and the reason the derivation is a new SOURCE rather
/// than a new default: with no `CALLBACK_GROUPS` in the metadata, nothing is
/// derived and the entry stays exactly what it was - one executor, no tiers.
#[test]
fn without_the_keyword_the_entry_derives_nothing_and_keeps_run_components() {
    let fixture = Fixture::copy("entry-no-keyword");
    let plan = entry_plan(&fixture, &[]);

    assert!(
        plan.tiers.is_empty() && plan.node_overrides.is_empty(),
        "nothing may be derived: {:?}",
        plan.tiers.keys().collect::<Vec<_>>()
    );
    assert!(
        plan.resolved_tiers.is_none(),
        "a groupless plan does not even resolve a table: {:?}",
        plan.resolved_tiers
    );

    let src = emit_cpp::emit_typed(&plan).expect("the typed C++ entry emits");
    assert!(
        !src.contains("run_tiers"),
        "without a declared group there is no tier to run; src:\n{src}"
    );
    assert!(
        src.contains("run_components"),
        "the groupless entry keeps the single-executor shape; src:\n{src}"
    );
}

/// An AUTHORED placement still wins, and it wins for the NODE THAT AUTHORED IT
/// and no other.
///
/// This test used to assert `plan.tiers.keys() == ["ctrl"]` - "the authored
/// table is the whole table; nothing was derived beside it" - which is the
/// defect issue 1426 names in its second bullet, written down as an
/// expectation. One component binding to one `[tiers.ctrl.zephyr]` disabled the
/// derivation for the other three, so three nodes with 30/10 Hz contracts and a
/// declared group landed on the synthesised default tier at Zephyr priority 0,
/// i.e. ABOVE the transport threads that feed them (issue 1427's inversion,
/// reached through the guard rather than through the allocator).
///
/// The rule now: precedence is per FACT.
/// `derive::placement_is_unauthored` rule 1 keeps `mrm_handler` at 7, rule 4
/// allocates a pool address for each of the other three, and the authored
/// number is recorded as having shadowed a rank rather than silently beating it.
#[test]
fn an_authored_placement_wins_only_for_the_node_that_authored_it() {
    let fixture = Fixture::copy("entry-authored");
    let meta = fixture.configure(&["main"]);
    let bringup = fixture.bringup();
    // The authored form RFC-0079 retires, written the way it is written today:
    // the tier, its per-RTOS priority, and the binding on the component.
    fixture.author(
        "ctrl",
        &["mrm_handler"],
        "[tiers.ctrl]\n[tiers.ctrl.zephyr]\npriority = 7\n",
    );

    let model = resolve_model_path(&bringup, true);
    let mut plan = plan_from_model(&model, Some(BOARD.to_string())).expect("plan from the model");
    assert!(
        plan.tiers.contains_key("ctrl"),
        "the authored tier reaches the plan: {:?}",
        plan.tiers.keys().collect::<Vec<_>>()
    );
    let index = metadata::ComponentIndex::load(&meta).expect("the cmake metadata loads");
    metadata::enrich_plan(&mut plan, &index).expect("enrich");
    resolve_plan_sched(&mut plan, BOARD).expect("resolve");

    let prio = priorities(&plan);
    assert_eq!(
        prio["mrm_handler"], 7,
        "rule 1: the authored priority is honoured verbatim: {prio:?}"
    );
    assert!(
        plan.tiers.contains_key("ctrl"),
        "the authored tier survives the merge: {:?}",
        plan.tiers.keys().collect::<Vec<_>>()
    );
    // Rule 4 for the three nodes nobody wrote anything about: each gets its own
    // allocated tier, inside the pool, and NOT the default tier's 0.
    let mut derived_members: Vec<&str> = prio
        .keys()
        .map(String::as_str)
        .filter(|n| *n != "mrm_handler")
        .collect();
    derived_members.sort_unstable();
    let mut want: Vec<&str> = FAST
        .iter()
        .chain(SLOW.iter())
        .copied()
        .filter(|n| *n != "mrm_handler")
        .collect();
    want.sort_unstable();
    assert_eq!(
        derived_members, want,
        "every node the author said nothing about is allocated a tier: {prio:?}"
    );
    for node in &derived_members {
        let p = prio[*node];
        assert!(
            POOL.0 <= p && p <= POOL.1,
            "{node} at {p} must be inside the board's application pool {POOL:?}, \
             not on the default tier above the transport: {prio:?}"
        );
    }
    // The rate-monotonic order still holds among them: the 30 Hz node outranks
    // the 10 Hz one (Zephyr counts down).
    assert!(
        prio["mrm_emergency_stop_operator"] < prio["mrm_comfortable_stop_operator"],
        "rate-monotonic among the allocated tiers: {prio:?}"
    );
}

/// Issue 1537 follow-up - the RUST shape of a derived image: no cmake metadata
/// at all, the groups stated only through `[[component]] group_tiers` (the
/// model's `execution.bindings`, the one group input `nros::main!` reads), and
/// still no `[tiers.*]`.
///
/// Before the fix the entry derived NOTHING here - `derive_entry_tiers` keyed
/// on cmake groups alone - so resolution failed on the bindings' tier names,
/// `schedule_board_features` withheld `tiers`, and a generated Rust Zephyr
/// entry whose macro DID derive a table could not compile
/// (`no associated function run_tiers`). Measured on
/// `realtime-rust/src/derived_bringup`'s image.
#[test]
fn a_group_tiers_only_image_derives_like_the_macro_does() {
    let fixture = Fixture::copy("group-tiers");
    let bringup = fixture.bringup();
    let system = bringup.join("system.toml");
    let mut raw = fs::read_to_string(&system).expect("read system.toml");
    for name in FAST.iter().chain(SLOW.iter()) {
        raw = raw.replace(
            &format!("name = \"{name}\""),
            &format!("name = \"{name}\"\ngroup_tiers = {{ main = \"bound\" }}"),
        );
    }
    fs::write(&system, raw).expect("bind each component's group");

    let model = resolve_model_with(&bringup, true);
    let mut plan = plan_from_model(&model, Some(BOARD.to_string())).expect("plan from the model");
    assert!(
        plan.tiers.is_empty(),
        "nothing is authored, so nothing reaches the plan's tier table"
    );
    // No `enrich_plan`: a Rust image has no cmake metadata to enrich from.
    resolve_plan_sched(&mut plan, BOARD).expect("resolve (and derive)");

    assert!(
        plan.is_multi_tier(),
        "a group_tiers-only image derives a multi-tier table: {:?}",
        plan.resolved_tiers
    );
    let prio = priorities(&plan);
    for fast in FAST {
        for slow in SLOW {
            assert!(
                prio[fast] < prio[slow],
                "30 Hz `{fast}` is more urgent than 10 Hz `{slow}`: {prio:?}"
            );
        }
    }
}
