meta:
  version: 1
  inputs:
  - path: launch/action_server.launch.xml
    sha256: 148a80d27eaffe922a6c16831792f617ae8dd61172784a30fba9b6b0a76c1613
  - path: system.toml
    sha256: cb9a76f08230c5928980029aa343dc60221864c01d93b5b75d78543bbc1ddfab
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
  diagnostics:
  - 'system config: [deploy.robot1] places unknown node ''/talker'' (absent in this variant?)'
  - 'system config: [deploy.robot2] places unknown node ''/listener'' (absent in this variant?)'
structure:
  scopes:
    action_server.launch.xml:
      file: action_server.launch.xml
  nodes:
    /fib_server:
      scope: action_server.launch.xml
      pkg: cpp_fib_server_pkg
      exec: fib_server
      node_name: fib_server
execution:
  deploy:
    /fib_server:
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
