meta:
  version: 1
  inputs:
  - path: launch/action_server.launch.xml
    sha256: 148a80d27eaffe922a6c16831792f617ae8dd61172784a30fba9b6b0a76c1613
  - path: system.toml
    sha256: 945aa9841eb2609df2647168f7767daaf95e167c6bddfbffb982ad10d02d3578
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
structure:
  scopes:
    action_server.launch.xml:
      file: action_server.launch.xml
  nodes:
    /fib_server:
      scope: action_server.launch.xml
      pkg: cpp_fib_server_pkg
      exec: fib_server
      node_name: fib_server
execution:
  deploy:
    /fib_server:
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
