meta:
  version: 1
  args:
    host: robot1
  inputs:
  - path: launch/multihost.launch.xml
    sha256: fa76a0a3e64675302f474f2395e3a568737bc19c8e50682acede7d64fbbf0a83
  - path: system.toml
    sha256: cb9a76f08230c5928980029aa343dc60221864c01d93b5b75d78543bbc1ddfab
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
  diagnostics:
  - 'system config: [deploy.robot2] places unknown node ''/listener'' (absent in this variant?)'
structure:
  scopes:
    multihost.launch.xml:
      file: multihost.launch.xml
      args:
        host: robot1
  nodes:
    /talker:
      scope: multihost.launch.xml
      pkg: talker_pkg
      exec: talker
      node_name: talker
execution:
  deploy:
    /talker:
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: robot1
        kind: self
        target: x86_64-unknown-linux-gnu
