meta:
  version: 1
  inputs:
  - path: launch/system.launch.xml
    sha256: 210a67e1dcbc9837705352cf6ec496b98f1cc5f971feb0be0de85f5b64136e0d
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
structure:
  scopes:
    system.launch.xml:
      file: system.launch.xml
