#!/bin/bash
# Build zenoh-pico for ARM Cortex-M3 (QEMU mps2-an385)
#
# Cross-compiles zenoh-pico as a static library for bare-metal ARM Cortex-M3.
# This produces a standalone .a that serves as a build-readiness check for
# QEMU E2E tests. The actual linking is done by zpico-sys/build.rs via cc::Build.
#
# Usage:
#   ./scripts/qemu/build-zenoh-pico.sh [--clean]
#
# Output:
#   build/qemu-zenoh-pico/libzenohpico.a
#
# Prerequisites:
#   - arm-none-eabi-gcc toolchain

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
BUILD_DIR="$REPO_ROOT/build/qemu-zenoh-pico"
ZENOH_PICO_DIR="$REPO_ROOT/packages/zpico/zpico-sys/zenoh-pico"
C_DIR="$REPO_ROOT/packages/zpico/zpico-sys/c"
PLATFORM_DIR="$C_DIR/platform"

# Parse arguments
if [ "$1" = "--clean" ]; then
    echo "Cleaning build directory..."
    rm -rf "$BUILD_DIR"
    echo "Done."
    exit 0
fi

# Check prerequisites
if ! command -v arm-none-eabi-gcc &>/dev/null; then
    echo "Error: arm-none-eabi-gcc not found"
    echo "Install with: sudo apt install gcc-arm-none-eabi"
    exit 1
fi

# Check zenoh-pico submodule
if [ ! -d "$ZENOH_PICO_DIR/include" ]; then
    echo "Error: zenoh-pico submodule not found"
    echo "Run: git submodule update --init"
    exit 1
fi

echo "Building zenoh-pico for ARM Cortex-M3..."

# Create build directory
mkdir -p "$BUILD_DIR"

# Generate version header (matches build.rs generate_embedded_version_header)
VERSION=$(cat "$ZENOH_PICO_DIR/version.txt" 2>/dev/null || echo "0.11.0")
MAJOR=$(echo "$VERSION" | cut -d. -f1)
MINOR=$(echo "$VERSION" | cut -d. -f2)
PATCH=$(echo "$VERSION" | cut -d. -f3)

mkdir -p "$BUILD_DIR/include"
cat > "$BUILD_DIR/include/zenoh-pico.h" << EOF
// Auto-generated version header for zenoh-pico
#ifndef ZENOH_PICO_H
#define ZENOH_PICO_H

#define ZENOH_PICO "$VERSION"
#define ZENOH_PICO_MAJOR $MAJOR
#define ZENOH_PICO_MINOR $MINOR
#define ZENOH_PICO_PATCH $PATCH
#define ZENOH_PICO_TWEAK 0

#include "zenoh-pico/api.h"

#endif // ZENOH_PICO_H
EOF

# Generate config header (matches build.rs generate_config_header)
mkdir -p "$BUILD_DIR/zenoh-config"
cat > "$BUILD_DIR/zenoh-config/zenoh_generic_config.h" << 'EOF'
/**
 * zenoh_generic_config.h - Generated by build-zenoh-pico.sh
 *
 * Matches the config header generated by zpico-sys/build.rs for bare-metal.
 * DO NOT EDIT — regenerated on every build.
 */

#ifndef ZENOH_GENERIC_CONFIG_H
#define ZENOH_GENERIC_CONFIG_H

// Buffer Sizes
#define Z_FRAG_MAX_SIZE 1500
#define Z_BATCH_UNICAST_SIZE 2048
#define Z_BATCH_MULTICAST_SIZE 2048
#define Z_CONFIG_SOCKET_TIMEOUT 100
#define Z_TRANSPORT_LEASE 10000
#define Z_TRANSPORT_LEASE_EXPIRE_FACTOR 3
#define ZP_PERIODIC_SCHEDULER_MAX_TASKS 8

// Core Features
#ifndef Z_FEATURE_MULTI_THREAD
#define Z_FEATURE_MULTI_THREAD 0
#endif
#define Z_FEATURE_PUBLICATION 1
#define Z_FEATURE_ADVANCED_PUBLICATION 0
#define Z_FEATURE_SUBSCRIPTION 1
#define Z_FEATURE_ADVANCED_SUBSCRIPTION 0
#define Z_FEATURE_QUERY 1
#define Z_FEATURE_QUERYABLE 1
#define Z_FEATURE_LIVELINESS 1
#define Z_FEATURE_INTEREST 1

// Transport Link Features
#define Z_FEATURE_LINK_TCP 1
#define Z_FEATURE_LINK_UDP_UNICAST 0
#define Z_FEATURE_LINK_UDP_MULTICAST 0
#define Z_FEATURE_LINK_SERIAL 0
#define Z_FEATURE_LINK_TLS 0
#define Z_FEATURE_LINK_WS 0
#define Z_FEATURE_LINK_BLUETOOTH 0
#define Z_FEATURE_RAWETH_TRANSPORT 0
#define Z_FEATURE_SCOUTING_UDP 0

// Local Subscriber
#define Z_FEATURE_LOCAL_SUBSCRIBER 0

#endif // ZENOH_GENERIC_CONFIG_H
EOF

# Collect zenoh-pico source files (excluding platform-specific system backends)
SOURCES=""
for dir in api collections link net protocol session transport utils; do
    for f in $(find "$ZENOH_PICO_DIR/src/$dir" -name "*.c" 2>/dev/null); do
        SOURCES="$SOURCES $f"
    done
done

# Add common system sources (shared across all platforms)
for f in $(find "$ZENOH_PICO_DIR/src/system/common" -name "*.c" 2>/dev/null); do
    SOURCES="$SOURCES $f"
done

# Add zpico (high-level API wrapper)
SOURCES="$SOURCES $C_DIR/zpico/zpico.c"

# Note: No system.c/network.c — bare-metal platform symbols are provided by
# Rust FFI (zpico-platform-mps2-an385). This library only contains zenoh-pico
# core + zpico shim.

# Compiler flags
CFLAGS="-mcpu=cortex-m3 -mthumb"
CFLAGS="$CFLAGS -Os -g"
CFLAGS="$CFLAGS -ffunction-sections -fdata-sections"
CFLAGS="$CFLAGS -fno-common -fno-exceptions"
CFLAGS="$CFLAGS -Wall -Wextra"

# Include paths (order matters — generated config takes precedence)
INCLUDES="-I$BUILD_DIR/zenoh-config"
INCLUDES="$INCLUDES -I$ZENOH_PICO_DIR/include"
INCLUDES="$INCLUDES -I$BUILD_DIR/include"
INCLUDES="$INCLUDES -I$PLATFORM_DIR"
INCLUDES="$INCLUDES -I$PLATFORM_DIR/bare-metal"
INCLUDES="$INCLUDES -I$C_DIR/include"

# Platform defines (matches build.rs build_zenoh_pico_embedded)
DEFINES="-DZENOH_GENERIC"
DEFINES="$DEFINES -DZPICO_SMOLTCP"
DEFINES="$DEFINES -DZ_FEATURE_MULTI_THREAD=0"
DEFINES="$DEFINES -DZ_FEATURE_LINK_TCP=1"
DEFINES="$DEFINES -DZ_FEATURE_LINK_UDP_MULTICAST=0"
DEFINES="$DEFINES -DZ_FEATURE_LINK_UDP_UNICAST=0"
DEFINES="$DEFINES -DZ_FEATURE_SCOUTING_UDP=0"
DEFINES="$DEFINES -DZ_FEATURE_LINK_SERIAL=0"
DEFINES="$DEFINES -DZ_FEATURE_LINK_TLS=0"
DEFINES="$DEFINES -DZ_FEATURE_LINK_WS=0"
DEFINES="$DEFINES -DZ_FEATURE_LINK_BLUETOOTH=0"
DEFINES="$DEFINES -DZ_FEATURE_RAWETH_TRANSPORT=0"
DEFINES="$DEFINES -DZENOH_DEBUG=0"

# Shim slot counts (matches ShimConfig defaults in build.rs)
DEFINES="$DEFINES -DZPICO_MAX_PUBLISHERS=8"
DEFINES="$DEFINES -DZPICO_MAX_SUBSCRIBERS=8"
DEFINES="$DEFINES -DZPICO_MAX_QUERYABLES=8"
DEFINES="$DEFINES -DZPICO_MAX_LIVELINESS=16"
DEFINES="$DEFINES -DZPICO_MAX_PENDING_GETS=4"
DEFINES="$DEFINES -DZPICO_GET_REPLY_BUF_SIZE=4096"
DEFINES="$DEFINES -DZPICO_GET_POLL_INTERVAL_MS=10"

# Compile each source file
OBJECTS=""
count=0
for src in $SOURCES; do
    basename=$(basename "$src" .c)
    # Handle name collisions by using full path hash
    objname=$(echo "$src" | md5sum | cut -c1-8)_${basename}.o
    obj="$BUILD_DIR/$objname"

    arm-none-eabi-gcc $CFLAGS $INCLUDES $DEFINES -c "$src" -o "$obj"
    OBJECTS="$OBJECTS $obj"
    count=$((count + 1))
done

# Create static library
arm-none-eabi-ar rcs "$BUILD_DIR/libzenohpico.a" $OBJECTS

echo "Built $count sources → $BUILD_DIR/libzenohpico.a ($(stat -c%s "$BUILD_DIR/libzenohpico.a" | numfmt --to=iec-i --suffix=B))"
