[patch.crates-io]
nano-ros-core = { path = "../../../packages/core/nano-ros-core" }
nano-ros-serdes = { path = "../../../packages/core/nano-ros-serdes" }
example_interfaces = { path = "generated/example_interfaces" }
