// nros-c service type - C implementation
// Package: example_interfaces
// Service: AddTwoInts
// Auto-generated by rosidl-codegen - do not edit

#include "example_interfaces_srv_add_two_ints.h"
#include <nros/types.h>
#include <nros/cdr.h>
#include <string.h>

// Type support structure
static const struct nros_service_type_t example_interfaces_srv_add_two_ints_type_support = {
    .type_name = "example_interfaces::srv::dds_::AddTwoInts_",
    .type_hash = "TypeHashNotSupported",
};

const struct nros_service_type_t* example_interfaces_srv_add_two_ints_get_type_support(void) {
    return &example_interfaces_srv_add_two_ints_type_support;
}

// ============================================================================
// Request Implementation
// ============================================================================

void example_interfaces_srv_add_two_ints_request_init(example_interfaces_srv_add_two_ints_request* msg) {
    if (msg == NULL) return;
    memset(msg, 0, sizeof(example_interfaces_srv_add_two_ints_request));
}

int32_t example_interfaces_srv_add_two_ints_request_serialize(const example_interfaces_srv_add_two_ints_request* msg, uint8_t* buffer, size_t buffer_size) {
    if (msg == NULL || buffer == NULL) return -1;

    uint8_t* ptr = buffer;
    const uint8_t* end = buffer + buffer_size;

    // Write CDR header (little-endian, version 1)
    if (ptr + 4 > end) return -1;
    *ptr++ = 0x00; // CDR encapsulation
    *ptr++ = 0x01; // Little-endian
    *ptr++ = 0x00; // Options (unused)
    *ptr++ = 0x00; // Options (unused)
    const uint8_t* origin = ptr; // CDR alignment origin (after header)
    (void)origin;
    if (nros_cdr_write_i64(&ptr, end, origin, msg->a) < 0) return -1;
    if (nros_cdr_write_i64(&ptr, end, origin, msg->b) < 0) return -1;

    return (int32_t)(ptr - buffer);
}

int32_t example_interfaces_srv_add_two_ints_request_deserialize(example_interfaces_srv_add_two_ints_request* msg, const uint8_t* buffer, size_t buffer_size) {
    if (msg == NULL || buffer == NULL) return -1;

    const uint8_t* ptr = buffer;
    const uint8_t* end = buffer + buffer_size;

    // Skip CDR header
    if (ptr + 4 > end) return -1;
    ptr += 4;
    const uint8_t* origin = ptr; // CDR alignment origin (after header)
    (void)origin;

    example_interfaces_srv_add_two_ints_request_init(msg);
    if (nros_cdr_read_i64(&ptr, end, origin, &msg->a) < 0) return -1;
    if (nros_cdr_read_i64(&ptr, end, origin, &msg->b) < 0) return -1;

    return 0;
}

// ============================================================================
// Response Implementation
// ============================================================================

void example_interfaces_srv_add_two_ints_response_init(example_interfaces_srv_add_two_ints_response* msg) {
    if (msg == NULL) return;
    memset(msg, 0, sizeof(example_interfaces_srv_add_two_ints_response));
}

int32_t example_interfaces_srv_add_two_ints_response_serialize(const example_interfaces_srv_add_two_ints_response* msg, uint8_t* buffer, size_t buffer_size) {
    if (msg == NULL || buffer == NULL) return -1;

    uint8_t* ptr = buffer;
    const uint8_t* end = buffer + buffer_size;

    // Write CDR header (little-endian, version 1)
    if (ptr + 4 > end) return -1;
    *ptr++ = 0x00; // CDR encapsulation
    *ptr++ = 0x01; // Little-endian
    *ptr++ = 0x00; // Options (unused)
    *ptr++ = 0x00; // Options (unused)
    const uint8_t* origin = ptr; // CDR alignment origin (after header)
    (void)origin;
    if (nros_cdr_write_i64(&ptr, end, origin, msg->sum) < 0) return -1;

    return (int32_t)(ptr - buffer);
}

int32_t example_interfaces_srv_add_two_ints_response_deserialize(example_interfaces_srv_add_two_ints_response* msg, const uint8_t* buffer, size_t buffer_size) {
    if (msg == NULL || buffer == NULL) return -1;

    const uint8_t* ptr = buffer;
    const uint8_t* end = buffer + buffer_size;

    // Skip CDR header
    if (ptr + 4 > end) return -1;
    ptr += 4;
    const uint8_t* origin = ptr; // CDR alignment origin (after header)
    (void)origin;

    example_interfaces_srv_add_two_ints_response_init(msg);
    if (nros_cdr_read_i64(&ptr, end, origin, &msg->sum) < 0) return -1;

    return 0;
}