// nros-c service type - C header for embedded systems
// Package: example_interfaces
// Service: AddTwoInts
// Auto-generated by rosidl-codegen - do not edit

#ifndef EXAMPLE_INTERFACES_SRV_ADD_TWO_INTS_H
#define EXAMPLE_INTERFACES_SRV_ADD_TWO_INTS_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#include <nros/types.h>

#ifdef __cplusplus
extern "C" {
#endif

// ============================================================================
// Request
// ============================================================================

// Request constants

/// AddTwoInts request structure
typedef struct example_interfaces_srv_add_two_ints_request {
    int64_t a;
    int64_t b;
} example_interfaces_srv_add_two_ints_request;

/// Initialize a AddTwoInts request to default values
void example_interfaces_srv_add_two_ints_request_init(example_interfaces_srv_add_two_ints_request* msg);

/// Serialize a AddTwoInts request to CDR format
/// Returns the number of bytes written, or -1 on error
int32_t example_interfaces_srv_add_two_ints_request_serialize(const example_interfaces_srv_add_two_ints_request* msg, uint8_t* buffer, size_t buffer_size);

/// Deserialize a AddTwoInts request from CDR format
/// Returns 0 on success, -1 on error
int32_t example_interfaces_srv_add_two_ints_request_deserialize(example_interfaces_srv_add_two_ints_request* msg, const uint8_t* buffer, size_t buffer_size);

// ============================================================================
// Response
// ============================================================================

// Response constants

/// AddTwoInts response structure
typedef struct example_interfaces_srv_add_two_ints_response {
    int64_t sum;
} example_interfaces_srv_add_two_ints_response;

/// Initialize a AddTwoInts response to default values
void example_interfaces_srv_add_two_ints_response_init(example_interfaces_srv_add_two_ints_response* msg);

/// Serialize a AddTwoInts response to CDR format
/// Returns the number of bytes written, or -1 on error
int32_t example_interfaces_srv_add_two_ints_response_serialize(const example_interfaces_srv_add_two_ints_response* msg, uint8_t* buffer, size_t buffer_size);

/// Deserialize a AddTwoInts response from CDR format
/// Returns 0 on success, -1 on error
int32_t example_interfaces_srv_add_two_ints_response_deserialize(example_interfaces_srv_add_two_ints_response* msg, const uint8_t* buffer, size_t buffer_size);

// ============================================================================
// Service Type Support
// ============================================================================

/// Get the ROS type name for AddTwoInts
static inline const char* example_interfaces_srv_add_two_ints_get_type_name(void) {
    return "example_interfaces::srv::dds_::AddTwoInts_";
}

/// Get the type hash for AddTwoInts
static inline const char* example_interfaces_srv_add_two_ints_get_type_hash(void) {
    return "TypeHashNotSupported";
}

/// Get the nros_service_type_t for this service type
const struct nros_service_type_t* example_interfaces_srv_add_two_ints_get_type_support(void);

#ifdef __cplusplus
}
#endif

#endif // EXAMPLE_INTERFACES_SRV_ADD_TWO_INTS_H