meta:
  version: 1
  inputs:
  - path: launch/action_client.launch.xml
    sha256: f52c7419eaf57518cdf97c7a18372b1361be3c397d30f63016a410ea33a223f3
  - path: system.toml
    sha256: 51317df55281ab822df0f3a67e042089ed463a334bc6f02b05c4ee7762efd4c0
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
structure:
  scopes:
    action_client.launch.xml:
      file: action_client.launch.xml
  nodes:
    /fibonacci_client:
      scope: action_client.launch.xml
      pkg: action_client_pkg
      exec: fibonacci_client
      node_name: fibonacci_client
execution:
  deploy:
    /fibonacci_client:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
