meta:
  version: 1
  inputs:
  - path: launch/action_server.launch.xml
    sha256: 164e157a1539fd6a11d9a12f02c376eed84f1120bde16d58c9874b4588d4a335
  - path: system.toml
    sha256: 75b2138d28ea46ffaf94ec671c3b478fdc247c89244ad4f150cebc56d91b89a3
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
  diagnostics:
  - 'system config: [deploy.robot1] places unknown node ''/talker'' (absent in this variant?)'
  - 'system config: [deploy.robot2] places unknown node ''/listener'' (absent in this variant?)'
structure:
  scopes:
    action_server.launch.xml:
      file: action_server.launch.xml
  nodes:
    /fibonacci_server:
      scope: action_server.launch.xml
      pkg: action_server_pkg
      exec: fibonacci_server
      node_name: fibonacci_server
execution:
  deploy:
    /fibonacci_server:
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
