meta:
  version: 1
  inputs:
  - path: /home/aeon/repos/nano-ros/examples/workspaces/rust/src/demo_bringup/launch/multihost.launch.xml
    sha256: 4d922641296357912d4afdeaf56aa67d6cc633d3938e8fe737a9bc78f6f7600d
  resolver:
    tool: play_launch
    version: 0.8.2
structure:
  scopes:
    /: {}
  nodes:
    /listener:
      scope: /
      pkg: listener_pkg
      exec: listener
      node_name: listener
    /talker:
      scope: /
      pkg: talker_pkg
      exec: talker
      node_name: talker
execution:
  deploy:
    /listener:
      target: linux
      host: robot2
    /talker:
      target: linux
      host: robot1
