meta:
  version: 1
  args:
    host: robot1
  inputs:
  - path: launch/multihost.launch.xml
    sha256: 1cadf204241ae690fe2eb08fbc1fd03a1d6693ef8d6c2d4aed5c61854669058e
  - path: system.toml
    sha256: 75b2138d28ea46ffaf94ec671c3b478fdc247c89244ad4f150cebc56d91b89a3
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
  diagnostics:
  - 'system config: [deploy.robot2] places unknown node ''/listener'' (absent in this variant?)'
structure:
  scopes:
    multihost.launch.xml:
      file: multihost.launch.xml
      args:
        host: robot1
  nodes:
    /talker:
      scope: multihost.launch.xml
      pkg: talker_pkg
      exec: talker
      node_name: talker
execution:
  deploy:
    /talker:
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: robot1
        kind: self
        target: x86_64-unknown-linux-gnu
