meta:
  version: 1
  inputs:
  - path: launch/multihost.launch.xml
    sha256: 4d922641296357912d4afdeaf56aa67d6cc633d3938e8fe737a9bc78f6f7600d
  - path: system.toml
    sha256: 51317df55281ab822df0f3a67e042089ed463a334bc6f02b05c4ee7762efd4c0
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
structure:
  scopes:
    multihost.launch.xml:
      file: multihost.launch.xml
  nodes:
    /listener:
      scope: multihost.launch.xml
      pkg: listener_pkg
      exec: listener
      node_name: listener
    /talker:
      scope: multihost.launch.xml
      pkg: talker_pkg
      exec: talker
      node_name: talker
execution:
  deploy:
    /listener:
      target: linux
      host: robot2
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: robot2
        kind: self
        target: x86_64-unknown-linux-gnu
    /talker:
      target: linux
      host: robot1
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: robot1
        kind: self
        target: x86_64-unknown-linux-gnu
