meta:
  version: 1
  inputs:
  - path: launch/service_inprocess.launch.xml
    sha256: 2bcd29192613a44a260b8d0f536ba38fb5b05ae1fc541e622abc1954c9bd22f2
  - path: system.toml
    sha256: 75b2138d28ea46ffaf94ec671c3b478fdc247c89244ad4f150cebc56d91b89a3
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
  diagnostics:
  - 'system config: [deploy.robot1] places unknown node ''/talker'' (absent in this variant?)'
  - 'system config: [deploy.robot2] places unknown node ''/listener'' (absent in this variant?)'
structure:
  scopes:
    service_inprocess.launch.xml:
      file: service_inprocess.launch.xml
  nodes:
    /add_client:
      scope: service_inprocess.launch.xml
      pkg: service_client_pkg
      exec: add_client
      node_name: add_client
    /add_server:
      scope: service_inprocess.launch.xml
      pkg: service_server_pkg
      exec: add_server
      node_name: add_server
execution:
  deploy:
    /add_client:
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
    /add_server:
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
