meta:
  version: 1
  inputs:
  - path: launch/service_server.launch.xml
    sha256: 1c3649a50b285e387a209591a1dae6552732fc91691572fa60af29c555494532
  - path: system.toml
    sha256: 51317df55281ab822df0f3a67e042089ed463a334bc6f02b05c4ee7762efd4c0
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
structure:
  scopes:
    service_server.launch.xml:
      file: service_server.launch.xml
  nodes:
    /add_server:
      scope: service_server.launch.xml
      pkg: service_server_pkg
      exec: add_server
      node_name: add_server
execution:
  deploy:
    /add_server:
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
