meta:
  version: 1
  inputs:
  - path: launch/service_client.launch.xml
    sha256: 5597087663f2f2b33c7c7a6d1285a0aa983c9b607c6e85783b746181e57ed146
  - path: system.toml
    sha256: 75b2138d28ea46ffaf94ec671c3b478fdc247c89244ad4f150cebc56d91b89a3
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
  diagnostics:
  - 'system config: [deploy.robot1] places unknown node ''/talker'' (absent in this variant?)'
  - 'system config: [deploy.robot2] places unknown node ''/listener'' (absent in this variant?)'
structure:
  scopes:
    service_client.launch.xml:
      file: service_client.launch.xml
  nodes:
    /add_client:
      scope: service_client.launch.xml
      pkg: service_client_pkg
      exec: add_client
      node_name: add_client
execution:
  deploy:
    /add_client:
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
