meta:
  version: 1
  inputs:
  - path: launch/showcase.launch.xml
    sha256: a2ccfccfab771fd2533a1ca160b23e633df564c16b7a8253e297f87b9b750147
  - path: system.toml
    sha256: 9f2f615718b6d6587f0e20daf8e6d8ace5e7dc5dd5d8515f51a12da67a14f25c
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
structure:
  scopes:
    showcase.launch.xml:
      file: showcase.launch.xml
  nodes:
    /add_client:
      scope: showcase.launch.xml
      pkg: service_client_pkg
      exec: add_client
      node_name: add_client
    /add_server:
      scope: showcase.launch.xml
      pkg: service_server_pkg
      exec: add_server
      node_name: add_server
    /fibonacci_client:
      scope: showcase.launch.xml
      pkg: action_client_pkg
      exec: fibonacci_client
      node_name: fibonacci_client
    /fibonacci_server:
      scope: showcase.launch.xml
      pkg: action_server_pkg
      exec: fibonacci_server
      node_name: fibonacci_server
    /listener:
      scope: showcase.launch.xml
      pkg: listener_pkg
      exec: listener
      node_name: listener
    /talker:
      scope: showcase.launch.xml
      pkg: talker_pkg
      exec: talker
      node_name: talker
execution:
  deploy:
    /add_client:
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
    /add_server:
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
    /fibonacci_client:
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
    /fibonacci_server:
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
    /listener:
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
    /talker:
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
