meta:
  version: 1
  inputs:
  - path: launch/showcase.launch.xml
    sha256: a2ccfccfab771fd2533a1ca160b23e633df564c16b7a8253e297f87b9b750147
  - path: system.toml
    sha256: 46225f9a407392e38125f04c8a678b0d2dfc87dbc46953b418d1033a8dd98b0e
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
structure:
  scopes:
    showcase.launch.xml:
      file: showcase.launch.xml
  nodes:
    /add_client:
      scope: showcase.launch.xml
      pkg: service_client_pkg
      exec: add_client
      node_name: add_client
    /add_server:
      scope: showcase.launch.xml
      pkg: service_server_pkg
      exec: add_server
      node_name: add_server
    /fibonacci_client:
      scope: showcase.launch.xml
      pkg: action_client_pkg
      exec: fibonacci_client
      node_name: fibonacci_client
    /fibonacci_server:
      scope: showcase.launch.xml
      pkg: action_server_pkg
      exec: fibonacci_server
      node_name: fibonacci_server
    /listener:
      scope: showcase.launch.xml
      pkg: listener_pkg
      exec: listener
      node_name: listener
    /talker:
      scope: showcase.launch.xml
      pkg: talker_pkg
      exec: talker
      node_name: talker
execution:
  deploy:
    /add_client:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
    /add_server:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
    /fibonacci_client:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
    /fibonacci_server:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
    /listener:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
    /talker:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
