meta:
  version: 1
  inputs:
  - path: launch/system.launch.xml
    sha256: f5a550aecbeb157bc731b831a051ba9bf3dd0158fdee9bb7e4869cf9531d697d
  - path: system.toml
    sha256: 9f2f615718b6d6587f0e20daf8e6d8ace5e7dc5dd5d8515f51a12da67a14f25c
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
structure:
  scopes:
    system.launch.xml:
      file: system.launch.xml
  nodes:
    /listener:
      scope: system.launch.xml
      pkg: listener_pkg
      exec: listener
      node_name: listener
    /talker:
      scope: system.launch.xml
      pkg: talker_pkg
      exec: talker
      node_name: talker
execution:
  deploy:
    /listener:
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
    /talker:
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
