meta:
  version: 1
  inputs:
  - path: /home/aeon/repos/nano-ros/examples/workspaces/rust/src/demo_bringup/config/system_model.record.json
    sha256: 2bb5d4f8ddda5264ef32cf59d50b448d62408e73a4222f8edabe199562b77b5b
  - path: /home/aeon/repos/nano-ros/examples/workspaces/rust/src/demo_bringup/launch/system.launch.xml
    sha256: f5a550aecbeb157bc731b831a051ba9bf3dd0158fdee9bb7e4869cf9531d697d
  resolver:
    tool: play_launch
    version: 0.8.2
  record:
    path: /home/aeon/repos/nano-ros/examples/workspaces/rust/src/demo_bringup/config/system_model.record.json
    sha256: 2bb5d4f8ddda5264ef32cf59d50b448d62408e73a4222f8edabe199562b77b5b
structure:
  scopes:
    /: {}
  nodes:
    /listener:
      scope: /
      pkg: listener_pkg
      exec: listener
    /talker:
      scope: /
      pkg: talker_pkg
      exec: talker
