[patch.crates-io]
nros-core = { path = "../../../../packages/core/nros-core" }  # nros-managed
nros-log = { path = "../../../../packages/core/nros-log" }  # nros-managed
nros-platform-cffi = { path = "../../../../packages/core/nros-platform-cffi" }  # nros-managed
nros-serdes = { path = "../../../../packages/core/nros-serdes" }  # nros-managed
