meta:
  version: 1
  inputs:
  - path: launch/cpp_safety_listener.launch.xml
    sha256: 80d9d9de0a1b554688e1e716fd906e6416ec21f14a924da430c78ecd50700302
  - path: system.toml
    sha256: 6d9bfe0a67171339123ce996a06e9568518e05497d22b8d0be00007346be878f
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
structure:
  scopes:
    cpp_safety_listener.launch.xml:
      file: cpp_safety_listener.launch.xml
  nodes:
    /safe_listener:
      scope: cpp_safety_listener.launch.xml
      pkg: cpp_safety_listener_pkg
      exec: cpp_safe_listener
      node_name: safe_listener
execution:
  deploy:
    /safe_listener:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
  features:
  - safety
