#!/usr/bin/env python3
"""Phase 380 W0 — committed generated messages must be CURRENT, in two ways.

Why this needs a gate
---------------------
`nros_serdes::schema::Message::FIELDS` is the static field list a generated
message exposes. Two things read it, and they fail in opposite ways when it is
absent:

* `nros-rmw-cyclonedds` walks it to build a `dds_topic_descriptor_t` at runtime.
  A missing schema there is loud — the backend cannot register the type.
* **`nros_serdes::size` computes a message's serialized size bound from it**
  (phase-380 W1), and a missing schema there is SILENT. The bound simply cannot
  be computed, so phase-380 W4's build-time assertion — "this subscription's
  buffer can hold its own message type" — has nothing to check and passes. The
  subscription then keeps dropping samples in the field, which is the exact
  failure W4 exists to prevent. A check that cannot see its subject does not
  fail; it reports success.

That is why this is a gate and not a convention. Measured 2026-08-26, before
phase-380 W0 regenerated them: **27 of 64** generated message structs in
`packages/interfaces` had no `FIELDS`, including `builtin_interfaces/Time`,
`builtin_interfaces/Duration` and every `rcl_interfaces` service type. The cause
was vintage, not a conditional emitter — those crates were last generated in
March/April 2026 and the schema emitter landed before July, so the three crates
nobody had regenerated since simply predated it. Nothing anywhere said so.

Scope: `packages/interfaces/**/generated/**`, the pre-generated message crates
this repo COMMITS (CLAUDE.md's exception — core crates need those messages
before any codegen runs). A user's own `generated/` tree is never committed and
is regenerated by `nros sync` from whatever CLI they have, so it is not this
gate's business.

The second property, and why one gate covers both
-------------------------------------------------
Schema presence is not the only thing that goes stale by vintage. The XCDR2
DHEADER wrap (phase-303 W4 / #0267) landed on its own timeline, and a crate can
have one and not the other: `nros-std-msgs-diag`, generated 2026-07-17, carried
`FIELDS` and emitted NO `begin_dheader`, so it could not speak XCDR2 at all —
and the first version of this gate passed it, because it only asked the first
question. That was found by phase-380 W2's property test failing, not by the
gate that exists to prevent exactly this.

So both are checked here. They share one cause (a crate nobody regenerated) and
one remedy (regenerate it), and splitting them across two gates would mean the
next dimension gets its own blind spot.

Exit 0 when every generated message struct declares `FIELDS` and every file with
a `serialize` wraps a DHEADER, 1 otherwise.
"""

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# A file that declares a message struct. `mod.rs` / `lib.rs` are re-export
# shims and declare none, so they are skipped by the struct test below rather
# than by name — a future layout that puts a struct in `mod.rs` should still be
# checked.
STRUCT_RE = re.compile(r"^pub struct \w+", re.M)
FIELDS_RE = re.compile(r"const FIELDS\s*:")
# phase-303 W4 — a generated `serialize` opens with `begin_dheader()`, a no-op
# under XCDR1 and the appendable delimiter under XCDR2. Its absence means the
# crate predates that emitter and cannot speak XCDR2.
SERIALIZE_RE = re.compile(r"fn serialize\s*\(")
DHEADER_RE = re.compile(r"begin_dheader\s*\(")


def generated_sources() -> list[Path]:
    """Tracked generated sources under `packages/interfaces`.

    Via the git index, not a filesystem walk: an untracked `target/` or a stray
    regeneration output must not be able to fail this gate.
    """
    out = subprocess.run(
        ["git", "ls-files", "packages/interfaces/**/generated/**/*.rs"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.split()
    return [ROOT / p for p in out]


def main() -> int:
    files = generated_sources()
    # Precondition, not decoration: an empty list would make the loop below
    # vacuous and this gate would report success having checked nothing — the
    # very shape it exists to catch one level down.
    if not files:
        print(
            "error: no tracked generated sources found under packages/interfaces —"
            " this gate would pass having checked nothing",
            file=sys.stderr,
        )
        return 1

    missing = []
    no_dheader = []
    checked = 0
    checked_ser = 0
    for path in files:
        text = path.read_text()
        if STRUCT_RE.search(text):
            checked += 1
            if not FIELDS_RE.search(text):
                missing.append(path.relative_to(ROOT))
        if SERIALIZE_RE.search(text):
            checked_ser += 1
            if not DHEADER_RE.search(text):
                no_dheader.append(path.relative_to(ROOT))

    if not missing and not no_dheader:
        print(
            f"generated schema coverage: OK ({checked} message struct(s) carry FIELDS,"
            f" {checked_ser} serializer(s) wrap a DHEADER)"
        )
        return 0

    if no_dheader and not missing:
        print(
            f"error: {len(no_dheader)} of {checked_ser} generated serializer(s) do not"
            f" wrap a DHEADER, so they cannot speak XCDR2.\n",
            file=sys.stderr,
        )
        for rel in no_dheader[:10]:
            print(f"  {rel}", file=sys.stderr)
        print(REMEDY, file=sys.stderr)
        return 1

    print(
        f"error: {len(missing)} of {checked} generated message struct(s) declare no"
        f" `Message::FIELDS`.\n",
        file=sys.stderr,
    )
    for rel in missing[:10]:
        print(f"  {rel}", file=sys.stderr)
    if len(missing) > 10:
        print(f"  … and {len(missing) - 10} more", file=sys.stderr)
    print(REMEDY_SCHEMA, file=sys.stderr)
    return 1


REMEDY = (
    "\nThese crates are regenerated by their own recipe, e.g."
    "\n    just generate-rcl-interfaces"
    "\n    just generate-lifecycle-msgs"
    "\n    just generate-diagnostic-msgs"
    "\n    just generate-rosgraph-msgs"
    "\nand the recipe REPLACES the generated `Cargo.toml`: restore the committed"
    "\none afterwards (`git checkout -- <crate>/Cargo.toml`) or the crate loses its"
    "\nworkspace inheritance and `[package.metadata.ros]`. Codegen output is also"
    "\nnot rustfmt-clean; run `cargo +nightly fmt -p <crate>` after."
)

REMEDY_SCHEMA = (
    "\nWithout a schema, `nros_serdes::size` cannot compute a bound for the type,"
        "\nso phase-380 W4's build-time buffer assertion has nothing to check and"
    "\nPASSES — the subscription then drops samples at runtime instead."
) + REMEDY


if __name__ == "__main__":
    sys.exit(main())
