#!/usr/bin/env python3
"""Every guard on a knob-sized C array must FIRE at 0, proven by compiling it.

The build-tier half of `check-c-array-pool-floors`. That gate is on the fast
line, must run on a bare worktree, and therefore reasons about the SOURCE: it
checks that a guard sits after the `#ifndef` fallback that defines its knob.
That catches the two shapes that shipped, and nothing else.

This one asks the compiler. It is the only way to answer "can this guard fire"
for a guard that is unreachable for a reason no static rule enumerates -- nested
inside an unrelated `#if`, disabled by a config header, or in a file the
translation unit never reaches.

WHY IT IS A SEPARATE GATE AND NOT A BRANCH OF THE OTHER ONE

It needs the zenoh-pico submodule, which the push lane does not check out. A
gate that silently weakens depending on which lane ran it reports the same OK
either way, and the reader cannot tell which answer they got -- the shape this
campaign has removed four times. Two gates, two lanes, two honest answers.

WHAT IT DOES

For every macro `check-c-array-pool-floors` classifies as GUARDED:

  * compile the file at DEFAULTS and require NO guard to fire. This is the
    half that catches `#607`: a guard placed before its `#define` reads the
    macro as undefined, which the preprocessor evaluates as 0, so it fired on
    every build.
  * compile with `-D<KNOB>=0` and require THAT guard to fire. This is the half
    that catches the first attempted fix: a guard inside the `#ifndef` is
    skipped by the very `-D` it is meant to catch.

Failures that are not a guard diagnostic are ignored on purpose. This asks one
question about the preprocessor; whether the whole TU type-checks is
`check-c`'s job, and coupling the two would make this red for reasons that say
nothing about guards.

Run:  python3 scripts/check-c-array-guard-probe.py [--self-test]
"""

import importlib.util
import os
import re
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# A guard says "must be >= N", and N is not always 1: `STRESS_SIZE`'s floor is
# 16 because `build_payload()` writes a 12-byte header with no bounds test
# (issue 1131). Matching the literal "must be >= 1" read every such guard as
# absent — and this gate reports an unreachable guard and a MISSPELLED one with
# the same message, so a substring was the wrong thing to key on.
GUARD_TEXT = re.compile(r"must be >= \d+")

# HOW EACH GUARDED FILE IS REACHED (issue 1131).
#
# This table used to be one hardcoded include set, because every guarded array
# lived in `zpico.c`. When issue 1131 ruled nine more knobs in six other files,
# the gate went red on all nine at once — not because a guard was unreachable
# but because the probe could not compile a ThreadX, Zephyr or XRCE translation
# unit with zenoh-pico's flags. A gate whose reach is narrower than the rule it
# enforces is issue 0196's shape, and here it failed CLOSED, which is the good
# direction and still wrong.
#
# Two modes, and the difference is stated per file rather than inferred:
#
#   "compile"     the real translation unit, real headers, `-fsyntax-only`.
#                 The strongest answer: an enclosing `#if` fed by a config
#                 header is evaluated as the build evaluates it.
#
#   "preprocess"  `#include` lines stripped, and every enclosing condition the
#                 guard sits under SUPPLIED here by name. For a file whose
#                 headers belong to a cross toolchain no host lane has, this is
#                 the honest maximum: it still proves the guard is positioned
#                 correctly relative to its own `#ifndef` and fires at 0, and it
#                 still catches both shapes that shipped (#607 and its first
#                 fix). What it CANNOT catch is an enclosing condition that is
#                 false in every real build — so that condition is written down
#                 here, where a reviewer can disagree with it.
#
# A guarded file in NEITHER mode is a failure. The gate must not grow a guard it
# silently does not probe.
PROBE_CONTEXT = {
    "packages/rmw/zenoh/zpico-sys/c/zpico/zpico.c": {
        "mode": "compile",
        "cc": "cc",
        "std": "c11",
        "includes": [
            "packages/rmw/zenoh/zpico-sys/c/include",
            "packages/rmw/zenoh/zpico-sys/zenoh-pico/include",
            "packages/platform/nros-platform-api/include",
        ],
        "defines": ["-DZENOH_LINUX=1", "-DZ_FEATURE_UNSTABLE_API=1"],
    },
    # `uxr/client/config.h` is generated by micro-XRCE's own cmake configure, so
    # the header set is a BUILD output rather than a checkout.
    "packages/rmw/xrce/nros-rmw-xrce/src/internal.h": {
        "mode": "preprocess",
        "cc": "cc",
        "std": "c11",
        "defines": [],
        "why": "uxr/client/config.h is generated by micro-XRCE's cmake configure",
        "enclosing": "none — the four guards sit at file scope",
    },
    # `nros_cpp_config_generated.h` is supplied per build; the checked-in copy is
    # a stub whose only content is an `#error` saying so.
    # phase-427 W4 — the NROS_COMPONENT_MAX_TIMERS guard moved here with the
    # timer pool when `component_node.hpp` was deleted. The KEY had to move in
    # the same commit: this table is only consulted for files the scan
    # DISCOVERS, so a key naming a deleted file is dead config that no
    # direction of this gate reports (see the stale-key check in `main`, added
    # by the same change for exactly that reason).
    "packages/api/nros-cpp/include/nros/node.hpp": {
        "mode": "preprocess",
        "cc": "c++",
        "std": "c++14",
        "defines": [],
        "why": "nros_cpp_config_generated.h is a per-build artifact, not a checkout",
        "enclosing": "none — the guard sits at file scope",
    },
    # Unlike `component_node.hpp` above, this header pulls in only the
    # COMMITTED `nros_cpp_ffi.h` (cbindgen output, checked in) and
    # `nros/result.hpp` — no per-build generated config — so the real TU
    # compiles from this checkout with one include path.
    "packages/api/nros-cpp/include/nros/node_parameters.hpp": {
        "mode": "compile",
        "cc": "c++",
        "std": "c++14",
        "includes": ["packages/api/nros-cpp/include"],
        "defines": [],
    },
    "packages/platform/nros-platform-threadx/src/timer.c": {
        "mode": "preprocess",
        "cc": "cc",
        "std": "c11",
        "defines": [],
        "why": "tx_api.h ships in the ThreadX kernel submodule, which no host lane checks out",
        "enclosing": "none — the guard sits at file scope",
    },
    # phase-454 W6.c — the CycloneDDS descriptor table, whose size became
    # DERIVED from the SystemModel's distinct-type count.
    #
    # `preprocess`, for the XRCE reason rather than the ThreadX one: the
    # cyclonedds submodule IS a checkout, but `dds/dds.h` pulls `dds/export.h`
    # and `dds/features.h`, which its own cmake configure GENERATES into the
    # build tree. A host lane that has not built Cyclone cannot resolve them,
    # and "compile only on a machine that happens to have built the backend"
    # is a probe that reports on the machine rather than on the guard.
    "packages/rmw/cyclonedds/nros-rmw-cyclonedds/src/descriptors.cpp": {
        "mode": "preprocess",
        "cc": "c++",
        "std": "c++14",
        "defines": [],
        "why": "dds/export.h and dds/features.h are generated by CycloneDDS's own "
               "cmake configure, not checked in",
        "enclosing": "none — the guard sits at file scope inside an anonymous namespace",
    },
    "packages/rmw/zenoh/zpico-sys/c/platform/threadx/platform.h": {
        "mode": "preprocess",
        "cc": "cc",
        "std": "c11",
        "defines": ["-DZ_FEATURE_MULTI_THREAD=1"],
        "why": "tx_api.h ships in the ThreadX kernel submodule, which no host lane checks out",
        "enclosing": "#if Z_FEATURE_MULTI_THREAD == 1 — the single-threaded build "
                     "has no _z_task_t and so no array to guard",
    },
    "zephyr/nros_platform_zephyr_shims.c": {
        "mode": "preprocess",
        "cc": "cc",
        "std": "c11",
        "defines": ["-DCONFIG_PTHREAD=1"],
        "why": "Zephyr headers come from the west workspace, not from this checkout",
        "enclosing": "#if defined(CONFIG_POSIX_API) || defined(CONFIG_PTHREAD) — a "
                     "build without pthreads has no stack array",
    },
    "packages/testing/nros-bench/stress-zenoh-zephyr/src/main.c": {
        "mode": "preprocess",
        "cc": "cc",
        "std": "c11",
        "defines": [],
        "why": "Zephyr headers come from the west workspace, not from this checkout",
        "enclosing": "none — the guard sits at file scope",
    },
    # issue 1131 — `<uORB/SubscriptionCallback.hpp>` and the px4_platform_common
    # work-queue headers ship in the PX4 SDK, whose submodule is empty in every
    # host lane. The file's own `#ifndef NROS_RMW_UORB_USE_PX4_HEADER` #error is
    # supplied by name below, exactly as the cmake does under
    # NROS_RMW_UORB_LINK_PX4.
    "packages/rmw/uorb/nros-rmw-uorb/src/px4_callback_glue.cpp": {
        "mode": "preprocess",
        "cc": "c++",
        "std": "c++14",
        "defines": ["-DNROS_RMW_UORB_USE_PX4_HEADER=1"],
        "why": "PX4's uORB + work-queue headers are an SDK checkout no host lane has",
        "enclosing": "none — the guard sits at file scope as the preprocessor sees "
                     "it (the enclosing `namespace {` is not a preprocessor "
                     "condition). NROS_RMW_UORB_USE_PX4_HEADER is supplied for "
                     "FIDELITY with the real TU, which is compiled only under "
                     "NROS_RMW_UORB_BUILD_PX4_GLUE -> NROS_RMW_UORB_LINK_PX4; it is "
                     "NOT load-bearing for this probe, and that was measured rather "
                     "than assumed — dropping it leaves the guard firing, because "
                     "the file's own `#ifndef ... #error` does not stop gcc "
                     "preprocessing. Stated so a reviewer is not misled into "
                     "thinking this probe proves more than it does.",
    },
    # phase-454 W6.d — the registry's capacity became a DERIVED number, so a
    # contract declaring no publishers and no subscriptions can now reach it
    # with 0, and `Entry g_table[0]` is a hard error in a `-Wpedantic -Werror`
    # PX4 C++ build. The guard landed with the derivation; this is the probe
    # that proves it fires.
    #
    # `compile`, not `preprocess`, and that is the whole difference from its
    # neighbour above: this TU includes only the package's own registry header,
    # `nros/rmw_ret.h` and `<cstring>` — no PX4 SDK, no per-build generated
    # config — so the real translation unit builds from this checkout with two
    # include paths and the probe asks the compiler the actual question.
    "packages/rmw/uorb/nros-rmw-uorb/src/topic_registry.cpp": {
        "mode": "compile",
        "cc": "c++",
        "std": "c++14",
        "includes": [
            "packages/rmw/uorb/nros-rmw-uorb/include",
            "packages/core/nros-rmw-abi/include",
        ],
        "defines": [],
    },
}
INCLUDE_LINE = re.compile(r"^\s*#\s*include\b")

# The submodule whose absence means this gate cannot run. Named as a FILE, not a
# directory: an initialised-but-empty submodule dir is the state that makes a
# "does the directory exist" probe lie.
SUBMODULE_PROBE = "packages/rmw/zenoh/zpico-sys/zenoh-pico/include/zenoh-pico/config.h"


def guarded_knobs():
    """{macro: path} for everything the source-level gate calls GUARDED."""
    path = os.path.join(ROOT, "scripts", "check-c-array-pool-floors.py")
    spec = importlib.util.spec_from_file_location("pool_floors", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    found = mod.scan(mod.read_sources())
    return {m: i["path"] for m, i in found.items() if i["guarded"]}


def compile_probe(rel_path, extra, ctx=None):
    """Guard diagnostics from probing `rel_path`. (text, ran) — never raises.

    `ctx` is the file's `PROBE_CONTEXT` entry; the default keeps the old zpico
    behaviour so the self-test can drive this with synthetic C.
    """
    ctx = ctx or PROBE_CONTEXT["packages/rmw/zenoh/zpico-sys/c/zpico/zpico.c"]
    src = os.path.join(ROOT, rel_path)
    tmp = None
    if ctx["mode"] == "preprocess":
        # Strip the includes rather than resolve them. See PROBE_CONTEXT: this
        # is the honest maximum for a file whose headers belong to a toolchain
        # no host lane has, and every condition it therefore cannot evaluate is
        # supplied by name in `defines`.
        suffix = ".cpp" if ctx["cc"] == "c++" else ".c"
        fd, tmp = tempfile.mkstemp(suffix=suffix)
        with os.fdopen(fd, "w") as out, open(src, errors="ignore") as inp:
            for line in inp:
                out.write("\n" if INCLUDE_LINE.match(line) else line)
        src = tmp
    cmd = [ctx["cc"]]
    cmd += ["-E", "-P"] if ctx["mode"] == "preprocess" else ["-fsyntax-only"]
    cmd += [f"-std={ctx['std']}", *ctx.get("defines", []), *extra]
    for inc in ctx.get("includes", []):
        cmd += ["-I", os.path.join(ROOT, inc)]
    cmd.append(src)
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
    except (OSError, subprocess.SubprocessError) as exc:
        return f"could not run the compiler: {exc}", False
    finally:
        if tmp:
            os.unlink(tmp)
    return r.stderr, True


def main():
    if "--self-test" in sys.argv:
        return self_test()
    if self_test() != 0:
        return 1

    if not os.path.isfile(os.path.join(ROOT, SUBMODULE_PROBE)):
        sys.path.insert(0, os.path.join(ROOT, "scripts", "build"))
        print(
            "[SKIPPED] c-array-guard-probe: zenoh-pico submodule not checked out "
            "(git submodule update --init packages/rmw/zenoh/zpico-sys/zenoh-pico)"
        )
        return 0

    knobs = guarded_knobs()
    if not knobs:
        sys.stderr.write(
            "check-c-array-guard-probe: the source gate reports NO guarded knob, "
            "so this would compile nothing and pass vacuously.\n"
        )
        return 1

    problems = []
    files = sorted(set(knobs.values()))

    # A guarded file this gate does not know how to reach is a FAILURE, never a
    # quiet omission: the whole point is that no guard ships unprobed.
    unknown = [f for f in files if f not in PROBE_CONTEXT]
    for rel in unknown:
        problems.append(
            f"{rel} carries a guard and has no PROBE_CONTEXT entry, so this gate\n"
            "      does not probe it. Add one: `compile` with the include set the\n"
            "      real TU needs, or `preprocess` naming WHY the headers are not\n"
            "      here and WHICH enclosing conditions the guard sits under."
        )

    # The OTHER direction, and the reason it exists (phase-427 W4).
    #
    # The check above asks "is every discovered guard probed?". Nothing asked
    # the reverse — "does every entry still name a file that exists?" — so when
    # `component_node.hpp` was deleted, its key became dead config and this gate
    # kept printing OK over a table with one fewer file. A gate whose subject
    # disappears passes vacuously; that is the failure this campaign keeps
    # hitting, and a table key is exactly where it hides.
    #
    # Keyed on the FILE existing, not on it being discovered: a header that
    # exists but has (legitimately) lost its last guard is not an error, while a
    # key pointing at nothing can only ever be stale.
    for rel in sorted(PROBE_CONTEXT):
        if not os.path.exists(os.path.join(ROOT, rel)):
            problems.append(
                f"{rel} has a PROBE_CONTEXT entry and DOES NOT EXIST. The entry is\n"
                "      dead config: this gate only consults the table for files the\n"
                "      scan discovers, so a key naming a deleted file is never read\n"
                "      and never reported. Move the entry with the guard, or delete it."
            )
    files = [f for f in files if f in PROBE_CONTEXT]

    # One probe per file at defaults: nothing may fire.
    for rel in files:
        out, ran = compile_probe(rel, [], PROBE_CONTEXT[rel])
        if not ran:
            sys.stderr.write(f"check-c-array-guard-probe: {out}\n")
            return 1
        fired = [l for l in out.split("\n") if GUARD_TEXT.search(l)]
        if fired:
            problems.append(
                f"{rel} fires {len(fired)} guard at DEFAULT knob values.\n"
                "      A guard that fires with no `-D` at all is not guarding a "
                "zero — it is\n"
                "      reading its macro as UNDEFINED, which the preprocessor "
                "evaluates as 0.\n"
                "      First: " + fired[0].strip()
            )

    # One probe per knob at zero: exactly that knob's guard must fire.
    for macro, rel in sorted(knobs.items()):
        if rel not in PROBE_CONTEXT:
            continue  # already reported above
        out, ran = compile_probe(rel, [f"-D{macro}=0"], PROBE_CONTEXT[rel])
        if not ran:
            sys.stderr.write(f"check-c-array-guard-probe: {out}\n")
            return 1
        if not any(GUARD_TEXT.search(l) and macro in l for l in out.split("\n")):
            problems.append(
                f"{macro} ({rel}) has a guard that does NOT fire at `-D{macro}=0`.\n"
                "      The `#if` is present but the preprocessor never reaches it "
                "with the\n"
                "      macro set — inside its own `#ifndef` (a `-D` skips the "
                "block), behind\n"
                "      an unrelated `#if`, or in a file this TU does not include."
            )

    if problems:
        sys.stderr.write(
            "check-c-array-guard-probe: %d problem(s)\n\n" % len(problems)
        )
        for p in problems:
            sys.stderr.write(f"  [FAIL] {p}\n\n")
        return 1

    print(
        "check-c-array-guard-probe: OK — %d guard(s) across %d file(s) fire at 0 "
        "and are silent at defaults." % (len(knobs), len(files))
    )
    return 0


def self_test():
    """Prove the probe can fail, on synthetic C rather than on the tree."""
    import tempfile

    good = ("#ifndef K\n#define K 8\n#endif\n"
            "#if K < 1\n#error \"K must be >= 1\"\n#endif\n"
            "int a[K];\n")
    before = ("#if K < 1\n#error \"K must be >= 1\"\n#endif\n"
              "#ifndef K\n#define K 8\n#endif\nint a[K];\n")
    inside = ("#ifndef K\n#define K 8\n"
              "#if K < 1\n#error \"K must be >= 1\"\n#endif\n#endif\n"
              "int a[K];\n")
    bad = 0
    with tempfile.TemporaryDirectory() as d:
        for name, src, want_default, want_zero in [
            ("good", good, 0, 1),
            ("before", before, 1, 1),   # fires with NO -D at all
            ("inside", inside, 0, 0),   # never fires, even at -DK=0
        ]:
            p = os.path.join(d, f"{name}.c")
            open(p, "w").write(src)
            def probe(extra):
                r = subprocess.run(["cc", "-fsyntax-only", "-std=c11", *extra, p],
                                   capture_output=True, text=True)
                return sum(1 for l in r.stderr.split("\n") if "must be >= 1" in l)
            got_d, got_z = min(probe([]), 1), min(probe(["-DK=0"]), 1)
            if (got_d, got_z) != (want_default, want_zero):
                print(f"  self-test FAIL: {name} -> default={got_d} zero={got_z}, "
                      f"want default={want_default} zero={want_zero}")
                bad += 1
    # --- the `preprocess` mode and the floor-above-one guard (issue 1131) ---
    #
    # Six of the seven guarded files belong to a cross toolchain no host lane
    # has, so they are probed with `#include` lines stripped and their enclosing
    # conditions supplied. Two things must stay true of that, or the mode is a
    # way to pass rather than a way to answer: the guard must still FIRE at 0,
    # and it must still be seen NOT to fire when the enclosing condition is
    # absent — otherwise stripping the includes would launder an unreachable
    # guard into a reachable one, which is the failure this gate exists for.
    nested = (
        '#include <a/header/that/does/not/exist.h>\n'
        "#if FEATURE_ON == 1\n"
        "#ifndef K\n#define K 64\n#endif\n"
        '#if K < 16\n#error "K must be >= 16"\n#endif\n'
        "int a[K];\n"
        "#endif\n"
    )
    fd, path = tempfile.mkstemp(suffix=".c")
    with os.fdopen(fd, "w") as fh:
        fh.write(nested)
    try:
        on = {"mode": "preprocess", "cc": "cc", "std": "c11",
              "defines": ["-DFEATURE_ON=1"]}
        off = dict(on, defines=[])

        out, ran = compile_probe(path, [], on)
        assert ran, out
        if GUARD_TEXT.search(out):
            print("  self-test FAIL: preprocess mode fires at DEFAULT")
            bad += 1
        out, ran = compile_probe(path, ["-DK=0"], on)
        # `must be >= 16`, not `>= 1`: a substring match on "must be >= 1" reads
        # this guard as absent, which is how nine correct guards went red.
        if not (ran and GUARD_TEXT.search(out)):
            print("  self-test FAIL: preprocess mode did not fire at -DK=0")
            bad += 1
        out, ran = compile_probe(path, ["-DK=0"], off)
        if not ran or GUARD_TEXT.search(out):
            print("  self-test FAIL: a guard behind an UNSUPPLIED enclosing "
                  "condition must not read as reachable")
            bad += 1
        # And the include really was stripped, not resolved.
        out, ran = compile_probe(path, ["-DK=0"], dict(on, mode="compile"))
        if not ran or GUARD_TEXT.search(out):
            print("  self-test FAIL: compile mode should not reach the guard "
                  "past a missing include")
            bad += 1
    finally:
        os.unlink(path)

    if bad:
        print(f"check-c-array-guard-probe self-test: {bad} case(s) FAILED")
        return 1
    print("check-c-array-guard-probe self-test: OK (7 cases: good, "
          "guard-before-define, guard-inside-ifndef, preprocess x4)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
