#!/usr/bin/env python3
"""Issue 1366 — an example workspace root manifest that lists a member nothing
provides, so cargo refuses to LOAD the workspace.

# The rule

If an `examples/workspaces/<ws>/` or `examples/templates/<ws>/` directory holds a
`[workspace]` root manifest ON DISK, every path in its `members` must resolve to
a directory with a `Cargo.toml`. A cargo workspace whose member list names a
directory with no manifest fails during MANIFEST PARSE — not at build time, and
not for the package you asked for. Nothing in that directory can be read after
that: `cargo build`, `cargo fmt`, `cargo metadata` and every gate built on them
die four frames deep on a path that never says why it was listed. Issue 0463's
absorbing shape, one file over.

# Why on DISK, and why this is not `check-workspace-root-build-files`

RFC-0098 D9 says a workspace has no root build file at all, and phase-445 W6's
`check-workspace-root-build-files` enforces exactly that — over `git ls-files`.
But the root that breaks a build is the one phase-383 W3.a GENERATED: it is
listed in each workspace's own `.gitignore`, so it is invisible to a tracked-file
gate, and it sits in every checkout that ran the pre-phase-445 builder while
being absent from a clone. That is the gate whose REACH is narrower than the rule
it enforces (CLAUDE.md's issue-0196 class), and this file is the other half.

Measured, issue 1366: `examples/workspaces/rust/Cargo.toml` — generated
2026-09-01, gitignored — listed `src/esp32_entry` at line 29. phase-445 W5
deleted that hand-written package and moved its generation to `[image.esp32]`
(`build/<coord>/esp32_entry`), so `src/esp32_entry` is a path no tracked
directory and no generator provides. `just build-test-fixtures lane=native`
stopped in that workspace and every later row in the lane went unbuilt.

# What a finding means, and what it does not

A finding is never "delete the member line": on `main` there is no tracked member
list to edit, and the emitter that wrote one was retired with phase-445 W5
(`builder/cargo_root.rs` classifies and RETIRES now; it no longer generates).
A generated entry is the cargo ROOT of its own image and reaches `src/*` as path
dependencies — it is not a member of anything. So a finding says one of two
things, and the report distinguishes them by reading the manifest's first line:

  GENERATED  our own retired build output. `nros build` deletes it
             (`cargo_root::retire`); so does `rm`. It is gitignored either way.
  AUTHORED   a user's file. D9 says a workspace has no root build file; the
             member it names is the evidence that the list has already drifted
             from the tree.

# Zero manifests is the expected reading, and is REPORTED

On a fresh clone this gate examines nothing, because D9 means there is nothing to
examine — which is also what a wrong glob, a wrong depth or a wrong repo root
would look like. So the OK line prints how many root manifests were read and how
many members were resolved, and `self_test` runs on the normal path with a
control in BOTH directions: a well-formed workspace must pass, and the same tree
plus one phantom member must fail.

Run: python3 scripts/check-example-workspace-members.py
"""

import os
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent / "lib"))
from git_hook_env import nros_clear_inherited_git_env  # noqa: E402

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - python < 3.11
    import tomli as tomllib  # type: ignore[no-redef]

REPO = Path(__file__).resolve().parents[1]

# The two trees whose immediate children are workspaces — the same pair
# `check-workspace-root-build-files` reads, deliberately, so the tracked half
# and the on-disk half of D9 cannot end up covering different directories.
WORKSPACE_PARENTS = ("examples/workspaces", "examples/templates")

# The first line `builder/cargo_root.rs` wrote, and the marker its `retire()`
# still keys on. Imported as a STRING rather than re-described: if the constant
# there ever changes, a manifest stops classifying as GENERATED and is reported
# as AUTHORED — louder, never quieter.
GENERATED_MARKER = "# GENERATED by `nros build`"


def roots(repo: Path) -> "list[Path]":
    """Every `<parent>/<ws>/Cargo.toml` that exists on disk, sorted."""
    out = []
    for parent in WORKSPACE_PARENTS:
        base = repo / parent
        if not base.is_dir():
            continue
        for ws in sorted(base.iterdir()):
            manifest = ws / "Cargo.toml"
            if manifest.is_file():
                out.append(manifest)
    return out


def members(manifest: Path) -> "list[str]":
    """The member paths a root manifest declares, globs expanded, sorted.

    `exclude` is honoured and a mid-path glob is skipped, matching
    `builder/discover.rs::cargo_workspace_members` — this gate must read a
    member list the way the builder does, or the two disagree about what the
    workspace contains and the gate reports on a set nothing builds.

    A manifest with no `[workspace]` table is a single PACKAGE that happens to
    sit at a workspace-shaped path (the shape `check-workspace-root-build-files`
    exempts). It declares no members and is not this gate's business.
    """
    try:
        doc = tomllib.loads(manifest.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError):
        # An unreadable or malformed root is a finding of its own kind, but not
        # THIS one; `cargo` names it precisely and immediately.
        return []
    ws = doc.get("workspace")
    if not isinstance(ws, dict):
        return []
    root = manifest.parent
    excluded = {
        root / e for e in ws.get("exclude", []) if isinstance(e, str)
    }
    out = set()
    for entry in ws.get("members", []):
        if not isinstance(entry, str):
            continue
        if entry.endswith("/*"):
            prefix = root / entry[: -len("/*")]
            if not prefix.is_dir():
                continue
            for child in prefix.iterdir():
                if child.is_dir() and child not in excluded:
                    out.add(os.path.relpath(child, root))
            continue
        if "*" in entry:
            # cargo's mid-path glob semantics are not ours to reimplement; a
            # wrong guess here would invent a finding.
            continue
        if root / entry in excluded:
            continue
        out.add(entry)
    return sorted(out)


def phantoms(repo: Path) -> "tuple[list[tuple[str, str, str]], int, int]":
    """(findings, roots read, members resolved).

    A finding is `(manifest, member, provenance)` where provenance says what
    could ever provide the path: a TRACKED directory, a GENERATOR (`build/` is
    where `nros build` writes an image's entry), or nothing.
    """
    tracked = tracked_dirs(repo)
    found = []
    seen_members = 0
    root_manifests = roots(repo)
    for manifest in root_manifests:
        rel_manifest = os.path.relpath(manifest, repo)
        ws_root = manifest.parent
        for member in members(manifest):
            seen_members += 1
            if (ws_root / member / "Cargo.toml").is_file():
                continue
            rel_member = f"{os.path.relpath(ws_root, repo)}/{member}"
            if rel_member in tracked:
                why = "tracked, but the working tree has no `Cargo.toml` there"
            elif member.split("/", 1)[0] in ("build", "target"):
                why = "generator output — `nros build` has not written it"
            else:
                why = "no tracked directory and no generator provides it"
            found.append((rel_manifest, member, why))
    return sorted(found), len(root_manifests), seen_members


def tracked_dirs(repo: Path) -> "set[str]":
    """Repo-relative directories git tracks a `Cargo.toml` in."""
    try:
        out = subprocess.run(
            ["git", "-C", str(repo), "ls-files", "-z", "--", "*Cargo.toml"],
            capture_output=True,
            text=True,
            check=True,
            env=nros_clear_inherited_git_env(dict(os.environ)),
        ).stdout
    except (OSError, subprocess.CalledProcessError):
        return set()
    return {p.rsplit("/", 1)[0] for p in out.split("\0") if "/" in p}


def generated(manifest: Path) -> bool:
    try:
        return manifest.read_text(encoding="utf-8").startswith(GENERATED_MARKER)
    except OSError:
        return False


def self_test() -> None:
    """The negative control, BOTH directions, on the normal path.

    A healthy tree has no example workspace root manifest at all, so the whole
    finder could be broken — wrong parents, wrong depth, a `members` key it
    never reads — and this gate would still print OK. These four cases are what
    stands between that and a verdict.
    """
    with tempfile.TemporaryDirectory() as tmp:
        repo = Path(tmp)

        def write(rel, body=""):
            p = repo / rel
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(body)
            return p

        # 1. A well-formed workspace: two real members. PASSES.
        write("examples/workspaces/rust/src/talker_pkg/Cargo.toml", '[package]\nname="t"\n')
        write("examples/workspaces/rust/src/listener_pkg/Cargo.toml", '[package]\nname="l"\n')
        write(
            "examples/workspaces/rust/Cargo.toml",
            '[workspace]\nmembers = ["src/talker_pkg", "src/listener_pkg"]\n',
        )
        found, n_roots, n_members = phantoms(repo)
        assert found == [], f"selftest: a well-formed workspace was reported: {found}"
        assert (n_roots, n_members) == (1, 2), f"selftest: read {n_roots} roots / {n_members} members"

        # 2. The same tree plus a phantom member — issue 1366's exact shape.
        #    FAILS, and names the member rather than the manifest alone.
        write(
            "examples/workspaces/rust/Cargo.toml",
            '[workspace]\nmembers = ["src/talker_pkg", "src/listener_pkg", "src/esp32_entry"]\n',
        )
        found, _, _ = phantoms(repo)
        assert [(m, mem) for m, mem, _ in found] == [
            ("examples/workspaces/rust/Cargo.toml", "src/esp32_entry")
        ], f"selftest: missed the phantom member: {found}"

        # 3. A `src/*` glob expands, and a listed-but-EXCLUDED absent member is
        #    not a finding — the builder skips both, so reporting either would
        #    be a finding about a package nothing builds.
        write(
            "examples/workspaces/rust/Cargo.toml",
            '[workspace]\nmembers = ["src/*", "src/gone"]\nexclude = ["src/gone"]\n',
        )
        found, _, n_members = phantoms(repo)
        assert found == [], f"selftest: the glob/exclude pair was misread: {found}"
        assert n_members == 2, f"selftest: `src/*` expanded to {n_members}, want 2"

        # 4. A root manifest with no `[workspace]` is a single PACKAGE at a
        #    workspace-shaped path. It declares no members; it is not a finding,
        #    and it must not make the gate raise.
        write("examples/templates/cpp-port/Cargo.toml", '[package]\nname="p"\n')
        found, n_roots, _ = phantoms(repo)
        assert found == [], f"selftest: a single-package root was reported: {found}"
        assert n_roots == 2, f"selftest: the templates tree was not read ({n_roots})"


def main() -> int:
    self_test()
    found, n_roots, n_members = phantoms(REPO)
    if not found:
        print(
            f"check-example-workspace-members: OK ({n_roots} root manifest(s) on disk, "
            f"{n_members} member(s) resolved under "
            + " / ".join(f"{p}/" for p in WORKSPACE_PARENTS)
            + ")"
            + (
                "\n  0 is the expected reading on a clean tree: RFC-0098 D9 says a"
                " workspace has no root build file."
                if n_roots == 0
                else ""
            )
        )
        return 0

    print(
        f"check-example-workspace-members: {len(found)} workspace member(s) "
        f"nothing provides:\n",
        file=sys.stderr,
    )
    for manifest, member, why in found:
        kind = "GENERATED" if generated(REPO / manifest) else "AUTHORED"
        print(f"  {manifest} [{kind}]\n      members += {member!r} — {why}", file=sys.stderr)
    print(
        "\nCargo refuses to LOAD a workspace whose member has no manifest, so this\n"
        "stops at MANIFEST PARSE: every `cargo build`, `cargo fmt`, `cargo metadata`\n"
        "and gate that reads this directory fails on a path that never says why it\n"
        "was listed (issue 1366; issue 0463's shape).\n"
        "\n"
        "A GENERATED root is retired build output — the phase-383 W3.a emitter that\n"
        "wrote it was deleted by phase-445 W5, and `nros build` removes the file it\n"
        "left behind (`builder/cargo_root::retire`). It is gitignored; delete it.\n"
        "\n"
        "An AUTHORED root should not exist either: RFC-0098 D9 makes a workspace a\n"
        "directory of packages with NO root build file. The cargo root is the entry\n"
        "`nros build` generates, `build/<coord>/<entry>/Cargo.toml`, which reaches\n"
        "`src/*` as path dependencies — a generated entry is not a member of\n"
        "anything, so it must not be listed as one.",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    sys.exit(main())
