#!/usr/bin/env python3
"""phase-320 W2.c — generate book/src/reference/board-support-tiers.md.

Generated, not hand-written, because the hand-written one drifted: the vendor
matrix claimed ARM FVP was "Tested" under a legend defining Tested as "boots in
CI", for a target no CI lane can boot.

Scope note, deliberately narrow: this generates the table of IN-TREE BOARD
PACKAGES from `packages/boards/board-support.toml`. It does NOT generate
`supported-boards.md`, which is a procurement matrix carrying vendor, MCU and
part rows for hardware that has never had a crate in this tree (nRF52840-DK,
LPC55S69, MIMXRT1170, …). Generating that from the registry would silently
delete every row the registry cannot express. Two documents, two jobs, and the
generated one says which is authoritative for what.

  --check   exit 1 if the committed file differs from freshly generated output
"""

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "book/src/reference/board-support-tiers.md"
# Reuse the registry parser from the gate so there is ONE reader, not two
# (CLAUDE.md: add one shared helper rather than a second spelling).
import importlib.util  # noqa: E402

_spec = importlib.util.spec_from_file_location(
    "board_tier_gate", ROOT / "scripts/check-board-tiers.py")
assert _spec is not None and _spec.loader is not None, "cannot load check-board-tiers.py"
_gate = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_gate)

TIER_TITLES = {
    "1": ("Tier 1 — supported",
          "`just ci` exercises it, it has asserted runtime coverage, and a nightly "
          "lane builds it. **A regression fails before merge.**"),
    "2": ("Tier 2 — verified",
          "Asserted runtime coverage and a nightly lane, but not in `just ci`. "
          "Breakage is found within a day."),
    "3": ("Tier 3 — build-only",
          "Compiles. **No CI lane can boot it** — real hardware or a license-gated "
          "model is required. Nobody has booted it recently unless a maintainer did "
          "so by hand."),
    "scaffold": ("Scaffold — not supported",
                 "Structurally incomplete. Distinct from tier 3: tier 3 is "
                 "finished-but-unverified, scaffold is unfinished. Do not build on "
                 "these."),
    "infra": ("Infrastructure — not boards",
              "Shared traits, family drivers, ABI mirrors, PACs, and descriptor "
              "directories. No platform, no tier promise."),
}


def render(entries):
    lines = []
    lines.append("<!-- GENERATED by scripts/gen-board-support-table.py — do not edit by hand.")
    lines.append("     Source of truth: packages/boards/board-support.toml")
    lines.append("     Regenerate: python3 scripts/gen-board-support-table.py -->")
    lines.append("")
    lines.append("# Board Support Tiers")
    lines.append("")
    lines.append("What nano-ros promises for each in-tree board package, and why.")
    lines.append("")
    lines.append("Every tier here is **checked against evidence** by "
                 "`just check-board-tiers`: a board cannot claim tier 1 or 2 without "
                 "runtime cells in the test matrix, cannot claim tier 3 while holding "
                 "runtime cells, and cannot be omitted from this table at all. That "
                 "gate exists because the previous hand-written table drifted into "
                 "claiming a license-gated target was CI-tested.")
    lines.append("")
    lines.append("For **procurement guidance on parts that have no crate in this tree** "
                 "(Nordic, NXP, TI and friends), see "
                 "[Supported Boards](supported-boards.md). That table is hand-maintained "
                 "and covers hardware this one cannot describe; this table is generated "
                 "and covers what is actually in the repo.")
    lines.append("")
    for tier in ("1", "2", "3", "scaffold", "infra"):
        rows = [e for e in entries if str(e.get("tier", "")) == tier]
        if not rows:
            continue
        title, blurb = TIER_TITLES[tier]
        lines.append(f"## {title}")
        lines.append("")
        lines.append(blurb)
        lines.append("")
        lines.append("| Board package | Platform | Maintainers | Notes |")
        lines.append("|---|---|---|---|")
        for e in sorted(rows, key=lambda r: r.get("crate", "")):
            plat = e.get("matrix_platform") or "—"
            who = ", ".join(e.get("maintainers") or []) or "*unassigned*"
            note = (e.get("notes") or "").replace("|", "\\|")
            gated = e.get("gated_sdk")
            if gated and gated != "none-modelled":
                note = f"**Gated SDK: `{gated}`.** {note}".strip()
            lines.append(f"| `{e.get('crate','?')}` | {plat} | {who} | {note} |")
        lines.append("")
    lines.append("## Maintainers")
    lines.append("")
    lines.append("A tier is a promise, and `just check-board-tiers` requires someone to "
                 "have made it: **tier 1 needs 3 named maintainers, tier 2 needs 2, "
                 "tier 3 needs 1** (phase-375 W1). Rust's target-tier policy is the "
                 "model — a named person per target, and demotion when the maintainer "
                 "becomes unreachable; that mechanism, not the directory layout, is what "
                 "actually retires abandoned targets.")
    lines.append("")
    lines.append("Rows that predate the rule are grandfathered by "
                 "`scripts/board-maintainer-baseline.json`, a list that only shrinks. So "
                 "the rule binds a NEW board immediately and an existing one as its owner "
                 "is found — a gate that failed all 22 rows on the day it landed would "
                 "have been bypassed instead. Recording an owner is the point; inventing "
                 "one would be worse than leaving the row at the tier it can carry.")
    lines.append("")
    return "\n".join(lines)


def main():
    entries = _gate.parse_registry(_gate.REGISTRY.read_text())
    out = render(entries)
    if "--check" in sys.argv:
        if not OUT.exists():
            print(f"[FAIL] {OUT.relative_to(ROOT)} does not exist — run "
                  "`python3 scripts/gen-board-support-table.py`", file=sys.stderr)
            return 1
        if OUT.read_text() != out:
            print(f"[FAIL] {OUT.relative_to(ROOT)} is stale — regenerate with "
                  "`python3 scripts/gen-board-support-table.py` and commit", file=sys.stderr)
            subprocess.run(["git", "--no-pager", "diff", "--stat", "--", str(OUT)], cwd=ROOT)
            return 1
        print("board support table is up to date.")
        return 0
    OUT.write_text(out)
    print(f"wrote {OUT.relative_to(ROOT)} ({len(entries)} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
