#!/usr/bin/env bash
#
# RFC-0054 (phase-299) — regenerate the COMMITTED Rust bindings for the
# C-header ABI SSoT packages. The C headers are the single source of
# truth; the Rust side ships this generated file, so embedded/cross
# builds never need libclang. Run after ANY edit to
# `packages/core/nros-rmw-abi/include/nros/*.h`, commit the result.
# The `check-abi-bindings` gate re-runs this and fails on a diff.
#
# --no-layout-tests: bindgen's generated size/offset asserts bake the
# HOST's (64-bit) layout literals, which are WRONG on 32-bit embedded
# targets (vtable 144 vs 288 bytes) — the same file compiles for every
# target. Layout parity needs no assert: both sides are repr(C) over
# identical field types, laid out by each target's own ABI rules.
#
# bindgen-cli is PINNED — output differs across versions, which would
# make the diff gate flap. Install with:
#   cargo install bindgen-cli --locked --version "$BINDGEN_PIN"

set -euo pipefail
cd "$(dirname "$0")/.."

BINDGEN_PIN="0.72.1"

if ! command -v bindgen >/dev/null 2>&1; then
    echo "error: bindgen-cli not installed (cargo install bindgen-cli --locked --version $BINDGEN_PIN)" >&2
    exit 2
fi
have="$(bindgen --version | awk '{print $2}')"
if [ "$have" != "$BINDGEN_PIN" ]; then
    echo "error: bindgen $have != pinned $BINDGEN_PIN (output would drift; reinstall the pin)" >&2
    exit 2
fi

# ---- RMW surface: nros-rmw-abi headers -> nros-rmw-cffi/src/generated.rs
RMW_ABI="packages/core/nros-rmw-abi"
RMW_OUT="packages/core/nros-rmw-cffi/src/generated.rs"

wrapper="$(mktemp --suffix=.h)"
trap 'rm -f "$wrapper"' EXIT
cat > "$wrapper" << 'EOF'
#include <nros/rmw_ret.h>
#include <nros/rmw_entity.h>
#include <nros/rmw_event.h>
#include <nros/rmw_vtable.h>
#include <nros/rmw_transport.h>
EOF

{
    echo "//! AUTO-GENERATED by scripts/gen-abi-bindings.sh (bindgen $BINDGEN_PIN) — DO NOT EDIT."
    echo "//!"
    echo "//! Source of truth: \`packages/core/nros-rmw-abi/include/nros/*.h\` (RFC-0054)."
    echo "//! Edit the headers, rerun the script, commit both."
    echo "#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals)]"
    echo "#![allow(unsafe_op_in_unsafe_fn, clippy::missing_safety_doc)]"
    bindgen "$wrapper" \
        --use-core \
        --ctypes-prefix core::ffi \
        --default-enum-style moduleconsts \
        --default-macro-constant-type signed \
        --allowlist-item 'nros_rmw_.*|NROS_RMW_.*|nros_transport_.*|NROS_TRANSPORT_.*' \
        --no-layout-tests \
        --sort-semantically \
        -- -I"$RMW_ABI/include"
} > "$RMW_OUT"

rustfmt +nightly "$RMW_OUT" 2>/dev/null || true
echo "regenerated $RMW_OUT ($(wc -l < "$RMW_OUT") lines, bindgen $BINDGEN_PIN)"

# ---- Platform surface: nros-platform-api headers -> nros-platform-cffi/src/generated.rs
# Function DECLARATIONS only (the port side defines them via the
# nros_platform_export_*! macros, which stay hand-written — they emit
# definitions, not declarations). platform_zephyr.h is excluded: it is a
# Zephyr-conditional surface consumed C-side only.
PLAT_API="packages/core/nros-platform-api"
PLAT_OUT="packages/core/nros-platform-cffi/src/generated.rs"

plat_wrapper="$(mktemp --suffix=.h)"
trap 'rm -f "$wrapper" "$plat_wrapper"' EXIT
cat > "$plat_wrapper" << 'EOF2'
#include <nros/platform.h>
#include <nros/platform_net.h>
#include <nros/platform_timer.h>
EOF2

{
    echo "//! AUTO-GENERATED by scripts/gen-abi-bindings.sh (bindgen $BINDGEN_PIN) — DO NOT EDIT."
    echo "//!"
    echo "//! Source of truth: \`packages/core/nros-platform-api/include/nros/platform*.h\` (RFC-0054)."
    echo "//! Edit the headers, rerun the script, commit both."
    echo "#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals)]"
    echo "#![allow(unsafe_op_in_unsafe_fn, clippy::missing_safety_doc)]"
    bindgen "$plat_wrapper" \
        --use-core \
        --ctypes-prefix core::ffi \
        --default-enum-style moduleconsts \
        --default-macro-constant-type signed \
        --allowlist-item 'nros_platform_.*|NROS_PLATFORM_.*' \
        --no-layout-tests \
        --sort-semantically \
        -- -I"$PLAT_API/include"
} > "$PLAT_OUT"

rustfmt +nightly "$PLAT_OUT" 2>/dev/null || true
echo "regenerated $PLAT_OUT ($(wc -l < "$PLAT_OUT") lines, bindgen $BINDGEN_PIN)"

# ---- Board surface: nros-board-cffi header -> nros-board-cffi/src/generated.rs
# Declarations only; the nros_board_export! macro (definitions, port side)
# stays hand-written — same split as the platform surface.
BOARD_API="packages/boards/nros-board-cffi"
BOARD_OUT="packages/boards/nros-board-cffi/src/generated.rs"

{
    echo "//! AUTO-GENERATED by scripts/gen-abi-bindings.sh (bindgen $BINDGEN_PIN) — DO NOT EDIT."
    echo "//!"
    echo "//! Source of truth: \`packages/boards/nros-board-cffi/include/nros/board.h\` (RFC-0054)."
    echo "//! Edit the header, rerun the script, commit both."
    echo "#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals)]"
    echo "#![allow(unsafe_op_in_unsafe_fn, clippy::missing_safety_doc)]"
    bindgen "$BOARD_API/include/nros/board.h" \
        --use-core \
        --ctypes-prefix core::ffi \
        --default-enum-style moduleconsts \
        --default-macro-constant-type signed \
        --enable-function-attribute-detection \
        --allowlist-item 'nros_board_.*|NROS_BOARD_.*' \
        --no-layout-tests \
        --sort-semantically \
        -- -I"$BOARD_API/include"
} > "$BOARD_OUT"

rustfmt +nightly "$BOARD_OUT" 2>/dev/null || true
echo "regenerated $BOARD_OUT ($(wc -l < "$BOARD_OUT") lines, bindgen $BINDGEN_PIN)"
