#!/usr/bin/env python3
"""Generate book/src/reference/support-status.md.

The support-status page (CI tiers, platform/RTOS pins, RMW versions,
ROS editions, toolchains) answers "what exactly am I getting, at which
version, tested how hard" — the questions a Rust user answers from
rustc's platform-support page. Version strings are PARSED from the
tree's single sources of truth so a pin bump moves this page in the
same commit or fails the gate:

  * `nros-sdk-index.toml`  — every `[tool.*]` / `[source.*]` version
  * `rust-toolchain.toml`  — the Rust channel + pinned cross targets
  * `packages/rmw/zenoh/zpico-sys/zenoh-pico/version.txt` — cross-check
    against the index's zenoh-pico row (they have disagreed before)

Prose (tier meanings, edition semantics, the router story) is static
data here, with citations.

Run:  python3 scripts/gen-support-status.py [--check]
Gate: just check-support-status
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "book", "src", "reference", "support-status.md")
INDEX = os.path.join(ROOT, "nros-sdk-index.toml")


def parse_index_versions():
    """{section-name: version} for every [tool.X] / [source.X]."""
    versions, current = {}, None
    for line in open(INDEX, encoding="utf8"):
        m = re.match(r"\[(tool|source)\.([A-Za-z0-9_-]+)\]", line.strip())
        if m:
            current = m.group(2)
            continue
        if line.strip().startswith("["):
            current = None
            continue
        m = re.match(r'version\s*=\s*"([^"]+)"', line.strip())
        if m and current and current not in versions:
            versions[current] = m.group(1)
    return versions


def rust_toolchain():
    text = open(os.path.join(ROOT, "rust-toolchain.toml"), encoding="utf8").read()
    channel = re.search(r'channel\s*=\s*"([^"]+)"', text).group(1)
    targets = re.findall(r'"([a-z0-9_]+-[a-z0-9_-]+)"', text.split("targets")[1])
    return channel, targets


def zpico_version_txt():
    p = os.path.join(ROOT, "packages/rmw/zenoh/zpico-sys/zenoh-pico/version.txt")
    return open(p, encoding="utf8").read().strip() if os.path.exists(p) else None


def v(versions, key):
    if key not in versions:
        sys.exit(f"gen-support-status: `[{key}]` missing from nros-sdk-index.toml "
                 "(renamed? update the curated rows here in the same commit).")
    return versions[key]


def render():
    ver = parse_index_versions()
    channel, targets = rust_toolchain()
    zp_txt = zpico_version_txt()
    zp_idx = v(ver, "zenoh-pico")
    if zp_txt and not zp_idx.startswith(zp_txt.split("-")[0][:3]):
        sys.exit(f"gen-support-status: zenoh-pico version disagrees — "
                 f"index says {zp_idx}, version.txt says {zp_txt}.")

    lines = [
        "<!-- GENERATED by scripts/gen-support-status.py — do not edit by hand.",
        "     Regenerate: python3 scripts/gen-support-status.py",
        "     Gated by:   just check-support-status -->",
        "",
        "# Support Status",
        "",
        "What you get, at which version, tested how hard — the analogue of",
        "Rust's platform-support page. Version strings on this page are",
        "parsed from `nros-sdk-index.toml` and `rust-toolchain.toml` (the",
        "pinning SSoTs), so they cannot drift from what `nros setup`",
        "actually installs.",
        "",
        "## CI tiers — what \"supported\" means",
        "",
        "| Tier | Lane | Runs | Guarantee |",
        "|---|---|---|---|",
        "| **1** | `ci` (every change) | Host-native builds + native fixtures, all gates | The logic and the seams are sound. Says nothing about embedded targets. |",
        "| **2** | `ci-matrix` (when core/codegen/cmake move) | 1-wise cover: every platform, language, RMW, and kind appears at least once (~28 % of the coordinate space) | Each axis value builds and runs somewhere — but pairings are NOT covered. |",
        "| **2-nightly** | `ci-matrix-nightly` | Pairwise cover (~70 %) | Platform×language and RMW×language interactions surface here, within a day. |",
        "| **3** | `ci-full` (pre-release) | The whole matrix | Everything the tree claims, verified together. |",
        "",
        "Per-board tier membership is generated on its own page:",
        "[Board Support Tiers](board-support-tiers.md). The hand-maintained",
        "procurement view (including boards with no in-tree crate) is",
        "[Supported Boards](supported-boards.md).",
        "",
        "## RTOS / platform source pins",
        "",
        "`nros setup <board>` fetches exactly these (shared store",
        "`${NROS_HOME:-~/.nros}/sdk`):",
        "",
        "| Component | Pinned version | Used by |",
        "|---|---|---|",
        f"| FreeRTOS kernel | `{v(ver,'freertos-kernel')}` | FreeRTOS boards (QEMU MPS2-AN385, overlays) |",
        f"| lwIP | `{v(ver,'lwip')}` | FreeRTOS networking |",
        f"| ThreadX | `{v(ver,'threadx')}` | ThreadX (Linux sim + QEMU RISC-V64) |",
        f"| NetX Duo | `{v(ver,'threadx-netxduo')}` | ThreadX networking |",
        f"| NuttX kernel | `{v(ver,'nuttx-kernel')}` | NuttX (QEMU armv7a / rv32) |",
        f"| Zephyr SDK | `{v(ver,'zephyr-sdk')}` (+ `{v(ver,'zephyr-sdk-1-0-1')}` for the 4.4 rolling line) | Zephyr module builds |",
        f"| mbedTLS | `{v(ver,'mbedtls')}` | zenoh TLS transport |",
        "",
        "These pins are **decisions, not lags** — they move only with a",
        "reason, tested together (see",
        "[Integrating into a Vendored Tree](../getting-started/vendored-tree.md)).",
        "",
        "## RMW backends — versions and interop pairing",
        "",
        "| Backend | Client side (pinned) | Host side | Pairing rule |",
        "|---|---|---|---|",
        f"| **Zenoh** | zenoh-pico `{zp_idx}` (vendored submodule) | Router = the one **ROS ships**: `ros2 run rmw_zenoh_cpp rmw_zenohd` — nano-ros deliberately vendors no router (RFC-0075) | zenoh-pico's wire protocol is stable across zenoh 1.x, so the pinned client interops with a newer ROS-shipped router (issue 0291) |",
        f"| **XRCE-DDS** | Micro-XRCE-DDS client `{v(ver,'micro-xrce-dds-client')}` + Micro-CDR `{v(ver,'micro-cdr')}` | Agent `{v(ver,'xrce-agent')}` (installed by `nros setup … --rmw xrce`) | Client and agent are pinned to the same upstream release |",
        f"| **Cyclone DDS** | fork `{v(ver,'cyclonedds-src')}` — upstream 0.10.5 + carried patches ([fork delta](https://github.com/NEWSLabNTU/nano-ros/blob/main/docs/reference/cyclonedds-fork-delta.md)) | Talks RTPS directly to `rmw_cyclonedds_cpp` | Pinned to the Cyclone **ROS ships** (`ros-humble-cyclonedds` 0.10.5) — upstream 11.x is deliberately NOT a rebase target until a distro migration (issue 0507) |",
        "",
        "Per-feature coverage across the three backends:",
        "[Per-RMW Feature Matrix](rmw-feature-matrix.md).",
        "",
        "## ROS 2 editions",
        "",
        "| Edition | Feature / flag | Status | Notes |",
        "|---|---|---|---|",
        "| Humble | `ros-humble` (default) | Supported | `TypeHashNotSupported` key expressions, XCDR1. No `rmw_zenoh_cpp` apt package — zenoh interop on Humble needs a source overlay, or use Cyclone DDS. |",
        "| Iron | `ros-iron` | Supported | RIHS01 type hashes. Same zenoh-apt caveat as Humble. |",
        "| Jazzy | `ros-jazzy` | Supported | RIHS01; ships `ros-jazzy-rmw-zenoh-cpp` — the zenoh-interop reference edition. XCDR2/appendable is tracked separately (phase-303). |",
        "",
        "Pick the edition of the ROS system you interop with — mismatched",
        "editions discover nothing (different key expressions).",
        "",
        "## Toolchains",
        "",
        "| Tool | Pinned version |",
        "|---|---|",
        f"| Rust | `{channel}` channel (`rust-toolchain.toml`); pinned cross targets: {', '.join('`'+t+'`' for t in targets)}. `rustfmt` runs on nightly (nightly-only options). |",
        f"| Arm GCC (`arm-none-eabi`) | `{v(ver,'arm-none-eabi-gcc')}` |",
        f"| RISC-V GCC (`riscv-none-elf`) | `{v(ver,'riscv-none-elf-gcc')}` |",
        f"| QEMU (patched, Arm) | `{v(ver,'qemu')}` |",
        f"| QEMU (Espressif fork, ESP32-C3) | `{v(ver,'esp32-qemu')}` |",
        f"| espflash | `{v(ver,'espflash')}` |",
        f"| Corrosion (CMake↔Cargo) | `{v(ver,'corrosion')}` (≥ 0.6.0 required — older versions share one build dir across workspace roots and break the `mixed` link) |",
        f"| OpenOCD | `{v(ver,'openocd')}` |",
        f"| sccache | `{v(ver,'sccache')}` |",
        "",
        "`-nros<N>` suffixes mark builds re-packaged (or patched) for the SDK",
        "store; the base version is the upstream release.",
        "",
        "## Related",
        "",
        "- [Install](../getting-started/installation.md) — how these get onto",
        "  a machine (`nros setup`, prebuilt-vs-source rules)",
        "- [Per-RMW Feature Matrix](rmw-feature-matrix.md)",
        "- [Board Support Tiers](board-support-tiers.md) (generated) ·",
        "  [Supported Boards](supported-boards.md) (procurement view)",
        "- [Integrating into a Vendored Tree](../getting-started/vendored-tree.md)",
        "  — pinning and upgrading these from a company tree",
        "",
    ]
    return "\n".join(lines)


def main():
    content = render()
    if "--check" in sys.argv:
        on_disk = open(OUT, encoding="utf8").read() if os.path.exists(OUT) else ""
        if on_disk != content:
            sys.exit("check-support-status: STALE — regenerate with "
                     "python3 scripts/gen-support-status.py and commit.")
        print("support-status OK")
        return
    with open(OUT, "w", encoding="utf8") as fh:
        fh.write(content)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
