#!/usr/bin/env python3
"""Generate `packages/cli/cli-source-dirs.txt` — the CLI freshness closure.

Issue 0604. `nros source-stamp` decides whether the in-tree CLI matches the
tree it was built from, and every fixture in the repo keys on that answer. Its
input set is `packages/cli` plus the in-repo crates the `nros` binary is
compiled from. Getting that set wrong is expensive in both directions:

* **too small** — `setup-cli` reports success without rebuilding, and the tree
  runs a museum CLI. Issue 0561 is that failure for the play_launch pin;
  phase-330 W1.a is it for `nros-orchestration-ir`.
* **too large** — an edit to a crate the CLI never compiles re-stales the CLI,
  and a stale CLI re-stales every fixture that keys on its stamp. That is the
  cold-leaf cascade issue 0604 exists to attribute.

## Why a generated file instead of a walk

`source_stamp.rs` is `include!`d by `build.rs`, so it may not use a TOML crate
and cannot shell `cargo metadata` (which takes the package-cache lock cargo is
already holding during a build). It therefore walked `path = "…"` textually.
Measured 2026-08-16, that walk was wrong in BOTH directions at once:

    textual walk : 23 dirs outside packages/cli
    cargo resolve:  8

    under-watched (CLI compiles them, stamp blind):
        packages/core/nros-core, packages/core/nros-rmw
    over-watched (17), all hanging off ONE edge:
        nros-board-common's `nros-platform = { optional = true }`, which
        `deploy-overlay` enables and the CLI does not — dragging in every
        platform port, nros-node, nros-log, nros-smoltcp, mps2-an385-pac,
        zpico-alloc, nros-ghost-types and three generated msg crates.

The under-watch has a single cause worth naming: `nros-rmw = { workspace =
true }` in `nros-orchestration-ir` carries no `path =` at all — the path lives
in the ROOT manifest's `[workspace.dependencies]`. A textual scan of the leaf
manifest cannot see a workspace-inherited dep, so it missed `nros-rmw` and,
through it, `nros-core`. Editing either left the stamp FRESH.

Fixing the walk means hand-rolling workspace-dep inheritance AND optional-dep
feature resolution inside a file that cannot parse TOML. Cargo already computes
both, exactly, so record its answer instead: this script writes the list, the
stamp reads it, and `check-cli-source-dirs` fails when the file disagrees with
cargo. One spelling, no resolver, and the gate is what makes it safe to trust.

Run: python3 scripts/gen-cli-source-dirs.py [--check]
"""

import argparse
import json
import os
import subprocess
import sys
from collections import deque
from pathlib import Path
import sys as _sys
from pathlib import Path as _Path
_sys.path.insert(0, str(_Path(__file__).resolve().parent / "lib"))
from tracked import tracked  # issue 0721: index lookup, not a walk

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "packages" / "cli" / "cli-source-dirs.txt"

# `just setup-cli` builds exactly this: `cargo build --release --bin nros`. The
# PACKAGE is `nros-cli`; `nros` is the binary it produces (`[[bin]] name`), and
# cargo metadata keys on the package name.
ROOT_PKG = "nros-cli"

HEADER = """\
# GENERATED by scripts/gen-cli-source-dirs.py — do not edit by hand.
#
# In-repo crate directories OUTSIDE packages/cli that the `nros` binary is
# compiled from. `source_stamp.rs` hashes these plus all of `packages/cli`;
# `check-cli-source-dirs` fails when this file disagrees with cargo's resolve.
#
# Regenerate: python3 scripts/gen-cli-source-dirs.py
"""


def embedded_input_dirs():
    """Directories of parent-relative `include_str!`/`include_bytes!` targets.

    phase-368 W8 — `workspace_scaffold.rs` embeds the copy-out templates from
    `examples/templates/…` via `include_str!`. Those files are rustc inputs
    (cargo rebuilds on their edits via dep-info) that the CRATE GRAPH does not
    name, so the cargo resolve below is blind to them — the exact "stamp
    smaller than the build" failure this script exists to prevent, one layer
    down. Scan the CLI workspace's sources for parent-relative
    `include_str!`/`include_bytes!` string literals resolving OUTSIDE
    packages/cli and fold in their `examples/templates/<name>`-depth
    directory, so a template gains files without regenerating this list.

    Only direct string literals are seen; a macro-built path would be missed —
    keep embedded paths literal.
    """
    import re
    cli = REPO / "packages" / "cli"
    pat = re.compile(r'include_(?:str|bytes)!\(\s*"(\.\./[^"]+)"')
    dirs = set()
    for src in tracked(cli, suffix=".rs"):
        if "target" in src.parts:
            continue
        try:
            text = src.read_text()
        except (UnicodeDecodeError, OSError):
            continue
        for m in pat.finditer(text):
            resolved = (src.parent / m.group(1)).resolve()
            try:
                rel = resolved.relative_to(REPO)
            except ValueError:
                continue  # outside the repo: not ours to watch
            if rel.parts[:2] == ("packages", "cli"):
                continue  # already hashed wholesale
            depth = min(3, max(1, len(rel.parts) - 1))
            dirs.add("/".join(rel.parts[:depth]))
    return dirs


def cargo_metadata():
    env = dict(os.environ)
    # `--locked` is injected project-wide by the `scripts/bin/cargo` PATH shim;
    # metadata does not resolve anything new, and a lock this tree cannot
    # satisfy is the gate's problem, not this script's.
    env["NROS_CARGO_FLAGS"] = ""
    proc = subprocess.run(
        ["cargo", "metadata", "--format-version", "1",
         "--manifest-path", str(REPO / "packages" / "cli" / "Cargo.toml")],
        capture_output=True, text=True, env=env,
    )
    if proc.returncode != 0:
        sys.stderr.write(proc.stderr)
        raise SystemExit("gen-cli-source-dirs: `cargo metadata` failed")
    return json.loads(proc.stdout)


def closure_dirs():
    """Repo-relative dirs of in-repo packages the `nros` bin compiles, sans cli."""
    md = cargo_metadata()
    pkgs = {p["id"]: p for p in md["packages"]}
    nodes = {n["id"]: n for n in md["resolve"]["nodes"]}

    roots = [i for i, p in pkgs.items() if p["name"] == ROOT_PKG]
    if not roots:
        raise SystemExit(f"gen-cli-source-dirs: package `{ROOT_PKG}` not in the cli workspace")

    seen, queue = set(), deque(roots)
    while queue:
        i = queue.popleft()
        if i in seen:
            continue
        seen.add(i)
        for dep in nodes.get(i, {}).get("deps", []):
            kinds = {k["kind"] for k in dep["dep_kinds"]}
            # `kind` is None for a normal dep and "build"/"dev" otherwise. A
            # build-dependency's sources ARE compiled, so they belong; dev-only
            # edges are not part of `--bin nros`.
            if kinds <= {"dev"}:
                continue
            queue.append(dep["pkg"])

    dirs = set()
    for i in seen:
        manifest = Path(pkgs[i]["manifest_path"])
        try:
            rel = manifest.parent.relative_to(REPO)
        except ValueError:
            continue  # registry crate or out-of-tree path
        rel = rel.as_posix()
        if rel.startswith("packages/cli"):
            continue  # watched wholesale by the stamp
        # Vendored submodules are tracked but are not nano-ros build inputs;
        # `is_cli_input` drops them anyway, so listing them would be noise.
        if "/third-party/" in rel or "/testing_workspaces/" in rel:
            continue
        dirs.add(rel)
    dirs |= embedded_input_dirs()
    return sorted(dirs)


def render(dirs):
    return HEADER + "".join(d + "\n" for d in dirs)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="fail if the committed file disagrees with cargo's resolve")
    args = ap.parse_args()

    want = render(closure_dirs())

    if not args.check:
        OUT.write_text(want)
        n = sum(1 for line in want.splitlines() if line and not line.startswith("#"))
        print(f"gen-cli-source-dirs: wrote {OUT.relative_to(REPO)} ({n} dir(s))")
        return 0

    have = OUT.read_text() if OUT.is_file() else ""
    if have == want:
        n = sum(1 for line in want.splitlines() if line and not line.startswith("#"))
        print(f"check-cli-source-dirs: OK ({n} dir(s) match cargo's resolve)")
        return 0

    def body(text):
        return [line for line in text.splitlines() if line and not line.startswith("#")]

    missing = sorted(set(body(want)) - set(body(have)))
    extra = sorted(set(body(have)) - set(body(want)))
    print("check-cli-source-dirs: packages/cli/cli-source-dirs.txt is out of date.",
          file=sys.stderr)
    for d in missing:
        print(f"  + {d}   (the CLI compiles it; the stamp is BLIND to edits there)",
              file=sys.stderr)
    for d in extra:
        print(f"  - {d}   (the CLI does not compile it; edits there re-stale the CLI"
              " and every fixture)", file=sys.stderr)
    print("\n  Regenerate:  python3 scripts/gen-cli-source-dirs.py\n"
          "\n"
          "  Issue 0604 — this list is the CLI freshness closure. A missing entry\n"
          "  makes `just setup-cli` report success without rebuilding (issue 0561's\n"
          "  failure mode); an extra one re-stales the CLI, and a stale CLI re-stales\n"
          "  every fixture keyed on its stamp.\n", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
