#!/usr/bin/env python3
"""Generate `packages/cli/probe-source-dirs.txt` — the metadata probe's inputs.

Issue 1578. `nros sync` decides whether a component's metadata sidecar is
current before it spends a harness build re-probing it. It used to key that on
the COMPONENT's own sources alone (`source_digest(package_root)`), but what a
probe REPORTS is decided by nano-ros crates too: the recording backend
(`packages/rmw/metadata`), the declarative registrar (`nros`), and, since
phase-457 W5, `nros-node`'s `DeclaredSubscriptionShape::in_place_capable()`,
which is literally the `in_place` value the sidecar carries. A change there left
the sidecar reading "already current". Measured: toggling that one bool
true -> false -> true gave `1 rebuilt`, `1 rebuilt`, then `0 rebuilt, 1 already
current` with a sidecar saying `false` against a source saying `true`.

So the probe's freshness key folds in the nano-ros crates the probe COMPILES.
This script records that set, and `check-probe-source-dirs` fails when the file
disagrees with cargo — the mechanism `gen-cli-source-dirs.py` uses for the CLI's
own stamp (issue 0627), for the same reason: a hand-written list is only as
complete as whoever wrote it, and cargo already knows the answer.

## Why `cargo tree -p`, not `cargo metadata`

`cargo metadata` resolves the WHOLE workspace with features unified across every
member, so `nros` would drag in every RMW backend some other member enables —
an over-watch that re-probes every component on a zpico edit. `cargo tree -p
<pkg> -F <features>` resolves one package as if it were built alone, which is
what a probe build is. The roots and features below are read off the two probe
builders, not chosen:

* the Rust harness (`metadata_build.rs`) depends on `nros` with `std`, and on
  `nros-platform-cffi` with `posix-c-port`; `metadata-mode` is added because it
  is the feature that turns on `nros-node/registration-observer`, the code that
  reports `in_place`;
* the C/C++ probe (`metadata_probe_cmake.rs`) builds `nros-cpp` with
  `metadata-mode` and links `nros-c`.

Over-watch is the safe direction here and under-watch is not: an extra dir costs
a re-probe, a missing one ships a stale `in_place`, and a stale `true` prices an
endpoint at no receive region the executor then claims.

Run: python3 scripts/gen-probe-source-dirs.py [--check]
"""

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "packages" / "cli" / "probe-source-dirs.txt"

# (package, features) — read off the probe builders; see the module doc.
ROOTS = [
    ("nros", "std,metadata-mode"),
    ("nros-platform-cffi", "posix-c-port"),
    ("nros-cpp", "metadata-mode"),
    ("nros-c", ""),
]

HEADER = """\
# GENERATED by scripts/gen-probe-source-dirs.py — do not edit by hand.
#
# In-repo crate directories a metadata PROBE compiles (issue 1578). `nros sync`
# folds their sources into each sidecar's freshness key, so a nano-ros change to
# what a probe reports re-probes instead of reusing a stale answer.
# `check-probe-source-dirs` fails when this file disagrees with cargo.
#
# Regenerate: python3 scripts/gen-probe-source-dirs.py
"""

PATH_RE = re.compile(r"\((/[^)]*)\)")


def parse_tree(stdout, repo=REPO):
    """In-repo crate dirs named in `cargo tree --format {p}` output.

    Pure, so the self-test can hand it text. Keeps a path only if it resolves
    UNDER `repo` and is not vendored third-party: a registry crate is not a
    nano-ros source, and a submodule's pin is gated elsewhere.
    """
    dirs = set()
    for m in PATH_RE.finditer(stdout):
        try:
            rel = Path(m.group(1)).resolve().relative_to(Path(repo).resolve()).as_posix()
        except ValueError:
            continue  # registry crate or out-of-tree path
        if "third-party/" in rel:
            continue
        dirs.add(rel)
    return dirs


def closure(pkg, features):
    env = dict(os.environ)
    # `--locked` is injected project-wide by the `scripts/bin/cargo` shim;
    # `cargo tree` resolves nothing new.
    env["NROS_CARGO_FLAGS"] = ""
    cmd = ["cargo", "tree", "-p", pkg, "-e", "normal,build",
           "--prefix", "none", "--format", "{p}"]
    if features:
        cmd += ["-F", features]
    proc = subprocess.run(cmd, cwd=REPO, capture_output=True, text=True, env=env)
    if proc.returncode != 0:
        sys.stderr.write(proc.stderr)
        raise SystemExit(f"gen-probe-source-dirs: `cargo tree -p {pkg}` failed")
    dirs = parse_tree(proc.stdout)
    if not dirs:
        # An empty closure is a broken query, never a real answer: `nros`
        # itself is always in its own closure.
        raise SystemExit(f"gen-probe-source-dirs: `cargo tree -p {pkg}` named no in-repo crate")
    return dirs


def diff(have_text, dirs):
    """(missing, extra) between a committed list and cargo's answer.

    `missing` is the DANGEROUS direction -- a crate a probe compiles that the
    key does not watch, i.e. a stale sidecar. `extra` costs a spurious re-probe.
    """
    have = {l for l in have_text.splitlines() if l.strip() and not l.startswith("#")}
    return sorted(set(dirs) - have), sorted(have - set(dirs))


def self_test(quiet=False):
    """Negative controls -- a gate whose rule never fires proves nothing."""
    import tempfile
    with tempfile.TemporaryDirectory() as t:
        repo = Path(t)
        for d in ("packages/core/nros-node", "packages/api/nros",
                  "third-party/zpico/zenoh-pico"):
            (repo / d).mkdir(parents=True)
        out = (f"nros v0.5.0 ({repo}/packages/api/nros)\n"
               f"nros-node v0.5.0 ({repo}/packages/core/nros-node)\n"
               f"zenoh-pico v1.8.0 ({repo}/third-party/zpico/zenoh-pico)\n"
               "serde v1.0.228\n"
               "heapless v0.8.0 (/home/u/.cargo/registry/src/heapless-0.8.0)\n")
        got = parse_tree(out, repo)
        assert got == {"packages/api/nros", "packages/core/nros-node"}, (
            f"parse_tree must keep in-repo crates and drop registry and "
            f"third-party ones; got {sorted(got)}")

    want = {"packages/api/nros", "packages/core/nros-node"}
    # FIRES: a list that omits a crate the probe compiles.
    missing, extra = diff("# h\npackages/api/nros\n", want)
    assert missing == ["packages/core/nros-node"] and not extra, (
        "an omitted crate must be reported MISSING -- the stale-sidecar direction")
    # FIRES: a list naming a crate no probe compiles.
    missing, extra = diff("# h\npackages/api/nros\npackages/core/nros-node\n"
                          "packages/core/unrelated\n", want)
    assert extra == ["packages/core/unrelated"] and not missing, (
        "an unrelated crate must be reported EXTRA -- the spurious-re-probe direction")
    # SILENT: the committed list equals cargo's answer, header and all.
    assert diff(render(want), want) == ([], []), "an exact list must pass"
    if not quiet:
        print("gen-probe-source-dirs self-test: OK (4 cases)")
    return 0


def render(dirs):
    return HEADER + "".join(d + "\n" for d in sorted(dirs))


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="fail if the committed file disagrees with cargo")
    ap.add_argument("--self-test", action="store_true",
                    help="run only the negative controls")
    args = ap.parse_args()
    if args.self_test:
        return self_test()
    # Always, not only behind the flag: a negative control nobody runs decays
    # into a comment, and this rule's whole job is to fire.
    self_test(quiet=True)

    dirs = set()
    for pkg, features in ROOTS:
        dirs |= closure(pkg, features)
    want = render(dirs)

    if not args.check:
        OUT.write_text(want)
        print(f"gen-probe-source-dirs: wrote {OUT.relative_to(REPO)} ({len(dirs)} dir(s))")
        return 0

    have = OUT.read_text() if OUT.is_file() else ""
    if have == want:
        print(f"check-probe-source-dirs: OK ({len(dirs)} dir(s))")
        return 0
    missing, extra = diff(have, dirs)
    sys.stderr.write("check-probe-source-dirs: packages/cli/probe-source-dirs.txt is stale\n")
    for d in missing:
        sys.stderr.write(f"  + {d}   (a probe compiles it; the key does not watch it -- a stale sidecar)\n")
    for d in extra:
        sys.stderr.write(f"  - {d}   (no probe compiles it; a spurious re-probe)\n")
    sys.stderr.write("  Regenerate: python3 scripts/gen-probe-source-dirs.py\n")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
