#!/usr/bin/env python3
"""Issue #239 — regenerate the RMW ABI offset-parity halves.

Emits `packages/core/nros-rmw-cffi/tests/c_stubs/abi_offsets.c` (C-compiler
`offsetof`/`sizeof` exports) and `packages/core/nros-rmw-cffi/tests/
abi_offsets.rs` (`core::mem::offset_of!` comparison) from the CURRENT Rust
mirror's field lists. Run after adding/removing a field or vtable slot on
either side of the hand-mirror (name parity itself is gated by
check-rmw-abi-mirror.sh, so the Rust field list is a safe manifest source).
"""

import re

CFFI = "packages/core/nros-rmw-cffi"

PAIRS = [
    ("nros_rmw_vtable_t", "NrosRmwVtable"),
    ("nros_rmw_qos_t", "NrosRmwQos"),
    ("nros_rmw_session_t", "NrosRmwSession"),
    ("nros_rmw_publisher_t", "NrosRmwPublisher"),
    ("nros_rmw_subscriber_t", "NrosRmwSubscriber"),
    ("nros_rmw_service_server_t", "NrosRmwServiceServer"),
    ("nros_rmw_service_client_t", "NrosRmwServiceClient"),
    ("nros_rmw_count_status_t", "NrosRmwCountStatus"),
    ("nros_rmw_liveliness_changed_status_t", "NrosRmwLivelinessChangedStatus"),
]

C_HEADER = """/*
 * Issue #239 — compiler-derived ABI offset/size export, C half.
 *
 * For every member of every hand-mirrored `nros_rmw_*` struct this TU
 * exports `offsetof`/`sizeof` values COMPUTED BY THE C COMPILER from the
 * public headers. The Rust half (`tests/abi_offsets.rs`) compares each
 * against `core::mem::offset_of!` on the `NrosRmw*` twin — both sides are
 * machine-derived from their actual definitions, so there is no shared
 * literal table to go stale. A same-width field split/reorder/type-swap
 * that text-level name parity or total-size asserts miss shifts an offset
 * and fails the test. Compiled by build.rs under `c-stub-test`.
 *
 * REGENERATED by scripts/gen-rmw-abi-offsets.py when the mirror grows —
 * do not hand-edit the tables.
 */

#include <nros/rmw_entity.h>
#include <nros/rmw_event.h>
#include <nros/rmw_vtable.h>

#include <stddef.h>
"""

R_HEADER = """//! Issue #239 — compiler-derived ABI offset/size parity, Rust half.
//!
//! Reads the C-compiler-computed `offsetof`/`sizeof` exports from
//! `tests/c_stubs/abi_offsets.c` and compares each against
//! `core::mem::offset_of!` / `size_of` on the Rust mirror. See the C file
//! header for the design; regenerated by scripts/gen-rmw-abi-offsets.py.
#![cfg(feature = "c-stub-test")]

use core::mem::{offset_of, size_of};

use nros_rmw_cffi::{
    NrosRmwCountStatus, NrosRmwLivelinessChangedStatus, NrosRmwPublisher, NrosRmwQos,
    NrosRmwServiceClient, NrosRmwServiceServer, NrosRmwSession, NrosRmwSubscriber, NrosRmwVtable,
};

unsafe extern "C" {"""


def rust_fields(rust: str, name: str) -> list[str]:
    m = re.search(r"pub struct %s \{(.*?)\n\}" % name, rust, re.S)
    if not m:
        raise SystemExit(f"Rust struct {name} not found")
    return re.findall(r"\n    pub ([A-Za-z_0-9]+):", m.group(1))


def main() -> None:
    rust = open(f"{CFFI}/src/lib.rs").read()
    manifest = [(c, r, rust_fields(rust, r)) for c, r in PAIRS]

    c_lines = [C_HEADER]
    r_lines = [R_HEADER]
    r_asserts = []
    for c_tag, r_name, fields in manifest:
        c_lines.append(f"/* ---- {c_tag} ---- */")
        c_lines.append(f"const size_t nros_abi_sizeof__{c_tag} = sizeof({c_tag});")
        r_lines.append(f"    static nros_abi_sizeof__{c_tag}: usize;")
        r_asserts.append(
            f"        assert_eq!(nros_abi_sizeof__{c_tag}, size_of::<{r_name}>(), "
            f'"sizeof {c_tag}");'
        )
        for f in fields:
            c_lines.append(
                f"const size_t nros_abi_off__{c_tag}__{f} = offsetof({c_tag}, {f});"
            )
            r_lines.append(f"    static nros_abi_off__{c_tag}__{f}: usize;")
            r_asserts.append(
                f"        assert_eq!(nros_abi_off__{c_tag}__{f}, "
                f'offset_of!({r_name}, {f}), "offset {c_tag}.{f}");'
            )
    r_lines.append("}")
    r_lines.append(
        "\n/// Every member offset + struct size must agree between the C headers and"
        "\n/// the Rust mirror, as computed by each side's own compiler."
        "\n#[test]\nfn rmw_abi_offsets_match() {\n    unsafe {"
    )
    r_lines.extend(r_asserts)
    r_lines.append("    }\n}")

    open(f"{CFFI}/tests/c_stubs/abi_offsets.c", "w").write("\n".join(c_lines) + "\n")
    open(f"{CFFI}/tests/abi_offsets.rs", "w").write("\n".join(r_lines) + "\n")
    n = sum(len(f) for _, _, f in manifest)
    print(f"regenerated: {n} member offsets + {len(manifest)} sizes")


if __name__ == "__main__":
    main()
