#!/usr/bin/env python3
"""Generate book/src/reference/sched-matrix.md.

The scheduling story used to live as prose in three places and drifted
three ways at once: scheduling-models.md said EDF is "not currently
used" while spin.rs dispatches an `is_edf` branch; the micro-ROS
comparison advertised the full class list with no per-platform truth;
and nothing said which kernel capability backs which class where.

No hand-maintained table can hold that line, so this page is DERIVED
from the two artifacts the runtime itself executes:

  * `sched_caps_for()` in nros-orchestration-ir/src/rtos_realizer.rs —
    the realizer calls this exact function to decide Native-vs-Degrade
    per deployment, and its doctrine is written at the posix arm:
    caps describe what nano-ros DELIVERS, not what the OS could do
    (issue 0261). Parsed per match arm; an unparsed arm or field is a
    generator FAILURE, not a blank cell.
  * `SchedClass::<X>` dispatch sites in nros-node's executor spin.rs —
    a class with match arms in the dispatch path is live in the
    portable executor; one without is a type, not a behavior.

Run:  python3 scripts/gen-sched-matrix.py [--check]
Gate: just check sched-matrix
"""

import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "book", "src", "reference", "sched-matrix.md")
REALIZER = "packages/core/nros-orchestration-ir/src/rtos_realizer.rs"
SPIN = "packages/core/nros-node/src/executor/spin.rs"

# match-arm pattern -> display row. Order = display order. The pattern is
# matched against the arm's guard text, the display name is ours.
TARGETS = [
    ('"posix" | "native"', "Linux / POSIX host"),
    ('"zephyr"', "Zephyr"),
    ('f.contains("freertos")', "FreeRTOS"),
    ('f.contains("threadx")', "ThreadX"),
    ('f.contains("nuttx")', "NuttX"),
    ("_", "Bare-metal (RTIC / NVIC)"),
]

FIELDS = ["edf", "reservation", "preempt_threshold", "affinity",
          "n_priorities", "low_number_is_high"]

CLASSES = ["Fifo", "Edf", "Sporadic", "TimeTriggered"]


def read(rel):
    with open(os.path.join(ROOT, rel), encoding="utf8") as fh:
        return fh.read()


def parse_caps():
    """[(display, {field: value})] parsed from sched_caps_for's arms."""
    text = read(REALIZER)
    m = re.search(r"pub fn sched_caps_for\b.*?\n\}", text, re.S)
    if not m:
        sys.exit("gen-sched-matrix: sched_caps_for() not found")
    body = m.group(0)
    rows = []
    for pat, display in TARGETS:
        # The arm: <pat> => SchedCaps { ...fields... }
        arm = re.search(
            re.escape(pat) + r"\s*=>\s*SchedCaps\s*\{(.*?)\}\s*,", body, re.S)
        if not arm:
            sys.exit(f"gen-sched-matrix: no arm matching {pat!r} in "
                     "sched_caps_for — update TARGETS in the same commit.")
        fields = dict(re.findall(r"([a-z_]+)\s*:\s*([A-Za-z0-9_]+)", arm.group(1)))
        missing = [f for f in FIELDS if f not in fields]
        if missing:
            sys.exit(f"gen-sched-matrix: arm {pat!r} missing field(s) "
                     f"{missing} — SchedCaps changed shape; update FIELDS.")
        rows.append((display, fields))
    return rows


def class_dispatch_counts():
    """{class: count of SchedClass::<X> refs in spin.rs}."""
    text = read(SPIN)
    return {c: len(re.findall(rf"SchedClass::{c}\b", text)) for c in CLASSES}


def b(v):
    return {"true": "✓", "false": "—"}.get(v, f"`{v}`")


def render():
    caps = parse_caps()
    counts = class_dispatch_counts()

    lines = [
        "<!-- GENERATED by scripts/gen-sched-matrix.py — do not edit by hand.",
        "     Regenerate: python3 scripts/gen-sched-matrix.py",
        "     Gated by:   just check sched-matrix -->",
        "",
        "# Scheduling Wiring Matrix",
        "",
        "Which scheduling capabilities nano-ros **delivers** per platform,",
        "and which portable executor classes are **live in dispatch** —",
        "derived from the two artifacts the runtime executes, not from",
        "prose. The per-platform rows are parsed from `sched_caps_for()`",
        "(`nros-orchestration-ir`), the exact function the workload realizer",
        "calls to decide Native-vs-Degrade for a deployment; its rule, quoted",
        "from the source: *caps describe what nano-ros DELIVERS, not what",
        "the OS could do* (issue 0261).",
        "",
        "## Kernel capabilities per platform",
        "",
        "| Platform | Kernel EDF | Reservation / sporadic server | Preemption threshold | SMP affinity | Priority levels | Low number = high priority |",
        "|---|---|---|---|---|---|---|",
    ]
    for display, f in caps:
        lines.append(
            f"| {display} | {b(f['edf'])} | {b(f['reservation'])} "
            f"| {b(f['preempt_threshold'])} | {b(f['affinity'])} "
            f"| {f['n_priorities']} | {b(f['low_number_is_high'])} |")
    lines += [
        "",
        "Notes carried from the source arms: the POSIX row is deliberately",
        "conservative — no `SCHED_DEADLINE` consumer exists, so `edf` is",
        "false even though Linux could; Zephyr's EDF is",
        "`CONFIG_SCHED_DEADLINE`; NuttX's reservation is POSIX",
        "`SCHED_SPORADIC`; ThreadX's preemption threshold is native; the",
        "bare-metal row is NVIC hardware priorities with SRP ceilings (RTIC),",
        "single core. A deployment can override `edf` and `cores` per board",
        "(`[deploy.<board>] edf = <bool>` / `cores = <n>` —",
        "`sched_caps_from_deploy`), because the image being built is the",
        "authority, not the platform default.",
        "",
        "## Portable executor classes (`SchedClass`)",
        "",
        "These run **inside** the executor on every platform — they need no",
        "kernel support, which is what makes them portable; where the kernel",
        "HAS the native capability (table above), the realizer places the",
        "workload natively instead. \"Dispatch sites\" counts",
        "`SchedClass::<X>` references in the executor's spin path — a class",
        "with zero sites is a type, not a behavior.",
        "",
        "| Class | Dispatch sites in `spin.rs` | Status |",
        "|---|---|---|",
    ]
    status = {
        "Fifo": "Live — the default class; bucketed FIFO ready-set.",
        "Edf": "Live — earliest-deadline-first ready-set ordering.",
        "Sporadic": "Live — budget/period enforcement in dispatch.",
        "TimeTriggered": "Accepted but deprecated in favour of cooperating "
                         "TT-with-other-classes (see the enum's deprecation "
                         "note); dispatches as Fifo.",
    }
    for c in CLASSES:
        n = counts[c]
        if n == 0 and "Live" in status[c]:
            sys.exit(f"gen-sched-matrix: class {c} has 0 dispatch sites but "
                     "a Live status row — reality moved; update STATUS.")
        lines.append(f"| `{c}` | {n} | {status[c]} |")
    lines += [
        "",
        "## Related",
        "",
        "- [Scheduling Models](../internals/scheduling-models.md) — the",
        "  narrative: how tiers, transport priorities, and these classes",
        "  land on each kernel",
        "- [RTOS Cooperation](../concepts/rtos-cooperation.md) — spin-loop",
        "  shapes per execution model",
        "- [Support Status](support-status.md) · [Per-RMW Feature",
        "  Matrix](rmw-feature-matrix.md)",
        "",
    ]
    return "\n".join(lines)


def main():
    content = render()
    if "--check" in sys.argv:
        on_disk = open(OUT, encoding="utf8").read() if os.path.exists(OUT) else ""
        if on_disk != content:
            sys.exit("check-sched-matrix: STALE — regenerate with "
                     "python3 scripts/gen-sched-matrix.py and commit.")
        print("sched-matrix OK")
        return
    with open(OUT, "w", encoding="utf8") as fh:
        fh.write(content)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
