//! Issue #239 — compiler-derived ABI offset/size parity, Rust half.
//!
//! Reads the C-compiler-computed `offsetof`/`sizeof` exports from
//! `tests/c_stubs/abi_offsets.c` and compares each against
//! `core::mem::offset_of!` / `size_of` on the Rust mirror. See the C file
//! header for the design; regenerated by scripts/gen-rmw-abi-offsets.py.
#![cfg(feature = "c-stub-test")]

use core::mem::{offset_of, size_of};

use nros_rmw_cffi::{
    NrosRmwCountStatus, NrosRmwLivelinessChangedStatus, NrosRmwPublisher, NrosRmwQos,
    NrosRmwServiceClient, NrosRmwServiceServer, NrosRmwSession, NrosRmwSubscriber, NrosRmwVtable,
};

unsafe extern "C" {
    static nros_abi_sizeof__nros_rmw_vtable_t: usize;
    static nros_abi_off__nros_rmw_vtable_t__open: usize;
    static nros_abi_off__nros_rmw_vtable_t__close: usize;
    static nros_abi_off__nros_rmw_vtable_t__drive_io: usize;
    static nros_abi_off__nros_rmw_vtable_t__create_publisher: usize;
    static nros_abi_off__nros_rmw_vtable_t__destroy_publisher: usize;
    static nros_abi_off__nros_rmw_vtable_t__publish_raw: usize;
    static nros_abi_off__nros_rmw_vtable_t__create_subscriber: usize;
    static nros_abi_off__nros_rmw_vtable_t__destroy_subscriber: usize;
    static nros_abi_off__nros_rmw_vtable_t__try_recv_raw: usize;
    static nros_abi_off__nros_rmw_vtable_t__has_data: usize;
    static nros_abi_off__nros_rmw_vtable_t__create_service_server: usize;
    static nros_abi_off__nros_rmw_vtable_t__destroy_service_server: usize;
    static nros_abi_off__nros_rmw_vtable_t__try_recv_request: usize;
    static nros_abi_off__nros_rmw_vtable_t__has_request: usize;
    static nros_abi_off__nros_rmw_vtable_t__send_reply: usize;
    static nros_abi_off__nros_rmw_vtable_t__create_service_client: usize;
    static nros_abi_off__nros_rmw_vtable_t__destroy_service_client: usize;
    static nros_abi_off__nros_rmw_vtable_t__call_raw: usize;
    static nros_abi_off__nros_rmw_vtable_t__send_request_raw: usize;
    static nros_abi_off__nros_rmw_vtable_t__try_recv_reply_raw: usize;
    static nros_abi_off__nros_rmw_vtable_t__register_subscriber_event: usize;
    static nros_abi_off__nros_rmw_vtable_t__register_publisher_event: usize;
    static nros_abi_off__nros_rmw_vtable_t__assert_publisher_liveliness: usize;
    static nros_abi_off__nros_rmw_vtable_t__next_deadline_ms: usize;
    static nros_abi_off__nros_rmw_vtable_t__set_wake_callback: usize;
    static nros_abi_off__nros_rmw_vtable_t__pub_loan: usize;
    static nros_abi_off__nros_rmw_vtable_t__pub_commit: usize;
    static nros_abi_off__nros_rmw_vtable_t__pub_discard: usize;
    static nros_abi_off__nros_rmw_vtable_t__sub_borrow: usize;
    static nros_abi_off__nros_rmw_vtable_t__sub_release: usize;
    static nros_abi_off__nros_rmw_vtable_t__service_server_available: usize;
    static nros_abi_off__nros_rmw_vtable_t__try_recv_sequence: usize;
    static nros_abi_off__nros_rmw_vtable_t__publish_streamed: usize;
    static nros_abi_off__nros_rmw_vtable_t__ping_session: usize;
    static nros_abi_off__nros_rmw_vtable_t__subscriber_supports_in_place: usize;
    static nros_abi_off__nros_rmw_vtable_t__process_raw_in_place: usize;
    static nros_abi_sizeof__nros_rmw_qos_t: usize;
    static nros_abi_off__nros_rmw_qos_t__reliability: usize;
    static nros_abi_off__nros_rmw_qos_t__durability: usize;
    static nros_abi_off__nros_rmw_qos_t__history: usize;
    static nros_abi_off__nros_rmw_qos_t__liveliness_kind: usize;
    static nros_abi_off__nros_rmw_qos_t__depth: usize;
    static nros_abi_off__nros_rmw_qos_t__tx_express: usize;
    static nros_abi_off__nros_rmw_qos_t___reserved0: usize;
    static nros_abi_off__nros_rmw_qos_t__deadline_ms: usize;
    static nros_abi_off__nros_rmw_qos_t__lifespan_ms: usize;
    static nros_abi_off__nros_rmw_qos_t__liveliness_lease_ms: usize;
    static nros_abi_off__nros_rmw_qos_t__avoid_ros_namespace_conventions: usize;
    static nros_abi_off__nros_rmw_qos_t___reserved1: usize;
    static nros_abi_off__nros_rmw_qos_t__rx_buffer_hint: usize;
    static nros_abi_sizeof__nros_rmw_session_t: usize;
    static nros_abi_off__nros_rmw_session_t__node_name: usize;
    static nros_abi_off__nros_rmw_session_t__namespace_: usize;
    static nros_abi_off__nros_rmw_session_t___reserved: usize;
    static nros_abi_off__nros_rmw_session_t__backend_data: usize;
    static nros_abi_sizeof__nros_rmw_publisher_t: usize;
    static nros_abi_off__nros_rmw_publisher_t__topic_name: usize;
    static nros_abi_off__nros_rmw_publisher_t__type_name: usize;
    static nros_abi_off__nros_rmw_publisher_t__qos: usize;
    static nros_abi_off__nros_rmw_publisher_t__can_loan_messages: usize;
    static nros_abi_off__nros_rmw_publisher_t___reserved: usize;
    static nros_abi_off__nros_rmw_publisher_t__backend_data: usize;
    static nros_abi_sizeof__nros_rmw_subscriber_t: usize;
    static nros_abi_off__nros_rmw_subscriber_t__topic_name: usize;
    static nros_abi_off__nros_rmw_subscriber_t__type_name: usize;
    static nros_abi_off__nros_rmw_subscriber_t__qos: usize;
    static nros_abi_off__nros_rmw_subscriber_t__can_loan_messages: usize;
    static nros_abi_off__nros_rmw_subscriber_t___reserved: usize;
    static nros_abi_off__nros_rmw_subscriber_t__backend_data: usize;
    static nros_abi_sizeof__nros_rmw_service_server_t: usize;
    static nros_abi_off__nros_rmw_service_server_t__service_name: usize;
    static nros_abi_off__nros_rmw_service_server_t__type_name: usize;
    static nros_abi_off__nros_rmw_service_server_t___reserved: usize;
    static nros_abi_off__nros_rmw_service_server_t__backend_data: usize;
    static nros_abi_sizeof__nros_rmw_service_client_t: usize;
    static nros_abi_off__nros_rmw_service_client_t__service_name: usize;
    static nros_abi_off__nros_rmw_service_client_t__type_name: usize;
    static nros_abi_off__nros_rmw_service_client_t___reserved: usize;
    static nros_abi_off__nros_rmw_service_client_t__backend_data: usize;
    static nros_abi_sizeof__nros_rmw_count_status_t: usize;
    static nros_abi_off__nros_rmw_count_status_t__total_count: usize;
    static nros_abi_off__nros_rmw_count_status_t__total_count_change: usize;
    static nros_abi_sizeof__nros_rmw_liveliness_changed_status_t: usize;
    static nros_abi_off__nros_rmw_liveliness_changed_status_t__alive_count: usize;
    static nros_abi_off__nros_rmw_liveliness_changed_status_t__not_alive_count: usize;
    static nros_abi_off__nros_rmw_liveliness_changed_status_t__alive_count_change: usize;
    static nros_abi_off__nros_rmw_liveliness_changed_status_t__not_alive_count_change: usize;
}

/// Every member offset + struct size must agree between the C headers and
/// the Rust mirror, as computed by each side's own compiler.
#[test]
fn rmw_abi_offsets_match() {
    unsafe {
        assert_eq!(
            nros_abi_sizeof__nros_rmw_vtable_t,
            size_of::<NrosRmwVtable>(),
            "sizeof nros_rmw_vtable_t"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_vtable_t__open,
            offset_of!(NrosRmwVtable, open),
            "offset nros_rmw_vtable_t.open"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_vtable_t__close,
            offset_of!(NrosRmwVtable, close),
            "offset nros_rmw_vtable_t.close"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_vtable_t__drive_io,
            offset_of!(NrosRmwVtable, drive_io),
            "offset nros_rmw_vtable_t.drive_io"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_vtable_t__create_publisher,
            offset_of!(NrosRmwVtable, create_publisher),
            "offset nros_rmw_vtable_t.create_publisher"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_vtable_t__destroy_publisher,
            offset_of!(NrosRmwVtable, destroy_publisher),
            "offset nros_rmw_vtable_t.destroy_publisher"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_vtable_t__publish_raw,
            offset_of!(NrosRmwVtable, publish_raw),
            "offset nros_rmw_vtable_t.publish_raw"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_vtable_t__create_subscriber,
            offset_of!(NrosRmwVtable, create_subscriber),
            "offset nros_rmw_vtable_t.create_subscriber"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_vtable_t__destroy_subscriber,
            offset_of!(NrosRmwVtable, destroy_subscriber),
            "offset nros_rmw_vtable_t.destroy_subscriber"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_vtable_t__try_recv_raw,
            offset_of!(NrosRmwVtable, try_recv_raw),
            "offset nros_rmw_vtable_t.try_recv_raw"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_vtable_t__has_data,
            offset_of!(NrosRmwVtable, has_data),
            "offset nros_rmw_vtable_t.has_data"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_vtable_t__create_service_server,
            offset_of!(NrosRmwVtable, create_service_server),
            "offset nros_rmw_vtable_t.create_service_server"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_vtable_t__destroy_service_server,
            offset_of!(NrosRmwVtable, destroy_service_server),
            "offset nros_rmw_vtable_t.destroy_service_server"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_vtable_t__try_recv_request,
            offset_of!(NrosRmwVtable, try_recv_request),
            "offset nros_rmw_vtable_t.try_recv_request"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_vtable_t__has_request,
            offset_of!(NrosRmwVtable, has_request),
            "offset nros_rmw_vtable_t.has_request"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_vtable_t__send_reply,
            offset_of!(NrosRmwVtable, send_reply),
            "offset nros_rmw_vtable_t.send_reply"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_vtable_t__create_service_client,
            offset_of!(NrosRmwVtable, create_service_client),
            "offset nros_rmw_vtable_t.create_service_client"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_vtable_t__destroy_service_client,
            offset_of!(NrosRmwVtable, destroy_service_client),
            "offset nros_rmw_vtable_t.destroy_service_client"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_vtable_t__call_raw,
            offset_of!(NrosRmwVtable, call_raw),
            "offset nros_rmw_vtable_t.call_raw"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_vtable_t__send_request_raw,
            offset_of!(NrosRmwVtable, send_request_raw),
            "offset nros_rmw_vtable_t.send_request_raw"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_vtable_t__try_recv_reply_raw,
            offset_of!(NrosRmwVtable, try_recv_reply_raw),
            "offset nros_rmw_vtable_t.try_recv_reply_raw"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_vtable_t__register_subscriber_event,
            offset_of!(NrosRmwVtable, register_subscriber_event),
            "offset nros_rmw_vtable_t.register_subscriber_event"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_vtable_t__register_publisher_event,
            offset_of!(NrosRmwVtable, register_publisher_event),
            "offset nros_rmw_vtable_t.register_publisher_event"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_vtable_t__assert_publisher_liveliness,
            offset_of!(NrosRmwVtable, assert_publisher_liveliness),
            "offset nros_rmw_vtable_t.assert_publisher_liveliness"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_vtable_t__next_deadline_ms,
            offset_of!(NrosRmwVtable, next_deadline_ms),
            "offset nros_rmw_vtable_t.next_deadline_ms"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_vtable_t__set_wake_callback,
            offset_of!(NrosRmwVtable, set_wake_callback),
            "offset nros_rmw_vtable_t.set_wake_callback"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_vtable_t__pub_loan,
            offset_of!(NrosRmwVtable, pub_loan),
            "offset nros_rmw_vtable_t.pub_loan"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_vtable_t__pub_commit,
            offset_of!(NrosRmwVtable, pub_commit),
            "offset nros_rmw_vtable_t.pub_commit"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_vtable_t__pub_discard,
            offset_of!(NrosRmwVtable, pub_discard),
            "offset nros_rmw_vtable_t.pub_discard"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_vtable_t__sub_borrow,
            offset_of!(NrosRmwVtable, sub_borrow),
            "offset nros_rmw_vtable_t.sub_borrow"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_vtable_t__sub_release,
            offset_of!(NrosRmwVtable, sub_release),
            "offset nros_rmw_vtable_t.sub_release"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_vtable_t__service_server_available,
            offset_of!(NrosRmwVtable, service_server_available),
            "offset nros_rmw_vtable_t.service_server_available"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_vtable_t__try_recv_sequence,
            offset_of!(NrosRmwVtable, try_recv_sequence),
            "offset nros_rmw_vtable_t.try_recv_sequence"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_vtable_t__publish_streamed,
            offset_of!(NrosRmwVtable, publish_streamed),
            "offset nros_rmw_vtable_t.publish_streamed"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_vtable_t__ping_session,
            offset_of!(NrosRmwVtable, ping_session),
            "offset nros_rmw_vtable_t.ping_session"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_vtable_t__subscriber_supports_in_place,
            offset_of!(NrosRmwVtable, subscriber_supports_in_place),
            "offset nros_rmw_vtable_t.subscriber_supports_in_place"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_vtable_t__process_raw_in_place,
            offset_of!(NrosRmwVtable, process_raw_in_place),
            "offset nros_rmw_vtable_t.process_raw_in_place"
        );
        assert_eq!(
            nros_abi_sizeof__nros_rmw_qos_t,
            size_of::<NrosRmwQos>(),
            "sizeof nros_rmw_qos_t"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_qos_t__reliability,
            offset_of!(NrosRmwQos, reliability),
            "offset nros_rmw_qos_t.reliability"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_qos_t__durability,
            offset_of!(NrosRmwQos, durability),
            "offset nros_rmw_qos_t.durability"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_qos_t__history,
            offset_of!(NrosRmwQos, history),
            "offset nros_rmw_qos_t.history"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_qos_t__liveliness_kind,
            offset_of!(NrosRmwQos, liveliness_kind),
            "offset nros_rmw_qos_t.liveliness_kind"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_qos_t__depth,
            offset_of!(NrosRmwQos, depth),
            "offset nros_rmw_qos_t.depth"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_qos_t__tx_express,
            offset_of!(NrosRmwQos, tx_express),
            "offset nros_rmw_qos_t.tx_express"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_qos_t___reserved0,
            offset_of!(NrosRmwQos, _reserved0),
            "offset nros_rmw_qos_t._reserved0"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_qos_t__deadline_ms,
            offset_of!(NrosRmwQos, deadline_ms),
            "offset nros_rmw_qos_t.deadline_ms"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_qos_t__lifespan_ms,
            offset_of!(NrosRmwQos, lifespan_ms),
            "offset nros_rmw_qos_t.lifespan_ms"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_qos_t__liveliness_lease_ms,
            offset_of!(NrosRmwQos, liveliness_lease_ms),
            "offset nros_rmw_qos_t.liveliness_lease_ms"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_qos_t__avoid_ros_namespace_conventions,
            offset_of!(NrosRmwQos, avoid_ros_namespace_conventions),
            "offset nros_rmw_qos_t.avoid_ros_namespace_conventions"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_qos_t___reserved1,
            offset_of!(NrosRmwQos, _reserved1),
            "offset nros_rmw_qos_t._reserved1"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_qos_t__rx_buffer_hint,
            offset_of!(NrosRmwQos, rx_buffer_hint),
            "offset nros_rmw_qos_t.rx_buffer_hint"
        );
        assert_eq!(
            nros_abi_sizeof__nros_rmw_session_t,
            size_of::<NrosRmwSession>(),
            "sizeof nros_rmw_session_t"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_session_t__node_name,
            offset_of!(NrosRmwSession, node_name),
            "offset nros_rmw_session_t.node_name"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_session_t__namespace_,
            offset_of!(NrosRmwSession, namespace_),
            "offset nros_rmw_session_t.namespace_"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_session_t___reserved,
            offset_of!(NrosRmwSession, _reserved),
            "offset nros_rmw_session_t._reserved"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_session_t__backend_data,
            offset_of!(NrosRmwSession, backend_data),
            "offset nros_rmw_session_t.backend_data"
        );
        assert_eq!(
            nros_abi_sizeof__nros_rmw_publisher_t,
            size_of::<NrosRmwPublisher>(),
            "sizeof nros_rmw_publisher_t"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_publisher_t__topic_name,
            offset_of!(NrosRmwPublisher, topic_name),
            "offset nros_rmw_publisher_t.topic_name"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_publisher_t__type_name,
            offset_of!(NrosRmwPublisher, type_name),
            "offset nros_rmw_publisher_t.type_name"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_publisher_t__qos,
            offset_of!(NrosRmwPublisher, qos),
            "offset nros_rmw_publisher_t.qos"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_publisher_t__can_loan_messages,
            offset_of!(NrosRmwPublisher, can_loan_messages),
            "offset nros_rmw_publisher_t.can_loan_messages"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_publisher_t___reserved,
            offset_of!(NrosRmwPublisher, _reserved),
            "offset nros_rmw_publisher_t._reserved"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_publisher_t__backend_data,
            offset_of!(NrosRmwPublisher, backend_data),
            "offset nros_rmw_publisher_t.backend_data"
        );
        assert_eq!(
            nros_abi_sizeof__nros_rmw_subscriber_t,
            size_of::<NrosRmwSubscriber>(),
            "sizeof nros_rmw_subscriber_t"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_subscriber_t__topic_name,
            offset_of!(NrosRmwSubscriber, topic_name),
            "offset nros_rmw_subscriber_t.topic_name"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_subscriber_t__type_name,
            offset_of!(NrosRmwSubscriber, type_name),
            "offset nros_rmw_subscriber_t.type_name"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_subscriber_t__qos,
            offset_of!(NrosRmwSubscriber, qos),
            "offset nros_rmw_subscriber_t.qos"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_subscriber_t__can_loan_messages,
            offset_of!(NrosRmwSubscriber, can_loan_messages),
            "offset nros_rmw_subscriber_t.can_loan_messages"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_subscriber_t___reserved,
            offset_of!(NrosRmwSubscriber, _reserved),
            "offset nros_rmw_subscriber_t._reserved"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_subscriber_t__backend_data,
            offset_of!(NrosRmwSubscriber, backend_data),
            "offset nros_rmw_subscriber_t.backend_data"
        );
        assert_eq!(
            nros_abi_sizeof__nros_rmw_service_server_t,
            size_of::<NrosRmwServiceServer>(),
            "sizeof nros_rmw_service_server_t"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_service_server_t__service_name,
            offset_of!(NrosRmwServiceServer, service_name),
            "offset nros_rmw_service_server_t.service_name"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_service_server_t__type_name,
            offset_of!(NrosRmwServiceServer, type_name),
            "offset nros_rmw_service_server_t.type_name"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_service_server_t___reserved,
            offset_of!(NrosRmwServiceServer, _reserved),
            "offset nros_rmw_service_server_t._reserved"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_service_server_t__backend_data,
            offset_of!(NrosRmwServiceServer, backend_data),
            "offset nros_rmw_service_server_t.backend_data"
        );
        assert_eq!(
            nros_abi_sizeof__nros_rmw_service_client_t,
            size_of::<NrosRmwServiceClient>(),
            "sizeof nros_rmw_service_client_t"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_service_client_t__service_name,
            offset_of!(NrosRmwServiceClient, service_name),
            "offset nros_rmw_service_client_t.service_name"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_service_client_t__type_name,
            offset_of!(NrosRmwServiceClient, type_name),
            "offset nros_rmw_service_client_t.type_name"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_service_client_t___reserved,
            offset_of!(NrosRmwServiceClient, _reserved),
            "offset nros_rmw_service_client_t._reserved"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_service_client_t__backend_data,
            offset_of!(NrosRmwServiceClient, backend_data),
            "offset nros_rmw_service_client_t.backend_data"
        );
        assert_eq!(
            nros_abi_sizeof__nros_rmw_count_status_t,
            size_of::<NrosRmwCountStatus>(),
            "sizeof nros_rmw_count_status_t"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_count_status_t__total_count,
            offset_of!(NrosRmwCountStatus, total_count),
            "offset nros_rmw_count_status_t.total_count"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_count_status_t__total_count_change,
            offset_of!(NrosRmwCountStatus, total_count_change),
            "offset nros_rmw_count_status_t.total_count_change"
        );
        assert_eq!(
            nros_abi_sizeof__nros_rmw_liveliness_changed_status_t,
            size_of::<NrosRmwLivelinessChangedStatus>(),
            "sizeof nros_rmw_liveliness_changed_status_t"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_liveliness_changed_status_t__alive_count,
            offset_of!(NrosRmwLivelinessChangedStatus, alive_count),
            "offset nros_rmw_liveliness_changed_status_t.alive_count"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_liveliness_changed_status_t__not_alive_count,
            offset_of!(NrosRmwLivelinessChangedStatus, not_alive_count),
            "offset nros_rmw_liveliness_changed_status_t.not_alive_count"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_liveliness_changed_status_t__alive_count_change,
            offset_of!(NrosRmwLivelinessChangedStatus, alive_count_change),
            "offset nros_rmw_liveliness_changed_status_t.alive_count_change"
        );
        assert_eq!(
            nros_abi_off__nros_rmw_liveliness_changed_status_t__not_alive_count_change,
            offset_of!(NrosRmwLivelinessChangedStatus, not_alive_count_change),
            "offset nros_rmw_liveliness_changed_status_t.not_alive_count_change"
        );
    }
}
