[patch.crates-io]
nros = { path = "../../../packages/core/nros" }  # nros-managed
nros-core = { path = "../../../packages/core/nros-core" }  # nros-managed
nros-platform = { path = "../../../packages/core/nros-platform" }  # nros-managed
nros-rmw-xrce-cffi = { path = "../../../packages/xrce/nros-rmw-xrce-cffi" }  # nros-managed
nros-rmw-zenoh = { path = "../../../packages/zpico/nros-rmw-zenoh" }  # nros-managed
nros-serdes = { path = "../../../packages/core/nros-serdes" }  # nros-managed
