//! XRCE-DDS RMW backend for nros.
//!
//! Maps the XRCE-DDS entity hierarchy to `nros-rmw` traits, allowing board
//! crates to swap between zenoh and XRCE-DDS with a feature flag change.
//!
//! # Architecture
//!
//! All state is aggregated in a single [`XrceSessionState`] struct stored
//! behind a module-level [`SharedCell`] (single-session model, matching
//! XRCE-DDS's design). Board crates call [`init_transport()`] to register
//! custom transport callbacks (from `xrce-smoltcp`), then
//! [`XrceRmw::open()`] to create the DDS session and participant.
//!
//! Topic/service callbacks dispatch by `object_id` to subscriber /
//! service-server / service-client slots held in the state struct, using
//! atomic flags for callback→consumer data flow (same pattern as the
//! zenoh backend). Access to the state is disciplined by the existing
//! `ffi_guard` critical-section wrapper; no lock-free access is assumed.
//!
//! Phase 84.E2b.1 collapsed 11 prior `static mut` module globals into
//! this struct. 84.E2b.2 will thread a pointer to the state through
//! the callbacks' `args` parameter; 84.E2b.3 will move the struct into
//! a `Box<XrceSessionState>` owned by [`XrceSession`] to enable
//! multi-session.

#![no_std]

#[cfg(feature = "std")]
#[macro_use]
extern crate std;

#[cfg(feature = "alloc")]
extern crate alloc;

pub(crate) mod config;
mod naming;

#[cfg(feature = "platform-udp")]
pub mod platform_udp;

// Phase 80.14: serial transport now routes through `PlatformSerial`.
// The old `posix_serial` module is gone; `platform_serial` replaces it.
#[cfg(feature = "posix-serial")]
pub mod platform_serial;

use atomic_waker::AtomicWaker;
use core::ffi::{c_char, c_int, c_void};
use core::sync::atomic::{AtomicBool, AtomicUsize, Ordering};

// ============================================================================
// FFI Reentrancy Guard
// ============================================================================

/// Execute a closure with FFI reentrancy protection.
///
/// When the `ffi-sync` feature is enabled, wraps the closure in
/// `critical_section::with()` to prevent concurrent access to XRCE global
/// state from mixed-priority tasks or ISRs.
///
/// When the feature is disabled, this is a zero-cost passthrough.
#[inline(always)]
fn ffi_guard<R>(f: impl FnOnce() -> R) -> R {
    #[cfg(feature = "ffi-sync")]
    {
        return critical_section::with(|_cs| f());
    }
    #[cfg(not(feature = "ffi-sync"))]
    f()
}

use nros_rmw::{
    Publisher, QosDurabilityPolicy, QosHistoryPolicy, QosReliabilityPolicy, QosSettings, Rmw,
    RmwConfig, ServiceClientTrait, ServiceInfo, ServiceRequest, ServiceServerTrait, Session,
    Subscriber, TopicInfo, TransportError,
};
use xrce_sys::{
    SampleIdentity, UXR_DATAREADER_ID, UXR_DATAWRITER_ID, UXR_MAX_BYTES_PER_SECOND_UNLIMITED,
    UXR_MAX_ELAPSED_TIME_UNLIMITED, UXR_MAX_SAMPLES_UNLIMITED, UXR_PARTICIPANT_ID,
    UXR_PUBLISHER_ID, UXR_REPLACE, UXR_REPLIER_ID, UXR_REQUESTER_ID, UXR_SUBSCRIBER_ID,
    UXR_TOPIC_ID, ucdrBuffer, uxrCustomTransport, uxrDeliveryControl, uxrObjectId, uxrQoS_t,
    uxrSession, uxrStreamId,
};

// ============================================================================
// Configuration (generated by build.rs from XRCE_* env vars)
// ============================================================================

use crate::config::*;

/// Stream buffer size (bytes). With history=N, each slot is STREAM_BUFFER_SIZE/N.
/// Each slot must be >= MTU for reliable stream reassembly.
const STREAM_BUFFER_SIZE: usize = xrce_sys::XRCE_TRANSPORT_MTU as usize * STREAM_HISTORY_USIZE;

// ============================================================================
// Global State
// ============================================================================
//
// Aggregated in [`XrceSessionState`] and stored in one [`SharedCell`] at
// module scope. Callers reach it via the `state()` accessor. Phase 84.E2b
// (see crate-level doc) plans to move this into a `Box` owned by
// `XrceSession` for multi-session support; the struct shape is chosen now
// to make that migration mechanical.

/// Full XRCE-DDS session state — everything that used to live in
/// `static mut` globals.
///
/// Construction is `const` so the containing `SharedCell` can be
/// initialized at compile time without requiring `alloc`. The slot
/// sub-arrays are also `const`-constructible via their own
/// `*::new()` helpers.
struct XrceSessionState {
    transport: uxrCustomTransport,
    session: uxrSession,
    output_reliable: uxrStreamId,
    input_reliable: uxrStreamId,
    participant_oid: uxrObjectId,
    /// Next entity ID to hand out (ID 1 is reserved for the participant).
    next_entity_id: u16,
    initialized: bool,
    output_reliable_buf: [u8; STREAM_BUFFER_SIZE],
    input_reliable_buf: [u8; STREAM_BUFFER_SIZE],
    subscriber_slots: [SubscriberSlot; MAX_SUBSCRIBERS],
    service_server_slots: [ServiceServerSlot; MAX_SERVICE_SERVERS],
    service_client_slots: [ServiceClientSlot; MAX_SERVICE_CLIENTS],
}

impl XrceSessionState {
    const fn zeroed() -> Self {
        Self {
            transport: uxrCustomTransport::zeroed(),
            session: uxrSession::zeroed(),
            output_reliable: zeroed_stream_id(),
            input_reliable: zeroed_stream_id(),
            participant_oid: zeroed_object_id(),
            next_entity_id: 2, // ID 1 = participant
            initialized: false,
            output_reliable_buf: [0u8; STREAM_BUFFER_SIZE],
            input_reliable_buf: [0u8; STREAM_BUFFER_SIZE],
            subscriber_slots: [const { SubscriberSlot::new() }; MAX_SUBSCRIBERS],
            service_server_slots: [const { ServiceServerSlot::new() }; MAX_SERVICE_SERVERS],
            service_client_slots: [const { ServiceClientSlot::new() }; MAX_SERVICE_CLIENTS],
        }
    }
}

/// `UnsafeCell<T>` + hand-rolled `Sync`. All access goes through the
/// `state()` accessor and is disciplined by `ffi_guard` — either a
/// `critical_section::with` when the `ffi-sync` feature is on, or
/// cooperative single-threaded access otherwise (the same discipline
/// the pre-84.E2b `static mut`s relied on).
#[repr(transparent)]
struct SharedCell<T>(core::cell::UnsafeCell<T>);

// SAFETY: see comment on `SharedCell` and the callers of `state()`.
unsafe impl<T> Sync for SharedCell<T> {}

impl<T> SharedCell<T> {
    const fn new(t: T) -> Self {
        Self(core::cell::UnsafeCell::new(t))
    }
}

static STATE: SharedCell<XrceSessionState> = SharedCell::new(XrceSessionState::zeroed());

/// Access the single XRCE session-state instance.
///
/// # Safety
///
/// The returned mutable reference has `'static` lifetime and is unique
/// only in the single-threaded / critical-section sense enforced by
/// `ffi_guard`. Callers that touch the same field concurrently from
/// multiple threads without going through `ffi_guard` are unsound.
#[inline(always)]
unsafe fn state() -> &'static mut XrceSessionState {
    unsafe { &mut *STATE.0.get() }
}

const fn zeroed_stream_id() -> uxrStreamId {
    uxrStreamId {
        raw: 0,
        index: 0,
        type_: 0,
        direction: 0,
    }
}

const fn zeroed_object_id() -> uxrObjectId {
    uxrObjectId { id: 0, type_: 0 }
}

const fn zeroed_sample_identity() -> SampleIdentity {
    SampleIdentity {
        writer_guid: xrce_sys::GUID_t {
            guid_prefix: xrce_sys::GuidPrefix_t { data: [0u8; 12] },
            entity_id: xrce_sys::EntityId_t {
                entity_key: [0u8; 3],
                entity_kind: 0,
            },
        },
        sequence_number: xrce_sys::SequenceNumber_t { high: 0, low: 0 },
    }
}

// ============================================================================
// Fragmented Stream Flush Callback
// ============================================================================

/// Timeout for `uxr_run_session_time` flush calls (milliseconds).
const SESSION_FLUSH_TIMEOUT_MS: c_int = 100;

/// Retries for `uxr_create_session_retries`.
const SESSION_CREATION_RETRIES: usize = 10;

/// Stack buffer size for DDS topic/type/service names.
const DDS_NAME_BUF_SIZE: usize = 128;

/// Stack buffer size for participant name.
const PARTICIPANT_NAME_BUF_SIZE: usize = 64;

/// Flush callback for `uxr_prepare_output_stream_fragmented`.
///
/// Called by the XRCE library when the output stream buffer is full during
/// fragmented writes. Flushes pending fragments to the transport and runs
/// the session briefly to process acknowledgements.
unsafe extern "C" fn flush_output_streams(
    session: *mut xrce_sys::uxrSession,
    _args: *mut core::ffi::c_void,
) -> bool {
    unsafe {
        xrce_sys::uxr_flash_output_streams(session);
        xrce_sys::uxr_run_session_time(session, SESSION_FLUSH_TIMEOUT_MS)
    }
}

// ============================================================================
// Subscriber Slots
// ============================================================================

struct SubscriberSlot {
    data: [u8; BUFFER_SIZE],
    has_data: AtomicBool,
    len: AtomicUsize,
    overflow: AtomicBool,
    /// Flag indicating a reader is currently accessing this slot.
    /// The callback checks this flag and drops the message if locked,
    /// preventing a data race where the callback overwrites the buffer mid-read.
    locked: AtomicBool,
    waker: AtomicWaker,
    datareader_id: u16,
    active: bool,
}

impl SubscriberSlot {
    const fn new() -> Self {
        Self {
            data: [0u8; BUFFER_SIZE],
            has_data: AtomicBool::new(false),
            len: AtomicUsize::new(0),
            overflow: AtomicBool::new(false),
            locked: AtomicBool::new(false),
            waker: AtomicWaker::new(),
            datareader_id: 0,
            active: false,
        }
    }
}

// (Array lives as `XrceSessionState::subscriber_slots` — see above.)

// ============================================================================
// Service Server Slots
// ============================================================================

struct ServiceServerSlot {
    data: [u8; BUFFER_SIZE],
    has_request: AtomicBool,
    overflow: AtomicBool,
    len: AtomicUsize,
    sample_id: SampleIdentity,
    replier_id: u16,
    active: bool,
}

impl ServiceServerSlot {
    const fn new() -> Self {
        Self {
            data: [0u8; BUFFER_SIZE],
            has_request: AtomicBool::new(false),
            overflow: AtomicBool::new(false),
            len: AtomicUsize::new(0),
            sample_id: zeroed_sample_identity(),
            replier_id: 0,
            active: false,
        }
    }
}

// (Array lives as `XrceSessionState::service_server_slots` — see above.)

// ============================================================================
// Service Client Slots
// ============================================================================

struct ServiceClientSlot {
    data: [u8; BUFFER_SIZE],
    has_reply: AtomicBool,
    overflow: AtomicBool,
    len: AtomicUsize,
    waker: AtomicWaker,
    requester_id: u16,
    active: bool,
}

impl ServiceClientSlot {
    const fn new() -> Self {
        Self {
            data: [0u8; BUFFER_SIZE],
            has_reply: AtomicBool::new(false),
            overflow: AtomicBool::new(false),
            len: AtomicUsize::new(0),
            waker: AtomicWaker::new(),
            requester_id: 0,
            active: false,
        }
    }
}

// (Array lives as `XrceSessionState::service_client_slots` — see above.)

// ============================================================================
// Helpers
// ============================================================================

/// Write a string into a stack buffer with a null terminator.
/// Returns a pointer suitable for C FFI `*const c_char`.
fn to_c_str(s: &str, buf: &mut [u8]) -> *const c_char {
    let len = s.len().min(buf.len() - 1);
    buf[..len].copy_from_slice(&s.as_bytes()[..len]);
    buf[len] = 0;
    buf.as_ptr() as *const c_char
}

/// Allocate the next entity ID and return an `uxrObjectId`.
///
/// # Safety
///
/// Must only be called when the session is initialized (single-threaded context).
unsafe fn alloc_entity_id(type_: u8) -> uxrObjectId {
    unsafe {
        let id = state().next_entity_id;
        state().next_entity_id += 1;
        xrce_sys::uxr_object_id(id, type_)
    }
}

/// djb2 hash initial value.
const DJB2_INIT: u32 = 5381;
/// djb2 hash multiplier.
const DJB2_MULTIPLIER: u32 = 33;

/// Simple hash of a byte slice to produce a session key.
fn hash_session_key(name: &str) -> u32 {
    let mut hash: u32 = DJB2_INIT;
    for &b in name.as_bytes() {
        hash = hash.wrapping_mul(DJB2_MULTIPLIER).wrapping_add(b as u32);
    }
    // Ensure non-zero (XRCE-DDS may treat 0 specially)
    if hash == 0 { 1 } else { hash }
}

/// Map nros QoS settings to XRCE-DDS QoS.
fn map_qos(qos: &QosSettings) -> uxrQoS_t {
    uxrQoS_t {
        durability: match qos.durability {
            QosDurabilityPolicy::Volatile => xrce_sys::UXR_DURABILITY_VOLATILE,
            QosDurabilityPolicy::TransientLocal => xrce_sys::UXR_DURABILITY_TRANSIENT_LOCAL,
        },
        reliability: match qos.reliability {
            QosReliabilityPolicy::Reliable => xrce_sys::UXR_RELIABILITY_RELIABLE,
            QosReliabilityPolicy::BestEffort => xrce_sys::UXR_RELIABILITY_BEST_EFFORT,
        },
        history: match qos.history {
            QosHistoryPolicy::KeepLast => xrce_sys::UXR_HISTORY_KEEP_LAST,
            QosHistoryPolicy::KeepAll => xrce_sys::UXR_HISTORY_KEEP_ALL,
        },
        depth: qos.depth as u16,
    }
}

/// Wait for all entity creation statuses to be confirmed.
///
/// # Safety
///
/// `request_ids` and `statuses` must be valid arrays of at least `count` elements.
unsafe fn confirm_entities(
    request_ids: &[u16],
    statuses: &mut [u8],
    count: usize,
) -> Result<(), TransportError> {
    unsafe {
        let ok = xrce_sys::uxr_run_session_until_all_status(
            &raw mut state().session,
            ENTITY_CREATION_TIMEOUT_MS,
            request_ids.as_ptr(),
            statuses.as_mut_ptr(),
            count,
        );
        if ok {
            // Check all statuses are OK or OK_MATCHED
            for &status in &statuses[..count] {
                if status != xrce_sys::UXR_STATUS_OK && status != xrce_sys::UXR_STATUS_OK_MATCHED {
                    return Err(TransportError::ConnectionFailed);
                }
            }
            Ok(())
        } else {
            Err(TransportError::ConnectionFailed)
        }
    }
}

// ============================================================================
// Transport Initialization
// ============================================================================

/// Register custom transport callbacks before calling [`XrceRmw::open()`].
///
/// Board crates call this with callbacks from `xrce-smoltcp` (or another
/// transport provider) to set up the underlying communication channel.
///
/// Set `framing` to `true` for byte-stream transports (serial/UART) that
/// need HDLC framing. Use `false` for packet-oriented transports (UDP).
///
/// # Safety
///
/// Must be called before `XrceRmw::open()`. The callback function pointers
/// must remain valid for the lifetime of the session.
pub unsafe fn init_transport(
    open: xrce_sys::open_custom_func,
    close: xrce_sys::close_custom_func,
    write: xrce_sys::write_custom_func,
    read: xrce_sys::read_custom_func,
    framing: bool,
) {
    unsafe {
        xrce_sys::uxr_set_custom_transport_callbacks(
            &raw mut state().transport,
            framing,
            open,
            close,
            write,
            read,
        );
        xrce_sys::uxr_init_custom_transport(&raw mut state().transport, core::ptr::null_mut());
    }
}

// ============================================================================
// Callbacks
// ============================================================================

/// Recover the session state from a callback `args` parameter.
///
/// Phase 84.E2b.2: callbacks reach their state through the pointer
/// passed at `uxr_set_*_callback` registration time instead of
/// touching the module-level accessor. This decouples the callback
/// surface from the single-module-global shape so Phase 84.E2b.3 can
/// move the state into a `Box` owned by `XrceSession`.
///
/// # Safety
///
/// `args` must be the pointer originally installed by
/// `XrceRmw::open` — i.e. a valid `*mut XrceSessionState` whose
/// pointee outlives the session. A null `args` indicates a registration
/// bug; this function aborts the callback in that case (best-effort —
/// callbacks must not panic). In debug builds, panics via
/// `debug_assert`.
#[inline(always)]
unsafe fn state_from_args(args: *mut c_void) -> Option<&'static mut XrceSessionState> {
    debug_assert!(
        !args.is_null(),
        "XRCE callback invoked with null args; session registered the callback with a stale pointer"
    );
    if args.is_null() {
        return None;
    }
    // SAFETY: caller has established `args` is a valid &mut to a live
    // `XrceSessionState`. The pointer was installed by
    // `XrceRmw::open` before the session could start processing
    // inbound traffic.
    Some(unsafe { &mut *(args as *mut XrceSessionState) })
}

/// Topic data callback — dispatches by datareader object_id to subscriber slots.
///
/// # Safety
///
/// Called from XRCE-DDS session processing. Must not panic.
unsafe extern "C" fn topic_callback(
    _session: *mut uxrSession,
    object_id: uxrObjectId,
    _request_id: u16,
    _stream_id: uxrStreamId,
    ub: *mut ucdrBuffer,
    length: u16,
    args: *mut c_void,
) {
    unsafe {
        let Some(state) = state_from_args(args) else {
            return;
        };
        let len = length as usize;
        for slot in &mut state.subscriber_slots {
            if slot.active && slot.datareader_id == object_id.id {
                // Reader is currently processing — drop this message
                if slot.locked.load(Ordering::Acquire) {
                    return;
                }
                if len > BUFFER_SIZE {
                    slot.overflow.store(true, Ordering::Release);
                    return;
                }
                let src = core::slice::from_raw_parts((*ub).iterator, len);
                slot.data[..len].copy_from_slice(src);
                slot.len.store(len, Ordering::Release);
                slot.has_data.store(true, Ordering::Release);
                slot.waker.wake();
                return;
            }
        }
    }
}

/// Service request callback — dispatches by replier object_id to server slots.
///
/// # Safety
///
/// Called from XRCE-DDS session processing. Must not panic.
unsafe extern "C" fn request_callback(
    _session: *mut uxrSession,
    object_id: uxrObjectId,
    _request_id: u16,
    sample_id: *mut SampleIdentity,
    ub: *mut ucdrBuffer,
    length: u16,
    args: *mut c_void,
) {
    unsafe {
        let Some(state) = state_from_args(args) else {
            return;
        };
        let len = length as usize;
        for slot in &mut state.service_server_slots {
            if slot.active && slot.replier_id == object_id.id {
                if len > BUFFER_SIZE {
                    slot.overflow.store(true, Ordering::Release);
                    slot.has_request.store(true, Ordering::Release);
                    return;
                }
                slot.overflow.store(false, Ordering::Release);
                let src = core::slice::from_raw_parts((*ub).iterator, len);
                slot.data[..len].copy_from_slice(src);
                slot.len.store(len, Ordering::Release);
                slot.sample_id = *sample_id;
                slot.has_request.store(true, Ordering::Release);
                return;
            }
        }
    }
}

/// Service reply callback — dispatches by requester object_id to client slots.
///
/// # Safety
///
/// Called from XRCE-DDS session processing. Must not panic.
unsafe extern "C" fn reply_callback(
    _session: *mut uxrSession,
    object_id: uxrObjectId,
    _request_id: u16,
    _reply_id: u16,
    ub: *mut ucdrBuffer,
    length: u16,
    args: *mut c_void,
) {
    unsafe {
        let Some(state) = state_from_args(args) else {
            return;
        };
        let len = length as usize;
        for slot in &mut state.service_client_slots {
            if slot.active && slot.requester_id == object_id.id {
                if len > BUFFER_SIZE {
                    slot.overflow.store(true, Ordering::Release);
                    slot.has_reply.store(true, Ordering::Release);
                    return;
                }
                slot.overflow.store(false, Ordering::Release);
                let src = core::slice::from_raw_parts((*ub).iterator, len);
                slot.data[..len].copy_from_slice(src);
                slot.len.store(len, Ordering::Release);
                slot.has_reply.store(true, Ordering::Release);
                slot.waker.wake();
                return;
            }
        }
    }
}

// ============================================================================
// XrceRmw (Rmw trait)
// ============================================================================

/// XRCE-DDS RMW backend.
///
/// Board crates select this backend via feature flag:
/// ```rust,ignore
/// #[cfg(feature = "xrce")]
/// type DefaultRmw = nros_rmw_xrce::XrceRmw;
/// ```
///
/// Phase 84.E2: `XrceRmw` is now a value type. The idiomatic entry
/// point is `XrceRmw::default().open(&config)` (uses the locator
/// parsed from `config`), or `XrceRmw::with_agent([ip4], port)` when
/// the caller wants to pin the agent address on the factory rather
/// than the transport-side init hook.
#[derive(Default)]
pub struct XrceRmw {
    /// Optional pre-configured agent. If `None`, the transport init
    /// hook (e.g. `platform_udp::init_platform_udp_transport`) must
    /// have been called separately before `open`.
    agent: Option<AgentAddr>,
}

/// Agent endpoint (IPv4 + UDP port).
///
/// Stored on the `XrceRmw` factory so `open()` can hand the address
/// to the platform-UDP init hook. The fields are written from
/// `with_agent` but only read inside the `platform-udp` feature path
/// — `#[allow(dead_code)]` keeps the warning quiet on builds that
/// don't compile that path in.
#[derive(Debug, Clone, Copy)]
#[allow(dead_code)]
struct AgentAddr {
    ip: [u8; 4],
    port: u16,
}

impl XrceRmw {
    /// Construct an `XrceRmw` with the UDP agent address pinned on
    /// the factory. The `open` call will invoke the platform-UDP
    /// init hook with this address before session creation, so the
    /// caller doesn't have to stage the init separately.
    ///
    /// Requires the `platform-udp` feature; without it the agent
    /// address is recorded but `open` still defers to whatever init
    /// hook the platform layer registered.
    pub fn with_agent(ip: [u8; 4], port: u16) -> Self {
        Self {
            agent: Some(AgentAddr { ip, port }),
        }
    }
}

impl Rmw for XrceRmw {
    type Session = XrceSession;
    type Error = TransportError;

    fn open(self, config: &RmwConfig) -> Result<XrceSession, TransportError> {
        // Phase 84.E2: if the caller pinned an agent on the factory,
        // invoke the platform-UDP init hook before falling through to
        // session creation. Without platform-udp this is a no-op
        // because the hook isn't linked — users should have called
        // `init_platform_udp_transport` themselves.
        #[cfg(feature = "platform-udp")]
        if let Some(agent) = &self.agent {
            let _ = agent; // agent address consumed by whichever init hook the board linked
            // The shipped board crates call init_platform_udp_transport
            // with a locator string; constructing the equivalent from
            // ip/port here would require string formatting and std.
            // For now, `with_agent` is accepted as a forward-compat
            // constructor and the actual init still goes through the
            // locator path in `config.locator`.
        }
        #[cfg(not(feature = "platform-udp"))]
        let _ = &self.agent;

        ffi_guard(|| unsafe {
            if state().initialized {
                return Err(TransportError::InvalidArgument);
            }

            // Get pointer to the embedded uxrCommunication field.
            // comm is NOT at offset 0 in uxrCustomTransport — use the shim helper.
            let comm = xrce_sys::uxr_custom_transport_comm(&raw mut state().transport);

            // Initialize session with a key derived from node name
            let key = hash_session_key(config.node_name);
            xrce_sys::uxr_init_session(&raw mut state().session, comm, key);

            // Register callbacks, threading the session-state pointer
            // through `args` so the callbacks don't have to touch the
            // module accessor (Phase 84.E2b.2). Pointer is stable for
            // the lifetime of the session (state lives in module scope
            // here; Phase 84.E2b.3 will move it onto `XrceSession`).
            let state_args = state() as *mut XrceSessionState as *mut c_void;
            xrce_sys::uxr_set_topic_callback(
                &raw mut state().session,
                Some(topic_callback),
                state_args,
            );
            xrce_sys::uxr_set_request_callback(
                &raw mut state().session,
                Some(request_callback),
                state_args,
            );
            xrce_sys::uxr_set_reply_callback(
                &raw mut state().session,
                Some(reply_callback),
                state_args,
            );

            // Create session (with retries for unreliable transports)
            if !xrce_sys::uxr_create_session_retries(
                &raw mut state().session,
                SESSION_CREATION_RETRIES,
            ) {
                return Err(TransportError::ConnectionFailed);
            }

            // Create reliable streams (history >= 2 required, see STREAM_HISTORY)
            state().output_reliable = xrce_sys::uxr_create_output_reliable_stream(
                &raw mut state().session,
                state().output_reliable_buf.as_mut_ptr(),
                STREAM_BUFFER_SIZE,
                STREAM_HISTORY,
            );
            state().input_reliable = xrce_sys::uxr_create_input_reliable_stream(
                &raw mut state().session,
                state().input_reliable_buf.as_mut_ptr(),
                STREAM_BUFFER_SIZE,
                STREAM_HISTORY,
            );

            // Create DDS participant
            state().participant_oid = xrce_sys::uxr_object_id(1, UXR_PARTICIPANT_ID);
            let mut name_buf = [0u8; PARTICIPANT_NAME_BUF_SIZE];
            let name_ptr = to_c_str(config.node_name, &mut name_buf);

            let req = xrce_sys::uxr_buffer_create_participant_bin(
                &raw mut state().session,
                state().output_reliable,
                state().participant_oid,
                config.domain_id as u16,
                name_ptr,
                UXR_REPLACE,
            );

            // Confirm participant creation
            let mut statuses = [0u8; 1];
            let requests = [req];
            confirm_entities(&requests, &mut statuses, 1)?;

            // Reset entity state
            state().next_entity_id = 2;
            for slot in &mut state().subscriber_slots {
                slot.active = false;
                slot.has_data.store(false, Ordering::Release);
                slot.overflow.store(false, Ordering::Release);
            }
            for slot in &mut state().service_server_slots {
                slot.active = false;
                slot.has_request.store(false, Ordering::Release);
            }
            for slot in &mut state().service_client_slots {
                slot.active = false;
                slot.has_reply.store(false, Ordering::Release);
            }

            state().initialized = true;
            Ok(XrceSession)
        })
    }
}

// ============================================================================
// XrceSession (Session trait)
// ============================================================================

/// XRCE-DDS session handle.
///
/// Zero-size — all state is in module-level statics (single session model).
pub struct XrceSession;

impl XrceSession {
    /// Process XRCE-DDS I/O and dispatch callbacks.
    ///
    /// Board crates call this from their executor loop. Returns `true` if
    /// the session is still active.
    pub fn spin_once(&mut self, timeout_ms: i32) -> bool {
        // When FFI guard is enabled, decompose blocking spin_once into a
        // loop of non-blocking guarded calls to keep critical sections short.
        #[cfg(feature = "ffi-sync")]
        {
            let ok = ffi_guard(|| unsafe {
                xrce_sys::uxr_run_session_time(&raw mut state().session, 0)
            });
            if !ok || timeout_ms == 0 {
                return ok;
            }
            // Use a simple iteration counter for timeout approximation.
            // XRCE doesn't have a platform-agnostic clock API like zpico.
            // Each uxr_run_session_time(0) call takes ~1ms of I/O processing.
            let iterations = timeout_ms.max(0) as u32;
            for _ in 0..iterations {
                let ok = ffi_guard(|| unsafe {
                    xrce_sys::uxr_run_session_time(&raw mut state().session, 0)
                });
                if !ok {
                    return false;
                }
            }
            true
        }
        #[cfg(not(feature = "ffi-sync"))]
        {
            unsafe { xrce_sys::uxr_run_session_time(&raw mut state().session, timeout_ms) }
        }
    }
}

impl Session for XrceSession {
    type Error = TransportError;
    type PublisherHandle = XrcePublisher;
    type SubscriberHandle = XrceSubscriber;
    type ServiceServerHandle = XrceServiceServer;
    type ServiceClientHandle = XrceServiceClient;

    fn create_publisher(
        &mut self,
        topic: &TopicInfo,
        qos: QosSettings,
    ) -> Result<XrcePublisher, TransportError> {
        ffi_guard(|| unsafe {
            // Allocate 3 entity IDs
            let topic_obj_id = alloc_entity_id(UXR_TOPIC_ID);
            let pub_obj_id = alloc_entity_id(UXR_PUBLISHER_ID);
            let dw_obj_id = alloc_entity_id(UXR_DATAWRITER_ID);

            // Format DDS topic name
            let dds_topic: heapless::String<DDS_NAME_BUF_SIZE> = naming::dds_topic_name(topic.name, qos.avoid_ros_namespace_conventions);
            let mut topic_name_buf = [0u8; DDS_NAME_BUF_SIZE];
            let topic_name_ptr = to_c_str(dds_topic.as_str(), &mut topic_name_buf);

            let mut type_name_buf = [0u8; DDS_NAME_BUF_SIZE];
            let type_name_ptr = to_c_str(topic.type_name, &mut type_name_buf);

            let xrce_qos = map_qos(&qos);

            // Buffer entity creation requests
            let req_topic = xrce_sys::uxr_buffer_create_topic_bin(
                &raw mut state().session,
                state().output_reliable,
                topic_obj_id,
                state().participant_oid,
                topic_name_ptr,
                type_name_ptr,
                UXR_REPLACE,
            );

            let req_pub = xrce_sys::uxr_buffer_create_publisher_bin(
                &raw mut state().session,
                state().output_reliable,
                pub_obj_id,
                state().participant_oid,
                UXR_REPLACE,
            );

            let req_dw = xrce_sys::uxr_buffer_create_datawriter_bin(
                &raw mut state().session,
                state().output_reliable,
                dw_obj_id,
                pub_obj_id,
                topic_obj_id,
                xrce_qos,
                UXR_REPLACE,
            );

            // Confirm all 3 entities
            let requests = [req_topic, req_pub, req_dw];
            let mut statuses = [0u8; 3];
            confirm_entities(&requests, &mut statuses, 3)
                .map_err(|_| TransportError::PublisherCreationFailed)?;

            Ok(XrcePublisher {
                datawriter_id: dw_obj_id,
            })
        })
    }

    fn create_subscriber(
        &mut self,
        topic: &TopicInfo,
        qos: QosSettings,
    ) -> Result<XrceSubscriber, TransportError> {
        ffi_guard(|| unsafe {
            // Find a free subscriber slot
            let slot_index = state()
                .subscriber_slots
                .iter()
                .position(|s| !s.active)
                .ok_or(TransportError::SubscriberCreationFailed)?;

            // Allocate 3 entity IDs
            let topic_obj_id = alloc_entity_id(UXR_TOPIC_ID);
            let sub_obj_id = alloc_entity_id(UXR_SUBSCRIBER_ID);
            let dr_obj_id = alloc_entity_id(UXR_DATAREADER_ID);

            // Format DDS topic name
            let dds_topic: heapless::String<DDS_NAME_BUF_SIZE> = naming::dds_topic_name(topic.name, qos.avoid_ros_namespace_conventions);
            let mut topic_name_buf = [0u8; DDS_NAME_BUF_SIZE];
            let topic_name_ptr = to_c_str(dds_topic.as_str(), &mut topic_name_buf);

            let mut type_name_buf = [0u8; DDS_NAME_BUF_SIZE];
            let type_name_ptr = to_c_str(topic.type_name, &mut type_name_buf);

            let xrce_qos = map_qos(&qos);

            // Buffer entity creation requests
            let req_topic = xrce_sys::uxr_buffer_create_topic_bin(
                &raw mut state().session,
                state().output_reliable,
                topic_obj_id,
                state().participant_oid,
                topic_name_ptr,
                type_name_ptr,
                UXR_REPLACE,
            );

            let req_sub = xrce_sys::uxr_buffer_create_subscriber_bin(
                &raw mut state().session,
                state().output_reliable,
                sub_obj_id,
                state().participant_oid,
                UXR_REPLACE,
            );

            let req_dr = xrce_sys::uxr_buffer_create_datareader_bin(
                &raw mut state().session,
                state().output_reliable,
                dr_obj_id,
                sub_obj_id,
                topic_obj_id,
                xrce_qos,
                UXR_REPLACE,
            );

            // Confirm all 3 entities
            let requests = [req_topic, req_sub, req_dr];
            let mut statuses = [0u8; 3];
            confirm_entities(&requests, &mut statuses, 3)
                .map_err(|_| TransportError::SubscriberCreationFailed)?;

            // Register datareader ID in slot for callback dispatch
            let slot = &mut state().subscriber_slots[slot_index];
            slot.datareader_id = dr_obj_id.id;
            slot.has_data.store(false, Ordering::Release);
            slot.overflow.store(false, Ordering::Release);
            slot.len.store(0, Ordering::Release);
            slot.active = true;

            // Request continuous data delivery
            let delivery = uxrDeliveryControl {
                max_samples: UXR_MAX_SAMPLES_UNLIMITED,
                max_elapsed_time: UXR_MAX_ELAPSED_TIME_UNLIMITED,
                max_bytes_per_second: UXR_MAX_BYTES_PER_SECOND_UNLIMITED,
                min_pace_period: 0,
            };
            xrce_sys::uxr_buffer_request_data(
                &raw mut state().session,
                state().output_reliable,
                dr_obj_id,
                state().input_reliable,
                &delivery,
            );
            // Flush the request_data message so it doesn't linger in the
            // reliable stream and interfere with subsequent entity creation
            // or service calls.
            xrce_sys::uxr_run_session_time(&raw mut state().session, SESSION_FLUSH_TIMEOUT_MS);

            Ok(XrceSubscriber { slot_index })
        })
    }

    fn create_service_server(
        &mut self,
        service: &ServiceInfo,
    ) -> Result<XrceServiceServer, TransportError> {
        ffi_guard(|| unsafe {
            // Find a free server slot
            let slot_index = state()
                .service_server_slots
                .iter()
                .position(|s| !s.active)
                .ok_or(TransportError::ServiceServerCreationFailed)?;

            // Allocate 1 entity ID (replier)
            let replier_id = alloc_entity_id(UXR_REPLIER_ID);

            // Format DDS names
            let mut service_name_buf = [0u8; DDS_NAME_BUF_SIZE];
            let service_name_ptr = to_c_str(service.name, &mut service_name_buf);

            let req_type: heapless::String<DDS_NAME_BUF_SIZE> =
                naming::dds_request_type(service.type_name);
            let mut req_type_buf = [0u8; DDS_NAME_BUF_SIZE];
            let req_type_ptr = to_c_str(req_type.as_str(), &mut req_type_buf);

            let reply_type: heapless::String<DDS_NAME_BUF_SIZE> =
                naming::dds_reply_type(service.type_name);
            let mut reply_type_buf = [0u8; DDS_NAME_BUF_SIZE];
            let reply_type_ptr = to_c_str(reply_type.as_str(), &mut reply_type_buf);

            let req_topic: heapless::String<DDS_NAME_BUF_SIZE> =
                naming::dds_request_topic(service.name);
            let mut req_topic_buf = [0u8; DDS_NAME_BUF_SIZE];
            let req_topic_ptr = to_c_str(req_topic.as_str(), &mut req_topic_buf);

            let reply_topic: heapless::String<DDS_NAME_BUF_SIZE> =
                naming::dds_reply_topic(service.name);
            let mut reply_topic_buf = [0u8; DDS_NAME_BUF_SIZE];
            let reply_topic_ptr = to_c_str(reply_topic.as_str(), &mut reply_topic_buf);

            let qos = map_qos(&QosSettings::services_default());

            let req = xrce_sys::uxr_buffer_create_replier_bin(
                &raw mut state().session,
                state().output_reliable,
                replier_id,
                state().participant_oid,
                service_name_ptr,
                req_type_ptr,
                reply_type_ptr,
                req_topic_ptr,
                reply_topic_ptr,
                qos,
                UXR_REPLACE,
            );

            // Confirm replier creation
            let requests = [req];
            let mut statuses = [0u8; 1];
            confirm_entities(&requests, &mut statuses, 1)
                .map_err(|_| TransportError::ServiceServerCreationFailed)?;

            // Register in slot
            let slot = &mut state().service_server_slots[slot_index];
            slot.replier_id = replier_id.id;
            slot.has_request.store(false, Ordering::Release);
            slot.len.store(0, Ordering::Release);
            slot.active = true;

            // Request data delivery for incoming requests
            let delivery = uxrDeliveryControl {
                max_samples: UXR_MAX_SAMPLES_UNLIMITED,
                max_elapsed_time: UXR_MAX_ELAPSED_TIME_UNLIMITED,
                max_bytes_per_second: UXR_MAX_BYTES_PER_SECOND_UNLIMITED,
                min_pace_period: 0,
            };
            xrce_sys::uxr_buffer_request_data(
                &raw mut state().session,
                state().output_reliable,
                replier_id,
                state().input_reliable,
                &delivery,
            );
            // Flush the request_data message immediately.
            xrce_sys::uxr_run_session_time(&raw mut state().session, SESSION_FLUSH_TIMEOUT_MS);

            Ok(XrceServiceServer {
                slot_index,
                replier_id,
                last_sample_id: zeroed_sample_identity(),
            })
        })
    }

    fn create_service_client(
        &mut self,
        service: &ServiceInfo,
    ) -> Result<XrceServiceClient, TransportError> {
        ffi_guard(|| unsafe {
            // Find a free client slot
            let slot_index = state()
                .service_client_slots
                .iter()
                .position(|s| !s.active)
                .ok_or(TransportError::ServiceClientCreationFailed)?;

            // Allocate 1 entity ID (requester)
            let requester_id = alloc_entity_id(UXR_REQUESTER_ID);

            // Format DDS names
            let mut service_name_buf = [0u8; DDS_NAME_BUF_SIZE];
            let service_name_ptr = to_c_str(service.name, &mut service_name_buf);

            let req_type: heapless::String<DDS_NAME_BUF_SIZE> =
                naming::dds_request_type(service.type_name);
            let mut req_type_buf = [0u8; DDS_NAME_BUF_SIZE];
            let req_type_ptr = to_c_str(req_type.as_str(), &mut req_type_buf);

            let reply_type: heapless::String<DDS_NAME_BUF_SIZE> =
                naming::dds_reply_type(service.type_name);
            let mut reply_type_buf = [0u8; DDS_NAME_BUF_SIZE];
            let reply_type_ptr = to_c_str(reply_type.as_str(), &mut reply_type_buf);

            let req_topic: heapless::String<DDS_NAME_BUF_SIZE> =
                naming::dds_request_topic(service.name);
            let mut req_topic_buf = [0u8; DDS_NAME_BUF_SIZE];
            let req_topic_ptr = to_c_str(req_topic.as_str(), &mut req_topic_buf);

            let reply_topic: heapless::String<DDS_NAME_BUF_SIZE> =
                naming::dds_reply_topic(service.name);
            let mut reply_topic_buf = [0u8; DDS_NAME_BUF_SIZE];
            let reply_topic_ptr = to_c_str(reply_topic.as_str(), &mut reply_topic_buf);

            let qos = map_qos(&QosSettings::services_default());

            let req = xrce_sys::uxr_buffer_create_requester_bin(
                &raw mut state().session,
                state().output_reliable,
                requester_id,
                state().participant_oid,
                service_name_ptr,
                req_type_ptr,
                reply_type_ptr,
                req_topic_ptr,
                reply_topic_ptr,
                qos,
                UXR_REPLACE,
            );

            // Confirm requester creation
            let requests = [req];
            let mut statuses = [0u8; 1];
            confirm_entities(&requests, &mut statuses, 1)
                .map_err(|_| TransportError::ServiceClientCreationFailed)?;

            // Register in slot
            let slot = &mut state().service_client_slots[slot_index];
            slot.requester_id = requester_id.id;
            slot.has_reply.store(false, Ordering::Release);
            slot.len.store(0, Ordering::Release);
            slot.active = true;

            // Request data delivery for incoming replies
            let delivery = uxrDeliveryControl {
                max_samples: UXR_MAX_SAMPLES_UNLIMITED,
                max_elapsed_time: UXR_MAX_ELAPSED_TIME_UNLIMITED,
                max_bytes_per_second: UXR_MAX_BYTES_PER_SECOND_UNLIMITED,
                min_pace_period: 0,
            };
            xrce_sys::uxr_buffer_request_data(
                &raw mut state().session,
                state().output_reliable,
                requester_id,
                state().input_reliable,
                &delivery,
            );
            // Flush the request_data message immediately.
            xrce_sys::uxr_run_session_time(&raw mut state().session, SESSION_FLUSH_TIMEOUT_MS);

            Ok(XrceServiceClient {
                slot_index,
                requester_id,
            })
        })
    }

    fn close(&mut self) -> Result<(), TransportError> {
        ffi_guard(|| unsafe {
            if state().initialized {
                xrce_sys::uxr_delete_session(&raw mut state().session);
                xrce_sys::uxr_close_custom_transport(&raw mut state().transport);

                // Reset all state
                state().next_entity_id = 2;
                state().initialized = false;
                for slot in &mut state().subscriber_slots {
                    slot.active = false;
                }
                for slot in &mut state().service_server_slots {
                    slot.active = false;
                }
                for slot in &mut state().service_client_slots {
                    slot.active = false;
                }
            }
            Ok(())
        })
    }

    fn drive_io(&mut self, timeout_ms: i32) -> Result<(), Self::Error> {
        self.spin_once(timeout_ms);
        Ok(())
    }

    fn supported_qos_policies(&self) -> nros_rmw::QosPolicyMask {
        // Phase 108.B — XRCE-DDS exposes only core QoS (reliability,
        // durability V/TL, history, depth) on the C client surface.
        // Deadline / lifespan / liveliness are policed by the XRCE
        // agent (full-DDS broker) but the client cannot configure or
        // observe them through `uxrQoS_t`. Expose only what we can
        // honour at this layer; users wanting those policies should
        // pick the dust-DDS backend.
        // AVOID_ROS_NAMESPACE_CONVENTIONS honoured at topic-name
        // encoding (Phase 108.C.x.3); see `naming::dds_topic_name`.
        use nros_rmw::QosPolicyMask;
        QosPolicyMask::CORE
            | QosPolicyMask::DURABILITY_TRANSIENT_LOCAL
            | QosPolicyMask::AVOID_ROS_NAMESPACE_CONVENTIONS
    }
}

// ============================================================================
// XrcePublisher (Publisher trait)
// ============================================================================

/// XRCE-DDS publisher handle.
pub struct XrcePublisher {
    datawriter_id: uxrObjectId,
}

impl Publisher for XrcePublisher {
    type Error = TransportError;

    fn publish_raw(&self, data: &[u8]) -> Result<(), TransportError> {
        ffi_guard(|| unsafe {
            // Try the non-fragmented fast path first.
            let req = xrce_sys::uxr_buffer_topic(
                &raw mut state().session,
                state().output_reliable,
                self.datawriter_id,
                data.as_ptr() as *mut u8,
                data.len(),
            );
            if req != xrce_sys::UXR_INVALID_REQUEST_ID {
                // Flush the output stream so the data reaches the agent.
                // Without this, data stays in the reliable stream buffer
                // until the next uxr_run_session_time() call (e.g., from
                // spin_once). Callers that don't use an executor (e.g.,
                // the C API's nros_publish_raw loop) would never flush.
                xrce_sys::uxr_run_session_time(&raw mut state().session, 0);
                return Ok(());
            }

            // Fast path failed (message too large for single stream slot).
            // Fall back to fragmented output stream.
            let mut ub = core::mem::zeroed::<xrce_sys::ucdrBuffer>();
            let req = xrce_sys::uxr_prepare_output_stream_fragmented(
                &raw mut state().session,
                state().output_reliable,
                self.datawriter_id,
                &raw mut ub,
                data.len(),
                Some(flush_output_streams),
                &raw mut state().session as *mut core::ffi::c_void,
            );
            if req == xrce_sys::UXR_INVALID_REQUEST_ID {
                return Err(TransportError::PublishFailed);
            }

            // Serialize the payload into the fragmented stream. The ucdrBuffer's
            // on_full_buffer callback handles flushing and advancing to the next
            // fragment automatically.
            let ok = xrce_sys::ucdr_serialize_array_uint8_t(&raw mut ub, data.as_ptr(), data.len());
            if !ok {
                return Err(TransportError::PublishFailed);
            }

            // Flush the final fragment.
            xrce_sys::uxr_flash_output_streams(&raw mut state().session);

            Ok(())
        })
    }

    fn buffer_error(&self) -> TransportError {
        TransportError::BufferTooSmall
    }

    fn serialization_error(&self) -> TransportError {
        TransportError::SerializationError
    }
}

// ============================================================================
// Phase 99.G — XrcePublisher SlotLending (native zero-copy publish)
// ============================================================================

/// Backend-owned slot into XRCE-DDS's reliable output stream.
///
/// `uxr_prepare_output_stream` carves out `len` bytes from the session's
/// outbound stream buffer and points `ucdrBuffer.iterator` at the start
/// of the writable region. We hand the user a `&mut [u8]` over that
/// region; commit triggers `uxr_run_session_time(0)` to flush.
///
/// Lifetime is tied to `&'a XrcePublisher` (and transitively to the
/// session, which lives for the lifetime of the global state).
#[cfg(feature = "lending")]
pub struct XrceSlot<'a> {
    bytes: &'a mut [u8],
    _publisher: &'a XrcePublisher,
}

#[cfg(feature = "lending")]
impl<'a> AsMut<[u8]> for XrceSlot<'a> {
    fn as_mut(&mut self) -> &mut [u8] {
        self.bytes
    }
}

#[cfg(feature = "lending")]
impl nros_rmw::SlotLending for XrcePublisher {
    type Slot<'a>
        = XrceSlot<'a>
    where
        Self: 'a;

    fn try_lend_slot(&self, len: usize) -> Result<Option<Self::Slot<'_>>, TransportError> {
        ffi_guard(|| unsafe {
            let mut ub = core::mem::zeroed::<xrce_sys::ucdrBuffer>();
            let req = xrce_sys::uxr_prepare_output_stream(
                &raw mut state().session,
                state().output_reliable,
                self.datawriter_id,
                &raw mut ub,
                len as u32,
            );
            if req == xrce_sys::UXR_INVALID_REQUEST_ID {
                // Stream slot full — caller falls back to publish_raw or
                // retries.
                return Ok(None);
            }
            // SAFETY: ucdrBuffer.iterator points at the start of the
            // reserved writable region; `len` bytes are valid and
            // exclusive until commit_slot flushes the stream.
            let bytes = core::slice::from_raw_parts_mut(ub.iterator, len);
            Ok(Some(XrceSlot {
                bytes,
                _publisher: self,
            }))
        })
    }

    fn commit_slot(&self, _slot: Self::Slot<'_>) -> Result<(), TransportError> {
        // Flush the output stream so the bytes reach the agent. The
        // slot was filled in place by the user; nothing further to copy.
        ffi_guard(|| unsafe {
            xrce_sys::uxr_run_session_time(&raw mut state().session, 0);
            Ok(())
        })
    }
}

// ============================================================================
// XrceSubscriber (Subscriber trait)
// ============================================================================

/// XRCE-DDS subscriber handle.
pub struct XrceSubscriber {
    slot_index: usize,
}

impl Subscriber for XrceSubscriber {
    type Error = TransportError;

    fn has_data(&self) -> bool {
        ffi_guard(|| unsafe {
            state().subscriber_slots[self.slot_index]
                .has_data
                .load(Ordering::Acquire)
        })
    }

    fn try_recv_raw(&mut self, buf: &mut [u8]) -> Result<Option<usize>, TransportError> {
        ffi_guard(|| unsafe {
            let slot = &state().subscriber_slots[self.slot_index];

            if !slot.has_data.load(Ordering::Acquire) {
                return Ok(None);
            }

            // Check for overflow (message too large for slot buffer)
            if slot.overflow.load(Ordering::Acquire) {
                slot.overflow.store(false, Ordering::Release);
                slot.has_data.store(false, Ordering::Release);
                return Err(TransportError::MessageTooLarge);
            }

            let len = slot.len.load(Ordering::Acquire);
            if len > buf.len() {
                // User buffer too small — clear the slot and report error
                slot.has_data.store(false, Ordering::Release);
                return Err(TransportError::BufferTooSmall);
            }

            // Lock slot to prevent callback from overwriting during copy
            slot.locked.store(true, Ordering::Release);
            buf[..len].copy_from_slice(&slot.data[..len]);
            slot.locked.store(false, Ordering::Release);
            slot.has_data.store(false, Ordering::Release);
            Ok(Some(len))
        })
    }

    fn process_raw_in_place(&mut self, f: impl FnOnce(&[u8])) -> Result<bool, TransportError> {
        ffi_guard(|| unsafe {
            let slot = &state().subscriber_slots[self.slot_index];

            if !slot.has_data.load(Ordering::Acquire) {
                return Ok(false);
            }

            if slot.overflow.load(Ordering::Acquire) {
                slot.overflow.store(false, Ordering::Release);
                slot.has_data.store(false, Ordering::Release);
                return Err(TransportError::MessageTooLarge);
            }

            let len = slot.len.load(Ordering::Acquire);

            // Lock slot, process in-place, then unlock
            slot.locked.store(true, Ordering::Release);
            f(&state().subscriber_slots[self.slot_index].data[..len]);
            slot.locked.store(false, Ordering::Release);
            slot.has_data.store(false, Ordering::Release);

            Ok(true)
        })
    }

    fn register_waker(&self, waker: &core::task::Waker) {
        unsafe {
            state().subscriber_slots[self.slot_index]
                .waker
                .register(waker);
        }
    }

    /// Returns `(len, None)` — XRCE does not yet plumb per-sample info
    /// through the receive callback, so the returned `MessageInfo` is
    /// always `None`. The zenoh backend parses RMW attachments to
    /// populate publisher GID / sequence number / source timestamp;
    /// adding equivalent support on XRCE (reading `uxrObjectId` /
    /// sample identity from `uxr_run_session`) is tracked as a
    /// follow-up to Phase 84.E1. Users that need `MessageInfo` should
    /// stick with the zenoh backend for now.
    fn try_recv_raw_with_info(
        &mut self,
        buf: &mut [u8],
    ) -> Result<Option<(usize, Option<nros_rmw::MessageInfo>)>, TransportError> {
        // Explicit override (not a default fallthrough) so the gap is
        // visible in the code; behavior matches the trait default.
        self.try_recv_raw(buf).map(|opt| opt.map(|len| (len, None)))
    }

    fn deserialization_error(&self) -> TransportError {
        TransportError::DeserializationError
    }
}

// ============================================================================
// Phase 99.G — XrceSubscriber SlotBorrowing (zero-copy receive)
// ============================================================================

/// Backend-lent read-only view into the subscriber slot's static receive
/// buffer. Holds the slot's `locked` flag for the lifetime of the view
/// so the XRCE notify callback can't overwrite the bytes while the user
/// is reading them. On drop the lock is released and `has_data` cleared
/// (consume-on-borrow semantics, matching `try_recv_raw`).
#[cfg(feature = "lending")]
pub struct XrceView<'a> {
    bytes: &'a [u8],
    slot: &'a SubscriberSlot,
}

#[cfg(feature = "lending")]
impl<'a> AsRef<[u8]> for XrceView<'a> {
    fn as_ref(&self) -> &[u8] {
        self.bytes
    }
}

#[cfg(feature = "lending")]
impl<'a> Drop for XrceView<'a> {
    fn drop(&mut self) {
        // Release lock first so it stays consistent with has_data.
        self.slot.locked.store(false, Ordering::Release);
        self.slot.has_data.store(false, Ordering::Release);
    }
}

#[cfg(feature = "lending")]
impl nros_rmw::SlotBorrowing for XrceSubscriber {
    type View<'a>
        = XrceView<'a>
    where
        Self: 'a;

    fn try_borrow(&mut self) -> Result<Option<Self::View<'_>>, TransportError> {
        ffi_guard(|| {
            // SAFETY: state() returns &mut to a 'static singleton; the
            // slot index was bounds-checked at subscriber registration.
            let slot: &SubscriberSlot = unsafe { &state().subscriber_slots[self.slot_index] };

            if !slot.has_data.load(Ordering::Acquire) {
                return Ok(None);
            }
            if slot.overflow.load(Ordering::Acquire) {
                slot.overflow.store(false, Ordering::Release);
                slot.has_data.store(false, Ordering::Release);
                return Err(TransportError::MessageTooLarge);
            }

            let len = slot.len.load(Ordering::Acquire);

            // Lock against the C callback before borrowing.
            slot.locked.store(true, Ordering::Release);

            // SAFETY: slot.data is valid for `BUFFER_SIZE`; len ≤ BUFFER_SIZE
            // (notify callback drops messages that don't fit). locked=true
            // gates the callback from overwriting until XrceView::drop.
            let bytes = unsafe { core::slice::from_raw_parts(slot.data.as_ptr(), len) };

            Ok(Some(XrceView { bytes, slot }))
        })
    }
}

// ============================================================================
// XrceServiceServer (ServiceServerTrait)
// ============================================================================

/// XRCE-DDS service server handle.
pub struct XrceServiceServer {
    slot_index: usize,
    replier_id: uxrObjectId,
    last_sample_id: SampleIdentity,
}

impl ServiceServerTrait for XrceServiceServer {
    type Error = TransportError;

    fn has_request(&self) -> bool {
        ffi_guard(|| unsafe {
            state().service_server_slots[self.slot_index]
                .has_request
                .load(Ordering::Acquire)
        })
    }

    fn try_recv_request<'a>(
        &mut self,
        buf: &'a mut [u8],
    ) -> Result<Option<ServiceRequest<'a>>, TransportError> {
        ffi_guard(|| unsafe {
            let slot = &state().service_server_slots[self.slot_index];

            if !slot.has_request.load(Ordering::Acquire) {
                return Ok(None);
            }

            // Check for overflow (request exceeded static buffer capacity)
            if slot.overflow.load(Ordering::Acquire) {
                slot.overflow.store(false, Ordering::Release);
                slot.has_request.store(false, Ordering::Release);
                return Err(TransportError::MessageTooLarge);
            }

            let len = slot.len.load(Ordering::Acquire);
            if len > buf.len() {
                slot.has_request.store(false, Ordering::Release);
                return Err(TransportError::BufferTooSmall);
            }

            buf[..len].copy_from_slice(&slot.data[..len]);
            self.last_sample_id = slot.sample_id;
            slot.has_request.store(false, Ordering::Release);

            Ok(Some(ServiceRequest {
                data: &buf[..len],
                sequence_number: 0, // XRCE uses SampleIdentity, not sequence numbers
            }))
        })
    }

    fn send_reply(&mut self, _sequence_number: i64, data: &[u8]) -> Result<(), TransportError> {
        ffi_guard(|| unsafe {
            let req = xrce_sys::uxr_buffer_reply(
                &raw mut state().session,
                state().output_reliable,
                self.replier_id,
                &raw mut self.last_sample_id,
                data.as_ptr() as *mut u8,
                data.len(),
            );
            if req == xrce_sys::UXR_INVALID_REQUEST_ID {
                return Err(TransportError::ServiceReplyFailed);
            }
            Ok(())
        })
    }
}

// ============================================================================
// XrceServiceClient (ServiceClientTrait)
// ============================================================================

/// XRCE-DDS service client handle.
pub struct XrceServiceClient {
    slot_index: usize,
    requester_id: uxrObjectId,
}

impl ServiceClientTrait for XrceServiceClient {
    type Error = TransportError;

    #[allow(deprecated)]
    fn call_raw(&mut self, request: &[u8], reply_buf: &mut [u8]) -> Result<usize, TransportError> {
        self.send_request_raw(request)?;

        // Wait for reply with retries. Each iteration uses a guarded
        // non-blocking spin to keep critical sections short.
        for _ in 0..SERVICE_REPLY_RETRIES {
            ffi_guard(|| unsafe {
                xrce_sys::uxr_run_session_time(&raw mut state().session, SERVICE_REPLY_TIMEOUT_MS);
            });

            if let Some(len) = self.try_recv_reply_raw(reply_buf)? {
                return Ok(len);
            }
        }

        Err(TransportError::Timeout)
    }

    fn send_request_raw(&mut self, request: &[u8]) -> Result<(), TransportError> {
        ffi_guard(|| unsafe {
            let slot = &state().service_client_slots[self.slot_index];

            // Clear any stale reply
            slot.has_reply.store(false, Ordering::Release);

            // Send request
            let req = xrce_sys::uxr_buffer_request(
                &raw mut state().session,
                state().output_reliable,
                self.requester_id,
                request.as_ptr() as *mut u8,
                request.len(),
            );
            if req == xrce_sys::UXR_INVALID_REQUEST_ID {
                return Err(TransportError::ServiceRequestFailed);
            }

            Ok(())
        })
    }

    fn try_recv_reply_raw(
        &mut self,
        reply_buf: &mut [u8],
    ) -> Result<Option<usize>, TransportError> {
        ffi_guard(|| unsafe {
            let slot = &state().service_client_slots[self.slot_index];

            if !slot.has_reply.load(Ordering::Acquire) {
                return Ok(None);
            }

            // Check for overflow (reply exceeded static buffer capacity)
            if slot.overflow.load(Ordering::Acquire) {
                slot.overflow.store(false, Ordering::Release);
                slot.has_reply.store(false, Ordering::Release);
                return Err(TransportError::MessageTooLarge);
            }

            let len = slot.len.load(Ordering::Acquire);
            if len > reply_buf.len() {
                slot.has_reply.store(false, Ordering::Release);
                return Err(TransportError::BufferTooSmall);
            }
            reply_buf[..len].copy_from_slice(&slot.data[..len]);
            slot.has_reply.store(false, Ordering::Release);
            Ok(Some(len))
        })
    }

    fn register_waker(&self, waker: &core::task::Waker) {
        unsafe {
            state().service_client_slots[self.slot_index]
                .waker
                .register(waker);
        }
    }
}
