meta:
  version: 1
  inputs:
  - path: /home/aeon/repos/nano-ros/examples/workspaces/ws-safety-cpp/src/demo_bringup/launch/safety_talker.launch.xml
    sha256: 06c749581177af60195426fdbb7e128cdf3945d783dc66c59fbfde5926d0d200
  resolver:
    tool: play_launch
    version: 0.8.2
structure:
  scopes:
    /: {}
  nodes:
    /talker:
      scope: /
      pkg: cpp_safety_talker_pkg
      exec: talker
      node_name: talker
