meta:
  version: 1
  inputs:
  - path: /home/aeon/repos/nano-ros/examples/workspaces/ws-safety-c/src/demo_bringup/launch/safety_listener.launch.xml
    sha256: 6692a11391043faaa6bba3294d4967a31c9b1923ac9868b7ae13f8ddd0a313fb
  - path: /home/aeon/repos/nano-ros/examples/workspaces/ws-safety-c/src/demo_bringup/system.toml
    sha256: ac8aea78dfdcb094c7c5da5940ae014b68c032e72cb2c3d29f19db50bf887f8f
  resolver:
    tool: play_launch
    version: 0.8.2
structure:
  scopes:
    safety_listener.launch.xml:
      file: safety_listener.launch.xml
  nodes:
    /safe_listener:
      scope: safety_listener.launch.xml
      pkg: c_safety_listener_pkg
      exec: safe_listener
      node_name: safe_listener
execution:
  deploy:
    /safe_listener:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
  features:
  - safety
