# Cyclone DDS type-support codegen helpers (Phase 117.2 / 117.5).
#
# Two public functions:
#
#   nros_rmw_cyclonedds_idlc_compile(<output_var>
#       IDL_FILE     <path/to/foo.idl>
#       OUTPUT_DIR   <build/dir>
#       [TYPE_NAME   nros_test::msg::TestString]   # optional, for self-reg
#   )
#       Runs Cyclone DDS's `idlc` over a single IDL file and emits
#       `<base>.c` + `<base>.h` + (when TYPE_NAME is given)
#       `<base>_register.c` — a tiny static-init translation unit
#       that registers the generated `dds_topic_descriptor_t` with the
#       backend's runtime registry under TYPE_NAME. Sets <output_var>
#       to the list of generated source files.
#
#   nros_rmw_cyclonedds_add_idl_library(<target>
#       IDL_FILES    <a.idl> [<b.idl> ...]
#       [REGISTER_TYPES <name1=full::cpp::Type1> ...]
#   )
#       Convenience wrapper: produces a STATIC IMPORTED-style library
#       containing the descriptor table for every IDL_FILE, plus
#       optional auto-registration translation units.
#
# Notes:
#  - Cyclone 0.10.5's idlc currently fails when emitting XTypes
#    type-discovery metadata in some configurations. We pass `-t` to
#    skip that section; the produced descriptor still works for pub/
#    sub against `rmw_cyclonedds_cpp` peers (the metadata is optional
#    on the wire — peers fall back to typename matching).
#  - Generated .c / .h are written to `${CMAKE_CURRENT_BINARY_DIR}` so
#    consumers don't have to manage their own scratch dirs.

if(NOT TARGET CycloneDDS::ddsc)
    message(FATAL_ERROR
        "NrosRmwCycloneddsTypeSupport.cmake requires CycloneDDS::ddsc; "
        "include it after find_package(CycloneDDS).")
endif()

# Locate idlc — Cyclone exports it as `CycloneDDS::idlc` when it's
# installed alongside ddsc.
if(NOT TARGET CycloneDDS::idlc)
    find_program(IDLC_EXECUTABLE idlc
        HINTS
            "${CycloneDDS_DIR}/../../../bin"
            "${CMAKE_INSTALL_PREFIX}/bin"
            "$ENV{CYCLONEDDS_INSTALL_DIR}/bin"
        DOC "Cyclone DDS IDL compiler")
    if(NOT IDLC_EXECUTABLE)
        message(FATAL_ERROR
            "idlc not found. Set IDLC_EXECUTABLE or run `just cyclonedds setup`.")
    endif()
endif()

#
# nros_rmw_cyclonedds_idlc_compile
#
# An IDL file may contain multiple `@topic`-eligible structs. Pass
# one TYPE_NAME (single-type) or TYPE_NAMES (one per struct, all
# registered) — both forms emit one constructor per name.
#
function(nros_rmw_cyclonedds_idlc_compile output_var)
    set(_options "")
    set(_one    IDL_FILE OUTPUT_DIR TYPE_NAME)
    set(_multi  TYPE_NAMES)
    cmake_parse_arguments(_arg "${_options}" "${_one}" "${_multi}" ${ARGN})

    if(NOT _arg_IDL_FILE)
        message(FATAL_ERROR "nros_rmw_cyclonedds_idlc_compile: IDL_FILE required")
    endif()
    if(NOT _arg_OUTPUT_DIR)
        set(_arg_OUTPUT_DIR "${CMAKE_CURRENT_BINARY_DIR}/cyclonedds-types")
    endif()
    file(MAKE_DIRECTORY "${_arg_OUTPUT_DIR}")

    get_filename_component(_idl_abs "${_arg_IDL_FILE}" ABSOLUTE)
    get_filename_component(_idl_stem "${_arg_IDL_FILE}" NAME_WE)
    set(_gen_c "${_arg_OUTPUT_DIR}/${_idl_stem}.c")
    set(_gen_h "${_arg_OUTPUT_DIR}/${_idl_stem}.h")

    if(TARGET CycloneDDS::idlc)
        set(_idlc "$<TARGET_FILE:CycloneDDS::idlc>")
    else()
        set(_idlc "${IDLC_EXECUTABLE}")
    endif()

    add_custom_command(
        OUTPUT  "${_gen_c}" "${_gen_h}"
        COMMAND "${_idlc}" -t -l c -o "${_arg_OUTPUT_DIR}" "${_idl_abs}"
        DEPENDS "${_idl_abs}"
        COMMENT "idlc ${_idl_stem}.idl"
        VERBATIM
    )

    set(_out_files "${_gen_c}")

    # Normalise the single + multi forms into one list.
    set(_all_types "")
    if(_arg_TYPE_NAME)
        list(APPEND _all_types "${_arg_TYPE_NAME}")
    endif()
    if(_arg_TYPE_NAMES)
        list(APPEND _all_types ${_arg_TYPE_NAMES})
    endif()

    set(_idx 0)
    foreach(_tn IN LISTS _all_types)
        # Per-type self-registration TU. The descriptor symbol is
        # `<TYPE_NAME with :: → _>_desc`; matches Cyclone idlc's
        # mangling. `_<idx>` keeps each register TU's filename
        # unique when multiple types share the same IDL.
        string(REPLACE "::" "_" _desc_sym "${_tn}_desc")
        # Sanitise the constructor's symbol name — descriptor symbol
        # has only A-Za-z0-9_ already so it's safe to reuse.
        set(_ctor "register_${_idl_stem}_${_idx}")
        set(_reg "${_arg_OUTPUT_DIR}/${_idl_stem}_register_${_idx}.c")
        file(WRITE "${_reg}.in"
"/* Auto-generated by nros_rmw_cyclonedds_idlc_compile() — do not edit. */
#include \"dds/dds.h\"
#include \"${_idl_stem}.h\"

extern const dds_topic_descriptor_t ${_desc_sym};

void nros_rmw_cyclonedds_register_descriptor(
    const char *type_name, const dds_topic_descriptor_t *desc);

__attribute__((constructor))
static void ${_ctor}(void) {
    nros_rmw_cyclonedds_register_descriptor(
        \"${_tn}\", &${_desc_sym});
}
")
        configure_file("${_reg}.in" "${_reg}" COPYONLY)
        list(APPEND _out_files "${_reg}")
        math(EXPR _idx "${_idx} + 1")
    endforeach()

    set(${output_var} "${_out_files}" PARENT_SCOPE)
endfunction()

#
# nros_rmw_cyclonedds_add_idl_library
#
function(nros_rmw_cyclonedds_add_idl_library tgt)
    set(_options "")
    set(_one    "")
    set(_multi  IDL_FILES REGISTER_TYPES)
    cmake_parse_arguments(_arg "${_options}" "${_one}" "${_multi}" ${ARGN})

    if(NOT _arg_IDL_FILES)
        message(FATAL_ERROR
            "nros_rmw_cyclonedds_add_idl_library: IDL_FILES required")
    endif()

    set(_all_sources "")
    foreach(_idl IN LISTS _arg_IDL_FILES)
        get_filename_component(_idl_stem "${_idl}" NAME_WE)
        set(_type_for_this "")
        # REGISTER_TYPES is a list of "<idl_stem>=<full::cpp::Type>" pairs.
        foreach(_pair IN LISTS _arg_REGISTER_TYPES)
            string(REGEX MATCH "^([^=]+)=(.*)$" _m "${_pair}")
            if(_m)
                set(_lhs "${CMAKE_MATCH_1}")
                set(_rhs "${CMAKE_MATCH_2}")
                if(_lhs STREQUAL "${_idl_stem}")
                    set(_type_for_this "${_rhs}")
                endif()
            endif()
        endforeach()
        if(_type_for_this)
            nros_rmw_cyclonedds_idlc_compile(_gen
                IDL_FILE  "${_idl}"
                OUTPUT_DIR "${CMAKE_CURRENT_BINARY_DIR}/${tgt}-idl"
                TYPE_NAME "${_type_for_this}"
            )
        else()
            nros_rmw_cyclonedds_idlc_compile(_gen
                IDL_FILE  "${_idl}"
                OUTPUT_DIR "${CMAKE_CURRENT_BINARY_DIR}/${tgt}-idl"
            )
        endif()
        list(APPEND _all_sources ${_gen})
    endforeach()

    add_library(${tgt} STATIC ${_all_sources})
    target_include_directories(${tgt}
        PUBLIC "${CMAKE_CURRENT_BINARY_DIR}/${tgt}-idl")
    target_link_libraries(${tgt} PUBLIC CycloneDDS::ddsc)
    set_target_properties(${tgt} PROPERTIES POSITION_INDEPENDENT_CODE ON)
endfunction()
