/* GENERATED by `nros ws entity-inventory` (phase-403 step 2). Do not edit.
 *
 * The QoS history DEPTH each subscription was DECLARED with, in
 * `nano_ros_node_register(... ENTITIES sub:<type>:<topic>@depth=N ...)`.
 * `nros/declared_qos.hpp` expands this into a `constexpr` table and
 * `NROS_SUBSCRIBE` static_asserts the QoS it is handed against it, so a
 * declaration and an implementation that disagree fail the BUILD naming
 * the topic and both numbers.
 *
 * An ABSENT row is not depth 0 and not depth 10: it is "nobody declared
 * this endpoint", and nothing asserts against it.
 *
 * Source: packages/api/nros-cpp/tests/compile/declared-qos-fixture/entities.json [demo::listener]
 */
#ifndef NROS_DECLARED_QOS_GENERATED_H
#define NROS_DECLARED_QOS_GENERATED_H

#define NROS_DECLARED_QOS_STATUS "resolved"
/* 1 of this image's depth-carrying endpoints declared no depth. */
#define NROS_DECLARED_QOS_UNDECLARED_COUNT 1

/* X-macro. `nros/declared_qos.hpp` defines NROS_DECLARED_QOS_ROW
 * and expands this; nothing else may. */
#define NROS_DECLARED_QOS_ROWS \
    NROS_DECLARED_QOS_ROW("std_msgs::msg::dds_::Int32_", "/chatter", 1) \
    NROS_DECLARED_QOS_ROW("std_msgs/msg/Int32", "/chatter", 1) \
    /* end */
#define NROS_DECLARED_QOS_ROW_COUNT 2

#endif /* NROS_DECLARED_QOS_GENERATED_H */
