// emit:ok
// nros-c message type - C implementation
// Package: fingerprint-corpus
// Message: Bounded
// Auto-generated by rosidl-codegen - do not edit

#include "fingerprint_corpus_msg_bounded.h"
#include <nros/types.h>
#include <nros/cdr.h>
#include <nros/platform.h>
#include <string.h>

// Type support structure
static const nros_message_type_t fingerprint_corpus_msg_bounded_type_support = {
    .type_name = "fingerprint-corpus::msg::dds_::Bounded_",
    .type_hash = "h",
    .serialized_size_max = 0,  // Dynamic/unknown
};

const nros_message_type_t* fingerprint_corpus_msg_bounded_get_type_support(void) {
    return &fingerprint_corpus_msg_bounded_type_support;
}

void fingerprint_corpus_msg_bounded_init(fingerprint_corpus_msg_bounded* msg) {
    if (msg == NULL) return;
    memset(msg, 0, sizeof(fingerprint_corpus_msg_bounded));
}

// Release heap-backed (`mode = "heap"`, RFC-0033) fields. Safe on a zero-inited
// or already-fini'd message (frees NULL, re-zeroes). No-op when the message has
// no heap fields.
void fingerprint_corpus_msg_bounded_fini(fingerprint_corpus_msg_bounded* msg) {
    if (msg == NULL) return;
}

// =============================================================================
// Inline serialize — writes fields only into an already-open CDR stream.
// Used by parent messages, services, and actions that embed this type as a
// nested field. Does NOT write an encapsulation header. `origin` is the
// CDR alignment origin of the surrounding encapsulation.
// =============================================================================
int32_t fingerprint_corpus_msg_bounded_serialize_inline(const fingerprint_corpus_msg_bounded* msg, uint8_t** ptr_ref, const uint8_t* end, const uint8_t* origin) {
    if (msg == NULL || ptr_ref == NULL || *ptr_ref == NULL) return -1;
    uint8_t* ptr = *ptr_ref;
    (void)origin; // may be unused for empty structs
    // phase-303 W4 (#0267) — XCDR2 DHEADER wrap (no-op / returns -1 under XCDR1).
    int64_t __dh = nros_cdr_begin_dheader(&ptr, end, origin);
    if (__dh < -1) return -1;
    if (nros_cdr_write_bool(&ptr, end, origin, msg->flag) < 0) return -1;
    if (nros_cdr_write_i64(&ptr, end, origin, msg->wide) < 0) return -1;
    if (nros_cdr_write_u8(&ptr, end, origin, msg->narrow) < 0) return -1;
    if (nros_cdr_write_f64(&ptr, end, origin, msg->d) < 0) return -1;
    if (nros_cdr_write_string(&ptr, end, origin, msg->label) < 0) return -1;
    for (size_t i = 0; i < 4; ++i) {
        if (nros_cdr_write_i32(&ptr, end, origin, msg->fixed[i]) < 0) return -1;
    }
    if (nros_cdr_end_dheader(__dh, &ptr, end, origin) < 0) return -1;
    *ptr_ref = ptr;
    return 0;
}

// =============================================================================
// Public serialize — writes a fresh 4-byte CDR encapsulation header then
// delegates to the inline serializer.
// =============================================================================
int32_t fingerprint_corpus_msg_bounded_serialize(const fingerprint_corpus_msg_bounded* msg, uint8_t* buffer, size_t buffer_size, size_t* serialized_size) {
    if (msg == NULL || buffer == NULL) return -1;

    uint8_t* ptr = buffer;
    const uint8_t* end = buffer + buffer_size;

    // Write the edition-appropriate CDR encapsulation header (XCDR1 `00 01` or
    // XCDR2 DELIMITED `00 09`) — phase-303 W4 (#0267).
    if (nros_cdr_write_encaps_header(&ptr, end) < 0) return -1;
    const uint8_t* origin = ptr; // CDR alignment origin (after header)

    if (fingerprint_corpus_msg_bounded_serialize_inline(msg, &ptr, end, origin) < 0) return -1;

    if (serialized_size != NULL) {
        *serialized_size = (size_t)(ptr - buffer);
    }
    return 0;
}

// =============================================================================
// Inline deserialize — reads fields only from an already-open CDR stream.
// =============================================================================
int32_t fingerprint_corpus_msg_bounded_deserialize_inline(fingerprint_corpus_msg_bounded* msg, const uint8_t** ptr_ref, const uint8_t* end, const uint8_t* origin) {
    if (msg == NULL || ptr_ref == NULL || *ptr_ref == NULL) return -1;
    const uint8_t* ptr = *ptr_ref;
    // phase-303 W4 (#0267) — XCDR2 DHEADER read (no-op / -1 under XCDR1).
    int64_t __dh = nros_cdr_begin_dheader_read(&ptr, end, origin);
    if (__dh < -1) return -1;
    (void)origin;
    if (nros_cdr_read_bool(&ptr, end, origin, &msg->flag) < 0) return -1;
    if (nros_cdr_read_i64(&ptr, end, origin, &msg->wide) < 0) return -1;
    if (nros_cdr_read_u8(&ptr, end, origin, &msg->narrow) < 0) return -1;
    if (nros_cdr_read_f64(&ptr, end, origin, &msg->d) < 0) return -1;
    if (nros_cdr_read_string(&ptr, end, origin, msg->label, sizeof(msg->label)) < 0) return -1;
    for (size_t i = 0; i < 4; ++i) {
        if (nros_cdr_read_i32(&ptr, end, origin, &msg->fixed[i]) < 0) return -1;
    }
    if (nros_cdr_end_dheader_read(__dh, &ptr, end, origin) < 0) return -1;
    *ptr_ref = ptr;
    return 0;
}

// =============================================================================
// Public deserialize — skips the 4-byte CDR encapsulation header then
// delegates to the inline deserializer.
// =============================================================================
int32_t fingerprint_corpus_msg_bounded_deserialize(fingerprint_corpus_msg_bounded* msg, const uint8_t* buffer, size_t buffer_size) {
    if (msg == NULL || buffer == NULL) return -1;

    const uint8_t* ptr = buffer;
    const uint8_t* end = buffer + buffer_size;

    // Skip CDR header
    if (ptr + 4 > end) return -1;
    ptr += 4;
    const uint8_t* origin = ptr; // CDR alignment origin (after header)

    fingerprint_corpus_msg_bounded_init(msg);

    if (fingerprint_corpus_msg_bounded_deserialize_inline(msg, &ptr, end, origin) < 0) return -1;
    return 0;
}