# phase-206 W2 — bake a bringup's own RMW config into the image.
#
# THE EXPERIENCE THIS EXISTS FOR. On ROS 2 the OS owns the devices and the user
# configures the middleware in the middleware's own language: an XML file named
# by `CYCLONEDDS_URI`, naming an IP or a device. Application code knows nothing
# about NICs. nano-ros should be the same — but on an RTOS there is no
# environment to set and no filesystem to point at, so `env_lookup` returns
# `nullptr` on a freestanding target and that rung is structurally dead.
#
# So the FILE is baked. The user writes the same document they would write for
# ROS 2; the build turns its bytes into a string literal; the backend hands
# those bytes to its OWN parser. nano-ros parses nothing.
#
# WHERE THE FILE LIVES, and why not `config/`:
#
#     <bringup>/rmw/cyclonedds.xml     authored, tracked, reviewed
#     <bringup>/rmw/zenoh.conf         (phase-206 W3)
#     <bringup>/config/*.yaml          GENERATED, gitignored (phase-330 W4.a)
#
# `<bringup>/config/` already means "build artifact, never committed" — putting
# an authored file there would put the one thing a user must edit inside the one
# directory the tree says is disposable. `rmw/` sits beside `launch/`, which is
# the existing precedent for authored, typed, per-bringup input.
#
# CONVENTION, NOT DECLARATION. There is no `system.toml` key naming the file:
# the active backend is already declared (`[system] rmw = "..."`), so the build
# knows which name to look for, and a second declaration is a second thing to
# keep in sync. RFC-0087's "derived from convention" applied one axis over.

# Bake `<bringup>/rmw/<backend>.<ext>` into `<out_dir>/nros_<backend>_user_config.h`.
#
# Writes nothing when the bringup ships no config — the consuming header guards
# on `__has_include`, so an image with no config compiles with no cmake
# participation at all.
function(nros_bake_rmw_user_config)
    cmake_parse_arguments(_NBR "" "BRINGUP;BACKEND;OUT_DIR;RESULT" "" ${ARGN})
    if(NOT _NBR_BRINGUP OR NOT _NBR_BACKEND OR NOT _NBR_OUT_DIR)
        message(FATAL_ERROR
            "nros_bake_rmw_user_config: BRINGUP, BACKEND and OUT_DIR are required")
    endif()

    # One extension per backend, because the backends' native config languages
    # genuinely differ (RFC-0004 amendment): CycloneDDS has an XML *document*
    # and parses it itself; zenoh-pico has no document format at all, so its
    # unit is a flat `key = value` list fed to `zp_config_insert`.
    if(_NBR_BACKEND STREQUAL "cyclonedds")
        set(_ext "xml")
    elseif(_NBR_BACKEND STREQUAL "zenoh")
        set(_ext "conf")
    else()
        # Not an error: a backend with no user-config surface simply has none.
        if(_NBR_RESULT)
            set(${_NBR_RESULT} "" PARENT_SCOPE)
        endif()
        return()
    endif()

    set(_src "${_NBR_BRINGUP}/rmw/${_NBR_BACKEND}.${_ext}")
    if(NOT EXISTS "${_src}")
        if(_NBR_RESULT)
            set(${_NBR_RESULT} "" PARENT_SCOPE)
        endif()
        return()
    endif()

    file(READ "${_src}" _body)

    # The raw-string delimiter must not appear in the document, or the literal
    # ends early and the file after it becomes code. Refuse rather than mangle:
    # a config that silently half-applied is this phase's whole complaint.
    if(_body MATCHES "\\)NROSXML\"")
        message(FATAL_ERROR
            "nros_bake_rmw_user_config: ${_src} contains the raw-string "
            "terminator )NROSXML\" and cannot be baked verbatim. Rename the "
            "delimiter in cmake/NanoRosRmwUserConfig.cmake, or remove that "
            "byte sequence from the file.")
    endif()

    # CONFIGURE_DEPENDS is not available for `file(READ)`, so the dependency is
    # stated explicitly — otherwise editing the config would not re-configure,
    # and the image would keep the previous bytes. That is the museum-binary
    # class (issue 0196) applied to a config file.
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_src}")

    set(_out "${_NBR_OUT_DIR}/nros_${_NBR_BACKEND}_user_config.h")
    file(MAKE_DIRECTORY "${_NBR_OUT_DIR}")
    string(TOUPPER "${_NBR_BACKEND}" _BACKEND_UC)
    # A VARIABLE, not a `#define`. A raw string literal cannot span physical
    # lines inside a macro definition: the preprocessor ends the directive at
    # the first unescaped newline, leaving the literal unterminated. The first
    # version of this generator emitted a macro and every multi-line config
    # failed to compile with "unterminated raw string" pointing at the generated
    # file — caught by the W2 test, which is what it is for.
    #
    # The PRESENT marker is a macro because that is the part `#ifdef` must see;
    # only the payload has to be a variable.
    file(WRITE "${_out}"
"/* GENERATED by nros_bake_rmw_user_config() — DO NOT EDIT.
 *
 * SSoT: ${_src}
 *
 * The bytes below are the user's own ${_NBR_BACKEND} configuration, verbatim.
 * nano-ros does not parse, validate or re-spell them; they are handed to the
 * backend's own parser. Edit the SSoT above, not this file. */
#ifndef NROS_${_BACKEND_UC}_USER_CONFIG_H
#define NROS_${_BACKEND_UC}_USER_CONFIG_H
#define NROS_${_BACKEND_UC}_USER_CONFIG_PRESENT 1

namespace nros_rmw_user_config {
inline constexpr const char* k${_BACKEND_UC}_config = R\"NROSXML(${_body})NROSXML\";
}  // namespace nros_rmw_user_config

#endif
")
    message(STATUS "nano-ros: baked ${_src} -> ${_out}")
    if(_NBR_RESULT)
        set(${_NBR_RESULT} "${_out}" PARENT_SCOPE)
    endif()
endfunction()
