# nano_ros_workspace_metadata.cmake — Phase 212.D
#
# Shells `nros plan` at CMake CONFIGURE time, emits
# ${CMAKE_BINARY_DIR}/nros_components.cmake, then include()s it so
# component targets are visible natively. Exposes both C++ and Rust
# component targets uniformly (Corrosion bridges Rust components when
# present). Hard cap: ≤150 LoC (see tokei gate in Phase 212 acceptance).
#
# Usage:
#   nano_ros_workspace_metadata(SYSTEM <bringup-pkg> [WORKSPACE_ROOT <dir>])

# Shared helpers (nros_resolve_cli — issue #219). include_guard'd.
include("${CMAKE_CURRENT_LIST_DIR}/NanoRosCodegenCore.cmake")

function(nano_ros_workspace_metadata)
    cmake_parse_arguments(_NRW "" "SYSTEM;WORKSPACE_ROOT" "" ${ARGN})
    if(NOT _NRW_SYSTEM)
        message(FATAL_ERROR "nano_ros_workspace_metadata: SYSTEM <bringup-pkg> required")
    endif()
    if(NOT _NRW_WORKSPACE_ROOT)
        set(_NRW_WORKSPACE_ROOT "${CMAKE_SOURCE_DIR}")
    endif()

    # Locate the nros binary: NROS_BIN cache override, else the shared
    # resolver (issue #219 — this used to be a bespoke find_program whose
    # HINTS searched a stale ~/.nros/bin BEFORE the activate.sh-wired PATH).
    if(NOT NROS_BIN)
        nros_resolve_cli(NROS_BIN CONTEXT "nano_ros_workspace_metadata")
    endif()

    # Locate the bringup pkg dir: prefer colcon-style `src/<system>/`
    # (today's `nros plan` walks `src/<pkg>/` for component_nros.toml),
    # fall back to `<workspace>/<system>/` (212.D-canonical flat layout
    # once the planner picks up the new shape).
    if(EXISTS "${_NRW_WORKSPACE_ROOT}/src/${_NRW_SYSTEM}/system.toml" OR
       EXISTS "${_NRW_WORKSPACE_ROOT}/src/${_NRW_SYSTEM}/package.xml")
        set(_bringup_dir "${_NRW_WORKSPACE_ROOT}/src/${_NRW_SYSTEM}")
    else()
        set(_bringup_dir "${_NRW_WORKSPACE_ROOT}/${_NRW_SYSTEM}")
    endif()
    set(_system_toml "${_bringup_dir}/system.toml")
    set(_launch_xml  "${_bringup_dir}/launch/system.launch.xml")
    file(RELATIVE_PATH _launch_rel "${_NRW_WORKSPACE_ROOT}" "${_launch_xml}")
    set(_plan_dir    "${CMAKE_BINARY_DIR}/nros-plan")
    set(_plan_json   "${_plan_dir}/nros-plan.json")
    set(_components_cmake "${CMAKE_BINARY_DIR}/nros_components.cmake")

    file(MAKE_DIRECTORY "${_plan_dir}")

    # Re-run configure when the declarative inputs change.
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
        "${_system_toml}" "${_launch_xml}")

    # Shell `nros plan` at configure time. TODO(212.D): when `nros plan
    # --emit-cmake` lands upstream, prefer that single-call path; for now
    # we parse nros-plan.json below.
    execute_process(
        COMMAND "${NROS_BIN}" plan
            --workspace "${_NRW_WORKSPACE_ROOT}"
            --out-dir "${_plan_dir}"
            "${_NRW_SYSTEM}" "${_launch_rel}"
        WORKING_DIRECTORY "${_NRW_WORKSPACE_ROOT}"
        RESULT_VARIABLE _plan_rc
        OUTPUT_VARIABLE _plan_out
        ERROR_VARIABLE  _plan_err
    )
    if(NOT _plan_rc EQUAL 0)
        message(FATAL_ERROR
            "nano_ros_workspace_metadata: `nros plan` failed (rc=${_plan_rc})\n"
            "stdout: ${_plan_out}\nstderr: ${_plan_err}")
    endif()

    # Fallback emit: walk nros-plan.json components and emit per-component
    # marker targets. Empty bringup pkg (zero components) emits a warning
    # but does NOT error (per Phase 212.D edge-case rule).
    set(_emit "# Generated by nano_ros_workspace_metadata() — DO NOT EDIT\n")
    string(APPEND _emit "# Source: ${_plan_json}\n\n")
    set(_have_rust 0)
    set(_n_components 0)

    if(EXISTS "${_plan_json}")
        file(READ "${_plan_json}" _plan_raw)
        string(JSON _comps_len ERROR_VARIABLE _je LENGTH "${_plan_raw}" components)
        if(_je)
            set(_comps_len 0)
        endif()
        if(_comps_len GREATER 0)
            math(EXPR _last "${_comps_len} - 1")
            foreach(i RANGE 0 ${_last})
                string(JSON _pkg  GET "${_plan_raw}" components ${i} package)
                string(JSON _comp GET "${_plan_raw}" components ${i} component)
                string(JSON _lang GET "${_plan_raw}" components ${i} language)
                set(_tgt "nros_component_${_pkg}_${_comp}")
                string(APPEND _emit
                    "# component[${i}]: pkg=${_pkg} component=${_comp} language=${_lang}\n"
                    "if(NOT TARGET ${_tgt})\n"
                    "    add_custom_target(${_tgt})\n"
                    "    set_target_properties(${_tgt} PROPERTIES\n"
                    "        NROS_PACKAGE \"${_pkg}\"\n"
                    "        NROS_COMPONENT \"${_comp}\"\n"
                    "        NROS_LANGUAGE \"${_lang}\")\n"
                    "endif()\n")
                if(_lang STREQUAL "rust")
                    set(_have_rust 1)
                endif()
                math(EXPR _n_components "${_n_components} + 1")
            endforeach()
        endif()
    endif()

    if(_n_components EQUAL 0)
        message(WARNING
            "nano_ros_workspace_metadata(${_NRW_SYSTEM}): plan has zero components")
        string(APPEND _emit "# (no components in plan — empty bringup)\n")
    endif()

    if(_have_rust)
        find_package(Corrosion QUIET)
        if(NOT Corrosion_FOUND AND NOT COMMAND corrosion_import_crate)
            message(STATUS
                "nano_ros_workspace_metadata: plan contains Rust component(s); "
                "Corrosion not found — user must FetchContent/find_package "
                "Corrosion before corrosion_import_crate() will resolve.")
        endif()
    endif()

    file(WRITE "${_components_cmake}" "${_emit}")
    include("${_components_cmake}")
    set(NROS_PLAN_JSON "${_plan_json}" PARENT_SCOPE)
    set(NROS_COMPONENTS_CMAKE "${_components_cmake}" PARENT_SCOPE)
endfunction()
