# NanoRosLink.cmake
#
# User-facing helpers for linking nano-ros onto application targets.
#
# Phase 140 deleted the install-layout `find_package(NanoRos)` consumer
# path; the root `CMakeLists.txt` (pulled via `add_subdirectory(<repo>)`)
# is the only supported entry. That root already builds + links
# `NanoRos::NanoRos` against the platform shim + RMW staticlib chosen
# by `NANO_ROS_PLATFORM` / `NANO_ROS_RMW`. These helpers exist purely
# to:
#   * record per-target platform / RMW choice as CMake properties
#     (useful for downstream introspection),
#   * emit the `nros_app_register_backends()` strong-stub TU that
#     overrides the weak no-op in `libnros_c_weak_stubs.a` (Phase
#     104.B.6) — bare-metal builds without `.init_array` rely on this
#     stub being the only `nros_rmw_<x>_register` call site.
#
# Functions
# ^^^^^^^^^
#
# ``nano_ros_link_platform(<target> [PLATFORM <plat>])``
#   Annotates the target with its chosen platform. Linkage to
#   ``NanoRos::NanoRos`` is the caller's responsibility (already on
#   the target via the standard add_subdirectory + target_link_libraries
#   recipe).
#
# ``nano_ros_link_rmw(<target> [RMW <rmw>])``
#   Annotates + emits the register stub described above. RMW resolves
#   as: explicit ``RMW`` arg → ``NANO_ROS_DEFAULT_RMW`` cache var →
#   ``NANO_ROS_RMW``. Multiple invocations accumulate (e.g. a bridge
#   node registering zenoh + xrce).

function(_nano_ros_resolve_choice OUT_VAR KIND REQUESTED FALLBACK_LIST)
    if(REQUESTED)
        set(${OUT_VAR} "${REQUESTED}" PARENT_SCOPE)
        return()
    endif()
    foreach(_var IN LISTS FALLBACK_LIST)
        if(DEFINED ${_var} AND NOT "${${_var}}" STREQUAL "")
            set(${OUT_VAR} "${${_var}}" PARENT_SCOPE)
            return()
        endif()
    endforeach()
    message(FATAL_ERROR
        "nano_ros_link_${KIND}: no ${KIND} resolved. "
        "Pass ${KIND} <name> explicitly, or set "
        "${FALLBACK_LIST} before calling.")
endfunction()

function(nano_ros_link_platform TARGET)
    cmake_parse_arguments(ARG "" "PLATFORM" "" ${ARGN})
    if(ARG_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR
            "nano_ros_link_platform: unexpected argument(s): "
            "${ARG_UNPARSED_ARGUMENTS}")
    endif()
    _nano_ros_resolve_choice(_chosen "platform" "${ARG_PLATFORM}"
        "NANO_ROS_DEFAULT_PLATFORM;NANO_ROS_PLATFORM")
    set_property(TARGET ${TARGET} PROPERTY NANO_ROS_PLATFORM "${_chosen}")
endfunction()

function(nano_ros_link_rmw TARGET)
    cmake_parse_arguments(ARG "" "RMW" "" ${ARGN})
    if(ARG_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR
            "nano_ros_link_rmw: unexpected argument(s): "
            "${ARG_UNPARSED_ARGUMENTS}")
    endif()
    _nano_ros_resolve_choice(_chosen "rmw" "${ARG_RMW}"
        "NANO_ROS_DEFAULT_RMW;NANO_ROS_RMW")
    set_property(TARGET ${TARGET} PROPERTY NANO_ROS_RMW "${_chosen}")

    # Phase 104.B.6 — accumulate the chosen RMW into the target's
    # `_NANO_ROS_LINKED_RMWS` list and (re)generate the strong-stub
    # `nros_app_register_backends()` TU. Idempotent across repeat calls.
    set(_stub_dir "${CMAKE_CURRENT_BINARY_DIR}/_nano_ros_link/${TARGET}")
    set(_stub_path "${_stub_dir}/nros_app_register_backends.c")
    get_target_property(_existing_rmws ${TARGET} _NANO_ROS_LINKED_RMWS)
    if(NOT _existing_rmws)
        set(_existing_rmws "")
    endif()
    list(APPEND _existing_rmws "${_chosen}")
    list(REMOVE_DUPLICATES _existing_rmws)
    set_property(TARGET ${TARGET} PROPERTY
        _NANO_ROS_LINKED_RMWS "${_existing_rmws}")

    file(MAKE_DIRECTORY "${_stub_dir}")
    set(_stub_content "/* Auto-generated by nano_ros_link_rmw().\n")
    string(APPEND _stub_content
        " * Strong def of nros_app_register_backends() overrides the\n")
    string(APPEND _stub_content
        " * weak no-op in libnros_c_weak_stubs.a (Phase 104.B.6).\n")
    string(REPLACE ";" ", " _rmw_list_pretty "${_existing_rmws}")
    string(APPEND _stub_content " * Backends registered: ${_rmw_list_pretty}\n")
    string(APPEND _stub_content " */\n")
    foreach(_rmw_name IN LISTS _existing_rmws)
        string(APPEND _stub_content
            "extern int nros_rmw_${_rmw_name}_register(void);\n")
    endforeach()
    string(APPEND _stub_content "void nros_app_register_backends(void) {\n")
    foreach(_rmw_name IN LISTS _existing_rmws)
        string(APPEND _stub_content
            "    (void)nros_rmw_${_rmw_name}_register();\n")
    endforeach()
    string(APPEND _stub_content "}\n")
    file(WRITE "${_stub_path}" "${_stub_content}")
    target_sources(${TARGET} PRIVATE "${_stub_path}")

    # Phase 177.27 — the cyclonedds backend is C++ (operator new/delete,
    # std::nothrow in publisher/subscriber/sertype_min). When a C executable
    # links it, CMake's link-language propagation from the C++ static lib can
    # be lost — the backend is pulled in transitively (and whole-archived for
    # the register TU) rather than by target name — so the C linker driver is
    # selected and fails on unresolved C++ runtime symbols. Force the C++
    # linker driver so libstdc++ is linked. Idempotent / harmless for C++ apps
    # (already CXX) and for hosts where propagation already works.
    if("cyclonedds" IN_LIST _existing_rmws)
        set_target_properties(${TARGET} PROPERTIES LINKER_LANGUAGE CXX)
    endif()
endfunction()
