# cmake/NanoRosThreadxSystemCodegen.cmake — Phase 212.H.4
#
# ThreadX-flavored extension on top of `nano_ros_workspace_metadata()`.
# What this module adds:
#
#   * `nros_threadx_codegen_system(SYSTEM <bringup> [WORKSPACE_ROOT <dir>])`
#       - Runs `nano_ros_workspace_metadata()` (which shells `nros plan`
#         and emits `${CMAKE_BINARY_DIR}/nros_components.cmake` with one
#         marker target per component).
#       - Emits `${CMAKE_BINARY_DIR}/nros-system/system_main.c` — a
#         placeholder ThreadX entry that invokes one
#         `nros_component_<comp>_entry()` per planned component. This is
#         the in-tree stand-in for the future `nros codegen system`
#         subcommand (DO NOT add to nros-cli — Phase 212.H.4 task scope
#         freezes nros-cli).
#       - Emits `${CMAKE_BINARY_DIR}/nros-system/Cargo.toml` — a
#         workspace stub listing every Rust component crate, so a future
#         `cargo build --manifest-path build/nros-system/Cargo.toml` can
#         replace the per-crate import loop below.
#       - For each Rust component, calls `corrosion_import_crate` against
#         `<workspace>/src/<pkg>/Cargo.toml` so the staticlib resolves
#         as `<pkg-name>-static` (default Corrosion naming).
#       - Compiles `system_main.c` into `nros_system_main` STATIC.
#
#   * `nros_threadx_link_app(<target>)`
#       - Links `nros_system_main` + every imported Rust component
#         staticlib onto <target>, then delegates to the host platform's
#         `nros_platform_link_app(<target>)` for kernel/netstack/startup
#         fixups. Safe to call without a prior `nros_platform_*` include
#         — `nros_platform_link_app` is then a no-op.

if(DEFINED _NROS_THREADX_SYSTEM_CODEGEN_INCLUDED)
    return()
endif()
set(_NROS_THREADX_SYSTEM_CODEGEN_INCLUDED TRUE)

include("${CMAKE_CURRENT_LIST_DIR}/nano_ros_workspace_metadata.cmake")

set(_NROS_THREADX_COMPONENT_LIBS "" CACHE INTERNAL "" FORCE)

function(nros_threadx_codegen_system)
    cmake_parse_arguments(_NTX "" "SYSTEM;WORKSPACE_ROOT" "" ${ARGN})
    if(NOT _NTX_SYSTEM)
        message(FATAL_ERROR "nros_threadx_codegen_system: SYSTEM <bringup> required")
    endif()
    if(NOT _NTX_WORKSPACE_ROOT)
        set(_NTX_WORKSPACE_ROOT "${CMAKE_SOURCE_DIR}")
    endif()
    nano_ros_workspace_metadata(SYSTEM "${_NTX_SYSTEM}"
        WORKSPACE_ROOT "${_NTX_WORKSPACE_ROOT}")

    set(_sys_dir "${CMAKE_BINARY_DIR}/nros-system")
    file(MAKE_DIRECTORY "${_sys_dir}")
    set(_sys_main_c "${_sys_dir}/system_main.c")
    set(_sys_cargo  "${_sys_dir}/Cargo.toml")

    # Re-walk the plan JSON the workspace_metadata fn already parsed and
    # emit the ThreadX-flavored artifacts.
    if(NOT EXISTS "${NROS_PLAN_JSON}")
        message(FATAL_ERROR "nros_threadx_codegen_system: missing ${NROS_PLAN_JSON}")
    endif()
    file(READ "${NROS_PLAN_JSON}" _plan)
    string(JSON _n_comps ERROR_VARIABLE _je LENGTH "${_plan}" components)
    if(_je OR NOT _n_comps)
        set(_n_comps 0)
    endif()

    set(_main_body
        "/* Generated by nros_threadx_codegen_system — DO NOT EDIT */\n"
        "#include <stdio.h>\n\n")
    set(_extern_block "")
    set(_weak_block "")
    set(_call_block "")
    set(_cargo_members "")
    set(_rust_libs "")

    if(_n_comps GREATER 0)
        math(EXPR _last "${_n_comps} - 1")
        foreach(i RANGE 0 ${_last})
            string(JSON _pkg  GET "${_plan}" components ${i} package)
            string(JSON _comp GET "${_plan}" components ${i} component)
            string(JSON _lang GET "${_plan}" components ${i} language)
            string(APPEND _extern_block
                "extern void nros_component_${_comp}_entry(void);\n")
            # Weak default: when Corrosion isn't on the host the Rust
            # component staticlib isn't linked; the weak stub keeps the
            # binary linkable + prints a deterministic marker so the
            # integration test can still grep for component identity.
            string(APPEND _weak_block
                "__attribute__((weak)) void nros_component_${_comp}_entry(void) {\n"
                "    puts(\"[${_comp}] stub component entry (no rust impl linked)\");\n"
                "}\n")
            string(APPEND _call_block
                "    nros_component_${_comp}_entry();\n")
            if(_lang STREQUAL "rust")
                set(_pkg_dir "${_NTX_WORKSPACE_ROOT}/src/${_pkg}")
                if(EXISTS "${_pkg_dir}/Cargo.toml")
                    string(APPEND _cargo_members "  \"src/${_pkg}\",\n")
                    if(COMMAND corrosion_import_crate)
                        # Corrosion names staticlib targets <crate>-static.
                        # The fixture crates are `talker_component` /
                        # `listener_component`; the cmake target ends up
                        # as `${cratename}-static`. The import is
                        # idempotent across multiple add_subdirectory()
                        # consumers.
                        corrosion_import_crate(
                            MANIFEST_PATH "${_pkg_dir}/Cargo.toml")
                        list(APPEND _rust_libs "${_pkg}")
                    else()
                        message(STATUS
                            "nros_threadx_codegen_system: Corrosion not available; "
                            "skipping corrosion_import_crate for ${_pkg}.")
                    endif()
                endif()
            endif()
        endforeach()
    endif()

    set(_cargo_content
        "# Generated by nros_threadx_codegen_system — DO NOT EDIT.\n"
        "[workspace]\nresolver = \"2\"\nmembers = [\n${_cargo_members}]\n")
    file(WRITE "${_sys_cargo}" ${_cargo_content})

    file(WRITE "${_sys_main_c}"
        ${_main_body}
        "${_extern_block}\n"
        "${_weak_block}\n"
        "int nros_system_main(void) {\n"
        "    puts(\"[nros-system] spawning components\");\n"
        "${_call_block}"
        "    return 0;\n"
        "}\n")

    if(NOT TARGET nros_system_main)
        add_library(nros_system_main STATIC "${_sys_main_c}")
        target_include_directories(nros_system_main PUBLIC "${_sys_dir}")
    endif()

    set(_NROS_THREADX_COMPONENT_LIBS "${_rust_libs}" CACHE INTERNAL "" FORCE)
    set(NROS_SYSTEM_DIR "${_sys_dir}" PARENT_SCOPE)
endfunction()

function(nros_threadx_link_app target)
    if(NOT TARGET ${target})
        message(FATAL_ERROR "nros_threadx_link_app: '${target}' is not a target.")
    endif()
    if(TARGET nros_system_main)
        target_link_libraries(${target} PRIVATE nros_system_main)
    endif()
    foreach(_pkg ${_NROS_THREADX_COMPONENT_LIBS})
        # Corrosion's staticlib target naming: `<crate>-static`. The
        # fixture crates name the staticlib after the pkg's lib name
        # (`talker_component` / `listener_component`); resolve to that.
        # We accept either `<crate>` or `<crate>-static` to stay forward
        # compatible with Corrosion's surface bumps.
        set(_crate_static "${_pkg}_component-static")
        set(_crate_plain  "${_pkg}_component")
        if(TARGET ${_crate_static})
            target_link_libraries(${target} PRIVATE ${_crate_static})
        elseif(TARGET ${_crate_plain})
            target_link_libraries(${target} PRIVATE ${_crate_plain})
        endif()
    endforeach()
    if(COMMAND nros_platform_link_app)
        nros_platform_link_app(${target})
    endif()
endfunction()
