#!/usr/bin/env python3
"""phase-475 W1 — classify a lane census's junit per TARGET.

A target's outcome is the worst of its cases: FAIL > FIXTURE > TIMEOUT > SKIP >
PASS. What each one tells a lane:

* PASS    — reached a verdict here with nothing staged. ADMISSIBLE.
* FAIL    — reached a verdict that is red, OR reported an unmet precondition as
            a failure instead of a skip. The census cannot tell those apart and
            does not pretend to: read the message. Both are findings — a real
            red nobody sees, or a skip-discipline defect.
* FIXTURE — needs a staged fixture. Admissible only where the job builds it.
* SKIP    — a precondition this environment lacks; the class and message say
            which. Counted per missing thing, so the image owner can see what
            one more package would buy.
* TIMEOUT — hung instead of skipping. Always a defect.

Skip recognition is `nros_tests::skip_marker`'s rule — a `[SKIPPED` PREFIX,
classed or not — never the bare `[SKIPPED]`, which is the five-site bug issue
0658 fixed."""
import argparse, re, sys, json, collections
import xml.etree.ElementTree as ET

SKIP = re.compile(r"\[SKIPPED(?::(\w+))?\]\s*(.*)")
FIXTURE = re.compile(r"not prebuilt|BuildFailed|fixture binary|NROS_FIXTURE|fixtures-built|build-test-fixtures", re.I)
RANK = {"PASS": 0, "SKIP": 1, "TIMEOUT": 2, "FIXTURE": 3, "FAIL": 4}
CRATE = "nros-tests"

# Module-level so `check-baseline-shape` can hold the admission file to it.
ADMIT_HEADER = (
    "# phase-475 W3 — the nros-tests targets the gate lane RUNS, GENERATED by the\n"
    "# lane census in the gate image: every target that reached a PASS in EVERY\n"
    "# census run, with nothing staged. Never edit it — regenerate it:\n"
    "#     scripts/test/lane-census.sh <gate-image> --runs 2 \\\n"
    "#         --admit .config/lane-admission/gate.txt\n"
    "#\n"
    "# One name per line. `lib` is the crate's own unit tests (`--lib`); every\n"
    "# other name is a `--test` target. `test-lane-contracts` runs exactly this set,\n"
    "# and `check-lane-contracts` reads it, so a target here that resolves a fixture\n"
    "# its job does not build is still refused.\n"
)


def target_of(suite_name: str) -> str:
    # nextest suite names are `<crate>::<binary>`; the crate's lib unit tests
    # are the bare crate name, admitted as `lib` (`--lib`).
    if "::" in suite_name:
        return suite_name.split("::", 1)[1]
    return "lib" if suite_name == CRATE else suite_name


def classify(junit: str) -> dict:
    root = ET.parse(junit).getroot()
    per = collections.defaultdict(lambda: {"cases": 0, "outcome": "PASS", "why": collections.Counter()})
    for suite in root.iter("testsuite"):
        target = target_of(suite.get("name", ""))
        for case in suite.iter("testcase"):
            t = per[target]; t["cases"] += 1
            fail = case.find("failure") if case.find("failure") is not None else case.find("error")
            if fail is None:
                continue
            text = (fail.get("message") or "") + "\n" + (fail.text or "")
            so = case.find("system-out"); se = case.find("system-err")
            text += "\n" + ((so.text if so is not None else "") or "") + ((se.text if se is not None else "") or "")
            m = SKIP.search(text)
            if "timed out" in text.lower() or "TIMEOUT" in (fail.get("type") or ""):
                kind, why = "TIMEOUT", "timed out"
            elif m:
                kind, why = "SKIP", f"{m.group(1) or 'capability'}: {m.group(2).strip()[:90]}"
            elif FIXTURE.search(text):
                kind, why = "FIXTURE", (FIXTURE.search(text).group(0))
            else:
                first = next((l.strip() for l in text.splitlines() if l.strip() and "panicked" not in l), "")
                kind, why = "FAIL", first[:110]
            if RANK[kind] > RANK[t["outcome"]]:
                t["outcome"] = kind
            t["why"][f"{kind} | {why}"] += 1
    return per


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("--admit")
    ap.add_argument("--show", action="append", default=[],
                    help="also list the targets with this outcome (repeatable)")
    ap.add_argument("junits", nargs="+")
    a = ap.parse_args()

    runs = [classify(j) for j in a.junits]
    targets = set().union(*runs)
    merged, unstable = {}, []
    for t in sorted(targets):
        seen = [r[t]["outcome"] if t in r else "ABSENT" for r in runs]
        worst = max((o for o in seen if o != "ABSENT"), key=RANK.get, default="FAIL")
        why = collections.Counter()
        for r in runs:
            if t in r:
                why.update(r[t]["why"])
        merged[t] = {"outcome": worst, "per_run": seen, "why": dict(why)}
        if len(set(seen)) > 1:
            unstable.append((t, seen))

    by = collections.defaultdict(list)
    for t, v in merged.items():
        by[v["outcome"]].append(t)
    print(f"census: {len(a.junits)} run(s), {len(targets)} target(s)")
    for k in ["PASS", "SKIP", "TIMEOUT", "FIXTURE", "FAIL"]:
        print(f"  {k:8s} {len(by[k])}")
    if unstable:
        # A target whose outcome differs between runs of the SAME tree is not
        # admissible whatever its best run said — that is what the repeat is for.
        print(f"\nUNSTABLE across runs ({len(unstable)}) — never admitted:")
        for t, seen in unstable:
            print(f"  {t:44s} {' / '.join(seen)}")
    for k in ["FAIL", "TIMEOUT"] + [x for x in a.show if x not in ("FAIL", "TIMEOUT")]:
        if by[k]:
            print(f"\n== {k} ==")
            for t in by[k]:
                top = collections.Counter(merged[t]["why"]).most_common(1)
                print(f"  {t:44s} {('— ' + top[0][0]) if top else ''}"[:170])
    json.dump(merged, open(a.out, "w"), indent=1, sort_keys=True)

    if a.admit:
        admitted = sorted(by["PASS"])
        with open(a.admit, "w") as fh:
            fh.write(ADMIT_HEADER)
            for t in admitted:
                fh.write(t + "\n")
        print(f"\nadmitted {len(admitted)} target(s) -> {a.admit}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
