//! C Entry-pkg TU emitter (typed, RFC-0043 / phase-257).
//!
//! Maps a [`Plan`] (see `super::mod`) onto a generated typed `main.c`: per launch
//! node it creates a `nros_cpp_node_t` (`nros_cpp_node_create`) and calls the
//! node's `NROS_C_COMPONENT` factory/configure seam
//! (`__nros_c_component_<pkg>_{create,configure}`) on the real executor; `main`
//! drives `nros_board_native_run_components`. The C counterpart of
//! [`super::emit_cpp::emit_typed`]. The legacy non-typed emitter (the
//! `EntryNodeRuntime` interpreter via `nros_board_native_run`) was retired in
//! phase-257 Stage-3.

use std::fmt::Write;

use super::{Plan, emit_boot_config_static, sanitize_pkg};

/// Phase 257 (W0-A) — a `lang == "c"` node is a `NROS_C_COMPONENT` typed
/// component the C Entry installs via its `__nros_c_component_<pkg>_*` seam.
fn is_c_node(n: &super::PlanNode) -> bool {
    n.lang.as_deref() == Some("c")
}

/// Phase 257 (W0-A, RFC-0043) — emit the **typed** C Entry TU: route each launch
/// node to the real executor via its `NROS_C_COMPONENT` factory/configure seam,
/// driven by the C-ABI `nros_board_native_run_components`. The C counterpart of
/// [`super::emit_cpp::emit_typed`]; pure-C workspaces only (every node is a C
/// component — a non-C node has no C seam and is rejected).
pub fn emit_typed(plan: &Plan) -> Result<String, String> {
    for n in &plan.nodes {
        if !is_c_node(n) {
            return Err(format!(
                "typed C entry emit: node pkg `{}` exec `{}` is lang `{}`, not `c` — \
                 a `--lang c` typed Entry supports C components only (use `--lang cpp` for \
                 a mixed C/C++/Rust workspace)",
                n.pkg,
                n.exec,
                n.lang.as_deref().unwrap_or("<unset>")
            ));
        }
    }

    let mut out = String::new();
    let _ = writeln!(
        out,
        "/* Generated by `nros codegen entry --lang c --typed` (RFC-0043)\n\
         *   bringup = {bringup}\n\
         *   launch  = {launch}\n\
         *   board   = {board}\n\
         *\n\
         * DO NOT EDIT — regenerated at configure time. Routes each launch node\n\
         * to the real executor via its `NROS_C_COMPONENT` factory/configure seam\n\
         * (no synthesizing interpreter); `nros_board_native_run_components` owns\n\
         * init/spin/shutdown.\n\
         */",
        bringup = plan.bringup,
        launch = plan.launch_file.display(),
        board = plan.board,
    );
    out.push('\n');

    out.push_str(
        "#include <nros/boot_config.h>  /* nros_baked_boot_config + nros_boot_config_node_name */\n",
    );
    out.push_str("#include <nros/main.h>         /* nros_board_native_run_components_named */\n");
    // The cbindgen FFI header is the superset: full `nros_cpp_node_t`, `nros_cpp_node_create`,
    // and the `NROS_CPP_RET_*` codes. We do NOT include `<nros/component.h>` — it redefines
    // `struct nros_cpp_qos_t` + the `nros_cpp_*` prototypes, which collide in C (struct
    // redefinition is ill-formed). The entry only creates nodes; the component TUs own the
    // pub/sub seam.
    out.push_str("#include <nros/nros_cpp_ffi.h> /* nros_cpp_node_t + nros_cpp_node_create + ret codes */\n\n");

    // Forward-declare the C-ABI factory + configure for each unique C pkg.
    out.push_str("/* C component factory + configure seam (NROS_C_COMPONENT). The node's\n");
    out.push_str(" * `nros_cpp_node_t*` + executor handle are handed to `configure`, which\n");
    out.push_str(" * registers the component's real callbacks on the executor. */\n");
    let mut seen_pkgs: Vec<String> = Vec::new();
    for n in &plan.nodes {
        let pkg = sanitize_pkg(&n.pkg);
        if seen_pkgs.contains(&pkg) {
            continue;
        }
        let _ = writeln!(out, "extern void* __nros_c_component_{pkg}_create(void);");
        let _ = writeln!(
            out,
            "extern int32_t __nros_c_component_{pkg}_configure(const nros_cpp_node_t* node, void* executor, void* self);"
        );
        seen_pkgs.push(pkg);
    }
    out.push('\n');

    // Static per-node storage — one `nros_cpp_node_t` per launch `<node>` row.
    out.push_str("/* Static per-node storage (outlives the spin loop; no heap). */\n");
    for (i, _n) in plan.nodes.iter().enumerate() {
        let _ = writeln!(out, "static nros_cpp_node_t __nros_node_{i};");
    }
    out.push('\n');

    // setup (post-init): create each node + wire its component's real callbacks.
    out.push_str("/* setup (post-init): the executor handle is passed in; create each node +\n");
    out.push_str(" * configure its component on the real executor. */\n");
    out.push_str("static int32_t __nros_entry_setup(void* executor) {\n");
    out.push_str("    if (executor == NULL) {\n");
    out.push_str("        return (int32_t)NROS_CPP_RET_NOT_INIT;\n");
    out.push_str("    }\n");

    // Phase 269 (W4) / 272 (W2) — sched-context wiring: emit one create call per
    // resolved tier (ordered highest-priority-first), then seed the node-name →
    // sched-context table BEFORE any node is constructed. Guard on non-empty multi-tier
    // resolved table; single-tier or absent → byte-identical output.
    let use_tiers = plan
        .resolved_tiers
        .as_ref()
        .is_some_and(|t| !t.is_single_tier());
    if use_tiers {
        let tiers = plan.resolved_tiers.as_ref().unwrap();
        let n_tiers = tiers.tiers.len();
        out.push_str("    /* Phase 269 (W4) — sched-context wiring (multi-tier scheduling). */\n");
        let _ = writeln!(out, "    uint8_t __nros_sc_ids[{n_tiers}] = {{0}};");
        for (ti, tier) in tiers.tiers.iter().enumerate() {
            let period_us = tier.spin_period_us.unwrap_or(0) as u32;
            let os_pri = (tier.priority.clamp(0, 255)) as u8;
            let _ = writeln!(out, "    {{");
            out.push_str("        nros_cpp_sched_context_t __sc = {0};\n");
            out.push_str("        __sc.class_ = 0;  /* Fifo */\n");
            out.push_str("        __sc.priority = 1;  /* Normal */\n");
            out.push_str("        __sc.deadline_policy = 0;  /* Released */\n");
            let _ = writeln!(out, "        __sc.period_us = {period_us}u;");
            let _ = writeln!(out, "        __sc.os_pri = {os_pri}u;");
            let _ = writeln!(
                out,
                "        nros_cpp_ret_t __scr{ti} = nros_cpp_create_sched_context(executor, &__sc, &__nros_sc_ids[{ti}]);"
            );
            let _ = writeln!(
                out,
                "        if (__scr{ti} != NROS_CPP_RET_OK) return (int32_t)__scr{ti};"
            );
            out.push_str("    }\n");
        }
        // Phase 272 (W2) — seed the node-name → sched-context table BEFORE any node is
        // built (RFC-0047: seed before the first node_builder(name).build()).
        out.push_str(
            "    /* Phase 272 (W2) — seed node-name → sched-context table (RFC-0047). */\n",
        );
        for n in &plan.nodes {
            if let Some(sc_idx) = n.sched_context {
                let node_name = n.name.as_deref().unwrap_or(&n.exec);
                let name_lit = node_name.replace('\\', "\\\\").replace('"', "\\\"");
                let ns_lit = n
                    .namespace
                    .as_deref()
                    .unwrap_or("/")
                    .replace('\\', "\\\\")
                    .replace('"', "\\\"");
                let _ = writeln!(
                    out,
                    "    nros_cpp_bind_node_name_sched(executor, \"{name_lit}\", \"{ns_lit}\", __nros_sc_ids[{sc_idx}]);"
                );
            }
        }
        // Phase 273 (W2) — seed the group → sched-context table BEFORE any node is
        // built (RFC-0047 Precedence: group table > node-name table > default).
        // One call per resolved (component, group) member across all tiers.
        out.push_str("    /* Phase 273 (W2) — seed group → sched-context table (RFC-0047). */\n");
        // Build node-name → ns map for lookup.
        let node_ns: Vec<(String, String)> = plan
            .nodes
            .iter()
            .map(|n| {
                let name = n.name.as_deref().unwrap_or(n.exec.as_str()).to_string();
                let ns = n
                    .namespace
                    .as_deref()
                    .unwrap_or("/")
                    .replace('\\', "\\\\")
                    .replace('"', "\\\"");
                (name, ns)
            })
            .collect();
        for (ti, tier) in tiers.tiers.iter().enumerate() {
            for (node_name, group) in &tier.members {
                let name_lit = node_name.replace('\\', "\\\\").replace('"', "\\\"");
                let group_lit = group.replace('\\', "\\\\").replace('"', "\\\"");
                let ns_lit = node_ns
                    .iter()
                    .find(|(n, _)| n == node_name)
                    .map(|(_, ns)| ns.as_str())
                    .unwrap_or("/");
                let _ = writeln!(
                    out,
                    "    nros_cpp_bind_group_sched(executor, \"{name_lit}\", \"{ns_lit}\", \"{group_lit}\", __nros_sc_ids[{ti}]);"
                );
            }
        }
    }

    for (i, n) in plan.nodes.iter().enumerate() {
        let pkg = sanitize_pkg(&n.pkg);
        let node_name = n.name.as_deref().unwrap_or(&n.exec);
        let name_lit = node_name.replace('\\', "\\\\").replace('"', "\\\"");
        let _ = writeln!(out, "    {{");
        // Phase 272 (W2): always use plain nros_cpp_node_create. Tier binding is
        // resolved via the seeded name table in node_builder (Phase 272 W2); the
        // per-node sched_context_id / node_create_ex path is removed.
        let _ = writeln!(
            out,
            "        nros_cpp_ret_t nrc = nros_cpp_node_create(executor, \"{name_lit}\", \"/\", &__nros_node_{i});"
        );
        out.push_str("        if (nrc != NROS_CPP_RET_OK) return (int32_t)nrc;\n");
        let _ = writeln!(
            out,
            "        void* self = __nros_c_component_{pkg}_create();"
        );
        let _ = writeln!(
            out,
            "        int32_t crc = __nros_c_component_{pkg}_configure(&__nros_node_{i}, executor, self);"
        );
        out.push_str("        if (crc != 0) return crc;\n");
        let _ = writeln!(out, "    }}");
    }
    if plan.param_services {
        out.push_str(
            "    /* Phase 269 (W1) — param-services: register + seed launch initials. */\n",
        );
        out.push_str("    {\n");
        out.push_str(
            "        nros_cpp_ret_t ps_ret = nros_cpp_register_parameter_services(executor);\n",
        );
        out.push_str("        if (ps_ret != NROS_CPP_RET_OK) return (int32_t)ps_ret;\n");
        for n in &plan.nodes {
            for (k, v) in &n.params {
                let k_esc = k.replace('\\', "\\\\").replace('"', "\\\"");
                let v_esc = v.replace('\\', "\\\\").replace('"', "\\\"");
                let _ = writeln!(
                    out,
                    "        nros_cpp_declare_param(executor, \"{k_esc}\", \"{v_esc}\");"
                );
            }
        }
        out.push_str("    }\n");
    }
    if let Some(autostart) = &plan.lifecycle {
        // Phase 269 (W2) — lifecycle-services: register the five REP-2002 services and
        // drive the boot autostart policy. autostart_code: 0=none (register only),
        // 1=configure, 2=active (configure + activate). Runs AFTER param-services so the
        // executor is fully seeded before any transition callbacks fire.
        let autostart_code: u8 = match autostart.as_str() {
            "none" => 0,
            "configure" => 1,
            _ => 2, // "active" or any future level → fully activate
        };
        out.push_str("    /* Phase 269 (W2) — lifecycle-services: register + autostart. */\n");
        out.push_str("    {\n");
        let _ = writeln!(
            out,
            "        nros_cpp_ret_t lc_ret = nros_cpp_lifecycle_autostart(executor, {autostart_code}u);"
        );
        out.push_str("        if (lc_ret != NROS_CPP_RET_OK) return (int32_t)lc_ret;\n");
        out.push_str("    }\n");
    }
    out.push_str("    return 0;\n");
    out.push_str("}\n\n");

    // Phase 266 (W5b) — bake the boot config blob so the session name is both
    // readable by a post-link tool and passed to the runner at startup.
    emit_boot_config_static(&mut out, plan)?;
    out.push('\n');

    out.push_str("int main(int argc, char** argv) {\n");
    out.push_str("    (void)argc;\n");
    out.push_str("    (void)argv;\n");
    out.push_str(
        "    return nros_board_native_run_components_named(\
nros_boot_config_node_name(&NROS_BOOT_CONFIG), &__nros_entry_setup);\n",
    );
    out.push_str("}\n");

    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codegen::entry::PlanNode;
    use std::path::PathBuf;

    fn fixture_plan(nodes: &[(&str, &str)]) -> Plan {
        Plan {
            board: "native".into(),
            nodes: nodes
                .iter()
                .map(|(pkg, exec)| PlanNode {
                    pkg: (*pkg).into(),
                    exec: (*exec).into(),
                    name: None,
                    namespace: None,
                    class_name: None,
                    class_header: None,
                    lang: Some("c".into()),
                    shape: None,
                    host: None,
                    qos_overrides: Vec::new(),
                    params: Vec::new(),
                    callback_groups: Vec::new(),
                    sched_context: None,
                    group_tiers: std::collections::BTreeMap::new(),
                })
                .collect(),
            depfile_paths: Vec::new(),
            bringup: "demo_bringup".into(),
            launch_file: PathBuf::from("/tmp/system.launch.xml"),
            lifecycle: None,
            param_services: false,
            safety: None,
            tiers: Default::default(),
            node_overrides: Vec::new(),
            resolved_tiers: None,
        }
    }

    #[test]
    fn typed_emit_creates_node_and_configures_component() {
        let plan = fixture_plan(&[("talker_pkg", "talker")]);
        let src = emit_typed(&plan).expect("typed C emit ok");
        // factory + configure seam forward-decls.
        assert!(src.contains("extern void* __nros_c_component_talker_pkg_create(void);"));
        assert!(src.contains(
            "extern int32_t __nros_c_component_talker_pkg_configure(const nros_cpp_node_t* node, void* executor, void* self);"
        ));
        // setup creates the node + configures on the executor.
        assert!(src.contains("nros_cpp_node_create(executor, \"talker\", \"/\", &__nros_node_0)"));
        assert!(
            src.contains("__nros_c_component_talker_pkg_configure(&__nros_node_0, executor, self)")
        );
        // main drives the real-executor lifecycle via the named runner.
        assert!(src.contains("nros_board_native_run_components_named(nros_boot_config_node_name(&NROS_BOOT_CONFIG), &__nros_entry_setup)"));
        // single-node: boot config has the node name baked in.
        assert!(src.contains("NROS_BOOT_SET_NODE_NAME"));
        assert!(src.contains(".node_name  = \"talker\""));
    }

    #[test]
    fn typed_emit_preserves_launch_order() {
        let plan = fixture_plan(&[("talker_pkg", "talker"), ("listener_pkg", "listener")]);
        let src = emit_typed(&plan).expect("typed C emit ok");
        let pos_talker = src.find("__nros_c_component_talker_pkg_create").unwrap();
        let pos_listener = src.find("__nros_c_component_listener_pkg_create").unwrap();
        assert!(pos_talker < pos_listener);
    }

    #[test]
    fn typed_emit_dashed_pkg_names_sanitised() {
        let plan = fixture_plan(&[("dashy-pkg", "talker")]);
        let src = emit_typed(&plan).expect("typed C emit ok");
        assert!(src.contains("__nros_c_component_dashy_pkg_create"));
        assert!(!src.contains("dashy-pkg_create"));
    }

    #[test]
    fn typed_emit_rejects_non_c_node() {
        let mut plan = fixture_plan(&[("talker_pkg", "talker")]);
        plan.nodes[0].lang = Some("cpp".into());
        let err = emit_typed(&plan).unwrap_err();
        assert!(err.contains("not `c`"), "{err}");
        assert!(err.contains("talker_pkg"), "{err}");
    }

    #[test]
    fn typed_emit_has_required_includes() {
        let plan = fixture_plan(&[("talker_pkg", "talker")]);
        let src = emit_typed(&plan).expect("typed C emit ok");
        assert!(src.contains("#include <nros/boot_config.h>"));
        assert!(src.contains("#include <nros/main.h>"));
        assert!(src.contains("#include <nros/nros_cpp_ffi.h>"));
        assert!(!src.contains("#include <nros/component.h>"));
        assert!(src.contains("int main(int argc, char** argv)"));
    }

    #[test]
    fn typed_emit_multi_node_boot_config_unset() {
        // Multi-node entry → all-unset boot config (node name not baked).
        let plan = fixture_plan(&[("talker_pkg", "talker"), ("listener_pkg", "listener")]);
        let src = emit_typed(&plan).expect("typed C emit ok");
        assert!(src.contains("NROS_BOOT_CONFIG"));
        // Multi-node: set_flags must be 0 (not NROS_BOOT_SET_NODE_NAME).
        assert!(src.contains(".set_flags  = 0,"));
        assert!(!src.contains("NROS_BOOT_SET_NODE_NAME"));
    }

    #[test]
    fn typed_emit_param_services_block_present_when_enabled() {
        // Phase 269 W1 — when param_services is true, the post-configure block emits
        // nros_cpp_register_parameter_services + nros_cpp_declare_param per node param.
        let mut plan = fixture_plan(&[("param_talker_pkg", "param_talker")]);
        plan.param_services = true;
        plan.nodes[0].params = vec![("publish_period_ms".into(), "250".into())];
        let src = emit_typed(&plan).expect("typed C emit ok");
        assert!(src.contains("nros_cpp_register_parameter_services(executor)"));
        assert!(src.contains("nros_cpp_declare_param(executor, \"publish_period_ms\", \"250\")"));
        // must appear after the configure loop, before return 0
        let reg_at = src.find("nros_cpp_register_parameter_services").unwrap();
        let ret_at = src.rfind("return 0;").unwrap();
        assert!(reg_at < ret_at, "param block must precede return 0");
    }

    #[test]
    fn typed_emit_param_services_absent_when_disabled() {
        // Guard: non-param plans produce byte-identical output (no param block).
        let plan = fixture_plan(&[("talker_pkg", "talker")]);
        let src = emit_typed(&plan).expect("typed C emit ok");
        assert!(!src.contains("nros_cpp_register_parameter_services"));
        assert!(!src.contains("nros_cpp_declare_param"));
    }

    #[test]
    fn typed_emit_lifecycle_active_emits_autostart_block() {
        // Phase 269 W2 — lifecycle = Some("active") → nros_cpp_lifecycle_autostart(executor, 2u)
        // in the post-configure block, AFTER any param block, BEFORE return 0.
        let mut plan = fixture_plan(&[("lifecycle_talker_pkg", "lifecycle_talker")]);
        plan.lifecycle = Some("active".into());
        let src = emit_typed(&plan).expect("typed C lifecycle emit ok");
        // autostart call with code 2 (active = configure + activate)
        assert!(
            src.contains("nros_cpp_lifecycle_autostart(executor, 2u)"),
            "expected nros_cpp_lifecycle_autostart(executor, 2u) in:\n{src}"
        );
        // error-propagation guard
        assert!(src.contains("if (lc_ret != NROS_CPP_RET_OK) return (int32_t)lc_ret"));
        // AFTER configure loop (all node configure calls), BEFORE return 0
        let autostart_at = src.find("nros_cpp_lifecycle_autostart").unwrap();
        let ret_at = src.rfind("return 0;").unwrap();
        assert!(
            autostart_at < ret_at,
            "lifecycle block must precede return 0"
        );
        // configure loop precedes the lifecycle block
        let cfg_at = src
            .find("__nros_c_component_lifecycle_talker_pkg_configure")
            .unwrap();
        assert!(
            cfg_at < autostart_at,
            "lifecycle block must follow configure loop"
        );
    }

    #[test]
    fn typed_emit_lifecycle_configure_emits_code_1() {
        let mut plan = fixture_plan(&[("lc_pkg", "lc")]);
        plan.lifecycle = Some("configure".into());
        let src = emit_typed(&plan).expect("typed C lifecycle configure emit ok");
        assert!(
            src.contains("nros_cpp_lifecycle_autostart(executor, 1u)"),
            "expected autostart_code 1 for 'configure'; src:\n{src}"
        );
    }

    #[test]
    fn typed_emit_lifecycle_none_emits_code_0() {
        let mut plan = fixture_plan(&[("lc_pkg", "lc")]);
        plan.lifecycle = Some("none".into());
        let src = emit_typed(&plan).expect("typed C lifecycle none emit ok");
        assert!(
            src.contains("nros_cpp_lifecycle_autostart(executor, 0u)"),
            "expected autostart_code 0 for 'none'; src:\n{src}"
        );
    }

    #[test]
    fn typed_emit_lifecycle_absent_when_disabled() {
        // Guard: lifecycle = None → byte-identical output (no lifecycle block).
        let plan = fixture_plan(&[("talker_pkg", "talker")]);
        let src = emit_typed(&plan).expect("typed C emit ok");
        assert!(
            !src.contains("nros_cpp_lifecycle_autostart"),
            "lifecycle block must be absent when lifecycle = None"
        );
        assert!(
            !src.contains("nros_cpp_register_lifecycle_services"),
            "lifecycle block must be absent when lifecycle = None"
        );
    }

    #[test]
    fn typed_emit_lifecycle_after_param_block() {
        // Phase 269 W2 — when both param_services and lifecycle are set, the lifecycle
        // block must appear AFTER the param block (same order as the Rust macro: params → lifecycle).
        let mut plan = fixture_plan(&[("talker_pkg", "talker")]);
        plan.param_services = true;
        plan.nodes[0].params = vec![("foo".into(), "bar".into())];
        plan.lifecycle = Some("active".into());
        let src = emit_typed(&plan).expect("typed C combined emit ok");
        let param_at = src.find("nros_cpp_register_parameter_services").unwrap();
        let lc_at = src.find("nros_cpp_lifecycle_autostart").unwrap();
        assert!(
            param_at < lc_at,
            "lifecycle block must follow param-services block"
        );
    }

    // -------------------------------------------------------------------------
    // Phase 269 (W4) — sched-context wiring tests
    // -------------------------------------------------------------------------

    fn fixture_plan_with_tiers() -> Plan {
        use crate::codegen::entry::PlanNode;
        use nros_orchestration_ir::{ResolvedTier, ResolvedTierTable};
        use std::path::PathBuf;
        // Two-tier plan: high (idx 0) and low (idx 1), each with one C node.
        let high_tier = ResolvedTier {
            name: "high".into(),
            priority: 80,
            stack_bytes: None,
            spin_period_us: Some(10_000),
            preempt_threshold: None,
            sched_class: None,
            class: None,
            period_us: None,
            budget_us: None,
            deadline_us: None,
            deadline_policy: None,
            core: None,
            members: vec![("ctrl".into(), "ctrl_grp".into())],
        };
        let low_tier = ResolvedTier {
            name: "low".into(),
            priority: 10,
            stack_bytes: None,
            spin_period_us: Some(100_000),
            preempt_threshold: None,
            sched_class: None,
            class: None,
            period_us: None,
            budget_us: None,
            deadline_us: None,
            deadline_policy: None,
            core: None,
            members: vec![("telem".into(), "telem_grp".into())],
        };
        Plan {
            board: "native".into(),
            nodes: vec![
                PlanNode {
                    pkg: "ctrl_pkg".into(),
                    exec: "ctrl".into(),
                    name: Some("ctrl".into()),
                    namespace: None,
                    class_name: None,
                    class_header: None,
                    lang: Some("c".into()),
                    shape: None,
                    host: None,
                    qos_overrides: Vec::new(),
                    params: Vec::new(),
                    callback_groups: vec!["ctrl_grp".into()],
                    sched_context: Some(0), // high tier
                    group_tiers: std::collections::BTreeMap::new(),
                },
                PlanNode {
                    pkg: "telem_pkg".into(),
                    exec: "telem".into(),
                    name: Some("telem".into()),
                    namespace: None,
                    class_name: None,
                    class_header: None,
                    lang: Some("c".into()),
                    shape: None,
                    host: None,
                    qos_overrides: Vec::new(),
                    params: Vec::new(),
                    callback_groups: vec!["telem_grp".into()],
                    sched_context: Some(1), // low tier
                    group_tiers: std::collections::BTreeMap::new(),
                },
            ],
            depfile_paths: Vec::new(),
            bringup: "demo_bringup".into(),
            launch_file: PathBuf::from("/tmp/system.launch.xml"),
            lifecycle: None,
            param_services: false,
            safety: None,
            tiers: Default::default(),
            node_overrides: Vec::new(),
            resolved_tiers: Some(ResolvedTierTable {
                tiers: vec![high_tier, low_tier],
            }),
        }
    }

    #[test]
    fn typed_emit_tiers_emits_sched_context_create_and_name_seed() {
        // Phase 272 (W2) — multi-tier plan emits sched-context create + name-seed calls
        // BEFORE node construction; node_create_ex is removed (binding is via the table).
        let plan = fixture_plan_with_tiers();
        let src = emit_typed(&plan).expect("typed C tier emit ok");
        // Sched-context IDs array declared.
        assert!(
            src.contains("uint8_t __nros_sc_ids[2] = {0};"),
            "expected sc_ids array; got:\n{src}"
        );
        // High tier: os_pri=80, period_us=10000.
        assert!(src.contains("__sc.os_pri = 80u;"), "expected os_pri=80");
        assert!(
            src.contains("__sc.period_us = 10000u;"),
            "expected period_us=10000"
        );
        assert!(
            src.contains("nros_cpp_create_sched_context(executor, &__sc, &__nros_sc_ids[0])"),
            "expected tier 0 sc create"
        );
        // Low tier: os_pri=10, period_us=100000.
        assert!(src.contains("__sc.os_pri = 10u;"), "expected os_pri=10");
        assert!(
            src.contains("__sc.period_us = 100000u;"),
            "expected period_us=100000"
        );
        assert!(
            src.contains("nros_cpp_create_sched_context(executor, &__sc, &__nros_sc_ids[1])"),
            "expected tier 1 sc create"
        );
        // Phase 272 (W2): bind_node_name_sched seeds for each tiered node.
        assert!(
            src.contains(
                "nros_cpp_bind_node_name_sched(executor, \"ctrl\", \"/\", __nros_sc_ids[0])"
            ),
            "ctrl node must be seeded via bind_node_name_sched; src:\n{src}"
        );
        assert!(
            src.contains(
                "nros_cpp_bind_node_name_sched(executor, \"telem\", \"/\", __nros_sc_ids[1])"
            ),
            "telem node must be seeded via bind_node_name_sched; src:\n{src}"
        );
        // node_create_ex must NOT appear (per-shape sched binding removed).
        assert!(
            !src.contains("nros_cpp_node_create_ex"),
            "node_create_ex must not appear; tier binding is via the table; src:\n{src}"
        );
        // opts.sched_context_id must NOT appear.
        assert!(
            !src.contains("sched_context_id"),
            "sched_context_id assign must not appear; src:\n{src}"
        );
        // Plain node_create used for all nodes.
        assert!(
            src.contains("nros_cpp_node_create(executor, \"ctrl\", \"/\", &__nros_node_0)"),
            "ctrl node must use plain nros_cpp_node_create; src:\n{src}"
        );
        assert!(
            src.contains("nros_cpp_node_create(executor, \"telem\", \"/\", &__nros_node_1)"),
            "telem node must use plain nros_cpp_node_create; src:\n{src}"
        );
        // Phase 273 (W2): bind_group_sched seeds for each (node, group) tier member.
        assert!(
            src.contains(
                "nros_cpp_bind_group_sched(executor, \"ctrl\", \"/\", \"ctrl_grp\", __nros_sc_ids[0])"
            ),
            "ctrl/ctrl_grp must be seeded via bind_group_sched; src:\n{src}"
        );
        assert!(
            src.contains(
                "nros_cpp_bind_group_sched(executor, \"telem\", \"/\", \"telem_grp\", __nros_sc_ids[1])"
            ),
            "telem/telem_grp must be seeded via bind_group_sched; src:\n{src}"
        );
        // Seed calls must appear BEFORE the per-node creates (RFC-0047: seed before build).
        let seed_at = src
            .find("nros_cpp_bind_node_name_sched(executor, \"ctrl\"")
            .unwrap();
        let group_seed_at = src
            .find("nros_cpp_bind_group_sched(executor, \"ctrl\"")
            .unwrap();
        let node_at = src.find("nros_cpp_node_create(executor, \"ctrl\"").unwrap();
        assert!(
            seed_at < node_at,
            "node-name seed block must precede per-node creates"
        );
        assert!(
            group_seed_at < node_at,
            "group seed block must precede per-node creates"
        );
    }

    #[test]
    fn typed_emit_no_tiers_uses_plain_node_create() {
        // Guard: empty resolved_tiers keeps byte-identical plain create (no seed, no sched).
        let plan = fixture_plan(&[("talker_pkg", "talker")]);
        let src = emit_typed(&plan).expect("typed C no-tier emit ok");
        // Must NOT contain sched block artifacts.
        assert!(
            !src.contains("__nros_sc_ids"),
            "no-tier plan must not emit sc_ids array"
        );
        assert!(
            !src.contains("nros_cpp_create_sched_context"),
            "no-tier plan must not emit sched_context_create"
        );
        assert!(
            !src.contains("nros_cpp_bind_node_name_sched"),
            "no-tier plan must not emit bind_node_name_sched"
        );
        assert!(
            !src.contains("nros_cpp_bind_group_sched"),
            "no-tier plan must not emit bind_group_sched"
        );
        assert!(
            !src.contains("nros_cpp_node_create_ex"),
            "no-tier plan must use plain nros_cpp_node_create"
        );
        assert!(
            src.contains("nros_cpp_node_create(executor, \"talker\", \"/\", &__nros_node_0)"),
            "no-tier plan must use plain nros_cpp_node_create"
        );
    }
}
