//! Phase 219.C — C Entry-pkg TU emitter.
//!
//! Maps a [`Plan`] (see `super::mod`) onto a generated `main.c` body
//! per `docs/roadmap/archived/phase-219-cpp-entry-pkg.md` §3.3 + §3.5. Symmetric
//! to [`super::emit_cpp`] modulo C ABI: register fns return
//! `nros_ret_t` (not `int32_t`) and take `nros_node_context_t*`
//! (not `::nros::NodeContext*`), and the Board adapter is the C
//! free-fn `nros_board_native_run` instead of the templated C++
//! `::nros::board::NativeBoard::run`.
//!
//! The Phase 219.E sibling header `<nros/main.h>` exports
//! `nros_board_native_run(nros_node_register_fn entry)` (one fn-ptr,
//! no closure); the generated `main()` packs the per-Node register
//! sequence into a static fn that the adapter receives.

use std::fmt::Write;

use super::{Plan, sanitize_pkg};

/// Emit the generated C TU as a `String`.
pub fn emit(plan: &Plan) -> String {
    let mut out = String::new();
    write_header(&mut out, plan);

    out.push_str("#include <nros/main.h>\n");
    out.push_str("#include <nros/nros.h>\n");
    out.push_str("#include <nros/node_pkg.h>\n\n");

    // One register-fn forward decl per pkg, deduped.
    out.push_str("/* Phase 212.M.5.a.1 mangled register fns — one per Node pkg the\n");
    out.push_str(" * launch XML pulled in. The Entry pkg's CMakeLists.txt\n");
    out.push_str(" * (`nano_ros_entry(LAUNCH …)`) auto-links the matching\n");
    out.push_str(" * `<pkg>_<exec>_component` static libs (Phase 219.J).\n");
    out.push_str(" */\n");
    let mut seen_pkgs: Vec<String> = Vec::new();
    for n in &plan.nodes {
        let sym = format!("__nros_component_{}_register", sanitize_pkg(&n.pkg));
        if !seen_pkgs.contains(&sym) {
            let _ = writeln!(
                out,
                "extern nros_ret_t {sym}(nros_node_context_t* context);"
            );
            seen_pkgs.push(sym);
        }
    }
    out.push('\n');

    // Per-plan register driver — packed into a static fn so it
    // matches the `nros_node_register_fn` typedef (single ctx-ptr
    // arg, `nros_ret_t` return). The board entry adapter resolves the
    // ctx ptr and invokes the driver once.
    out.push_str("/* Per-plan register driver — invoked once by the Board adapter. */\n");
    out.push_str("static nros_ret_t __nros_entry_register_all(nros_node_context_t* context) {\n");
    for n in &plan.nodes {
        let sym = format!("__nros_component_{}_register", sanitize_pkg(&n.pkg));
        let _ = writeln!(out, "    {{");
        let _ = writeln!(out, "        nros_ret_t rc = {sym}(context);");
        let _ = writeln!(out, "        if (rc != NROS_RET_OK) return rc;");
        let _ = writeln!(out, "    }}");
    }
    out.push_str("    return NROS_RET_OK;\n");
    out.push_str("}\n\n");

    let board_run = board_c_entry(&plan.board);
    out.push_str("int main(int argc, char** argv) {\n");
    out.push_str("    (void)argc;\n");
    out.push_str("    (void)argv;\n");
    let _ = writeln!(out, "    return {board_run}(__nros_entry_register_all);");
    out.push_str("}\n");

    out
}

fn write_header(out: &mut String, plan: &Plan) {
    let _ = writeln!(
        out,
        "/* Generated by `nros codegen entry --lang c`\n\
         *   bringup = {bringup}\n\
         *   launch  = {launch}\n\
         *   board   = {board}\n\
         *\n\
         * DO NOT EDIT — re-run the build to regenerate. The cmake fn\n\
         * `nano_ros_entry(LAUNCH \"…\")` drives this codegen via\n\
         * `nros codegen entry --lang c` at configure time.\n\
         */",
        bringup = plan.bringup,
        launch = plan.launch_file.display(),
        board = plan.board,
    );
    out.push('\n');
}

/// Board key → C Board adapter fn name. Native is the only target the
/// C/C++ Entry-pkg surface supports today (Phase 212.L.2).
fn board_c_entry(board: &str) -> &'static str {
    match board {
        "native" | "posix" => "nros_board_native_run",
        _ => "nros_board_native_run",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codegen::entry::PlanNode;
    use std::path::PathBuf;

    fn fixture_plan(nodes: &[(&str, &str)]) -> Plan {
        Plan {
            board: "native".into(),
            nodes: nodes
                .iter()
                .map(|(pkg, exec)| PlanNode {
                    pkg: (*pkg).into(),
                    exec: (*exec).into(),
                    name: None,
                    namespace: None,
                    class_name: None,
                    class_header: None,
                    lang: None,
                    shape: None,
                })
                .collect(),
            depfile_paths: Vec::new(),
            bringup: "demo_bringup".into(),
            launch_file: PathBuf::from("/tmp/system.launch.xml"),
        }
    }

    #[test]
    fn one_node_plan_emits_extern_decl_and_call() {
        let plan = fixture_plan(&[("talker_pkg", "talker")]);
        let src = emit(&plan);
        assert!(src.contains(
            "extern nros_ret_t __nros_component_talker_pkg_register(nros_node_context_t* context);"
        ));
        assert!(src.contains("__nros_component_talker_pkg_register(context);"));
        assert!(src.contains("nros_board_native_run(__nros_entry_register_all)"));
    }

    #[test]
    fn two_node_plan_preserves_launch_order() {
        let plan = fixture_plan(&[("talker_pkg", "talker"), ("listener_pkg", "listener")]);
        let src = emit(&plan);
        let pos_talker = src
            .find("__nros_component_talker_pkg_register(context);")
            .unwrap();
        let pos_listener = src
            .find("__nros_component_listener_pkg_register(context);")
            .unwrap();
        assert!(pos_talker < pos_listener);
    }

    #[test]
    fn duplicate_pkg_decl_deduped_but_call_repeated() {
        let plan = fixture_plan(&[("twin_pkg", "a"), ("twin_pkg", "b")]);
        let src = emit(&plan);
        let decl = "extern nros_ret_t __nros_component_twin_pkg_register";
        assert_eq!(src.matches(decl).count(), 1);
        let call = "__nros_component_twin_pkg_register(context);";
        assert_eq!(src.matches(call).count(), 2);
    }

    #[test]
    fn dashed_pkg_names_are_sanitised() {
        let plan = fixture_plan(&[("dashy-pkg", "talker")]);
        let src = emit(&plan);
        assert!(src.contains("__nros_component_dashy_pkg_register"));
        assert!(!src.contains("dashy-pkg_register"));
    }

    #[test]
    fn generated_tu_has_main_and_required_includes() {
        let plan = fixture_plan(&[("talker_pkg", "talker")]);
        let src = emit(&plan);
        assert!(src.contains("#include <nros/main.h>"));
        assert!(src.contains("#include <nros/nros.h>"));
        assert!(src.contains("#include <nros/node_pkg.h>"));
        assert!(src.contains("int main(int argc, char** argv)"));
    }

    #[test]
    fn header_banner_mentions_bringup_launch_board() {
        let plan = fixture_plan(&[("talker_pkg", "talker")]);
        let src = emit(&plan);
        assert!(src.contains("bringup = demo_bringup"));
        assert!(src.contains("launch  = /tmp/system.launch.xml"));
        assert!(src.contains("board   = native"));
    }
}
