//! Phase 219.A — Rust Entry-pkg TU emitter.
//!
//! Today the canonical Rust Entry pkg is the `nros::main!()`
//! proc-macro (`packages/core/nros-macros/src/main_macro.rs`); this
//! emitter exists so the CLI verb `nros codegen entry --lang rust …`
//! can produce a standalone `main.rs` body for tooling that wants to
//! pre-bake the macro expansion (e.g. for byte-level diffs against the
//! proc-macro output, or to inspect the launch-XML resolution outside
//! a cargo build).
//!
//! The proc-macro itself remains the canonical compile-time emitter —
//! it keeps direct access to `proc_macro::Span` for diagnostics that
//! a CLI shell-out cannot match. The shared [`crate::codegen::entry`]
//! `Plan` IR makes the two paths converge on a single pkg-index +
//! launch-parse implementation.

use std::fmt::Write;

use super::{Plan, sanitize_pkg};

/// Emit a Rust `main.rs` body for the given plan.
///
/// Output mirrors the proc-macro's `OwnedSpin` framework branch (which
/// is the only branch the CLI verb dispatches today — RTIC + Embassy
/// emits stay proc-macro-only since they need `proc_macro::Span` for
/// the `custom_tasks` splice). The body installs both a hosted `fn
/// main()` and an embedded `#[unsafe(no_mangle)] extern "C" fn main()`
/// so the same TU works for native + bare-metal targets.
pub fn emit(plan: &Plan) -> String {
    let mut out = String::new();
    write_header(&mut out, plan);

    // include_bytes! tracking — same rebuild-correctness workaround
    // the proc-macro uses. Each tracked path gets one anonymous const.
    for dep in &plan.depfile_paths {
        let p = dep.display().to_string();
        // Defensive: skip non-existent paths (proc-macro does the
        // same).
        if !dep.exists() {
            continue;
        }
        let _ = writeln!(
            out,
            "const _: &[u8] = ::core::include_bytes!({});",
            quote_str(&p)
        );
    }
    out.push('\n');

    let board_path = board_path_for(&plan.board).unwrap_or("::nros_board_native::NativeBoard");

    // __nros_entry_run body — one ::<pkg>::register(runtime)?; per
    // launch-XML node, in source order.
    let mut register_calls = String::new();
    for n in &plan.nodes {
        let _ = writeln!(
            register_calls,
            "            ::{}::register(runtime)?;",
            sanitize_pkg(&n.pkg)
        );
    }

    let _ = writeln!(
        out,
        "fn __nros_entry_run() -> ::core::result::Result<\n\
         \x20   (),\n\
         \x20   ::nros::__macro_support::nros_platform::RuntimeError,\n\
         > {{\n\
         \x20   <{board_path} as ::nros::__macro_support::nros_platform::BoardEntry>::run(\n\
         \x20       |runtime: &mut ::nros::__macro_support::nros_platform::RuntimeCtx<'_>|\n\
         \x20           -> ::core::result::Result<\n\
         \x20               (),\n\
         \x20               ::nros::__macro_support::nros_platform::RuntimeError,\n\
         \x20           >\n\
         \x20   {{\n\
         {register_calls}            ::core::result::Result::Ok(())\n\
         \x20       }},\n\
         \x20   )\n\
         }}\n"
    );

    out.push_str(
        "\n#[cfg(not(target_os = \"none\"))]\n\
         fn main() {\n\
         \x20   if let ::core::result::Result::Err(e) = __nros_entry_run() {\n\
         \x20       ::std::eprintln!(\"{}: {}\", ::core::env!(\"CARGO_PKG_NAME\"), e);\n\
         \x20       ::std::process::exit(1);\n\
         \x20   }\n\
         }\n\
         \n\
         #[cfg(target_os = \"none\")]\n\
         #[unsafe(no_mangle)]\n\
         pub extern \"C\" fn main() -> i32 {\n\
         \x20   match __nros_entry_run() {\n\
         \x20       ::core::result::Result::Ok(()) => 0,\n\
         \x20       ::core::result::Result::Err(_) => 1,\n\
         \x20   }\n\
         }\n",
    );

    out
}

fn write_header(out: &mut String, plan: &Plan) {
    let _ = writeln!(
        out,
        "// Generated by `nros codegen entry --lang rust`\n\
         //   bringup = {bringup}\n\
         //   launch  = {launch}\n\
         //   board   = {board}\n\
         //\n\
         // DO NOT EDIT — re-run `cargo build` to regenerate. The Rust\n\
         // `nros::main!()` proc-macro is the canonical compile-time\n\
         // emitter; this CLI-baked form mirrors its `OwnedSpin` branch.\n",
        bringup = plan.bringup,
        launch = plan.launch_file.display(),
        board = plan.board,
    );
}

/// Board key → Rust ZST path.
///
/// Delegates to [`nros_orchestration_ir::board_path_for`], the single source
/// of truth shared with the `nros::main!()` proc-macro. Any board added to
/// the IR crate is automatically available here with no extra edit.
fn board_path_for(board: &str) -> Option<&'static str> {
    nros_orchestration_ir::board_path_for(board)
}

/// Quote a string into a valid Rust string literal (raw form when
/// possible so backslashes in path components survive on Windows
/// hosts).
fn quote_str(s: &str) -> String {
    // Pick a raw-string hash count that doesn't collide with the
    // string's own quote sequences. For paths the input is overwhelm-
    // ingly free of `"#` runs, so a single `#` works.
    let mut hashes = 1usize;
    loop {
        let needle = format!("\"{}", "#".repeat(hashes));
        if !s.contains(&needle) {
            break;
        }
        hashes += 1;
    }
    let hs = "#".repeat(hashes);
    format!("r{hs}\"{s}\"{hs}")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codegen::entry::PlanNode;
    use std::path::PathBuf;

    fn fixture_plan(nodes: &[(&str, &str)]) -> Plan {
        Plan {
            board: "native".into(),
            nodes: nodes
                .iter()
                .map(|(pkg, exec)| PlanNode {
                    pkg: (*pkg).into(),
                    exec: (*exec).into(),
                    name: None,
                    namespace: None,
                    class_name: None,
                    class_header: None,
                    lang: None,
                    shape: None,
                    host: None,
                    qos_overrides: Vec::new(),
                    params: Vec::new(),
                    callback_groups: Vec::new(),
                    sched_context: None,
                })
                .collect(),
            depfile_paths: Vec::new(),
            bringup: "demo_bringup".into(),
            launch_file: PathBuf::from("/tmp/system.launch.xml"),
            lifecycle: None,
            param_services: false,
            safety: None,
            tiers: Default::default(),
            node_overrides: Vec::new(),
            resolved_tiers: None,
        }
    }

    #[test]
    fn emit_two_node_plan_contains_register_calls() {
        let plan = fixture_plan(&[("talker_pkg", "talker"), ("listener_pkg", "listener")]);
        let src = emit(&plan);
        assert!(src.contains("::talker_pkg::register(runtime)?;"));
        assert!(src.contains("::listener_pkg::register(runtime)?;"));
        assert!(src.contains("NativeBoard"));
        // Both a hosted main and an embedded main.
        assert!(src.contains("#[cfg(not(target_os = \"none\"))]"));
        assert!(src.contains("#[cfg(target_os = \"none\")]"));
    }

    #[test]
    fn dash_pkg_names_are_sanitised() {
        let plan = fixture_plan(&[("talker-pkg", "talker")]);
        let src = emit(&plan);
        assert!(src.contains("::talker_pkg::register(runtime)?;"));
    }

    #[test]
    fn freertos_board_maps_to_correct_zst() {
        let mut plan = fixture_plan(&[("talker_pkg", "talker")]);
        plan.board = "freertos".into();
        let src = emit(&plan);
        assert!(src.contains("::nros_board_mps2_an385_freertos::Mps2An385"));
    }

    #[test]
    fn quote_str_handles_simple_paths() {
        let q = quote_str("/abs/path.xml");
        assert!(q.starts_with("r#\""));
        assert!(q.ends_with("\"#"));
        assert!(q.contains("/abs/path.xml"));
    }
}
