//! Phase 219.C — C Entry-pkg TU emitter.
//!
//! Maps a [`Plan`] (see `super::mod`) onto a generated `main.c` body
//! per `docs/roadmap/archived/phase-219-cpp-entry-pkg.md` §3.3 + §3.5. Symmetric
//! to [`super::emit_cpp`] modulo C ABI: register fns return
//! `nros_ret_t` (not `int32_t`) and take `nros_node_context_t*`
//! (not `::nros::NodeContext*`), and the Board adapter is the C
//! free-fn `nros_board_native_run` instead of the templated C++
//! `::nros::board::NativeBoard::run`.
//!
//! The Phase 219.E sibling header `<nros/main.h>` exports
//! `nros_board_native_run(nros_node_register_fn entry)` (one fn-ptr,
//! no closure); the generated `main()` packs the per-Node register
//! sequence into a static fn that the adapter receives.

use std::fmt::Write;

use super::{Plan, sanitize_pkg};

/// Phase 257 (W0-A) — a `lang == "c"` node is a `NROS_C_COMPONENT` typed
/// component the C Entry installs via its `__nros_c_component_<pkg>_*` seam.
fn is_c_node(n: &super::PlanNode) -> bool {
    n.lang.as_deref() == Some("c")
}

/// Emit the generated C TU as a `String`.
pub fn emit(plan: &Plan) -> String {
    let mut out = String::new();
    write_header(&mut out, plan);

    out.push_str("#include <nros/main.h>\n");
    out.push_str("#include <nros/nros.h>\n");
    out.push_str("#include <nros/node_pkg.h>\n\n");

    // One register-fn forward decl per pkg, deduped.
    out.push_str("/* Phase 212.M.5.a.1 mangled register fns — one per Node pkg the\n");
    out.push_str(" * launch XML pulled in. The Entry pkg's CMakeLists.txt\n");
    out.push_str(" * (`nano_ros_entry(LAUNCH …)`) auto-links the matching\n");
    out.push_str(" * `<pkg>_<exec>_component` static libs (Phase 219.J).\n");
    out.push_str(" */\n");
    let mut seen_pkgs: Vec<String> = Vec::new();
    for n in &plan.nodes {
        let sym = format!("__nros_component_{}_register", sanitize_pkg(&n.pkg));
        if !seen_pkgs.contains(&sym) {
            let _ = writeln!(
                out,
                "extern nros_ret_t {sym}(nros_node_context_t* context);"
            );
            seen_pkgs.push(sym);
        }
    }
    out.push('\n');

    // Per-plan register driver — packed into a static fn so it
    // matches the `nros_node_register_fn` typedef (single ctx-ptr
    // arg, `nros_ret_t` return). The board entry adapter resolves the
    // ctx ptr and invokes the driver once.
    out.push_str("/* Per-plan register driver — invoked once by the Board adapter. */\n");
    out.push_str("static nros_ret_t __nros_entry_register_all(nros_node_context_t* context) {\n");
    for n in &plan.nodes {
        let sym = format!("__nros_component_{}_register", sanitize_pkg(&n.pkg));
        let _ = writeln!(out, "    {{");
        let _ = writeln!(out, "        nros_ret_t rc = {sym}(context);");
        let _ = writeln!(out, "        if (rc != NROS_RET_OK) return rc;");
        let _ = writeln!(out, "    }}");
    }
    out.push_str("    return NROS_RET_OK;\n");
    out.push_str("}\n\n");

    let board_run = board_c_entry(&plan.board);
    out.push_str("int main(int argc, char** argv) {\n");
    out.push_str("    (void)argc;\n");
    out.push_str("    (void)argv;\n");
    let _ = writeln!(out, "    return {board_run}(__nros_entry_register_all);");
    out.push_str("}\n");

    out
}

/// Phase 257 (W0-A, RFC-0043) — emit the **typed** C Entry TU: route each launch
/// node to the real executor via its `NROS_C_COMPONENT` factory/configure seam,
/// driven by the C-ABI `nros_board_native_run_components`. The C counterpart of
/// [`super::emit_cpp::emit_typed`]; pure-C workspaces only (every node is a C
/// component — a non-C node has no C seam and is rejected).
pub fn emit_typed(plan: &Plan) -> Result<String, String> {
    for n in &plan.nodes {
        if !is_c_node(n) {
            return Err(format!(
                "typed C entry emit: node pkg `{}` exec `{}` is lang `{}`, not `c` — \
                 a `--lang c` typed Entry supports C components only (use `--lang cpp` for \
                 a mixed C/C++/Rust workspace)",
                n.pkg,
                n.exec,
                n.lang.as_deref().unwrap_or("<unset>")
            ));
        }
    }

    let mut out = String::new();
    let _ = writeln!(
        out,
        "/* Generated by `nros codegen entry --lang c --typed` (RFC-0043)\n\
         *   bringup = {bringup}\n\
         *   launch  = {launch}\n\
         *   board   = {board}\n\
         *\n\
         * DO NOT EDIT — regenerated at configure time. Routes each launch node\n\
         * to the real executor via its `NROS_C_COMPONENT` factory/configure seam\n\
         * (no synthesizing interpreter); `nros_board_native_run_components` owns\n\
         * init/spin/shutdown.\n\
         */",
        bringup = plan.bringup,
        launch = plan.launch_file.display(),
        board = plan.board,
    );
    out.push('\n');

    out.push_str("#include <nros/main.h>        /* nros_board_native_run_components */\n");
    // The cbindgen FFI header is the superset: full `nros_cpp_node_t`, `nros_cpp_node_create`,
    // and the `NROS_CPP_RET_*` codes. We do NOT include `<nros/component.h>` — it redefines
    // `struct nros_cpp_qos_t` + the `nros_cpp_*` prototypes, which collide in C (struct
    // redefinition is ill-formed). The entry only creates nodes; the component TUs own the
    // pub/sub seam.
    out.push_str("#include <nros/nros_cpp_ffi.h> /* nros_cpp_node_t + nros_cpp_node_create + ret codes */\n\n");

    // Forward-declare the C-ABI factory + configure for each unique C pkg.
    out.push_str("/* C component factory + configure seam (NROS_C_COMPONENT). The node's\n");
    out.push_str(" * `nros_cpp_node_t*` + executor handle are handed to `configure`, which\n");
    out.push_str(" * registers the component's real callbacks on the executor. */\n");
    let mut seen_pkgs: Vec<String> = Vec::new();
    for n in &plan.nodes {
        let pkg = sanitize_pkg(&n.pkg);
        if seen_pkgs.contains(&pkg) {
            continue;
        }
        let _ = writeln!(out, "extern void* __nros_c_component_{pkg}_create(void);");
        let _ = writeln!(
            out,
            "extern int32_t __nros_c_component_{pkg}_configure(const nros_cpp_node_t* node, void* executor, void* self);"
        );
        seen_pkgs.push(pkg);
    }
    out.push('\n');

    // Static per-node storage — one `nros_cpp_node_t` per launch `<node>` row.
    out.push_str("/* Static per-node storage (outlives the spin loop; no heap). */\n");
    for (i, _n) in plan.nodes.iter().enumerate() {
        let _ = writeln!(out, "static nros_cpp_node_t __nros_node_{i};");
    }
    out.push('\n');

    // setup (post-init): create each node + wire its component's real callbacks.
    out.push_str("/* setup (post-init): the executor handle is passed in; create each node +\n");
    out.push_str(" * configure its component on the real executor. */\n");
    out.push_str("static int32_t __nros_entry_setup(void* executor) {\n");
    out.push_str("    if (executor == NULL) {\n");
    out.push_str("        return (int32_t)NROS_CPP_RET_NOT_INIT;\n");
    out.push_str("    }\n");
    for (i, n) in plan.nodes.iter().enumerate() {
        let pkg = sanitize_pkg(&n.pkg);
        let node_name = n.name.as_deref().unwrap_or(&n.exec);
        let name_lit = node_name.replace('\\', "\\\\").replace('"', "\\\"");
        let _ = writeln!(out, "    {{");
        let _ = writeln!(
            out,
            "        nros_cpp_ret_t nrc = nros_cpp_node_create(executor, \"{name_lit}\", \"/\", &__nros_node_{i});"
        );
        out.push_str("        if (nrc != NROS_CPP_RET_OK) return (int32_t)nrc;\n");
        let _ = writeln!(
            out,
            "        void* self = __nros_c_component_{pkg}_create();"
        );
        let _ = writeln!(
            out,
            "        int32_t crc = __nros_c_component_{pkg}_configure(&__nros_node_{i}, executor, self);"
        );
        out.push_str("        if (crc != 0) return crc;\n");
        let _ = writeln!(out, "    }}");
    }
    out.push_str("    return 0;\n");
    out.push_str("}\n\n");

    out.push_str("int main(int argc, char** argv) {\n");
    out.push_str("    (void)argc;\n");
    out.push_str("    (void)argv;\n");
    out.push_str("    return nros_board_native_run_components(&__nros_entry_setup);\n");
    out.push_str("}\n");

    Ok(out)
}

fn write_header(out: &mut String, plan: &Plan) {
    let _ = writeln!(
        out,
        "/* Generated by `nros codegen entry --lang c`\n\
         *   bringup = {bringup}\n\
         *   launch  = {launch}\n\
         *   board   = {board}\n\
         *\n\
         * DO NOT EDIT — re-run the build to regenerate. The cmake fn\n\
         * `nano_ros_entry(LAUNCH \"…\")` drives this codegen via\n\
         * `nros codegen entry --lang c` at configure time.\n\
         */",
        bringup = plan.bringup,
        launch = plan.launch_file.display(),
        board = plan.board,
    );
    out.push('\n');
}

/// Board key → C Board adapter fn name. Native is the only target the
/// C/C++ Entry-pkg surface supports today (Phase 212.L.2).
fn board_c_entry(board: &str) -> &'static str {
    match board {
        "native" | "posix" => "nros_board_native_run",
        _ => "nros_board_native_run",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codegen::entry::PlanNode;
    use std::path::PathBuf;

    fn fixture_plan(nodes: &[(&str, &str)]) -> Plan {
        Plan {
            board: "native".into(),
            nodes: nodes
                .iter()
                .map(|(pkg, exec)| PlanNode {
                    pkg: (*pkg).into(),
                    exec: (*exec).into(),
                    name: None,
                    namespace: None,
                    class_name: None,
                    class_header: None,
                    lang: None,
                    shape: None,
                    host: None,
                    qos_overrides: Vec::new(),
                })
                .collect(),
            depfile_paths: Vec::new(),
            bringup: "demo_bringup".into(),
            launch_file: PathBuf::from("/tmp/system.launch.xml"),
        }
    }

    #[test]
    fn one_node_plan_emits_extern_decl_and_call() {
        let plan = fixture_plan(&[("talker_pkg", "talker")]);
        let src = emit(&plan);
        assert!(src.contains(
            "extern nros_ret_t __nros_component_talker_pkg_register(nros_node_context_t* context);"
        ));
        assert!(src.contains("__nros_component_talker_pkg_register(context);"));
        assert!(src.contains("nros_board_native_run(__nros_entry_register_all)"));
    }

    #[test]
    fn two_node_plan_preserves_launch_order() {
        let plan = fixture_plan(&[("talker_pkg", "talker"), ("listener_pkg", "listener")]);
        let src = emit(&plan);
        let pos_talker = src
            .find("__nros_component_talker_pkg_register(context);")
            .unwrap();
        let pos_listener = src
            .find("__nros_component_listener_pkg_register(context);")
            .unwrap();
        assert!(pos_talker < pos_listener);
    }

    #[test]
    fn duplicate_pkg_decl_deduped_but_call_repeated() {
        let plan = fixture_plan(&[("twin_pkg", "a"), ("twin_pkg", "b")]);
        let src = emit(&plan);
        let decl = "extern nros_ret_t __nros_component_twin_pkg_register";
        assert_eq!(src.matches(decl).count(), 1);
        let call = "__nros_component_twin_pkg_register(context);";
        assert_eq!(src.matches(call).count(), 2);
    }

    #[test]
    fn dashed_pkg_names_are_sanitised() {
        let plan = fixture_plan(&[("dashy-pkg", "talker")]);
        let src = emit(&plan);
        assert!(src.contains("__nros_component_dashy_pkg_register"));
        assert!(!src.contains("dashy-pkg_register"));
    }

    #[test]
    fn generated_tu_has_main_and_required_includes() {
        let plan = fixture_plan(&[("talker_pkg", "talker")]);
        let src = emit(&plan);
        assert!(src.contains("#include <nros/main.h>"));
        assert!(src.contains("#include <nros/nros.h>"));
        assert!(src.contains("#include <nros/node_pkg.h>"));
        assert!(src.contains("int main(int argc, char** argv)"));
    }

    #[test]
    fn header_banner_mentions_bringup_launch_board() {
        let plan = fixture_plan(&[("talker_pkg", "talker")]);
        let src = emit(&plan);
        assert!(src.contains("bringup = demo_bringup"));
        assert!(src.contains("launch  = /tmp/system.launch.xml"));
        assert!(src.contains("board   = native"));
    }
}
