meta:
  version: 1
  inputs:
  - path: /home/aeon/repos/nano-ros/examples/workspaces/ws-custom-msg-mixed/src/demo_bringup/config/system_model.record.json
    sha256: 5f63c3a68a9e23bbbd4e34801e4b3f2c8a4bdc4dd37029d9555226f1b72af5c0
  - path: /home/aeon/repos/nano-ros/examples/workspaces/ws-custom-msg-mixed/src/demo_bringup/launch/system.launch.xml
    sha256: 126b69850f9526e76e13d3c9cf911e856002fd31cedc4d070bf2d4e5b5d44751
  - path: /home/aeon/repos/nano-ros/examples/workspaces/ws-custom-msg-mixed/src/demo_bringup/system.toml
    sha256: 6e8a34ee7f631b2018cd88440aa811eb81ed482f1b11cf5c4d2ba3579a41a75d
  resolver:
    tool: play_launch
    version: 0.8.2
  record:
    path: /home/aeon/repos/nano-ros/examples/workspaces/ws-custom-msg-mixed/src/demo_bringup/config/system_model.record.json
    sha256: 5f63c3a68a9e23bbbd4e34801e4b3f2c8a4bdc4dd37029d9555226f1b72af5c0
structure:
  scopes:
    /: {}
  nodes:
    /reading_listener:
      scope: /
      pkg: reading_listener_pkg
      exec: reading_listener
    /reading_talker:
      scope: /
      pkg: reading_talker_pkg
      exec: reading_talker
execution:
  deploy:
    /reading_listener:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
    /reading_talker:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
