meta:
  version: 1
  inputs:
  - path: launch/system.launch.xml
    sha256: 6b18a20f70c6a57aa9e0546c58ebb09badfcd8d0ba1bcb89e3663d86b3cc4eba
  - path: system.toml
    sha256: 5fdcf33dab7580132123a0e1402dd507e5063618a2b46b547f41a9254e950a6f
  resolver:
    tool: ros-launch-resolve
    version: 0.1.0
structure:
  scopes:
    system.launch.xml:
      file: system.launch.xml
  nodes:
    /ctrl_node:
      scope: system.launch.xml
      pkg: ctrl_pkg
      exec: ctrl
      node_name: ctrl_node
    /telem_node:
      scope: system.launch.xml
      pkg: telem_pkg
      exec: telem
      node_name: telem_node
execution:
  deploy:
    /ctrl_node:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
    /telem_node:
      target: linux
      domain: 0
      rmw: zenoh
      extra:
        deploy_name: native
        kind: self
        target: x86_64-unknown-linux-gnu
  tiers:
    high:
      spin_period_us: 10000
      posix:
        priority: 80
      zephyr:
        priority: 5
      nuttx:
        priority: 110
    low:
      spin_period_us: 100000
      posix:
        priority: 10
      zephyr:
        priority: 10
      nuttx:
        priority: 100
  bindings:
    /ctrl_node/ctrl: high
    /telem_node/telem: low
