//! The cargo workspace root that no longer exists (RFC-0098 D9, phase-445 W5).
//!
//! ## What this module used to do
//!
//! phase-383 W3.a generated `<ws>/Cargo.toml`: a `[workspace]` listing every
//! node package and every generated entry, with an `exclude` for the west
//! entries. It sat at the workspace ROOT because cargo resolves a package's
//! workspace by walking UP and requires members to sit BELOW the root — so a
//! root under `build/` was refused (measured 2026-08-26). RFC-0065 D3 recorded
//! that as "the cargo root is `<ws>/Cargo.toml` and nowhere else".
//!
//! ## Why there is no root now
//!
//! That constraint is real only while a workspace EXISTS. With no `[workspace]`
//! anywhere, the generated entry under `build/<coord>/<entry>/` is its own cargo
//! root and reaches `src/*` as PATH dependencies, which need not sit below
//! anything (RFC-0098 D9, measured 2026-09-10). Each image then has its own
//! lock and its own settings file ([`super::cargo_config`]), and a workspace is
//! a directory of packages, as in colcon.
//!
//! ## What is left
//!
//! Roots written by the OLD builder still sit, gitignored, in every checkout
//! that ran it. A stale one is not harmless: its `[workspace]` claims the
//! generated entries below it, and cargo then refuses them with "current
//! package believes it's in a workspace when it's not". So [`retire`] deletes a
//! root carrying [`GENERATED_MARKER`] — our own build output — and REFUSES an
//! authored one rather than deleting a user's file: D9 says a workspace has no
//! root build file, and the user is the one who has to remove it.

use std::path::{Path, PathBuf};

/// The first line of a root the phase-383 builder wrote. How [`retire`] tells
/// our output from a user's file.
pub const GENERATED_MARKER: &str = "# GENERATED by `nros build`";

/// What sits at `<ws>/Cargo.toml`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RootState {
    /// No manifest, or a manifest with no `[workspace]` (a package, not a root).
    None,
    /// A root the old builder generated.
    Generated,
    /// A `[workspace]` a person wrote.
    Authored,
}

/// Classify `<root>/Cargo.toml`.
#[must_use]
pub fn state(root: &Path) -> RootState {
    let Ok(text) = std::fs::read_to_string(root.join("Cargo.toml")) else {
        return RootState::None;
    };
    if text.starts_with(GENERATED_MARKER) {
        return RootState::Generated;
    }
    let is_workspace = text
        .parse::<toml::Value>()
        .ok()
        .is_some_and(|d| d.get("workspace").is_some());
    if is_workspace {
        RootState::Authored
    } else {
        RootState::None
    }
}

/// Remove a generated workspace root (and the lock it produced); refuse an
/// authored one.
///
/// Returns the path removed, if any.
pub fn retire(root: &Path) -> Result<Option<PathBuf>, String> {
    let manifest = root.join("Cargo.toml");
    match state(root) {
        RootState::None => Ok(None),
        RootState::Generated => {
            std::fs::remove_file(&manifest)
                .map_err(|e| format!("removing the stale generated {}: {e}", manifest.display()))?;
            // The lock beside it resolved THAT root's member list, which no
            // longer exists; each entry now carries its own.
            let _ = std::fs::remove_file(root.join("Cargo.lock"));
            Ok(Some(manifest))
        }
        RootState::Authored => Err(format!(
            "{} declares a cargo `[workspace]`, and a workspace has no root build file \
             (RFC-0098 D9).\n\
             \n\
             `nros build` gives each image its own cargo root — the generated entry under \
             `build/<coord>/` — and a `[workspace]` above it claims that entry, which cargo \
             refuses (\"current package believes it's in a workspace when it's not\").\n\
             \n\
             Delete {} (and its `Cargo.lock`); the packages under `src/` need nothing else.",
            manifest.display(),
            manifest.display()
        )),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn no_manifest_is_no_root() {
        let tmp = tempfile::tempdir().unwrap();
        assert_eq!(state(tmp.path()), RootState::None);
        assert_eq!(retire(tmp.path()).unwrap(), None);
    }

    #[test]
    fn a_generated_root_is_retired_with_its_lock() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(
            tmp.path().join("Cargo.toml"),
            format!("{GENERATED_MARKER} (phase-383 W3.a) — DO NOT EDIT.\n[workspace]\n"),
        )
        .unwrap();
        std::fs::write(tmp.path().join("Cargo.lock"), "version = 4\n").unwrap();
        assert_eq!(state(tmp.path()), RootState::Generated);
        assert!(retire(tmp.path()).unwrap().is_some());
        assert!(!tmp.path().join("Cargo.toml").exists());
        assert!(!tmp.path().join("Cargo.lock").exists());
    }

    #[test]
    fn an_authored_root_is_refused_and_never_deleted() {
        let tmp = tempfile::tempdir().unwrap();
        let authored = "[workspace]\nmembers = [\"src/a\"]\n";
        std::fs::write(tmp.path().join("Cargo.toml"), authored).unwrap();
        let e = retire(tmp.path()).expect_err("refused");
        assert!(e.contains("RFC-0098 D9"), "{e}");
        assert_eq!(
            std::fs::read_to_string(tmp.path().join("Cargo.toml")).unwrap(),
            authored,
            "a user's file survives byte for byte"
        );
    }

    #[test]
    fn a_package_manifest_at_the_root_is_not_a_workspace_root() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(tmp.path().join("Cargo.toml"), "[package]\nname = \"x\"\n").unwrap();
        assert_eq!(state(tmp.path()), RootState::None);
        assert!(retire(tmp.path()).unwrap().is_none());
        assert!(tmp.path().join("Cargo.toml").exists());
    }
}
